<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thema 11 · Chi-kwadraat &amp; Simpson – Werkboek OZP 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../libs/quarto-nav/quarto-nav.js"></script>
<script src="../libs/quarto-nav/headroom.min.js"></script>
<script src="../libs/clipboard/clipboard.min.js"></script>
<script src="../libs/quarto-search/autocomplete.umd.js"></script>
<script src="../libs/quarto-search/fuse.min.js"></script>
<script src="../libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../woordenlijst.html" rel="next">
<link href="../10_power/10_power.html" rel="prev">
<script src="../libs/quarto-html/quarto.js" type="module"></script>
<script src="../libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../libs/quarto-html/popper.min.js"></script>
<script src="../libs/quarto-html/tippy.umd.min.js"></script>
<script src="../libs/quarto-html/anchor.min.js"></script>
<link href="../libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../libs/bootstrap/bootstrap.min.js"></script>
<link href="../libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../libs/bootstrap/bootstrap-a8976c3e89df70b272bdfba3d2fda974.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../common/styles/countcamp.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../11_chi_kwadraat/11_chi_kwadraat.html">Deel 6 · Categorische samenhang</a></li><li class="breadcrumb-item"><a href="../11_chi_kwadraat/11_chi_kwadraat.html">Thema 11 · Chi-kwadraat &amp; Simpson</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Schakel leesmodus">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar CountCamp</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Start</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 0 · Fundament</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../00_fundament/00_fundament.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deel 0 · Fundament</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 1 · Beschrijven</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_gemiddelde_spreiding/01_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 1 · Gemiddelde &amp; spreiding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_verdelingen_bekijken/02_verdelingen_bekijken.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 2 · Verdelingen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 2 · Standaardiseren</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03_normaalverdeling_z/03_normaalverdeling_z.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 3 · Normaalverdeling &amp; *z*-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../04_discrete_kansvariabelen/04_discrete_kansvariabelen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 4 · Discrete kansvariabelen</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 3 · Samenhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../05_correlatie/05_correlatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 5 · Correlatie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_regressie/06_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 6 · Regressie</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 4 · Steekproef → populatie</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../07_steekproevenverdeling_ci/07_steekproevenverdeling_ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 7 · Steekproevenverdeling &amp; betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 5 · Toetsen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../08_toetsgevoel_ztoets/08_toetsgevoel_ztoets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 8 · Toetsgevoel &amp; *z*-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../09_t_toets/09_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 9 · <em>t</em>-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../10_power/10_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thema 10 · Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Deel 6 · Categorische samenhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../11_chi_kwadraat/11_chi_kwadraat.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Thema 11 · Chi-kwadraat &amp; Simpson</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../woordenlijst.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Woordenlijst</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../12_tabellen/12_tabellen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bijlage · Kansverdeling-tabellen</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Op deze pagina</h2>
   
  <ul>
  <li><a href="#van-getallen-naar-categorieën" id="toc-van-getallen-naar-categorieën" class="nav-link active" data-scroll-target="#van-getallen-naar-categorieën">Van getallen naar categorieën</a></li>
  <li><a href="#chi-kwadraat-goodness-of-fit" id="toc-chi-kwadraat-goodness-of-fit" class="nav-link" data-scroll-target="#chi-kwadraat-goodness-of-fit">Chi-kwadraat goodness-of-fit</a></li>
  <li><a href="#chi-kwadraat-onafhankelijkheid-kruistabel" id="toc-chi-kwadraat-onafhankelijkheid-kruistabel" class="nav-link" data-scroll-target="#chi-kwadraat-onafhankelijkheid-kruistabel">Chi-kwadraat onafhankelijkheid (kruistabel)</a></li>
  <li><a href="#de-val-van-simpson-een-verband-dat-omkeert" id="toc-de-val-van-simpson-een-verband-dat-omkeert" class="nav-link" data-scroll-target="#de-val-van-simpson-een-verband-dat-omkeert">De val van Simpson — een verband dat omkeert</a></li>
  <li><a href="#oefenen" id="toc-oefenen" class="nav-link" data-scroll-target="#oefenen">Oefenen</a></li>
  <li><a href="#tot-slot" id="toc-tot-slot" class="nav-link" data-scroll-target="#tot-slot">Tot slot</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../11_chi_kwadraat/11_chi_kwadraat.html">Deel 6 · Categorische samenhang</a></li><li class="breadcrumb-item"><a href="../11_chi_kwadraat/11_chi_kwadraat.html">Thema 11 · Chi-kwadraat &amp; Simpson</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Thema 11 · Chi-kwadraat &amp; Simpson</h1>
<p class="subtitle lead">Deel 6 — Categorieën · <em>aantallen tellen</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="van-getallen-naar-categorieën" class="level1">
<h1>Van getallen naar categorieën</h1>
<p>Tot nu toe verdiende elke meting een getal op een schaal: pienterheid, lengte, leeftijd. Maar veel waarnemingen zijn <strong>categorisch</strong>: bruin / grijs / zwart, geslaagd / gezakt, links / midden / rechts. Daar begin je niet met gemiddelden, maar met <strong>tellen</strong>. En daar past één toetsfamilie: de <strong>chi-kwadraat</strong>.</p>
<p>Twee smaken:</p>
<ol type="1">
<li><strong>Goodness-of-fit</strong> — past mijn ene categorische variabele bij een verwachte verdeling? (Eén rij.)</li>
<li><strong>Onafhankelijkheid</strong> — hangen twee categorische variabelen samen? (Een kruistabel.)</li>
</ol>
<p>Beide draaien om hetzelfde recept: vergelijk <strong>geobserveerd</strong> met <strong>verwacht</strong> onder <span class="math inline">\(H_0\)</span>, en tel de gestandaardiseerde afwijkingen op. Het is opnieuw <strong>DATA = FIT + RESIDU</strong>: wat zien we (<span class="math inline">\(O\)</span>), wat verwacht het model (<span class="math inline">\(E\)</span>), en hoeveel blijft er over (<span class="math inline">\(O - E\)</span>)?</p>
</section>
<section id="chi-kwadraat-goodness-of-fit" class="level1">
<h1>Chi-kwadraat goodness-of-fit</h1>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="De egels — drie pelskleuren">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>De egels — drie pelskleuren
</div>
</div>
<div class="callout-body-container callout-body">
<p>Onder egels zien we drie pelskleuren: bruin, grijs en zwart. De biologen vermoeden dat ze in de natuur gelijk verdeeld zijn (1/3 elk). Wij vangen er 90 en zien: <strong>40 bruin, 30 grijs, 20 zwart</strong>. Klopt de gelijke verdeling, of niet?</p>
</div>
</div>
<p>Onder <span class="math inline">\(H_0\)</span> (gelijke verdeling) verwachten we <span class="math inline">\(90/3 = 30\)</span> egels per kleur. Bereken voor elke categorie het verschil en kwadrateer dat (we <strong>kwadrateren</strong> zodat plus- en min-afwijkingen elkaar niet wegvlakken — net als bij de blauwe vierkantjes van de variantie in thema 1), gedeeld door <span class="math inline">\(E\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">kleur</th>
<th style="text-align: center;">geobs. <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">verw. <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><span class="math inline">\(O - E\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\dfrac{O-E}{\sqrt{E}}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\dfrac{(O-E)^2}{E}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">bruin</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">+10</td>
<td style="text-align: center;"><strong>+1,83</strong></td>
<td style="text-align: center;">3,33</td>
</tr>
<tr class="even">
<td style="text-align: center;">grijs</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">zwart</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">−10</td>
<td style="text-align: center;"><strong>−1,83</strong></td>
<td style="text-align: center;">3,33</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>χ² = 6,67</strong></td>
</tr>
</tbody>
</table>
<p>Vrijheidsgraden: <span class="math inline">\(df = k - 1 = 3 - 1 = 2\)</span> — de <span class="math inline">\(df\)</span> volgt uit het <strong>aantal categorieën</strong> (<span class="math inline">\(k = 3\)</span> kleuren), niet uit het aantal egels. Kritieke waarde <span class="math inline">\(\chi^2_{.05, df=2} = 5{,}99\)</span> (uit de tabel). Onze 6,67 is groter → <strong>verwerp de nulhypothese</strong>: de pelskleuren zijn níét gelijk verdeeld.</p>
<p>Maar <span class="math inline">\(\chi^2\)</span> zelf zegt alleen <em>dát</em> het patroon afwijkt — de <strong>cellen</strong> vertellen <em>waar</em>. Daarvoor lees je de <strong>ruwe celresiduen</strong> <span class="math inline">\(\dfrac{O-E}{\sqrt{E}}\)</span> (de vierde kolom): bruin zit <strong>+1,83</strong> boven verwachting, zwart <strong>−1,83</strong> eronder, grijs precies goed. Een residu voorbij ongeveer ±2 is een opvallende cel — al is dat een <em>ruwe</em> vuistregel; hoe je een cel écht standaardiseert (en waarom <span class="math inline">\(\sqrt{E}\)</span> daarvoor te grof is) zie je zo bij de kruistabel. En kwadrateer je zo’n residu, dan krijg je exact die cel z’n <strong>bijdrage aan <span class="math inline">\(\chi^2\)</span></strong> (<span class="math inline">\(1{,}83^2 \approx 3{,}33\)</span>) — samen weer 6,67. Zo zie je niet alleen of het afwijkt, maar welke kleur het verschil maakt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-gof" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gof-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11_chi_kwadraat_files/figure-html/fig-gof-1.png" class="img-fluid figure-img" width="537">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gof-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;1: Geobserveerd (blauw) vs verwacht onder gelijke verdeling (grijze stippellijn op 30). Bruin zit boven het verwachte, zwart eronder; samen levert dat een chi-kwadraat van 6,67.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../common/img/engine/kaart_chikwadraat.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>De chi-kwadraat-engine gaat maar één kant op: <span class="math inline">\(\chi^2 \to p\)</span>, en je leest áltijd de <strong>rechterstaart</strong>. Je telt de cel-bijdragen <span class="math inline">\((O-E)^2/E\)</span> op tot één <span class="math inline">\(\chi^2\)</span>, en zoekt de kans op “dit of nog schever” in de <span class="math inline">\(\chi^2\)</span>-tabel (bij <span class="math inline">\(df = k-1\)</span>). Groot <span class="math inline">\(\chi^2\)</span> → klein staartje → verwerpen. En let op: <span class="math inline">\(\chi^2\)</span> ként geen richting — een cel té hoog of té laag telt allebei mee, want alles wordt gekwadrateerd. Die twee kanten zitten dus al in dat ene kwadraat: daarom één rechterstaart en <strong>nooit Pippi</strong> (de ×2 is al voor je gedaan).</figcaption>
</figure>
</div>
<div class="formule callout callout-style-default callout-note no-icon callout-titled" title="Chi-kwadraat-toetsingsgrootheid">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Chi-kwadraat-toetsingsgrootheid
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\chi^2 = \sum \frac{(O-E)^2}{E}\]</span></p>
<hr>
<ul>
<li><span class="math inline">\(\chi^2\)</span> — de toetsingsgrootheid: hoe sterk het geobserveerde van het verwachte afwijkt</li>
<li><span class="math inline">\(O\)</span> — het <strong>geobserveerde</strong> aantal in een cel (wat je telt)</li>
<li><span class="math inline">\(E\)</span> — het <strong>verwachte</strong> aantal in die cel onder <span class="math inline">\(H_0\)</span></li>
<li><span class="math inline">\((O-E)^2\)</span> — de afwijking per cel, gekwadrateerd (zodat plus en min niet wegvallen)</li>
<li>delen door <span class="math inline">\(E\)</span> — zodat een grote cel niet vanzelf zwaarder meetelt</li>
<li><span class="math inline">\(\sum\)</span> — tel op over <strong>álle</strong> cellen</li>
</ul>
<p><strong>Vrijheidsgraden</strong> — uit het aantal categorieën: goodness-of-fit <span class="math inline">\(df = k-1\)</span> (<span class="math inline">\(k\)</span> = aantal categorieën); kruistabel <span class="math inline">\(df = (r-1)(c-1)\)</span> (<span class="math inline">\(r\)</span> rijen, <span class="math inline">\(c\)</span> kolommen).</p>
<p><strong>Wanneer:</strong> categorische data — geobserveerde tegen verwachte aantallen onder <span class="math inline">\(H_0\)</span>.</p>
</div>
</div>
</section>
<section id="chi-kwadraat-onafhankelijkheid-kruistabel" class="level1">
<h1>Chi-kwadraat onafhankelijkheid (kruistabel)</h1>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Roken × geslacht — een vermoeden dat iedereen al heeft">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Roken × geslacht — een vermoeden dat iedereen al heeft
</div>
</div>
<div class="callout-body-container callout-body">
<p>We vragen 400 mensen of ze roken, en noteren hun geslacht. Hier heeft iedereen al een onderbuikgevoel bij: roken mannen vaker? Vraag: hangt roken samen met geslacht?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">rookt</th>
<th style="text-align: center;">rookt niet</th>
<th style="text-align: center;">rij-totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">mannen</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">200</td>
</tr>
<tr class="even">
<td style="text-align: center;">vrouwen</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">200</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>kolom-totaal</strong></td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">340</td>
<td style="text-align: center;">400</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Voel eerst wat “verwacht” betekent.</strong> In het algemeen rookt 60 van de 400 — <strong>15%</strong> (iedereen die binnen kan wandelen én rookt). Stel nu dat roken en geslacht <strong>onafhankelijk</strong> zijn, dat het één niks met het ander te maken heeft: dan zou je verwachten dat in élke groep gewoon diezelfde 15% rookt. Je past die kans niet aan omdat er toevallig een man of een vrouw komt binnenwandelen. 200 mannen → je verwacht <span class="math inline">\({,}15 \cdot 200 = 30\)</span> rokers. Maar er roken er <strong>40</strong>. Méér dan verwacht — precies wat je onderbuik al fluisterde. En bij de vrouwen andersom: verwacht 30, geobserveerd 20, minder. Juist in dat gat tussen <em>verwacht</em> en <em>geobserveerd</em> zit het verhaal — en daar mag je van schrikken. Die verwachte aantallen zijn het meest informatief: heb je ze eenmaal, dan vertelt de rest zich vanzelf.</p>
<p>Het rekenen zelf is een <strong>beweging</strong>, geen formule om te stampen. Voor een cel: kijk naar zijn <strong>rijtotaal</strong> (opzij) en zijn <strong>kolomtotaal</strong> (omlaag), vermenigvuldig die twee, en deel door <span class="math inline">\(N\)</span>. <em>Cel → rij → kolom → delen door <span class="math inline">\(N\)</span>.</em></p>
<ul>
<li><span class="math inline">\(E\)</span>(man, rookt) <span class="math inline">\(= \dfrac{200 \cdot 60}{400} = 30\)</span> — precies die 15% van zojuist</li>
<li><span class="math inline">\(E\)</span>(vrouw, rookt) <span class="math inline">\(= \dfrac{200 \cdot 60}{400} = 30\)</span></li>
<li><span class="math inline">\(E\)</span>(man, niet) <span class="math inline">\(= \dfrac{200 \cdot 340}{400} = 170\)</span>, <span class="math inline">\(E\)</span>(vrouw, niet) <span class="math inline">\(= 170\)</span></li>
</ul>
<div class="formule callout callout-style-default callout-note no-icon callout-titled" title="Verwachte celwaarde (onder onafhankelijkheid)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Verwachte celwaarde (onder onafhankelijkheid)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[E = \frac{\text{rijtotaal} \times \text{kolomtotaal}}{N}\]</span></p>
<hr>
<ul>
<li><span class="math inline">\(E\)</span> — het <strong>verwachte</strong> aantal in een cel áls de twee variabelen onafhankelijk zijn</li>
<li>rijtotaal — het totaal van de rij waarin de cel ligt (kijk opzij)</li>
<li>kolomtotaal — het totaal van de kolom waarin de cel ligt (kijk omlaag)</li>
<li><span class="math inline">\(N\)</span> — het totale aantal waarnemingen</li>
<li>de <strong>beweging</strong>: cel → rijtotaal → kolomtotaal → delen door <span class="math inline">\(N\)</span></li>
</ul>
<p><strong>Wanneer:</strong> bij een kruistabel — je hebt <span class="math inline">\(E\)</span> per cel nodig vóór je <span class="math inline">\(\chi^2\)</span> kunt berekenen.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Percentage, proportie, kans — en twee routes naar het verwachte aantal">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Percentage, proportie, kans — en twee routes naar het verwachte aantal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eén ding, drie jasjes. Die 15% rokers is hetzelfde als de <strong>proportie</strong> <span class="math inline">\({,}15\)</span>, en dat is weer hetzelfde als de <strong>kans</strong> dat een willekeurige bezoeker rookt. Een percentage is gewoon een proportie maal honderd: <span class="math inline">\({,}15 \to 15\%\)</span> (keer 100), <span class="math inline">\(15\% \to {,}15\)</span> (deel door 100). Proportie en kans zijn één pot nat — allebei een getal tussen 0 en 1.</p>
<p>Daarom zijn er <strong>twee routes</strong> naar precies hetzelfde verwachte aantal:</p>
<ul>
<li><strong>Korte route (de formule):</strong> <span class="math inline">\(E = \dfrac{\text{rijtotaal} \times \text{kolomtotaal}}{N} = \dfrac{60 \times 200}{400} = 30\)</span>.</li>
<li><strong>Lange route (via de proportie):</strong> bepaal eerst de proportie rokers over iederéén — <span class="math inline">\(\text{rijtotaal}/N = 60/400 = {,}15\)</span> (= 15%) — en leg die over het kolomtotaal: <span class="math inline">\({,}15 \times 200 = 30\)</span>.</li>
</ul>
<p>Ze geven hetzelfde, want <span class="math inline">\(\dfrac{\text{rij}}{N} \times \text{kolom} = \dfrac{\text{rij} \times \text{kolom}}{N}\)</span>. De lange route laat alleen zien wáár de formule vandaan komt: onder <span class="math inline">\(H_0\)</span> rookt in élke groep diezelfde 15%.</p>
<p><strong>De val</strong> (waar veel mensen op stuk lopen): die <span class="math inline">\({,}15\)</span> is een <strong>proportie</strong> (15%), nog géén <strong>aantal</strong>. Het verwachte <em>aantal</em> krijg je pas ná het vermenigvuldigen met het kolomtotaal. Verwar die twee niet — en onthoud: een rijtotaal krijg je door de cellen op te <strong>tellen</strong> (<span class="math inline">\(40 + 20 = 60\)</span>), niet te vermenigvuldigen.</p>
</div>
</div>
<p>Vervolgens <span class="math inline">\(\sum (O-E)^2/E\)</span> over alle vier de cellen:</p>
<p><span class="math display">\[\chi^2 = \frac{(40-30)^2}{30} + \frac{(20-30)^2}{30} + \frac{(160-170)^2}{170} + \frac{(180-170)^2}{170}\]</span> <span class="math display">\[= 3{,}33 + 3{,}33 + 0{,}59 + 0{,}59 = 7{,}84\]</span></p>
<p>Ook hier volgt <span class="math inline">\(df\)</span> uit het <strong>aantal categorieën</strong> — nu in twee richtingen: het aantal <strong>rijen</strong> en het aantal <strong>kolommen</strong>. Voor een kruistabel met <span class="math inline">\(r\)</span> rijen en <span class="math inline">\(c\)</span> kolommen: <span class="math inline">\(df = (r-1)(c-1)\)</span>. Hier een <span class="math inline">\(2 \times 2\)</span>-tabel, dus <span class="math inline">\(df = 1 \cdot 1 = 1\)</span>. (Intuïtie: liggen de rij- en kolomtotalen vast, dan kun je nog <span class="math inline">\((r-1)(c-1)\)</span> cellen vrij invullen; de rest volgt dwingend.) Kritieke waarde <span class="math inline">\(\chi^2_{.05, df=1} = 3{,}84\)</span>. Onze 7,84 is groter → <strong>verwerp de nulhypothese</strong>: roken hangt samen met geslacht — mannen roken vaker dan je onder onafhankelijkheid zou verwachten, precies wat iedereen al dacht.</p>
<p>Welke cel drijft dat? Weer de <strong>ruwe celresiduen</strong> <span class="math inline">\(\dfrac{O-E}{\sqrt{E}}\)</span>: de twee <strong>rookt</strong>-cellen springen eruit (<span class="math inline">\(\pm 1{,}83\)</span>: <span class="math inline">\(\tfrac{40-30}{\sqrt{30}} = +1{,}83\)</span> bij mannen, <span class="math inline">\(-1{,}83\)</span> bij vrouwen), terwijl de niet-rokers veel kleiner zijn (<span class="math inline">\(\pm 0{,}77\)</span>). Daar — bij wie wél rookt — wijkt de werkelijkheid het sterkst van onafhankelijkheid af.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Ruw is ruk — ook bij residuen (waarom √E te kort door de bocht is)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ruw is ruk — ook bij residuen (waarom √E te kort door de bocht is)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die <span class="math inline">\(\dfrac{O-E}{\sqrt{E}}\)</span> is een <strong>ruwe</strong> residu. Mooi, want z’n kwadraat is precies de celbijdrage aan <span class="math inline">\(\chi^2\)</span> — maar hij heeft één vervelende eigenschap: zijn standaarddeviatie is <strong>niet</strong> 1. En je weet het inmiddels: ruw is ruk. Wil je ’m tegen <span class="math inline">\(\pm 1{,}96\)</span> leggen (de <span class="math inline">\(z\)</span> uit thema 3), dan moet hij éérst écht gestandaardiseerd worden.</p>
<p>Waarom is <span class="math inline">\(\sqrt{E}\)</span> te groot? <span class="math inline">\(\sqrt{E}\)</span> is de spreiding van een <strong>vrije</strong> cel — een telling die los mag fluctueren (variantie = gemiddelde = <span class="math inline">\(E\)</span>, zoals bij een vrij oplopende telling). Maar jouw cel is niet vrij. Hij hangt vast aan zijn <strong>rijtotaal</strong> en zijn <strong>kolomtotaal</strong>: die liggen vast, en dat bindt de cel. Een gebonden cel kan minder ver afdwalen dan een vrije, dus zijn echte spreiding is <em>kleiner</em> dan <span class="math inline">\(\sqrt{E}\)</span>. Deel je alleen door <span class="math inline">\(\sqrt{E}\)</span>, dan deel je door te véél → je residu wordt te klein → je bent te voorzichtig en mist échte uitschieters.</p>
<p>De <strong>gestandaardiseerde celresidu</strong> corrigeert dat: hij deelt óók door de bindingsfactor <span class="math inline">\(\sqrt{(1-\text{rij}/n)(1-\text{kol}/n)}\)</span>. Pas díé mag je als een gewone <span class="math inline">\(z\)</span> aflezen.</p>
<p><strong>Op de rokers.</strong> De man-rookt-cel: ruw <span class="math inline">\(\dfrac{40-30}{\sqrt{30}} = 1{,}83\)</span> — netjes ónder ±2, je zou ’m bijna laten lopen. Maar de bindingsfactor is <span class="math inline">\(\sqrt{\left(1-\tfrac{200}{400}\right)\left(1-\tfrac{60}{400}\right)} = \sqrt{0{,}5 \cdot 0{,}85} = 0{,}65\)</span>, en dus: <span class="math display">\[\text{gestd. celresidu} = \frac{1{,}83}{0{,}65} = 2{,}80.\]</span> Voorbij ±2 — wél een uitschieter. De ruwe versie had je ’m bijna laten missen.</p>
<p>En de cirkel sluit: weet je nog dat bij een <span class="math inline">\(2\times2\)</span>-tabel <span class="math inline">\(\chi^2 = z^2\)</span>? Dáár is die <span class="math inline">\(z\)</span>. <span class="math inline">\(\sqrt{7{,}84} = 2{,}80\)</span>, en <span class="math inline">\(2{,}80^2 = 7{,}84\)</span>. Rond. De ruwe 1,83 was alleen de cel z’n <em>hapje</em> van <span class="math inline">\(\chi^2\)</span>; de gestandaardiseerde 2,80 ís de hele <span class="math inline">\(z\)</span>.</p>
</div>
</div>
<div class="formule callout callout-style-default callout-note no-icon callout-titled" title="Gestandaardiseerde celresidu (adjusted standardized residual)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Gestandaardiseerde celresidu (adjusted standardized residual)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\text{gestd. celresidu} = \frac{O-E}{\sqrt{E \left(1 - \dfrac{\text{rijtotaal}}{n}\right)\left(1 - \dfrac{\text{kolomtotaal}}{n}\right)}}\]</span></p>
<hr>
<ul>
<li><span class="math inline">\(O\)</span> — het <strong>geobserveerde</strong> aantal in de cel</li>
<li><span class="math inline">\(E\)</span> — het <strong>verwachte</strong> aantal in die cel onder <span class="math inline">\(H_0\)</span> (onafhankelijkheid)</li>
<li>rijtotaal, kolomtotaal — de totalen van de rij en de kolom waarin de cel ligt</li>
<li><span class="math inline">\(n\)</span> — het totale aantal waarnemingen</li>
<li>de noemer — de <strong>echte</strong> standaarddeviatie van <span class="math inline">\(O-E\)</span>: <span class="math inline">\(\sqrt{E}\)</span>, gecorrigeerd voor de binding aan de marges (altijd kleiner dan <span class="math inline">\(\sqrt{E}\)</span>, dus de residu wordt <em>groter</em>)</li>
</ul>
<p><strong>Wanneer:</strong> als je een afzonderlijke cel wilt toetsen — voorbij <span class="math inline">\(\pm 1{,}96\)</span> is die cel significant (tweezijdig, <span class="math inline">\(\alpha = .05\)</span>). Het <em>ruwe</em> <span class="math inline">\(\dfrac{O-E}{\sqrt{E}}\)</span> gebruik je alleen voor de celbijdrage aan <span class="math inline">\(\chi^2\)</span>, niet om tegen <span class="math inline">\(z\)</span> te leggen.</p>
</div>
</div>
<p>Eén waarschuwing: <span class="math inline">\(\chi^2\)</span> wordt vanzelf groter bij een grotere steekproef. Een hoge <span class="math inline">\(\chi^2\)</span> betekent dus <em>significant</em>, niet automatisch <em>een sterk verband</em> — maten voor de <strong>sterkte</strong> (zoals Cramérs V) leer je later.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Is chi-kwadraat één- of tweezijdig? (richtingloos)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Is chi-kwadraat één- of tweezijdig? (richtingloos)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Strikvraag. <span class="math inline">\(\chi^2\)</span> kent <strong>geen richting</strong>: door het kwadrateren telt elke afwijking — een cel té hoog of té laag — even hard mee. De toets vraagt niet “hoger of lager?” maar “wijkt het af, hoe dan ook?”. In die zin is <span class="math inline">\(\chi^2\)</span> <strong>stiekem tweezijdig</strong> (bij meer dan twee categorieën eigenlijk: <em>alle</em> kanten tegelijk).</p>
<p>Maar juist omdat beide kanten al in dat kwadraat zitten, lees je <strong>één</strong> staart (de rechter) en doe je <strong>nooit ×2</strong> — de “keer 2” van een tweezijdige <em>z</em>-toets is hier al gedaan door het kwadrateren.</p>
<p>Mooiste bewijs: bij deze <span class="math inline">\(2 \times 2\)</span>-tabel (<span class="math inline">\(df = 1\)</span>) is het <em>létterlijk</em> tweezijdig. Daar geldt <span class="math inline">\(\chi^2 = z^2\)</span>, en de rechterstaart-kans van <span class="math inline">\(\chi^2\)</span> is exact de <strong>tweezijdige</strong> <span class="math inline">\(p\)</span> van die <span class="math inline">\(z\)</span>. De ×2 zit er dus echt al in.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rookt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rookt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11_chi_kwadraat_files/figure-html/fig-rookt-1.png" class="img-fluid figure-img" width="537">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rookt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;2: Aantal rokers per geslacht (blauw) tegen het verwachte aantal onder onafhankelijkheid (grijze stippellijn op 30). Mannen zitten erboven (40), vrouwen eronder (20) — juist dát gat tussen verwacht en geobserveerd pikt de chi-kwadraat op.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Het stappenplan voor een chi-kwadraat">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Het stappenplan voor een chi-kwadraat
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>OV: hangen twee variabelen samen? (Of, bij GOF: past de verdeling van één variabele bij wat we verwachten?)</li>
<li><span class="math inline">\(H_0\)</span>: onafhankelijkheid (of: past bij verwachte verdeling). <span class="math inline">\(H_1\)</span>: hangt samen (of: wijkt af).</li>
<li>Toetskeuze: chi-kwadraat (onafhankelijkheid of goodness-of-fit).</li>
<li>Onder <span class="math inline">\(H_0\)</span>: bereken de verwachte aantallen per cel.</li>
<li>Toetsingsgrootheid: <span class="math inline">\(\chi^2 = \sum (O-E)^2/E\)</span>.</li>
<li>df = <span class="math inline">\((r-1)(c-1)\)</span> voor kruistabel (<span class="math inline">\(r\)</span> rijen, <span class="math inline">\(c\)</span> kolommen); <span class="math inline">\(k-1\)</span> voor goodness-of-fit (<span class="math inline">\(k\)</span> categorieën).</li>
<li>Vergelijk met <span class="math inline">\(\chi^2_{\alpha, df}\)</span> in de tabel.</li>
<li>Conclusie: <em>de samenhang tussen X en Y</em> — zeg wélk verband (richting en welke cellen beoordeel je uit de tabel en de residuen, niet uit <span class="math inline">\(\chi^2\)</span> zelf).</li>
</ol>
</div>
</div>
<div class="spss-syntax callout callout-style-default callout-note no-icon callout-titled" title="In SPSS — klikpad">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS — klikpad
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Data om mee te spelen:</strong> <a href="../common/data/roken_geslacht.sav"><code>roken_geslacht.sav</code></a> en <a href="../common/data/egel_pelskleur.sav"><code>egel_pelskleur.sav</code></a> — of de <a href="../common/data/ozp1_spss_data.zip">hele zip</a>. Met de hand snap je nu wat er gebeurt; in SPSS doe je dezelfde toets met twee categorische variabelen.</p>
<p><strong>Analyze → Descriptive Statistics → Crosstabs</strong> → één variabele naar <em>Row(s)</em>, de andere naar <em>Column(s)</em> → <em>Statistics… → Chi-square</em> aanvinken → <em>Continue → OK</em>.</p>
<p>Je leest de toets af in de regel <em>Pearson Chi-Square</em>: de waarde van <span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(df\)</span> en de bijbehorende kans (<em>Asymptotic Significance</em>).</p>
</div>
</div>
</div>
</section>
<section id="de-val-van-simpson-een-verband-dat-omkeert" class="level1">
<h1>De val van Simpson — een verband dat omkeert</h1>
<p>Alles wat we sinds correlatie (thema 5) doen heeft één gevaar: een globaal verband kan subgroepen verbergen. Een kruistabel laat het <em>globale</em> plaatje zien. Maar soms verbergt dat plaatje een <strong>omgekeerd</strong> verband dat binnen subgroepen leeft. Dat is <strong>Simpson’s paradox</strong>, en je moet ’m kennen — anders trek je serieus de verkeerde conclusie.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Twee opleidingen, één raar plaatje">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Twee opleidingen, één raar plaatje
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een universiteit kijkt naar de slaagpercentages van jongens en meisjes bij twee opleidingen.</p>
<p><strong>Opleiding A (makkelijk):</strong> jongens 480/800 = 60% geslaagd; meisjes 140/200 = <strong>70%</strong> geslaagd. → meisjes scoren beter.</p>
<p><strong>Opleiding B (moeilijk):</strong> jongens 40/200 = 20% geslaagd; meisjes 200/800 = <strong>25%</strong> geslaagd. → meisjes scoren beter.</p>
<p><strong>Totaal:</strong> jongens 520/1000 = <strong>52%</strong>; meisjes 340/1000 = <strong>34%</strong>. → jongens scoren beter ?!</p>
</div>
</div>
<p>Binnen elke opleiding doen meisjes het beter; maar in het totaal lijken jongens beter. Hoe kan dat? <strong>Doordat de groepen zich anders verdelen over de opleidingen.</strong> Veel meisjes deden de moeilijke opleiding (waar iederéén slechter scoort), en veel jongens de makkelijke. Dat trekt het meisjes-gemiddelde naar beneden en het jongens-gemiddelde omhoog.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-simpson" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simpson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11_chi_kwadraat_files/figure-html/fig-simpson-1.png" class="img-fluid figure-img" width="614">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simpson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figuur&nbsp;3: Simpson-paradox visueel. Per opleiding (A makkelijk, B moeilijk) scoren meisjes hoger dan jongens. Maar in het totaal scoren jongens hoger — omdat ze relatief veel in de makkelijke opleiding zaten en meisjes in de moeilijke. De aggregatie verbergt de échte richting.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Les uit Simpson">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Belangrijk</span>Les uit Simpson
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een <strong>derde variabele</strong> (hier: opleiding) die met beide andere samenhangt, kan een verband doen kantelen. <em>Aggregeer dus nooit zonder na te denken</em>: kijk altijd binnen relevante subgroepen. Dit is ook precies wat een covariaat doet in latere analyses — controleren voor zo’n meelopende variabele.</p>
</div>
</div>
</section>
<section id="oefenen" class="level1">
<h1>Oefenen</h1>
<div class="opgave callout callout-style-default callout-note no-icon callout-titled" title="T11.1 — Chi-kwadraat met de hand">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>T11.1 — Chi-kwadraat met de hand
</div>
</div>
<div class="callout-body-container callout-body">
<p>Honderd egels worden in drie hokken gezet (links / midden / rechts). Onder <span class="math inline">\(H_0\)</span> verwachten we gelijke voorkeur. Telling: links 25, midden 50, rechts 25.</p>
<ol type="a">
<li><p>Bereken <span class="math inline">\(\chi^2\)</span>.</p></li>
<li><p>Met <span class="math inline">\(df = 2\)</span> en <span class="math inline">\(\chi^2_{.05} = 5{,}99\)</span> — verwerpen?</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Antwoord T11.1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord T11.1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(E = 100/3 \approx 33{,}33\)</span> per hok. Per hok <span class="math inline">\((O-E)^2/E\)</span>:</p>
<ul>
<li>links: <span class="math inline">\((25-33{,}33)^2/33{,}33 = 2{,}08\)</span></li>
<li>midden: <span class="math inline">\((50-33{,}33)^2/33{,}33 = 8{,}33\)</span></li>
<li>rechts: idem links <span class="math inline">\(= 2{,}08\)</span></li>
</ul>
<p><span class="math inline">\(\chi^2 = 2{,}08 + 8{,}33 + 2{,}08 = 12{,}5\)</span>.</p>
<p><strong>(b)</strong> <span class="math inline">\(12{,}5 &gt; 5{,}99\)</span> → verwerpen. De egels hebben een sterke voorkeur voor het middelste hok.</p>
</div>
</div>
</div>
<div class="spss-syntax callout callout-style-default callout-note no-icon callout-titled" title="T11.1 in SPSS — goodness-of-fit">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>T11.1 in SPSS — goodness-of-fit
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Data:</strong> <a href="../common/data/egel_hok.sav"><code>egel_hok.sav</code></a> — 100 egels, één kolom <code>hok</code> (1 = links, 2 = midden, 3 = rechts; links 25, midden 50, rechts 25).</p>
<p>Dit is een <strong>goodness-of-fit</strong> (één variabele tegen een verwachte verdeling), dus <em>niet</em> Crosstabs maar: <strong>Analyze → Nonparametric Tests → Legacy Dialogs → Chi-square</strong> → zet <code>hok</code> bij <em>Test Variable List</em> → onder <em>Expected Values</em> staat <em>All categories equal</em> (de gelijke verdeling uit <span class="math inline">\(H_0\)</span>) → <em>OK</em>.</p>
<p>Aflezen: <em>Chi-Square</em> = 12,50, <em>df</em> = 2, <em>Asymp. Sig.</em> = ,002 — exact je handwerk (<span class="math inline">\(\chi^2 = 12{,}5\)</span>), en ruim onder .05, dus verwerpen. (De data staat hier al uitgeklapt — 1 rij per egel — zodat je niets hoeft te wegen. Had je een teltabel met 3 rijen, dan eerst <strong>Data → Weight Cases</strong> op de aantallen-kolom.)</p>
</div>
</div>
</div>
<div class="opgave callout callout-style-default callout-note no-icon callout-titled" title="T11.2 — Simpson herkennen">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>T11.2 — Simpson herkennen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een schoolinspecteur bekijkt twee scholen op één-jaars-doorstroom. School X: 80%. School Y: 65%. School X lijkt beter. Maar binnen elke leerlingcategorie (laag / hoog vooropleidingsniveau) doet School Y het juist iets <em>beter</em>. Hoe kan dat?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Antwoord T11.2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord T11.2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>School X heeft waarschijnlijk veel meer leerlingen met een hoog vooropleidingsniveau (die sowieso vaker doorstromen, op elke school). Het aggregaatcijfer reflecteert dus vooral de samenstelling van de leerlingen, niet de kwaliteit van de school. Net als bij Simpson: een meelopende derde variabele (vooropleiding) verklaart het schijnverschil. Wie scholen eerlijk wil vergelijken, vergelijkt binnen vooropleidingsniveau — niet over de hoofden heen.</p>
</div>
</div>
</div>
<div class="opgave callout callout-style-default callout-note no-icon callout-titled" title="T11.3 — Van percentage naar verwacht aantal">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>T11.3 — Van percentage naar verwacht aantal
</div>
</div>
<div class="callout-body-container callout-body">
<p>In het bos is aan 300 dieren gevraagd of ze bang zijn voor onweer. Alleen de randtotalen staan vast:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>bang voor onweer</th>
<th>dassen</th>
<th>uilen</th>
<th>rij-totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ja</td>
<td>?</td>
<td>?</td>
<td>120</td>
</tr>
<tr class="even">
<td>nee</td>
<td>?</td>
<td>?</td>
<td>180</td>
</tr>
<tr class="odd">
<td><strong>kolom-totaal</strong></td>
<td>180</td>
<td>120</td>
<td><strong>300</strong></td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Welk deel van <em>alle</em> dieren is bang voor onweer? Geef je antwoord als <strong>proportie</strong> én als <strong>percentage</strong>.</p></li>
<li><p>Onder <span class="math inline">\(H_0\)</span> (bang-zijn staat los van soort): hoeveel <strong>dassen</strong> verwacht je die bang zijn? Doe het via de <strong>proportie-route</strong> (proportie <span class="math inline">\(\times\)</span> kolomtotaal).</p></li>
<li><p>Controleer met de <strong>formule</strong> <span class="math inline">\(\dfrac{\text{rijtotaal} \times \text{kolomtotaal}}{N}\)</span> — krijg je hetzelfde?</p></li>
<li><p>Een medestudent zegt: <em>“die ,40 ís het verwachte aantal bange dassen.”</em> Klopt dat? Leg in één zin uit.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Antwoord T11.3">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord T11.3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> <span class="math inline">\(120/300 = {,}40\)</span>, oftewel <strong>40%</strong> is bang voor onweer (proportie <span class="math inline">\({,}40\)</span> = percentage 40% = de kans dat een willekeurig dier bang is).</p>
<p><strong>(b)</strong> Onder <span class="math inline">\(H_0\)</span> is in élke soort 40% bang. Dassen: <span class="math inline">\({,}40 \times 180 = \mathbf{72}\)</span>.</p>
<p><strong>(c)</strong> <span class="math inline">\(\dfrac{120 \times 180}{300} = \dfrac{21600}{300} = 72\)</span>. Hetzelfde — want <span class="math inline">\(\dfrac{120}{300} \times 180 = \dfrac{120 \times 180}{300}\)</span>.</p>
<p><strong>(d)</strong> Nee. <span class="math inline">\({,}40\)</span> is een <strong>proportie</strong> (40%), géén aantal. Het verwachte <em>aantal</em> is <span class="math inline">\({,}40 \times 180 = 72\)</span> — je moet de proportie eerst nog over het kolomtotaal leggen.</p>
</div>
</div>
</div>
<div class="opgave callout callout-style-default callout-note no-icon callout-titled" title="T11.4 — Chi-kwadraat onafhankelijkheid (3×2, zes cellen)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>T11.4 — Chi-kwadraat onafhankelijkheid (3×2, zes cellen)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Is er in het bos een verband tussen <strong>pootvoorkeur</strong> (rechts / links / nog geen) en <strong>soort</strong> (das / uil)? Bij 200 jonge dieren:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>pootvoorkeur</th>
<th>das</th>
<th>uil</th>
<th>rij-totaal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rechts</td>
<td>60</td>
<td>50</td>
<td>110</td>
</tr>
<tr class="even">
<td>links</td>
<td>15</td>
<td>16</td>
<td>31</td>
</tr>
<tr class="odd">
<td>nog geen</td>
<td>25</td>
<td>34</td>
<td>59</td>
</tr>
<tr class="even">
<td><strong>kolom-totaal</strong></td>
<td><strong>100</strong></td>
<td><strong>100</strong></td>
<td><strong>200</strong></td>
</tr>
</tbody>
</table>
<p>Toets op <span class="math inline">\(\alpha = .05\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Kort antwoord T11.4">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Kort antwoord T11.4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span>: geen verband (soort en pootvoorkeur onafhankelijk)</li>
<li><span class="math inline">\(H_1\)</span>: wel verband</li>
<li><span class="math inline">\(\chi^2 = 2{,}31\)</span> · <span class="math inline">\(df = (3-1)(2-1) = 2\)</span></li>
<li><span class="math inline">\(\chi^2\)</span>-tabel (rechterstaart): <span class="math inline">\(2{,}31 &lt;\)</span> de .25-grens (<span class="math inline">\(2{,}77\)</span>) → <span class="math inline">\(p &gt; .25\)</span></li>
<li><span class="math inline">\(p &gt; \alpha\ (.05)\)</span> → <strong><span class="math inline">\(H_0\)</span> niet verwerpen</strong></li>
<li><strong>Antwoord:</strong> geen significant verband tussen soort en pootvoorkeur</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="Volledige uitwerking T11.4 — stap voor stap">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Volledige uitwerking T11.4 — stap voor stap
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong><span class="math inline">\(H_0\)</span> / <span class="math inline">\(H_1\)</span></strong> (elk op een regel):<br><span class="math inline">\(H_0\)</span> = geen verband (onafhankelijk)<br><span class="math inline">\(H_1\)</span> = wel verband (afhankelijk).</li>
<li><strong>Verwachte waarde per cel</strong> <span class="math inline">\(= \dfrac{\text{rijtotaal} \times \text{kolomtotaal}}{N}\)</span>. Beide kolommen zijn hier 100, dus per rij:
<ul>
<li>rechts: <span class="math inline">\(110 \times 100 / 200 = 55\)</span> (das én uil)</li>
<li>links: <span class="math inline">\(31 \times 100 / 200 = 15{,}5\)</span></li>
<li>nog geen: <span class="math inline">\(59 \times 100 / 200 = 29{,}5\)</span></li>
</ul></li>
<li><strong><span class="math inline">\(\chi^2\)</span> per cel</strong> — in een tabel, zo zie je elke stap terug:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>cel</th>
<th><span class="math inline">\(O\)</span></th>
<th><span class="math inline">\(E\)</span></th>
<th><span class="math inline">\((O-E)^2/E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rechts, das</td>
<td>60</td>
<td>55</td>
<td>0,455</td>
</tr>
<tr class="even">
<td>rechts, uil</td>
<td>50</td>
<td>55</td>
<td>0,455</td>
</tr>
<tr class="odd">
<td>links, das</td>
<td>15</td>
<td>15,5</td>
<td>0,016</td>
</tr>
<tr class="even">
<td>links, uil</td>
<td>16</td>
<td>15,5</td>
<td>0,016</td>
</tr>
<tr class="odd">
<td>nog geen, das</td>
<td>25</td>
<td>29,5</td>
<td>0,686</td>
</tr>
<tr class="even">
<td>nog geen, uil</td>
<td>34</td>
<td>29,5</td>
<td>0,686</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(\Sigma = \chi^2\)</span></strong></td>
<td></td>
<td></td>
<td><strong>2,31</strong></td>
</tr>
</tbody>
</table>
<ol start="4" type="1">
<li><strong><span class="math inline">\(df\)</span></strong> <span class="math inline">\(= (\text{rijen} - 1)(\text{kolommen} - 1) = (3-1)(2-1) = \mathbf{2}\)</span>.</li>
<li><strong>Opzoeken</strong> in de <span class="math inline">\(\chi^2\)</span>-tabel — altijd de <strong>rechterstaart</strong> (richtingloos, nooit ×2): <span class="math inline">\(2{,}31\)</span> ligt vóór <span class="math inline">\(2{,}77\)</span> (de .25-grens bij <span class="math inline">\(df = 2\)</span>) → <span class="math inline">\(p &gt; .25\)</span>.</li>
<li><strong>Beslissen:</strong> <span class="math inline">\(p &gt; \alpha\ (.05)\)</span> → <strong><span class="math inline">\(H_0\)</span> niet verwerpen</strong>.</li>
<li><strong>Conclusie:</strong> er is geen significant verband tussen soort en pootvoorkeur; de kleine verschillen zijn toeval.</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/t11_4_chi2_df2.png" class="img-fluid figure-img" style="width:62.0%"></p>
<figcaption><span class="math inline">\(\chi^2 = 2{,}31\)</span> bij <span class="math inline">\(df = 2\)</span> — ruim vóór de .25-grens, dus <span class="math inline">\(p\)</span> groot</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="tot-slot" class="level1">
<h1>Tot slot</h1>
<p>Geen gemiddelden meer, gewoon tellen — maar onder de motorkap is er niks veranderd. Je zet wat je ziet (<span class="math inline">\(O\)</span>) naast wat het model verwacht (<span class="math inline">\(E\)</span>), en in dat gat ertussen zit het hele verhaal. Te groot een gat, gekwadrateerd en opgeteld, en je gooit “het is toeval” overboord. De fiets in de bakker, nu in een kruistabel. En onthoud dat ene: <span class="math inline">\(\chi^2\)</span> kent geen richting, alles wordt gekwadrateerd, dus nooit Pippi.</p>
<p>En dan Simpson, helemaal aan het eind, als een waarschuwing die je nooit meer kwijtraakt: aggregeren is een vorm van vergeten. De subgroepen zwijgen niet — je hoort ze alleen niet meer.</p>
<hr>
<p><em>Werkboek OZP 1 · Thema 11, versie 0.1 (handrekenen &amp; theorie). Doorlopend voorbeeld: de egels (+ alledaagse voorbeelden: roken, school).</em></p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Terug naar boven</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../10_power/10_power.html" class="pagination-link" aria-label="Thema 10 · Power">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Thema 10 · Power</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../woordenlijst.html" class="pagination-link" aria-label="Woordenlijst">
        <span class="nav-page-text">Woordenlijst</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Werkboek OZP 1 · CountCamp Lab · wisi.nl</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Vragen, opmerkingen of suggesties? <a href="mailto:vragen@countcamp.org">vragen@countcamp.org</a></p>
</div>
  </div>
</footer>




</body></html>