<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 3.3 · De residuen bekijken – R-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_steekproevenverdeling.html" rel="next">
<link href="../20_blokken/blok_enkelvoudige_regressie.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Tweede beweging · Verschillen koppelen</li><li class="breadcrumb-item"><a href="../20_blokken/blok_correlatie_scatterplot.html">H3 · Het rechthoekje</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_residuen.html">Oefening 3.3 · De residuen bekijken</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">H3 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 3.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_confounding_partiele_correlatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.2 · Confounding en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · Eenweg ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Tweede beweging · Verschillen koppelen</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Tweede beweging · Verschillen koppelen</li><li class="breadcrumb-item"><a href="../20_blokken/blok_correlatie_scatterplot.html">H3 · Het rechthoekje</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_residuen.html">Oefening 3.3 · De residuen bekijken</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 3.3 · De residuen bekijken</h1>
<p class="subtitle lead">Onafhankelijk, gelijke spreiding, normaal verdeeld · <em>residual diagnostics</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#tien-dagen-van-precies-81-graden" id="toc-tien-dagen-van-precies-81-graden">Tien dagen van precies 81 graden</a></li>
  <li><a href="#reken-de-residuen-uit-en-teken-ze-in-r" id="toc-reken-de-residuen-uit-en-teken-ze-in-r">Reken de residuen uit en teken ze in R</a></li>
  <li><a href="#is-die-1.65-raar" id="toc-is-die-1.65-raar">Is die 1.65 raar?</a></li>
  <li><a href="#drie-aannames-drie-plaatjes" id="toc-drie-aannames-drie-plaatjes">Drie aannames, drie plaatjes</a></li>
  <li><a href="#twee-lijnen-keuren" id="toc-twee-lijnen-keuren">Twee lijnen keuren</a></li>
  <li><a href="#diepe-snavel-lichte-pinguïn-het-hele-hoofdstuk-in-één-wolk" id="toc-diepe-snavel-lichte-pinguïn-het-hele-hoofdstuk-in-één-wolk">Diepe snavel, lichte pinguïn? — het hele hoofdstuk in één wolk</a></li>
  <li><a href="#schrijf-op-wat-je-gecontroleerd-hebt" id="toc-schrijf-op-wat-je-gecontroleerd-hebt">Schrijf op wat je gecontroleerd hebt</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/luchtkwaliteit.csv" download="luchtkwaliteit.csv">luchtkwaliteit.csv</a> 116 zomerdagen in New York · <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../10_data/bigfive.csv" download="bigfive.csv">bigfive.csv</a> 2634 ingevulde vragenlijsten · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="tien-dagen-van-precies-81-graden" class="level2">
<h2 class="anchored" data-anchor-id="tien-dagen-van-precies-81-graden">Tien dagen van precies 81 graden</h2>
<p><span class="begrippen">voorspelling · misser · spreiding rond de lijn</span></p>
<p>Het meetkastje op Roosevelt Island ken je al — dat is het kastje uit de oefening over de mediaan, dat de zomer van 1973 lang elke dag de ozon in de New Yorkse lucht opsnoof.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Zelfde kastje, nieuwe vraag: naast de ozon noteerde het ook de temperatuur, en warme lucht en smog horen bij elkaar. Leg er dus een lijn in. Hoe warmer de dag, hoe meer ozon.</p>
<p>Die lijn komt er, hij loopt netjes omhoog, en hij dekt bijna de helft van alle verschil tussen de dagen: <em>R</em>² = .49. Voor buitenlucht is dat veel.</p>
<p>En nu iets raars. In die 116 dagen zitten <strong>tien</strong> dagen van precies 81 graden Fahrenheit. Tien keer dezelfde temperatuur, dus tien keer dezelfde voorspelling: de lijn zegt voor alle tien <strong>49.7</strong> ppb ozon. Wat het kastje op die tien dagen werkelijk mat:</p>
<blockquote class="blockquote">
<p>9 · 27 · 32 · 36 · 39 · 44 · 45 · 48 · 59 · <strong>168</strong></p>
</blockquote>
<p>Van 9 tot 168, bij één en dezelfde temperatuur. De lijn kan daar niets aan doen — hij weet alleen de temperatuur, en die was tien keer gelijk. Maar het zet wel een vraag op scherp die we tot nu toe hebben laten liggen: <strong>hoe ver zit de lijn er eigenlijk naast, en zit hij er overal even ver naast?</strong></p>
<p>Reken je het na, dan is het antwoord op die tweede vraag <em>nee</em>. Op de koelere helft van de zomer (tot en met 79 graden) zit de lijn er gemiddeld <strong>13.7</strong> ppb naast; op de warmere helft <strong>20.9</strong>. Eén lijn, en toch op de ene helft van de zomer duidelijk scherper dan op de andere.</p>
<p>Trek even mee. We gaan die missers zélf tekenen — en het blijkt dat er drie verschillende dingen in te zien zijn, waarvan er twee niets met de lijn zelf te maken hebben.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="reken-de-residuen-uit-en-teken-ze-in-r" class="level2">
<h2 class="anchored" data-anchor-id="reken-de-residuen-uit-en-teken-ze-in-r">Reken de residuen uit en teken ze in R</h2>
<p><span class="begrippen">residu · voorspelde waarde · residuenplot</span></p>
<p>Zo’n misser heeft een naam, en je hebt hem in het boek al zien staan: <strong>DATA = FIT + RESIDU</strong>. De <em>fit</em> is wat de lijn gokt, het <strong>residu</strong> is wat er overblijft — de gokfout, nu niet meer ten opzichte van het gemiddelde maar ten opzichte van de lijn.</p>
<div class="rcode callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"diamantjes.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>model.karaat <span class="ot">&lt;-</span> <span class="fu">lm</span>(glans <span class="sc">~</span> karaat, <span class="at">data =</span> d)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># wat de lijn gokt, en wat er overblijft</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">fitted</span>(model.karaat), <span class="dv">1</span>)     <span class="co"># → 30.7 33.9 33.9 40.4 50.0 50.0 53.2 56.4 59.6 59.6 66.1 66.1</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">resid</span>(model.karaat),  <span class="dv">1</span>)     <span class="co"># → -10.7 -3.9 -3.9 -10.4 0.0 20.0 26.8 3.6 10.4 20.4 -36.1 -16.1</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># de kolom die je in het boek al hebt zien optellen tot nul</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">resid</span>(model.karaat))           <span class="co"># → 0 (op afrondingsgruis na)</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<p>Dat zijn precies de twee kolommen uit de tabel in het boek: Else valt op nul (de lijn gaat dwars door haar heen), Kees zit er met −36.1 het verst naast. Nieuw is alleen de <strong>derde regel</strong> hieronder — je zet die twee kolommen tegen elkaar in een plaatje in plaats van ze te lezen:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(model.karaat), <span class="fu">resid</span>(model.karaat))    <span class="co"># de residuenplot: gok op de x-as, misser op de y-as</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)                <span class="co"># de lijn zelf ligt hier plat op nul</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Kijk goed wat dat plaatje doet. De regressielijn is <strong>plat geworden</strong>: alles wat de lijn al wist is eruit gerekend, dus wat overblijft hoort rond de nullijn te zweven zonder patroon. Een residuenplot is een schoongeveegde scatterplot — je kijkt niet meer naar het verband, je kijkt naar wat het verband liet liggen.</p>
<p>Met twaalf punten zie je er weinig aan, en dat is geen tegenvaller maar het eerste wat je leert: hierover zo meer.</p>
<p><strong>Nu jij</strong> — bij het meetkastje, dat je van de mediaan-oefening al kent. Bekende data, nieuwe vraag: wat laat die ozon-lijn liggen?</p>
<div class="rcode callout callout-style-default callout-note callout-titled" title="In R · trek eraan">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In R · trek eraan
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Base R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Sneller</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>lucht <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"luchtkwaliteit.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>model.temp <span class="ot">&lt;-</span> <span class="fu">lm</span>(ozon <span class="sc">~</span> temp_F, <span class="at">data =</span> lucht)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 — de residuenplot: waar zit de lijn ernaast, en hoe ver?</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(model.temp), <span class="fu">resid</span>(model.temp), <span class="at">xlab =</span> <span class="st">"voorspelde ozon"</span>, <span class="at">ylab =</span> <span class="st">"residu"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 — de vorm van de missers: hoe liggen ze om de nul heen?</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(model.temp))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 3 — dezelfde vraag, strenger: liggen ze op een rechte lijn?</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(model.temp)); <span class="fu">qqline</span>(<span class="fu">resid</span>(model.temp))</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>R maakt deze drie ook zelf. Geef het model aan <code>plot()</code> en vraag om plaatje 1 en 2 van de vier die hij kent:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.temp, <span class="at">which =</span> <span class="dv">1</span>)     <span class="co"># residuen tegen voorspelling, met een hulplijn erdoor</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.temp, <span class="at">which =</span> <span class="dv">2</span>)     <span class="co"># de Q-Q-plot van de residuen</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Zelfde plaatjes, andere opmaak — R zet er de rijnummers van de drie opvallendste punten bij. Handig zodra je wilt weten <em>wie</em> er buiten hangt.</p>
</div>
</div>
</div>
</div>
</div>
<p>Drie plaatjes, en in alle drie staat iets.</p>
<p><strong>De residuenplot</strong> begint smal en loopt open. Links, bij voorspellingen onder de 30 ppb, liggen de punten in een dun bandje om de nullijn (<em>SD</em> rond de 10); vanaf een voorspelling van 30 is dat bandje ruim twee keer zo breed. Aan de uiterste rechterkant lijkt hij weer te versmallen, maar daar staan nog maar dertien dagen — te weinig om iets van te vinden.</p>
<p>Reken die indruk na, want een indruk is nog geen bevinding. Knip de zomer bij 79 graden doormidden — dat is de mediane dag — en vergelijk de spreiding van de residuen links en rechts:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>koel <span class="ot">&lt;-</span> lucht<span class="sc">$</span>temp_F <span class="sc">&lt;=</span> <span class="dv">79</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">resid</span>(model.temp)[koel])       <span class="co"># → 17.47   59 koelere dagen</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">resid</span>(model.temp)[<span class="sc">!</span>koel])      <span class="co"># → 28.74   57 warmere dagen</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">resid</span>(model.temp)[<span class="sc">!</span>koel]) <span class="sc">/</span> <span class="fu">sd</span>(<span class="fu">resid</span>(model.temp)[koel])    <span class="co"># → 1.65</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Het histogram en de Q-Q-plot</strong> wijzen naar iets anders. De missers liggen niet symmetrisch om nul: er is een lange staart naar rechts (die ene dag van +118) en niets vergelijkbaars naar links. In de Q-Q-plot buigen de punten rechtsboven weg van de hulplijn.</p>
<p>Die scheefheid is dezelfde scheefheid die je in de mediaan-oefening al zag — alleen zat hij toen in de ozon zelf, en zit hij nu in wat er van de ozon overblijft nadat de temperatuur zijn deel heeft gehad.</p>
<div class="kicker">
<p>schud het</p>
</div>
</section>
<section id="is-die-1.65-raar" class="level2">
<h2 class="anchored" data-anchor-id="is-die-1.65-raar">Is die 1.65 raar?</h2>
<p><span class="begrippen">schudden · loskoppelen · duizend werelden rond één</span></p>
<p>1.65 keer zo breed. Dat <em>klinkt</em> als veel, maar de vorige alinea’s zijn een verhaal en geen bewijs: twee groepjes van pakweg 58 dagen hebben nooit precies dezelfde spreiding, ook niet als er niks aan de hand is. De vraag is dus niet of 1.65 groter is dan 1, maar <strong>hoeveel groter dan 1 een gewone wiebel al is</strong>.</p>
<p>Daar hebben we een zet voor. We laten de voorspellingen staan waar ze staan, en we husselen de residuen erlangs — de misser van een hete dag verhuist naar een koele en omgekeerd.</p>
<p>Dat husselen is de hele truc, en het loont om er even bij stil te staan: je <strong>koppelt het residu los van zijn eigen voorspelling</strong>. Je haalt met eigen handen weg dat een bepaalde misser bij een bepaalde temperatuur hoorde. In zo’n losgekoppelde wereld kán de spreiding niet meer meelopen met de voorspelling — en dus is elk verschil tussen de twee helften dat je er dan nóg in meet, per definitie puur toeval.</p>
<div class="rcode callout callout-style-default callout-note callout-titled" title="In R · schud de missers los van hun eigen dag">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In R · schud de missers los van hun eigen dag
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">resid</span>(model.temp)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>maat <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sd</span>(x[<span class="sc">!</span>koel]) <span class="sc">/</span> <span class="fu">sd</span>(x[koel])   <span class="co"># breed gedeeld door smal</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>nep <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">maat</span>(<span class="fu">sample</span>(e, <span class="at">replace =</span> <span class="cn">FALSE</span>)))   <span class="co"># 1000 losgekoppelde zomers</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nep, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))    <span class="co"># → 0.66 tot 1.53</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nep <span class="sc">&gt;=</span> <span class="fl">1.65</span>)              <span class="co"># → 18 van de 1000</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(nep)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">1.65</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<p><strong>Duizend werelden die dansen rond één.</strong> Rond één, niet rond nul, want dit is een verhouding: twee even brede helften geven 1.0. En kijk waar ze landen — tussen 0.66 en 1.53 ligt negentig procent van de gehusselde zomers. Dat is een brede dans. Twee helften kunnen dus zomaar anderhalf keer schelen zonder dat er iets aan de hand is.</p>
<p>En dan die rode streep op 1.65, er net buiten: <strong>achttien</strong> van de duizend gehusselde zomers halen dat. Niet onmogelijk, wel ongewoon. Geen <em>p</em>-waarde die je moet geloven — een <strong>afstand die je zíet</strong>, en hier is die afstand krap.</p>
<p>Doe hetzelfde bij de pinguïns en je ziet meteen hoe anders “niks aan de hand” eruitziet. Daar voorspelde je in de vorige oefening het gewicht uit de vinlengte:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>peng <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"penguins.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>model.vl   <span class="ot">&lt;-</span> <span class="fu">lm</span>(gewicht <span class="sc">~</span> vinlengte, <span class="at">data =</span> peng)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>kort <span class="ot">&lt;-</span> peng<span class="sc">$</span>vinlengte <span class="sc">&lt;=</span> <span class="dv">197</span>            <span class="co"># de mediane vin</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">resid</span>(model.vl)[<span class="sc">!</span>kort]) <span class="sc">/</span> <span class="fu">sd</span>(<span class="fu">resid</span>(model.vl)[kort])    <span class="co"># → 0.92</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>nep_p <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  { x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">resid</span>(model.vl), <span class="at">replace =</span> <span class="cn">FALSE</span>); <span class="fu">sd</span>(x[<span class="sc">!</span>kort]) <span class="sc">/</span> <span class="fu">sd</span>(x[kort]) })</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nep_p, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))    <span class="co"># → 0.88 tot 1.14</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>0.92, en de gewone-wiebel-band loopt van 0.88 tot 1.14. Het echte getal ligt er gewoon <strong>in</strong>. Bij de pinguïns is er niets te zien, en dat is precies zoals het hoort: 342 dieren geven een smalle band, dus daar zou een trechter meteen opvallen. Bij 116 dagen is de band breder. Bij twaalf diamantjes — daar komen we zo op — is hij zo breed dat er bijna niets meer buiten valt.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="drie-aannames-drie-plaatjes" class="level2">
<h2 class="anchored" data-anchor-id="drie-aannames-drie-plaatjes">Drie aannames, drie plaatjes</h2>
<p><span class="begrippen">onafhankelijkheid · gelijke spreiding · normaliteit</span></p>
<p>Het boek noemt bij de regressielijn drie veronderstellingen, en ze gaan geen van drieën over de lijn zelf. De lijn eist maar één ding, en dat is dat het verband recht is. De drie hieronder gaan over het gedrag van de <strong>fouten</strong> — en je hebt ze net alle drie in beeld gehad.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>aanname</th>
<th>welk plaatje</th>
<th>waaraan je ziet dat het misgaat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>onafhankelijk</strong></td>
<td>geen plaatje — je studieopzet</td>
<td>dezelfde persoon of plek staat meerdere keren in de tabel</td>
</tr>
<tr class="even">
<td><strong>gelijke spreiding</strong></td>
<td>residuen tegen voorspelling</td>
<td>een trechter: smal aan de ene kant, breed aan de andere</td>
</tr>
<tr class="odd">
<td><strong>normaal verdeeld</strong></td>
<td>histogram of Q-Q-plot van de residuen</td>
<td>een scheve staart; in de Q-Q-plot buigen de punten weg van de hulplijn</td>
</tr>
</tbody>
</table>
<p>Loop ze langs op de ozon.</p>
<p><strong>Onafhankelijk</strong> — dat is de enige van de drie waar geen knop voor bestaat, en dat is geen tekortkoming van R. Ben vat hem samen in één vraag: <em>“geeft elke rij in mijn dataset informatie die niet al ergens anders in de tabel zit?”</em> Het antwoord zit in je opzet, niet in je data. Bij het meetkastje is het antwoord twijfelachtig: dit zijn 116 opeenvolgende dagen op één plek. Een smoggerige dinsdag maakt een smoggerige woensdag waarschijnlijker, want de lucht is ’s nachts niet weg. Elke rij is dus deels een herhaling van de vorige.</p>
<p>En let op wat er gebeurt als je dat tóch in de data probeert te zien. Meet de samenhang tussen het residu van de ene meetdag en dat van de volgende, en er komt .08 uit — een getal dat in 175 van de 1000 gehusselde zomers óók gehaald wordt. Het plaatje zegt dus: niets aan de hand. Het <strong>ontwerp</strong> zegt: dagen na elkaar op één plek. Die twee spreken elkaar niet tegen; ze meten iets anders. Daarom hoort deze aanname bij je opzet en niet bij je plaatjes — een steekproef kan er onafhankelijk <em>uitzien</em> en het niet zijn.</p>
<p><strong>Gelijke spreiding</strong> — het deftige woord is <em>homoscedasticiteit</em>, en dat mag je hardop oefenen. Hier gaat het mis, zij het krap: 1.65 tegen een gewone-wiebel-band die tot 1.53 loopt. Het gevolg zit niet in de lijn maar in de <em>onzekerheid</em> om de lijn: R rekent één standaardfout uit voor het hele bereik, en die is dan te ruim voor de koele dagen en te krap voor de hete. Je helling blijft bruikbaar; je betrouwbaarheidsinterval wordt onbetrouwbaar, en precies daar waar de metingen het wildst zijn.</p>
<p><strong>Normaal verdeeld</strong> — hier zit de duidelijkste schending. En één zin van Ben voorkomt dat je hem te streng leest: <em>“een steekproef kan niet normaal verdeeld zijn, alleen bíj benadering normaal verdeeld”</em> — voor een perfecte normale verdeling heb je oneindig veel scores nodig. Je zoekt dus geen perfecte klok maar een hoop zonder duidelijke scheefheid. Deze is dat niet: er is een lange staart naar rechts en niets vergelijkbaars naar links. Waar die vandaan komt, staat een paar alinea’s verderop — hij heeft dezelfde oorzaak als de trechter.</p>
<p><strong>En dan de vraag die niemand stelt: hoeveel data heb je nodig om dit te zien?</strong> Doe dezelfde schud-zet op de twaalf diamantjes en het antwoord staat er:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model.karaat <span class="ot">&lt;-</span> <span class="fu">lm</span>(glans <span class="sc">~</span> karaat, <span class="at">data =</span> d)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>laag <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model.karaat) <span class="sc">&lt;=</span> <span class="fu">median</span>(<span class="fu">fitted</span>(model.karaat))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">resid</span>(model.karaat)[<span class="sc">!</span>laag]) <span class="sc">/</span> <span class="fu">sd</span>(<span class="fu">resid</span>(model.karaat)[laag])       <span class="co"># → 2.09</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>nep_d <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  { x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">resid</span>(model.karaat), <span class="at">replace =</span> <span class="cn">FALSE</span>); <span class="fu">sd</span>(x[<span class="sc">!</span>laag]) <span class="sc">/</span> <span class="fu">sd</span>(x[laag]) })</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nep_d, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))                     <span class="co"># → 0.48 tot 2.08</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Op twaalf steentjes loopt de gewone-wiebel-band van 0.48 tot 2.08. De helft van je metingen mag dus zomaar twee keer zo breed zijn als de andere helft, puur door toeval. Zet de drie naast elkaar en de les is één regel breed:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>data</th>
<th style="text-align: right;"><em>N</em></th>
<th style="text-align: right;">verhouding</th>
<th style="text-align: right;">gewone-wiebel-band</th>
<th>oordeel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>diamantjes</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">0.48 – 2.08</td>
<td>de band is zo breed dat je niets kunt zeggen</td>
</tr>
<tr class="even">
<td>luchtkwaliteit</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">0.66 – 1.53</td>
<td>er net buiten: een trechter, krap</td>
</tr>
<tr class="odd">
<td>pinguïns</td>
<td style="text-align: right;">342</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">0.88 – 1.14</td>
<td>er ruim binnen: gewone wiebel</td>
</tr>
</tbody>
</table>
<p>Hoe minder data, hoe wilder de gewone wiebel — en dus hoe minder een residuenplot je vertelt. Dat maakt een klein bestand niet verdacht; het maakt je oordeel erover ongegrond. Wie bij een handjevol punten roept dat hij een trechter ziet, ziet ruis.</p>
<p><strong>En wat doe je er dan aan?</strong> Er is nog een aanwijzing die dezelfde kant op wijst, en die zie je zonder enig plaatje: vraag de voorspellingen op met <code>range(fitted(model.temp))</code> en er staat <strong>−8.6</strong> tot 88.6. Op de vier koelste dagen belooft deze lijn een negatieve hoeveelheid ozon, en minder dan niets bestaat niet. De lijn loopt door tot in de oneindigheid; de ozon heeft een bodem.</p>
<p>Precies díé bodem maakt ook de trechter en de scheve staart. Een lijn die 20 voorspelt kan er maar 20 naast zitten aan de onderkant en onbeperkt aan de bovenkant. Drie waarnemingen, één oorzaak — en dat wijst meteen de gewone zet aan: reken op een andere schaal. Neem de logaritme van de ozon, dus tel de <em>verhoudingen</em> in plaats van de punten:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>model.log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(ozon) <span class="sc">~</span> temp_F, <span class="at">data =</span> lucht)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">resid</span>(model.log)[<span class="sc">!</span>koel]) <span class="sc">/</span> <span class="fu">sd</span>(<span class="fu">resid</span>(model.log)[koel])    <span class="co"># → 0.82   (was 1.65)</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.log)<span class="sc">$</span>r.squared                          <span class="co"># → 0.547  (was 0.488)</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>De trechter is weg, en het model is er ook nog beter van gaan passen. Dat is geen trucje om een controle te laten slagen: het is de erkenning dat ozon zich in verhoudingen gedraagt en niet in optellingen. Twintig ppb erbij op een smoggerige dag betekent iets anders dan twintig ppb erbij op een schone. De prijs is dat je uitkomst nu in logaritmen staat en dus vertaald moet worden voor je hem opschrijft — en dát is werk voor later in het boek.</p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="twee-lijnen-keuren" class="level2">
<h2 class="anchored" data-anchor-id="twee-lijnen-keuren">Twee lijnen keuren</h2>
<p><span class="begrippen">residuenplot · Q-Q-plot · schud-band · oordelen</span></p>
<p>Twee regressielijnen, allebei op data die je kent, en aan jou de vraag of je de residuen vertrouwt. Je doet voor allebei hetzelfde rondje: residuenplot, Q-Q-plot, de verhouding, en duizend keer schudden om te zien hoe breed de gewone wiebel hier is.</p>
<div class="rcode callout callout-style-default callout-note callout-titled" title="In R · de twee lijnen">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In R · de twee lijnen
</div>
</div>
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lucht <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"luchtkwaliteit.csv"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>model.wind <span class="ot">&lt;-</span> <span class="fu">lm</span>(ozon <span class="sc">~</span> wind, <span class="at">data =</span> lucht)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"bigfive.csv"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>b<span class="sc">$</span>N <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(b[, <span class="fu">c</span>(<span class="st">"N1"</span>,<span class="st">"N2"</span>,<span class="st">"N3"</span>,<span class="st">"N4"</span>,<span class="st">"N5"</span>)])</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>b<span class="sc">$</span>O <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(b[, <span class="fu">c</span>(<span class="st">"O1"</span>,<span class="st">"O2"</span>,<span class="st">"O3"</span>,<span class="st">"O4"</span>,<span class="st">"O5"</span>)])</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>model.big5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(N <span class="sc">~</span> O, <span class="at">data =</span> b)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># scheefheid heeft in base R geen eigen functie, dus hier is de formule:</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># hoe scheef ligt een hoop getallen om zijn eigen gemiddelde?</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>scheefheid <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">mean</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> <span class="fu">mean</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="fl">1.5</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Beantwoord de vragen op volgorde; ze bouwen op elkaar. De laatste heet met opzet <strong>Z)</strong> en niet k): de aannames staan altijd achteraan — ook in een oefening die zélf over aannames gaat.</p>
<p><strong>a)</strong> Lees <code>model.wind</code> af. (rapporteer <em>b</em><sub>0</sub>, <em>b</em><sub>1</sub> mét eenheid, en <em>R</em>²)</p>
<p><strong>b)</strong> Teken de residuenplot en de Q-Q-plot van deze lijn. Wat zie je? (twee zinnen: één over de breedte, één over de vorm)</p>
<p><strong>c)</strong> Let op, de knip loopt hier <strong>andersom</strong> dan bij de temperatuur. De helling is negatief — meer wind, minder smog — dus de hóóg voorspelde dagen zijn de dagen met <strong>weinig</strong> wind. Knip bij de mediane wind en deel de spreiding bij weinig wind door die bij veel wind. (de mediane wind, twee standaardafwijkingen mét hun <em>n</em>, en de verhouding)</p>
<p><strong>d)</strong> Schud de residuen duizend keer los van hun eigen dag. (de 5%- en 95%-grens van de geschudde zomers, en hoeveel van de duizend de echte verhouding halen)</p>
<p><strong>e)</strong> Geef je oordeel over de wind-lijn, en zeg of het strenger of milder is dan bij de temperatuur-lijn. (twee zinnen, met allebei de verhoudingen én allebei de banden erbij)</p>
<p><strong>f)</strong> Nu de tweede lijn: 2634 ingevulde vragenlijsten, neuroticisme voorspeld uit openheid. Lees <code>model.big5</code> af. (rapporteer <em>b</em><sub>1</sub> mét eenheid en <em>R</em>²)</p>
<p><strong>g)</strong> Doe het keuringsrondje ook hier. (de verhouding, de schudband, en de scheefheid van de residuen)</p>
<p><strong>h)</strong> Geef je oordeel over alle drie de aannames van deze tweede lijn. (drie korte uitspraken, elk met het getal waar je hem op baseert)</p>
<p><strong>i)</strong> Die schudband is bij de vragenlijsten veel smaller dan bij de zomerdagen. Waarom? (één zin, en noem allebei de <em>n</em>’s)</p>
<p><strong>j)</strong> De denk-vraag, en hij is de belangrijkste van dit blok. Bij <code>model.big5</code> zijn de aannames in orde en is de <em>R</em>² .03 — nog geen drie procent. Waar geeft een residuenplot dus wél antwoord op, en waar niet? (drie zinnen)</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Eén van de drie aannames heeft geen plaatje, en juist die scheidt deze twee bestanden. Vraag je bij allebei af waar de rijen vandaan komen: 116 opeenvolgende dagen op één meetkastje, tegenover 2634 mensen die elk één keer een vragenlijst invulden. (zeg per bestand of de rijen onafhankelijk zijn, en welke van je antwoorden hierboven eraan hangen)</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <em>b</em><sub>0</sub> = 96.87 en <em>b</em><sub>1</sub> = −5.55 ppb ozon per mijl per uur wind; <em>R</em>² = .36. Elke mijl per uur meer wind gaat samen met ruim vijfeneenhalve ppb minder ozon.</p>
<p><strong>b)</strong> De residuenplot loopt open naar de kant van de hóóg voorspelde dagen — dus naar de dagen met weinig wind. En de vorm is scheef: een lange staart omhoog, niets vergelijkbaars omlaag, en in de Q-Q-plot buigen de punten rechtsboven weg van de hulplijn. Dezelfde twee dingen als bij de temperatuur-lijn, en dat is geen toeval: het is dezelfde ozon met dezelfde bodem van nul.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.wind, <span class="at">which =</span> <span class="dv">1</span>)          <span class="co"># residuen tegen voorspelling</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.wind, <span class="at">which =</span> <span class="dv">2</span>)          <span class="co"># de Q-Q-plot</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scheefheid</span>(<span class="fu">resid</span>(model.wind))        <span class="co"># → 0.68</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>c)</strong> De mediane wind is 9.7 mph. Bij weinig wind is <em>SD</em> = 31.08 ppb (<em>n</em> = 62), bij veel wind <em>SD</em> = 19.88 ppb (<em>n</em> = 54). De verhouding is dus <strong>1.56</strong>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>weinig <span class="ot">&lt;-</span> lucht<span class="sc">$</span>wind <span class="sc">&lt;=</span> <span class="fu">median</span>(lucht<span class="sc">$</span>wind)     <span class="co"># → 9.7</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">resid</span>(model.wind)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(e[weinig])                  <span class="co"># → 31.08   62 dagen met weinig wind</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(e[<span class="sc">!</span>weinig])                 <span class="co"># → 19.88   54 dagen met veel wind</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(e[weinig]) <span class="sc">/</span> <span class="fu">sd</span>(e[<span class="sc">!</span>weinig]) <span class="co"># → 1.56</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>d)</strong> De gewone-wiebel-band loopt van <strong>0.80 tot 1.26</strong>, en <strong>geen enkele</strong> van de duizend gehusselde zomers haalt de 1.56.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>nep <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  { x <span class="ot">&lt;-</span> <span class="fu">sample</span>(e, <span class="at">replace =</span> <span class="cn">FALSE</span>); <span class="fu">sd</span>(x[weinig]) <span class="sc">/</span> <span class="fu">sd</span>(x[<span class="sc">!</span>weinig]) })</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nep, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))    <span class="co"># → 0.80 tot 1.26</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nep <span class="sc">&gt;=</span> <span class="fl">1.56</span>)              <span class="co"># → 0 van de 1000</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>e)</strong> Hier is de gelijke spreiding duidelijk geschonden, en het oordeel is <strong>strenger</strong> dan bij de temperatuur-lijn. Daar was het 1.65 tegen een band die tot 1.53 liep — er net buiten, en achttien van de duizend haalden het. Hier is de verhouding kleiner (1.56) maar de band ook véél smaller (tot 1.26), en dan haalt er niet één van de duizend meer. <strong>Een kleiner getal kan dus een harder oordeel opleveren</strong>, want je vergelijkt het niet met 1 maar met de band.</p>
<p><strong>f)</strong> <em>b</em><sub>1</sub> = 0.35 punten neuroticisme per punt openheid, <em>R</em>² = .03.</p>
<p><strong>g)</strong> De verhouding is <strong>1.06</strong>, de schudband loopt van <strong>0.96 tot 1.04</strong>, en de scheefheid van de residuen is <strong>0.19</strong>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>e5 <span class="ot">&lt;-</span> <span class="fu">resid</span>(model.big5); f5 <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model.big5)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>laag <span class="ot">&lt;-</span> f5 <span class="sc">&lt;=</span> <span class="fu">median</span>(f5)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(e5[<span class="sc">!</span>laag]) <span class="sc">/</span> <span class="fu">sd</span>(e5[laag])     <span class="co"># → 1.06</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>nep5 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  { x <span class="ot">&lt;-</span> <span class="fu">sample</span>(e5, <span class="at">replace =</span> <span class="cn">FALSE</span>); <span class="fu">sd</span>(x[<span class="sc">!</span>laag]) <span class="sc">/</span> <span class="fu">sd</span>(x[laag]) })</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nep5, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))      <span class="co"># → 0.96 tot 1.04</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scheefheid</span>(e5)                   <span class="co"># → 0.19</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>h)</strong> <em>Gelijke spreiding:</em> de verhouding 1.06 ligt net buiten de band 0.96–1.04. <em>Normaal verdeeld:</em> scheefheid 0.19, dus geen scheve staart van betekenis. <em>Onafhankelijk:</em> 2634 mensen die elk één keer invulden, dus elke rij is nieuwe informatie — zie Z).</p>
<p>En dan meteen de vraag die je bij e) hebt leren stellen: buiten de band, dus mis? Hier niet, en dat is geen slap aftreksel van de regel maar de andere helft ervan. <strong>Buiten de band betekent “dit is geen toeval”; het zegt niets over hoe gróót het is.</strong> Bij 2634 waarnemingen wordt de band zó smal (0.96–1.04) dat een afwijking van zes procent er al buiten valt. Zes procent verschil in spreiding verandert aan geen enkele <em>p</em> in dit model iets. Bij de wind-lijn ging het om zesenvijftig procent, en dáár hangt je hele betrouwbaarheidsinterval aan.</p>
<p>Kijk dus altijd naar allebei: <strong>ligt het buiten de band</strong> (is het echt?) én <strong>hoe ver van 1 ligt het</strong> (doet het ertoe?). Met veel data gaan die twee uiteenlopen, en dan is de tweede de vraag die telt.</p>
<p><strong>i)</strong> Omdat een schudband smaller wordt naarmate je meer waarnemingen hebt: bij <em>n</em> = 2634 wiebelen twee helften nauwelijks van elkaar weg, bij <em>n</em> = 116 nog flink. Dat is dezelfde regel als in de tabel hierboven — twaalf diamantjes gaven 0.48 tot 2.08.</p>
<p><strong>j)</strong> Een residuenplot beantwoordt: <em>mag ik de onzekerheid rond deze lijn geloven?</em> Hij zegt of de standaardfouten, de intervallen en de <em>p</em>’s op een kloppende aanname rusten. Hij zegt <strong>niet</strong> of het model iets waard is: hier is alles netjes en verklaart het model 3% van de verschillen. En hij zegt al helemaal niet of de lijn de júiste lijn is — dat is een derde vraag, en die komt in de Eindopdracht hieronder langs.</p>
<p><strong>Z)</strong> Dit is de aanname zonder plaatje, en hij valt bij deze twee bestanden tegengesteld uit.</p>
<ul>
<li><strong>De vragenlijsten:</strong> 2634 verschillende mensen, elk één keer. Elke rij draagt informatie die niet al ergens anders in de tabel zit. Onafhankelijk, dus.</li>
<li><strong>Het meetkastje:</strong> 116 <strong>opeenvolgende</strong> dagen op één plek. Een smoggerige dinsdag maakt een smoggerige woensdag waarschijnlijker; elke rij is dus deels een herhaling van de vorige. Níét onafhankelijk — en let op dat je dit niet aan de data ziet maar aan de opzet. De samenhang tussen het residu van de ene dag en dat van de volgende is .08, een getal dat in 175 van de 1000 gehusselde zomers óók gehaald wordt. Het plaatje zegt dus “niets aan de hand” terwijl het ontwerp iets anders zegt.</li>
</ul>
<p>Wat daar aan hangt:</p>
<ul>
<li><p><strong>Blijft staan:</strong> alle beschrijvende getallen — de hellingen bij a) en f), de <em>R</em>²’s, de verhoudingen bij c) en g), de scheefheid. Die beschrijven wat er in de tabel staat.</p></li>
<li><p><strong>Doe je over:</strong> bij de wind-lijn de schudband bij d), en daarmee het oordeel bij e). Schudden gaat ervan uit dat de residuen onderling <strong>verwisselbaar</strong> zijn: elk residu had bij elke andere dag kunnen horen. Bij opeenvolgende dagen klopt dat niet.</p>
<p>En dat maakt de band te smal, langs deze weg: als een smoggerige dag door een smoggerige buurdag wordt gevolgd, dan draagt zo’n paar maar één keer nieuwe informatie in plaats van twee keer. Je hebt dus minder échte waarnemingen dan de 116 die je telde — en hoe minder waarnemingen, hoe bréder de gewone wiebel, dat wist je uit de tabel hierboven. Door tóch met 116 losse dagen te schudden reken je een band uit die hoort bij méér data dan je hebt: te smal. En met een te smalle band lijkt je eigen getal er sneller buiten te vallen, dus je oordeel is strenger dan het mag zijn.</p>
<p>Hier verandert dat de uitkomst niet — 0 van de 1000 is zo extreem dat een wat bredere band hem niet binnenhaalt — maar je weet nu wélke kant de fout op staat, en dat is meer dan “het klopt niet helemaal”.</p></li>
</ul>
<p>En dat is het eerlijke antwoord van deze hele oefening: de aanname die het minst te zien is, is degene die het meest kan kosten.</p>
</div>
</div>
</div>
<div class="kicker">
<p>eindopdracht</p>
</div>
</section>
<section id="diepe-snavel-lichte-pinguïn-het-hele-hoofdstuk-in-één-wolk" class="level2">
<h2 class="anchored" data-anchor-id="diepe-snavel-lichte-pinguïn-het-hele-hoofdstuk-in-één-wolk">Diepe snavel, lichte pinguïn? — het hele hoofdstuk in één wolk</h2>
<p><span class="begrippen">correlatie · regressielijn · residuenplot · derde speler</span></p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eindopdracht">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eindopdracht
</div>
</div>
<div class="callout-body-container callout-body">
<p>De afsluiter van het hele hoofdstuk: de wolk, de lijn en de residuen komen samen in één taak. Zelfde 342 pinguïns, nieuw paar: <strong>gewicht op snaveldiepte</strong>. Allebei ken je — de diepte was de ster van de eerste oefening van dit hoofdstuk, het gewicht rolde in de vorige uit de vinlengte — maar sámen heb je ze nog nooit bekeken. En let op de verrassing die eraan zit te komen.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>peng <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"penguins.csv"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>model.diepte <span class="ot">&lt;-</span> <span class="fu">lm</span>(gewicht <span class="sc">~</span> snaveldiepte, <span class="at">data =</span> peng)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># de scheefheid-functie uit de vorige taak heb je hier weer nodig</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>scheefheid <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">mean</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> <span class="fu">mean</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="fl">1.5</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>En let op de vorm: een artikel valt in <strong>twee gelabelde stukken</strong>, en die volgorde is niet dezelfde als de volgorde waarin je het leerde. Toen mocht de aannamecontrole achteraf, want je moest eerst zien wát je nou eigenlijk controleerde. Nu je het opschrijft voor een lezer gaat hij vóórop, want die wil weten of hij je getallen mag geloven vóórdat hij ze leest.</p>
<section id="methode-en-data-analyse" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse">Methode en data-analyse</h3>
<p><strong>a)</strong> Wat onderzoek je, waarop, en met welke analyse? Schrijf het op zonder één uitkomst te noemen. (twee of drie zinnen; wie of wat er gemeten is, hoeveel, en welke analyse)</p>
<p><strong>b)</strong> Hoeveel pinguïns hebben allebei de maten compleet, en hoeveel staan er in het bestand? (twee getallen)</p>
<p><strong>c)</strong> Doe het keuringsrondje uit dit blok: teken de residuenplot, <strong>beschrijf in één zin de vorm die je ziet</strong>, reken de verhouding tussen de brede en de smalle helft uit, schud hem duizend keer, en vraag de scheefheid op. (die ene zin, de verhouding, de schudband, hoeveel van de duizend het halen, en de scheefheid)</p>
<p><strong>d)</strong> Schrijf de data-analyse-alinea: loop de drie aannames langs en zeg per stuk wat je vond. (drie korte uitspraken, elk met het getal waar je hem op baseert — en zeg welke van de drie eruit springt)</p>
</section>
<section id="resultaten" class="level3">
<h3 class="anchored" data-anchor-id="resultaten">Resultaten</h3>
<p><strong>e)</strong> Begin waar dit hoofdstuk begon: kijk éérst, reken dán. Teken de wolk en reken de correlatie uit. (rapporteer <em>r</em>, en één zin over de wolk)</p>
<p><strong>f)</strong> Trek de lijn en lees hem hardop mét zijn eenheden. (rapporteer <em>b</em><sub>0</sub>, <em>b</em><sub>1</sub>, <em>SE</em>, het 95%-interval en <em>R</em>²)</p>
<p><strong>g)</strong> Herken het lege adres, en centreer daarna de snaveldiepte. (twee getallen, en zeg welk bekend getal je terugziet)</p>
<p><strong>h)</strong> Terug naar de zin die je bij c) opschreef. Een residuenplot hoort een vormeloze wolk te zijn; als jij daar iets anders zag, is dat te meten. Knip de voorspelling in drie even brede stukken, vraag per stuk het gemiddelde residu op, en zeg wat die drie getallen wél en niet bewijzen. (drie getallen, en twee zinnen)</p>
<p><strong>i)</strong> Nu de onthulling. Geef de residuenplot kleuren per soort en vraag het gemiddelde residu per soort op. (drie getallen)</p>
<p><strong>j)</strong> Trek de lijn binnen elke soort apart. (drie hellingen — en let op het teken)</p>
<p><strong>k)</strong> Hoe kan dat? Zet de soortgemiddelden ernaast. (twee rijtjes van drie, en twee zinnen; het verschijnsel heeft een naam)</p>
<p><strong>l)</strong> Schrijf de resultaten-alinea uit, in rapportagevorm. (hele zinnen, verleden tijd, symbolen cursief — en de bevinding is tweeledig)</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Je hebt de aannames bij c) en d) al nagelopen, dus nu de vraag die erachteraan hoort. Dit blok kent <strong>twee</strong> zetten die “schudden” heten: koppels husselen om te zien of de samenhang echt is (uit de eerste oefening van dit hoofdstuk), en residuen husselen om te zien of de spreiding gelijk is (uit dit blok). Draai ze allebei op deze data, en zeg welke van de twee die omgeklapte lijn had gevangen — en welke niet, en waarom niet. (twee uitkomsten, en twee of drie zinnen over wat je voortaan altijd controleert)</p>
</section>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="methode-en-data-analyse-1" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse-1">Methode en data-analyse</h3>
<p><strong>a)</strong> Bijvoorbeeld: <em>“Bij 342 pinguïns van drie soorten onderzochten we of het gewicht samenhangt met de snaveldiepte. We voorspelden het gewicht uit de snaveldiepte met een enkelvoudige regressie, en beoordeelden de residuen op gelijke spreiding, symmetrie en onafhankelijkheid.”</em> Geen enkel getal uit de uitkomsten — dat is de toets waaraan je ziet of de scheiding echt is.</p>
<p><strong>b)</strong> <strong>342</strong> van de <strong>342</strong> rijen zijn compleet op allebei de maten; er valt er geen weg.</p>
<p><strong>c)</strong> De verhouding tussen de brede en de smalle helft is <strong>1.61</strong>, de schudband loopt van <strong>0.89 tot 1.12</strong>, en <strong>geen enkele</strong> van de duizend gehusselde werelden haalt de 1.61. De scheefheid van de residuen is <strong>0.24</strong>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">resid</span>(model.diepte); f <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model.diepte)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>laag <span class="ot">&lt;-</span> f <span class="sc">&lt;=</span> <span class="fu">median</span>(f)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(f, e); <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(e[<span class="sc">!</span>laag]) <span class="sc">/</span> <span class="fu">sd</span>(e[laag])        <span class="co"># → 1.61</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>nep <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  { x <span class="ot">&lt;-</span> <span class="fu">sample</span>(e, <span class="at">replace =</span> <span class="cn">FALSE</span>); <span class="fu">sd</span>(x[<span class="sc">!</span>laag]) <span class="sc">/</span> <span class="fu">sd</span>(x[laag]) })</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nep, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))        <span class="co"># → 0.89 tot 1.12</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nep <span class="sc">&gt;=</span> <span class="fl">1.61</span>)                  <span class="co"># → 0 van de 1000</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="fu">scheefheid</span>(e)                     <span class="co"># → 0.24</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>En de vorm die je opschreef: geen openlopende trechter maar <strong>schuine banen</strong>, van linksboven naar rechtsonder, en het zijn er zo op het oog twee — een linker en een rechter, en die rechter ligt hoger. Dat je de verhouding 1.61 uitrekent betekent dus niet dat je een trechter zíet; het betekent alleen dat de ene helft breder spreidt dan de andere, en dat kan ook door banen komen.</p>
<p><strong>d)</strong> <em>Gelijke spreiding:</em> geschonden, en hard — 1.61 tegen een band die tot 1.12 loopt, en 0 van de 1000 gehusselde werelden halen het. Bij de ozon was 1.65 nog krap; hier is de band smal, want 342 dieren, en valt het echte getal er mijlenver buiten. <em>Normaal verdeeld:</em> geen bezwaar, scheefheid 0.24. Ter vergelijking kun je de vin-lijn erbij pakken, het model uit dit blok waar niets aan de hand was — die zit op 0.31:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scheefheid</span>(<span class="fu">resid</span>(<span class="fu">lm</span>(gewicht <span class="sc">~</span> vinlengte, <span class="at">data =</span> peng)))   <span class="co"># → 0.31</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Deze residuen liggen dus nóg netter om nul dan die van een model waar je niets op aan te merken had. <em>Onafhankelijk:</em> elke pinguïn is één keer gewogen.</p>
<p>Wat eruit springt is dus de <strong>gelijke spreiding</strong>, en let op wat dat wél en niet zegt: er is iets mis, maar niet wát.</p>
</section>
<section id="resultaten-1" class="level3">
<h3 class="anchored" data-anchor-id="resultaten-1">Resultaten</h3>
<p><strong>e)</strong> <em>r</em> = −.47. De wolk hangt omlaag — hoe dieper de snavel, hoe lichter het dier — en twee keer zo sterk als de −.24 waar dit hoofdstuk mee opende.</p>
<p><strong>f)</strong> gewicht = 7488.65 − 191.64 × snaveldiepte, met <em>SE</em> = 19.42, <em>t</em>(340) = −9.87, <em>p</em> &lt; .001, 95% CI [−229.84, −153.45] en <em>R</em>² = .22. Elke millimeter snavel dieper is bijna tweehonderd gram pinguïn minder.</p>
<div class="rcode callout callout-style-default callout-note callout-titled" title="In R · waar de standaardfout en het interval vandaan komen">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In R · waar de standaardfout en het interval vandaan komen
</div>
</div>
<div class="callout-body-container callout-body">
<p>De standaardfout en het interval staan niet in <code>coef()</code>; die haal je hier vandaan:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.diepte)<span class="sc">$</span>coefficients   <span class="co"># → schatting, SE, t en p per rij</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model.diepte)                <span class="co"># → snaveldiepte: -229.8353 tot -153.4502</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.diepte)<span class="sc">$</span>r.squared      <span class="co"># → 0.223</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>(Je scherm geeft meer cijfers dan je opschrijft. In je rapportagezin staat [−229.84, −153.45] — twee decimalen, want dat is APA; hier staat wat R afdrukt, zodat je kunt nakijken of jij hetzelfde voor je hebt.)</p>
</div>
</div>
<p><strong>g)</strong> Het intercept 7488.65 is de voorspelling voor een pinguïn met een snavel van nul millimeter diep, terwijl de ondiepste snavel in het bestand 13.1 mm is — een leeg adres. Na het centreren staat er <strong>4201.75</strong>, en dat getal ken je: het is het gemiddelde gewicht van alle 342, precies zoals toen je in de vorige oefening de vinlengte centreerde. De helling verroert zich niet.</p>
<p><strong>h)</strong> <strong>+217, −255 en +220</strong> gram. Let op dat dit grámmen zijn; er komt bij j) een 217.15 langs die gram per millimeter is, en dat is toeval.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(e, <span class="fu">cut</span>(f, <span class="dv">3</span>), mean)        <span class="co"># → +217   -255   +220</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Over álle punten samen is het gemiddelde residu exact nul — daar is de lijn op gebouwd, dus dat bewijst niets. Maar per stuk hoort het óók ongeveer nul te zijn, en dat is het niet: erboven, eronder, er weer boven. Wat die drie getallen bewijzen is dat er <strong>structuur</strong> in zit; een vormeloze wolk doet dit niet. Dát het schuine banen zijn, zie je alleen in het plaatje.</p>
<p><strong>i)</strong> Adélie <strong>−272.0</strong>, Chinstrap <strong>−225.4</strong>, Gentoo <strong>+458.6</strong> gram.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(f, e, <span class="at">col =</span> <span class="fu">factor</span>(peng<span class="sc">$</span>soort), <span class="at">pch =</span> <span class="dv">16</span>); <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(e, peng<span class="sc">$</span>soort, mean)    <span class="co"># → Adelie -272.0  Chinstrap -225.4  Gentoo 458.6</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>De lijn zit er voor de Adélies gemiddeld 272 gram bóven — ze zijn lichter dan hij belooft — voor de Chinstraps 225 gram, en voor de Gentoo’s zit hij er 459 gram ónder. In het rechterderde van je plaatje zijn 97 van de 98 punten een Gentoo.</p>
<p><strong>j)</strong> Adélie <strong>+217.15</strong>, Chinstrap <strong>+204.62</strong>, Gentoo <strong>+369.44</strong> gram per millimeter. Alle drie <strong>plus</strong>, waar de lijn over alle 342 heen −191.64 zei. Binnen élke soort geldt dus: hoe dieper de snavel, hoe zwáárder het dier. Het teken is omgeklapt, en dit keer niet bij een kale correlatie maar bij een complete regressielijn.</p>
<p><strong>k)</strong> De Gentoo’s zijn veruit de zwaarste dieren (5076 gram, tegen 3701 en 3733) én ze hebben de ondiepste snavels (14.98 mm, tegen 18.35 en 18.42). Dat ene feit — zwaar én ondiep — trekt de hele wolk de verkeerde kant op. Het verschijnsel heet de <strong>Simpsons paradox</strong>: houd je rekening met een derde variabele, dan kan het verband tussen de eerste twee wegvallen of zelfs omdraaien.</p>
<p>En knoop hem vast aan de naam uit de eerste oefening van dit hoofdstuk. Daar heette de derde speler die zich als het verband vermomt <strong>confounding</strong>. Dat is dezelfde vermomming: confounding is wat de derde variabele <em>doet</em>, de Simpsons paradox is hoe het eruitziet als hij het teken helemaal omdraait.</p>
<p><strong>l)</strong> Bijvoorbeeld:</p>
<blockquote class="blockquote">
<p>We voorspelden het gewicht van de pinguïns uit hun snaveldiepte (<em>N</em> = 342). Over alle dieren samen ging elke millimeter meer snaveldiepte samen met 191.64 gram minder gewicht, <em>b</em> = −191.64, <em>SE</em> = 19.42, 95% CI [−229.84, −153.45], <em>R</em>² = .22. Binnen elk van de drie soorten liep het verband echter andersom: daar ging een diepere snavel juist samen met een zwaarder dier (<em>b</em> = 204.62 tot 369.44 gram per millimeter).</p>
</blockquote>
<p>Kijk wat die laatste zin doet: hij haalt het eerste resultaat niet weg, hij zet het in zijn verband. Allebei de helften zijn waar; alleen samen zijn ze eerlijk.</p>
<p><strong>Z)</strong> De twee zetten geven tegengestelde antwoorden, en dat is de hele les.</p>
<p><strong>Koppels husselen</strong> — de zet uit de eerste oefening — had je hier <strong>niets</strong> verteld. Schud je de snaveldieptes los van de gewichten, dan komt geen van de duizend geschudde werelden ook maar in de buurt van −.47. Die samenhang ís er dus. Hij zegt alleen niets over de <em>richting</em> die je eruit leest: <em>echt</em> en <em>waar</em> zijn twee verschillende dingen, en dat wist je sinds de snavels.</p>
<p><strong>Residuen husselen</strong> — de zet uit dit blok — sloeg wél alarm: 1.61 tegen een band die tot 1.12 loopt, 0 van de 1000. Maar hij zei alleen <em>dát</em> er iets mis was, niet wat. Pas het kleuren per soort bij i) gaf de derde speler zijn naam.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>nep.r <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">cor</span>(peng<span class="sc">$</span>snaveldiepte, <span class="fu">sample</span>(peng<span class="sc">$</span>gewicht, <span class="at">replace =</span> <span class="cn">FALSE</span>)))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(nep.r) <span class="sc">&gt;=</span> <span class="fl">0.47</span>)     <span class="co"># → 0 van de 1000 — de samenhang is echt</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nep <span class="sc">&gt;=</span> <span class="fl">1.61</span>)            <span class="co"># → 0 van de 1000 — en de spreiding deugt niet</span></span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Twee keer 0 van de 1000, en ze betekenen het tegenovergestelde van elkaar: de eerste zegt <em>er is hier iets</em>, de tweede zegt <em>en je hebt het verkeerd opgeschreven</em>.</p>
<p>Wat je voortaan altijd controleert voordat je een lijn door een wolk vertrouwt: teken de residuen tegen de voorspelling, en kijk of er <strong>structuur</strong> in zit in plaats van alleen te vragen of ze breed uitlopen. En vraag je bij elke wolk af wie er nog meer in zit — want dezelfde soort die zich in de eerste oefening als een correlatie vermomde, vermomde zich hier als een complete regressielijn.</p>
</section>
</div>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-op-wat-je-gecontroleerd-hebt" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-op-wat-je-gecontroleerd-hebt">Schrijf op wat je gecontroleerd hebt</h2>
<p><span class="begrippen">rapportage van een controle · APA-notatie</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een assumptie-controle hoort in je verslag, en het is de kortste rapportage die je dit hele boek schrijft: één zin als er niks is, twee als er wél iets is. Wat je niet doet, is ’m weglaten — een lezer die niets leest, weet niet of je niets vond of niet gekeken hebt.</p>
<p>Zo ziet ‘wél iets’ eruit:</p>
<blockquote class="blockquote">
<p>We voorspelden de dagelijkse ozonconcentratie uit de maximumtemperatuur (<em>N</em> = 116). De residuen werden visueel geïnspecteerd. De spreiding nam toe met de voorspelde waarde: op de koelere helft van de dagen was <em>SD</em> = 17.47 ppb (<em>n</em> = 59), op de warmere <em>SD</em> = 28.74 ppb (<em>n</em> = 57). De residuen waren rechtsscheef.</p>
</blockquote>
<p>En zo ‘niks aan de hand’:</p>
<blockquote class="blockquote">
<p>We voorspelden het gewicht van de pinguïns uit hun vinlengte (<em>N</em> = 342). De residuen werden visueel geïnspecteerd; de spreiding was gelijkmatig over het bereik van de voorspelde waarden en de verdeling week niet zichtbaar af van normaal.</p>
</blockquote>
<p>Let op de kleine lettertjes. Alleen de symbolen <em>N</em>, <em>n</em> en <em>SD</em> staan cursief, de gewone woorden rechtop. En let op dat er twee n’en zijn: de <strong>hoofdletter</strong> <em>N</em> is je hele bestand, de <strong>kleine</strong> <em>n</em> een groep daarbinnen — hier dus <em>N</em> = 116 dagen, verdeeld over <em>n</em> = 59 koele en <em>n</em> = 57 warme. De zinnen staan in de verleden tijd, want je vertelt wat je gedáán en gevónden hebt. En ze noemen allebei de steekproef, de uitkomst én de voorspeller, zodat ze op eigen benen staan.</p>
<p>Eén woord dat je hier bewust <em>niet</em> schrijft: <strong>“aan de assumpties werd voldaan”</strong>. Dat klinkt als een toets die geslaagd is, en zo werkt het niet — je hebt gekeken, en je zag niets bijzonders. Schrijf op wat je zag.</p>
<p>Jouw beurt: schrijf zo’n zin voor de wind-lijn uit de taak hierboven. Kies zelf welke van de twee vormen erbij past, en verdedig die keuze in één zin.</p>
<p>En dan de eindopdracht, want die verdient een eigen zin. Een omgeklapt teken is de strengste proef op de regel dat een rapportage op eigen benen staat: het getal over alle 342 klopt, en tóch klopt het verhaal pas als de soorten erbij staan. Zo:</p>
<blockquote class="blockquote">
<p>We voorspelden het gewicht van de pinguïns uit hun snaveldiepte (<em>N</em> = 342). Over alle dieren samen ging elke millimeter meer snaveldiepte samen met 191.64 gram minder gewicht, <em>b</em> = −191.64, <em>SE</em> = 19.42, 95% CI [−229.84, −153.45], <em>R</em>² = .22. Binnen elk van de drie soorten liep het verband echter andersom: daar ging een diepere snavel juist samen met een zwaarder dier (<em>b</em> = 204.62 tot 369.44 gram per millimeter).</p>
</blockquote>
<p>Kijk wat die laatste zin doet: hij haalt het eerste resultaat niet weg, hij zet het in zijn verband. Allebei de helften zijn waar; alleen samen zijn ze eerlijk.</p>
<p>Jouw beurt, nog één keer: schrijf diezelfde tweeledige bevinding op in de taal van de correlatie — met <em>r</em> in plaats van <em>b</em> (over alle 342 pinguïns <em>r</em> = −.47, binnen de soorten <em>r</em> = .58 tot .72). Die vorm ken je uit de eerste oefening van dit hoofdstuk; leen hem gerust. En toets bij allebei je zinnen: laat je de tweede helft weg, dan staat er iets wat niet waar is.</p>
</div>
</div>
<div class="boekvorm" data-w="W4">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: de drie aannames aan de residuen afgelezen — welk plaatje je opvraagt, en waaraan je ziet dat het misgaat.</p>
<p>In het boek: <strong>W4 — Hangen ze samen?</strong></p>
<p><em>Daar krijgen de drie alleen hun naam, en staat erbij dat de lijn zélf niets meer eist dan rechtheid. Hier zie je wat de fouten ervan bakken.</em></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Dagelijkse ozonmetingen (delen per miljard, <em>parts per billion</em>) op Roosevelt Island, New York, mei–september 1973; New York State Department of Conservation / National Weather Service. Beschikbaar als de klassieke R-dataset <code>airquality</code>; dit zijn de 116 dagen waarop de ozonmeting gelukt is. Alle getallen in dit blok zijn op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="pagination-link" aria-label="Oefening 3.2 · Enkelvoudige regressie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 3.2 · Enkelvoudige regressie</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_steekproevenverdeling.html" class="pagination-link" aria-label="Oefening 4.1 · Steekproevenverdeling en standaardfout">
        <span class="nav-page-text">Oefening 4.1 · Steekproevenverdeling en standaardfout</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>