<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Meervoudige regressie – GGZ-VS/JASP-werkboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_anova.html" rel="next">
<link href="../20_blokken/blok_power_significant.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">Meervoudige regressie</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">GGZ-VS/JASP-werkboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GGZ-VS/JASP-werkboek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/00_parkeerkaart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De parkeerkaart</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meetniveaus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meetniveaus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gemiddelde en standaardafwijking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_kwartielen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_standaardfout.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standaardfout en non-respons</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De correlatie <em>r</em> en de scatterplot</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De effectgrootte — Cohens <em>d</em></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cronbachs α</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">W6 · Bestaat het verschil echt?</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De <em>p</em>-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets_gepaard_onafhankelijk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De <em>t</em>-toets: gepaard en onafhankelijk</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power_significant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Significantie en power</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Meervoudige regressie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA en η²</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactie en moderatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De odds ratio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Schil (naast het boek)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De kruistabel en χ²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mann_whitney.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De Mann-Whitney-toets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/99_register.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Het register</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Meervoudige regressie</h1>
<p class="subtitle lead"><em>multiple regression</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Vooraf, in één zin:</strong> een tabel met vier voorspellers onder elkaar nodigt uit om naar het sterretje te zoeken, maar de eerste vraag is hoeveel voorspellers er op hoeveel mensen losgelaten zijn — hieronder wordt dezelfde voorspeller pas significant in het model dat níéts verklaart, en waarom dat zo werkt staat onderaan bij <em>Wat het niet zegt</em>.</p>
</blockquote>
<section id="wat-je-ziet" class="level2">
<h2 class="anchored" data-anchor-id="wat-je-ziet">Wat je ziet</h2>
<p><strong>In het kort.</strong> Geen enkel getal, maar een <strong>tabel</strong>: een rijtje voorspellers onder elkaar, elk met een <em>b</em>, een standaardfout en een <em>p</em>, en eronder één regel voor het model als geheel — een <em>F</em> en een R². Dat is een <strong>meervoudige regressie</strong> / <em>multiple regression</em>: één uitkomst, meerdere voorspellers tegelijk. Je komt hem tegen zodra een onderzoek wil weten wat iets voorspelt <em>terwijl</em> er van alles anders meespeelt: leeftijd, geslacht, hoe ernstig iemand begon.</p>
<p>Zo ziet het eruit in het wild:</p>
<blockquote class="blockquote">
<p><em>Voorbeeldfragment, geschreven in de stijl van een resultatensectie — het artikel bestaat niet.</em></p>
<p>Change in total difficulties (SDQ, T0 minus T1; higher = improvement) was regressed on baseline severity (centered), age (centered) and gender in the 24 adolescents who completed the VR intervention. The model did not explain a significant proportion of the variance, F(3, 20) = 1.58, p = .225, R² = .19. Baseline severity was the only predictor approaching significance, b = 0.38, SE = 0.19, t = 1.94, p = .066, 95% CI [−0.03, 0.78]. Neither age (b = 0.27, SE = 0.44, p = .552) nor gender (b = −1.16, SE = 1.95, p = .560) contributed.</p>
</blockquote>
</section>
<section id="wat-er-staat" class="level2">
<h2 class="anchored" data-anchor-id="wat-er-staat">Wat er staat</h2>
<p><strong>In het kort.</strong> Vierentwintig jongeren, drie voorspellers, en een model dat het niet doet: de <em>F</em> van 1.58 met <em>p</em> = .225 zegt dat deze drie samen niet meer verklaren dan toeval kan maken. De R² van .19 zegt dat ze op papier 19% van de verschillen in verbetering dekken — een getal dat groot lijkt en het hier niet is, want met 24 mensen en drie voorspellers haal je die 19% ook zonder dat er iets aan de hand is. En de enige regel die in de buurt komt, baseline, is precies de regel waar je het minst aan hebt. Waarom, dat is de rest van dit blok.</p>
<p>Nu rustig van voren af aan. <strong>Wat een <em>b</em> betekent naast andere <em>b</em>’s.</strong> In de enkelvoudige regressie die je uit <em>Het rechthoekje</em> kent, was <em>b</em> het verschil in de uitkomst dat hoort bij één punt verschil in de voorspeller. Dat blijft zo — er komt één woord bij: <em>terwijl de andere voorspellers gelijk blijven.</em> Hier betekent <em>b</em> = 0.38 dus: <strong>twee jongeren die één SDQ-punt in ernst verschilden bij binnenkomst, verschilden gemiddeld 0.38 punt in verbetering — bij gelijke leeftijd en gelijk geslacht.</strong></p>
<p>Let op de vorm van die zin. Er staat <em>verschilden</em>, geen <em>stegen</em>. Er is hier niets gemanipuleerd: niemand heeft iemands beginscore hoger gezet om te kijken wat er gebeurt. Twee jongeren vergelijken is iets anders dan één jongere veranderen, en de taal moet dat verschil vasthouden. Dat is geen muggenzifterij; het is het enige wat een lezer tegen de verleiding beschermt om er een oorzaak van te maken.</p>
<p><strong>Wat “gecorrigeerd voor” doet.</strong> Elke <em>b</em> in deze tabel is berekend met de andere twee erin. Je kunt het lezen als: eerst haalt het model uit de verbetering weg wat leeftijd en geslacht ervan kunnen verklaren, en pas over wat er dan nog ligt, legt het de lijn voor baseline. Vandaar de Nederlandse formulering die je in artikelen ziet — <em>gecorrigeerd voor leeftijd en geslacht</em>, of <em>adjusted for</em>. Wat je overhoudt, is het stuk van de samenhang dat níét al door de andere voorspellers verteld werd.</p>
<p><strong>Wat de <em>F</em> en R² samen zeggen.</strong> De R² van .19 is het aandeel van de verschillen in verbetering dat het hele model dekt: negentien procent. De <em>F</em> stelt daar de nuchtere vraag bij — is dat meer dan je met drie willekeurige voorspellers op 24 mensen sowieso zou halen? Antwoord: nee, <em>p</em> = .225. Kijk daarom altijd eerst naar die regel. Een tabel vol voorspellers waarvan het model als geheel niet significant is, is een tabel waarin je geen enkele individuele regel als bevinding mag oppakken — en dat is precies wat er in dit fragment gebeurt.</p>
<p><strong>En de baseline-regel dan, met <em>p</em> = .066?</strong> Twee dingen. Ten eerste is .066 groter dan .05, en “randsignificant” is geen aparte categorie — het betrouwbaarheidsinterval [−0.03, 0.78] loopt over de nul heen, dus een verband van nul past nog steeds bij deze data. Ten tweede, en belangrijker: zelfs als deze regel wél een sterretje had gehad, zou hij je weinig hebben verteld. Waarom niet, staat bij <em>Wat het niet zegt</em>.</p>
</section>
<section id="waar-het-vandaan-komt" class="level2">
<h2 class="anchored" data-anchor-id="waar-het-vandaan-komt">Waar het vandaan komt</h2>
<p>Dit blok leunt op de boek-eenheid <em>Meer dan één verschil</em>. Daar wordt de stap gezet die dit hele blok draagt: van één rechthoekje naar meerdere. Zolang je één voorspeller hebt, is regressie een lijn door een wolk. Komt er een tweede bij, dan wordt het wegrekenen — je haalt uit de uitkomst eerst weg wat de ene voorspeller verklaart, en kijkt wat de andere over de rest nog te zeggen heeft. Het boek tekent dat als een tweeluik: dezelfde wolk, één keer met en één keer zonder wat de eerste voorspeller al had opgeslokt.</p>
<p>Twee oude bekenden komen daarbij terug. R² ken je als <em>r</em>² uit het correlatie-blok — hetzelfde idee, nu met meerdere verklaarders tegelijk. En de <em>F</em> ken je van de ANOVA: nog steeds een breuk van verklaarde en onverklaarde spreiding, alleen heet “de groepen” hier “de voorspellers samen”.</p>
</section>
<section id="zelf-doen-in-jasp" class="level2">
<h2 class="anchored" data-anchor-id="zelf-doen-in-jasp">Zelf doen in JASP</h2>
<p><a href="../10_data/verschilscore_mra.csv" class="data-download" download="verschilscore_mra.csv">⬇ Download de data — <code>verschilscore_mra.csv</code></a></p>
<p>Bij dit blok hoort <code>verschilscore_mra.csv</code>: 24 rijen, zeven kolommen — <code>id</code>, <code>tds_t0</code> en <code>tds_t1</code> (de SDQ-totaalscore vóór en na), <code>verbetering</code> (T0 min T1, dus positief = minder klachten), <code>leeftijd</code>, <code>geslacht</code> en <code>diagnose</code>. Het zijn <strong>dezelfde 24 jongeren als in het <em>t</em>-toets-blok</strong>; er is alleen bij gekomen wat je voor dit model nodig hebt. De rijen zijn gegenereerd — er zit geen echte jongere in — en ze reproduceren precies de getallen uit het fragment.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open het bestand in JASP (menu linksboven → Open).</li>
<li>Klik in de balk bovenin op <strong>Regression</strong> en kies <strong>Linear Regression</strong>.</li>
<li>Sleep <code>verbetering</code> naar <strong>Dependent Variable</strong>, <code>tds_t0</code> en <code>leeftijd</code> naar <strong>Covariates</strong>, en <code>geslacht</code> naar <strong>Factors</strong>.</li>
<li>Vink onder <strong>Statistics</strong> aan: <strong>Estimates</strong>, <strong>Model fit</strong> en <strong>Confidence intervals</strong>.</li>
<li>Wil je de twee modellen naast elkaar zien: open het tabblad <strong>Model</strong>, maak een tweede <strong>Block</strong> aan en zet <code>diagnose</code> daarin. JASP toont dan model 1 en model 2 onder elkaar, met de R² van beide.</li>
</ol>
</div>
</div>
<p>In de tabel rechts staat nu bij <code>tds_t0</code> een <em>b</em> van 0.377 met SE 0.194, <em>t</em> = 1.944, <em>p</em> = .066 en een 95%-interval van [−0.03, 0.78]; bij <code>leeftijd</code> 0.266 (<em>p</em> = .552) en bij geslacht −1.155 (<em>p</em> = .560). In de Model Summary: R² = .192, adjusted R² = .071, en in de ANOVA-regel <em>F</em>(3, 20) = 1.58, <em>p</em> = .225. Leg het fragment ernaast — dezelfde getallen.</p>
<p>Eén ding valt op als je goed kijkt: het fragment noemt baseline <em>centered</em> en jij sleepte gewoon <code>tds_t0</code> naar binnen. Toch komen de <em>b</em>, de <em>p</em> en het interval exact overeen. Dat klopt: centreren verschuift alleen het nulpunt, en daarmee de intercept — de helling verandert niet. Wat centreren wél doet, is de intercept betekenis geven (de verwachte verbetering bij een gemiddelde beginscore in plaats van bij een SDQ van 0, wat niemand heeft). Het is dus een leesbaarheidstruc, geen ander model.</p>
</section>
<section id="zelf-opschrijven" class="level2">
<h2 class="anchored" data-anchor-id="zelf-opschrijven">Zelf opschrijven</h2>
<div class="apa callout callout-style-default callout-note callout-titled" title="Schrijf het op — de meervoudige regressie">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Schrijf het op — de meervoudige regressie
</div>
</div>
<div class="callout-body-container callout-body">
<p>Voor je eigen Nederlandstalige literatuurstudie:</p>
<blockquote class="blockquote">
<p>De verandering in totale probleemscore werd voorspeld uit de beginscore, leeftijd en geslacht. Het model verklaarde geen significant deel van de verschillen in verandering, <em>F</em>(3, 20) = 1.58, <em>p</em> = .225, R² = .19. Jongeren die één punt hoger begonnen, verbeterden gemiddeld 0.38 punt meer, maar dit verband was niet significant, <em>b</em> = 0.38, <em>SE</em> = 0.19, <em>p</em> = .066, 95% BI [−0.03, 0.78].</p>
</blockquote>
<p>Drie werkafspraken daarbij:</p>
<ul>
<li><strong>Rapporteer het model vóór de regels.</strong> <em>F</em>, R² en het aantal voorspellers eerst; pas daarna de losse coëfficiënten. Wie met een significante regel begint, verzwijgt de vraag of het model überhaupt iets deed.</li>
<li><strong>Noem N én het aantal voorspellers.</strong> Vier voorspellers op 24 mensen is een ander onderzoek dan vier op 400, ook als de tabellen identiek ogen. Zonder die twee getallen kan je lezer de tabel niet wegen.</li>
<li><strong>Verschil-taal, geen verandering-taal.</strong> “Jongeren die hoger begonnen, verbeterden meer” — niet “hoger beginnen zorgt voor meer verbetering”. Er is niets gemanipuleerd; er zijn alleen mensen met elkaar vergeleken.</li>
</ul>
</div>
</div>
</section>
<section id="wat-het-niet-zegt" class="level2">
<h2 class="anchored" data-anchor-id="wat-het-niet-zegt">Wat het niet zegt</h2>
<p>De verleidelijkste redenering die je over dit fragment kunt opschrijven is: <em>“baseline voorspelt verbetering (p = .066, bijna significant), dus wie zieker binnenkomt, heeft meer baat bij de VR-training.”</em> Eén zin, drie fouten.</p>
<p><strong>“Bijna significant.”</strong> Die categorie bestaat niet. Het interval loopt van −0.03 tot 0.78: nul zit er nog in, dus “geen verband” is een uitkomst die bij deze data past. En het model als geheel deed het niet (<em>p</em> = .225). Wat je mag opschrijven is dat dit onderzoek geen significante voorspellers van verandering vond — niet dat het er bijna één vond.</p>
<p><strong>“Wie zieker binnenkomt, heeft meer baat.”</strong> Hier zit de val die in pre-post-onderzoek zonder controlegroep altijd klaarligt: <strong>regressie naar het gemiddelde</strong>. Wie hoog scoort op een meting, zit daar deels hoog door een slechte dag of door meetruis; bij een tweede meting zakt dat stukje ruis vanzelf weg. Hoog beginnen voorspelt daarom bijna mechanisch een grotere daling — ook als de behandeling niets doet, en zelfs als er helemaal geen behandeling is. De baseline-regel in deze tabel is dus de regel waar je het minst uit mag concluderen, niet de meest interessante. Wil je weten of de VR-training werkt, dan heb je een groep nodig die hem niet kreeg.</p>
<p><strong>“Gecorrigeerd voor leeftijd en geslacht, dus het ligt niet daaraan.”</strong> Corrigeren haalt eruit wat je hebt gemeten, en niets anders. Alles wat niet in de tabel staat — motivatie, thuissituatie, of iemand er tegelijk een andere behandeling bij kreeg — zit nog gewoon in dat verband. “Gecorrigeerd voor” is geen synoniem van “dus causaal”; het is een lijst van wat er wél is meegenomen, en die lijst lees je als lezer juist op wat er níét in staat.</p>
<p><strong>En dan de belangrijkste, want die kun je in dit databestand zelf zien gebeuren.</strong> Voeg aan dit model de diagnose toe — zeven categorieën, dus zes dummy’s erbij — en je hebt negen voorspellers op 24 mensen. Wat er dan gebeurt:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>model 1 (3 voorspellers)</th>
<th>model 2 (9 voorspellers)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R²</td>
<td>.19</td>
<td><strong>.45</strong></td>
</tr>
<tr class="even">
<td>adjusted R²</td>
<td>.07</td>
<td>.10</td>
</tr>
<tr class="odd">
<td><em>F</em></td>
<td><em>F</em>(3, 20) = 1.58, <em>p</em> = .225</td>
<td><em>F</em>(9, 14) = 1.27, <em>p</em> = .330</td>
</tr>
<tr class="even">
<td>baseline</td>
<td><em>b</em> = 0.38, <em>p</em> = .066</td>
<td><em>b</em> = 0.56, <strong><em>p</em> = .018</strong></td>
</tr>
</tbody>
</table>
<p>Lees die tabel van links naar rechts en er gebeurt iets ongemakkelijks. De R² springt van .19 naar .45 — het model lijkt twee keer zo goed. Het model als geheel wordt er níét beter van (<em>p</em> gaat van .225 naar .330). En de baseline-regel, die net nog niet significant was, <strong>krijgt een sterretje</strong>: <em>p</em> = .018.</p>
<p>Er is niets veranderd aan de wereld. Er is alleen ruis toegevoegd: dummy’s voor categorieën waarvan er drie <strong>precies één jongere</strong> bevatten. Zo’n dummy kan die ene persoon perfect natekenen, en dat kost niets aan uitleg maar wel aan vrijheidsgraden — van 20 naar 14. R² kán daarbij alleen maar omhoog: elke voorspeller die je toevoegt, verklaart altijd iets, al is het toeval. Dáárvoor bestaat adjusted R², die een verwachte toevalswinst aftrekt; die blijft hier rond de tien procent hangen en verraadt zo dat de sprong lucht was.</p>
<p>Dit is geen verzonnen schrikbeeld. In het echte onderzoek waar dit cohort op gebaseerd is, gebeurde precies dit: het eerste model had negen voorspellers op 24 deelnemers, en daarin leek een diagnose-dummy significant (<em>p</em> = .017). Afslanken naar drie voorspellers en er bleef niets van over. Bij ons springt het sterretje op een andere regel, maar het mechanisme is hetzelfde.</p>
<p><strong>De leesregel die je hieraan overhoudt:</strong> tel bij elke regressietabel eerst het aantal voorspellers en zoek de N erbij. Een vuistregel die in de literatuur rondgaat is tien tot vijftien deelnemers per voorspeller; negen voorspellers vragen dus honderd tot honderdvijftig mensen, en dit onderzoek had er 24. Zie je een tabel met veel voorspellers, weinig deelnemers en één sterretje — dan heb je iets gevonden voor het kopje “beperkingen”, geen bevinding.</p>
</section>
<section id="oefening" class="level2">
<h2 class="anchored" data-anchor-id="oefening">Oefening</h2>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Oefening">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Oefening
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Leesopgave.</strong> Hieronder een voorbeeldfragment (verzonnen). Vertel in gewone Nederlandse zinnen wat er staat. Wat weet je na deze zinnen wél, en wat niet? En welke twee getallen zou je als eerste opzoeken voor je er iets over opschrijft?</p>
<blockquote class="blockquote">
<p>A multiple regression with eight predictors (age, gender, education, duration of illness, medication use, comorbidity, therapist experience and baseline severity) on 31 patients explained 52% of the variance in treatment outcome, R² = .52. Therapist experience emerged as a significant predictor, b = 2.14, p = .041. The authors recommend matching experienced therapists to complex cases.</p>
</blockquote>
<p><strong>Doe-opgave.</strong> Draai op <code>verschilscore_mra.csv</code> eerst het model met drie voorspellers en daarna dat met negen (diagnose erbij, als tweede Block). Noteer van allebei R², adjusted R², <em>F</em> met vrijheidsgraden, en de regel van <code>tds_t0</code>. Beantwoord dan drie vragen. (1) Welk getal in de tweede tabel zou je op het verkeerde been zetten als je alleen díé tabel zag? (2) Waarom is adjusted R² nauwelijks meegestegen met R²? (3) De vrijheidsgraden van de <em>F</em> gingen van (3, 20) naar (9, 14) — reken na waar die 14 vandaan komt, en wat dat betekent voor hoe scherp dit onderzoek nog iets kán aantonen.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Uitwerkingen — klik open">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Uitwerkingen — klik open
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="uitwerking-leesopgave" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-leesopgave">Uitwerking leesopgave</h3>
<p>Wat er staat: acht voorspellers op 31 patiënten verklaren samen 52% van de verschillen in behandeluitkomst, en één daarvan — ervaring van de behandelaar — heeft een <em>p</em> onder de .05. Wat je wél weet: in déze 31 patiënten hangt ervaring samen met uitkomst, in dit model. Wat je niet weet: zo’n beetje al het andere. Acht voorspellers op 31 mensen is ongeveer vier mensen per voorspeller, ver onder elke vuistregel; een R² van .52 is bij die verhouding precies wat je van toeval mag verwachten, want elke voorspeller verklaart altijd íéts.</p>
<p>De twee getallen die je als eerste opzoekt: de <strong>adjusted R²</strong> (die staat er niet, en zal fors lager liggen) en de <strong><em>F</em> van het hele model met zijn vrijheidsgraden en <em>p</em></strong> (die staat er ook niet — en zonder die regel weet je niet eens of het model als geheel iets deed). Ontbreken ze allebei, dan is de enige eerlijke zin in je literatuurstudie dat het onderzoek een verband rapporteert dat op deze steekproefgrootte niet te onderscheiden is van toeval. En de aanbeveling van de auteurs — ervaren behandelaars koppelen aan complexe casus — is een beleidsadvies op één <em>p</em>-waarde uit een overladen model, in een onderzoek waarin niemand behandelaars heeft toegewezen. Dat is twee stappen te ver: van samenhang naar oorzaak, en van één regel naar beleid.</p>
</section>
<section id="uitwerking-doe-opgave" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-doe-opgave">Uitwerking doe-opgave</h3>
<p>De twee modellen naast elkaar: model 1 geeft R² = .192, adjusted R² = .071, <em>F</em>(3, 20) = 1.58, <em>p</em> = .225, met <code>tds_t0</code> op <em>b</em> = 0.377, <em>SE</em> = 0.194, <em>p</em> = .066. Model 2 geeft R² = .450, adjusted R² = .097, <em>F</em>(9, 14) = 1.27, <em>p</em> = .330, met <code>tds_t0</code> op <em>b</em> = 0.563, <em>SE</em> = 0.211, <em>p</em> = .018.</p>
<ol type="1">
<li>Het getal dat je op het verkeerde been zet, is die <em>p</em> = .018 — of, als je alleen naar het model kijkt, de R² van .45. Beide zien er sterker uit dan model 1, terwijl het model als geheel juist minder significant werd. (2) Adjusted R² stijgt nauwelijks omdat hij precies corrigeert voor wat hier gebeurde: hij trekt van R² af wat je van puur toeval mocht verwachten gegeven het aantal voorspellers. Zes extra dummy’s leveren op papier veel op en na aftrek bijna niets — dat gaatje tussen .45 en .10 ís de overfit, zichtbaar gemaakt. (3) De 14: 24 deelnemers min 9 voorspellers min 1 voor de intercept. Elke voorspeller kost een vrijheidsgraad, en met 14 over is de toets bot geworden — dezelfde data, minder scherpte. Dat is de prijs van voorspellers toevoegen, en die betaal je ook als ze niets verklaren.</li>
</ol>
</section>
</div>
</div>
</div>
<div class="boekvorm" data-w="W8">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: meerdere voorspellers tegelijk, elke <em>b</em> gelezen als “bij gelijke andere voorspellers” — en de vraag hoeveel voorspellers er op hoeveel mensen los mogen.</p>
<p>In het boek: <strong>W8 — Meer dan één verschil</strong>.</p>
<p><em>Daar gaat het van één rechthoekje naar meerdere: eerst wegrekenen wat de ene voorspeller al verklaart, dan kijken wat de volgende over de rest nog te zeggen heeft.</em></p>
</div>
<div class="werk">
<p>TODO: stem-pas — dit blok is nog niet langs Bens transcript-units gelegd (Bib-query op meervoudige regressie / confounding / overfit). Data zijn expliciet synthetisch (<code>verschilscore_mra.csv</code>, gegenereerd uit hetzelfde cohort als het <em>t</em>-toets-blok); het anker en de bewuste afwijking staan in de kop van <code>genereer_verschilscore_mra.R</code>.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_power_significant.html" class="pagination-link" aria-label="Significantie en power">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Significantie en power</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_anova.html" class="pagination-link" aria-label="ANOVA en η²">
        <span class="nav-page-text">ANOVA en η²</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>