<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Interactie en moderatie – GGZ-VS/JASP-werkboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">Interactie en moderatie</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">GGZ-VS/JASP-werkboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GGZ-VS/JASP-werkboek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/00_parkeerkaart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De parkeerkaart</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meetniveaus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meetniveaus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gemiddelde en standaardafwijking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_kwartielen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_standaardfout.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standaardfout en non-respons</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De correlatie <em>r</em> en de scatterplot</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De effectgrootte — Cohens <em>d</em></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cronbachs α</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">W6 · Bestaat het verschil echt?</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De <em>p</em>-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets_gepaard_onafhankelijk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De <em>t</em>-toets: gepaard en onafhankelijk</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power_significant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Significantie en power</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meervoudige regressie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA en η²</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Interactie en moderatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De odds ratio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Schil (naast het boek)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De kruistabel en χ²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mann_whitney.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De Mann-Whitney-toets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/99_register.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Het register</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Interactie en moderatie</h1>
<p class="subtitle lead"><em>interaction &amp; moderation</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Vooraf, in één zin:</strong> een interactie betekent dat het effect van het ene ding afhangt van het andere — en zodra dat zo is, bestaat “het gemiddelde effect” voor niemand echt; waarom je dan de hoofdeffecten niet zomaar mag lezen, staat onderaan bij <em>Wat het niet zegt</em>.</p>
</blockquote>
<section id="wat-je-ziet" class="level2">
<h2 class="anchored" data-anchor-id="wat-je-ziet">Wat je ziet</h2>
<p><strong>In het kort.</strong> Een kruisje tussen twee variabelenamen, met een <em>F</em> en een <em>p</em> erachter: group × time, F(1, 116) = 6.76, p = .010. Dat kruisje is een <strong>interactie</strong> / <em>interaction</em> — een antwoord op de vraag <em>hangt het effect van het één af van het ander?</em> In regressie-taal heet hetzelfde idee <strong>moderatie</strong> / <em>moderation</em>: de ene variabele modereert (stuurt bij) het effect van de andere. Twee woorden, één verschijnsel.</p>
<p>Zo ziet hij eruit in het wild:</p>
<blockquote class="blockquote">
<p><em>Voorbeeldfragment, geschreven in de stijl van een resultatensectie — het artikel bestaat niet.</em></p>
<p>Dyadic adjustment (DAS) was assessed in 30 couples before (T0) and after (T1) the patient’s treatment. A significant group × time interaction emerged, F(1, 116) = 6.76, p = .010, partial η² = .06: patients’ DAS scores increased from baseline (M = 94.0) to post-treatment (M = 109.1), whereas partners’ scores remained essentially unchanged (M = 108.1 vs.&nbsp;M = 108.0).</p>
</blockquote>
</section>
<section id="wat-er-staat" class="level2">
<h2 class="anchored" data-anchor-id="wat-er-staat">Wat er staat</h2>
<p><strong>In het kort.</strong> Dertig koppels waarvan één partner in behandeling was, vulden vóór en na de behandeling een relatiekwaliteitslijst in. De patiënten gingen er ruim vijftien punten op vooruit; hun partners bewogen niet. De winst over tijd is dus niet één getal — hij <em>hangt af</em> van wie je het vraagt. Dát is de interactie, en de <em>F</em> van 6.76 toetst precies dat: verschillen de twee winsten van elkaar?</p>
<p>Nu hetzelfde, rustig en van voren af aan. Vier celgemiddelden, in een tabelletje:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>T0</th>
<th>T1</th>
<th>winst</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>patiënt</td>
<td>94.0</td>
<td>109.1</td>
<td>+15.1</td>
</tr>
<tr class="even">
<td>partner</td>
<td>108.1</td>
<td>108.0</td>
<td>−0.1</td>
</tr>
</tbody>
</table>
<p>De patiënten beginnen laag — geen wonder, zij zitten in de klachten — en klimmen naar het niveau van hun partners. De partners beginnen hoger en blijven daar staan. De interactie is het <strong>verschil ván de verschillen</strong>: +15.1 tegenover −0.1, een verschil-in-verschillen van 15.2 punten. Op dat ene getal — is 15.2 te veel om toeval te zijn? — staat de <em>F</em> van 6.76 en de <em>p</em> van .010.</p>
<p>Teken het en je ziet het meteen. Zet de twee meetmomenten op de x-as en trek per rol een lijn door de twee gemiddelden: de patiëntenlijn klimt, de partnerlijn ligt vlak. <strong>Twee lijnen die niet parallel lopen — dat ís een interactie.</strong> Liepen ze wél parallel (allebei klimmend, allebei vlak, maakt niet uit — als de winst maar gelijk was), dan was er geen interactie en volstond één gemiddeld effect voor iedereen. Nu niet: de zin “de behandeling verhoogt de relatiekwaliteit” is te grof, want het hangt ervan af <em>wíens</em> relatiekwaliteit je bedoelt. In moderatie-taal: rol modereert het effect van tijd.</p>
<p>En de partiële η² van .06 zegt, net als bij elke ANOVA, hoeveel van de variantie dit stukje voor zijn rekening neemt — hier een bescheiden, maar duidelijk aanwezig deel.</p>
</section>
<section id="waar-het-vandaan-komt" class="level2">
<h2 class="anchored" data-anchor-id="waar-het-vandaan-komt">Waar het vandaan komt</h2>
<p>Dit is de boek-eenheid <em>Verschil in verschil</em>, en de naam is het hele idee: je kijkt niet naar een verschil, maar naar de vraag of dat verschil zélf verschilt. Daar leer je dat één gemiddeld effect alleen volstaat zolang de lijnen parallel lopen — en dat je, zodra ze dat niet doen, het verhaal in tweeën moet vertellen: één effect per groep, niet één effect voor allemaal.</p>
<p>Neem ook de leesvolgorde uit het boek mee, want die is bij een 2×2-tabel als deze goud waard: <strong>eerst de interactie, dan pas de hoofdeffecten</strong>. Is de interactie afwezig, dan mag je de hoofdeffecten gewoon lezen. Is hij aanwezig — zoals hier — dan zijn de hoofdeffecten gemiddelden over groepen die niet hetzelfde beleven, en dan wonen de echte antwoorden in de vier cellen. Waarom dat zo is, proef je zo meteen aan een concreet getal.</p>
</section>
<section id="zelf-doen-in-jasp" class="level2">
<h2 class="anchored" data-anchor-id="zelf-doen-in-jasp">Zelf doen in JASP</h2>
<p><a href="../10_data/groep_tijd_das.csv" class="data-download" download="groep_tijd_das.csv">⬇ Download de data — <code>groep_tijd_das.csv</code></a></p>
<p>Bij dit blok hoort het databestand <code>groep_tijd_das.csv</code>: 120 rijen, vijf kolommen — <code>id</code> (metingnummer), <code>koppel_id</code> (k01 t/m k30), <code>rol</code> (patient of partner), <code>meetmoment</code> (T0 of T1) en <code>das_score</code> (ervaren relatiekwaliteit, DAS-achtig, hier lopend van 69 tot 142; hoger is beter). Elke rij is één méting, geen persoon: dit heet <strong>long format</strong>, en 30 koppels × 2 rollen × 2 momenten geeft de 120 rijen. De data zijn gegenereerd — er zit geen echt koppel in — en ze reproduceren precies de uitkomsten uit het fragment.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open het bestand in JASP (menu linksboven → Open).</li>
<li>Klik in de balk bovenin op <strong>ANOVA</strong> en kies onder Classical <strong>ANOVA</strong>.</li>
<li>Sleep <code>das_score</code> naar <strong>Dependent Variable</strong> en zet <code>rol</code> én <code>meetmoment</code> allebei in <strong>Fixed Factors</strong>; <code>id</code> en <code>koppel_id</code> laat je staan waar ze staan. Kijk even onder <strong>Model</strong>: JASP heeft daar naast de twee losse factoren ook <code>rol ✻ meetmoment</code> gezet — dát is de interactieterm, en die moet erin blijven.</li>
<li>Vink onder <strong>Display</strong> aan: <strong>Descriptive statistics</strong> en <strong>Estimates of effect size</strong> (η², of partial η² — hier scheelt het weinig).</li>
<li>Open <strong>Descriptives plots</strong> en sleep <code>meetmoment</code> naar <strong>Horizontal Axis</strong> en <code>rol</code> naar <strong>Separate Lines</strong>. Dit is de interactieplot.</li>
</ol>
</div>
</div>
<p>In de ANOVA-tabel rechts staat nu de regel <code>rol ✻ meetmoment</code>: F(1, 116) = 6.76, p = .010, η² = .06. In de Descriptives-tabel de vier cellen: patiënt 94.00 → 109.07, partner 108.10 → 108.00 (alle vier de standaardafwijkingen rond de 16). En in de plot: de klimmende patiëntenlijn, de vlakke partnerlijn — niet parallel. Leg het fragment ernaast: precies de getallen die daar stonden. JASP rekent; jij leest.</p>
<p>Eén eerlijkheidje voor de liefhebber: we doen hier alsof alle 120 metingen los van elkaar staan, terwijl T0 en T1 van dezelfde persoon komen en patiënt en partner uit hetzelfde koppel. Een echt artikel zou daar met een repeated-measures- of mixed-model rekening mee houden. Voor het lezen van de interactie verandert dat niets aan het idee — het verschil-van-de-verschillen blijft het verschil-van-de-verschillen — maar weet dat de nette variant bestaat.</p>
</section>
<section id="zelf-opschrijven" class="level2">
<h2 class="anchored" data-anchor-id="zelf-opschrijven">Zelf opschrijven</h2>
<div class="apa callout callout-style-default callout-note callout-titled" title="Schrijf het op — de interactie">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Schrijf het op — de interactie
</div>
</div>
<div class="callout-body-container callout-body">
<p>Voor je eigen Nederlandstalige literatuurstudie:</p>
<blockquote class="blockquote">
<p>Bij koppels waarvan één partner in behandeling was, steeg de door de patiënt ervaren relatiekwaliteit (DAS) van gemiddeld 94.0 naar 109.1, terwijl die van de partner vrijwel onveranderd bleef (108.1 naar 108.0); dit verschil in verandering was significant (interactie rol × meetmoment, <em>F</em>(1, 116) = 6.76, <em>p</em> = .010, partiële η² = .06).</p>
</blockquote>
<p>Drie werkafspraken daarbij:</p>
<ul>
<li><strong>Schrijf de interactie altijd uit in celgemiddelden.</strong> “Er was een significante interactie” is voor je lezer een lege huls; +15.1 tegenover −0.1 vertelt het verhaal. De <em>F</em> en de <em>p</em> zijn de handtekening, de cellen zijn de brief.</li>
<li><strong>Noem beide kanten.</strong> Ook de groep waar níks gebeurde — juist die. De vlakke partnerlijn is de helft van de bevinding.</li>
<li><strong>Rapporteer géén los hoofdeffect</strong> (“de scores stegen over tijd”) als er een duidelijke interactie is — waarom, staat hieronder.</li>
</ul>
</div>
</div>
</section>
<section id="wat-het-niet-zegt" class="level2">
<h2 class="anchored" data-anchor-id="wat-het-niet-zegt">Wat het niet zegt</h2>
<p>De verleidelijkste redenering die je over dit fragment kunt opschrijven is: <em>“significante interactie, dus de behandeling werkt bij de patiënten wel en bij de partners niet — en gemiddeld genomen verbetert de relatiekwaliteit.”</em> Drie haarscheurtjes, één per bijzin.</p>
<p><strong>“Dus bij de patiënten wél.”</strong> De interactie-toets zegt dát de twee winsten van elkaar verschillen — niet hoe groot elke winst afzonderlijk is, en zelfs niet óf elke winst afzonderlijk significant is. Voor die vragen moet je naar de celgemiddelden en naar aparte toetsen per groep (artikelen noemen die <em>simple effects</em>). Hier is dat onderscheid mild — +15.1 tegen −0.1 laat weinig te raden over — maar de interactie kan ook significant zijn bij +12 tegen +4: twee groepen die állebei opknappen, alleen niet even hard. “Interactie” betekent nooit automatisch “werkt-wel versus werkt-niet”.</p>
<p><strong>En omgekeerd geldt het ook.</strong> Een níét-significante interactie bewijst niet dat het effect voor beide groepen gelijk is. Interactie-toetsen vragen veel power — je toetst een verschil tussen verschillen, en daar stapelt de ruis van vier cellen zich in op. Een studie die met dertig koppels géén significante interactie vindt en concludeert “de winst was voor patiënt en partner gelijk”, heeft afwezigheid van bewijs verward met bewijs van afwezigheid. Die valkuil ken je uit het boek; bij interacties is hij extra diep.</p>
<p><strong>“Gemiddeld genomen verbetert de relatiekwaliteit.”</strong> Dat is het hoofdeffect van meetmoment, en het is in deze data zelfs significant (<em>p</em> = .012): gemiddeld over iedereen stijgen de scores zo’n 7.5 punten. Maar kijk wie dat getal beschrijft: de patiënten wonnen 15, de partners 0. <strong>Niemand won 7.5.</strong> Bij een sterke interactie is het hoofdeffect een gemiddelde over groepen die verschillende dingen meemaken — een getal zonder eigenaar. Daarom de leesvolgorde: eerst de interactie; pas als die er niet is, zijn de hoofdeffecten leesbaar als verhaal over iedereen.</p>
<p>En los daarvan het inhoudelijke voorbehoud dat je bij elk design zonder controlegroep maakt: dat de patiënten opknapten <em>tijdens</em> de behandeling zegt nog niet dat het <em>dóór</em> de behandeling was. De interactie vertelt je bij wie de verandering zat — niet waar hij vandaan kwam.</p>
</section>
<section id="oefening" class="level2">
<h2 class="anchored" data-anchor-id="oefening">Oefening</h2>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Oefening">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Oefening
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Leesopgave.</strong> Hieronder twee voorbeeldfragmenten (verzonnen), elk met een conclusie eronder. Zeg per fragment of de conclusie uit de cijfers volgt — en zo niet, wat er wél staat.</p>
<blockquote class="blockquote">
<p>Study A (N = 300): a significant treatment × age group interaction was found, F(1, 296) = 8.10, p = .005. Younger patients improved by 9.8 points, older patients by 3.9 points. <em>Conclusie van de auteurs: “the intervention is effective in younger, but not in older patients.”</em></p>
<p>Study B (N = 28): the treatment × gender interaction was not significant, F(1, 24) = 1.95, p = .175. <em>Conclusie van de auteurs: “the intervention works equally well for men and women.”</em></p>
</blockquote>
<p><strong>Doe-opgave.</strong> Draai de analyse van hierboven (<code>groep_tijd_das.csv</code>) en pak de Descriptives-tabel erbij. Reken de interactie na op een kladblaadje: winst van de patiënten, winst van de partners, en het verschil tussen die twee — kom je op de 15.2 waar de <em>F</em> over gaat? Kijk daarna in de ANOVA-tabel naar de regel <code>meetmoment</code> (het hoofdeffect van tijd, <em>p</em> = .012) en beantwoord voor jezelf: welke gemiddelde winst hoort daarbij, en van wie in dit bestand is dat getal een eerlijke beschrijving?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Uitwerkingen — klik open">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Uitwerkingen — klik open
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="uitwerking-leesopgave" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-leesopgave">Uitwerking leesopgave</h3>
<p><strong>Studie A:</strong> de conclusie zegt meer dan de cijfers. De interactie is significant en de jongeren winnen inderdaad meer — maar de ouderen winnen óók nog 3.9 punten, en of dát effect op zichzelf significant en klinisch betekenisvol is, staat er niet. “Effectief bij jong, niet bij oud” leest een <em>verschil in effect</em> als een <em>aan/uit-knop</em>. Wat er wél staat: de interventie lijkt bij jongere patiënten dúidelijk meer op te leveren; over de ouderen is de eerlijke samenvatting “minder winst, en uit dit fragment niet te zeggen of die winst echt is”.</p>
<p><strong>Studie B:</strong> klassieker. Achtentwintig deelnemers, verdeeld over vier cellen — een interactie-toets heeft hier nauwelijks power, en <em>p</em> = .175 betekent dan vooral “deze studie kon het verschil niet zien”, niet “het verschil is er niet”. “Works equally well” is bewijs van afwezigheid claimen waar alleen afwezigheid van bewijs ligt. Wat er wél staat: geen aantoonbaar verschil tussen mannen en vrouwen <em>in deze kleine steekproef</em> — meer niet.</p>
</section>
<section id="uitwerking-doe-opgave" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-doe-opgave">Uitwerking doe-opgave</h3>
<p>Winst patiënten: 109.07 − 94.00 = +15.1. Winst partners: 108.00 − 108.10 = −0.1. Verschil van de verschillen: 15.1 − (−0.1) ≈ 15.2 — en dat is het getal waar F(1, 116) = 6.76 over toetst. Meer machinerie zit er niet in: een interactie in een 2×2 is een aftreksom van twee aftreksommen.</p>
<p>Het hoofdeffect van meetmoment hoort bij de gemiddelde winst over álle 120 metingen: (15.1 + (−0.1)) / 2 ≈ 7.5 punten. En van wie is dat een eerlijke beschrijving? Van niemand in het bestand: de patiënten zitten er ruim onder noch boven — zij wonnen het dubbele — en de partners wonnen niets. Het is het gemiddelde van twee groepen die verschillende dingen meemaakten, en precies daarom lees je bij een interactie eerst de cellen en pas daarna (of liever: niet meer) de hoofdeffecten.</p>
</section>
</div>
</div>
</div>
<div class="boekvorm" data-w="W10">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: het effect van tijd hangt af van de rol — twee lijnen die niet parallel lopen, en één gemiddeld effect dat daardoor voor niemand meer klopt.</p>
<p>In het boek: <strong>W10 — Verschil in verschil</strong>.</p>
<p><em>Daar wordt geplant dat een interactie geen extra ingewikkeldheid is maar een eerlijkheid: soms ís er niet één antwoord, en dan is “het hangt ervan af” — mét de plot erbij — het precieze antwoord.</em></p>
</div>
<div class="werk">
<p>TODO: stem-pas. Data fictief (gegenereerd, reproduceert fragment exact); long-format-uitleg en JASP-klikpad (gewone twee-weg ANOVA op 120 rijen vs.&nbsp;Repeated Measures/Mixed — eerlijkheidje staat in de tekst) checken bij de screenshot-ronde, incl.&nbsp;of <code>rol ✻ meetmoment</code> en de Descriptives-plot er in 0.98.1 zo uitzien als beschreven.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>