<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Van significant naar relevant – GGZ-VS/JASP-werkboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_kruistabel_chikwadraat.html" rel="next">
<link href="../20_blokken/blok_odds_ratio.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../20_blokken/blok_klinische_relevantie.html">Van significant naar relevant</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">GGZ-VS/JASP-werkboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GGZ-VS/JASP-werkboek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/00_parkeerkaart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De parkeerkaart</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/01_vijf_basisvragen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De vijf basisvragen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/02_effectmaten_kaart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De effectmatenkaart</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meetniveaus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meetniveaus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gemiddelde en standaardafwijking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_kwartielen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_standaardfout.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standaardfout en non-respons</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De correlatie <em>r</em> en de scatterplot</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Enkelvoudige regressie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De effectgrootte — Cohens <em>d</em></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cronbachs α</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">W6 · Bestaat het verschil echt?</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De <em>p</em>-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets_gepaard_onafhankelijk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De <em>t</em>-toets: gepaard en onafhankelijk</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power_significant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Significantie en power</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meervoudige regressie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA en η²</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactie en moderatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De odds ratio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_klinische_relevantie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Van significant naar relevant</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Schil (naast het boek)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De kruistabel en χ²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mann_whitney.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De Mann-Whitney-toets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/99_register.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Het register</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Van significant naar relevant</h1>
<p class="subtitle lead">Wat betekent dit voor de praktijk? · <em>clinical significance</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Vooraf, in één zin:</strong> een <em>p</em> onder de .05 is geen aanbeveling — of een verschil de moeite waard is, staat nergens in de statistiek, en waarom je dat oordeel tóch niet uit de losse pols hoeft te vellen, staat hieronder.</p>
</blockquote>
<section id="wat-je-ziet" class="level2">
<h2 class="anchored" data-anchor-id="wat-je-ziet">Wat je ziet</h2>
<p><strong>In het kort.</strong> Een resultatenregel met een keurige <em>p</em>, en één zin verderop in de discussie die van dat resultaat een advies maakt. Tussen die twee zinnen zit een stap die het artikel meestal niet zet en jij wel moet zetten: van <em>“het verschil bestaat waarschijnlijk”</em> naar <em>“het verschil is de moeite waard”</em>. Dat is de vijfde en laatste van <a href="../20_blokken/01_vijf_basisvragen.html">de vijf basisvragen</a>, en het is de enige waar de statistiek je alleen tot de deur brengt.</p>
<p>Zo ziet dat eruit:</p>
<blockquote class="blockquote">
<p><em>Voorbeeldfragment, geschreven in de stijl van een resultatensectie — het artikel bestaat niet.</em></p>
<p>In a retrospective chart review (<em>N</em> = 150), relapse within one year differed by aftercare intensity: 56% (28/50) of patients without aftercare relapsed, versus 40% (20/50) with standard and 24% (12/50) with intensive aftercare, χ²(2) = 10.67, <em>p</em> = .005, Cramér’s V = .27. <em>These findings support the routine implementation of intensive aftercare.</em></p>
</blockquote>
<p>Je herkent de eerste helft misschien: het is het fragment uit <a href="../20_blokken/blok_kruistabel_chikwadraat.html">de kruistabel en χ²</a>. Dezelfde tabel, andere vraag. Daar ging het over de vraag óf de aantallen samenhangen; hier gaat het over die laatste cursieve zin — <em>support the routine implementation</em> — en of die zin verdiend is.</p>
</section>
<section id="wat-er-staat" class="level2">
<h2 class="anchored" data-anchor-id="wat-er-staat">Wat er staat</h2>
<p><strong>In het kort.</strong> Er staan drie percentages, een χ² en een <em>p</em>. Wat er níét staat, en wat je in twintig seconden zelf uit die percentages haalt, zijn de twee getallen waarmee je vraag 5 kunt beantwoorden: het <strong>risicoverschil</strong> (32 procentpunten) en de <strong>NNT</strong> (4). Die twee getallen zetten het resultaat terug in de eenheid waarin een afdeling denkt: patiënten.</p>
<p>Nu rustig van voren af aan. De <em>p</em> van .005 zegt dat dit patroon van aantallen slecht past bij “nazorg maakt niets uit”. Dat is vraag 4, en die is hiermee beantwoord. De χ² zegt verder niets — niet hoe groot het verschil is, niet welke kant het op gaat, en al helemaal niet of je er iets mee moet.</p>
<p>Ga dus terug naar de percentages, want die zijn gewoon leesbaar. Zonder nazorg viel 56% binnen een jaar terug, met intensieve nazorg 24%. Trek ze van elkaar af en je hebt het <strong>risicoverschil</strong> / <em>risk difference</em>, ook wel <em>absolute risk reduction</em>:</p>
<div class="formule callout callout-style-default callout-note callout-titled" title="Twee sommen, meer is het niet">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Twee sommen, meer is het niet
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Risicoverschil</strong> = risico zonder − risico met = 56% − 24% = <strong>32 procentpunten</strong></p>
<hr>
<p><strong>NNT</strong> = 1 gedeeld door het risicoverschil = 1 / 0,32 = 3,1 → <strong>4</strong></p>
<p>De NNT rond je naar <strong>boven</strong> af. Je kunt geen 3,1 patiënt behandelen, en naar boven afronden is de voorzichtige kant: je belooft liever te weinig dan te veel.</p>
</div>
</div>
<p>Let op het woord <strong>procentpunten</strong>. Van 56% naar 24% is een daling van 32 <em>procentpunten</em>, en tegelijk een daling van 57 <em>procent</em> (want 32 is 57% van 56). Allebei waar, en ze klinken heel verschillend. Wie ze door elkaar haalt, schrijft een resultaat op dat bijna twee keer zo groot lijkt als het is. Op <a href="../20_blokken/02_effectmaten_kaart.html">de effectmatenkaart</a> staan alle zes de maten die uit deze ene tabel te halen zijn, naast elkaar.</p>
<p>En dan de <strong>NNT</strong>, voluit <em>number needed to treat</em>. Dit is de enige effectmaat die je antwoord in mensen geeft in plaats van in punten of verhoudingen, en dat is precies waarom hij aan een vergadertafel blijft hangen:</p>
<blockquote class="blockquote">
<p>Je moet 4 patiënten intensieve nazorg geven om bij 1 patiënt extra terugval te voorkomen.</p>
</blockquote>
<p>Vier. Dat is, klinisch gesproken, uitzonderlijk goed — bij veel medicatie in de somatiek liggen NNT’s tussen de 20 en de 100. Hoe kleiner de NNT, hoe sterker de interventie, en dat is de omgekeerde leesrichting van alle andere maten in dit werkboek.</p>
<p>Eén ding om nu alvast op te merken en onderaan uit te werken: in die zin staat een woord dat statistisch nergens vandaan komt, en dat is <strong>voorkomen</strong>. Deze data komen uit een dossieronderzoek. Onthoud de zin, en wees voorzichtig met dat ene woord.</p>
</section>
<section id="waar-het-vandaan-komt" class="level2">
<h2 class="anchored" data-anchor-id="waar-het-vandaan-komt">Waar het vandaan komt</h2>
<p>Dit blok hangt aan de boek-eenheid <em>Hoe beslis je?</em> — het hoofdstuk waarin de α van .05 een <strong>afspraak</strong> blijkt te zijn en geen natuurwet, iets wat mensen met elkaar afgesproken hebben en waar goede redenen zijn om hem te verschuiven. Dat is de opmaat naar dit blok, want als de grens al een menselijk oordeel is, dan is de vraag wat er áchter die grens gebeurt dat des te meer.</p>
<p>Het boek zegt daar iets wat je hier nodig hebt: een toets beantwoordt de vraag die je hem stelt, en niet de vraag die je eigenlijk had. De toets vraagt <em>past “geen verschil” nog bij deze data?</em> Jij wilde weten <em>moet ik mijn afdeling anders inrichten?</em> Dat zijn twee vragen, en tussen die twee zit geen rekenstap maar een oordeel — met een dossier, een patiëntenpopulatie, een begroting en een team eromheen.</p>
<p>Dat is geen zwakte van de statistiek. Het is precies wat statistiek is: een manier om zorgvuldig te zeggen wat je uit je gegevens mag afleiden, zodat het oordeel dat daarna komt op iets stevigs staat.</p>
</section>
<section id="zelf-doen-in-jasp" class="level2">
<h2 class="anchored" data-anchor-id="zelf-doen-in-jasp">Zelf doen in JASP</h2>
<p><a href="../10_data/terugval_nazorg.csv" class="data-download" download="terugval_nazorg.csv">⬇ Download de data — <code>terugval_nazorg.csv</code></a></p>
<p>Bij dit blok hoort het databestand <code>terugval_nazorg.csv</code>: 150 rijen, drie kolommen — <code>id</code> (deelnemernummer), <code>nazorg</code> (geen, standaard of intensief) en <code>terugval</code> (ja of nee). De rijen zijn gegenereerd — er zit geen echte patiënt in — en ze reproduceren precies de aantallen uit het fragment.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open het bestand in JASP (menu linksboven → Open).</li>
<li>Klik in de balk bovenin op <strong>Frequencies</strong> en kies onder Classical <strong>Contingency Tables</strong>.</li>
<li>Sleep <code>nazorg</code> naar <strong>Rows</strong> en <code>terugval</code> naar <strong>Columns</strong>; de kolom <code>id</code> laat je staan waar hij staat.</li>
<li>Klap <strong>Cells</strong> open en vink onder Percentages <strong>Row</strong> aan.</li>
</ol>
</div>
</div>
<p>Meer heb je van JASP niet nodig — de rest doe je met een kladblaadje, en dat is geen armoede maar de kern van dit blok. In de rijpercentages staat nu:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>nazorg</th>
<th>terugval</th>
<th>percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>geen</td>
<td>28 van 50</td>
<td>56.0%</td>
</tr>
<tr class="even">
<td>standaard</td>
<td>20 van 50</td>
<td>40.0%</td>
</tr>
<tr class="odd">
<td>intensief</td>
<td>12 van 50</td>
<td>24.0%</td>
</tr>
</tbody>
</table>
<p>Reken nu de twee sommen uit voor <strong>twee</strong> vergelijkingen, en zet ze naast elkaar:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>vergelijking</th>
<th>risicoverschil</th>
<th>NNT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>intensief tegenover geen nazorg</td>
<td>56 − 24 = 32 procentpunten</td>
<td>1 / 0,32 = 3,1 → <strong>4</strong></td>
</tr>
<tr class="even">
<td>standaard tegenover geen nazorg</td>
<td>56 − 40 = 16 procentpunten</td>
<td>1 / 0,16 = 6,25 → <strong>7</strong></td>
</tr>
</tbody>
</table>
<p>Kijk daar even naar, want hier zit een les in die je in geen enkel artikel uitgelegd krijgt. <strong>Er bestaat niet zoiets als “de NNT van nazorg”.</strong> Er bestaat een NNT van intensieve nazorg tegenover niets (4) en een NNT van standaardnazorg tegenover niets (7), en straks op jouw afdeling misschien een NNT van intensieve nazorg tegenover de standaardzorg die je al geeft — dat is weer een derde getal. Een NNT is altijd een NNT <em>ergens tegenover</em>. Staat er in een artikel een NNT zonder dat erbij staat waartegen, dan is dat een half getal.</p>
<p>JASP rekent; jij vergelijkt.</p>
</section>
<section id="zelf-opschrijven" class="level2">
<h2 class="anchored" data-anchor-id="zelf-opschrijven">Zelf opschrijven</h2>
<div class="apa callout callout-style-default callout-note callout-titled" title="Schrijf het op — van resultaat naar relevantie">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Schrijf het op — van resultaat naar relevantie
</div>
</div>
<div class="callout-body-container callout-body">
<p>Voor je eigen Nederlandstalige literatuurstudie:</p>
<blockquote class="blockquote">
<p>Patiënten die intensieve nazorg kregen, vielen binnen een jaar minder vaak terug dan patiënten zonder nazorg (24.0% tegen 56.0%; χ²(2) = 10.67, <em>p</em> = .005). Dat komt neer op een absoluut verschil van 32 procentpunten: per honderd patiënten zouden er tweeëndertig minder terugvallen. Omdat het om dossieronderzoek gaat, is niet vast te stellen of de nazorg dat verschil veroorzaakte; patiënten met een gunstiger beloop kunnen vaker voor intensieve nazorg in aanmerking zijn gekomen.</p>
</blockquote>
<p>Drie werkafspraken daarbij:</p>
<ul>
<li><strong>Zet het absolute verschil er altijd bij.</strong> Een relatieve maat alleen — “57% minder terugval”, “RR = 0.43” — is niet fout, maar hij vertelt je lezer niet hoeveel patiënten dit zijn. De absolute maat wel. Wie beide geeft, is niet uitvoeriger maar eerlijker.</li>
<li><strong>Noem de vergelijking.</strong> Waartegen is dit afgezet: tegen niets, tegen gebruikelijke zorg, tegen een andere interventie? Zonder dat staat er geen effect maar een getal.</li>
<li><strong>Schrijf de onzekerheid in dezelfde alinea.</strong> Niet in een voetnoot en niet in een aparte beperkingen-paragraaf achteraan waar niemand hem naast het resultaat legt. Het cijfer en zijn voorbehoud horen bij elkaar in één adem.</li>
</ul>
</div>
</div>
</section>
<section id="de-vijf-weegpunten" class="level2">
<h2 class="anchored" data-anchor-id="de-vijf-weegpunten">De vijf weegpunten</h2>
<p>Vraag 5 is geen som en toch ook geen vrij zwevende mening. Er zijn vijf dingen die je aan het artikel — of aan jezelf — kunt vragen, en die samen een oordeel dragen dat je kunt verdedigen. Loop ze langs in deze volgorde; ze staan van “weegt het zwaarst” naar “beslist meestal het laatst”.</p>
<p><strong>1 · Bijdrage aan kwaliteit van leven.</strong> Merkt de patiënt hier iets van? Terugval binnen een jaar is een uitkomst waar iemand het verschil van voelt. Twee punten op een symptoomlijst zijn dat niet per se. <em>Vraag aan het artikel:</em> is de uitkomstmaat iets wat de patiënt ervaart, of iets wat de onderzoeker kan meten? <em>Staat er niets:</em> schrijf op dat de studie op een surrogaatuitkomst leunt — dat is een volwaardige beperking.</p>
<p><strong>2 · Ernst van het probleem.</strong> Hoe erg is datgene wat je probeert te voorkomen? Een kleine daling in een ernstige uitkomst (terugval, heropname, suïcidaliteit) weegt zwaarder dan een grote daling in een milde. <em>Vraag aan het artikel:</em> wat gebeurt er met de patiënten in de controlegroep? <em>Staat er niets:</em> zoek het absolute risico in de controlegroep op — dat cijfer staat er bijna altijd wél, en het vertelt je meteen hoe groot het probleem is.</p>
<p><strong>3 · Impact van bijwerkingen en belasting.</strong> Wat kost het de patiënt? Tijd, moeite, bijwerkingen, het gevoel een patiënt te zijn. Een NNT van 4 is prachtig als de interventie ongevaarlijk is; bij een zware interventie behandel je nog altijd drie mensen voor niets. <em>Vraag aan het artikel:</em> worden nadelen gerapporteerd, of alleen effecten? <em>Staat er niets:</em> dat is zelf een bevinding. Studies die alleen de gunstige kant meten, geven je een halve balans.</p>
<p><strong>4 · Beschikbaarheid van alternatieven.</strong> Waartegen zet je dit af — tegen niets, of tegen wat je al doet? Kijk terug naar de tabel hierboven: intensieve nazorg tegenover niets is NNT 4; tegenover standaardnazorg is het een ander en kleiner voordeel. Op een afdeling die al standaardnazorg geeft, is dát de vergelijking die telt. <em>Vraag aan het artikel:</em> wat kreeg de controlegroep? <em>Staat er “usual care”:</em> zoek uit wát daar gebruikelijk was, want dat verschilt per land en per instelling, en het bepaalt of dit resultaat op jou van toepassing is.</p>
<p><strong>5 · Kosten voor organisatie en samenleving.</strong> Uren, opleiding, roosters, geld. Dit is het weegpunt dat een onderzoeker zelden meeneemt en een praktijkinstelling altijd, en het is de reden dat een statistisch overtuigend resultaat toch niet ingevoerd wordt. <em>Vraag aan het artikel:</em> wat kost de interventie in menstijd? <em>Staat er niets:</em> reken het zelf grofweg om met de NNT — vier patiënten intensieve nazorg is een concreet aantal uren, en dat is een zin die het in een teamoverleg wél doet.</p>
<p>Wat deze vijf samen opleveren is geen cijfer maar een <strong>verdedigbaar oordeel</strong>: je kunt laten zien waaróm je iets relevant vindt, en waar de studie je in de steek laat. Dat laatste is in een literatuurstudie minstens zo waardevol als het eerste.</p>
</section>
<section id="en-bij-een-gemeten-uitkomst" class="level2">
<h2 class="anchored" data-anchor-id="en-bij-een-gemeten-uitkomst">En bij een gemeten uitkomst?</h2>
<p>Het risicoverschil en de NNT werken alleen bij een <strong>getelde</strong> uitkomst — bij ja/nee. Krijg je een schaal voor je (een BDI, een PANSS, een PHQ-9), dan is de vraag anders: is dit aantal punten een verschil dat iemand merkt?</p>
<p>Daar bestaat een begrip voor dat je zult tegenkomen: het <strong>kleinste klinisch relevante verschil</strong> / <em>minimal clinically important difference</em>, kortweg <strong>MCID</strong>. Dat is het aantal punten op een specifieke schaal waarbij patiënten zelf zeggen dat het verschil merkbaar is. Het is per instrument bepaald, in apart onderzoek, en het is dus geen vuistregel maar een opgezocht getal.</p>
<p>Wat je ermee doet is simpel. Staat er in het artikel een MCID genoemd, leg het gevonden verschil ernaast en zeg of het eroverheen komt — én of het <em>betrouwbaarheidsinterval</em> eroverheen komt, want een verschil van 6 punten met een interval van 1 tot 11 is iets anders dan hetzelfde verschil met een interval van 5 tot 7. Staat er geen MCID, dan is de eerlijke zin dat het artikel geen maatstaf voor klinische relevantie aanreikt. Wat je niet doet, is de vuistregels van Cohen erbij pakken en <em>d</em> = 0.5 “middelmatig relevant” noemen — dat is een statistische maat die zich als een klinisch oordeel voordoet.</p>
</section>
<section id="wat-het-niet-zegt" class="level2">
<h2 class="anchored" data-anchor-id="wat-het-niet-zegt">Wat het niet zegt</h2>
<p><strong>“Om terugval te voorkomen.”</strong> De NNT-zin die je hierboven leerde, is een oorzakelijke zin, en dit fragment is een dossieronderzoek. Let op: de som mág hier, want nazorg is iets wat je <em>doet</em> — er is een interventie, en zonder interventie valt er sowieso geen NNT te berekenen (zie <a href="../20_blokken/blok_odds_ratio.html">de odds ratio</a>). Het probleem zit niet in de rekenkunde maar in dat ene woord. Want wie kreeg er intensieve nazorg? Vermoedelijk niet een willekeurig geloot deel van de patiënten — eerder wie gemotiveerd was, wie verzekerd was, wie in beeld bleef. Dat zijn stuk voor stuk kenmerken die óók met minder terugval samenhangen. De 32 procentpunten zijn dan deels het verschil tussen twee soorten patiënten in plaats van tussen twee soorten zorg. Het getal is niet fout; de zin eromheen is te sterk. Bij een dossieronderzoek schrijf je dus: <em>“patiënten met intensieve nazorg vielen minder vaak terug”</em> — en niet <em>“intensieve nazorg voorkomt terugval”</em>. In een gerandomiseerd onderzoek mag dat tweede wél, en juist daarom is het eerste wat je bij een NNT opzoekt: <strong>hoe zijn de groepen tot stand gekomen?</strong></p>
<p><strong>Dat deze NNT ook op jouw afdeling geldt.</strong> De NNT hangt aan het risico in de controlegroep, en dat risico is populatiegebonden. Deze 56% terugval hoort bij déze patiënten. Zit jouw populatie op 20% terugval, dan levert precies dezelfde interventie een veel grotere NNT op — er valt bij jou minder te winnen omdat er minder misgaat. Een NNT reist dus slechter dan een Cohens <em>d</em>. Dat is geen gebrek maar een eigenschap: hij is zo bruikbaar juist omdát hij aan een concrete situatie vastzit.</p>
<p><strong>Dat een klein verschil onbelangrijk is.</strong> Bij een ernstige uitkomst kan een risicoverschil van één procentpunt de moeite waard zijn, ook al is de NNT dan 100. En omgekeerd: een groot, hard significant verschil op een uitkomst die niemand merkt, is nog steeds niet relevant. De omvang van het getal en het gewicht ervan zijn twee verschillende dingen — dat is dezelfde les als bij <a href="../20_blokken/blok_effectgrootte_d.html">de effectgrootte</a>, één trap hoger.</p>
<p><strong>Dat “niet significant” betekent dat het niet werkt.</strong> Een studie die te klein is om een effect aan te tonen, heeft geen effect uitgesloten — hij heeft niets gevonden, en dat is iets anders. Kijk in dat geval altijd naar het interval: loopt het van “flink nadeel” tot “flink voordeel”, dan weet deze studie het gewoon niet. Zie <a href="../20_blokken/blok_power_significant.html">significantie en power</a>.</p>
<p><strong>En dat het artikel het voor je doet.</strong> De zin <em>“these findings support the routine implementation”</em> is de meest voorkomende plek waar dit misgaat: onderzoekers stappen daar in één zin van vraag 4 naar vraag 5, zonder een van de vijf weegpunten aan te raken. Dat opmerken is niet vervelend doen. Het is de opdracht.</p>
</section>
<section id="oefening" class="level2">
<h2 class="anchored" data-anchor-id="oefening">Oefening</h2>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Oefening">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Oefening
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Leesopgave.</strong> Hieronder een voorbeeldfragment (verzonnen), uit een groot, goed uitgevoerd gerandomiseerd onderzoek. Vertel in gewone Nederlandse zinnen wat er staat, reken het risicoverschil en de NNT uit, en beantwoord dan de vraag die de auteurs stellen: zou jij dit middel op je afdeling invoeren? Loop in je antwoord minstens drie van de vijf weegpunten langs.</p>
<blockquote class="blockquote">
<p>In this multicentre randomised trial (<em>N</em> = 8,412), the incidence of the primary endpoint at 24 months was 1.0% in the intervention group versus 2.0% in the placebo group (RR = 0.50, 95% CI [0.34, 0.74], <em>p</em> &lt; .001), representing a 50% reduction in risk. Discontinuation due to adverse events occurred in 11.2% of the intervention group versus 3.1% of controls.</p>
</blockquote>
<p><strong>Leesopgave — drie keer een NNT.</strong> Drie voorbeeldfragmenten (verzonnen; de artikelen bestaan geen van drieën), en bij elk dezelfde drie vragen. <strong>(1)</strong> Klopt de som? Reken hem na uit de aantallen die er staan; je hebt er een kladblaadje voor nodig en verder niets. <strong>(2)</strong> Klopt de zin eromheen? <strong>(3)</strong> Wat zou jij hiervan overnemen in je literatuurstudie?</p>
<blockquote class="blockquote">
<p><strong>1.</strong> In this randomised controlled trial (<em>N</em> = 240), patients discharged from an acute psychiatric ward were randomly allocated to a structured crisis plan (<em>n</em> = 120) or to usual care (<em>n</em> = 120). Readmission within 12 months occurred in 18/120 (15.0%) of the crisis-plan group versus 36/120 (30.0%) of controls, RR = 0.50, 95% CI [0.30, 0.83], χ²(1) = 7.74, <em>p</em> = .005. The number needed to treat to prevent one readmission within 12 months was 7, 95% CI [4, 22].</p>
<p><strong>2.</strong> In this retrospective cohort study (<em>N</em> = 280), readmission within 12 months occurred in 28/80 (35.0%) of patients with a comorbid personality disorder and in 34/200 (17.0%) of patients without — an absolute difference of 18 percentage points, corresponding to a number needed to treat of 6. Treating comorbid personality pathology would thus prevent one readmission for every six patients.</p>
<p><strong>3.</strong> In this randomised trial (<em>N</em> = 400), relapse within one year occurred in 24/200 (12.0%) of patients in the relapse-prevention programme versus 40/200 (20.0%) of patients receiving usual care, a relative risk reduction of 40%. The programme is highly efficient: the number needed to treat is 2.5.</p>
</blockquote>
<p>En dan één vraag terug naar het eerste fragment. Op jouw afdeling wordt niet 30% maar 12% van de patiënten binnen een jaar heropgenomen. Stel dat de crisiskaart daar hetzelfde <em>relatieve</em> effect heeft — wat wordt de NNT dan, en verandert dat je oordeel?</p>
<p><strong>Doe-opgave.</strong> Draai de analyse van hierboven (<code>terugval_nazorg.csv</code>) en zet de rijpercentages erbij. Reken nu een <strong>derde</strong> vergelijking uit die in dit blok nog niet gemaakt is: intensieve nazorg tegenover <em>standaard</em>nazorg. Wat zijn het risicoverschil en de NNT? En schrijf dan één zin op voor een teamoverleg op een afdeling die al standaardnazorg geeft — welke van de drie NNT’s is daar de eerlijke?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Uitwerkingen — klik open">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Uitwerkingen — klik open
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="uitwerking-leesopgave" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-leesopgave">Uitwerking leesopgave</h3>
<p>Eerst het navertellen. In een groot gerandomiseerd onderzoek onder ruim achtduizend deelnemers kreeg 1.0% van de behandelde groep binnen twee jaar de primaire uitkomst, tegen 2.0% van de placebogroep. Het risico was dus de helft zo groot, en het interval [0.34, 0.74] bevat de 1 niet: dit is een hard resultaat, en met 8.412 deelnemers is het ook precies geschat.</p>
<p>Dan de twee sommen. Het risicoverschil is 2.0% − 1.0% = <strong>1 procentpunt</strong>. De NNT is 1 / 0,01 = <strong>100</strong>. Diezelfde studie levert dus tegelijk de zin <em>“het middel halveert het risico”</em> (waar) en de zin <em>“je moet honderd mensen twee jaar behandelen om bij één de uitkomst te voorkomen”</em> (ook waar). Dat is precies het verschil tussen een relatieve en een absolute maat, en dit is waarom je ze allebei opschrijft.</p>
<p>En dan het oordeel. <strong>Ernst van het probleem:</strong> het gaat om 2% in twee jaar — of dat zwaar weegt, hangt volledig af van wát die primaire uitkomst is, en dat staat er niet bij. Dat is het eerste wat je zou opzoeken. <strong>Impact van bijwerkingen:</strong> hier valt het om. 11.2% tegen 3.1% stopt met het middel wegens bijwerkingen — dat is ruim 8 procentpunten extra, oftewel ongeveer één op de twaalf. Zet dat naast een NNT van 100: op elke honderd behandelde mensen helpt het er één, en krijgen er ongeveer acht last die ze doet stoppen. <strong>Kosten:</strong> honderd mensen twee jaar behandelen voor één voorkomen gebeurtenis is een serieuze uitgave en een serieuze belasting van je poli.</p>
<p>Een verdedigbaar antwoord luidt dus: statistisch overtuigend, klinisch twijfelachtig — niet invoeren zonder te weten hoe ernstig de primaire uitkomst is en zonder een subgroep te kunnen aanwijzen met een veel hoger uitgangsrisico. Want daar zit de uitweg: bij patiënten met een hoger risico levert dezelfde halvering een groter absoluut verschil en dus een kleinere NNT.</p>
<p>Wat je hier vooral moet zien: de zin <em>“a 50% reduction in risk”</em> is volledig waar en volstrekt misleidend, en het enige dat ertegen beschermt is dat je zelf één keer aftrekt in plaats van deelt.</p>
</section>
<section id="uitwerking-leesopgave-drie-keer-een-nnt" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-leesopgave-drie-keer-een-nnt">Uitwerking leesopgave — drie keer een NNT</h3>
<p><strong>Fragment 1 — deze houdt stand.</strong></p>
<p>De som eerst: 30.0% − 15.0% = <strong>15 procentpunten</strong>, en 1 / 0,15 = 6,67, naar boven afgerond <strong>NNT = 7</strong>. Klopt.</p>
<p>En de zin eromheen klopt ook, en het is de moeite waard om te benoemen waaróm — want dit zijn precies de vier dingen die je bij elke NNT nagaat:</p>
<ul>
<li><strong>Er is iets gedaan.</strong> Een crisiskaart is een interventie; er valt iets te behandelen. (Dit is de vraag waar het tweede fragment straks op omvalt.)</li>
<li><strong>Er staat waartegen.</strong> Tegen <em>usual care</em>, en dat staat er met zoveel woorden. Een NNT zonder vergelijking is een half getal.</li>
<li><strong>Er staat welke uitkomst en binnen welke termijn.</strong> Heropname binnen twaalf maanden. Een NNT hangt aan een uitkomst en aan een tijdvak; verleng de follow-up en het getal verandert.</li>
<li><strong>Er staat een interval bij, en dat interval is breed.</strong> 95% CI [4, 22]. Zeven is de beste schatting, maar deze data verdragen ook <em>“tweeëntwintig patiënten voor één”</em>. Dat is een heel ander gesprek in een teamoverleg. De meeste artikelen geven dit interval niet, en dan is de NNT schijnpreciezer dan hij is.</li>
</ul>
<p>Wat je overneemt: <em>Patiënten die een crisiskaart kregen, werden binnen een jaar minder vaak heropgenomen dan patiënten met gebruikelijke zorg (15.0% tegen 30.0%; RR = 0.50, 95%-BI [0.30, 0.83]). Dat komt neer op 15 procentpunten absoluut verschil: je moet ongeveer zeven patiënten een crisiskaart geven om bij één patiënt extra een heropname te voorkomen, al loopt het interval van vier tot tweeëntwintig patiënten.</em></p>
<p><strong>Fragment 2 — de som klopt, en de zin kan niet bestaan.</strong></p>
<p>De som: 35.0% − 17.0% = <strong>18 procentpunten</strong>, en 1 / 0,18 = 5,56 → <strong>NNT = 6</strong>. Er is niets mis met dat rekenwerk.</p>
<p>Lees de zin nu hardop, met het werkwoord erin: <em>“je moet zes patiënten behandelen om één heropname te voorkomen.”</em> Behandelen — waarmee? In dit onderzoek is niemand behandeld. Er zijn dossiers doorgenomen en er is geteld wie er een comorbide persoonlijkheidsstoornis hád. Een persoonlijkheidsstoornis is een <strong>kenmerk</strong> van patiënten, geen interventie, en de 18 procentpunten zijn dus het verschil tussen twee soorten patiënt — niet het effect van wat voor zorg dan ook.</p>
<p>De auteurs voelen dat zelf ook, en daarom schuift hun zin ongemerkt op: ze schrijven <em>treating comorbid personality pathology</em>. Daarmee wordt er een behandeling in het onderzoek gesmokkeld die er nooit in zat. Zelfs als zo’n behandeling bestaat — en die bestaat — is er in deze studie niemand mee behandeld, dus weet dit onderzoek er niets van. <strong>De NNT hoort bij een interventie; het risicoverschil hoort bij elke twee groepen.</strong></p>
<p>Eén ding om niet te ver door te trekken: het ligt niet aan het woord <em>retrospective</em>. Ook zonder loting mag de som, zolang er maar iets gegeven is — zoals bij het dossieronderzoek boven aan dit blok, waar wél nazorg werd verstrekt. Dan is de NNT te berekenen en is alleen het oorzakelijke woord (<em>voorkomen</em>) te sterk. Hier ligt het een stap dieper: er is helemaal niets gegeven.</p>
<p>Wat je overneemt: het risicoverschil, en meer niet. <em>Patiënten met een comorbide persoonlijkheidsstoornis werden binnen een jaar vaker heropgenomen dan patiënten zonder (35.0% tegen 17.0%; een verschil van 18 procentpunten).</em> Dat is bruikbare informatie — het zegt bij wie je moet opletten. Het zegt alleen niet wat je moet dóén, en de NNT doet net alsof het dat wel zegt.</p>
<p><strong>Fragment 3 — hier klopt de som niet.</strong></p>
<p>20.0% − 12.0% = <strong>8 procentpunten</strong>, dus 1 / 0,08 = 12,5 → <strong>NNT = 13</strong>. Het artikel zegt 2,5. Waar komt die vandaan? Uit 1 / 0,40 — de auteurs hebben gedeeld door de <strong>relatieve</strong> risicoreductie in plaats van door het risicoverschil. Dat is de meest voorkomende rekenfout bij deze maat, en het verschil is niet klein: ongeveer drie patiënten tegenover dertien.</p>
<p>Twee dingen om mee te nemen. Ten eerste maakt deze fout de uitkomst <strong>altijd mooier</strong>, nooit lelijker. Delen door de relatieve maat in plaats van door de absolute levert namelijk precies de echte NNT maal het risico in de controlegroep op — hier 12,5 × 0,20 = 2,5 — en dat risico is altijd kleiner dan 1. Een NNT die te mooi is om waar te zijn, is het soms ook letterlijk.</p>
<p>Ten tweede is er één grens die de moeite waard is om te onthouden, en die geldt áltijd: <strong>de NNT kan nooit kleiner zijn dan 1 gedeeld door het risico in de controlegroep.</strong> Meer dan alle terugval voorkomen kan een programma niet. Hier valt 20% terug, dus de allerbeste denkbare uitkomst is 1 / 0,20 = 5. Het artikel drukt 2,5 af, en dat kan dus niet — je ziet het zonder de goede som te maken. Reken er niet op dat deze grens elke versie van de fout vangt: bij een hoger uitgangsrisico kan een verkeerd berekende NNT er nog netjes bovenuit komen. Maar als hij afgaat, weet je genoeg.</p>
<p><strong>En de vraag over jouw afdeling.</strong> Bij een uitgangsrisico van 12% in plaats van 30% haalt hetzelfde relatieve effect (RR = 0.50) het risico naar 6.0%. Het risicoverschil is dan <strong>6 procentpunten</strong> en 1 / 0,06 = 16,67 → <strong>NNT = 17</strong>. Zeven wordt zeventien. Zelfde crisiskaart, zelfde relatieve effect, andere afdeling — omdat er bij jou minder te winnen is.</p>
<p>Merk op wat we daarbij hebben aangenomen: dat het <em>relatieve</em> effect meereist en het absolute niet. Dat is de gebruikelijke aanname, en het blijft een aanname — maar hij is een stuk voorzichtiger dan de NNT van 7 zomaar overnemen. Of je de crisiskaart dan nog invoert, is weegpunt 5: zeventien kaarten opstellen kost meer uren dan zeven, en de winst is dezelfde ene patiënt.</p>
</section>
<section id="uitwerking-doe-opgave" class="level3">
<h3 class="anchored" data-anchor-id="uitwerking-doe-opgave">Uitwerking doe-opgave</h3>
<p>Intensief tegenover standaard: 40.0% − 24.0% = <strong>16 procentpunten</strong>, en 1 / 0,16 = 6,25 → <strong>NNT 7</strong>. Toevallig hetzelfde getal als standaard tegenover niets — bij deze data zijn de twee stappen even groot.</p>
<p>De zin voor het teamoverleg is de eerlijke omdat hij de goede vergelijking maakt: <em>“We geven nu standaardnazorg. Als we voor deze groep zouden opschalen naar intensieve nazorg, moeten we op grond van dit onderzoek ongeveer zeven patiënten intensief begeleiden om bij één patiënt extra terugval te voorkomen — en dat is een dossieronderzoek, dus het kan meevallen én tegenvallen.”</em></p>
<p>Niet de NNT van 4, dus. Die vergelijkt met géén nazorg, en dat is niet de situatie waarin jouw afdeling verkeert. Wie de 4 noemt, verkoopt het voordeel van iets wat hij al doet als winst van iets nieuws. Dat is dezelfde fout als de relatieve maat noemen zonder de absolute — alleen dan in de keuze van de vergelijking in plaats van in de keuze van het getal.</p>
</section>
</div>
</div>
</div>
<div class="boekvorm" data-w="W7">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: de stap van “het verschil bestaat waarschijnlijk” naar “het verschil is de moeite waard” — en het besef dat die stap geen rekenstap is.</p>
<p>In het boek: <strong>W7 — Hoe beslis je?</strong></p>
<p><em>Daar blijkt de grens van .05 een afspraak tussen mensen te zijn en geen natuurwet; hier blijkt dat te gelden voor alles wat er ná die grens komt.</em></p>
</div>
<div class="werk">
<p>TODO — drie dingen. (1) Boek-anker W7 gekozen omdat <em>Hoe beslis je?</em> de eenheid is waar de afspraak-natuur van α aan de orde komt; controleren zodra dat hoofdstuk zijn stem-pas heeft, en heroverwegen als het boek de klinische weging elders onderbrengt. (2) OPGELOST 12-8-2026 (spoor <em>adres</em>): risicoverschil en NNT stonden alleen hier en op de effectmatenkaart, en wie ze opzocht greep mis. Ze staan nu op de parkeerkaart en in het register, allebei met <a href="../20_blokken/02_effectmaten_kaart.html">de effectmatenkaart</a> als adres — die kaart wijst per maat door naar hier. Let op wat dat betekent voor onderhoud: de doorverwijzing naar dít blok staat op de kaart, dus verandert er iets aan waar het risicoverschil wordt uitgewerkt, dan is de kaart de plek die mee moet. (3) MCID is hier bewust één sectie en geen blok; als de vraag terugkomt of hij een eigen adres verdient, is dit de plek waar het besluit hoort.</p>
<p>Bijgekomen 16-8-2026 (spoor <em>nnt</em>): de leesopgave <strong>drie keer een NNT</strong>. Ben besloot die dag dat de NNT niet alleen ergens genoemd moet worden maar geoefend — en dat dit werkboek de plek is, in zijn eigen vorm: andermans artikel wegen. Het boek doet de NNT bewust niet (H12), en de broertjes-alinea blijft zoals hij is.</p>
<p>Waarom hier en niet in een eigen blok: parkeerkaart, register en effectmatenkaart wijzen alle drie voor de NNT naar de kaart, en de kaart wijst voor vraag 5 naar dít blok. Een eigen blok zou een vierde plek zijn geweest en het één-adres-besluit van 12-8 doorsnijden. <strong>Open voor Ben:</strong> nu de NNT hier een volle opgave draagt, is de vraag of hij alsnog een eigen adres verdient — dat is dezelfde soort vraag als die over MCID hierboven, en het is jouw call, niet die van een zetter.</p>
<p>De drie fragmenten zijn verzonnen en de getallen zijn berekend, niet gekozen: <code>_tools/getallen_nnt_opgave.R</code> rekent elk getal opnieuw uit de aantallen in de fragmenten en zoekt of die vorm nog in de tekst staat. Er hoort geen databestand bij — de aantallen staan in de fragmenten zelf, zodat een student ze met een kladblaadje kan narekenen. <code>_tools/_proef_nnt_wachter.R</code> laat de wachter afgaan; die proef legde meteen een gat bloot (de NNT ín fragment 1 werd niet bewaakt), dat is gedicht.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_odds_ratio.html" class="pagination-link" aria-label="De odds ratio">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">De odds ratio</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="pagination-link" aria-label="De kruistabel en χ²">
        <span class="nav-page-text">De kruistabel en χ²</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>