<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Hoofdstuk 2 - De Normaalverdeling. – Handleiding Statistiek met JASP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="libs/quarto-nav/quarto-nav.js"></script>
<script src="libs/quarto-nav/headroom.min.js"></script>
<script src="libs/clipboard/clipboard.min.js"></script>
<script src="libs/quarto-search/autocomplete.umd.js"></script>
<script src="libs/quarto-search/fuse.min.js"></script>
<script src="libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-samenhang.html" rel="next">
<link href="./01-descriptive-statistics.html" rel="prev">
<script src="libs/quarto-html/quarto.js" type="module"></script>
<script src="libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="libs/quarto-html/popper.min.js"></script>
<script src="libs/quarto-html/tippy.umd.min.js"></script>
<script src="libs/quarto-html/anchor.min.js"></script>
<link href="libs/quarto-html/tippy.css" rel="stylesheet">
<link href="libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="libs/bootstrap/bootstrap.min.js"></script>
<link href="libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-de-normaal-verdeling.html"><span class="chapter-title">Hoofdstuk 2 - De Normaalverdeling.</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Handleiding Statistiek met JASP</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Voorwoord</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-descriptive-statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, <em>Descriptive Statistics</em>.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-de-normaal-verdeling.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Hoofdstuk 2 - De Normaalverdeling.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-samenhang.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-van-steekproef-naar-populatie.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 4 - Van Steekproef naar Populatie. Generalisatie van Statistieken naar Parameters aan de hand van Betrouwbaarheidsintervallen en Significantie-toetsen.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-enkelvoudige-lineaire-regressie.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 5 - Enkelvoudige Lineaire Regressie-Analyse.</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Bijlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#scores-zijn-verdeeld-verschillende-vormen-van-verdelingen." id="toc-scores-zijn-verdeeld-verschillende-vormen-van-verdelingen." class="nav-link active" data-scroll-target="#scores-zijn-verdeeld-verschillende-vormen-van-verdelingen.">Scores zijn verdeeld, verschillende vormen van verdelingen.</a></li>
  <li><a href="#de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling" id="toc-de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling" class="nav-link" data-scroll-target="#de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling">De Normaalverdeling, Sommige Scores Volgen een Normaalverdeling</a></li>
  <li><a href="#opgaven-verdelingen" id="toc-opgaven-verdelingen" class="nav-link" data-scroll-target="#opgaven-verdelingen"><em>Opgaven</em> Verdelingen</a></li>
  <li><a href="#variabelen-in-de-steekproef-en-parameters-in-de-populatie" id="toc-variabelen-in-de-steekproef-en-parameters-in-de-populatie" class="nav-link" data-scroll-target="#variabelen-in-de-steekproef-en-parameters-in-de-populatie">Variabelen in de Steekproef en Parameters in de Populatie</a></li>
  <li><a href="#opgaven-variabelen-en-parameters" id="toc-opgaven-variabelen-en-parameters" class="nav-link" data-scroll-target="#opgaven-variabelen-en-parameters"><em>Opgaven</em> Variabelen en Parameters</a></li>
  <li><a href="#wat-is-normaal" id="toc-wat-is-normaal" class="nav-link" data-scroll-target="#wat-is-normaal">Wat is Normaal?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Hoofdstuk 2 - De Normaalverdeling.</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="scores-zijn-verdeeld-verschillende-vormen-van-verdelingen." class="level2">
<h2 class="anchored" data-anchor-id="scores-zijn-verdeeld-verschillende-vormen-van-verdelingen.">Scores zijn verdeeld, verschillende vormen van verdelingen.</h2>
<p>Als je heel vaak met een dobbelsteen gooit, weet je dat je ongeveer even vaak alle <em>mogelĳke</em> scores zult gooien, de zes verschilllende ‘gebeurtenissen’ ( elk van de zes verschillende aantal ogen op een dobbelsteen) zullen even vaak voorkomen. Omdat de kans op - of de <em>frequentie</em> van - elke gebeurtenis even groot zal zĳn, zeggen we ook wel dat de dobbelsteen univorm verdeeld is. Gelijke kansen voor elke waarde van <span class="math inline">\(X\)</span>, bij een zuivere of eerlijke dobbelsteen, is die kans op elke specifieke waarde (<span class="math inline">\(X=1\)</span>, <span class="math inline">\(X=2\)</span>, <span class="math inline">\(X=3\)</span>, <span class="math inline">\(X=4\)</span> <span class="math inline">\(X=5\)</span> of <span class="math inline">\(X=6\)</span>), <span class="math inline">\(1\)</span> op <span class="math inline">\(6\)</span> <span class="math inline">\(\left(\frac{1}{6} = .1667\right)\)</span>. Hieronder zie je de verdeling voor de scores van de variabele <span class="math inline">\(X\)</span>, de zes mogelijke waarden op een dobbelsteen. Je ziet dat boven elke waarde een vierkantje ligt die allemaal dezelfde oppervlakte hebben en die oppervlaktes staan voor de kans (<em>probability</em>) op onderliggende gebeurtenis. De oppervlakte van de zes vierkantjes samen is gelijk aan <span class="math inline">\(1\)</span>, en aangezien alle blokjes een gelijke oppervlakte hebben, moet een vierkantje dus een oppervlakte hebben van <span class="math inline">\(\frac{1}{6} = .1667\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Bronnen/pictures/H2unformDob.png" class="img-fluid figure-img" width="514"></p>
<figcaption>De Uniforme verdeling voor een dobbelsteen.</figcaption>
</figure>
</div>
</div>
</div>
<p>Zo is de kans dat je bijvoorbeeld de waarde ‘<span class="math inline">\(X = 3\)</span>’ gooit met een dobbelsteen dus gelijk aan <span class="math inline">\(\frac{1}{6}\)</span> of wiskundig schrijven we dan het volgende op:</p>
<p><span class="math display">\[P(X = 3) = \frac{1}{6}\]</span></p>
<p>Maar hoe zit dat met <em>vorm</em> van de kans-verdeling van de scores zoals voor belminuten, iemands lengte of iemands intelligentie, gemeten IQ-scores? Is de kans dat iemand <span class="math inline">\(170\)</span> centimeter is net zo groot als de kans op iemand die <span class="math inline">\(210\)</span> centimeter is? Komen deze gebeurtenissen net zo vaak voor, hebben ze dezelfde kans van optreden? Zĳn er op deze wereld net zoveel reuzen als gemiddelde mensen? Het mag misschien duidelĳk zĳn dat de scores voor lengte niet uniform verdeeld zĳn. De verschillende waarden die je tegenkomt, komen niet allemaal even vaak voor, sommige waarden of observaties kom je vaker tegen dan anderen. Mensen met ongeveer een gemiddelde lengte, zeg <span class="math inline">\(170\)</span> cm zĳn talrĳker dan met mensen met een extreme lengte (reuzen of lilliputters). De vorm van een kans verdeling vertelt ons dus <em>hoe</em> een bepaalde variabele zich gedraagt. Een dobbelsteen ‘gedraagt’ zich dus uniform. De vorm van zo’n verdeling hangt dus af van hoe een variabele zich gedraagt. Sommigen gebeurtenissen (voor een bepaalde variabele) gedragen zich ‘binomiaal’ en volgt de kans verdeling voor die variabele een binomiale kansverdeling. Bijvoorbeeld als je kijkt naar het totale <em>aantal</em> keer dat je ‘kop’ (<span class="math inline">\(X\)</span>) gooit, als je tien keer met een muntje gooit. Je bent dus hier het <em>aantal</em> “hits” aan het tellen. Het moge duidelijk zijn dat het aantal mogelijke waarden (bij deze telling) bij dit spelletje beperkt is (en dus discreet is). Als laagste waarde kan je dus <span class="math inline">\(X=0\)</span> hebben, als je dus nul keer kop gooit (beetje onwaarschijnlijk wel, maar er is toch een kleine kans dat je tien keer achter elkaar ‘munt’ gooit). Als hoogste waarde kun je dus <span class="math inline">\(X=10\)</span> krijgen en dat zijn bij elkaar dus elf mogelijke uitkomsten (<span class="math inline">\(0\)</span> t/m <span class="math inline">\(10\)</span>) voor de variabele <span class="math inline">\(X\)</span>. Het <em>aantal</em> hits is altijd een discrete variabele omdat je bijvoorbeeld niet halve of nog kleinere hits hebt, je kan niet anderhalf keer kop gooienn als je tien keer gooit! Maar goed er zijn dus heel veel vormen van verdelingen (distributions) en bij sommige variabelen is die vorm van de verdeling niet eens te benoemen met een naampje. Als we naar <em>continue</em> varabialen kijken zoals lengte of gewicht is de binomiale verdeling in ieder geval geen optie, een uniforme verdeling soms, maar heel vaak lijkt het erop dat een variabele zich <em>normaal</em> gedraagt (daar is niks ‘normaals’ aan hoor, ook hier is het slechts een naampje voor een hele eigenaardige vorm!).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21normaalverdeling1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>De Normaalverdeling</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling" class="level2">
<h2 class="anchored" data-anchor-id="de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling">De Normaalverdeling, Sommige Scores Volgen een Normaalverdeling</h2>
<p>In de statistiek komen we (heel) vaak variabelen tegen die zogezegd ‘normaal’ verdeeld zĳn (ik vind er niks ‘normaals’ aan hoor). Of we nemen in ieder geval aan dat die score zich normaal gedraagt in de populatie (je kunt het nooit écht weten toch?). Als een variabele qua kans (of frequentie) normaal verdeeld is, ‘gedraagt’ deze variabele zich dus ook volgens een bekend patroon, net zoals bij een uniforme verdeling, maar dan dus met een andere vorm: de zogenaamde klok-vorm ( <em>bell-shape</em> ) of klok curve (lijntje). Zoals bĳ een dobbelsteen bekend is dat deze zich uniform gedraagt, is bĳvoorbeeld van IQ-scores bekend (nemen we aan) dat deze variabele zich ‘normaal’ gedraagt in de populatie met een gemiddelde van <span class="math inline">\(100\)</span> (punten) en een standaardafwĳking van <span class="math inline">\(15\)</span> (punten). Sowieso kunnen we aan de hand van voorgaande hoofdstukken al stellen dat de beste gok voor een willekeurig persoon <span class="math inline">\(100\)</span> IQ-punten is en dat men gemiddeld dus <span class="math inline">\(15\)</span> punten van het gemiddelde verwĳderd zit. Maar ómdat IQ-scores zich ‘normaal’ gedragen, kunnen we nog <em>veel meer</em> uitspraken doen. Omdat we weten (aannemen) dat de variabele IQ normaal verdeeld is, kunnen we voor elke willekeurige waarde of score uitrekenen hoeveel procent van de populatie boven of onder die waarde zou moeten vallen. We kunnen punten dus uitrekenen wat de kans is dat iemand links of rechtsin van een bepaalde waarde zal vallen. Zoals je bĳ een dobbelsteen kunt uitrekenen wat de kans is op <span class="math inline">\(3\)</span> of <span class="math inline">\(4\)</span> gooien (p(<span class="math inline">\(x = 3\)</span> of <span class="math inline">\(x = 4\)</span>) <span class="math inline">\(= \frac{2}{6} = .333\)</span>), zo kun je nu bĳ IQ scores uitrekenen wat de kans is dat iemand een IQ heeft tussen de 120 en 130. We mogen deze berekeningen alleen doen als we ook daadwerkelĳk mogen aannemen dat de variabele normaal verdeeld is. Vaak in onderzoek worden tal van berekeningen gedaan op basis van onterechte ‘normaliteits-’ aannames en worden dus conclusies getrokken die nooit hadden mogen worden gedaan. Ik zal je mĳn frustraties hierover besparen en zo snel mogelĳk verder gaan met een aantal verlichtende opgaven.</p>
</section>
<section id="opgaven-verdelingen" class="level2">
<h2 class="anchored" data-anchor-id="opgaven-verdelingen"><em>Opgaven</em> Verdelingen</h2>
<div id="Opgave2.1" class="opgaven">
<section id="opgave-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgave-1">Opgave 1</h5>
<ol type="1">
<li><p>Stel, ik ga naar mars en kom in gesprek met een marsmannetje. Hij heeft nog nooit kennis gemaakt met iets of iemand van de planeet aarde, het enige wat hij wel beheerst, is een gezonde dosis statistiek-kennis. Het enige dat ik hem uitleg, is dat IQ een maat is voor iemands intelligentie en dat een hogere score ook staat voor een hogere intelligentie en dat deze score een normaal verdeling volgt. Verder vertel ik hem dat mijn IQ-score 130 is. Wat kan het marsmannetje nu zeggen over mijn score (in relatie tot de rest van de mensen op aarde)?</p></li>
<li><p>Ok, dat was wel erg weinig informatie. Ik vertel hem nu ook dat het gemiddelde voor IQ-scores <span class="math inline">\(100\)</span> is op aarde (<span class="math inline">\(\mu_x = 100\)</span>). Welke informatie voegt het gemiddelde toe? Wat kan het marsmannetje nu zeggen over mijn score in relatie tot de rest van de wereld?</p></li>
</ol>
</section>
</div>
<div id="Uitwerking2.1" class="uitwerkingen">
<section id="uitwerking-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-1">Uitwerking 1</h5>
<ol type="1">
<li><p>Alleen aan een ruwe score als informatie hebben we helemaal niks. Niemand kan op basis van slechts deze informatie zeggen of dit een hoge of een lage score is. Wat betekent een score van <span class="math inline">\(130\)</span> nou eigelijk? Om wel een antwoord hier op te kunnen geven heb je meer parameters nodig (die dus de rest van de bevolking ook beschrijven).</p></li>
<li><p>Door toevoeging van het gemiddelde en de informatie dat de score normaal verdeeld is, moet het marsmannetje wel weten dat we dus in de rechter helft van de verdeling vallen. Het gemiddelde is het midden en de score 130 bevindt zich daar rechts van. Het moet dus wel een hogere score zijn (ten opzichte van de ‘rest’). Maar hoe hoog, daar kunnen nu nog geen antwoord opgeven. Scores hebben of krijgen (vaak) alleen betekenis ten opzichte van elkaar, en zelfs dan is het echte verschil niet altijd duidelijk. Een IQ-score van <span class="math inline">\(128\)</span> is lager dan <span class="math inline">\(130\)</span>, ja, zelfs twee punten om precies te zijn, maar om hoeveel hersencellen gaat het? Overigens, een niet onbelangrijk vraag hier: is IQ überhaupt wel te definiëren (in termen van aantal hersencellen)?</p></li>
</ol>
</section>
</div>
</section>
<section id="variabelen-in-de-steekproef-en-parameters-in-de-populatie" class="level2">
<h2 class="anchored" data-anchor-id="variabelen-in-de-steekproef-en-parameters-in-de-populatie">Variabelen in de Steekproef en Parameters in de Populatie</h2>
<p>Nu vertel ik hem ook dat de standaardafwĳking <span class="math inline">\(15\)</span> (IQ-punten) is (<span class="math inline">\(\sigma_x = 15\)</span>. Aan de hand van deze informatie (gemiddelde, standaardafwĳking, een bepaalde score voor <span class="math inline">\(X\)</span> en de wetenschap dat deze variabele normaal verdeeld is) moet hĳ in staat zĳn om precies uit te zoeken hoeveel procent van de bevolking dommer is (links van mij zit) en hoeveel procent slimmer is (rechts van mij zit) dan ik (met een IQ van <span class="math inline">\(X = 130\)</span>). Dat is handige informatie, als je precies weet waar ik ten opzichte van de rest sta, dus mĳn positie (op de getallenlijn) qua IQ-score ten opzichte van de rest van de mogelĳke observaties in de wereld. Alleen aan de score <span class="math inline">\(X = 130\)</span> hebben we dus niet genoeg om te kunnen zeggen of dit hoog of laag is. Om uit te zoeken hoeveel procent van de populatie boven of onder mĳ valt, waaruit we dus kunnen afleiden of ik hoog of laag zit, moeten we <em>eerst</em> de ‘ruwe’ score (<span class="math inline">\(X_{Benjamin}=130\)</span>) ‘standaardiseren’ om <em>vervolgens</em> hierbĳ een ‘overschrĳdingskans’ op te zoeken. De variabele IQ heb ik dus omgedoopt tot de variabele <span class="math inline">\(X\)</span> en praat ik dus gewoon over de variabele ‘<span class="math inline">\(X\)</span>’. In de komende opgave gaan we over tot ‘standaardisatie’ van de ruwe score <span class="math inline">\(X\)</span> en gaan we bekĳken hoeveel procent van deze wereld nou echt slimmer is dan ik. We gaan het op twee verschillende manieren oplossen. Eerst aan de hand van een aantal vuistregels (voor standaardafwijkingen bij een normaalverdeling), vooral om inzicht te vergaren wat hier aan de hand is en zodat je in de toekomst altĳd een redelĳke schatting kun maken voordat je echt gaat rekenen. De tweede manier is aan de hand van de standaard-normaal verdeling (ook wel de ‘z-tabel’ waarbij de <span class="math inline">\(Z\)</span>-scores normaal verdeeld zijn), die ons een preciezere benadering geeft dan de vuistregels voor standaardafwijkingen bij een normaal verdeling.</p>
<p>Voordat we verder gaan, eerst nog even een stukje notatie. We hebben dus een variabele <span class="math inline">\(X\)</span> die normaal verdeeld is in de populatie (we nemen dit dus even aan) met een gemiddelde van <span class="math inline">\(100\)</span> en een standaardafwĳking van <span class="math inline">\(15\)</span>. we kunnen dit ook korter noteren:</p>
<p><span class="math display">\[X \mathtt{\sim} N(\mu_x = 100 ; \sigma_x = 15)\]</span> of nog korter (zonder de symbolen voor het gemiddelde en de standaardafwijking omdat we toch altijd eerst het gemiddelde en dan pas de standaardafwijking):</p>
<p><span class="math display">\[X \mathtt{\sim} N(100; 15)\]</span> Je spreekt uit als: ‘De variabele <span class="math inline">\(X\)</span> volgt een normaalverdeling met een gemiddelde van 100 en een standaardafwijking van 15’.</p>
<p>Of in het algemeen als je alleen maar wilt aan geven dat de variabele <span class="math inline">\(X\)</span> normaal verdeeld is:</p>
<p><span class="math display">\[X \mathtt{\sim} N(\mu_x; \sigma_x)\]</span> Eigenlijk omdat ik geen informatie heb gegeven over één enkele steekproef, maar over de gehele populatie, gebruiken heb ik dus geen statistieken voor het gemiddelde en standaardafwijking, maar <em>parameters</em> voor een beschrijving. En laten we wel wezen, niemand weet precies wat er in een populatie gebeurt. Wie weet er nou echt wat het gemiddelde voor IQ is als het gaat om de gehele populatie? Afgezien dat een populatie oneindig groot is, heb je nooit tĳd en of geld om iedereen op de gehele wereld op te meten qua IQ-score om dan vervolgens het ware gemiddelde te berekenen. Ik zeg altĳd maar zo (als geheugensteun): wĳ kunnen alleen maar dromen over het ware gemiddelde, laat staan uitrekenen. De Enige Echte die kan weten wat er zich echt afspeelt qua gemiddelde en standaardafwĳking en dus de echte waarden ervan weet, is God. Ik als agnost (atheïst durf ik niet te hard te zeggen) vind dat behoorlĳk vaag en wanneer iets vaag is, gebruik je ook vage letters! Vandaar dat we voor parameters ook vage letters gebruiken, Griekse wel te verstaan. Omdat dus <em>niemand</em> over <em>alle</em> data (<span class="math inline">\(X\)</span>-scores) uit de populatie beschikt, of de tijd heeft om oneindig veel data-punten te verwerken, kan niemand (strikt genomen) weten wat er precies in een populatie gebeurt (hoe een variabele zich gedraagt in een populatie) en dus eigenlijk ook geen uitspraak doen met <span class="math inline">\(100\)</span> procent of absolute zekerheid. Dus voor alle duidelijkheid, voor dit verhaal <em>nemen</em> we dus <em>slechts</em> even aan dat deze populatie normaal verdeeld is met <span class="math inline">\(\mu_x = 100\)</span> en <span class="math inline">\(\sigma_x = 15\)</span>. Het onderscheid tussen statistieken en parameters is qua gebruik nu nog niet heel belangrĳk, maar ik zal het toch consequent toepassen, zodat je er vast aan kunt wennen.</p>
</section>
<section id="opgaven-variabelen-en-parameters" class="level2">
<h2 class="anchored" data-anchor-id="opgaven-variabelen-en-parameters"><em>Opgaven</em> Variabelen en Parameters</h2>
<div id="Opgave2.2" class="opgaven">
<section id="opgave-2" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgave-2">Opgave 2</h5>
<ol type="1">
<li><p>Teken een normaal verdeling met een gemiddelde van <span class="math inline">\(100\)</span> en een standaardafwijking van <span class="math inline">\(15\)</span>. Als je vanuit het gemiddelde (het midden van je verdeling) <span class="math inline">\(1\)</span> standaardafwijking naar links wandelt, op welke waarde kom je dan uit? En als je <span class="math inline">\(1\)</span> standaardafwijking naar rechts wandelt? Volgens de vuistregel vind je altijd <em>ongeveer</em> <span class="math inline">\(68\)</span> procent van alle waarnemingen tussen deze twee waarden, dus tussen de waarden die je bereikt, als je <span class="math inline">\(1\)</span> standaardafwijking naar links en naar rechts ‘wandelt’ vanuit het midden. Hoeveel procent van de mogelijke observaties valt boven of rechts van de score <span class="math inline">\(X = 115\)</span>? Wat is dan dus de kans dat iemand een score heeft hoger of gelijk aan <span class="math inline">\(115\)</span>? In formule ook wel: <span class="math inline">\(P(X \geq 115)\)</span>. Dit is dus de kans (<span class="math inline">\(P\)</span> voor probability) dat de variabele <span class="math inline">\(X\)</span> een waarde aan neemt groter of gelijk (<span class="math inline">\(\geq\)</span>) aan <span class="math inline">\(115\)</span>. We noemen dit ook wel de rechteroverschrijdingskans (<em>right tail probabilty</em>) op <span class="math inline">\(X = 115\)</span>.</p></li>
<li><p>Als we niet <span class="math inline">\(1\)</span> maar <span class="math inline">\(2\)</span> standaardafwijkingen naar links en naar rechts wandelen vanuit <span class="math inline">\(\mu_x\)</span>, hebben we volgens de vuistregel <em>ongeveer</em> <span class="math inline">\(95\)</span> procent van de mogelijke waarden te pakken. Op welke <span class="math inline">\(X\)</span>-waarden komen we uit als we <span class="math inline">\(2\)</span> standaardafwijkingen naar links en naar rechts wandelen? Teken ook voor dit probleem weer een normaalverdeling met de nodige waarden erin. Wat is de kans dat iemand (op of) tussen de scores <span class="math inline">\(115\)</span> en <span class="math inline">\(130\)</span> valt, of ook wel: <span class="math inline">\(P(115 \leq  X \leq 130)\)</span> Spreek uit als: ‘De kans op <span class="math inline">\(115\)</span> kleiner gelijk <span class="math inline">\(X\)</span> én <span class="math inline">\(X\)</span> kleiner gelijk <span class="math inline">\(130\)</span>’</p></li>
<li><p>‘Toevallig’ had ik gezegd dat mijn IQ gelijk was aan <span class="math inline">\(130\)</span>. Wat is volgens de vuistregel ongeveer de kans dat iemand in de populatie lager of gelijk scoort? En wat is de kans dat iemand gelijk of hoger scoort? Respectievelijk zijn dit de kansen: <span class="math inline">\(P(X \leq 130)\)</span> en <span class="math inline">\(P(X ≥ 130)\)</span></p></li>
<li><p>Nu draaien we de vraag (een soort van) om. Hoe <em>slim</em> is ongeveer de slimste persoon van de domste <span class="math inline">\(2.5\)</span> procent van de populatie. Besef dat ik hier een kans <em>geef</em> (uitgedrukt in een percentage) in plaats van een (specifieke waarde voor de) gebeurtenis (waarde) voor <span class="math inline">\(X\)</span>. En ik <em>vraag</em> dus naar een specifieke <span class="math inline">\(X\)</span>-waarde waarop ik een overschrijdingskans wil weten. Gek maar waar: dit is de formulering in formulevorm die bij deze vraag hoort: <span class="math display">\[P(X \leq x) = 0.025\]</span> Spreek uit als: Voor <em>welke waarde</em> van <span class="math inline">\(x\)</span> is de kans dat <span class="math inline">\(X\)</span> een waarde aanneemt kleiner of gelijk aan die <span class="math inline">\(x\)</span> gelijk aan <span class="math inline">\(.025\)</span>?</p></li>
<li><p>Nog een omgekeerde vraagstelling. Volgens de vuistregel valt ongeveer <span class="math inline">\(99.7\)</span> procent van alle waarnemingen tussen <span class="math inline">\(3\)</span> standaardafwijkingen naar links en naar rechts. Voor welke waarde(n) van <span class="math inline">\(x\)</span> is de kans ongeveer <span class="math inline">\(.0015\)</span> ofwel <span class="math inline">\(0.15\)</span> procent dat <span class="math inline">\(X\)</span> een waarde aanneemt groter dan <span class="math inline">\(x\)</span>? De vraag is dus hier hoe slim de domste persoon (meest linkse waarneming) van de <span class="math inline">\(0.15\)</span> procent slimste mensen (de rechterstaart met een oppervlakte (die staat voor de kans) van <span class="math inline">\(p = .0015\)</span>). <span class="math inline">\(P(X \geq x) = .0015\)</span></p></li>
</ol>
</section>
</div>
<div id="Uitwerking2.2" class="uitwerkingen">
<section id="uitwerking-2" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-2">Uitwerking 2</h5>
<ol type="1">
<li>Eigenlijk hebben we de hele verdeling in drieën gehakt, ik spreek hier dus ook wel van een ‘driedeling’. Het linkerstuk (of linker staart) loopt van min-oneindig tot en met <span class="math inline">\(X = 85\)</span>. Het middenstuk dat precies in het midden ligt, loopt vanaf X = 85 tot en met <span class="math inline">\(X = 115\)</span>. Het rechterstuk loopt vanaf <span class="math inline">\(X = 115\)</span> tot en met plus oneindig. Het middenstuk beslaat volgens de vuistregel <span class="math inline">\(68\)</span> procent van de gehele verdeling. Je kunt ook zeggen dat de oppervlakte onder de curve tussen <span class="math inline">\(85\)</span> en <span class="math inline">\(115\)</span> gelijk is aan <span class="math inline">\(0.68\)</span>. In kansen wil dit zeggen: <span class="math display">\[P(85 \leq X \leq 115) = 0.68\]</span> De kans dat <span class="math inline">\(X\)</span> een waarde aanneemt tussen de <span class="math inline">\(85\)</span> en de <span class="math inline">\(115\)</span> is <span class="math inline">\(0.68\)</span> of je kan dus ook zeggen de <span class="math inline">\(68\)</span> procent van de bevolking een IQ heeft tussen de <span class="math inline">\(85\)</span> en de <span class="math inline">\(115\)</span>. Omdat de twee staartjes qua oppervlakte even groot moeten zijn (vanwege de symmetrie in deze verdeling) moeten ze samen de totale oppervlakte min 0.68 hebben. De totale oppervlakte van een verdeling is altijd <span class="math inline">\(1\)</span>. De twee staarten <em>samen</em> hebben dus een oppervlakte van <span class="math inline">\(0.32\)</span> en een enkele staart moet dus wel de helft van <span class="math inline">\(0.32\)</span> zijn. De vraag is hoeveel procent van de bevolking <span class="math inline">\(115\)</span> of meer scoort. <span class="math inline">\(P(X \geq 115) = .16\)</span>. Dus <span class="math inline">\(16\)</span> procent ongeveer.</li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/2-2vuistregelsNormaalverdeling-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Vuistregels voor 2 Standaardafwijkingen voor Normaal Verdeling</figcaption>
</figure>
</div>
</div>
</div>
<div id="Opgave2.2vervolg" class="uitwerkingen">
<ol start="2" type="1">
<li>Nu kunnen we het beste een ‘zes-deling’ maken en door optellen en aftrekken, vinden we de juiste oppervlakte. Het stuk vanaf het gemiddelde tot en met <span class="math inline">\(X=115\)</span> beslaat <span class="math inline">\(34\)</span> procent (de helft van <span class="math inline">\(68\)</span> procent). Het stuk vanaf het gemiddelde tot en met <span class="math inline">\(X=130\)</span> beslaat <span class="math inline">\(47.5\)</span> procent (de helft van 95 procent). Dus als het om het gevraagde stuk gaat: <span class="math display">\[P(115 \leq X \leq 130) = P(100 \leq X \leq 130) - P(100 \leq X \leq 115) = .475 - .34 = .135\]</span></li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/2-2vuistregels-voor-normaalverdeling2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Vuistregels voor Normaalverdeling</figcaption>
</figure>
</div>
</div>
</div>
<div id="Opgave2.2vervolg2" class="uitwerkingen">
<p><span class="math inline">\(13.5\)</span> procent van de bevolking heeft dus een IQ-score tussen de <span class="math inline">\(115\)</span> en de <span class="math inline">\(130\)</span>.</p>
<ol start="3" type="1">
<li><p>Kijk alleen even naar de rechter helft van de verdeling, dus vanaf het gemiddelde naar rechts. In de vorige vraag hadden we de rechterhelft (<span class="math inline">\(50\)</span> procent) in drie stukken gedeeld. Het gaat hier om het laatste stukje, het rechter staartje dus. Vanwege de twee standaardafwijking-vuistregel weten we dat het stuk van <span class="math inline">\(100\)</span> tot en met <span class="math inline">\(130\)</span> ongeveer <span class="math inline">\(47.5\)</span> procent moet beslaan. We houden dus nog slechts 2.5 procent over voor het laatste rechter staartje. Hiermee weten we dus de kans dat iemand hoger scoort dan (of gelijk aan) <span class="math inline">\(X=130\)</span>. <span class="math inline">\(P(X \geq 130) = 0.025\)</span> Om de vraag te beantwoorden hoeveel procent van de mensheid lager (of gelijk) scoort dan <span class="math inline">\(130\)</span>, moeten we dus uitvinden hoe groot de oppervlakte onder de curve is links van <span class="math inline">\(X=130\)</span>. <span class="math display">\[P(X \leq 130) = 1 – P(X \geq 130) = 1 – .0250 = .975\]</span> <span class="math inline">\(97.5\)</span> procent van de bevolking scoort <span class="math inline">\(130\)</span> of lager.</p></li>
<li><p>We zijn op zoek naar de slimste persoon van de 2.5 procent domste mensen. Waar in de verdeling bevinden zich de domste mensen? Die bevinden zich aan de linkerkant van de verdeling ofwel de linker staart beginnend bij <span class="math inline">\(X =\)</span> min oneindig (de allerdomste persoon) tot en met een waarde voor <span class="math inline">\(X\)</span> zodanig dat je <span class="math inline">\(2.5\)</span> procent van de bevolking te pakken hebt. Op basis vuistregels kunnen we zeggen een linkerstaartje van <span class="math inline">\(2.5\)</span> procent altijd begint bij min-oneindig en altijd eindigt op twee standaardafwijkingen links van het gemiddelde. De slimste persoon zit precies waar het staartje eindigt, dit is de hoogste waarde voor <span class="math inline">\(X\)</span> van alle mogelijke waarden van <span class="math inline">\(X\)</span> onder het staartje.</p></li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/2-2vuistregelsvoornormaalverdeling2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord vraag 2.4</figcaption>
</figure>
</div>
</div>
</div>
<div id="Opgave2.2vervolg3" class="uitwerkingen">
<ol start="5" type="1">
<li>We zijn op zoek naar de domste persoon van de <span class="math inline">\(0.15\)</span> procent slimste mensen. Mijn IQ van <span class="math inline">\(130\)</span> is helaas te laag, want dat was juist de ondergrens van de <span class="math inline">\(2.5\)</span> procent slimste mensen (ik hoor er weer es een keer niet bij). ‘Mijn staartje’ met een oppervlakte van <span class="math inline">\(p = .025\)</span> is dus groter of langer dan het ‘gegeven’ staartje van <span class="math inline">\(0.15\)</span> procent (<span class="math inline">\(p = .0015\)</span>, let op het aantal decimalen!). Of anders gezegd: mijn score (<span class="math inline">\(X = 130\)</span>) is minder ver verwijderd van het gemiddelde en is dus minder extreem dan de gevraagde score, die hoort bij de ‘gegeven’ overschrijdingskans van <span class="math inline">\(0.15\)</span> procent. <span class="math inline">\(99.7\)</span> procent van alle mogelijke waarnemingen valt dus tussen drie standaardafwijkingen links en drie standaardafwijkingen rechts van het gemiddelde. Je zou kunnen zeggen dat we nu met een driedeling te maken hebben met drie intervallen: <span class="math inline">\(X ≤ 55\)</span>, <span class="math inline">\(55 ≤ X ≤ 145\)</span> en <span class="math inline">\(X ≥ 145\)</span> qua scores en de drie bijbehorende kansen voor deze drie stukken: <span class="math inline">\(P(X \leq 55) = .0015\)</span> <span class="math inline">\(P(55 \leq X \leq 145) = .9970\)</span> <span class="math inline">\(P(X \geq 145) = .0015\)</span> Dus de driedeling qua kansen: <span class="math inline">\(.0015 - .9970 - .0015\)</span></li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/2-2Vuistregels-voor-normaalverdeling-3sigma-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord vraag 2.5</figcaption>
</figure>
</div>
</div>
</div>
<div id="Opgave2.2vervolg4" class="uitwerkingen">
<ul>
<li>Toevallig begint het staartje van <span class="math inline">\(0.15\)</span> procent (<span class="math inline">\(p = 0.0015\)</span>) waar wij mee te maken hebben, precies bij <span class="math inline">\(X=145\)</span>. Een IQ score van <span class="math inline">\(145\)</span> is dus de ondergrens van het staartje die de slimste <span class="math inline">\(0.15\)</span> procent van de bevolking representeert. <span class="math inline">\(P(X \geq x) = 0.0015\)</span> We zijn dus opzoek naar de waarde voor de kleine <span class="math inline">\(x\)</span> zodanig dat de stelling klopt. De kleine <span class="math inline">\(x\)</span> moet dus <span class="math inline">\(145\)</span> zijn want alleen dan klopt de stelling! De domste onder de 0.15 procent slimste mensen moet dus ongeveer een IQ hebben van <span class="math inline">\(145\)</span> punten.</li>
</ul>
</div>
<div id="Opgave2.3" class="opgaven">
<section id="opgave-3" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgave-3"><em>Opgave</em> 3</h5>
<p>In opgave 2 hebben we gekeken naar hoe vaak bepaalde scores binnen een verdeling voorkomen (uitgedrukt in kansen of percentages) aan de hand van de vuistregels voor standaardafwijkingen. In de deze opgave gaan we hetzelfde doen, maar dan aan de hand van <span class="math inline">\(z\)</span>-scores en de <span class="math inline">\(z\)</span>-tabel. We kunnen dan ook scores bekijken die niet precies <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span> of <span class="math inline">\(3\)</span> standaardafwĳkingen van het gemiddelde vandaan liggen (de wereld bestaat niet alleen uit mooie ronde getallen).</p>
<ol type="1">
<li>We hebben de ruwe score dus omgezet (getransformeerd) naar een nieuw soort score die ons alleen nog vertelt <em>hoeveel</em> standaardafwijkingen de oorspronkelijke score verwijderd is van het gemiddelde. We noemen de getransformeerde score een gestandaardiseerde score of een <span class="math inline">\(Z\)</span>-score. We zijn dus van een ruwe ‘gebeurtenis’ naar een gestandaardiseerde ‘gebeurtenis’ over gegaan. <span class="math inline">\(X_{Benjamin} = 130\)</span>, ruwe (of ongestandaardiseerde) score <span class="math inline">\(Z_{Benjamin} = 2.00\)</span>, gestandaardiseerde score (standardized score) Aan de hand van de berekende <span class="math inline">\(z\)</span>-waarde kunnen we nu opzoeken in de <span class="math inline">\(z\)</span>-tabel wat de kans is dat een bepaalde <span class="math inline">\(z\)</span>-waarde een hogere – of een lagere – waarde kan aannemen dan de opgezochte waarde voor <span class="math inline">\(z\)</span>. We zijn in ons geval dus geïnteresseerd in de rechter overschrijdingskans op <span class="math inline">\(z\)</span> is <span class="math inline">\(2.00\)</span>, omdat ik wilde weten hoeveel procent van de mensheid slimmer is dan ik, dus boven (of gelijk aan) de <span class="math inline">\(130\)</span> scoort. De tabel geeft <span class="math inline">\(z\)</span>-waarden (afgerond op <span class="math inline">\(2\)</span> decimalen) en geeft de daarbij behorende, vaste linker overschrijdingskansen. Zoek de waarde <span class="math inline">\(z = 2.00\)</span> op en kijk welke overschrijdingskans (<span class="math inline">\(p\)</span>-waarde) de tabel daarbij geeft. Als we de kans willen weten dat iemand <span class="math inline">\(130\)</span> of hoger scoort, wat moeten we dan nog doen met de opgezochte kans? Hieronder geef ik een voorbeeld om de linker overschrijdingskans te vinden voor <span class="math inline">\(z = 1.00\)</span>. de eerste kolom laat <span class="math inline">\(z\)</span>-waarden zien, maar voor slechts (tot en met) het eerste decimaal. de bovenste rij laat het tweede decimaal zien (dus het derde cijfer in het getal). Bij <span class="math inline">\(z = 1.00\)</span> zijn het eerste én tweede decimaal allebei <span class="math inline">\(0\)</span>, dus kijk je bij de rij voor <span class="math inline">\(z = 1.0\)</span> (roze) en bij de kolom met de waarde <span class="math inline">\(0.00\)</span> bovenaan, vervolgens kijk je waar die rij en kolom samen komen en je vindt daar de linker overschrijdingskans (<span class="math inline">\(p = 0.8413\)</span>). Dus bijvoorbeeld bij <span class="math inline">\(z = 1.67\)</span> hoort een <span class="math inline">\(p\)</span>-waarde van <span class="math inline">\(.9525\)</span>.</li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Standaard Normaalverdeling</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">$Z$</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.00</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.01</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.02</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.03</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.04</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.05</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.06</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.07</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.08</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.09</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">**0.0**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.5000</td>
<td style="text-align: right;">0.5040</td>
<td style="text-align: right;">0.5080</td>
<td style="text-align: right;">0.5120</td>
<td style="text-align: right;">0.5160</td>
<td style="text-align: right;">0.5199</td>
<td style="text-align: right;">0.5239</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.5279</td>
<td style="text-align: right;">0.5319</td>
<td style="text-align: right;">0.5359</td>
</tr>
<tr class="even">
<td style="text-align: right;">**0.1**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.5398</td>
<td style="text-align: right;">0.5438</td>
<td style="text-align: right;">0.5478</td>
<td style="text-align: right;">0.5517</td>
<td style="text-align: right;">0.5557</td>
<td style="text-align: right;">0.5596</td>
<td style="text-align: right;">0.5636</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.5675</td>
<td style="text-align: right;">0.5714</td>
<td style="text-align: right;">0.5753</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**0.2**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.5793</td>
<td style="text-align: right;">0.5832</td>
<td style="text-align: right;">0.5871</td>
<td style="text-align: right;">0.5910</td>
<td style="text-align: right;">0.5948</td>
<td style="text-align: right;">0.5987</td>
<td style="text-align: right;">0.6026</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.6064</td>
<td style="text-align: right;">0.6103</td>
<td style="text-align: right;">0.6141</td>
</tr>
<tr class="even">
<td style="text-align: right;">**0.3**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.6179</td>
<td style="text-align: right;">0.6217</td>
<td style="text-align: right;">0.6255</td>
<td style="text-align: right;">0.6293</td>
<td style="text-align: right;">0.6331</td>
<td style="text-align: right;">0.6368</td>
<td style="text-align: right;">0.6406</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.6443</td>
<td style="text-align: right;">0.6480</td>
<td style="text-align: right;">0.6517</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**0.4**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.6554</td>
<td style="text-align: right;">0.6591</td>
<td style="text-align: right;">0.6628</td>
<td style="text-align: right;">0.6664</td>
<td style="text-align: right;">0.6700</td>
<td style="text-align: right;">0.6736</td>
<td style="text-align: right;">0.6772</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.6808</td>
<td style="text-align: right;">0.6844</td>
<td style="text-align: right;">0.6879</td>
</tr>
<tr class="even">
<td style="text-align: right;">**0.5**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.6915</td>
<td style="text-align: right;">0.6950</td>
<td style="text-align: right;">0.6985</td>
<td style="text-align: right;">0.7019</td>
<td style="text-align: right;">0.7054</td>
<td style="text-align: right;">0.7088</td>
<td style="text-align: right;">0.7123</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.7157</td>
<td style="text-align: right;">0.7190</td>
<td style="text-align: right;">0.7224</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**0.6**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.7257</td>
<td style="text-align: right;">0.7291</td>
<td style="text-align: right;">0.7324</td>
<td style="text-align: right;">0.7357</td>
<td style="text-align: right;">0.7389</td>
<td style="text-align: right;">0.7422</td>
<td style="text-align: right;">0.7454</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.7486</td>
<td style="text-align: right;">0.7517</td>
<td style="text-align: right;">0.7549</td>
</tr>
<tr class="even">
<td style="text-align: right;">**0.7**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.7580</td>
<td style="text-align: right;">0.7611</td>
<td style="text-align: right;">0.7642</td>
<td style="text-align: right;">0.7673</td>
<td style="text-align: right;">0.7704</td>
<td style="text-align: right;">0.7734</td>
<td style="text-align: right;">0.7764</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.7794</td>
<td style="text-align: right;">0.7823</td>
<td style="text-align: right;">0.7852</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**0.8**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.7881</td>
<td style="text-align: right;">0.7910</td>
<td style="text-align: right;">0.7939</td>
<td style="text-align: right;">0.7967</td>
<td style="text-align: right;">0.7995</td>
<td style="text-align: right;">0.8023</td>
<td style="text-align: right;">0.8051</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.8078</td>
<td style="text-align: right;">0.8106</td>
<td style="text-align: right;">0.8133</td>
</tr>
<tr class="even">
<td style="text-align: right;">**0.9**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.8159</td>
<td style="text-align: right;">0.8186</td>
<td style="text-align: right;">0.8212</td>
<td style="text-align: right;">0.8238</td>
<td style="text-align: right;">0.8264</td>
<td style="text-align: right;">0.8289</td>
<td style="text-align: right;">0.8315</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.8340</td>
<td style="text-align: right;">0.8365</td>
<td style="text-align: right;">0.8389</td>
</tr>
<tr class="odd">
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">**1.0**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important; background-color: rgba(237, 175, 175, 255) !important;">0.8413</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8438</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8461</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8485</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8508</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8531</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8554</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important; background-color: rgba(185, 237, 217, 255) !important;">0.8577</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8599</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.8621</td>
</tr>
<tr class="even">
<td style="text-align: right;">**1.1**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.8643</td>
<td style="text-align: right;">0.8665</td>
<td style="text-align: right;">0.8686</td>
<td style="text-align: right;">0.8708</td>
<td style="text-align: right;">0.8729</td>
<td style="text-align: right;">0.8749</td>
<td style="text-align: right;">0.8770</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.8790</td>
<td style="text-align: right;">0.8810</td>
<td style="text-align: right;">0.8830</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**1.2**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.8849</td>
<td style="text-align: right;">0.8869</td>
<td style="text-align: right;">0.8888</td>
<td style="text-align: right;">0.8907</td>
<td style="text-align: right;">0.8925</td>
<td style="text-align: right;">0.8944</td>
<td style="text-align: right;">0.8962</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.8980</td>
<td style="text-align: right;">0.8997</td>
<td style="text-align: right;">0.9015</td>
</tr>
<tr class="even">
<td style="text-align: right;">**1.3**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9032</td>
<td style="text-align: right;">0.9049</td>
<td style="text-align: right;">0.9066</td>
<td style="text-align: right;">0.9082</td>
<td style="text-align: right;">0.9099</td>
<td style="text-align: right;">0.9115</td>
<td style="text-align: right;">0.9131</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9147</td>
<td style="text-align: right;">0.9162</td>
<td style="text-align: right;">0.9177</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**1.4**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9192</td>
<td style="text-align: right;">0.9207</td>
<td style="text-align: right;">0.9222</td>
<td style="text-align: right;">0.9236</td>
<td style="text-align: right;">0.9251</td>
<td style="text-align: right;">0.9265</td>
<td style="text-align: right;">0.9279</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9292</td>
<td style="text-align: right;">0.9306</td>
<td style="text-align: right;">0.9319</td>
</tr>
<tr class="even">
<td style="text-align: right;">**1.5**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9332</td>
<td style="text-align: right;">0.9345</td>
<td style="text-align: right;">0.9357</td>
<td style="text-align: right;">0.9370</td>
<td style="text-align: right;">0.9382</td>
<td style="text-align: right;">0.9394</td>
<td style="text-align: right;">0.9406</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9418</td>
<td style="text-align: right;">0.9429</td>
<td style="text-align: right;">0.9441</td>
</tr>
<tr class="odd">
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">**1.6**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important; background-color: rgba(250, 221, 195, 255) !important;">0.9452</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9463</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9474</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9484</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9495</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9505</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9515</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important; background-color: rgba(250, 221, 195, 255) !important;">0.9525</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9535</td>
<td style="text-align: right; background-color: rgba(250, 221, 195, 255) !important;">0.9545</td>
</tr>
<tr class="even">
<td style="text-align: right;">**1.7**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9554</td>
<td style="text-align: right;">0.9564</td>
<td style="text-align: right;">0.9573</td>
<td style="text-align: right;">0.9582</td>
<td style="text-align: right;">0.9591</td>
<td style="text-align: right;">0.9599</td>
<td style="text-align: right;">0.9608</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9616</td>
<td style="text-align: right;">0.9625</td>
<td style="text-align: right;">0.9633</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**1.8**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9641</td>
<td style="text-align: right;">0.9649</td>
<td style="text-align: right;">0.9656</td>
<td style="text-align: right;">0.9664</td>
<td style="text-align: right;">0.9671</td>
<td style="text-align: right;">0.9678</td>
<td style="text-align: right;">0.9686</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9693</td>
<td style="text-align: right;">0.9699</td>
<td style="text-align: right;">0.9706</td>
</tr>
<tr class="even">
<td style="text-align: right;">**1.9**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9713</td>
<td style="text-align: right;">0.9719</td>
<td style="text-align: right;">0.9726</td>
<td style="text-align: right;">0.9732</td>
<td style="text-align: right;">0.9738</td>
<td style="text-align: right;">0.9744</td>
<td style="text-align: right;">0.9750</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9756</td>
<td style="text-align: right;">0.9761</td>
<td style="text-align: right;">0.9767</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**2.0**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9772</td>
<td style="text-align: right;">0.9778</td>
<td style="text-align: right;">0.9783</td>
<td style="text-align: right;">0.9788</td>
<td style="text-align: right;">0.9793</td>
<td style="text-align: right;">0.9798</td>
<td style="text-align: right;">0.9803</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9808</td>
<td style="text-align: right;">0.9812</td>
<td style="text-align: right;">0.9817</td>
</tr>
<tr class="even">
<td style="text-align: right;">**2.1**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9821</td>
<td style="text-align: right;">0.9826</td>
<td style="text-align: right;">0.9830</td>
<td style="text-align: right;">0.9834</td>
<td style="text-align: right;">0.9838</td>
<td style="text-align: right;">0.9842</td>
<td style="text-align: right;">0.9846</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9850</td>
<td style="text-align: right;">0.9854</td>
<td style="text-align: right;">0.9857</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**2.2**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9861</td>
<td style="text-align: right;">0.9864</td>
<td style="text-align: right;">0.9868</td>
<td style="text-align: right;">0.9871</td>
<td style="text-align: right;">0.9875</td>
<td style="text-align: right;">0.9878</td>
<td style="text-align: right;">0.9881</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9884</td>
<td style="text-align: right;">0.9887</td>
<td style="text-align: right;">0.9890</td>
</tr>
<tr class="even">
<td style="text-align: right;">**2.3**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9893</td>
<td style="text-align: right;">0.9896</td>
<td style="text-align: right;">0.9898</td>
<td style="text-align: right;">0.9901</td>
<td style="text-align: right;">0.9904</td>
<td style="text-align: right;">0.9906</td>
<td style="text-align: right;">0.9909</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9911</td>
<td style="text-align: right;">0.9913</td>
<td style="text-align: right;">0.9916</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**2.4**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9918</td>
<td style="text-align: right;">0.9920</td>
<td style="text-align: right;">0.9922</td>
<td style="text-align: right;">0.9925</td>
<td style="text-align: right;">0.9927</td>
<td style="text-align: right;">0.9929</td>
<td style="text-align: right;">0.9931</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9932</td>
<td style="text-align: right;">0.9934</td>
<td style="text-align: right;">0.9936</td>
</tr>
<tr class="even">
<td style="text-align: right;">**2.5**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9938</td>
<td style="text-align: right;">0.9940</td>
<td style="text-align: right;">0.9941</td>
<td style="text-align: right;">0.9943</td>
<td style="text-align: right;">0.9945</td>
<td style="text-align: right;">0.9946</td>
<td style="text-align: right;">0.9948</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9949</td>
<td style="text-align: right;">0.9951</td>
<td style="text-align: right;">0.9952</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**2.6**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9953</td>
<td style="text-align: right;">0.9955</td>
<td style="text-align: right;">0.9956</td>
<td style="text-align: right;">0.9957</td>
<td style="text-align: right;">0.9959</td>
<td style="text-align: right;">0.9960</td>
<td style="text-align: right;">0.9961</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9962</td>
<td style="text-align: right;">0.9963</td>
<td style="text-align: right;">0.9964</td>
</tr>
<tr class="even">
<td style="text-align: right;">**2.7**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9965</td>
<td style="text-align: right;">0.9966</td>
<td style="text-align: right;">0.9967</td>
<td style="text-align: right;">0.9968</td>
<td style="text-align: right;">0.9969</td>
<td style="text-align: right;">0.9970</td>
<td style="text-align: right;">0.9971</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9972</td>
<td style="text-align: right;">0.9973</td>
<td style="text-align: right;">0.9974</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**2.8**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9974</td>
<td style="text-align: right;">0.9975</td>
<td style="text-align: right;">0.9976</td>
<td style="text-align: right;">0.9977</td>
<td style="text-align: right;">0.9977</td>
<td style="text-align: right;">0.9978</td>
<td style="text-align: right;">0.9979</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9979</td>
<td style="text-align: right;">0.9980</td>
<td style="text-align: right;">0.9981</td>
</tr>
<tr class="even">
<td style="text-align: right;">**2.9**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9981</td>
<td style="text-align: right;">0.9982</td>
<td style="text-align: right;">0.9982</td>
<td style="text-align: right;">0.9983</td>
<td style="text-align: right;">0.9984</td>
<td style="text-align: right;">0.9984</td>
<td style="text-align: right;">0.9985</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9985</td>
<td style="text-align: right;">0.9986</td>
<td style="text-align: right;">0.9986</td>
</tr>
<tr class="odd">
<td style="text-align: right;">**3.0**</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">0.9987</td>
<td style="text-align: right;">0.9987</td>
<td style="text-align: right;">0.9987</td>
<td style="text-align: right;">0.9988</td>
<td style="text-align: right;">0.9988</td>
<td style="text-align: right;">0.9989</td>
<td style="text-align: right;">0.9989</td>
<td style="text-align: right; background-color: rgba(185, 237, 217, 255) !important;">0.9989</td>
<td style="text-align: right;">0.9990</td>
<td style="text-align: right;">0.9990</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="Opgave2.3vervolg0" class="opgaven">
<p>2.. Als ik mijn eigen ego een beetje extra zou willen strelen, zou ik dan de z-tabel of de vuistregel beter kunnen gebruiken om de overschrijdingskans te berekenen. Met andere woorden: In hoeverre verschilt de uitkomst van 2 op basis van de z-tabel in vergelijking tot de oplossing volgens de vuistregels (opgave 3)?</p>
<ol start="3" type="1">
<li><p>Wat is de kans dat iemand een score heeft lager of gelijk aan <span class="math inline">\(X = 125\)</span>? of ook wel: <span class="math inline">\(P(X \leq 125)\)</span>. Geef je antwoord ook in een percentage.</p></li>
<li><p>Hoeveel procent van de bevolking heeft een IQ hoger (of gelijk aan) <span class="math inline">\(125\)</span>? of dus ook wel: <span class="math inline">\(P(X \geq 125)\)</span></p></li>
<li><p>Wat is de kans dat iemand een score voor <span class="math inline">\(X\)</span> heeft lager of gelijk aan <span class="math inline">\(75\)</span>? Of dus: <span class="math inline">\(P(X \leq 75)\)</span></p></li>
<li><p>Wat is de kans dat iemand een score heeft hoger gelijk 75?</p></li>
<li><p>Stel je bent heel lui (lui is goed, daar word je wiskundig van). Wat is het minimale aantal keerdat je de z-tabel zou moeten raadplegen om vraag 4 t/m 7 op te lossen?</p></li>
</ol>
</div>
<div id="Uitwerking2.3" class="uitwerkingen">
<section id="uitwerking-3" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-3"><em>Uitwerking</em> 3</h5>
<p>1.<span class="math inline">\(X_{Benjamin} = 130\)</span> <span class="math inline">\(z_i = \frac{X_i – \mu_x}{\sigma_x}\)</span> <span class="math inline">\(z_{Benjamin} = \frac{X_{Benjamin} – \mu_x}{\sigma_x} = \frac{130-100}{15} = (130-100)/15 = 2.00\)</span> Berekening in woorden: eerst neem (bereken) je het ruwe verschil tussen de observatie (<span class="math inline">\(x=130\)</span>) en het gemiddelde (<span class="math inline">\(\mu_x = 100\)</span>) en daarna deel je het gevonden verschil door de standaardafwijking <span class="math inline">\(\sigma_x = 15\)</span>. Het antwoord geeft je dus het <em>aantal</em> standaardafwijkingen dat de waarneming van het gemiddelde verwijderd ligt. Gewoon een telling dus die hoort bij de vraag: Hoe vaak past de standaardafwijking tussen de observatie en het gemiddelde? Denk dus maar gewoon even dat een standaardafwijking lineaaltje is die je een <em>aantal</em> keer moet neerleggen vanaf het gemiddelde (midden van de normaal verdeling) om bij die speciefieke gebeurtenis (observatie of score) te komen.</p>
<ol start="2" type="1">
<li>De <span class="math inline">\(z\)</span>-tabel (zie appendix) geeft alleen linker overschrijdingskansen, dus de kans dat een gebeurtenis of score links van een bepaalde waarde valt: <span class="math display">\[P(z \leq 2.00) = .9772\]</span> Je kijkt dus naar de rij waar <span class="math inline">\(z=2.0\)</span> staat (voor het eerste decimaal of eerste cijfer na de komma) en de kolom waar ‘<span class="math inline">\(0.00\)</span>’ staat (voor het tweede decimaal achter de komma) en vervolgens kijk je waar deze rij en kolom samen komen voor de bijbehorende <span class="math inline">\(p\)</span>-waarde (kans). Dit wil dus zeggen dat de kans <span class="math inline">\(.9772\)</span> is dat <span class="math inline">\(z\)</span> een waarde aanneemt kleiner gelijk <span class="math inline">\(2.00\)</span>. Deze overschrijdingskans geldt dus ook voor de ruwe waarde (<span class="math inline">\(X=130\)</span>). Omdat de kans die ze geven eigenlijk overeen komt met de oppervlakte (<em>area</em>) onder de curve (kromme lijntje) links van <span class="math inline">\(z=2.00\)</span>, noemen we dit ook wel de <em>left tail probability</em>.</li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21uitwerking22-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking opgave 2.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21uitwerking22-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking opgave 2.2</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking2.3vervolg" class="uitwerkingen">
<ul>
<li>Met andere woorden: <span class="math inline">\(97.72\)</span> procent van de bevolking is dus dommer dan ik! Maar wij wilde eigenlijk weten hoeveel procent slimmer is dan ik ofwel de kans dat iemand 130 of hoger scoort in de populatie. Wanneer je een hele verdeling in tweeën hakt (in ons geval bij <span class="math inline">\(z=2.00\)</span> of <span class="math inline">\(X=130\)</span>), hebben de rechter en linker staart samen altijd een oppervlakte (kans en ook wel proportie ) van <span class="math inline">\(1.00\)</span>. Nu dus nog één stapje om dat laatste op te lossen: <span class="math inline">\(P(X \geq 130) = P(z \geq 2.00) = 1 – P(z \leq 2.00) = 1 – 0.9772 = 0.0228\)</span> Nu hebben we de oppervlakte van de rechterstaart en deze staat dus voor de kans dat <span class="math inline">\(z\)</span> een waarde aanneemt groter gelijk <span class="math inline">\(2.00\)</span> ofwel de <em>right tail probability</em> dus. Ik kan dus nu zeggen dat slechts <span class="math inline">\(2.28\)</span> procent van de bevolking slimmer is dan ik, omdat deze overschrijdingskans dus ook op gaat voor de ruwe (ongestandaardiseerde) score <span class="math inline">\(X=130\)</span>.</li>
</ul>
<ol start="3" type="1">
<li><p>Volgens de vuistregels voor standaardafwijkingen, is de rechter overschrijdingskans gelijk aan <span class="math inline">\(2.5\)</span> procent en op basis van de standaard normaaltabel <span class="math inline">\(2.28\)</span> procent. Mijn ego is gebaat bij zo min mogelijk mensen die slimmer zijn dan ik en dus kies ik voor de <span class="math inline">\(z\)</span>-tabel in plaats van de vuistregels voor standaardafwijkingen omdat die overschrijdingskans net iets lager uitvalt (<span class="math inline">\(p = .0228\)</span> is kleiner dan <span class="math inline">\(p = .025\)</span>), waardoor ik dus een extremere waarde qua IQ lijkt te hebben.</p></li>
<li><p>De ruwe score (<span class="math inline">\(X=125\)</span>) waarop de linker overschrijdingskans wordt gevraagd, moet eerst worden omgezet naar een gestandaardiseerde score, een <span class="math inline">\(z\)</span>-score. <span class="math inline">\(X=125\)</span> <span class="math inline">\(z = \frac{X - \mu_{x}}{\sigma_{x}} = \frac{125 - 100}{15}=(125-100)/15 = 1.67\)</span> <span class="math inline">\(z=1.67\)</span></p></li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking34-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 2.4</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking342-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 2.4</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking2.3vervolg2" class="uitwerkingen">
<ul>
<li>Nu kun je de bijbehorende overschrijdingskans opzoeken in de <span class="math inline">\(z\)</span>-tabel (officiëel heet deze de ‘standaard normaaltabel’, maar ik noem hem lekker gewoon de <span class="math inline">\(z\)</span>-tabel). In de kolom links vind je de <span class="math inline">\(z\)</span>-scores met het eerste decimaal (de <span class="math inline">\(6\)</span> uit <span class="math inline">\(1.67\)</span>), voor het tweede decimaal (de <span class="math inline">\(7\)</span>), moet je in de bovenste rij kijken van de tabel en zoek naar de kolom waar <span class="math inline">\(0.07\)</span> boven staat. Dan kijk je waar rij en kolom samenkomen en daar vind je de <span class="math inline">\(p\)</span>-waarde. Vervolgens kunnen we zeggen: <span class="math inline">\(P(X \leq 125) = P(Z \leq 1.67) = .9525\)</span> De <span class="math inline">\(z\)</span>-tabel geeft de linker overschrijdingskans. Dus <span class="math inline">\(95.25\)</span> procent van de bevolking scoort lager of gelijk aan <span class="math inline">\(X=125\)</span>.</li>
</ul>
<ol start="5" type="1">
<li><p>De (grens-) gebeurtenis blijft hetzelfde als bij de vorige vraag (<span class="math inline">\(X=125\)</span>), alleen moeten we nu de rechter overschrijdingskans – eigenlijk percentage – uitrekenen. We hadden de ruwe verdeling in tweeën gehakt bij <span class="math inline">\(X=125\)</span> of in de gestandaardiseerde verdeling bij <span class="math inline">\(z=1.67\)</span>. De oppervlakte van het linkerstuk (<em>left tail probability</em>) hadden we al gevonden bij de vorige vraag (<span class="math inline">\(p=0.9525\)</span>). Het rechter stuk (right tail probability) moet dus wel het resterende gedeelte zijn. In formules: <span class="math inline">\(P(X \geq 125) = 1 – P(X \leq 125) = P(Z \geq 1.67) = 1 – P(Z \leq 1.67) = 1 – 0.9525 = 0.0475\)</span> In de vraag vroeg ik om een percentage, dus moet je ook in percentages antwoorden en niet met een kans komen aandraven. Dus maken we het nog even af: de kans van <span class="math inline">\(p=.0475\)</span> komt overeen met een percentage van <span class="math inline">\(4.75\)</span> procent (de kans dus vermenigvuldigen met een factor <span class="math inline">\(100\)</span>).</p></li>
<li><p>In plaats van <span class="math inline">\(25\)</span> punten rechts van het gemiddelde zitten we nu <span class="math inline">\(25\)</span> punten links van het gemiddelde. Er wordt gevraagd naar een linker overschrijdingskans. X=75 <span class="math inline">\(X=75\)</span> <span class="math inline">\(z = \frac{X - \mu_{x}}{\sigma_{x}} = \frac{75 - 100}{15}=(75-100)/15 = \text{-}1.67\)</span> <span class="math inline">\(z=\text{-}1.67\)</span> De waarde voor <span class="math inline">\(z\)</span> is - absoluut gezien - even groot als bij de vorige vraag, alleen nu negatief! We moeten dus zoeken bij de negatieven z-waarden. Ik heb jullie maar één <span class="math inline">\(z\)</span>-tabel gegeven, alleen voor positieve <span class="math inline">\(z\)</span>-waarden. Er zijn heel veel soorten <span class="math inline">\(z\)</span>-tabellen, die dus ook net weer even iets anders werken qua opzoeken. Ik ben lui en wil jullie extra laten nadenken, dus ik heb jullie maar één <span class="math inline">\(z\)</span>-tabel gegeven, alleen eentje voor de <em>positieve</em> <span class="math inline">\(z\)</span>-waarden. Lang Leve Symmetrie (twee zijdige gelijkheid)! Kijk maar even mee.</p></li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking36-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 3.6</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking36-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 3.6</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking2.3vervolg3" class="uitwerkingen">
<ul>
<li>Laten we afspreken dat bij elke <span class="math inline">\(z\)</span>-waarde vanaf nu een tweedeling qua kansen (percentage, staarten, proporties) hoort. Je ziet dat bij <span class="math inline">\(z=1.67\)</span> dus de tweedeling ’<span class="math inline">\(p = .9525\)</span>, voor de grote of linker staart en <span class="math inline">\(p = .0475\)</span>, voor de kleine of rechter staart. Als je met de dezelfde <span class="math inline">\(z\)</span>-waarde te maken hebt, maar dan negatief, dus <span class="math inline">\(z=\text{-}1.67\)</span>, hebben we met dezelfde tweedeling te maken alleen wordt de linker staart nu <em>klein</em> en de rechter staart dus <em>groot</em>, de boel draait dus om!<br>
<span class="math inline">\(P(X \leq 75) = P(z \leq \text{–}1.67) = 0.0475\)</span> De kans is dus <span class="math inline">\(0.0475\)</span> (weer?!) dat iemand lager of gelijk een IQ van <span class="math inline">\(75\)</span> heeft.</li>
</ul>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/uitwerking36-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord 3.6</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/uitwerking362-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord 3.6</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking2.3vervolg4" class="uitwerkingen">
<ol start="7" type="1">
<li><p><span class="math inline">\(P(X \leq 125) = 1 – P(X \leq 125) = P(z \geq \text{-}1.67) = 1 – P(z \leq \text{-}1.67) = 1 – 0.0475 = 0.9525\)</span> De kans is dus <span class="math inline">\(.9525\)</span> (weer?!) dat iemand hoger of gelijk aan <span class="math inline">\(X=75\)</span>.</p></li>
<li><p>We hadden slechts één keer de tabel te hoeven raadplegen. Elke <span class="math inline">\(z\)</span>-waarde (in ons geval <span class="math inline">\(z= 1.67\)</span>) heeft een <em>linker</em> én een <em>rechter</em> overschrijdingskans, de zogenaamde tweedeling. Of de <span class="math inline">\(z\)</span>-waarde nu positief of negatief is, maakt niet uit voor die tweedeling, het enige wat verandert, is waar het grote (groter dan <span class="math inline">\(50\)</span> procent) of het kleine (kleiner dan <span class="math inline">\(50\)</span> procent) stuk zich bevindt, dus links of rechts van die <span class="math inline">\(z\)</span>-waarde. Als de <span class="math inline">\(z\)</span>-waarde negatief is, zit het kleinere deel van de tweedeling altijd links van die z-waarde en als de <span class="math inline">\(z\)</span>-waarde positief is, zit het kleine deel juist altijd rechts van die <span class="math inline">\(z\)</span>-waarde. Slechts één waarde voor <span class="math inline">\(z\)</span> leidt tot een tweedeling waar de stukken precies gelijk zijn en dat is voor de waarde <span class="math inline">\(z=0\)</span>. Dit is het geval wanneer de gebeurtenis <span class="math inline">\(X\)</span> dus nul standaardafwijkingen opzij zit van het gemiddelde ofwel dus gelijk is aan het gemiddelde.</p></li>
</ol>
</div>
<div id="Uitwerking2.3" class="opgaven">
<section id="opgave-4" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgave-4"><em>Opgave</em> 4</h5>
<ol type="1">
<li><p>Een iPad-fabrikant vraagt zich af welk garantietermijn hij zijn klant mee moet geven. Hij onderzoekt zijn iPads en neemt aan dat de ‘levensduur’ van zijn iPads een normaalverdeling volgt met een gemiddelde van <span class="math inline">\(20000\)</span> uur en een standaardafwijking van <span class="math inline">\(2500\)</span> uur. Wat is de proportie (of kans) iPads die langer zal meegaan dan <span class="math inline">\(18500\)</span> uur?</p></li>
<li><p>Geef de proportie iPads die langer meegaan dan <span class="math inline">\(18500\)</span> uur, maar korter dan <span class="math inline">\(23000\)</span> uur.</p></li>
<li><p>Hij wil een niet-goed-nieuwe-iPad garantie geven zodanig dat hij slechts <span class="math inline">\(1.00\)</span> procent van zijn verkochte iPads hoeft te vervangen. Welk garantietermijn (levensduur in uren) moet hij op het etiket zetten zodanig dat hij maximaal <span class="math inline">\(1.00\)</span> procent van de iPods hoeft te vervangen?</p></li>
</ol>
</section>
</div>
<div id="Uitwerking4" class="uitwerkingen">
<section id="uitwerking-4" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-4"><em>Uitwerking</em> 4</h5>
<ol type="1">
<li>De variabele levensduur van een iPad is normaal verdeeld met een gemiddelde van <span class="math inline">\(20000\)</span> (uur) en een standaardafwijking van <span class="math inline">\(2500\)</span> (uur) ofwel: <span class="math display">\[X \mathtt{\sim} N(\mu_x = 20000; \sigma_x = 2500)\]</span> De vraag is hoe groot de proportie (gedeelte) is die de waarnemingen vanaf <span class="math inline">\(18500\)</span> en hoger in beslag neemt ten opzichte van alle waarnemingen. Proporties en kansen zijn eigenlijk gelijk aan elkaar. We willen dus de rechter overschrijdingskans op <span class="math inline">\(X=18500\)</span>. <span class="math inline">\(X = 18500\)</span>, <span class="math inline">\(\mu_x = 20000\)</span> en <span class="math inline">\(\sigma_x = 2500\)</span> <span class="math inline">\(z = \frac{X - \mu_{x}}{\sigma_{x}} = \frac{18500 - 20000}{2500}=(18500-20000)/2500 = \text{-}0.60\)</span> <span class="math inline">\(z=\text{-}0.67\)</span></li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking41-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking41-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.1</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking4vervolg0" class="uitwerkingen">
<ul>
<li><span class="math inline">\(P(X \geq 18500) = P(z \geq \text{-}0.60) = P(z \leq 0.60) = .7257\)</span> Dus als je een tekening maakt, vraag je dan altijd af: Is mijn <span class="math inline">\(z\)</span>-waarde positief of negatief? Heb ik de linker of rechter staart nodig? Heb ik <em>dus</em> te maken met de grote of met de kleine helft van de tweedeling. Als je tekent, zie je het ook gewoon! De proportie iPods die langer meegaat dan 18500 uur is dus <span class="math inline">\(p=.7257\)</span> (<span class="math inline">\(72.57\)</span> procent).</li>
</ul>
<ol start="2" type="1">
<li>We zijn nu geïnteresseerd in de waarden voor <span class="math inline">\(X\)</span> tussen de <span class="math inline">\(18500\)</span> en de <span class="math inline">\(23000\)</span>. Er zijn meerdere wegen naar Rome, zo ook hier naar het antwoord. Kijk eerst maar even naar de 3 normaalverdelingen hieronder.</li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking42-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking42-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/21Uitwerking42-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.2</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking4Vervolg1" class="uitwerkingen">
<ul>
<li>Bijvoorbeeld als je alleen kijkt naar verdeling <span class="math inline">\(1\)</span> en <span class="math inline">\(2\)</span>: Verdeling <span class="math inline">\(1\)</span> laat de linker overschrijdingskans zien op <span class="math inline">\(X=23000\)</span> met een waarde van <span class="math inline">\(p = .8849\)</span> (de grote groene linker staart). Verdeling <span class="math inline">\(2\)</span> laat de linker overschrijdingskans zien op <span class="math inline">\(X=18500\)</span> met een waarde van <span class="math inline">\(p = .2743\)</span> (de kleine groene linker staart). We willen de oppervlakte weten boven het interval dat loopt van <span class="math inline">\(X=18500\)</span> tot en met <span class="math inline">\(X=23000\)</span>. Je haalt dus de kleine staart van de grote staart af, wat hou je dan over? <span class="math inline">\(P(18500 \leq X \leq 23000) =  P( X \leq 23000) - P(X \leq 18500) = .8849 - .2743 = .6106\)</span> <span class="math inline">\(P(18500 \leq X \leq 23000) = .6106\)</span> Maar dit is ruw, dus: <span class="math inline">\(P(\text{–}0.60 \leq z \leq 1.20) = P(z \leq 1.20) – P(z \leq \text{–}0.60) = .8849 – .2743 = .6106\)</span> <span class="math inline">\(P(–0.60 \leq z \leq 1.20) = 0.6106\)</span> Als <span class="math inline">\(88.49\)</span> procent van de iPads korter meegaat dan <span class="math inline">\(23000\)</span> uur en <span class="math inline">\(27.43\)</span> procent korter dan <span class="math inline">\(18500\)</span> uur, dan moet het wel zijn dat <span class="math inline">\(88.49 - 27.43 = 61.06\)</span> procent van de iPads tussen de <span class="math inline">\(18500\)</span> uur en <span class="math inline">\(23000\)</span> uur meegaat. Vergelijk deze redenering met het volgende: Als <span class="math inline">\(80\)</span> procent van een groep kinderen jonger is dan <span class="math inline">\(9\)</span> jaar en <span class="math inline">\(20\)</span> procent van die groep jonger dan <span class="math inline">\(5\)</span> jaar dan moet dus <span class="math inline">\(80 - 20 = 60\)</span> procent van alle kinderen in die groep tussen de <span class="math inline">\(5\)</span> en de <span class="math inline">\(9\)</span> jaar zijn.</li>
</ul>
<ol start="3" type="1">
<li>De levensduur varieert, sommige iPads gaan korter mee dan andere. Sommige zelfs zo kort dat de klant dus een nieuwe zou willen hebben (niet-goed-nieuwe-iPod garantie). De fabrikant wil hooguit <span class="math inline">\(1\)</span> procent van zijn iPads vervangen omdat ze ‘te slecht’ waren. Als hij dus weet wat de iPad is qua hoogste levensduur van zijn <span class="math inline">\(1.00\)</span> procent slechtste iPads, kan hij dat als garantie termijn meegeven. Hij zal dan hooguit <span class="math inline">\(1\)</span> procent van zijn verkochte iPads terug krijgen en moeten vervangen. Hier is weer sprake van zo’n omgedraaide vraag zoals bij vraag 2.2d en e. Bij de gewone ‘berekeningen’ zetten we een ruwe score om naar een z-waarde om vervolgens de overschrijdingskans op te zoeken of even schematisch: <span class="math inline">\(X \rightarrow Z \rightarrow P\)</span> Dus met een gegeven <span class="math inline">\(X\)</span> uit de vraag kun je via de berekende <span class="math inline">\(z\)</span>-waarde, een <span class="math inline">\(p\)</span>-waarde opzoeken aan de hand van de <span class="math inline">\(z\)</span>-tabel. Bij <em>deze</em> vraag beginnen we met de overschrijdingskans (die is gegeven in de opgave) om die vervolgens weer terug te transformeren - omzetten - naar een ruwe score ofwel: $P Z X $ Dus met een gegeven <span class="math inline">\(p\)</span>-waarde uit de vraag, kun je via de opgezochte <span class="math inline">\(z\)</span>-waarde (aan de hand van de <span class="math inline">\(z\)</span>-tabel), een <span class="math inline">\(X\)</span>-waarde uitrekenen. De slechtste <span class="math inline">\(1\)</span> procent van de iPads bevinden zich onder de linkerstaart met een oppervlakte van <span class="math inline">\(p=.01\)</span>. Dus we zijn op zoek naar de <span class="math inline">\(X\)</span>-waarde die bij een linker staart van <span class="math inline">\(p = .01\)</span> hoort. Omdat dit staartje links zit én kleiner is dan <span class="math inline">\(50\)</span> procent, <em>moet</em> de bijbehorende <span class="math inline">\(z\)</span>-waarde dus negatief zijn. Ik heb jullie alleen een <span class="math inline">\(z\)</span>-tabel gegeven met positieve waarden, dus wij moeten eerst nog de vertaling maken:</li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking43-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.3</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking43-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.3</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking43-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.3</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking4vervolg4" class="uitwerkingen">
<ul>
<li>Dus de <span class="math inline">\(z\)</span>-waarde die wij zoeken hoort bij de tweedeling ‘<span class="math inline">\(.01\)</span> tegen <span class="math inline">\(.99\)</span>’ en is dus dezelfde <span class="math inline">\(z\)</span>-waarde die hoort bij de tweedeling ‘<span class="math inline">\(.99\)</span> tegen <span class="math inline">\(.01\)</span>’ het enige verschil is dus het minnetje! Omdat onze <span class="math inline">\(z\)</span>-tabel alleen maar linker staarten geeft die groter dan <span class="math inline">\(50\)</span> procent zijn, zoeken we dus op een linker staart met <span class="math inline">\(p =.99\)</span> Zoek dus in de <span class="math inline">\(z\)</span>-tabel naar <span class="math inline">\(p = 0.99\)</span> en kijk welke waarde voor <span class="math inline">\(z\)</span> daarbij hoort. Omdat de waarde <span class="math inline">\(0.99\)</span> er net niet precies in staat, is het het handigst om te kijken welk getalletje (<span class="math inline">\(p\)</span>-waarde) er het dichtstbij in de buurt komt. Twee getalletjes komen in aanmerking. De linker overschrijdingskans van <span class="math inline">\(0.9901\)</span> ligt net iets boven en <span class="math inline">\(0.9898\)</span> ligt net iets onder de <span class="math inline">\(0.99\)</span> (denk voor het kijk-gemak dat onze staartje een oppervakte heeft van <span class="math inline">\(0.9900\)</span>, hetzelfde dus als <span class="math inline">\(0.99\)</span>, maar dan in vier decimalen zoals de tabel ook geeft). De fabrikant wilde <em>maximaal</em> <span class="math inline">\(1.00\)</span> procent vervangen dus laten we vooral niet het grotere voor meer dan <span class="math inline">\(1.00\)</span> procent gaan, maar voor de tweedeling <span class="math inline">\(p = 0.9901\)</span> tegen <span class="math inline">\(p = 0.0099\)</span>! Lees nu af welke <span class="math inline">\(z\)</span>-waarde bij de linker overschrijdingskans van <span class="math inline">\(0.9901\)</span> en als het goed is vind je dan <span class="math inline">\(z=2.33\)</span> want: <span class="math inline">\(P(z \leq 2.33) = 0.9901\)</span> en hier volgt dus <span class="math inline">\(P(z \leq \text{-}2.33) = 0.0099\)</span> Bij een linker staartje met oppervlakte van <span class="math inline">\(p=0.0099\)</span> hoort dus een <span class="math inline">\(z\)</span>-waarde van <span class="math inline">\(\text{-}2.33\)</span>.</li>
</ul>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking43vervolg-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.3 vervolg</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking43vervolg-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.3 vervolg</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking43vervolg-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 4.3 vervolg</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking4vervolg5" class="uitwerkingen">
<ul>
<li>Dit betekent dus dat de ruwe score <span class="math inline">\(X\)</span> dus <span class="math inline">\(2.33\)</span> standaardafwijking links van het gemiddelde zit in de ruwe verdeling. Ik geef jullie twee manieren op de juiste waarde van <span class="math inline">\(X\)</span> te vinden (berekenen). Voor de eerste - en meest simpele - manier, gaan we een stukje wandelen vanuit het gemiddelde (<span class="math inline">\(\mu_x = 20000\)</span>). Niet <span class="math inline">\(1\)</span>, niet <span class="math inline">\(2\)</span>, maar <span class="math inline">\(2.33\)</span> standaardafwijkingen (denk lineaaltjes) naar links dus: <span class="math inline">\(X_{garantie} = 20000 – 2.33 \cdot 2500 = 14175\)</span> Dus het minnetje <em>omdat</em> we naar links wandelen vanuit het gemiddelde. Als we naar rechts moeten wandelen, doen we dus plus! Deze berekening kun je dus beredeneren, zie de standaardafwijking weer als een liniaaltje: je start vanuit het middelpunt van de verdeling (<span class="math inline">\(\mu_x = 20000\)</span>) en omdat je in dit geval naar links moet, doe je ‘min’ het aantal standaardafwijkingen (<span class="math inline">\(2.33\)</span>) keer de lengte van ons liniaaltje (<span class="math inline">\(\sigma_x = 2500\)</span>). Je legt het liniaaltje dus <span class="math inline">\(2.33\)</span> keer naar links vanuit het gemiddelde. Anyway, de conclusie is dus dat ongeveer <span class="math inline">\(1\)</span> procent van de iPads dus een levensduur heeft van <span class="math inline">\(14175\)</span> uur of korter. En als die dus deze waarde als garantie termijn stelt, zal de fabrikant dus maar <span class="math inline">\(1\)</span> procent van de verkochte iPads te vervangen. Het kan ook moeilijker. Dus nu tweede manier. Zodra je <span class="math inline">\(de\)</span> z-waarde weet, vul je die in in de <span class="math inline">\(z\)</span>-formule. Je vult ook de andere waarden in die je al weet en je houdt <span class="math inline">\(1\)</span> onbekende over, de waarde die we willen weten, namelijk <span class="math inline">\(X\)</span>: <span class="math inline">\(z = \frac{X - \mu_x}{\sigma_x}\)</span> De <span class="math inline">\(z\)</span>-formule, nu nog invullen, onze <span class="math inline">\(z\)</span>-waarde is negatief dus vergeet nu niet het minteken. <span class="math inline">\(\text{-}2.33 = \frac{X - 20000}{2500}\)</span> Ik pak hier even een uitgebreidere uitwerking (<em>old school</em>, de balans-methode om een vergelijking op te lossen), snellere manieren zijn ook mogelijk uiteraard, maar op deze manier komen we wat basis rekenregels tegen. Ik draai dus eerst de boel even om omdat ik de onbekende (<span class="math inline">\(X\)</span>) graag aan de linker kant van de vergelijking wil. Ik gebruik hier dus de regel (eigenschap): als ‘<span class="math inline">\(a=b\)</span>’ dan ook ‘<span class="math inline">\(b=a\)</span>’. <span class="math inline">\(\frac{X - 20000}{2500} = \text{-}2.33\)</span> Nu beide kanten vermenigvuldigen met <span class="math inline">\(2500\)</span>, zodat we de boel in ‘balance’ houden, wel zo eerlijk om met beide zijdes van de vergelijking hetzelfde te doen: <span class="math inline">\(\frac{X - 20000}{2500} \cdot 2500 = \text{-}2.33 \cdot 2500\)</span> Dit is te schrijven als: <span class="math inline">\(\frac{(X - 20000) \cdot 2500}{2500}  = \text{-}2.33 \cdot 2500\)</span> Aan de linkerkant vallen de twee ‘2500’-tjes tegen elkaar weg (<span class="math inline">\(\frac{2500}{2500}=1\)</span>): <span class="math inline">\((X - 20000) \cdot \frac{2500}{2500}  = \text{-}2.33 \cdot 2500\)</span> <span class="math inline">\((X - 20000) \cdot 1  = \text{-}2.33 \cdot 2500\)</span> <span class="math inline">\((X - 20000) = \text{-}2.33 \cdot 2500\)</span> <span class="math inline">\(X - 20000 = \text{-}2.33 \cdot 2500\)</span> Nu aan beide zijden er <span class="math inline">\(20000\)</span> bij optellen: <span class="math inline">\(X – 20000 + 20000 = \text{–}2.33 \cdot 2500 + 20000\)</span> wordt: <span class="math inline">\(X = \text{–}2.33 \cdot 2500 + 20000\)</span> of: <span class="math inline">\(X =  20000 + \text{-}2.33 \cdot 2500\)</span> of korter: <span class="math inline">\(X =  20000 - 2.33 \cdot 2500\)</span> Nu hebben we wat we bij de eerste manier zelf al hadden bedacht! dus: <span class="math inline">\(X_{garantie} = 20000 - 2.33 \cdot 2500 = 14175\)</span> De fabrikant moet zijn klant dus vertellen dat als zijn iPad sneller kapot gaat dan <span class="math inline">\(14175\)</span> uur, dat de klant dan een nieuwe kan komen halen.</li>
</ul>
</div>
<div id="Opgaven5" class="opgaven">
<section id="opgave-5" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgave-5"><em>Opgave</em> 5</h5>
<ol type="1">
<li><p>We gaan terug naar IQ-scores. We nemen weer even aan dat deze scores normaal verdeeld zijn met een gemiddelde van <span class="math inline">\(100\)</span> en een standaardafwijking van <span class="math inline">\(15\)</span>. Eigenlijk wil ik <em>straks</em> weten wat de kans is op een IQ-score van <strong>precies</strong> <span class="math inline">\(110\)</span>. Bij een dobbelsteen kunnen we kansen uitrekenen op enkele gebeurtenissen. Bijvoorbeeld: Wat is de kans dat je precies drie ogen gooit bij één worp? Bijna iedereen die vaker dan eens gedobbeld heeft, weet dat het juiste antwoord <span class="math inline">\(1/6\)</span> is. Tot nu toe hadden we het bij IQ telkens over de kans op een aantal (of interval van bepaalde) scores. De kans op een score hoger of gelijk <span class="math inline">\(X=130\)</span> bijvoorbeeld, behelst eigenlijk oneindig veel opties, want alle scores op het interval vanaf <span class="math inline">\(130\)</span> en groter, tellen mee! Dus ook een score met heel veel cijfers achter de komma zoals zoals de score <span class="math inline">\(131.300234\)</span>. We beginnen even met een klein interval voor IQ scores nog niet 1 enkele score. Wat is de kans dat iemand tussen de 109 en de 111 scoort, dus <span class="math inline">\(P(109 \leq X \leq 111)\)</span>?</p></li>
<li><p>Een dobbelsteen heeft <span class="math inline">\(6\)</span> mogelijke gebeurtenissen en de kans op precies drie ogen bij één worp is <span class="math inline">\(1/6\)</span>. Om deze waarde te berekenen kijk je dus welk deel de gewenste gebeurtenis(sen) inneemt van het aantal voor alle mogelijke gebeurtenissen en je deelt dus het <em>aantal</em> gewenste of toegestane uitkomsten (hier slecht <span class="math inline">\(1\)</span>, namelijk de uitkomst drie ogen) door het totale aantal uitkomsten (hier dus <span class="math inline">\(6\)</span>).Hoeveel mogelijke waarden zijn er bij de variabele IQ en wat is dus kans op precies <span class="math inline">\(X = 110\)</span>?</p></li>
<li><p>Grade Point Average (GPA) zijn scores die zeggen wat het gemiddelde resultaat van een student is, de scores lopen van <span class="math inline">\(0\)</span> tot en met <span class="math inline">\(4\)</span>. Voor het gemak en onze berekeneningen nemen we aan dat GPA-scores in de populatie een normaalverdeling volgt met een gemiddelde <span class="math inline">\(\mu{GPA} = 2.75\)</span> en <span class="math inline">\(\sigma{GPA} = 0.500\)</span>. Wat is de kans (dus niet percentage) dat een willekeurige student een score tussen de <span class="math inline">\(2.60\)</span> en de <span class="math inline">\(2.70\)</span>? Of ook wel: <span class="math inline">\(p(2.6 \leq GPA \leq 2.7)\)</span></p></li>
</ol>
</section>
</div>
<div id="Uitwerking5" class="uitwerkingen">
<section id="uitwerking-5" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-5"><em>Uitwerking</em> 5</h5>
<ol type="1">
<li>Zie de volgende drie plaatjes.</li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/antwoord51 -1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/antwoord51 -2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/antwoord51 -3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div id="Uitwerking5vervolg" class="uitwerkingen">
<p><span class="math display">\[P(109 \leq X \leq 111) = P(X \leq 111) – P(X \leq 109)\]</span></p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div id="Uitwerking5vervolg" class="uitwerkingen">
<p><span class="math inline">\(P(0.60 \leq z \leq 0.73) = P(z \leq 0.73) − P(z \leq 0.60) = 0.7673 − 0.7257 = 0.0416\)</span> De kans is dus <span class="math inline">\(.0416\)</span> dat iemand <span class="math inline">\(109\)</span> of hoger maar lager gelijk <span class="math inline">\(111\)</span> scoort.</p>
<ol start="2" type="1">
<li>Tot nu toe hebben we telkens de kans op een verzameling scores tussen twee waarden bekeken dus de de kans op scores behorend bij een bepaald interval. Als we de rechter overschrijdingskans op een score van bijvoorbeeld <span class="math inline">\(120\)</span> bekijken, heeft die ook een tweede waarde of grens, namelijk plus-oneindig. Het interval met de scores waarop we een kans willen berekenen, loopt dan dus van <span class="math inline">\(X=120\)</span> tot en met plus oneindig. Eigenlijk is het interval dus oneindig lang aan de rechter kant (ik geloof dat we dit ook wel een <em>open</em> interval noemen). We zullen nu de kans op één enkele waarde bekijken. Ik bekijk het op twee verschillende manieren. Bij een dobbelsteen zou je kunnen zeggen dat er in totaal zes verschillende scores mogelijk zijn. De kans op bijvoorbeeld precies ‘3 ogen’ bij één worp, bereken je door het aantal juiste mogelijkheden (in dit geval dus maar <span class="math inline">\(1\)</span>) door het totale aantal mogelijkheden (<span class="math inline">\(6\)</span>, want zes zijdes) te delen: <span class="math inline">\(P(\text{precies 3 gooien}) =\frac{\text{aantal juiste gebeurtenissen}}{\text{totaal aantal gebeurtenissen}} = \frac{1}{6} = .167\)</span> Wij zijn op zoek naar de kans dat <span class="math inline">\(X\)</span> <em>precies</em> <span class="math inline">\(110\)</span> is (dat iemand dus een IQ heeft van precies <span class="math inline">\(110\)</span> punten). Er is dus maar een ‘juiste’ gebeurtenis die bevredigt (voldoet aan onze eis), maar hoeveel gebeurtenissen zijn er in totaal? Oneindig! We krijgen dus: <span class="math inline">\(P(X = 110) =\frac{\text{aantal juiste gebeurtenissen}}{\text{totaal aantal gebeurtenissen}} = \frac{1}{\text{oneindig groot getal}} = \frac{1}{\infty} = 0\)</span> Omdat er eigenlijk oneindig veel mogelijkheden zijn, moeten we dus delen door een oneindig groot getal (<span class="math inline">\(\infty\)</span>) en als je <span class="math inline">\(1\)</span> deelt door oneindig krijg je (afgerond) <span class="math inline">\(0\)</span>. Anders gezegd is de kans dus gelijk aan <span class="math inline">\(0\)</span> dat iemand precies een score van <span class="math inline">\(110\)</span> heeft. Best vreemd toch?? Er zijn toch genoeg mensen met een IQ van <span class="math inline">\(110\)</span>? We kunnen het ook aan de hand van een normaalverdeling bekijken. Je zou kunnen zeggen dat het interval begint op <span class="math inline">\(X=110\)</span> én eindigt op <span class="math inline">\(X=110\)</span> ofwel een lengte van <span class="math inline">\(0\)</span> heeft. We zijn op zoek naar de oppervlakte boven het interval (dus de <span class="math inline">\(p\)</span>-waarde) en als je in het plaatje hieronder kijkt, zie je dat die oppervlakte eigenlijk alleen uit het verticale lijntje boven <span class="math inline">\(X=110\)</span> bestaat. En een lijntje is in de wiskunde <em>oneindig</em> dun en heeft dus ook een oppervlakte van 0! Bij een dobbelsteen (een discrete variabele) kun je dus wel een kans berekenen maar bij scores die normaal verdeeld zijn dus niet. Of beter gezegd: Het aantal ogen bij het gooien met een dobbelsteen gedraagt zich als een discrete variabele wat wil zeggen dat er slechts een <em>beperkt</em> aantal mogelijke waarde zijn en als je van één waarde naar de dichtstbij zijnde mogelijke waarde wil wandelen, moet je springen! Met een dobbelsteen kun je geen <span class="math inline">\(2.5\)</span> gooien! Maar als we berekeningen los laten op een variabele als IQ, behandelen we IQ alsof het een <em>continue</em> variabele is. Een continue variabele loopt door, <em>elke</em> waarde (op een interval) is mogelijk, ook een getal met <span class="math inline">\(20\)</span> cijfers achter de komma. Toch is het vreemd, want dit alles suggereert dat er niemand zou kunnen zijn die precies een score van <span class="math inline">\(110.000000...\)</span> heeft. In de praktijk is dit natuurlijk wel het geval. Eigenlijk zijn hier twee punten die ik wil maken. Als eerste dat de kans op één specifieke waarde voor een continue variabele, wiskundig gezien, <em>altijd</em> gelijk aan nul! <span class="math inline">\(P(X=110)=0\)</span> Als tweede, of eigenlijk leidt het eerste punt tot het volgende: Omdat deze kans precies nul is, maakt het bij overschrijdingskansen (<span class="math inline">\(p\)</span>-waarden) niet uit of de vraag gaat over ‘kleiner dan (<span class="math inline">\(&lt;\)</span>)’ of ‘kleiner gelijk aan (<span class="math inline">\(\leq\)</span>)’, dit geldt ook voor de vergrotende trap: <span class="math inline">\(P(X \leq 110) = P(z \leq 0.67) = .7486\)</span> is hetzelfde als: <span class="math inline">\(P(X &lt; 110) = P(z &lt; 0.67) = .7486\)</span> en <span class="math inline">\(P(X \geq 110) = P(z \geq 0.67) = .2514\)</span> is hetzelfde als: <span class="math inline">\(P(X &gt; 110) = P(z &gt; 0.67) = .2514\)</span> Bij berekeningen met de normaal verdeling maakt het dus niet uit of we een ‘kleiner dan’- of een ‘kleiner gelijk’ teken gebruiken. Dit geld ook voor de vraagstelling. ‘Wat is de kans dat iemand lager dan 110 scoort?’ heeft hetzelfde antwoord (<span class="math inline">\(p=0.7486\)</span>) als de vraag: ‘Wat is de kans dat iemand lager of gelijk aan <span class="math inline">\(110\)</span> scoort?’. Dit gaat dus niet op voor discrete scores (dobbelsteen), maar alleen voor variabelen waarvan we <em>aannemen</em> dat ze zich normaal (en dus ook continue) gedragen.</li>
</ol>
</div>
<div id="Opgave6" class="opgaven">
<section id="opgave-6" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgave-6"><em>Opgave</em> 6</h5>
<ol type="1">
<li><p>Grade Point Average (GPA) zin scores die zeggen wat het gemiddelde resultaat van een tudent is. de scores lopen van 0 tot en met 4. GPA volgt ind e populatie eenn ormaalverdeling met een gemiddelde van mu_GPA = 2.75 en een sigma_GPA=0.500. Wat is de kans (dus niet percentage) dat een willekeurige student een score tussen de 2.60 en de 2.70 of ook wel: <span class="math display">\[P(2.6 \leq GPA \leq 2.7 \]</span></p></li>
<li><p>Stel dat er op een onderwijsinstelling <span class="math inline">\(4500\)</span> leerlingen zitten, hoeveel van deze leerlingen hebben naar verwachting een GPA-score tussen de <span class="math inline">\(2\)</span> en <span class="math inline">\(3\)</span>?</p></li>
<li><p>Geef de GPA score van de domste leerling van de <span class="math inline">\(10\)</span> procent slimste leerlingen op deze onderwijsinstelling.</p></li>
</ol>
</section>
</div>
<div id="Uitwerking5vervolg" class="uitwerkingen">
<section id="uitwerking-2.6" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-2.6"><em>Uitwerking</em> 2.6</h5>
<ol type="1">
<li>Gegeven: <span class="math display">\[\text{GPA} \; \mathtt{\sim} \; N(\mu_{gpa} = 2.75 ; \sigma_{gpa} = 0.50)\]</span> <span class="math display">\[P(2.6 \leq GPA \leq 2.7) = P(GPA \leq 2.7) − P(GPA \leq 2.6)\]</span></li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking61-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 6.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking61-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 6.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking61-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 6.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking61-4.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 6.1</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking6vervolg0" class="uitwerkingen">
<p><span class="math display">\[P(\text{-}0.30 \leq  z \leq \text{-}0.10) = P(z \leq \text{-}0.10) − P(z \leq \text{-}0.30) = 0.4602 − 0.3821 = 0.0781\]</span> 2. <span class="math display">\[P(2 \leq GPA \leq 3) = P(GPA \leq 3) − P(GPA \leq 2) = .6915 - .0668 = 0.6247\]</span></p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/uitwerking62-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord 6.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/uitwerking62-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord 6.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/uitwerking62-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord 6.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/uitwerking62-4.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Antwoord 6.2</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking6vervolg1" class="uitwerkingen">
<ul>
<li><span class="math display">\[P(2 \leq GPA \leq 3) = P(GPA \leq 3) − P(GPA \leq 2) = .6915 - .0668 = 0.6247\]</span> <span class="math display">\[P(\text{-}1.50 \leq z \leq 0.50) = P(z \leq 0.50) − P(z \leq \text{-}1.50) = .6915 - .0668 = 0.6247\]</span> Verwachte aantal leerlingen: <span class="math inline">\(0.6247 \cdot 4500 \approx 2811\)</span></li>
</ul>
</div>
<div id="Theorie" class="definities">
<p><strong><span style="color: blue;">t-tabel</span></strong></p>
<p>Voordat we verder gaan met opgaven, geef ik jullie nog een tabel, ook wel de ‘<span class="math inline">\(t\)</span>-tabel’, zoals we nu met <span class="math inline">\(z\)</span>-waarden te maken hebben, hebben we later vanaf hoofdstuk 4, ook <span class="math inline">\(t\)</span>-waarden nodig. Het handige van deze tabel is dat er ook een paar heel precieze <span class="math inline">\(z\)</span>-waarden in staan (onderaan), die precies horen bij veel gebruikte <span class="math inline">\(p\)</span>-waarden zoals <span class="math inline">\(p = .10\)</span>, <span class="math inline">\(p = .05\)</span>, <span class="math inline">\(p = .025\)</span>, <span class="math inline">\(p = .01\)</span> en <span class="math inline">\(p = .001\)</span>. Later vertel ik meer over deze tabel (zie ook de appendix voor alle kanstabellen). Als je wilt weten met welke <span class="math inline">\(z\)</span>-waarde (ook wel de kritieke <span class="math inline">\(z\)</span>-waarde genoemd of kortweg <span class="math inline">\(z^{*}\)</span>) je te maken hebt bij een tweedeling <span class="math inline">\(p=.90\)</span> tegen <span class="math inline">\(p = .10\)</span> (of een symmetrische driedeling met een middenstuk van <span class="math inline">\(p = .80\)</span> en twee staarten van <span class="math inline">\(p = .10\)</span>), kijk je bij de kolom waar een upper tail van <span class="math inline">\(p = .10\)</span> bij hoort. Vervolgens kijk je helemaal in de onderste rij voor de bijbehorende <span class="math inline">\(z\)</span>-waarde. Als het goed is, vind je dan <span class="math inline">\(z^{*} = 1.282\)</span>. Onthoud ook maar vast de heilige <span class="math inline">\(z\)</span>-waarde die hoort bij een rechter staart van <span class="math inline">\(p = .025\)</span>, namelijk: <span class="math inline">\(Z_{heilig} = 1.960\)</span>. Nogmaals, ik kom later terug op deze tabel wanneer we hem voor <span class="math inline">\(t\)</span>-waarden nodig hebben, <em>the real thing</em>!</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/t-dist-uppertail-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>t verdeling kritieke t-waarden</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="12" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Upper tail probability $p$
</div></th>
</tr>
<tr class="even">
<th style="text-align: right;" data-quarto-table-cell-role="th">**_df_**</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.25</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.20</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.15</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.10</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.05</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.025</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.02</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.01</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">0.005</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.0025</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.001</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.0005</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">1</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.376</td>
<td style="text-align: right;">1.963</td>
<td style="text-align: right;">3.078</td>
<td style="text-align: right;">6.314</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">12.706</td>
<td style="text-align: right;">15.895</td>
<td style="text-align: right;">31.821</td>
<td style="text-align: right;">63.657</td>
<td style="text-align: right;">127.321</td>
<td style="text-align: right;">318.309</td>
<td style="text-align: right;">318.309</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">2</td>
<td style="text-align: right;">0.816</td>
<td style="text-align: right;">1.061</td>
<td style="text-align: right;">1.386</td>
<td style="text-align: right;">1.886</td>
<td style="text-align: right;">2.920</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">4.303</td>
<td style="text-align: right;">4.849</td>
<td style="text-align: right;">6.965</td>
<td style="text-align: right;">9.925</td>
<td style="text-align: right;">14.089</td>
<td style="text-align: right;">22.327</td>
<td style="text-align: right;">22.327</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">3</td>
<td style="text-align: right;">0.765</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">1.250</td>
<td style="text-align: right;">1.638</td>
<td style="text-align: right;">2.353</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">3.182</td>
<td style="text-align: right;">3.482</td>
<td style="text-align: right;">4.541</td>
<td style="text-align: right;">5.841</td>
<td style="text-align: right;">7.453</td>
<td style="text-align: right;">10.215</td>
<td style="text-align: right;">10.215</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">4</td>
<td style="text-align: right;">0.741</td>
<td style="text-align: right;">0.941</td>
<td style="text-align: right;">1.190</td>
<td style="text-align: right;">1.533</td>
<td style="text-align: right;">2.132</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.776</td>
<td style="text-align: right;">2.999</td>
<td style="text-align: right;">3.747</td>
<td style="text-align: right;">4.604</td>
<td style="text-align: right;">5.598</td>
<td style="text-align: right;">7.173</td>
<td style="text-align: right;">7.173</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">5</td>
<td style="text-align: right;">0.727</td>
<td style="text-align: right;">0.920</td>
<td style="text-align: right;">1.156</td>
<td style="text-align: right;">1.476</td>
<td style="text-align: right;">2.015</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.571</td>
<td style="text-align: right;">2.757</td>
<td style="text-align: right;">3.365</td>
<td style="text-align: right;">4.032</td>
<td style="text-align: right;">4.773</td>
<td style="text-align: right;">5.893</td>
<td style="text-align: right;">5.893</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">6</td>
<td style="text-align: right;">0.718</td>
<td style="text-align: right;">0.906</td>
<td style="text-align: right;">1.134</td>
<td style="text-align: right;">1.440</td>
<td style="text-align: right;">1.943</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.447</td>
<td style="text-align: right;">2.612</td>
<td style="text-align: right;">3.143</td>
<td style="text-align: right;">3.707</td>
<td style="text-align: right;">4.317</td>
<td style="text-align: right;">5.208</td>
<td style="text-align: right;">5.208</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">7</td>
<td style="text-align: right;">0.711</td>
<td style="text-align: right;">0.896</td>
<td style="text-align: right;">1.119</td>
<td style="text-align: right;">1.415</td>
<td style="text-align: right;">1.895</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.365</td>
<td style="text-align: right;">2.517</td>
<td style="text-align: right;">2.998</td>
<td style="text-align: right;">3.499</td>
<td style="text-align: right;">4.029</td>
<td style="text-align: right;">4.785</td>
<td style="text-align: right;">4.785</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">8</td>
<td style="text-align: right;">0.706</td>
<td style="text-align: right;">0.889</td>
<td style="text-align: right;">1.108</td>
<td style="text-align: right;">1.397</td>
<td style="text-align: right;">1.860</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.306</td>
<td style="text-align: right;">2.449</td>
<td style="text-align: right;">2.896</td>
<td style="text-align: right;">3.355</td>
<td style="text-align: right;">3.833</td>
<td style="text-align: right;">4.501</td>
<td style="text-align: right;">4.501</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">9</td>
<td style="text-align: right;">0.703</td>
<td style="text-align: right;">0.883</td>
<td style="text-align: right;">1.100</td>
<td style="text-align: right;">1.383</td>
<td style="text-align: right;">1.833</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.262</td>
<td style="text-align: right;">2.398</td>
<td style="text-align: right;">2.821</td>
<td style="text-align: right;">3.250</td>
<td style="text-align: right;">3.690</td>
<td style="text-align: right;">4.297</td>
<td style="text-align: right;">4.297</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid; background-color: rgba(237, 175, 175, 255) !important;">10</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.700</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">0.879</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">1.093</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">1.372</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">1.812</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important; background-color: rgba(237, 175, 175, 255) !important;">2.228</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">2.359</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">2.764</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">3.169</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">3.581</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">4.144</td>
<td style="text-align: right; background-color: rgba(237, 175, 175, 255) !important;">4.144</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">11</td>
<td style="text-align: right;">0.697</td>
<td style="text-align: right;">0.876</td>
<td style="text-align: right;">1.088</td>
<td style="text-align: right;">1.363</td>
<td style="text-align: right;">1.796</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.201</td>
<td style="text-align: right;">2.328</td>
<td style="text-align: right;">2.718</td>
<td style="text-align: right;">3.106</td>
<td style="text-align: right;">3.497</td>
<td style="text-align: right;">4.025</td>
<td style="text-align: right;">4.025</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">12</td>
<td style="text-align: right;">0.695</td>
<td style="text-align: right;">0.873</td>
<td style="text-align: right;">1.083</td>
<td style="text-align: right;">1.356</td>
<td style="text-align: right;">1.782</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.179</td>
<td style="text-align: right;">2.303</td>
<td style="text-align: right;">2.681</td>
<td style="text-align: right;">3.055</td>
<td style="text-align: right;">3.428</td>
<td style="text-align: right;">3.930</td>
<td style="text-align: right;">3.930</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">13</td>
<td style="text-align: right;">0.694</td>
<td style="text-align: right;">0.870</td>
<td style="text-align: right;">1.079</td>
<td style="text-align: right;">1.350</td>
<td style="text-align: right;">1.771</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.160</td>
<td style="text-align: right;">2.282</td>
<td style="text-align: right;">2.650</td>
<td style="text-align: right;">3.012</td>
<td style="text-align: right;">3.372</td>
<td style="text-align: right;">3.852</td>
<td style="text-align: right;">3.852</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">14</td>
<td style="text-align: right;">0.692</td>
<td style="text-align: right;">0.868</td>
<td style="text-align: right;">1.076</td>
<td style="text-align: right;">1.345</td>
<td style="text-align: right;">1.761</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.145</td>
<td style="text-align: right;">2.264</td>
<td style="text-align: right;">2.624</td>
<td style="text-align: right;">2.977</td>
<td style="text-align: right;">3.326</td>
<td style="text-align: right;">3.787</td>
<td style="text-align: right;">3.787</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">15</td>
<td style="text-align: right;">0.691</td>
<td style="text-align: right;">0.866</td>
<td style="text-align: right;">1.074</td>
<td style="text-align: right;">1.341</td>
<td style="text-align: right;">1.753</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.131</td>
<td style="text-align: right;">2.249</td>
<td style="text-align: right;">2.602</td>
<td style="text-align: right;">2.947</td>
<td style="text-align: right;">3.286</td>
<td style="text-align: right;">3.733</td>
<td style="text-align: right;">3.733</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">16</td>
<td style="text-align: right;">0.690</td>
<td style="text-align: right;">0.865</td>
<td style="text-align: right;">1.071</td>
<td style="text-align: right;">1.337</td>
<td style="text-align: right;">1.746</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.120</td>
<td style="text-align: right;">2.235</td>
<td style="text-align: right;">2.583</td>
<td style="text-align: right;">2.921</td>
<td style="text-align: right;">3.252</td>
<td style="text-align: right;">3.686</td>
<td style="text-align: right;">3.686</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">17</td>
<td style="text-align: right;">0.689</td>
<td style="text-align: right;">0.863</td>
<td style="text-align: right;">1.069</td>
<td style="text-align: right;">1.333</td>
<td style="text-align: right;">1.740</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.110</td>
<td style="text-align: right;">2.224</td>
<td style="text-align: right;">2.567</td>
<td style="text-align: right;">2.898</td>
<td style="text-align: right;">3.222</td>
<td style="text-align: right;">3.646</td>
<td style="text-align: right;">3.646</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">18</td>
<td style="text-align: right;">0.688</td>
<td style="text-align: right;">0.862</td>
<td style="text-align: right;">1.067</td>
<td style="text-align: right;">1.330</td>
<td style="text-align: right;">1.734</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.101</td>
<td style="text-align: right;">2.214</td>
<td style="text-align: right;">2.552</td>
<td style="text-align: right;">2.878</td>
<td style="text-align: right;">3.197</td>
<td style="text-align: right;">3.610</td>
<td style="text-align: right;">3.610</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">19</td>
<td style="text-align: right;">0.688</td>
<td style="text-align: right;">0.861</td>
<td style="text-align: right;">1.066</td>
<td style="text-align: right;">1.328</td>
<td style="text-align: right;">1.729</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.093</td>
<td style="text-align: right;">2.205</td>
<td style="text-align: right;">2.539</td>
<td style="text-align: right;">2.861</td>
<td style="text-align: right;">3.174</td>
<td style="text-align: right;">3.579</td>
<td style="text-align: right;">3.579</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">20</td>
<td style="text-align: right;">0.687</td>
<td style="text-align: right;">0.860</td>
<td style="text-align: right;">1.064</td>
<td style="text-align: right;">1.325</td>
<td style="text-align: right;">1.725</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.086</td>
<td style="text-align: right;">2.197</td>
<td style="text-align: right;">2.528</td>
<td style="text-align: right;">2.845</td>
<td style="text-align: right;">3.153</td>
<td style="text-align: right;">3.552</td>
<td style="text-align: right;">3.552</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">21</td>
<td style="text-align: right;">0.686</td>
<td style="text-align: right;">0.859</td>
<td style="text-align: right;">1.063</td>
<td style="text-align: right;">1.323</td>
<td style="text-align: right;">1.721</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.080</td>
<td style="text-align: right;">2.189</td>
<td style="text-align: right;">2.518</td>
<td style="text-align: right;">2.831</td>
<td style="text-align: right;">3.135</td>
<td style="text-align: right;">3.527</td>
<td style="text-align: right;">3.527</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">22</td>
<td style="text-align: right;">0.686</td>
<td style="text-align: right;">0.858</td>
<td style="text-align: right;">1.061</td>
<td style="text-align: right;">1.321</td>
<td style="text-align: right;">1.717</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.074</td>
<td style="text-align: right;">2.183</td>
<td style="text-align: right;">2.508</td>
<td style="text-align: right;">2.819</td>
<td style="text-align: right;">3.119</td>
<td style="text-align: right;">3.505</td>
<td style="text-align: right;">3.505</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">23</td>
<td style="text-align: right;">0.685</td>
<td style="text-align: right;">0.858</td>
<td style="text-align: right;">1.060</td>
<td style="text-align: right;">1.319</td>
<td style="text-align: right;">1.714</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.069</td>
<td style="text-align: right;">2.177</td>
<td style="text-align: right;">2.500</td>
<td style="text-align: right;">2.807</td>
<td style="text-align: right;">3.104</td>
<td style="text-align: right;">3.485</td>
<td style="text-align: right;">3.485</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">24</td>
<td style="text-align: right;">0.685</td>
<td style="text-align: right;">0.857</td>
<td style="text-align: right;">1.059</td>
<td style="text-align: right;">1.318</td>
<td style="text-align: right;">1.711</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.064</td>
<td style="text-align: right;">2.172</td>
<td style="text-align: right;">2.492</td>
<td style="text-align: right;">2.797</td>
<td style="text-align: right;">3.091</td>
<td style="text-align: right;">3.467</td>
<td style="text-align: right;">3.467</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">25</td>
<td style="text-align: right;">0.684</td>
<td style="text-align: right;">0.856</td>
<td style="text-align: right;">1.058</td>
<td style="text-align: right;">1.316</td>
<td style="text-align: right;">1.708</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.060</td>
<td style="text-align: right;">2.167</td>
<td style="text-align: right;">2.485</td>
<td style="text-align: right;">2.787</td>
<td style="text-align: right;">3.078</td>
<td style="text-align: right;">3.450</td>
<td style="text-align: right;">3.450</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">26</td>
<td style="text-align: right;">0.684</td>
<td style="text-align: right;">0.856</td>
<td style="text-align: right;">1.058</td>
<td style="text-align: right;">1.315</td>
<td style="text-align: right;">1.706</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.056</td>
<td style="text-align: right;">2.162</td>
<td style="text-align: right;">2.479</td>
<td style="text-align: right;">2.779</td>
<td style="text-align: right;">3.067</td>
<td style="text-align: right;">3.435</td>
<td style="text-align: right;">3.435</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">27</td>
<td style="text-align: right;">0.684</td>
<td style="text-align: right;">0.855</td>
<td style="text-align: right;">1.057</td>
<td style="text-align: right;">1.314</td>
<td style="text-align: right;">1.703</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.052</td>
<td style="text-align: right;">2.158</td>
<td style="text-align: right;">2.473</td>
<td style="text-align: right;">2.771</td>
<td style="text-align: right;">3.057</td>
<td style="text-align: right;">3.421</td>
<td style="text-align: right;">3.421</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">28</td>
<td style="text-align: right;">0.683</td>
<td style="text-align: right;">0.855</td>
<td style="text-align: right;">1.056</td>
<td style="text-align: right;">1.313</td>
<td style="text-align: right;">1.701</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.048</td>
<td style="text-align: right;">2.154</td>
<td style="text-align: right;">2.467</td>
<td style="text-align: right;">2.763</td>
<td style="text-align: right;">3.047</td>
<td style="text-align: right;">3.408</td>
<td style="text-align: right;">3.408</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">29</td>
<td style="text-align: right;">0.683</td>
<td style="text-align: right;">0.854</td>
<td style="text-align: right;">1.055</td>
<td style="text-align: right;">1.311</td>
<td style="text-align: right;">1.699</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.045</td>
<td style="text-align: right;">2.150</td>
<td style="text-align: right;">2.462</td>
<td style="text-align: right;">2.756</td>
<td style="text-align: right;">3.038</td>
<td style="text-align: right;">3.396</td>
<td style="text-align: right;">3.396</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">30</td>
<td style="text-align: right;">0.683</td>
<td style="text-align: right;">0.854</td>
<td style="text-align: right;">1.055</td>
<td style="text-align: right;">1.310</td>
<td style="text-align: right;">1.697</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.042</td>
<td style="text-align: right;">2.147</td>
<td style="text-align: right;">2.457</td>
<td style="text-align: right;">2.750</td>
<td style="text-align: right;">3.030</td>
<td style="text-align: right;">3.385</td>
<td style="text-align: right;">3.385</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">40</td>
<td style="text-align: right;">0.681</td>
<td style="text-align: right;">0.851</td>
<td style="text-align: right;">1.050</td>
<td style="text-align: right;">1.303</td>
<td style="text-align: right;">1.684</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.021</td>
<td style="text-align: right;">2.123</td>
<td style="text-align: right;">2.423</td>
<td style="text-align: right;">2.704</td>
<td style="text-align: right;">2.971</td>
<td style="text-align: right;">3.307</td>
<td style="text-align: right;">3.307</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">50</td>
<td style="text-align: right;">0.679</td>
<td style="text-align: right;">0.849</td>
<td style="text-align: right;">1.047</td>
<td style="text-align: right;">1.299</td>
<td style="text-align: right;">1.676</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.009</td>
<td style="text-align: right;">2.109</td>
<td style="text-align: right;">2.403</td>
<td style="text-align: right;">2.678</td>
<td style="text-align: right;">2.937</td>
<td style="text-align: right;">3.261</td>
<td style="text-align: right;">3.261</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">60</td>
<td style="text-align: right;">0.679</td>
<td style="text-align: right;">0.848</td>
<td style="text-align: right;">1.045</td>
<td style="text-align: right;">1.296</td>
<td style="text-align: right;">1.671</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">2.000</td>
<td style="text-align: right;">2.099</td>
<td style="text-align: right;">2.390</td>
<td style="text-align: right;">2.660</td>
<td style="text-align: right;">2.915</td>
<td style="text-align: right;">3.232</td>
<td style="text-align: right;">3.232</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">80</td>
<td style="text-align: right;">0.678</td>
<td style="text-align: right;">0.846</td>
<td style="text-align: right;">1.043</td>
<td style="text-align: right;">1.292</td>
<td style="text-align: right;">1.664</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">1.990</td>
<td style="text-align: right;">2.088</td>
<td style="text-align: right;">2.374</td>
<td style="text-align: right;">2.639</td>
<td style="text-align: right;">2.887</td>
<td style="text-align: right;">3.195</td>
<td style="text-align: right;">3.195</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">100</td>
<td style="text-align: right;">0.677</td>
<td style="text-align: right;">0.845</td>
<td style="text-align: right;">1.042</td>
<td style="text-align: right;">1.290</td>
<td style="text-align: right;">1.660</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">1.984</td>
<td style="text-align: right;">2.081</td>
<td style="text-align: right;">2.364</td>
<td style="text-align: right;">2.626</td>
<td style="text-align: right;">2.871</td>
<td style="text-align: right;">3.174</td>
<td style="text-align: right;">3.174</td>
</tr>
<tr class="even">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">1000</td>
<td style="text-align: right;">0.675</td>
<td style="text-align: right;">0.842</td>
<td style="text-align: right;">1.037</td>
<td style="text-align: right;">1.282</td>
<td style="text-align: right;">1.646</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">1.962</td>
<td style="text-align: right;">2.056</td>
<td style="text-align: right;">2.330</td>
<td style="text-align: right;">2.581</td>
<td style="text-align: right;">2.813</td>
<td style="text-align: right;">3.098</td>
<td style="text-align: right;">3.098</td>
</tr>
<tr class="odd">
<td style="text-align: right; font-weight: bold; border-right: 1px solid;">$z^{*}$</td>
<td style="text-align: right;">0.674</td>
<td style="text-align: right;">0.842</td>
<td style="text-align: right;">1.036</td>
<td style="text-align: right;">1.282</td>
<td style="text-align: right;">1.645</td>
<td style="text-align: right; background-color: rgba(150, 184, 242, 255) !important;">1.960</td>
<td style="text-align: right;">2.054</td>
<td style="text-align: right;">2.326</td>
<td style="text-align: right;">2.576</td>
<td style="text-align: right;">2.807</td>
<td style="text-align: right;">3.090</td>
<td style="text-align: right;">3.291</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="Uitwerking6vervolg2" class="uitwerkingen">
<ol start="3" type="1">
<li>Hier wordt dus weer een kans (percentage) gegeven en om een ruwe gebeurtenis gevraagd. Dus van <span class="math inline">\(p\)</span> via <span class="math inline">\(z\)</span> terug naar <span class="math inline">\(x\)</span>.</li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div id="Uitwerking6vervolg2" class="uitwerkingen">
<p>We zijn dus op zoek naar de waarde voor <span class="math inline">\(x\)</span> zodanig dat precies <span class="math inline">\(10\)</span> procent van alle <span class="math inline">\(X\)</span>-waarden daarboven valt. De <em>upper tail</em> of rechterstaart moet dus een oppervlakte hebben van <span class="math inline">\(p = .10\)</span> <span class="math inline">\(P(X \geq x) = 0.10\)</span> Hier hebben we geen tabel voor, dus doen we het eerst met <span class="math inline">\(z\)</span>: <span class="math inline">\(P(Z \geq z) = 0.10\)</span> Opzoeken in de <span class="math inline">\(z\)</span> of <span class="math inline">\(t\)</span>-tabel geeft: <span class="math inline">\(z^{*} = 1.282\)</span> Dit betekent dus dat de waarde voor <span class="math inline">\(X\)</span> dus precies <span class="math inline">\(1.282\)</span> standaardafwijkingen (denk lineaaltjes) vanaf het gemiddelde naar rechts ligt, dus lekker wandelen vanuit het gemiddelde: <span class="math inline">\(X = 2.75 + 1.282 \cdot 0.5 = 3.391\)</span></p>
</div>
<div id="Opgave7" class="opgaven">
<section id="opgaven-7" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgaven-7"><em>Opgaven</em> 7</h5>
<ol type="1">
<li><p>Van een universiteit in Nederland is bekend dat voor het eerste statistiek tentamen gemiddeld een <span class="math inline">\(6.7\)</span> wordt behaald. Aangenomen mag worden dat de scores normaal verdeeld zijn met een standaardafwijking van <span class="math inline">\(1.4\)</span>. Jaarlijks doen <span class="math inline">\(950\)</span> studenten het tentamen. Hoeveel studenten zullen naar verwachting een score hebben tussen de <span class="math inline">\(5\)</span> en een <span class="math inline">\(7\)</span>?</p></li>
<li><p>Een score van <span class="math inline">\(5.5\)</span> of hoger, betekent een voldoende (Leiden Universiteit, hoe bedoel je ‘zessen’ cultuur? Gelukkig doen ze in Leiden ook genoeg aan plagiaat en data-setjes opleuken), hoeveel procent van de studenten slaagt niet voor het tentamen en halen dus een onvoldoende?</p></li>
<li><p>Hoeveel punten zou de universiteit de studenten kado moeten geven zodanig dat slechts <span class="math inline">\(5\)</span> procent zou zakken? Hint: Tekenen en bedenk wat het nieuwe gemiddelde zou moeten zijn zodanig dat slechts vijf procent lager scoort dan 5.5. De standaardafwijking voor het tentamencijfer blijft constant en vraag jezelf af (zoek op) hoeveel standaardafwijkingen de score <span class="math inline">\(5.5\)</span> van het gemiddelde af moet liggen.</p></li>
</ol>
</section>
</div>
<div id="Uitwerking7" class="uitwerkingen">
<section id="uitwerking-7" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-7"><em>Uitwerking</em> 7</h5>
<ol type="1">
<li>Gegeven: <span class="math inline">\(X \mathtt{\sim} N(\mu_x = 6.7 ; \sigma_x = 1.4)\)</span>. Gevraagd: Hoeveel studenten zullen naar verwachting tussen een <span class="math inline">\(5\)</span> en een <span class="math inline">\(7\)</span> scoren. Dus eerste de proportie of kans vinden en dan kunnen we het aantal studenten uitrekenen.</li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking71-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking71-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking71-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.1</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking71-4.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.1</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking7vervolg0" class="uitwerkingen">
<ul>
<li><span class="math display">\[P(5 \leq X \leq 7) = P(X \leq 7) − P(X \leq 5)\]</span> <span class="math display">\[P(\text{-}1.21 \leq Z \leq 0.21) = P(z \leq 0.21) − P(z ≤ \text{−}1.21) = .5832−.1131 = .4701\]</span> Dus de kans (of proportie) is dus 0.4701 dat iemand een cijfer tussen de <span class="math inline">\(5\)</span> en <span class="math inline">\(7\)</span> zal halen, maar er werd om een aantal mensen gevraagd, dus de proportie vermigvuldigen met het totale aantal studenten: <span class="math inline">\(.4701 \cdot 950 = 446.6\)</span> studenten (eigenlijk naar beneden afronden anders zouden er mensen bijzitten die lager dan een 5 of hoger dan een 7 scoren). Besef trouwens dat ik de berekende <span class="math inline">\(z\)</span>-waarden heb afgerond en dat dus de opgezochte en gebruikte kansen dus iets afwijken (om precies te zijn zouden we op <span class="math inline">\(448.8927\)</span> personen moeten uitkomen die tussen de <span class="math inline">\(5\)</span> en een <span class="math inline">\(7\)</span> scoren, heb ik zo via andere wegen berekend).</li>
</ul>
<ol start="2" type="1">
<li>Gevraagd: <span class="math inline">\(P(X &lt; 5.5)\)</span>, Dus de kans (in percentage) dat iemand <em>lager</em> dan een <span class="math inline">\(5.5\)</span> voor zijn tentamen haalt.</li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking72-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking72-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.2</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking72-3.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.2</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking7vervolg1" class="uitwerkingen">
<ul>
<li><span class="math inline">\(P(X &lt; 5.5) = P(X \leq 5.5) = P(z \leq \text{−} 0.86) = 0.1949\)</span> Vervolgens ndeze kans nog keer <span class="math inline">\(100\)</span> procent doen om het percentage te vinden: <span class="math inline">\(.1949 \cdot 100\% = 19.49\%\)</span> Dus <span class="math inline">\(19.5\%\)</span> van de leerlingen haalt een onvoldoende.</li>
</ul>
<ol start="3" type="1">
<li>Als we scores veranderen (transformeren) dan veranderen ook sommige statistieken mee (zie ook opgave 1.5). Nu is het gemiddelde voor het tentamen <span class="math inline">\(6.7\)</span> en als iedereen bijvoorbeeld een halve punt erbij zou krijgen, zou het gemmidelde ook toenemen met een halve punt (<span class="math inline">\(\mu_{nieuw}= 6.7 + 0.5 = 7.2\)</span>), de standaardafwijking veranderd niet in dit geval (<span class="math inline">\(\sigma_x\)</span> verandert alleen als de scores worden getransformeerd met een vermenigvuldiging). Je zou voor dit specifieke voorbeeld (<span class="math inline">\(\mu_{nieuw} = 7.2\)</span>) kunnen kijken (uitrekenen) hoeveel procent van de studenten dan een voldoende haalt en of dat meer dan 95 procent is zoals Leiden Universiteit dat graag wil (of minder dan 5 procent die het niet haalt). Laten we het maar even snel doen meteen, voor het gevoel. Dus even uitgaande van dit specifieke voorbeeld waarbij <span class="math inline">\(X \mathtt{\sim} N(\mu_x = 7.2 ; \sigma_x = 1.4)\)</span> en de vraag <span class="math inline">\(P(X &lt; 5.5)\)</span>: <span class="math display">\[z = \frac{X-\mu_x}{\sigma_x} = \frac{5.5-7.2}{1.4} = \text{-}1.21\]</span> <span class="math display">\[P(X &lt; 5.5) = P(z &lt; \text{-}1.21) = 1 - P(z &gt; 1.21) =  0.1131\]</span> Dus met dit nieuwe gemiddelde (<span class="math inline">\(\mu_x = 7.2\)</span>) zou ongeveer <span class="math inline">\(11\)</span> procent van de studenten een onvpldoende halen, en dat is te veel! het mocht maximaal <span class="math inline">\(5\)</span> procent zijn! We zouden natuurlijk het nog een paar keer kunnen proberen en zo bij het correcte nieuwe gemiddelde uitkomen, door <em>trial and error</em> dus tot het goede antwoord komen. We gaan het natuurlijk systematischer aanpakken. Als iedereen in een populatie (of steekproef) <span class="math inline">\(\mu_{nieuw]\)</span> of het nieuwe gemiddelde is dus – nu nog – onbekend, maar op (of bij) de score <span class="math inline">\(X=5.5\)</span> moet de tweedeling voor <span class="math inline">\(5\)</span> en <span class="math inline">\(95\)</span> procent vallen. Van alle mogelijke scores zou slechts <span class="math inline">\(5\)</span> procent links van <span class="math inline">\(5.5\)</span> moeten vallen en <span class="math inline">\(95\)</span> procent van de studenten zou dan boven de <span class="math inline">\(5.5\)</span> moeten scoren. Verder weten we eigenlijk nog weinig behalve dat de boel normaal verdeeld is met een standaardafwijking van <span class="math inline">\(1.40\)</span> en dus dat de score <span class="math inline">\(X = 5.5\)</span> precies op de tweedeling moet vallen, dus <em>so far</em>: <span class="math display">\[X \mathtt{\sim} N(\mu_{nieuw} = ? ; \sigma_x = 1.4)$ én $P(X &lt; 5.5) = .05\]</span>:</li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking73-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.3</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking73-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 7.3</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking7vervolg1" class="uitwerkingen">
<ul>
<li>Omdat we de tweedeling weten qua kansen, kunnen we <em>dus</em> ook een <span class="math inline">\(z\)</span>-waarde opzoeken. Voor de tweedeling <span class="math inline">\(p = .05\)</span> tegen <span class="math inline">\(p = .95\)</span> vind je, op basis van de <span class="math inline">\(t\)</span>-tabel, een bijbehorende <span class="math inline">\(z\)</span>-waarde van <span class="math inline">\(1.645\)</span> (met de <span class="math inline">\(z\)</span>-tabel moet je weer wat afronden en kom je op <span class="math inline">\(z=1.64\)</span> of <span class="math inline">\(z=1.65\)</span> uit, ook goed). Wij hebben dus met <span class="math inline">\(\text{-}1.645\)</span> te maken omdat we links van het midden zitten. Anders gezegd: vanuit het – nu nog – onbekende gemiddelde zouden we <span class="math inline">\(1.645\)</span> standaardafwijking naar <em>links</em> moeten wandelen om op de juiste score uit te komen (<span class="math inline">\(X=5.5\)</span>). Of omgedraaid: We moeten vanuit die <span class="math inline">\(X=5.5\)</span> precies <span class="math inline">\(1.645\)</span> standaardafwijkingen naar <em>rechts</em> wandelen om bij het <em>nieuwe</em> of onbekende gemiddelde uit te komen. Laten we dat maar meteen doen: <span class="math display">\[\mu_{nieuw} = 5.5 + 1.645 \cdot 1.4 = 7.803\]</span> of met de <span class="math inline">\(z\)</span>-formule kan het natuurlijk ook, je neemt dan wel een hele lange weg: <span class="math display">\[z = \frac{X - \mu_x}{\sigma_x}\]</span> nu nog invullen, onze <span class="math inline">\(z\)</span>-waarde is negatief dus vergeet niet het minteken. <span class="math display">\[\text{-}1.645 = \frac{5.5 - \mu_{nieuw}}{1.4}\]</span> <span class="math display">\[\frac{5.5 - \mu_{nieuw}}{1.4} = \text{-}1.645\]</span> Nu beide kanten vermenigvuldigen met <span class="math inline">\(1.4\)</span>, <span class="math inline">\(\frac{5.5 - \mu_{nieuw}}{1.4} \cdot 1.4 = \text{-}1.645 \cdot 1.4\)</span> Dit is te schrijven als: <span class="math inline">\(\frac{(5.5 - \mu_{nieuw}) \cdot 1.4}{1.4}  = \text{-}1.645 \cdot 1.4\)</span> Aan de linkerkant vallen de twee ‘1.4’-tjes tegen elkaar weg, ik doe nog even de extra tussenstapjes: <span class="math inline">\((5.5 - \mu_{nieuw}) \cdot \frac{1.4}{1.4}  = \text{-}1.645 \cdot 1.4\)</span> <span class="math inline">\((5.5 - \mu_{nieuw}) \cdot 1  = \text{-}1.645 \cdot 1.4\)</span> <span class="math inline">\((5.5 - \mu_{nieuw}) =  \text{-}1.645 \cdot 1.4\)</span> <span class="math inline">\(5.5 - \mu_{nieuw} =  \text{-}1.645 \cdot 1.4\)</span> Nu aan beide zijden er <span class="math inline">\(5.5\)</span> van aftrekken: <span class="math inline">\(5.5 - \mu_{nieuw} -5.5 =  \text{-}1.645 \cdot 1.4 - 5.5\)</span> wordt: <span class="math inline">\(\text{-}\mu_{nieuw} = \text{-}7.803\)</span> beide zijden vermenigvuldigen met <span class="math inline">\(\text{-}1\)</span>: <span class="math inline">\(\text{-}\mu_{nieuw} \cdot \text{-}1 = \text{-}7.803 \cdot \text{-}1\)</span> <span class="math inline">\(\mu_{nieuw} = 7.803\)</span> (hèhè, tjemig de pemig zeg, wat een weg) Dus als het nieuwe gemiddelde voor het tentamencijfer <span class="math inline">\(\mu_{nieuw} = 7.8\)</span> zou zijn en de standaardafwijking gewoon nog steeds <span class="math inline">\(\sigma_x = 1.40\)</span>, dan zou slechts <span class="math inline">\(5\)</span> procent van de studenten een onvoldoende halen (<span class="math inline">\(X &lt; 5.5\)</span>).Gezien het oude gemiddelde <span class="math inline">\(6.7\)</span> was, moet dus iedereen er <em>minimaal</em> <span class="math inline">\(1.1\)</span> tentamenpunt (<span class="math inline">\(7.8 - 6.7 = 1.1\)</span>) bovenop hun tentamencijfer krijgen zodanig dat <em>maximaal</em> <span class="math inline">\(5\)</span> procent een onvoldoende haalt en dus <em>minimaal</em> <span class="math inline">\(95\)</span> procent een voldoende. In deze berekening heb ik trouwens geen rekening gehouden met wat de keuze qua afronden betreft. Wij kwamen uit op <span class="math inline">\(\mu_{nieuw} = 7.803\)</span> (en dus niet <span class="math inline">\(\mu_{nieuw} = 7.8\)</span>) dus bij een stijging van <span class="math inline">\(1.100\)</span> in plaats van <span class="math inline">\(1.103\)</span> zou dus eigenlijk <em>net</em> iets <em>minder</em> dan <span class="math inline">\(95\)</span> procent slagen en dat was eigenlijk niet de bedoeling. In het voordeel van Leiden Universteit (en hun accreditatie) kunnen ze dus de boel beter met bijvoorbeeld <span class="math inline">\(1.2\)</span> tentamenpunt ophogen!</li>
</ul>
</div>
<div id="Opgaven8" class="opgaven">
<section id="opgaven-8" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="opgaven-8"><em>Opgaven</em> 8</h5>
<ol type="1">
<li><p>Toen ik vijf jaar samen was met mijn zogenaamde levenspartner zei ze toen al dat ze genoeg van me had. Maar hoe serieus moest ik haar toen nemen? Toen, onder mijn vrienden wist ik dat ongeveer <span class="math inline">\(20\)</span> procent het niet langer dan <span class="math inline">\(3\)</span> jaar uit hield met hun relatie. Gelukkig was <span class="math inline">\(30\)</span> procent van mijn vrienden hoopgevend en duurde bij hun een relatie langer dan <span class="math inline">\(9\)</span> jaar. Ook bleek dat de duur van een relatie een normaalverdeling volgt. Uiteraard waren mijn vrienden niet van invloed op mijn of haar keuzes en gedraagt (gedroeg) elke relatie zich onafhankelijk, dus voor elke relatie betekent dit: Nieuwe ronde, nieuwe relatie, nieuwe kansen. Wat zou de gemiddelde duur van een relatie zijn als <span class="math inline">\(20\)</span> procent van de mensen het korter uithoudt dan <span class="math inline">\(3\)</span> jaar en <span class="math inline">\(20\)</span> procent het juist langer dan <span class="math inline">\(9\)</span> jaar uithoudt (dus de twee staarten zijn <em>nu</em> dus nog even groot, beide <span class="math inline">\(p = .20\)</span>, en mag je dus nog even in symmetrie denken)?</p></li>
<li><p>We hebben te maken met twee overschrijdingskansen die niet gelijk zijn. Het gemiddelde zal dus ook niet in het midden van 3 en 9 jaar liggen. Bij welke grenswaarde ligt het gemiddelde dichterbij en welke grenswaarde is dus het minst extreem?</p></li>
<li><p>Bereken de verwachte duur van mijn relatie ofwel de gemiddelde duur van een relatie en de standaardafwijking voor de variabele ‘duur van een relatie’. Ga hier dus uit van de eerder gegeven overschrijdingskansen, de genoemde <span class="math inline">\(20\)</span> en <span class="math inline">\(30\)</span> procent.</p></li>
</ol>
</section>
</div>
<div id="Uitwerking8" class="uitwerkingen">
<section id="uitwerking-2.8" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="uitwerking-2.8"><em>Uitwerking</em> 2.8</h5>
<ol type="1">
<li>Omdat beide staarten van de normaal verdeling even groot zijn, beide hebben een oppervlakte van <span class="math inline">\(0.20\)</span>, moet het gemiddelde wel precies in het midden liggen als het om een normaal verdeelde variabele gaat. Of anders gezegd: omdat beide staarten, behorend bij <span class="math inline">\(X=3\)</span> en <span class="math inline">\(X=9\)</span>, zijn de twee gebeurtenissen <em>even</em> extreem (vanuit het gemiddelde gezien), dus liggen even ver van het midden in de verdeling. Het midden van <span class="math inline">\(3\)</span> en <span class="math inline">\(9\)</span> (de twee grenswaarden van de staarten, waarop de overschrijdingskans gegeven is) is ook wel het gemiddelde (of het midden) van die twee, dus tot zover gegeven: <span class="math inline">\(X \mathtt{\sim} N(\mu_{x} = ? ; \sigma_x = ?)\)</span> en <span class="math inline">\(P(X \leq 3) = P(X \geq 9)= .20\)</span> Met deze informatie kunnen we vast een schets maken van wat we tot zover weten:</li>
</ol>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking81-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 8.1</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking8vervolg0" class="uitwerkingen">
<ul>
<li>Omdat <span class="math inline">\(\mu_x\)</span> dus in het midden moet liggen krijgen we: <span class="math inline">\(\mu_x = \frac{X_a + X_b}{2} = \frac{3 + 9}{2} = 6\)</span> jaar. Dus de gemiddelde duur van een relatie zou in dit geval dus <span class="math inline">\(\mu_{\text{levensduur relatie}} = 6\)</span> jaar zijn.</li>
</ul>
<ol start="2" type="1">
<li>Omdat er een grotere overschrijdingskans is op <span class="math inline">\(9\)</span> jaar, betekent dat deze waarde makkelijker te overschrijden valt (vanuit het gemiddelde gezien) en dus minder extreem is dan de gebeurtenis <span class="math inline">\(X = 3\)</span>. Dit betekent dat het gemiddelde dichter bij <span class="math inline">\(X=9\)</span> zal liggen dan en dat 9 dus minder extreem is. In het algemeen: Hoe verder een score verwijderd ligt van het gemiddelde, des te extremer is deze score en zal deze score moeilijker te ‘bereiken’ zijn en heeft daarom een kleinere overschrijdingskans en dus een kleinere (kortere) staart heeft. Ik zeg altijd maar zo: Einstein heeft de <em>kleinste</em> staart, omdat hij het hoogste - en dus et meest extreme - IQ heeft! Laten we de boel even schetsen bij de volgende gegevens: <span class="math inline">\(X \mathtt{\sim} N(\mu_{x} = ? ; \sigma_x = ?)\)</span>, <span class="math inline">\(P(X \leq 3) = .20\)</span> en <span class="math inline">\(P(X \geq 9)= .30\)</span></li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/Uitwerking82-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Uitwerking 8.2</figcaption>
</figure>
</div>
</div>
</div>
<div id="Uitwerking8vervolg0" class="uitwerkingen">
<ul>
<li>Je ziet dat <span class="math inline">\(\mu_x\)</span> dus dichter bij <span class="math inline">\(X=9\)</span> ligt dan bij <span class="math inline">\(X=6\)</span> en kunnen we dus zeggen dat vanuit het gemiddelde gezien <span class="math inline">\(X=9\)</span> het minst extreem is.</li>
</ul>
<ol start="3" type="1">
<li>Eigenlijk is dit een van de allermoeilijkste vragen, met een aantal stapjes die we zullen moeten nemen om het antwoord te vinden. Ook hier zijn meerdere manieren om dit probleem op te lossen. We zullen het zoveel mogelijk visueel proberen op te lossen. Nog steeds geldt: <span class="math inline">\(X \mathtt{\sim} N(\mu_{x} = ? ; \sigma_x = ?)\)</span>, <span class="math inline">\(P(X \leq 3) = .20\)</span> en <span class="math inline">\(P(X \geq 9)= .30\)</span>, zie dus ook de normaal verdeling bij vorige opgave (2.8b) We hebben dus alleen twee ruwe <span class="math inline">\(X\)</span>-waarden, met hun bijbehorende overschrijdingskansen. Via de <span class="math inline">\(z\)</span>-verdeling vinden we de oplossing. Omdat we de overschrijdingskansen weten, kunnen we dus ook <span class="math inline">\(z\)</span>-waarden opzoeken (ik gebruik hier de <span class="math inline">\(z\)</span>-tabel en rond even beetje af:</li>
</ol>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-de-normaal-verdeling_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div id="Uitwerking8vervolg0" class="uitwerkingen">
<ul>
<li><p>We beginnnen met de waarde van <span class="math inline">\(\sigma_x\)</span>. We weten nu, aan de hand van de gevonden <span class="math inline">\(z\)</span>-waarden, <em>hoeveel</em> (het aantal) standaardafwijkingen de twee ruwe gebeurtenissen van het gemiddelde verwijderd liggen: Bij <span class="math inline">\(X=3\)</span> hoort <span class="math inline">\(z=\text{-}0.84\)</span> en wil dus zeggen dat de gebeurtenis <span class="math inline">\(X=3\)</span> precies <span class="math inline">\(0.84\)</span> standaardafwijking <em>links</em> van het gemiddelde (midden) zit (dus bijna <span class="math inline">\(1\)</span> standaardafwijking ervandaan dus). Bij <span class="math inline">\(X=9\)</span> hoort <span class="math inline">\(z=0.52\)</span> en wil dus zeggen dat de gebeurtenis <span class="math inline">\(X=3\)</span> precies <span class="math inline">\(0.52\)</span> standaardafwijking <em>rechts</em> van het gemiddelde zit (dus ruim een halve standaardafwijking). We weten nog niet <em>hoe groot</em> de standaardafwijking is, maar we kunnen nu wel bedenken <em>hoeveel</em> standaardafwijkingen je moet ‘wandelen’ om van <span class="math inline">\(X=3\)</span>, via <span class="math inline">\(\mu_x\)</span>, naar <span class="math inline">\(X=9\)</span> te komen. Het eerste stukje was <span class="math inline">\(0.84\)</span> keer <span class="math inline">\(\sigma_x\)</span> en voor het tweede stukje is het <span class="math inline">\(0.52\)</span> keer <span class="math inline">\(\sigma_x\)</span>. Dus in totaal is dat:</p></li>
<li><p>$0.84 _x + 0.52 _x = 1.36 _x $ of in termen van de afstand tussen <span class="math inline">\(z_a\)</span> en <span class="math inline">\(z_b\)</span>:</p></li>
<li><p><span class="math inline">\(z_b - z_a = 0.52 - \text{-}0.84 = 0.52 + 0.84 = 1.36\)</span></p></li>
<li><p>Dit wil dus zeggen dat - om van <span class="math inline">\(X=3\)</span> naar <span class="math inline">\(X=9\)</span> te wandelen - je <span class="math inline">\(1.36\)</span> standaardafwijking moet wandelen. Maar hoeveel moet je ‘ruw’ wandelen om van <span class="math inline">\(X=3\)</span> naar <span class="math inline">\(X=9\)</span> te wandelen? <span class="math inline">\(6\)</span> ruwe punten of jaren dus (<span class="math inline">\(X_b - X_a = 9-3 = 6\)</span>). We kunnen nu dus zeggen dat die ‘gestandaardiseerde’ wandeling (<span class="math inline">\(1.36 \cdot \sigma_x\)</span>) en de ruwe wandeling (<span class="math inline">\(6\)</span> jaar) aan elkaar gelijk moeten zijn. dus hieruit volgt een vergelijking met één onbekende (<span class="math inline">\(\sigma_x\)</span>):</p></li>
</ul>
<p><span class="math inline">\(1.36 \cdot \sigma_x = 6\)</span> even oplossen door beide kanten door <span class="math inline">\(1.36\)</span> te delen: <span class="math inline">\(\frac{1.36 \cdot \sigma_x}{1.36} = \frac{6}{1.36}\)</span> <span class="math inline">\(\frac{1.36}{1.36} \cdot \sigma_x = 4.4118\)</span> <span class="math inline">\(1 \cdot \sigma_x = 4.4118\)</span> <span class="math inline">\(\sigma_x = 4.4118\)</span> ons eerste antwoord, de standaardafwijking voor deze verdeling! Nu nog het gemiddelde vinden. Nu hebben we twee opties, we gaan vanuit <span class="math inline">\(X=3\)</span> of <span class="math inline">\(X=9\)</span> naar het gemiddelde wandelen, ik wandel liever naar rechts en start dus vanuit <span class="math inline">\(X=3\)</span>. Vanuit <span class="math inline">\(X=3\)</span> moet je <span class="math inline">\(0.84\)</span> keer de standaardafwijking wandelen om bij <span class="math inline">\(\mu_x\)</span> te komen, <em>let’s do that</em>: <span class="math inline">\(\mu_x = 3 + 0.84 \cdot \sigma_x = 3 + 0.84 \cdot 4.4118 = 6.705912\)</span> <span class="math inline">\(\mu_x = 6.71\)</span> Blijkbaar duurt een gemiddelde relatie onder mijn vrienden <span class="math inline">\(6.71\)</span> jaar (en had ik naar verwachting nog <span class="math inline">\(1.71\)</span> jaar te gaan). De meer wiskundige oplossing, had natuurlijk ook gekund, maar slaat totaal de plank mis! Ik wil dat je schetst, kijkt en vervolgens schat wat mogelijk antwoorden zouden kunnen zijn.</p>
<ul>
<li>Klaar!</li>
</ul>
</div>
</section>
<div id="Theorie" class="definities">
<section id="wat-is-normaal" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="wat-is-normaal">Wat is Normaal?</h2>
<p>Zo zie je maar dat een schets of tekening en even denken vaak de voorkeur verdient voor het oplossen van een probleem, het geeft je zelfs al van te voren een idee van wat de uitkomst ongeveer zou moeten of kunnen zijn. Bij de strikt wiskundige (algebraïsche) oplossing sluipen en er snel foutjes in en is het vaak heel onduidelijk waar we nu eigenlijk mee bezig zijn. Ben je een überNerd, dan maakt het natuurlijk geen reet uit. Ik ben geen überNerd, hooguit wat slim en lui. Bij mij is dus altijd Regel <span class="math inline">\(1\)</span>: “<em>Don’t get caught</em> (Dexter, the Serial Killer) en <em>teken</em> je dus eerst even de situatie uit”. Natuurlijk wil je Inzicht in de probleemstelling en boeit het antwoord <em>alleen</em> als je er geld mee kunt verdienen of er mensen mee kunt manipuleren (helpen enzo), op school nog even niet dus, daar gaat het om het leer-effect en eigenlijk niet om de output (toetsen) en de cijfers. Ik had lage cijfers op school, ik vond school zwaar debiel en onnodig, gewoon robot werk dus. Ik deed dus ook vrij weinig en zorgde dus wel voor het nodige Inzicht, zodat ik de boel kon berederen tijdens mijn proefwerken. Natuurlijk is tekenen niet altijd makkelijk en zeker niet voor een blinde, maar die heeft misschien weer een beter geheugen en voorstellingsvermogen. Kun jij zeven dingen tegelijk in je hoofdje houden en de verbanden zien? ik niet, maar ik kan het wel tekenen! Een schets is natuurlijk meer dan voldoende en niets meer dan Normaal!</p>
</section>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-descriptive-statistics.html" class="pagination-link" aria-label="Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, _Descriptive Statistics_.">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, <em>Descriptive Statistics</em>.</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-samenhang.html" class="pagination-link" aria-label="Hoofdstuk 3  - Samenhang tussen 2 variabelen, correlatie.">
        <span class="nav-page-text"><span class="chapter-title">Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>