<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie. – Handleiding Statistiek met JASP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="libs/quarto-nav/quarto-nav.js"></script>
<script src="libs/quarto-nav/headroom.min.js"></script>
<script src="libs/clipboard/clipboard.min.js"></script>
<script src="libs/quarto-search/autocomplete.umd.js"></script>
<script src="libs/quarto-search/fuse.min.js"></script>
<script src="libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-van-steekproef-naar-populatie.html" rel="next">
<link href="./02-de-normaal-verdeling.html" rel="prev">
<script src="libs/quarto-html/quarto.js" type="module"></script>
<script src="libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="libs/quarto-html/popper.min.js"></script>
<script src="libs/quarto-html/tippy.umd.min.js"></script>
<script src="libs/quarto-html/anchor.min.js"></script>
<link href="libs/quarto-html/tippy.css" rel="stylesheet">
<link href="libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="libs/bootstrap/bootstrap.min.js"></script>
<link href="libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-samenhang.html"><span class="chapter-title">Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Handleiding Statistiek met JASP</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Voorwoord</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-descriptive-statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, <em>Descriptive Statistics</em>.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-de-normaal-verdeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 2 - De Normaalverdeling.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-samenhang.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-van-steekproef-naar-populatie.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 4 - Van Steekproef naar Populatie. Generalisatie van Statistieken naar Parameters aan de hand van Betrouwbaarheidsintervallen en Significantie-toetsen.</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-enkelvoudige-lineaire-regressie.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hoofdstuk 5 - Enkelvoudige Lineaire Regressie-Analyse.</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Bijlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#correlatie" id="toc-correlatie" class="nav-link active" data-scroll-target="#correlatie">Correlatie</a></li>
  <li><a href="#verband-in-woorden" id="toc-verband-in-woorden" class="nav-link" data-scroll-target="#verband-in-woorden">Verband in woorden</a></li>
  <li><a href="#predictor-criterium-respons" id="toc-predictor-criterium-respons" class="nav-link" data-scroll-target="#predictor-criterium-respons">Predictor, criterium, respons</a></li>
  <li><a href="#het-verband-grafisch-weergeven." id="toc-het-verband-grafisch-weergeven." class="nav-link" data-scroll-target="#het-verband-grafisch-weergeven.">Het verband grafisch weergeven.</a></li>
  <li><a href="#covariantie-en-pearson-correlatie" id="toc-covariantie-en-pearson-correlatie" class="nav-link" data-scroll-target="#covariantie-en-pearson-correlatie">Covariantie en Pearson Correlatie</a>
  <ul>
  <li><a href="#covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen" id="toc-covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen" class="nav-link" data-scroll-target="#covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen">Covariantie als ongestandaardiseerde maat voor het verband tussen twee variabelen</a></li>
  <li><a href="#correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen." id="toc-correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen." class="nav-link" data-scroll-target="#correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen.">Correlatiecoëfficiënt, de Pearson Correlatie als gestandaardiseerde maat voor het verband tussen twee variabelen.</a></li>
  <li><a href="#andere-manieren-om-de-pearson-correlatie-uit-te-rekenen." id="toc-andere-manieren-om-de-pearson-correlatie-uit-te-rekenen." class="nav-link" data-scroll-target="#andere-manieren-om-de-pearson-correlatie-uit-te-rekenen.">Andere manieren om de Pearson Correlatie uit te rekenen.</a></li>
  </ul></li>
  <li><a href="#lekker-belangrijk" id="toc-lekker-belangrijk" class="nav-link" data-scroll-target="#lekker-belangrijk">Lekker Belangrijk</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Tot zo ver hebben we in hoofdstuk <span class="math inline">\(0\)</span>, <span class="math inline">\(1\)</span> en <span class="math inline">\(2\)</span> telkens naar één variabele gekeken (en die dus beschreven aan de hand van een aantal statistieken zoals het gemiddelde en de standaardafwĳking). In dit hoofdstuk gaan we een stap verder en kĳken we naar het <em>verband</em> tussen twee variabelen. Denk bĳvoorbeeld aan het verband tussen motivatie en prestatie, mensen die minder gemotiveerd zĳn (dus onder-gemiddeld op motivatie scoren) zullen hoogstwaarschĳnlĳk ook minder presteren (onder-gemiddeld presteren). En mensen die hoog gemotiveerd zĳn, zullen waarschĳnlĳk ook vaker hoger dan gemiddeld presteren. Hier zĳn het dus de twee variabelen motivatie en prestatie die een samenhang (verband) vertonen. Natuurlĳk zĳn er uitzonderingen op deze uitspraken, zoals die luie (ongemotiveerde) nerd die toch hoog presteert vanwege zĳn hoge intelligentie, maar bĳ algemene verwachtingen laat je natuurlĳk - die extreem rare of bĳzondere gevallen, even buiten beschouwing.</p>
<section id="correlatie" class="level2">
<h2 class="anchored" data-anchor-id="correlatie">Correlatie</h2>
<p><strong><span style="color: blue;">correlatie, covariatie, covariantie, associatie, samenhang, afhankelĳkheid of relatie (tussen twee variabelen) </span></strong></p>
<p>Bovenstaande begrippen betekenen allemaal hetzelfde. Het draait natuurlĳk allemaal om het voorspellen of verklaren van verschillen (variatie) of waarden, dus natuurlĳk ook bĳ het begrip ‘verband’. Het enige verschil is dat we nu bĳ een voorspelling qua waarde voor de ene variabele, rekening houden met een waarde op een andere variabele. Omdat die twee waarden dus ‘iets met elkaar te maken hebben’ of dus ‘samen’ ‘hangen’. Als je weet dat iemand een man (waarde op de ene variabele, geslacht) is, zal die wel wat langer (waarde op de andere variabele) qua lengte zĳn. Dus de voorspelling (of beste gok) qua lengte - als je weet dat iemand een man is - zal hoger (anders) zĳn, dan als je weet dat die persoon een vrouw is.Vrouwen zĳn over het algemeen (meestal) kleiner. Als we (op grond van de waarden van de ene variabele) alleen maar juiste (dus zonder fouten) voorspellingen doen voor de andere variabele, zeggen we ook wel dat het verband perfect is. Maar als het dus totaal geen zin heeft om (waarden van -) de ene variabele te gebruiken om de andere te voorspellen, zeggen we dat er geen verband is tussen die twee variabelen.</p>
<ul>
<li><p>Sommige zaken zĳn nou eenmaal perfect aan elkaar gerelateerd, bĳvoorbeeld wanneer je temperatuur in graden Celsius omrekent naar temperatuur gemeten in Kelvin)</p></li>
<li><p>Sommige zaken zĳn gedeeltelĳk aan elkaar gerelateerd, bĳvoorbeeld de lengte van een persoon en zĳn gewicht, lange mensen zĳn over het algemeen zwaarder maar er zĳn genoeg uitzonderingen.</p></li>
<li><p>sommige zaken zĳn in zĳn geheel niet aan elkaar gerelateerd, zoals de lengte van je schoenveter en de mate waarin je van oliebollen houdt. Laten we eerst maar even kĳken hoe het bĳ onze aapjes zit, voordat we verder gaan.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Aapjes Data</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respondentnummer
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Lengte
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Leeftijd
</div></th>
</tr>
<tr class="even">
<th style="text-align: center;" data-quarto-table-cell-role="th">$i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Y_i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$X_i$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">2.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>De meest basale gok qua lengte (als één van onze aapjes binnen zou komen wandelen) zou het gemiddelde van de variabele <span class="math inline">\(Y\)</span> zĳn (ook wel het nul-model of intercept-model genoemd), het gemiddelde van alle aapjes in onze steekproef wordt ook wel het ‘grote gemiddelde’ genoemd. Hier dus <span class="math inline">\(\overline{Y} = 150\)</span>. Maar stel nou dat ik je extra informatie zou geven over de leeftĳd (<span class="math inline">\(X_i\)</span>) van een aapje dat binnenkomt. Ik vertel je bĳvoorbeeld dat het aapje - voordat hĳ binnenkomt - een leeftĳd heeft van <span class="math inline">\(2\)</span> jaar. Je mag nog steeds naar alle gegevens kĳken die je in de tabel ziet staan. Zou je dan nog steeds zeggen dat de beste gok <span class="math inline">\(150\)</span> is? Ik hoop het niet, want als je kĳkt naar de drie aapjes die <span class="math inline">\(2\)</span> jaar oud zĳn, zie je dat die allemaal langer zĳn dan 150 cm (namelĳk 160, 170 en 180 cm). Anders gezegd: Het gemiddelde voor <span class="math inline">\(Y\)</span> voor alléén de aapjes die de waarde 2 voor de variabele <span class="math inline">\(X\)</span> hebben, is 170 cm. Ik hoop dat je dus <span class="math inline">\(170\)</span> zou gokken als je weet dat een aapje dat binnenkomt, <span class="math inline">\(2\)</span> jaar oud is. Als je zou weten dat een aapje <span class="math inline">\(1\)</span> jaar is, zou <span class="math inline">\(130\)</span> de beste gok of verwachting zĳn en als een aapje <span class="math inline">\(1.5\)</span> jaar is, dan zou je je voorspelling niet aanpassen en gewoon nog steeds <span class="math inline">\(150\)</span> cm zeggen.</p>
<p>Het gokspelletje nog een keer, maar nu ook met de ‘nieuwe’ gokfouten (residuen):</p>
<ul>
<li><p>Als je dus niet weet dat ‘toevallig’ aapje nummer <span class="math inline">\(9\)</span> gaat binnen komen lopen én je zou ook niet weten welke leeftĳd dat aapje heeft, zou je dus <span class="math inline">\(150\)</span> cm als beste gok geven. Als dan aapje nummer <span class="math inline">\(9\)</span> binnenkomt lopen, heb je dus een gokfout van <span class="math inline">\(30\)</span> cm gemaakt.</p></li>
<li><p>Als je dus niet weet dat ‘toevallig’ aapje nummer <span class="math inline">\(9\)</span> binnenkomt lopen, maar je weet wel dat het aapje dat binnenkomt <span class="math inline">\(2\)</span> jaar oud is, zou je dus <span class="math inline">\(170\)</span> cm als beste gok geven. Aangezien aapje nummer <span class="math inline">\(9\)</span> weer ‘toevallig’ binnen komt lopen, heb je nu dus maar een gokfout van 10 cm gemaakt. Hĳ (<span class="math inline">\(Y_9 = 180\)</span>) zit namelĳk <span class="math inline">\(10\)</span> cm boven je nieuwe – of specifiekere – verwachting (<span class="math inline">\(170\)</span> cm). Ik zeg hier ‘specifieker’ omdat het gemiddelde van <span class="math inline">\(170\)</span> alleen voor de laatste drie aapjes geldt en dat is specifieker (of minder algemeen) dan het gemiddelde van alle negen aapjes. De score van aapje nummer negen zelf (<span class="math inline">\(Y_9 = 180\)</span>) is weer een specifiekere waarde dan het gemiddelde voor de drie aapjes van 2 jaar (<span class="math inline">\(170\)</span>). De nieuwe afwĳking of gokfout (tussen de score voor aapje nummer <span class="math inline">\(9\)</span> en de gemiddelde lengte voor de drie aapjes van <span class="math inline">\(2.0\)</span> jaar oud) is positief omdat de observatie (<span class="math inline">\(Y_9 = 180\)</span>) rechts van dat laatste gemiddelde (<span class="math inline">\(170\)</span>) zit. Besef dat je met je specifiekere model (een verwachting of voorspelling voor de lengte op basis van leeftĳd) in het geval van aapje nummer <span class="math inline">\(9\)</span> dus nog maar een gokfout maakt van <span class="math inline">\(10\)</span> cm en niet meer van <span class="math inline">\(30\)</span> cm. Het specifiekere model voorspelt bĳ dit aapje dus <em>beter</em> dan het algemenere model. Zou dat voor ieder aapje gelden? Als het specifiekere model – gemiddeld gezien – beter voorspelt dan het grote gemiddelde, kan je dus zeggen dat het specifiekere model de scores voor <span class="math inline">\(Y_i\)</span> beter (terug) voorspelt of verklaart (omdat de gemiddelde gok-fout kleiner wordt).</p></li>
</ul>
</section>
<section id="verband-in-woorden" class="level2">
<h2 class="anchored" data-anchor-id="verband-in-woorden">Verband in woorden</h2>
<p>Samenhang of verband heel algemeen: Als jou voorspelling (hier voor lengte) afhangt van de waarde op een andere variabele (hier leeftĳd) dan zegt men dus dat er sprake is van samenhang tussen de twee variabelen. We zeggen dan ook wel dat de twee variabelen afhankelĳk van elkaar zĳn, omdat de informatie over het één (informatie qua leeftĳd) iets zegt over de mogelĳke informatie van het andere (lengte). Simpel gezegd:</p>
<ul>
<li>Naar mate een aapje ouder is, zal die ook wel wat langer zĳn. Maar ook:</li>
<li>Hoe jonger een aapje is, des te kleiner zal die waarschĳnlĳk zĳn. En:</li>
<li>Als een aapje gemiddeld is qua leeftĳd? Dan zal die, qua voorspelling voor zijn lengte, ook gemiddeld zĳn. Gemiddeld op het één betekent vaak ook gemiddeld op het andere (als variabelen dus samenhangen).</li>
</ul>
<p>Hoe sterker het verband is, des te zekerder je bent van deze drie uitspraken (en je dus minder uitzonderingen zal tegenkomen zoals een oud ‘lilliputter’ aapje of een heel jonge ‘king kong’ aap).</p>
<p><strong><span style="color: blue;">Verband tussen twee variabelen is niet hetzelfde als een oorzaak/gevolg relatie tussen die variabelen.</span></strong></p>
<p>We weten allemaal dat jonge aapjes langer worden naarmate ze ouder worden. Maar zou je deze uitspraak ook kunnen omdraaien? Dus: Naarmate aapjes langer worden zullen ze ook ouder worden. Ja dat kan! Technisch of statistisch gezien is dit precies hetzelfde, maar op de een of andere manier klinkt dit in onze taal toch niet zo lekker, maar het is dus wel goed! Die laatste uitspraak ‘klinkt’ minder fĳn, omdat wĳ als mensen (naïevelingen dus) - op de een of andere manier - leeftĳd als een soort <em>oorzaak</em> (begin, basis of reden) zien van lengte en dat de leeftijd van een aapje echt zijn lengte beinvloedt. Maar laten we wel wezen: Natuurlĳk is lengte niet echt het gevolg van leeftĳd. Leeftĳd veroorzaakt geen verandering in lengte. Leeftĳd beïnvloedt lengte niet. Niemand groeit vanwege de tĳd, je groeit hooguit met de (leef-) tĳd, de twee variabelen veranderen, of gaan samen. De echte redenen (oorzaken of factoren) dat mens en dier groeit, zĳn natuurlĳk zaken zoals voedsel, genen, zuurstof en een beetje liefde misschien! Echte oorzaak/gevolg relaties (causale relaties) tussen variabelen zĳn heel moeilĳk te bewĳzen, mocht je dat toch willen doen, zul je een heus experiment moeten doen, en dus de mogelĳke ‘oorzaak’ van groeien, zoals voedsel, weg moeten nemen (Natuurlĳk stoppen aapjes met groeien als je ze geen eten geeft!) Denk dan dus ook echt aan een laboratorium gevoel met experimentele en controle condities. Overigens is er een tal van grote denkers (waaronder de kleine ik) die zelfs zover gaan dat ze stellen dat causale relaties überhaupt niet bestaan. Causatie is dan ook meer een onderwerp voor de filosofie. Als je een opera zangeres heel hard en hoog laat gillen naast een wĳnglas dan veroorzaakt het harde en hoge geluid dat het wĳnglas breekt. Maar als je tegelĳkertĳd een hamer op het wĳnglas slaat, dan is het dus onduidelĳk wie de veroorzaker was van het kapotte glas. Misschien een beetje flauw en gelukkig hoef je hier natuurlĳk niet echt over na te denken, maar onthoud voorlopig wel dat causale uitspraken (het één veroorzaakt of beïnvloedt het ander, zoals de ballen op een biljarttafel, binnen de statistiek eigenlijk veel te voorbarig zĳn en dus meestal ongegrond (onbewezen) zĳn. Maar we maken dus vaak wel - voor het gemak - een keuze over welke variabele wĳ als oorzaak <em>willen</em> zien (die noemen we dan de X variabele, of heel verwarrend: de onafhankelijke variabele) en welke variabele we als gevolg willen zien (de Y variabele, of wederom verwarrend: de afhankelijke). In deze handleiding gaan we heel veel modelletjes (machientje of voorspel-formule) bouwen. Je stopt er iets in (de <em>input</em>, de X-variabele, dus de onafhankelijke variabele, Independent Variable, IV), en het produkt dat het machientje maakt, dus wat eruit komt noemen we de (voorspelling van) de afhankelijke variabele (uitkomst, criterium of Dependent Variable, DV)</p>
<p><strong><span style="color: blue;">Correlatie is dus niet hetzelfde als causatie, maar causatie behelst of omvat wel correlatie.</span></strong></p>
<p>Dus als twee variabelen een samenhang vertonen (gecorreleerd zĳn), is dat nog niet hetzelfde als een <em>causaal</em> verband tussen de twee variabelen (dat zou dus verder onderzocht moeten worden aan de hand van een experiment). Maar als (je weet dat) twee variabelen een causale (oorzaak/gevolg) relatie hebben met elkaar, dan zĳn deze twee variabelen - sowieso - gecorreleerd met elkaar. Het bestaan van een correlatie tussen twee variabelen is dus een noodzakelĳke voorwaarde voor causatie, maar het is nog niet genoeg voor causatie, correlatie is dus geen voldoende voorwaarde voor causatie. Dus puur een correlatie tussen twee variabelen is nog niet voldoende bewĳs dat die twee variabelen ook echt causaal aan elkaar gerelateerd zĳn.</p>
<p>Extreem voorbeeld: Als er op een dag (object, case) veel ĳsjes worden gegeten (waarde op de variabele ĳs-eten) dan weten we ook dat er op diezelfde dag ook meer mensen zullen verdrinken (waarde op aantal verdrinkingen die dag). De naïeveling (Geert Wilders) zou roepen dat ĳs eten dus de oorzaak is van het aantal verdrinkingen. Maar natuurlĳk is er geen causale relatie tussen de hoeveelheid gegeten ĳs en het aantal verdrinkingen op een dag. De waarden die de twee variabelen aannemen noemen we ook wel een <em>common response</em>, een gelĳk of algemeen antwoord op iets anders, een derde variabele. Het is alleen het zonnetje (gebrek aan wolken) of de temperatuur waarvan mensen trek krĳgen in ĳs en natuurlĳk zin hebben om te gaan zwemmen (en dus misschien wel verdrinken). Het is dus het zonnetje dat het (gerelateerde) gedrag van beide variabele (of van de corresponderende waarden op beide variabelen) (beter) verklaart.</p>
</section>
<section id="predictor-criterium-respons" class="level2">
<h2 class="anchored" data-anchor-id="predictor-criterium-respons">Predictor, criterium, respons</h2>
<p>Omdat ík uiteindelĳk (in hoofdstuk 5) vooral geïnteresseerd ben in de verklaring van de variatie (verschillen) in lengte aan de hand van, of op basis van, leeftĳd, heb ik dus voor leeftĳd de variabele <span class="math inline">\(X\)</span> genomen en voor lengte, de variabele <span class="math inline">\(Y\)</span>. In hoofdstuk <span class="math inline">\(5\)</span> gaan we een ‘regressiemodel’ bouwen om aan de hand van de variabele <span class="math inline">\(X\)</span> de variatie in variabele <span class="math inline">\(Y\)</span> te voorspellen (verklaren) en ik heb er dus voor <em>gekozen</em> om leeftĳd dus als ‘oorzakelĳk’ te <em>zien</em> (maar het is dus niet echt de ‘oorzaak’) en lengte als gevolg (is dus niet echt het gevolg). Als ik het hier over oorzaak en gevolg heb, bedoel ik dus alleen de keuze qua richting van voorspelling: van X naar Y, van vraag naar antwoord, van <em>input</em> naar <em>output</em>. Een ‘oorzakelĳke variabele’ wordt ook wel de onafhankelĳke variabele of predictor (voorspeller) genoemd. Voor de ‘gevolg variabele’ kiezen we dus vaak <span class="math inline">\(Y\)</span> als naampje, maar deze ‘gevolg’ variabele wordt ook wel, de afhankelĳke variabele, het criterium (bereik), uitkomst of respons (antwoord) variabele genoemd. Nogmaals: bĳ het begrip verband boeit de richting van voorspelling dus totaal niet en is de voorspel-richting (of volgorde qua benoeming van variabelen) puur een kwestie van wat je leuk vindt of wat handig is voor een vlot lopend (en dus gezellig) verhaal of probleemstelling.</p>
</section>
<section id="het-verband-grafisch-weergeven." class="level2">
<h2 class="anchored" data-anchor-id="het-verband-grafisch-weergeven.">Het verband grafisch weergeven.</h2>
<p>Om zaken zoals plaatjes en figuren te interpreteren en uit te leggen, denk ik vaak aan een blinde persoon. Dan kan je dus niet een plaatje voor zichzelf laten spreken en leuk met je vingertje wĳzen. Hoe zou je een blinde moeten uitleggen wat jĳ ziet? Wat ik hier eigenlĳk mee wil zeggen, is dat als twee mensen naar hetzelfde figuur kĳken, wil dat nog niet zeggen dat ze ook daadwerkelĳk hetzelfde zien (of de zelfde informatie eruit halen). Ik zal niet elk detail benoemen van de figuur, maar doe wel een kleine of grove poging. Kijk eerst zelf maar even naar het de het spreidingsdiagram hieronder:</p>
<!-- figuur 3A -->
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-samenhang_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Als je een mogelĳke samenhang tussen twee variabelen grafisch wilt weergeven of bekĳken, kunnen we dat dus doen aan de hand van een grafiek. Omdat we slechts kĳken naar het verband tussen twee variabelen hebben we maar twee assen nodig, een horizontale en een verticale as, ook wel de X (leeftĳd) en de Y (lengte) as. De variabele leeftĳd had als laagst voorkomende waarde 1 jaar en als hoogste waarde 2 jaar. Voor lengte was het minimum 120 cm en het maximum 180 cm. We hoeven dus ook niet oneindig lange assen te tekenen, alleen die (lĳn) stukken die onze waarden dekken. In een standaard assen-stelsel vind je altĳd de waarden 0 voor X en 0 voor Y waar de assen elkaar snĳden of kruisen (met een hoek van 90 graden). Hier heb ik dus gesmokkeld omdat de telling niet bĳ nul begint voor beide variabelen of assen. Omdat je per case (aapje) twee datapunten hebt (een waarde op leeftĳd en een waarde op lengte), kun je die twee scores (ook wel coördinaten) tegen elkaar uitzetten. Die puntjes in zo’n grafiek zetten of tekenen, noemen we ook wel ‘plotten’. Elk punt in het figuur is dus opgebouwd uit twee waarden, een <span class="math inline">\(X\)</span>-waarde en een <span class="math inline">\(Y\)</span>-waarde (ook wel de twee componenten of coördinaten van een punt). De plek of positie van één (of ieder) punt is dus te definiëren door slechts twee coördinaten, de X en de Y coördinaten. De <span class="math inline">\(X\)</span>-waarde van één punt vertelt ons hoe ‘links’ of ‘rechts’ het punt ligt (horizontale richting) en de <span class="math inline">\(Y\)</span>-waarde van dat zelfde punt, vertelt ons hoe ‘hoog’ of hoe ‘laag’ (verticale richting) dat zelfde puntje zich bevindt. Even moeilĳk gezegd, maar probeer het toch te begrĳpen, als je van een willekeurig punt wil weten wat zĳn X-waarde is projecteer je dat punt op de X-as (je laat hem verticaal omlaag vallen) en kĳk je waar dat punt terecht komt op de X-as. Zo ook voor de <span class="math inline">\(Y\)</span>-waarde van een punt: door het punt op de Y-as te projecteren (door het punt horizontaal naar links of naar rechts te duwen, tot dat het puntje op de Y-as ligt), zie je dus de Y-waarde van het punt.</p>
</section>
<section id="covariantie-en-pearson-correlatie" class="level2">
<h2 class="anchored" data-anchor-id="covariantie-en-pearson-correlatie">Covariantie en Pearson Correlatie</h2>
<p>Als je naar de hele puntenwolk kĳkt, zie je dat de wolk omhoog loopt, of beter: de ligging of het ‘verloop’ van de wolk is vanaf linksonder in de grafiek en gaat dan rechtlĳnig schuin omhoog naar rechtsboven in de grafiek. Als een wolk rechtlĳnig omhoog - of omlaag - kruipt (en dus juist niet een horizontale ligging heeft), spreken we van een lineair (rechtlĳnig) verband. De maat voor een rechtlĳnig of lineair verband noemen we ook wel de Pearson correlatie. Deze maat (statistiek of parameter) is officieel alleen bedoeld voor het verband tussen twee variabelen die minimaal een interval meetniveau hebben (of je moet tenminste aannemen dat de variabelen op intervalniveau behandeld kunnen worden). Voorlopig kĳken wĳ alleen naar rechtlĳnige verbanden en laten we de kromlĳnige verbanden (als een puntenwolk bĳvoorbeeld een hema-worst vorm heeft) even buiten beschouwing. De sterkte van het verband hangt van twee dingen af: enerzĳds de steilheid van de wolk, en anderzĳds de dikte of breedte van de wolk. Hoe steiler (omhoog of omlaag) de wolk loopt, des te sterker zal het verband zĳn. Als de wolk dunner of smaller wordt (de wolk gaat steeds meer op een rechte lĳn lĳken), wordt het verband ook sterker. Des te sterker het verband des te meer zal de waarde (getal) van het verband van 0 afwĳken. Om het lineaire verband tussen twee (interval) variabelen te beschrĳven gebruiken we twee maten, een ruwe maat de covariantie genoemd (<span class="math inline">\(S_{xy}\)</span> of <span class="math inline">\(cov(xy)\)</span> ) en een gestandaardiseerde maat: de Pearson correlatie die als statistiek de letter ‘<span class="math inline">\(r\)</span>’ krijgt. Dus voor de variabelen <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> noemen we hem <span class="math inline">\(r_{xy}\)</span>.</p>
<p>Omdat een verband tussen twee variabelen positief (de puntenwolk kruipt omhoog) of negatief (de wolk kruipt omlaag) kan zijn, willen we vaak weten hoeveel cases bĳdragen aan <em>geen</em>, een <em>positief</em> of een <em>negatief</em> verband. Hiervoor heb ik het volgende plaatje gemaakt. Je kan dit dus grafisch maar ook numeriek (qua getallen) bekĳken. Eerst grafisch:</p>
<!-- figuur 3B -->
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-samenhang_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>Je ziet nu dat ik door het middelpunt (centrum) van de wolk een horizontale en een verticale lĳn heb getrokken. Dat middelpunt is altĳd bĳ het (denkbeeldig) punt (<span class="math inline">\(\overline{X}\)</span>, <span class="math inline">\(\overline{Y}\)</span>), bĳ ons dus het punt (<span class="math inline">\(1.5\)</span>, <span class="math inline">\(150\)</span>). Bĳ ons is er toevallig een aapje die voldoet aan die waarden en is het dus ook toevallig een echt punt in onze wolk, maar dat hoeft dus niet. Ik heb dus het plaatje in vieren gedeeld, ook wel in vier kwadranten. De drie punten in het kwadrant linksonder hebben alledrie gemeen dat ze onder-gemiddeld op X zĳn (allemaal 1 jaar) en onder-gemiddeld op Y zĳn (120, 130 en 140 cm). Je zou kunnen zeggen dat deze drie cases op beide variabelen in de <em>zelfde</em> richting scoren (laag, laag). En omdat deze drie aapjes op beide variabelen in de <em>zelfde</em> richting afwijken of ‘bewegen’ (co-variëren) zeggen we ook wel dat ze alledrie bĳdragen aan een <em>positief</em> verband. Zo ook voor de drie aapjes in het kwadrant rechtsboven. Op beide variabelen scoren de drie aapjes boven gemiddeld, dus de combinatie ‘hoog, hoog’. Omdat ook deze drie op de twee variabelen dus in de <em>zelfde</em> richting bewegen, zeggen we natuurlĳk hier ook dat ze bĳdragen aan een positief verband. Dus tot zover hebben we zes aapjes die bĳdragen aan een positief verband. Omdat we geen aapjes in het kwadrant linksboven of rechtsonder vinden, draagt er geen één aapje bĳ aan een negatief verband. Een punt in het kwadrant linksboven zou beteken dat iemand - op de twee variabelen - juist in tegengestelde richting beweegt, laag op <span class="math inline">\(X\)</span> en hoog op <span class="math inline">\(Y\)</span>. In het kwadrant rechtsonder, zou je juist ‘hoog op <span class="math inline">\(X\)</span> en laag op <span class="math inline">\(Y\)</span> combinaties’ tegenkomen, ook tegengesteld qua richting, dus ook een bĳdrage aan een negatief verband. De punten van de middelste drie aapjes liggen allemaal op de verticale lĳn (dus hun <span class="math inline">\(X\)</span> waarde is precies gelĳk aan het gemiddelde). Eén ervan (nummer 5) is zelfs ook gemiddeld op <span class="math inline">\(Y\)</span>, omdat ie ook op de horizontale lĳn ligt. Omdat er dus geen sprake is van variatie (afwijking, beweging) op beide variabelen tegelĳk (geen sprake van co-variatie dus), dragen deze drie apen dus ook niet bĳ aan een positief, dan wel negatief verband. Genoeg geouwehoerd, aan de slag met een berekening, we beginnen met de ruwe samenhangsmaat, de ‘covariantie’ voor <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span>, ook wel <span class="math inline">\(S_{xy}\)</span> of <span class="math inline">\(cov(xy)\)</span>.</p>
<section id="covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen" class="level3">
<h3 class="anchored" data-anchor-id="covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen">Covariantie als ongestandaardiseerde maat voor het verband tussen twee variabelen</h3>
<p><span class="math display">\[S_{xy} = cov(xy) =  \frac{1}{n-1} \cdot \sum\limits^{i=n}_{i=1}{(X_i-\overline{X})(Y_i-\overline{Y})}\]</span></p>
<p>Berekening van de covariantie (<span class="math inline">\(S_{xy}\)</span>) in woorden:</p>
<ul>
<li><p>Eerste voor iedere case de afwĳkingen (t.o.v. het gemiddelde) op <span class="math inline">\(X\)</span> en op <span class="math inline">\(Y\)</span> uitrekenen. Dus <span class="math inline">\(X_i-\overline{X}\)</span> en <span class="math inline">\(Y_i-\overline{Y}\)</span>.</p></li>
<li><p>dan voor iedere case zijn <span class="math inline">\(X\)</span>-afwĳking met zijn <span class="math inline">\(Y\)</span>-afwĳking vermenigvuldigen, dus het product nemen: <span class="math inline">\((X_i-\overline{X})(Y_i-\overline{Y})\)</span></p></li>
<li><p>dan de producten optellen (in plaats van een <em>sum of squares</em> hebben we dus hier een <em>sum of products</em>): <span class="math inline">\(\sum\limits^{i=n}_{i=1}{(X_i-\overline{X})(Y_i-\overline{Y})}\)</span></p></li>
<li><p>dan delen door het aantal vrĳheidsgraden, dus <span class="math inline">\(n-1\)</span>, (of dus vermenigvuldigen met het omgekeerde, zoals ik hem graag zie): <span class="math inline">\(\frac{1}{n-1} \cdot \sum\limits^{i=n}_{i=1}{(X_i-\overline{X})(Y_i-\overline{Y})}\)</span></p></li>
</ul>
<p>Zoals de variantie <span class="math inline">\(S^2\)</span> voor een variabele als het ‘gemiddelde kwadraat’ (of gemiddelde oppervlakte van een blauw <em>vierkant</em>) te interpreteren is, zo kun je de covariantie <span class="math inline">\(S_{xy}\)</span> voor twee variabelen als het gemiddelde product (of gemiddelde oppervlakte van een rechthoek waarvan de twee zijden dus voor de afwijking op <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> staan).</p>
<p>Berekening aan de hand van een tabel:</p>
<!-- tabel 3B -->
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Berekening Covariantie Leeftijd en Lengte voor Aapjes Data</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respnr.
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Leeftijd
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Lengte
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Afwijking op X
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Afwijking op Y
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Produkt van Afwijkingen
</div></th>
</tr>
<tr class="even">
<th style="text-align: center;" data-quarto-table-cell-role="th">$i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$X_i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Y_i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$X_i - \overline{X}$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Y_i - \overline{Y}$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$(X_i - \overline{X})(Y_i - \overline{Y})$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">-0.5</td>
<td style="text-align: center;">-30</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">-0.5</td>
<td style="text-align: center;">-20</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">-0.5</td>
<td style="text-align: center;">-10</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">-10</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">$\sum\limits^{i=9}_{i=1}{(X_i-\overline{X})} = 0$</td>
<td style="text-align: center;">$\sum\limits^{i=9}_{i=1}{(Y_i-\overline{Y})} = 0$</td>
<td style="text-align: center;">$\sum\limits^{i=9}_{i=1}{(X_i-\overline{X})(Y_i-\overline{Y})} = 60$</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Aan de laatste kolom is dus te zien wat de waarden van de individuele producten zĳn en je kan dus aan die waarden zien of ze bĳdragen aan géén, een positief of een negatief verband. Hier dragen dus zes apen bĳ aan een positief verband (zes producten hebben een positieve waarde), drie aan geen verband (drie producten hebben een waarde van nul) en nul aapjes aan een negatief verband (zes producten hebben een negatieve waarde). Je kunt nu ook meteen zien dat aapje nummer <span class="math inline">\(1\)</span> en <span class="math inline">\(9\)</span> het sterkst bĳdragen omdat hun producten het <em>meest</em> van 0 afwĳken (absoluut gezien het grootst zĳn). Deze twee apen liggen dan ook beide het verst van het ‘middelpunt’ van de puntenwolk vandaan.</p>
<p>Als je de de <em>Sum of Products</em> dus deelt door het aantal vrĳheidsgraden, hier <span class="math inline">\(8\)</span>, ben je klaar:</p>
<p><span class="math inline">\(S_{xy} = \frac{60}{8} = 60/8 = 7.5\)</span></p>
<p><span class="math inline">\(S_{xy} = \frac{1}{8} \cdot 60 = 1/8 \cdot 60  = 7.5\)</span> (of je vermenigvuldigt dus met <span class="math inline">\(\frac{1}{8}\)</span>)</p>
<p>De berekening meteen uitgewerkt aan de hand van de formule:</p>
<p><span class="math display">\[S_{xy} = cov(xy) =  \frac{1}{n-1} \cdot \sum\limits^{i=n}_{i=1}{(X_i-\overline{X})(Y_i-\overline{Y})}\]</span></p>
<p><span class="math display">\[S_{xy} =  \frac{1}{9-1} \cdot \sum\limits^{i=9}_{i=1}{(X_i-\overline{X})(Y_i-\overline{Y})}\]</span></p>
<p><span class="math display">\[S_{xy} =  \frac{1}{9-1} \cdot [(1–1.5)(120–150) + (1–1.5)(130–150) + (1–1.5)(140–150) + \\  (1.5–1.5)(140–150) + (1.5–1.5)(150–150) + (1.5–1.5)(160–150) + \\ (2–1.5)(160–150)  +  (2–1.5)(170–150) + (2–1.5)(180–150) ]\]</span></p>
<p><span class="math display">\[S_{xy} =  \frac{1}{8} \cdot [\text{-}.5·\text{-}30 + \text{-}.5·\text{-}20 + \text{-}.5·\text{-}10 + 0·\text{-}10 + 0·0 + 0·10 +.5·10 +.5·20 +.5·30]\]</span> <span class="math display">\[S_{xy} =  \frac{1}{8} \cdot [15 + 10 + 5 + 0+ 0 + 0 + 5 + 10 + 15]\]</span> <span class="math display">\[S_{xy} =  \frac{1}{8} \cdot [60]\]</span> <span class="math display">\[S_{xy} =  \frac{1}{8} \cdot 60 = 1/8 \cdot 60 \]</span> <span class="math display">\[S_{xy} =  7.5\]</span></p>
<p>We hebben dus nu de waarde van de covariantie berekend (<span class="math inline">\(S_{xy} = 7.50\)</span>), maar aangezien de covariantie een <em>ruwe</em> (ongestandaardiseerde) samenhangsmaat is, kunnen we nog niet echt (of direkt) zeggen <em>hoe</em> sterk het gevonden verband is (behalve dat het verband tussen <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> dus positief is). Ruw is Ruk, zeg ik vaak. De eenheden voor leeftĳd en lengte waar we nu mee gerekend hebben, stonden qua éénheid, respectievelĳk in jaren en centimeters, maar als je bĳvoorbeeld je berekeningen voor lengte in meters had gedaan, was de uiteindelĳke waarde van de covariantie honderd maal zo klein (leuke oefening, transformeer centimeters naar meters en bereken opnieuw de covariantie, maar nu dus voor lengte in meters en leeftijd in jaren en check of de uiteindelijke waarde voor de covariantie daadwekelijk honderd keer zo klein is). Er zijn wel wat moeilijkere interpretaties mogelijk, maar die zijn even niet van belang en je gebruikt het toch amper. Op naar een gestandaardiseerde samenhangsmaat!</p>
</section>
<section id="correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen." class="level3">
<h3 class="anchored" data-anchor-id="correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen.">Correlatiecoëfficiënt, de Pearson Correlatie als gestandaardiseerde maat voor het verband tussen twee variabelen.</h3>
<p>De correlatiecoëfficiënt (<span class="math inline">\(r_{xy}\)</span>) is dus een gestandaardiseerde maat voor samenhang die wel in één keer is te interpreteren qua sterkte! Laten we hem eerst maar berekenen. Natuurlĳk zĳn er tal van manieren (formules) om de correlatie te berekenen, maar we pakken even degene die voor <em>nu</em> het snelst werkt, we hebben immers al heel wat statistieken berekend:</p>
<p><span class="math display">\[ r_{xy} = \frac{S_{xy}}{S_x \cdot S_y} \]</span></p>
<p>Met de gegevens die we eerder hebben berekend:</p>
<p><span class="math inline">\(S_{xy} = 7.5\)</span>, <span class="math inline">\(S_x^2 = .1875\)</span> en <span class="math inline">\(S_y^2 = 375\)</span></p>
<p>Dus om de standaardafwĳkingen voor <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> te krĳgen, moet je eerst nog de wortel nemen van de varianties, ik doe dat binnen de formule, zodat we niet tussen door hoeven af te ronden:</p>
<p><span class="math display">\[ r_{xy} = \frac{7.5}{\sqrt{.1875} \cdot \sqrt{375}} = 7.5/(\sqrt{.1875} \cdot \sqrt{375}) = .8944272 \]</span></p>
<p>Omdat de berekende waarde voor de correlatie (<span class="math inline">\(r_{xy} = .89\)</span>, ik heb de waarde dus op twee decimalen afgerond) positief van nul afwĳkt (positief is), moeten we dus zeggen dat er een positief verband is tussen leeftijd en lengte in deze steekproef. Omdat de waarde dicht bĳ 1 ligt kunnen we ook meteen zeggen dat het een ‘sterk’ verband is (maar wat is sterk?). De correlatie-coëfficiënt kan elke waarden aannemen tussen de <span class="math inline">\(\text{-}1\)</span> tot en met <span class="math inline">\(1\)</span>, waarbĳ de uiterste waarden (dus <span class="math inline">\(\text{-}1\)</span> en <span class="math inline">\(1\)</span>) betekenen dat het verband ‘perfect’ is en alle punten precies op één rechte lĳn liggen, als je aan de puntenwolk denkt. Bĳ een waarde van <span class="math inline">\(\text{-}1\)</span> zeggen we dus dat het verband perfect negatief is en zal de punten-lĳn dus omlaag lopen, van linksboven naar rechts onder in de grafiek. Bĳ de waarde <span class="math inline">\(+1\)</span> spreken we dus van een perfect positief verband en loopt de lijn (punten-lijn) omhoog, van links onder naar rechtsboven. Bĳ een waarde van precies 0 zeggen we dus dat er geen verband is en heb je met een puntenwolk (of puntenlijn), die niet omlaag of omhoog kruipt en dus <em>volledig</em> horizontaal ligt.</p>
</section>
<section id="andere-manieren-om-de-pearson-correlatie-uit-te-rekenen." class="level3">
<h3 class="anchored" data-anchor-id="andere-manieren-om-de-pearson-correlatie-uit-te-rekenen.">Andere manieren om de Pearson Correlatie uit te rekenen.</h3>
<p>Omdat het kan en soms handig is, ook even een andere manier om de correlatie te berekenen. Hieronder zie je misschien wel de meest gebruikte formule voor de Pearson correlatie:</p>
<p><span class="math display">\[r_{xy} =  \frac{1}{n-1} \cdot \sum\limits^{i=n}_{i=1}{\left(\frac{X_i-\overline{X}}{S_x}\right)\left(\frac{Y_i-\overline{Y}}{S_y}\right)}\]</span> Qua <em>vorm</em> lijkt die op de formule voor de covariantie, tussen de eerste twee haakjes zie je niet meer de ruwe afwijking op <span class="math inline">\(X\)</span>, maar meteen de gestandaardiseerde afwijking, een <span class="math inline">\(Z\)</span>-score dus. Besef nog even dat als je een ruwe afwijking deelt door de standaardafwijking <span class="math inline">\(\left(\frac{X_i-\overline{X}}{S_x}\right)\)</span>, weet je precies <em>hoe vaak</em> de standaardafwijking tussen de observatie en het gemiddelde past. En dat noemen we een <span class="math inline">\(z\)</span>-score. Hetzelfde gebeurt hier ook voor de variabele <span class="math inline">\(Y\)</span>. We kunnen de formule voor de correlatie (<span class="math inline">\(r_{xy}\)</span>) van hier boven dus ook korter opschrijven in termen van <span class="math inline">\(Z\)</span>-scores voor <span class="math inline">\(X_i\)</span> en <span class="math inline">\(Y_i\)</span>, dus <span class="math inline">\(Z_{X_i}\)</span> en <span class="math inline">\(Z_{Y_i}\)</span>:</p>
<p>Dus omdat <span class="math inline">\(Z_{x_i} = \frac{X_i-\overline{X}}{S_x}\)</span> en <span class="math inline">\(Z_{y_i} = \frac{Y_i-\overline{Y}}{S_y}\)</span> kunnen we de formule formule voor de Pearson correlatie dus ook als volgt opschrijven:</p>
<p><span class="math display">\[r_{xy}=\frac{1}{n-1} \cdot \sum\limits^{i=n}_{i=1}{{Z_{X_i}} \cdot Z_{Y_i}}\]</span></p>
<p>Dus even weer een tabelletje maken om de boel uit te werken, al laat ik ook even zien hoe de berekening zou gaan als je alles in een keer intypet.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Berekening Correlatie Leeftijd en Lengte voor Aapjes Data</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respnr.
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Leeftijd
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Lengte
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Gest. Afwijking op X
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Gest. Afwijking op Y
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Produkt van $Z_{x_i}$ en $Z_{y_i}$
</div></th>
</tr>
<tr class="even">
<th style="text-align: center;" data-quarto-table-cell-role="th">$i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$X_i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Y_i$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Z_{x_i} = \frac{X_i - \overline{X}}{S_x}$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Z_{y_i} = \frac{Y_i - \overline{Y}}{S_y}$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$Z_{x_i} \cdot Z_{y_i}$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">-1.1547</td>
<td style="text-align: center;">-1.5492</td>
<td style="text-align: center;">1.7889</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">-1.1547</td>
<td style="text-align: center;">-1.0328</td>
<td style="text-align: center;">1.1926</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">-1.1547</td>
<td style="text-align: center;">-0.5164</td>
<td style="text-align: center;">0.5963</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">-0.5164</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.5164</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">1.1547</td>
<td style="text-align: center;">0.5164</td>
<td style="text-align: center;">0.5963</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">1.1547</td>
<td style="text-align: center;">1.0328</td>
<td style="text-align: center;">1.1926</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">1.1547</td>
<td style="text-align: center;">1.5492</td>
<td style="text-align: center;">1.7889</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">$\sum\limits^{i=9}_{i=1}{Z_{x_i}} = 0$</td>
<td style="text-align: center;">$\sum\limits^{i=9}_{i=1}{Z_{y_i}} = 0$</td>
<td style="text-align: center;">$\sum\limits^{i=9}_{i=1}{Z_{x_i}\cdot Z_{y_i}} = 7.1554$</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ook hier weer: we willen de <em>sum of products</em> (van de <span class="math inline">\(Z_{x_i}\)</span> en <span class="math inline">\(Z_{y_i}\)</span> scores) en niet het ’product van de twee sommen van <span class="math inline">\(Z_{x_i}\)</span> en <span class="math inline">\(Z_{y_i}\)</span>, dat zou altijd de waarde van <span class="math inline">\(0\)</span> moeten hebben, omdat <span class="math inline">\(Z\)</span>-scores sowieso tot <span class="math inline">\(0\)</span> optellen. Dus invullen geeft:</p>
<p><span class="math display">\[r_{xy}=\frac{1}{n-1} \cdot \sum\limits^{i=n}_{i=1}{{Z_{X_i}} \cdot Z_{Y_i}}\]</span></p>
<p><span class="math display">\[r_{xy} = \frac{1}{9-1} \cdot 7.1554 = 1/8 \cdot 7.1554 = 7.1554/8 = .8944\]</span> Natuurlijk vinden we de zelfde waarde voor de correlatie <span class="math inline">\(r_{xy} = .89\)</span> als met onze eerste berekening. Mocht je tussen door hebben afgerond bij de berekning, kom je mischien niet helemaal precies uit op hetzelfde getal (<span class="math inline">\(.8944\)</span>), maar laat ik zeggen als jouw antwoord ergens tussen de waarde <span class="math inline">\(.8900\)</span> en de <span class="math inline">\(.9000\)</span> vind ik het mooi genoeg!</p>
</section>
</section>
<section id="lekker-belangrijk" class="level2">
<h2 class="anchored" data-anchor-id="lekker-belangrijk">Lekker Belangrijk</h2>
<p>Later, in Hoofdstuk <span class="math inline">\(6\)</span>, wanneer we regressie-analyses gaan doen, kan ik jullie meer vertellen over de sterkte van het verband tussen twee variabelen en hoe je dus de sterkte van het verband op andere manieren kunt uitdrukken, benoemen of interpreteren (of zelfs voelen). Maar voordat we daaraan beginnen, gaan we in het volgende hoofdstuk, eerst nadenken over de significantie van onze berekende steekproef-resultaten. Het begrip ‘significantie’ is een veel gebruikte term in de statistiek, de ‘significantie’ van jouw steekproef-resultaat (statistiek) vertelt je hoe serieus je de berekende waarde mag nemen, bĳvoorbeeld bĳ een gemiddelde of een correlatie (of die nou klein of groot, sterk of zwak is). Door de ‘significantie’ of belangrijkheid van jouw statistiek, weet je of je die waarde mag generaliseren. Als je generaliseert, maak je van een uitspraak (of stelling), specifiek bedoeld voor één groep (je steekproef), een uitspraak die voor een grotere groep bedoeld is. Het is dus de vraag in hoeverre <em>de waarde</em> van de door ons berekende correlatie (<span class="math inline">\(r_{xy} = .89\)</span>) ook voor de gehele populatie aapjes geldt. Niet alles wat je (toevallig) binnen je gewone leventje tegenkomt, neem je serieus en zal je meteen als voor altĳd waar aannemen. In zo’n geval zeg je vaak ‘Oh, dat is toeval’ en ‘Normaal gaat het anders’, bĳvoorbeeld als je een keer te laat komt (niet doen, geen excuus geven). Zo dus ook bĳ steekproef-trekkingen: Niet elk gevonden verschil, verband of effect neem je serieus. Je gaat niet zomaar roepen dat de populatie aapjes – van nu - langer zĳn dan aapjes van <span class="math inline">\(50\)</span> jaar geleden (die waren toen gemiddeld <span class="math inline">\(135\)</span> cm namelĳk, heb ik zo gelezen in de boeken van Jane Goodal). Een steekproef gemiddelde van <span class="math inline">\(\overline{Y} = 150\)</span> cm, gebaseerd op <span class="math inline">\(n=9\)</span>, geeft je nog niet genoeg zekerheid om meteen te roepen dat het echte populatie gemiddelde (<span class="math inline">\(\mu_y\)</span>) nu ook precies <span class="math inline">\(150\)</span> cm is en <em>nu</em> dus meer dan vroeger (<span class="math inline">\(\mu_{vroeger} = 135\)</span> cm). Alleen als je genoeg vertrouwen hebt dat je, heel vaak, tot diezelfde conclusie zou komen als je nog een keer een steekproef zou trekken en dan het <em>liefst</em> wel uit die zelfde populatie. En nog een keer, in eindeloze herhalingen. Maar hoe doe je dat als je geen zin hebt om eindeloos steekproeven te blijven trekken? Op naar de significantie (belangrijkheid) van onze bevindingen (dus onze statistieken zoals bijvoorbeeld <span class="math inline">\(\overline{Y}\)</span> of <span class="math inline">\(r_{xy}\)</span>) in het volgende hoofdstuk, gewoon gebaseerd op de enige échte steekproef die je hebt genomen!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-de-normaal-verdeling.html" class="pagination-link" aria-label="Hoofdstuk 2 - De Normaalverdeling.">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Hoofdstuk 2 - De Normaalverdeling.</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-van-steekproef-naar-populatie.html" class="pagination-link" aria-label="Hoofdstuk 4 - Van Steekproef naar Populatie. Generalisatie van Statistieken naar Parameters aan de hand van Betrouwbaarheidsintervallen en Significantie-toetsen.">
        <span class="nav-page-text"><span class="chapter-title">Hoofdstuk 4 - Van Steekproef naar Populatie. Generalisatie van Statistieken naar Parameters aan de hand van Betrouwbaarheidsintervallen en Significantie-toetsen.</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>