<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse. | Handleiding Statistiek met JASP</title>
  <meta name="description" content="6 Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse. | Handleiding Statistiek met JASP" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse. | Handleiding Statistiek met JASP" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse. | Handleiding Statistiek met JASP" />
  
  
  

<meta name="author" content="Benjamin Telkamp" />


<meta name="date" content="2021-11-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"/>
<link rel="next" href="appendix.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-0.108.3.2/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-0.108.3.2/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-0.108.3.2/rglClass.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/utils.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/buffer.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/subscenes.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/shaders.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/textures.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/projection.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/mouse.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/init.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/pieces.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/draw.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/controls.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/selection.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/rglTimer.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/pretty.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/axes.src.js"></script>
<script src="libs/CanvasMatrix4-0.108.3.2/CanvasMatrix.src.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
<script data-goatcounter="https://countcamp.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Voorwoord</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html"><i class="fa fa-check"></i>Hoofdstuk 0</a>
<ul>
<li class="chapter" data-level="0.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#handleiding-der-handleidingen-en-het-absoluut-minimale-dat-je-móet-weten."><i class="fa fa-check"></i><b>0.1</b> Handleiding der Handleidingen en het absoluut minimale dat je móet weten.</a>
<ul>
<li class="chapter" data-level="0.1.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#de-essentie-van-waar-we-mee-bezig-zĳn-in-het-leven-én-in-de-wetenschap."><i class="fa fa-check"></i><b>0.1.1</b> De essentie van waar we mee bezig zĳn, in het leven én in de wetenschap.</a></li>
<li class="chapter" data-level="0.1.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#aapjes"><i class="fa fa-check"></i><b>0.1.2</b> Aapjes</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#onderzoek-en-aantal-algemene-definities-voordat-we-aan-de-slag-gaan-met-het-echte-rekenwerk-het-absoluut-minimale-dus."><i class="fa fa-check"></i><b>0.2</b> Onderzoek en aantal algemene definities voordat we aan de slag gaan met het echte rekenwerk, het absoluut minimale dus.</a></li>
<li class="chapter" data-level="0.3" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#rekenen-aan-apen."><i class="fa fa-check"></i><b>0.3</b> Rekenen aan Apen.</a>
<ul>
<li class="chapter" data-level="0.3.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#waarnemingen-samenvatten-aan-de-hand-van-statistieken."><i class="fa fa-check"></i><b>0.3.1</b> Waarnemingen samenvatten aan de hand van statistieken.</a></li>
<li class="chapter" data-level="0.3.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#de-berekening-van-het-gemiddelde-voor-een-variabele."><i class="fa fa-check"></i><b>0.3.2</b> De berekening van het gemiddelde voor een variabele.</a></li>
<li class="chapter" data-level="0.3.3" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#de-berekening-van-de-variantie-en-de-standaardafwijking"><i class="fa fa-check"></i><b>0.3.3</b> De berekening van de Variantie en de Standaardafwijking</a>
<ul>
<li class="chapter" data-level="0.3.3.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#rekenregels-en-volgorde-van-toepassing"><i class="fa fa-check"></i><b>0.3.3.1</b> Rekenregels en volgorde van toepassing</a></li>
</ul></li>
<li class="chapter" data-level="0.3.4" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#minimale-oefening"><i class="fa fa-check"></i><b>0.3.4</b> Minimale Oefening</a></li>
</ul></li>
<li class="chapter" data-level="0.4" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#meetniveaus-van-variabelen"><i class="fa fa-check"></i><b>0.4</b> Meetniveaus van variabelen</a>
<ul>
<li class="chapter" data-level="0.4.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#nominaal"><i class="fa fa-check"></i><b>0.4.1</b> Nominaal</a></li>
<li class="chapter" data-level="0.4.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#ordinaal"><i class="fa fa-check"></i><b>0.4.2</b> Ordinaal</a></li>
<li class="chapter" data-level="0.4.3" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#interval"><i class="fa fa-check"></i><b>0.4.3</b> Interval</a></li>
<li class="chapter" data-level="0.4.4" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#ratio"><i class="fa fa-check"></i><b>0.4.4</b> Ratio</a></li>
<li class="chapter" data-level="0.4.5" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#absoluut"><i class="fa fa-check"></i><b>0.4.5</b> Absoluut</a></li>
<li class="chapter" data-level="0.4.6" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#het-negeren-van-hogere-meetniveaus."><i class="fa fa-check"></i><b>0.4.6</b> Het negeren van hogere meetniveaus.</a></li>
<li class="chapter" data-level="0.4.7" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#andere-soorten-indelingen-dan-het-meetniveau-voor-soorten-variabelen"><i class="fa fa-check"></i><b>0.4.7</b> Andere soorten indelingen (dan het meetniveau) voor soorten variabelen</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#het-beschrĳven-van-data-aan-de-hand-statistieken-en-parameters"><i class="fa fa-check"></i><b>0.5</b> Het Beschrĳven van Data aan de hand Statistieken en Parameters</a></li>
<li class="chapter" data-level="0.6" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#het-grotere-doel-lekker-significant."><i class="fa fa-check"></i><b>0.6</b> Het Grotere Doel (Lekker Significant).</a></li>
<li class="chapter" data-level="0.7" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#rekenen-met-jasp"><i class="fa fa-check"></i><b>0.7</b> Rekenen met JASP</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><i class="fa fa-check"></i><b>1</b> Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, <em>Descriptive Statistics</em>.</a>
<ul>
<li class="chapter" data-level="1.1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#waar-ligt-de-data"><i class="fa fa-check"></i><b>1.1</b> Waar ligt de Data?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#belgedrag-onder-jongeren-in-nederland"><i class="fa fa-check"></i><b>1.1.1</b> Belgedrag onder Jongeren in Nederland</a></li>
<li class="chapter" data-level="1.1.2" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#opgaven-belgedrag-onder-jongeren-in-nederland-beschrijven"><i class="fa fa-check"></i><b>1.1.2</b> <em>Opgaven</em> Belgedrag onder Jongeren in Nederland: Beschrijven</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#hoe-is-de-data-verdeeld-spreidingsmaten."><i class="fa fa-check"></i><b>1.2</b> Hoe is de data verdeeld? Spreidingsmaten.</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#opgaven-belgedrag-onder-jongeren-in-nederland-spreidingsmaten"><i class="fa fa-check"></i><b>1.2.1</b> <em>Opgaven</em> Belgedrag onder Jongeren in Nederland: Spreidingsmaten</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html"><i class="fa fa-check"></i><b>2</b> Hoofdstuk 2 - De Normaalverdeling.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#scores-zijn-verdeeld-verschillende-vormen-van-verdelingen."><i class="fa fa-check"></i><b>2.1</b> Scores zijn verdeeld, verschillende vormen van verdelingen.</a></li>
<li class="chapter" data-level="2.2" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling"><i class="fa fa-check"></i><b>2.2</b> De Normaalverdeling, Sommige Scores Volgen een Normaalverdeling</a></li>
<li class="chapter" data-level="2.3" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#opgaven-verdelingen"><i class="fa fa-check"></i><b>2.3</b> <em>Opgaven</em> Verdelingen</a></li>
<li class="chapter" data-level="2.4" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#variabelen-in-de-steekproef-en-parameters-in-de-populatie"><i class="fa fa-check"></i><b>2.4</b> Variabelen in de Steekproef en Parameters in de Populatie</a></li>
<li class="chapter" data-level="2.5" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#opgaven-variabelen-en-parameters"><i class="fa fa-check"></i><b>2.5</b> <em>Opgaven</em> Variabelen en Parameters</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><i class="fa fa-check"></i><b>3</b> Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#correlatie"><i class="fa fa-check"></i><b>3.1</b> Correlatie</a></li>
<li class="chapter" data-level="3.2" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#verband-in-woorden"><i class="fa fa-check"></i><b>3.2</b> Verband in woorden</a></li>
<li class="chapter" data-level="3.3" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#predictor-criterium-respons"><i class="fa fa-check"></i><b>3.3</b> Predictor, criterium, respons</a></li>
<li class="chapter" data-level="3.4" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#het-verband-grafisch-weergeven."><i class="fa fa-check"></i><b>3.4</b> Het verband grafisch weergeven.</a></li>
<li class="chapter" data-level="3.5" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#covariantie-en-pearson-correlatie"><i class="fa fa-check"></i><b>3.5</b> Covariantie en Pearson Correlatie</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen"><i class="fa fa-check"></i><b>3.5.1</b> Covariantie als ongestandaardiseerde maat voor het verband tussen twee variabelen</a></li>
<li class="chapter" data-level="3.5.2" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen."><i class="fa fa-check"></i><b>3.5.2</b> Correlatiecoëfficiënt, de Pearson Correlatie als gestandaardiseerde maat voor het verband tussen twee variabelen.</a></li>
<li class="chapter" data-level="3.5.3" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#andere-manieren-om-de-pearson-correlatie-uit-te-rekenen."><i class="fa fa-check"></i><b>3.5.3</b> Andere manieren om de Pearson Correlatie uit te rekenen.</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#lekker-belangrijk"><i class="fa fa-check"></i><b>3.6</b> Lekker Belangrijk</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><i class="fa fa-check"></i><b>4</b> Hoofdstuk 4 - Van Steekproef naar Populatie. Generalisatie van Statistieken naar Parameters aan de hand van Betrouwbaarheidsintervallen en Significantie-toetsen.</a>
<ul>
<li class="chapter" data-level="4.1" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#populaties-kun-je-niet-meten-steekproeven-wel."><i class="fa fa-check"></i><b>4.1</b> Populaties kun je niet meten, steekproeven wel.</a></li>
<li class="chapter" data-level="4.2" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#de-steekproevenverdeling."><i class="fa fa-check"></i><b>4.2</b> De steekproe<strong>ven</strong>verdeling.</a></li>
<li class="chapter" data-level="4.3" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#standaard-normaalverdeling-voor-steekproefgemiddelden-overliney."><i class="fa fa-check"></i><b>4.3</b> Standaard Normaalverdeling voor Steekproefgemiddel<strong>den</strong>, <span class="math inline">\(\overline{Y}\)</span>.</a></li>
<li class="chapter" data-level="4.4" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#students-t-verdeling-voor-steekproefgemiddelden-overliney."><i class="fa fa-check"></i><b>4.4</b> <em>Student’s</em> <span class="math inline">\(t\)</span>-verdeling voor Steekproefgemiddel<em>den</em>, <span class="math inline">\(\overline{Y}\)</span>.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#betrouwbaarheidsintervallen-voor-een-populatiegemiddelde."><i class="fa fa-check"></i>Betrouwbaarheidsintervallen voor een populatiegemiddelde.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#toetsing-van-een-idee-aan-de-hand-van-een-stelsel-van-hypotheses."><i class="fa fa-check"></i>Toetsing van een idee aan de hand van een stelsel van Hypotheses.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#tweezijdige-toetsing"><i class="fa fa-check"></i>Tweezijdige Toetsing</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#type-i-en-ii-fouten"><i class="fa fa-check"></i>Type I en II Fouten</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#conclusie-aan-de-hand-van-je-toetsings-resultaat."><i class="fa fa-check"></i>Conclusie aan de hand van je toetsings-resultaat.</a></li>
<li><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#when-p-is-low-h-o-must-go">When <em>p</em> is Low, H-O must Go!</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#eénzijdige-toetsing"><i class="fa fa-check"></i>Eénzijdige Toetsing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#significantietoetsen-en-betrouwbaarheidsintervallen"><i class="fa fa-check"></i><b>4.5</b> Significantietoetsen en Betrouwbaarheidsintervallen</a></li>
<li class="chapter" data-level="4.6" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#significantie-toets-voor-verband-de-pearson-correlatie"><i class="fa fa-check"></i><b>4.6</b> Significantie Toets voor Verband, de Pearson Correlatie</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><i class="fa fa-check"></i><b>5</b> Hoofdstuk 5 - Enkelvoudige Lineaire Regressie-Analyse.</a>
<ul>
<li class="chapter" data-level="5.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-voorspelling-van-een-belangrĳke-variabele-op-basis-van-één-andere-toch-óók-wel-een-beetje-belangrĳke-variabele."><i class="fa fa-check"></i><b>5.1</b> De voorspelling van een belangrĳke variabele op basis van één andere (toch óók wel een beetje belangrĳke) variabele.</a></li>
<li class="chapter" data-level="5.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#beter-voorspellen-aan-de-hand-van-een-lineaire-vergelĳking-formule."><i class="fa fa-check"></i><b>5.2</b> Beter Voorspellen aan de Hand van een Lineaire Vergelĳking (Formule).</a></li>
<li class="chapter" data-level="5.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-enkelvoudige-lineaire-regressie-vergelĳking-de-regressie-lĳn"><i class="fa fa-check"></i><b>5.3</b> De Enkelvoudige Lineaire Regressie-vergelĳking, de Regressie-lĳn</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#slope-en-intercept-old-school"><i class="fa fa-check"></i><b>5.3.1</b> Slope en Intercept, Old School</a></li>
<li class="chapter" data-level="5.3.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#slope-en-intercept-for-real"><i class="fa fa-check"></i><b>5.3.2</b> Slope en Intercept, For Real</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#voorspelkracht"><i class="fa fa-check"></i><b>5.4</b> Voorspelkracht</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#het-spel-bij-regressie"><i class="fa fa-check"></i><b>5.4.1</b> Het Spel bij Regressie</a></li>
<li class="chapter" data-level="5.4.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdeling-van-totale-afwijking-in-model-en-error-per-individu"><i class="fa fa-check"></i><b>5.4.2</b> Opdeling van Totale Afwijking in Model en Error per Individu</a></li>
<li class="chapter" data-level="5.4.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdeling-van-totale-variatie-in-model-variatie-en-error-variatie"><i class="fa fa-check"></i><b>5.4.3</b> Opdeling van Totale Variatie in Model Variatie en Error Variatie</a>
<ul>
<li class="chapter" data-level="5.4.3.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#sum-of-squares-voor-total-model-en-error"><i class="fa fa-check"></i><b>5.4.3.1</b> Sum of Squares voor Total, Model en Error</a></li>
</ul></li>
<li class="chapter" data-level="5.4.4" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#grand-final"><i class="fa fa-check"></i><b>5.4.4</b> Grand Final</a>
<ul>
<li class="chapter" data-level="5.4.4.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#standaardafwijking-van-de-error"><i class="fa fa-check"></i><b>5.4.4.1</b> Standaardafwijking van de error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsintervallen-en-significantietoetsen-voor-regressie-parameters."><i class="fa fa-check"></i><b>5.5</b> Betrouwbaarheidsintervallen en Significantietoetsen voor Regressie-Parameters.</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsinterval-bi-voor-de-populatie-slope-beta_1"><i class="fa fa-check"></i><b>5.5.1</b> Betrouwbaarheidsinterval (BI) voor de populatie-slope <span class="math inline">\(\beta_1\)</span></a></li>
<li class="chapter" data-level="5.5.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#significantietoets-voor-de-populatie-slope"><i class="fa fa-check"></i><b>5.5.2</b> Significantietoets voor de Populatie Slope</a>
<ul>
<li class="chapter" data-level="5.5.2.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-t-toets-voor-een-regressieslope"><i class="fa fa-check"></i><b>5.5.2.1</b> De t-toets voor een regressieslope</a></li>
</ul></li>
<li class="chapter" data-level="5.5.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsinterval-en-toetsing-van-het-intercept"><i class="fa fa-check"></i><b>5.5.3</b> Betrouwbaarheidsinterval en Toetsing van het Intercept</a>
<ul>
<li class="chapter" data-level="5.5.3.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsinterval-voor-het-populatie-intercept-beta_0"><i class="fa fa-check"></i><b>5.5.3.1</b> Betrouwbaarheidsinterval voor het Populatie Intercept (<span class="math inline">\(\beta_0\)</span>)</a></li>
<li class="chapter" data-level="5.5.3.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#significantietoets-voor-het-populatie-intercept-beta_0"><i class="fa fa-check"></i><b>5.5.3.2</b> Significantietoets voor het Populatie Intercept (<span class="math inline">\(\beta_0\)</span>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#toetsing-van-een-model-als-geheel"><i class="fa fa-check"></i><b>5.6</b> Toetsing van een Model als ‘Geheel’</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#toetsing-van-het-regressie_model_-aan-de-hand-de-hand-van-een-anova-tabel"><i class="fa fa-check"></i><b>5.6.1</b> Toetsing van het regressie_model_ aan de hand de hand van een ANOVA tabel</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-4-populatie-assumpties-bij-lineaire-enkelvoudige-regressie-analyse."><i class="fa fa-check"></i><b>5.7</b> De 4 Populatie-assumpties bij Lineaire Enkelvoudige Regressie Analyse.</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#onafhankelĳkheid-van-observaties"><i class="fa fa-check"></i><b>5.7.1</b> Onafhankelĳkheid van Observaties</a></li>
<li class="chapter" data-level="5.7.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#lineariteit"><i class="fa fa-check"></i><b>5.7.2</b> Lineariteit</a></li>
<li class="chapter" data-level="5.7.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#homoscedasticiteit"><i class="fa fa-check"></i><b>5.7.3</b> Homoscedasticiteit</a></li>
<li class="chapter" data-level="5.7.4" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#normaal-verdeelde-residuen"><i class="fa fa-check"></i><b>5.7.4</b> Normaal verdeelde residuen</a></li>
<li class="chapter" data-level="5.7.5" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#wrapping-up"><i class="fa fa-check"></i><b>5.7.5</b> Wrapping Up</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#aapjes-en-jasp"><i class="fa fa-check"></i><b>5.8</b> AAPJES en JASP</a></li>
<li class="chapter" data-level="5.9" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#rapporteren-van-je-resultaten"><i class="fa fa-check"></i><b>5.9</b> Rapporteren van je Resultaten</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#inleiding"><i class="fa fa-check"></i>Inleiding</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#methode"><i class="fa fa-check"></i>Methode</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#participanten"><i class="fa fa-check"></i>Participanten</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#meetinstrumenten"><i class="fa fa-check"></i>Meetinstrumenten</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#analyse"><i class="fa fa-check"></i>Analyse</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#resultaten"><i class="fa fa-check"></i>Resultaten</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#jasp-lineaire-enkelvoudige-regressie-analyse-qol"><i class="fa fa-check"></i><b>5.10</b> JASP, Lineaire Enkelvoudige Regressie Analyse, QOL</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#lineaire-regressie-aan-de-hand-van-één-continue-interval-predictor."><i class="fa fa-check"></i><b>5.10.1</b> Lineaire Regressie aan de hand van één continue (interval) predictor.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-1"><i class="fa fa-check"></i>Opdracht 1</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-2"><i class="fa fa-check"></i>Opdracht 2</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-3"><i class="fa fa-check"></i>Opdracht 3</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-4"><i class="fa fa-check"></i>Opdracht 4</a></li>
</ul></li>
<li class="chapter" data-level="5.10.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#enkelvoudige-lineaire-regressie-analyse-aan-de-hand-van-nominale-predictoren."><i class="fa fa-check"></i><b>5.10.2</b> Enkelvoudige Lineaire Regressie-Analyse aan de hand van Nominale Predictoren.</a>
<ul>
<li><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-1-independent-samples-t-test-voor-het-vergelijken-van-twee-steekproefgemiddelden.">Opdracht 1, ‘independent samples <span class="math inline">\(t\)</span>-test’ voor het vergelijken van twee steekproefgemiddelden.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-2-enkelvoudige-regressie-analyse-voor-het-vergelijken-van-twee-steekproefgemiddelden-aan-de-hand-van-een-dummy-variabele."><i class="fa fa-check"></i>Opdracht 2, ‘Enkelvoudige Regressie-analyse’ voor het vergelijken van twee steekproefgemiddelden aan de hand van een dummy-variabele.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#enkelvoudige-regressie-analyse-voor-het-vergelijken-van-drie-steekproefgemiddelden-aan-de-hand-van-twee-dummy-variabelen."><i class="fa fa-check"></i>‘Enkelvoudige Regressie-analyse’ voor het vergelijken van drie steekproefgemiddelden aan de hand van twee dummy-variabelen.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-3-1"><i class="fa fa-check"></i>Opdracht 3</a></li>
</ul></li>
<li class="chapter" data-level="5.10.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#eénweg-anova-oneway-anova"><i class="fa fa-check"></i><b>5.10.3</b> Eénweg ANOVA (oneway ANOVA)</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-4-oneway-anova"><i class="fa fa-check"></i>Opdracht 4, Oneway ANOVA</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#assumptie-checks-voor-eenweg-anova"><i class="fa fa-check"></i>Assumptie checks voor eenweg ANOVA</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#oneway-anova-rapporteren"><i class="fa fa-check"></i>Oneway ANOVA Rapporteren</a></li>
</ul></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><i class="fa fa-check"></i><b>6</b> Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html#correctie-voor-spurieuze-verbanden"><i class="fa fa-check"></i>Correctie voor Spurieuze Verbanden</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html#veranderende-of-omdraaiende-verbanden"><i class="fa fa-check"></i>Veranderende of Omdraaiende verbanden</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="6.1" data-path="appendix.html"><a href="appendix.html#standaard-normaalverdeling-z-tabel"><i class="fa fa-check"></i><b>6.1</b> Standaard Normaalverdeling, <span class="math inline">\(z\)</span>-tabel</a></li>
<li class="chapter" data-level="6.2" data-path="appendix.html"><a href="appendix.html#t-verdeling-t-tabel"><i class="fa fa-check"></i><b>6.2</b> <span class="math inline">\(t\)</span>-verdeling, <span class="math inline">\(t\)</span>-tabel</a></li>
<li class="chapter" data-level="6.3" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel"><i class="fa fa-check"></i><b>6.3</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel-voor-alpha-.05"><i class="fa fa-check"></i><b>6.3.1</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel, voor <span class="math inline">\(\alpha = .05\)</span></a></li>
<li class="chapter" data-level="6.3.2" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel-voor-alpha-.025"><i class="fa fa-check"></i><b>6.3.2</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel, voor <span class="math inline">\(\alpha = .025\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel-voor-alpha-.01"><i class="fa fa-check"></i><b>6.3.3</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel, voor <span class="math inline">\(\alpha = .01\)</span></a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Handleiding Statistiek met JASP</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hoofdstuk-6---meervoudige-lineaire-regressie-analyse." class="section level1" number="6">
<h1><span class="header-section-number">6</span> Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse.</h1>
<p>In hoofdstuk <span class="math inline">\(3\)</span> hebben we gekeken naar de relatie (verband, correlatie, covariatie, associatie, samenhang) tussen twee variabelen, hierbij maakte we geen onderscheid in voorspelrichting. Hoofdstuk <span class="math inline">\(5\)</span> heeft dit onderscheid wel: dus één onafhankelijke variabele (de predictor <span class="math inline">\(x\)</span>) en de afhankelijke variabele (de uitkomst of het criterium, <span class="math inline">\(y\)</span>). Dit extra onderscheid in voorspelrichting heb je dus niet bij een ‘simpele’ Pearson correlatie tussen twee (interval) variabelen zoals in hoofdstuk <span class="math inline">\(3\)</span>. Sterker nog, in hoofdstuk <span class="math inline">\(5\)</span>, hebben we gekeken <em>hoe</em> je de afhankelijke variabele (<span class="math inline">\(Y\)</span>) kan voorspellen op basis van de onafhankelijke variabele aan de hand van een enkelvoudige regressievergelijking: <span class="math inline">\(\hat{y}_i = b_0 + b_1 \cdot x_i\)</span>. De slope (<span class="math inline">\(b_1\)</span>) speelt hierbij de belangrijkste rol, omdat de waarde van de slope je precies vertelt hoeveel punten (éénheden) de afhankelijke variabele ‘verandert’ voor elke toename (of afname) van één éénheid voor de predictor. Bedenk nog even dat bij onze aapjes, <span class="math inline">\(1\)</span> jaar verschil in leeftijd (<span class="math inline">\(X\)</span>) overeenkomt met <span class="math inline">\(40\)</span> cm verschil in lengte (<span class="math inline">\(Y\)</span>) vanwege <span class="math inline">\(b_1 = 40\)</span>. Op zich best flauw, want als de correlatie tussen twee variabelen positief is, zal de slope, dus bij een enkelvoudige regressie, ook positief zijn. Altijd, altijd en altijd. Vaak vinden we het dus al genoeg om te weten <em>hoe</em> sterk de relatie is in termen van ‘gewoon’ de (Pearson) correlatie (<span class="math inline">\(r_{xy}\)</span>) en doet de slope er dus eigenlijk niet toe. En als je de correlatie (<span class="math inline">\(r_{xy}\)</span>) kwadrateert, weet je ook welk gedeelte (proportie) of hoeveel procent, van de totale variatie de variabelen van <em>elkaar</em> kunnen verklaren (de <em>Variance Accounted For</em>, VAF). Waarom hebben we dan enkelvoudige regressie analyses uitgevoerd in hoofdstuk <span class="math inline">\(5\)</span>? Puur als opbouw en basis voor dit hoofdstuk.</p>
<p>Aangezien onze wereld uit meer dan slechts twee variabelen bestaat en er natuurlijk velen mogelijke andere predictoren (verklaarders) bestaan voor de voorspelling van een afhankelijke variabele, willen we juist weten welke <em>combinatie</em> van predictoren de afhankelijke variabele zo goed mogelijk voorspelt. Daarom dus juist een (Lineaire) Multipele Regressie Analyse (MRA) en eigenlijk begint onze wereld hier pas, hier worden wij als statistici pas warm van (Ja ja)!</p>
<div id="correctie-voor-spurieuze-verbanden" class="section level4 unnumbered">
<h4>Correctie voor Spurieuze Verbanden</h4>
<p>De heer Wilders is geen statisticus (zoals zoveel politici) en hij denkt dan ook behoorlijk enkelvoudig en baseert zijn conclusies dus ook enkel en alleen op simpele verbanden (het verband tussen slechts twee variabelen). Zijn gedachtegang is bijvoorbeeld dat (verschil in) etniciteit (<span class="math inline">\(x\)</span>) de <em>oorzaak</em> is aan van het al dan niet vertonen van crimineel gedrag (<span class="math inline">\(y\)</span>) en hij veronderstelt dus een causaal (oorzakelijk) verband: het één <em>veroorzaakt</em> het ander. Ik ben het met hem eens dat er een <em>relatie</em> is tussen deze twee variabelen, Ik geloof heus wel dat Marokkaanse jongeren vaker crimineel zijn dan Hollandse jongeren, maar is dit het hele verhaal? Natuurlijk niet, de heer Wilders vergeet in zijn betoog te kijken naar andere variabelen die de criminaliteit veel beter (misschen wel echt op een oorzakelijke manier) verklaren. Sterker nog, als je ‘corrigeert’ (leg ik zo uit) voor andere variabelen, zoals sociaal economische status (SES) of opleidingsniveau, zal het effect van etniciteit (op crimineel gedrag) geheel verdwijnen. Het probleem is dat Marokkaanse jongeren vaak opgroeien in gezinnen met een behoorlijk lage SES (laag inkomen en/of laag opleidingsniveau). Het feit dat deze jongeren dus vaak relatief arm zijn, is misschien wel de daadwerkelijke rede dat deze jongeren crimineel gedrag vertonen, want ook de jongeren uit relatief arme Hollandse gezinnen, zijn meer geneigd tot criminaliteit. Het is dus waarschijnlijker dat armoede leidt tot (de veroorzaker is van) criminaliteit, en dus niet de afkomst van een persoon. Als je naar simpele verbanden kijkt, zul je vaak verbanden tegenkomen die eigenlijk ‘spurieus’ (schijn) zijn. Een correlatie tussen twee variabelen is spurieus als na correctie (of controle) voor een andere variabele er eigenlijk geen verband meer is tussen de eerste twee. Nou is Wilders ook wel een heel spurieuze verschijning, zou ik zo zeggen. Belangrijk voor <em>nu</em> is dat je onthoudt dat het juist de <em>combinatie</em> van meerdere predictoren is, waarmee je kan uitvogelen <em>welke</em> predictor (of combinatie van predictoren) ‘echt’ van belang zijn voor de voorspelling van een afhankelijke variabele. Je zal zien dat bij een multipele regressie, om criminalteit te voorspellen op basis van zowel etniciteit als SES, het alléén SES is die nog variatie zal verklaren! Dus als het om ‘meer of minder gaat’ zouden we dus van alle armen afmoeten, willen we criminaliteit voorkomen!</p>
</div>
<div id="veranderende-of-omdraaiende-verbanden" class="section level4 unnumbered">
<h4>Veranderende of Omdraaiende verbanden</h4>
<p>Stel je wilt zo goed mogelijk (variatie in) een variabele (<span class="math inline">\(y\)</span>) verklaren en je hebt meerdere voorspellers (<span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(x_3\)</span>…) tot je beschikking. Bijvoorbeeld een toets-cijfer op de basisschool als criterium (<span class="math inline">\(y\)</span>) en je hebt gegevens over het aantal studie uren (<span class="math inline">\(x_1\)</span>), en de intelligentie (<span class="math inline">\(x_2\)</span>) van ieder kind. Stel dat je de data verzameld hebt en <em>alleen</em> kijkt naar de (simpele) correlatie (of enkelvoudige regressie) tussen het aantal studie-uren (<span class="math inline">\(x_1\)</span>) en het toetscijfer (<span class="math inline">\(y\)</span>). Wat denk je, een positief of negatief verband tussen de twee variabelen? Gek genoeg, zul je hoogst waarschijnlijk een <em>negatief</em> verband vinden, dus hoe <em>langer</em> iemand gestudeerd heeft, des te <em>lager</em> zal zijn toets-score zijn, gek hè? En toch is het zo. Ook niet heel gek, want wie zijn het die vaak het laagst scoren? De kinderen die het minst intelligent zijn en het zijn juist die kinderen die vaak langer moeten studeren (maar nog steeds een relatief laag cijfer halen). Tuurlijk als je alleen kijkt naar een groepje kinderen met dezelfde intelligentie, en als je binnen dat groepje de toetsscores vergelijkt tussen de kinderen die kort of juist lang hebben gestudeerd, dan zul je juist wel vinden dat het aantal studie-uren <em>positief</em> gerelateerd is aan de toets-score. Dus gewoon zoals je verwacht had misschien, hoe langer iemand studeert des te hoger zal zijn cijfer zijn. Maar zeker op een basisschool, zul je dus ook veel variatie in intelligentie hebben. Alleen bij specifieke groepen waarin kinderen een vergelijkbare intelligentie hebben (zoals bijvoorbeeld binnen een mavo, havo of vwo klas), zul je meteen een positief verband vinden tussen het aantal studie uren en de toets-score. Maar als je dus wel veel variatie hebt in intelligentie, is het dus van belang om deze variabele mee te nemen (als predictor) in je regressie-analyse, juist zodat je kunt achterhalen wat het effect is van het aantal studie uren binnen groepjes van kinderen met éénzelfde intelligentie. Dat doet een multipele regressie gewoon voor je! Deze analyse ‘kijkt’ telkens naar een groepje kinderen met eenzelfde waarde voor intelligentie en kijkt vervolgens wat het effect is van het aantal studie-uren op de toets-score binnen dat groepje. We zeggen dan ook wel dat we dan naar het effect van studie-uren (op de toets-score) kijken onder ‘constant-houding van’ of ‘gecontroleerd voor’ intelligentie (terwijl het gewoon de tweede predictor is in onze MRA).</p>
<p>Laten we dit laatste verhaal ook eens aan de hand van een paar plaatjes bekijken. Dus de basisschool situatie, waarin we drie variabelen meten: Toets-score (<span class="math inline">\(y\)</span>), het aantal studie-uren (<span class="math inline">\(x_1\)</span>) en IQ (<span class="math inline">\(x_2\)</span>) waarbij we de volgende data-set tot onze beschikking hebben:</p>
<table>
<caption>
<span id="tab:toets-score">Tabel 6.1: </span>Toets Data
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respondentnummer
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Toets Score
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Aantal Studie-uren
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
IQ
</div>
</th>
</tr>
<tr>
<th style="text-align:center;">
<span class="math inline">\(i\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(y_i\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(x_{i1}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(x_{i2}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3.0
</td>
<td style="text-align:center;">
110
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
4.5
</td>
<td style="text-align:center;">
105
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
5.0
</td>
<td style="text-align:center;">
105
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
5.0
</td>
<td style="text-align:center;">
100
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
5.5
</td>
<td style="text-align:center;">
100
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
6.0
</td>
<td style="text-align:center;">
95
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
7.0
</td>
<td style="text-align:center;">
95
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
4.0
</td>
<td style="text-align:center;">
110
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
5.5
</td>
<td style="text-align:center;">
100
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
6.5
</td>
<td style="text-align:center;">
95
</td>
</tr>
<tr>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
3.5
</td>
<td style="text-align:center;">
110
</td>
</tr>
<tr>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
4.5
</td>
<td style="text-align:center;">
105
</td>
</tr>
</tbody>
</table>
<p>Laten we eerst kijken naar de voorspelling van de toets-score op basis van <em>alleen</em> het aantal studie-uren. We kijken dan dus aan de hand van een enkelvoudige regressie naar het simpele verband tussen deze twee variabelen:</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:toetsData-plaatje1"></span>
<img src="main_files/figure-html/toetsData-plaatje1-1.png" alt="Een (ogenschijnlijk) negatief verband tussen het aantal studie-uur en toets-score" width="672" />
<p class="caption">
Figuur 6.1: Een (ogenschijnlijk) negatief verband tussen het aantal studie-uur en toets-score
</p>
</div>
<p>Je ziet dat de puntenwolk van linksboven naar rechts onder loopt, en dus een negatief verband weergeeft tussen het aantal studie-uren en de toets-score. En de regressielijn laat daarom ook een dalende trent zien met een slope (<span class="math inline">\(b_1\)</span>) die negatief is (<span class="math inline">\(-0.74\)</span>) en dus aangeeft dat voor elk studie-uur (één eenheid dus) dat er <em>meer</em> gestudeerd wordt er dus (gemiddeld gezien) <span class="math inline">\(0.74\)</span> eenheid <em>lager</em> gescoord wordt op de toets. Maar dit is dus wel een heel ‘simpel’ verhaal, het ‘meervoudige’ verhaal luidt geheel anders.</p>
<p>In het volgende plaatje, hou ik ook rekening met de intelligentie van de leerlingen en heb de punten - per specifieke waarde van IQ - een kleur gegeven. Zo heb ik de leerlingen met de hoogste intelligentie (<span class="math inline">\(IQ = 110\)</span>) rood gekleurd. In dit plaatje staat dus informatie over drie variabelen weergegeven:</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:toetsData-plaatje2"></span>
<img src="main_files/figure-html/toetsData-plaatje2-1.png" alt="Een positief verband tussen tussen het aantal studie-uur en toets-score, na (met) correctie voor IQ" width="672" />
<p class="caption">
Figuur 6.2: Een positief verband tussen tussen het aantal studie-uur en toets-score, na (met) correctie voor IQ
</p>
</div>
<p>Als je naar één puntje (van een leerling) kijkt, zie je drie dingen:</p>
<ul>
<li><p>Hoe links of rechts een puntje staat (het links-rechts gebeuren, of de variatie in horizontale richting, de <span class="math inline">\(x_1\)</span> - as), dus de waarde op het aantal studie-uur, <span class="math inline">\(x_1\)</span>. Zo heeft het meest linker puntje (voor leerling <span class="math inline">\(i = 1\)</span>) dus een waarde <span class="math inline">\(3\)</span> op het aantal studie-uur.</p></li>
<li><p>De kleur van het puntje (het kleur-gebeuren, of de gebruikte kleurvariatie voor verschil in waarde voor <span class="math inline">\(x_2\)</span>). Zo is het puntje voor leerling <span class="math inline">\(i = 1\)</span> rood en staat dus voor een IQ met de waarde <span class="math inline">\(110\)</span></p></li>
<li><p>Hoe hoog of een puntje staat (het laag-hoog gebeuren, of dus variatie in verticale richting, dus de <span class="math inline">\(y\)</span> - as), dus de waarde op de toets-score, <span class="math inline">\(y\)</span>. Zo heeft het meest linker puntje dus een waarde <span class="math inline">\(8\)</span> op de toets-score.</p></li>
</ul>
<p>Richt je aandacht nu op slechts één groepje leerlingen voor één bepaalde waarde qua IQ. Zo zie je dat <em>binnen</em> het groepje leerlingen met <span class="math inline">\(IQ = 110\)</span> (dus de drie rode puntjes), dat het verband tussen het aantal studie-uur nu wel positief is. Als je alleen voor dit groepje (<span class="math inline">\(n = 3\)</span>) een enkelvoudige regressie runt (dus met <span class="math inline">\(y=\)</span> toets-score, <span class="math inline">\(x=\)</span> aantal studie-uur) vind je een slope met de waarde <span class="math inline">\(2\)</span>, dus positief! Zo vind je bij het volgende groepje (voor <span class="math inline">\(IQ = 105\)</span>, <span class="math inline">\(n=3\)</span>) ook een positieve slope (<span class="math inline">\(b_1 = 3\)</span>) en bij de twee andere groepjes vind je dus ook een positieve slope. Wat is de gemiddelde waarde van die vier slopes? Ik zou zeggen (ongeveer) <span class="math inline">\(2.5\)</span>, dus binnen de groepjes is de slope, gemiddeld gezien, dus positief en ligt ergens rond de waarde <span class="math inline">\(2.5\)</span>. Dus als twee leerlingen met hetzelfde IQ, 1 uur verschillen qua aantal studie-uur dan, zal de leerling met een uur meer gestudeerd, ongeveer <span class="math inline">\(2.5\)</span> punten hoger scoren op de toets-score.</p>
<p>Hoewel voor later in dit hoofdstuk niet echt nodig, heb ik toch dezelfde informatie ook op een andere manier geplot (uitgezet in een grafiek). Het verband tussen twee variabelen is vrij makkelijk te plotten. je gebruik dan dus alleen een <span class="math inline">\(x\)</span>- en <span class="math inline">\(y\)</span>-as (dus twee dimensionaal, links-recht, en laag-hoog). Bij drie variabelen moeten we <em>ook</em> nog (variatie in) de diepte aangeven en wordt het plotten dus al een stuk lastiger. Ik heb voor nu een <em>fancy</em> drie-dimensionaal plaatje gemaakt waarin je dus drie assen kunt onderscheiden (<span class="math inline">\(x_1\)</span>-, <span class="math inline">\(x_2\)</span>- en <span class="math inline">\(y\)</span>-as). Voor het kijk-gemak heb ik ook nog het kleur onderscheid behouden, terwijl dit dus eigenlijk niet nodig is. Je kunt met de muis het plaatje laten draaien door er op te klikken en heen en weer te slepen of in te zoemen door te scrollen. Kijk maar of je leerling met <span class="math inline">\(i=1\)</span> kunt terugvinden. Zijn</p>
<pre><code>## This build of rgl does not include OpenGL functions.  Use
##  rglwidget() to display results, e.g. via options(rgl.printRglwidget = TRUE).</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:toetsData-plaatje3"></span>
<style>#rgl89698 {margin:auto;}</style>
<div id="rgl89698" style="width:672px;height:432px;" class="rglWebGL html-widget"></div>
<script type="application/json" data-for="rgl89698">{"x":{"material":{"color":"#000000","alpha":1,"lit":true,"ambient":"#000000","specular":"#FFFFFF","emission":"#000000","shininess":50,"smooth":true,"front":"filled","back":"filled","size":3,"lwd":1,"fog":true,"point_antialias":false,"line_antialias":false,"texture":null,"textype":"rgb","texmipmap":false,"texminfilter":"linear","texmagfilter":"linear","texenvmap":false,"depth_mask":true,"depth_test":"less","isTransparent":false,"polygon_offset":[0,0],"margin":"","floating":false,"tag":""},"rootSubscene":1,"objects":{"7":{"id":7,"type":"spheres","material":{},"vertices":"0","colors":"1","radii":[[0.156938299536705]],"centers":"2","ignoreExtent":false,"fastTransparency":true,"flags":32771},"9":{"id":9,"type":"text","material":{"lit":false,"margin":0,"floating":true,"edge":[0,1,1]},"vertices":"3","colors":"4","texts":[["aantal studie-uren"]],"cex":[[1]],"adj":[[0.5,0.5,0.5]],"centers":"5","family":[["sans"]],"font":[[1]],"ignoreExtent":true,"flags":33808},"10":{"id":10,"type":"text","material":{"lit":false,"margin":1,"floating":true,"edge":[1,1,1]},"vertices":"6","colors":"7","texts":[["IQ"]],"cex":[[1]],"adj":[[0.5,0.5,0.5]],"centers":"8","family":[["sans"]],"font":[[1]],"ignoreExtent":true,"flags":33808},"11":{"id":11,"type":"text","material":{"lit":false,"margin":2,"floating":true,"edge":[1,1,1]},"vertices":"9","colors":"10","texts":[["Toets-score"]],"cex":[[1]],"adj":[[0.5,0.5,0.5]],"centers":"11","family":[["sans"]],"font":[[1]],"ignoreExtent":true,"flags":33808},"12":{"id":12,"type":"lines","material":{"alpha":0.298039227724075,"lit":false,"isTransparent":true},"vertices":"12","colors":"13","centers":"14","ignoreExtent":false,"flags":32864},"5":{"id":5,"type":"light","vertices":[[0,0,1]],"colors":[[1,1,1,1],[1,1,1,1],[1,1,1,1]],"viewpoint":true,"finite":false},"4":{"id":4,"type":"background","material":{},"colors":"15","centers":"16","sphere":false,"fogtype":"none","fogscale":1,"flags":32768},"6":{"id":6,"type":"background","material":{"lit":false,"back":"lines"},"colors":"17","centers":"18","sphere":false,"fogtype":"none","fogscale":1,"flags":32768},"8":{"id":8,"type":"bboxdeco","material":{"front":"lines","back":"lines"},"vertices":"19","colors":"20","axes":{"mode":["pretty","pretty","pretty"],"step":[1,5,1],"nticks":[5,5,5],"marklen":[15,15,15],"expand":[1,1,1]},"draw_front":true,"flags":32769},"1":{"id":1,"type":"subscene","par3d":{"antialias":8,"FOV":30,"ignoreExtent":false,"listeners":1,"mouseMode":{"none":"none","left":"trackball","right":"zoom","middle":"fov","wheel":"pull"},"observer":[0,0,41.239875793457],"modelMatrix":[[2.35407447814941,0,0,-11.7703723907471],[0,0.214704245328903,1.76968514919281,-35.2798233032227],[0,-0.589895069599152,0.644112765789032,14.3935241699219],[0,0,0,1]],"projMatrix":[[3.73205065727234,0,0,0],[0,3.73205065727234,0,0],[0,0,-3.86370301246643,-148.664993286133],[0,0,-1,0]],"skipRedraw":false,"userMatrix":[[1,0,0,0],[0,0.342020143325668,0.939692620785909,0],[0,-0.939692620785909,0.342020143325668,0],[0,0,0,1]],"userProjection":[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],"scale":[2.35407447814941,0.62775319814682,1.8832596540451],"viewport":{"x":0,"y":0,"width":1,"height":1},"zoom":1,"bbox":[2.93333339691162,7.06666660308838,94.75,110.25,4.91666650772095,10.0833330154419],"windowRect":[0,0,256,256],"family":"sans","font":1,"cex":1,"useFreeType":true,"fontname":"NULL","maxClipPlanes":2147483647,"glVersion":"NA","activeSubscene":0},"embeddings":{"viewport":"replace","projection":"replace","model":"replace","mouse":"replace"},"objects":[6,8,7,9,10,11,12,5],"subscenes":[],"flags":34163}},"crosstalk":{"key":[],"group":[],"id":[],"options":[]},"width":672,"height":432,"context":{"shiny":false,"rmarkdown":"bookdown::gitbook"},"buffer":{"accessors":[{"bufferView":0,"componentType":5126,"count":12,"type":"VEC3"},{"bufferView":1,"componentType":5126,"count":12,"type":"VEC4"},{"bufferView":2,"componentType":5126,"count":12,"type":"VEC3"},{"bufferView":3,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":4,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":5,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":6,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":7,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":8,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":9,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":10,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":11,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":12,"componentType":5126,"count":24,"type":"VEC3"},{"bufferView":13,"componentType":5126,"count":1,"type":"VEC4"},{"bufferView":14,"componentType":5126,"count":12,"type":"VEC3"},{"bufferView":15,"componentType":5126,"count":1,"type":"VEC4"},{"bufferView":16,"componentType":5121,"count":1,"type":"VEC3"},{"bufferView":17,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":18,"componentType":5121,"count":1,"type":"VEC3"},{"bufferView":19,"componentType":5126,"count":15,"type":"VEC3"},{"bufferView":20,"componentType":5121,"count":1,"type":"VEC4"}],"bufferViews":[{"buffer":0,"byteLength":144,"byteOffset":0},{"buffer":0,"byteLength":192,"byteOffset":144},{"buffer":0,"byteLength":144,"byteOffset":336},{"buffer":0,"byteLength":12,"byteOffset":480},{"buffer":0,"byteLength":4,"byteOffset":492},{"buffer":0,"byteLength":12,"byteOffset":496},{"buffer":0,"byteLength":12,"byteOffset":508},{"buffer":0,"byteLength":4,"byteOffset":520},{"buffer":0,"byteLength":12,"byteOffset":524},{"buffer":0,"byteLength":12,"byteOffset":536},{"buffer":0,"byteLength":4,"byteOffset":548},{"buffer":0,"byteLength":12,"byteOffset":552},{"buffer":0,"byteLength":288,"byteOffset":564},{"buffer":0,"byteLength":16,"byteOffset":852},{"buffer":0,"byteLength":144,"byteOffset":868},{"buffer":0,"byteLength":16,"byteOffset":1012},{"buffer":0,"byteLength":3,"byteOffset":1028},{"buffer":0,"byteLength":4,"byteOffset":1031},{"buffer":0,"byteLength":3,"byteOffset":1035},{"buffer":0,"byteLength":180,"byteOffset":1040},{"buffer":0,"byteLength":4,"byteOffset":1220}],"buffers":[{"byteLength":1224,"bytes":"AADAQAAAvkIAAKBAAADgQAAAvkIAAOBAAADQQAAAvkIAAMBAAACgQAAAyEIAAMBAAACwQAAA\nyEIAAABBAACwQAAAyEIAAOBAAACQQAAA0kIAAABBAACgQAAA0kIAABBBAACQQAAA0kIAAOBA\nAABAQAAA3EIAAABBAACAQAAA3EIAACBBAABgQAAA3EIAABBBAAAAAMnIyD4AAAAAAACAPwAA\nAADJyMg+AAAAAAAAgD8AAAAAycjIPgAAAAAAAIA/AAAAAAAAAAAAAIA/AACAPwAAAAAAAAAA\nAACAPwAAgD8AAAAAAAAAAAAAgD8AAIA/AACAP6alJT8AAAAAAACAPwAAgD+mpSU/AAAAAAAA\ngD8AAIA/pqUlPwAAAAAAAIA/AACAPwAAAAAAAAAAAACAPwAAgD8AAAAAAAAAAAAAgD8AAIA/\nAAAAAAAAAAAAAIA/AADAQAAAvkIAAKBAAADgQAAAvkIAAOBAAADQQAAAvkIAAMBAAACgQAAA\nyEIAAMBAAACwQAAAyEIAAABBAACwQAAAyEIAAOBAAACQQAAA0kIAAABBAACgQAAA0kIAABBB\nAACQQAAA0kIAAOBAAABAQAAA3EIAAABBAACAQAAA3EIAACBBAABgQAAA3EIAABBBAADAfwAA\ngEAAAIA/AAAAAQAAwH8AAIBAAACAPwAAwH8AAIBAAACAPwAAAAEAAMB/AACAQAAAgD8AAMB/\nAACAQAAAgD8AAAABAADAfwAAgEAAAIA/AADAQAAAvkIAAKBAAADAQAAAvkIAAKBAAADgQAAA\nvkIAAOBAAADgQAAAvkIAAKBAAADQQAAAvkIAAMBAAADQQAAAvkIAAKBAAACgQAAAyEIAAMBA\nAACgQAAAyEIAAKBAAACwQAAAyEIAAABBAACwQAAAyEIAAKBAAACwQAAAyEIAAOBAAACwQAAA\nyEIAAKBAAACQQAAA0kIAAABBAACQQAAA0kIAAKBAAACgQAAA0kIAABBBAACgQAAA0kIAAKBA\nAACQQAAA0kIAAOBAAACQQAAA0kIAAKBAAABAQAAA3EIAAABBAABAQAAA3EIAAKBAAACAQAAA\n3EIAACBBAACAQAAA3EIAAKBAAABgQAAA3EIAABBBAABgQAAA3EIAAKBAv74+P7++Pj+/vj4/\nmZiYPgAAwEAAAL5CAACgQAAA4EAAAL5CAADAQAAA0EAAAL5CAACwQAAAoEAAAMhCAACwQAAA\nsEAAAMhCAADQQAAAsEAAAMhCAADAQAAAkEAAANJCAADQQAAAoEAAANJCAADgQAAAkEAAANJC\nAADAQAAAQEAAANxCAADQQAAAgEAAANxCAADwQAAAYEAAANxCAADgQJmYmD6ZmJg+mZiYPgAA\ngD8AAAABAQEBAAAAAAAAAEBAAADAfwAAwH8AAIBAAADAfwAAwH8AAKBAAADAfwAAwH8AAMBA\nAADAfwAAwH8AAOBAAADAfwAAwH8AAMB/AAC+QgAAwH8AAMB/AADIQgAAwH8AAMB/AADSQgAA\nwH8AAMB/AADcQgAAwH8AAMB/AADAfwAAoEAAAMB/AADAfwAAwEAAAMB/AADAfwAA4EAAAMB/\nAADAfwAAAEEAAMB/AADAfwAAEEEAAMB/AADAfwAAIEEAAAAB"}]},"players":[],"webGLoptions":{"preserveDrawingBuffer":true}},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figuur 6.3: Een positief verband tussen tussen het aantal studie-uur en toets-score, na (met) correctie voor IQ
</p>
</div>
<p>(Nu we enkelvoudige lineaire regressie-analyse achter de rug hebben, heb je de basis overwonnen. Echt, heel veel analyses in de statistiek zĳn eigenlĳk alleen maar generalisaties of uitbreidingen
van wat je in hoofdstuk 5 geleerd hebt, enkelvoudige regressie analyse. In dit hoofdstuk gaan we proberen om een nog beter
model te bouwen door één of meer predictoren toe te voegen aan ons model. We krĳgen dus
een complexer model dan een enkelvoudig regressie-model (met slechts één predictor). Complexere modellen, dus met
meer predictoren, voorspellen over het algemeen beter dan eenvoudigere modellen. Althans,
dit is waar, onder twee voorwaarden. Als eerste moet het eenvoudigere model niet al honderd
procent van de te verklaren variabele verklaren, want dan is er geen verbetering meer mogelĳk.
En als tweede geldt dit alleen altĳd voor je steekproef. Dus complexere modellen kunnen bĳna
altĳd de afhankelĳke variabelen beter verklaren binnen je steekproef, maar of die verbetering in
voorspelkracht ook generaliseerbaar is naar de populatie is nog maar de vraag. De verbetering in
voorspelling is alleen generaliseerbaar naar de populatie als de toename in proportie verklaarde
variantie, ook daadwerkelĳk significant is. De variatie in lengte scores van onze aapjes konden
wĳ voor 80 procent verklaren aan de hand van verschillen in hun leeftĳden. Dus M1 (het
enkelvoudige regressie-model) verklaarde 80 procent meer dan M0, het nulmodel. Het nulmodel
(het grote gemiddelde qua lengte) verklaart natuurlĳk helemaal niets van de variatie, nul
procent dus. Wĳ gaan M2 bouwen, een multipel regressie-model met twee predictoren, namelĳk
leeftĳd en het aantal bananen dat een aap per dag eet. Ik noem deze tweede variabele kortweg
‘banaan’. Voor onze aapjes zal dit model dus wel beter zĳn dan het model dat alleen gebaseerd is
op de variabele leeftĳd. Maar of het dus ook significant beter voorspelt, valt dus nog te bezien en
zal getoetst moeten worden. Gaan we doen!</p>
<p>Y</p>
<p>figuur 6A</p>
<p>X2</p>
<p>108</p>
<p>lengte (y)</p>
<p>Handleiding statistiek I</p>
<p>X1</p>
<p>6§1
Van een twee-dimensionale
wereld naar een driedimensionale wereld.</p>
<p>Tot zover hebben we alleen te maken gehad met twee variabelen, dus twee dimensies. Als we
grafisch het verband tussen leeftĳd en lengte willen laten zien, hebben we alleen een x en een
y as nodig om een puntenwolk te plotten. Om een x en een y as te tekenen, heb je alleen een
plat vlak nodig. Het enige wat je in dit geval hoeft te doen, is te beginnen met een willekeurige
rechte lĳn. Het maakt eigenlĳk niet uit waar, of hoe je die tekent, zolang die maar recht is. Dit
is je eerste as. Vervolgens teken je een tweede lĳn die precies een hoek maakt van 90 graden
met de eerste as. Als twee lĳnen een hoek van 90 graden met elkaar maken, zeggen we ook
wel dat ze orthogonaal staan ten opzichte van elkaar. Als je vervolgens een schaalverdeling
kiest (de meeteenheid per variabele), kun je je twee-assig stelsel afmaken en elk punt van je
puntenwolk – qua positie – definiëren. Dit doe je door voor elk punt (behorend tot een aapje) de
twee bĳbehorende coördinaten te geven, dus zĳn leeftĳd en lengte. Zodra er een derde dimensie
bĳkomt, moeten we dus eigenlĳk van het papier af want we willen dat de derde as ook een hoek
maakt van 90 graden met de twee andere assen. Als je aan een kubus denkt ben je dus al een
heel eind. Een kubus heeft drie dimensies (lengte, breedte (of diepte) en de hoogte). Een drieassig stelsel zonder de eenheden per variabele (x1, x2, y)zie je in figuur 6A. Je zou dus eigenlĳk
moeten denken dat de nieuwe as (de x2 as) uit het papier zou moeten komen. Gelukkig kennen
de meesten van ons de 3D-films van de bioskoop en weten we allemaal hoe het voelt als de
suggestie wordt gewekt, dat er meer is dan een plat beeld. Suggestie doet leven.</p>
<p>lengte (y)</p>
<p>Aan de hand van ons drie assig stelsel, kunnen we dus weer elk punt een positie geven in
onze drie-dimensionale wereld als we weten wat een aapje, op de drie variabelen scoort. De
predictor ‘leeftĳd’ kennen we toe aan de x1-as, de tweede predictor, ‘banaan’, aan de x2-as, en
de afhankelĳke variabele ‘lengte’ aan de y-as. In figuur 6B heb ik ook vast het punt voor aapje
nummer 9 gezet, (2.0, 8, 180).</p>
<p>figuur 6B</p>
<p>aapje 9 (2.0, 8, 180)</p>
<p>2</p>
<p>leeftijd (x1)</p>
<p>ba</p>
<p>na</p>
<p>an
(x</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>.</p>
<p>109</p>
<p>.</p>
<p>.</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>figuur 6C</p>
<p>lengte (y)</p>
<p>hoofdstuk 6 / Meervoudige Lineaire Regressie-Analyse.</p>
<p>In figuur 6C heb ik alle bĳbehorende punten gezet, een echte drie-dimensionale puntenwolk dus
(de suggestie is echt, want het is nog steeds op een plat vlak getekend!).</p>
<p>9
8
7
5</p>
<p>6
3</p>
<p>2</p>
<p>2</p>
<p>4</p>
<p>1</p>
<p>leeftijd (x1)
.</p>
<p>.</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>ba</p>
<p>na</p>
<p>an</p>
<p>(x</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>.</p>
<p>Omdat we nu met meerdere voorspellers te maken hebben, ziet het regressie-model er niet
meer uit als een rechte lĳn door een platte puntenwolk (de regressielĳn). In het geval van twee
predictoren hebben we te maken met een regressie-vlak, zie figuur 6D.</p>
<p>Handleiding statistiek I</p>
<p>Dit vlak moet zo dicht mogelĳk bĳ elk puntje liggen, of omgedraaid: alle observaties moeten,
gemiddeld gezien, zo dicht mogelĳk bĳ het regressie-vlak liggen. Net zoals bĳ enkelvoudige
regressie-analyse, gaat het er om dat de verticale afstand van een observatie naar het regressievlak – een residu of error dus – gemiddeld gezien, zo klein mogelĳk is, zie figuur 6E (pagina 112).
Mocht je nog meer predictoren toevoegen aan een model, dan wordt het wel heel moeilĳk
om daar nog een grafische voorstelling van te maken. In 4 (of meer) dimensionale ruimtes
kunnen we prima berekeningen uitvoeren en dus ook modelleren of voorspellen, maar om er
nog een grafische voorstelling van te maken, gaat de meesten boven hun pet en is ook niet
nodig. Het gaat immers puur om de voorspelling en dat gaat gewoon aan de hand van een
regressievergelĳking! Omdat we nu extra voorspellers gebruiken, is de vergelĳking alleen wat
langer. In het bĳzondere geval van twee predictoren kunnen we de voorspelde waarde van
lengte (ŷi) als volgt uitdrukken:
Ŷi = b0 + b1·Xi1 + b2·Xi2
110</p>
<p>lengte (y)</p>
<p>figuur 6D</p>
<p>9
8
7
5</p>
<p>6
3</p>
<p>2</p>
<p>2</p>
<p>4</p>
<p>1</p>
<p>leeftijd (x1)
.</p>
<p>.</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>ba</p>
<p>na</p>
<p>an</p>
<p>(x</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>.</p>
<p>Y-dakje is weer de voorspelde waarde en is dus gelĳk aan wat er rechts van het is-gelĳk-teken
staat. Maar wat staat er eigenlĳk aan de rechterkant? Is het een som of een produkt? Het is
een Som van drie termen, want we tellen drie dingen op, namelĳk het intercept en iets met x1
en x2. Het is niet zomaar een som, het is namelĳk een gewogen som. Een gewogen som kennen
jullie allemaal! Want iedereen van jullie kan zĳn eindcĳfer voor een vak berekenen, ook als
jullie verteld wordt dat het tentamen cĳfer twee keer zo zwaar meetelt als de inleveropdracht
bĳvoorbeeld. Ook hier bereken je een gewogen som of een gewogen gemiddelde (is wiskundig
gezien precies het zelfde). Aan de ‘regressie-gewichten’ b1 en b2, kun je zien (als je hun
numerieke waarden kent) hoe zwaar x1 en x2 meetellen voor de voorspelling van y. En mocht
je met meer dan twee predictoren te maken hebben, kun je de regressie-vergelĳking gewoon
uitbreiden:
Ŷi = b0 + b1·Xi1 + b2·Xi2 + b3·Xi3 …… + bj·Xij
Omdat we de letter i al hadden weggegeven aan case (of respondent) nummer, nummeren we
de predictors, met de letter j. En we zeggen ook wel (als je nog niet weet hoeveel predictoren je
gaat gebruiken) dat je dus een regressie analyse doet met ‘J’ predictoren. We geven de slope,
behorende bĳ één bepaalde predictor, het zelfde nummer als dat de predictor heeft gekregen.
Omdat wĳ maar twee predictoren hebben (‘leeftĳd’ en ‘banaan’) heeft ‘J’ ook wel de waarde 2.
Als je dus een voorspelling wil doen voor case nummer i, dan heb je voor elke predictor (tot en
met de J-de, dus voor predictor j=1 en j=2 bĳ ons) de scores nodig van case i. Die waarden vul je
dan in, in de regressievergelĳking en dan kun je uitrekenen, wat zĳn score op de afhankelĳke
111</p>
<p>lengte (y)</p>
<p>hoofdstuk 6 / Meervoudige Lineaire Regressie-Analyse.</p>
<p>figuur 6E</p>
<p>9
8
7
5</p>
<p>6
3</p>
<p>2</p>
<p>2</p>
<p>4</p>
<p>1</p>
<p>leeftijd (x1)
.</p>
<p>.</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>ba</p>
<p>na</p>
<p>an</p>
<p>(x</p>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<p>.</p>
<p>variabele zou moeten zĳn (Ŷi), de voorspelde waarde. Je zal eerst natuurlĳk moeten weten wat
de waarden van je regressie-gewichten zĳn, anders valt er überhaupt weinig uit te rekenen qua
voorspelling.</p>
<p>Handleiding statistiek I</p>
<p>6§2
De berekening of schatting
van regressie-gewichten
(… not!).</p>
<p>Het berekenen van de regressie-gewichten (het intercept en de slopes) gaan we niet meer zelf
doen, we laten dit geheel over aan de statistiek programma’s (natuurlĳk kies je dan voor R of
RStudio). Hetzelfde geldt voor de standaard errors voor de regressie-gewichten, je hoeft je om
die berekeningen dus niet meer druk te maken. Maar je moet al de uitkomsten (berekende
waarden, de schattingen voor de parameters van je model) natuurlĳk wel begrĳpen! Daarom dus
al het voorgaande in deze verhandeling. Naarmate we vorderen in de statistiek, zullen we ons
dus steeds meer op de output (resultaten en uitkomsten) van zo’n statistiek programma richten.
Vervolgens interpreteren we de output en op basis daarvan trekken we dan conclusies over de
onderzoeksvragen die we proberen op te lossen. Je zult in dit hoofdstuk dus ook steeds minder
formules zien, omdat ik slechts de resultaten (uitkomsten) zal bespreken.
Eerlĳk gezegd, tĳdens mĳn studiejaren (die ik ontzettend mis), heb ik het vak ‘Mathematische
Statistiek’ gevolgd. Ik vond dat super ‘kicke’. Eindelĳk werd mĳ duidelĳk dat echte statistiek
helemaal geen wiskunde A is. Statistiek wordt bĳna altĳd met wiskunde A geassocieerd, je weet
wel, van die eindeloos lange verhaaltjes-sommen, vreselĳk. Bĳ Mathematische Statistiek moest
ik – gewoon zoals bĳ wis B – met een potlood en een gum – laten zien hoe je de oppervlakte
onder een curve (lĳntje) berekent (en dus niet opzoekt in je z-tabel, of je normalCDF op je ‘GR’
gebruikt (nee, niet normalPDF), ‘integreren’ dus. En dat de slope niks anders is dan een ‘afgeleide
functie’, ook wel ‘dy/dx’ voor diegenen die GR-afhankelĳk zĳn, het lĳkt wel de ‘Grote vriendelĳke
Reus tegenwoordig’. Hĳ mocht dan Grafisch, Vriendelĳk en gRoot zĳn, maar inzicht gaf hĳ alleen
aan die mensen, die er ‘klaar’ voor waren. Kortom, je bent nu klaar voor het ‘snelle’ werk, omdat
112</p>
<p>je de basis overleefd hebt. Dat hoop ik natuurlĳk, maar dat zal vooral van je aandacht - als
belangrĳkste predictor - afhangen.
Conclusie: we knallen de data in een programma (het importeren of inlezen van je data-set in je
statistiek-programma). Vervolgens vertellen we het programma dat we een regressie-analyse
willen doen, welke variabele de afhankelĳke variabele is voor ons model en dan welke variabelen
we als predictoren willen gebruiken. We doen immers een (Uni-Variate) Multiple Regression
Analysis (MRA). ‘Uni-Variaat’, omdat we slechts één criterium variabele hebben,‘lengte’ de
afhankelĳke variabele).’Multiple’, omdat we meer dan één predictor hebben (‘leeftĳd’ en
‘banaan’, de twee onafhankelĳke variabelen). En uiteindelĳk ‘Regression Analyse’, omdat we
the variatie in de geobserveerde scores van de variabele Y terug brengen naar Ŷ. En Y-dakje
drukken we dus weer uit in een gewogen som van X-en. Het regressie-model is nog steeds
lineair van aard, Y-dakje is een recht vlak in onze 3D grafiek. Dit vlak is zodanig gepositioneerd,
dat de verticale afstanden van de observatie naar het regressie-vlak, de residuen, gemiddeld
gezien zo klein mogelĳk zĳn. Het woord ‘Variaat’ op zich, mag niet onbesproken blĳven. De
‘Variaat’ staat voor Ŷ en is dus het regressie-model.
Als je databestand niet te groot is, krĳg je binnen één oogblink, de schattingen van je
parameters te zien (als je tenminste weet waar je moet zoeken in die output). Blink maar, en kĳk
dan naar tabel 6A.
tabel 6A</p>
<p>Drie Modellen voor de voorspelling van lengte</p>
<p>Afhankelijke variable: lengte</p>
<p>coefficient</p>
<p>Std. Error</p>
<p>t</p>
<p>p</p>
<p>&lt; .001</p>
<p>Model 0
R2 = .00</p>
<p>intercept only</p>
<p>b0</p>
<p>150.00</p>
<p>6.46</p>
<p>23.24</p>
<p>intercept</p>
<p>b0</p>
<p>90.00</p>
<p>11.75</p>
<p>7.66</p>
<p>&lt; .001</p>
<p>leeftijd</p>
<p>b1</p>
<p>40.00</p>
<p>7.56</p>
<p>5.29</p>
<p>.001</p>
<p>intercept</p>
<p>b0</p>
<p>78.44</p>
<p>9.43</p>
<p>8.31</p>
<p>&lt; .001</p>
<p>leeftijd</p>
<p>b1</p>
<p>35.05</p>
<p>5.72</p>
<p>6.12</p>
<p>&lt; .001</p>
<p>banaan</p>
<p>b2</p>
<p>3.72</p>
<p>1.35</p>
<p>2.75</p>
<p>.033</p>
<p>Model 1
R2 = .80</p>
<p>F(1,7) = 28.00, p = .001
Model 2
R2 = .91</p>
<p>F(2,6) = 30.90, p &lt; .001</p>
<p>113</p>
<p>hoofdstuk 6 / Meervoudige Lineaire Regressie-Analyse.</p>
<p>6§2
Interpretatie en evaluatie
van een multipele
regressie analyse in
stappen.
tabel 6B</p>
<p>Zoals je ziet, heb ik in tabel 6A ook de twee voorgaande modellen erbĳ gezet, het nul-model en
het model met één predictor (M1). Wĳ richten ons nu op het model met twee predictoren (M2),
namelĳk het model met ‘leeftĳd’ en ‘banaan’ als onafhankelĳke variabelen. De data waar dit
regressie-model op gebaseerd is, vind je in tabel 6B. In de kolom met Xi2, vind je nu ook het
‘aantal bananen’ dat een aapje per dag (gemiddeld) eet, onze tweede predictor dus.
i
1
2
3
4
5
6
7
8
9</p>
<p>Yi
120
130
140
140
150
160
160
170
180</p>
<p>Xi1
1.0
1.0
1.0
1.5
1.5
1.5
2.0
2.0
2.0</p>
<p>Xi2
2
4
6
6
5
7
4
4
8</p>
<p>Ŷi
120.92
128.35
135.78
153.31
149.59
157.02
163.4o
163.4o
178.26</p>
<p>(Yi – !)2
900
400
100
100
0
100
100
400
900</p>
<p>(Ŷi – !)2
845.76
468.72
202.15
10.92
0.17
49.29
179.45
179.45
798.63</p>
<p>Yi – Ŷi = ei
-0.92
1.65
4.22
-13.31
0.41
2.98
-3.40
6.60
1.74</p>
<p>(Yi – Ŷi)2 = e2i
0.84
2.72
17.79
177.02
0.17
8.87
11.53
43.61
3.02</p>
<p>sst = 3000</p>
<p>ssm = 2734.4</p>
<p>∑=0.0</p>
<p>sse = 265.60</p>
<p>Stap 1 De regressie-vergelĳking opstellen en interpreteren.
Voor ons model heeft het intercept (b0) een waarde van 78.44, de slope voor leeftĳd (b1) nu
een waarde van 35.05 en de slope voor banaan (b2) een waarde van 3.72. In deze tabel staan
trouwens afgeronde waarden, dus verdere berekeningen met deze waarden, zullen dus niet meer
heel precies zĳn en net iets anders kunnen zĳn dan als we met precieze waarden zouden verder
rekenen. Met deze drie (afgeronde) waarden kunnen we de regressie-vergelĳking opstellen:
Ŷi = 78.44 + 35.05·Xi1 + 3.72·Xi2</p>
<p>Handleiding statistiek I</p>
<p>Het intercept (b0 = 78.44) is de voorspelde waarde voor een aapje dat op beide voorspellers
precies een 0 scoort. In onze steekproef hebben we geen aapjes die nul scoren op beide
variabelen dus de vraag is wel of deze waarde reëel of relevant is, maar misschien wel de lengte
van een aapje als die net geboren is en nog geen bananen heeft gegeten. Beter meet je dat soort
aapjes en dan weet je het gewoon, het blĳft gevaarlĳk om buiten de range van jou gemeten
x-waarden een voorspelling te doen qua Y.
Het regressie-gewicht (of slope) toegekend aan leeftĳd (b1 = 35.05), vertelt ons hoeveel twee
aapjes van elkaar zouden moeten verschillen qua lengte als ze één eenheid verschillen qua
leeftĳd. Deze interpretatie geldt alleen onder constant houding van het aantal bananen, de
andere predictor. Anders gezegd, betekenen deze laatste twee zinnen, dat als je twee aapjes
neemt die hetzelfde aantal bananen eten, maar een jaar verschillen qua leeftĳd, zal het oudere
aapje wel 35.05 cm langer zĳn dan het jongere aapje.
Het regressie-gewicht toegekend aan de voorspeller ‘banaan’ (b2 = 3.72) betekent dus dat twee
aapjes die de zelfde leeftĳd hebben, maar wel 1 banaan verschillen, ongeveer 3.72 cm zullen
verschillen qua lengte. Waar bĳ het aapje dat één banaan meer eet, natuurlĳk langer zal zĳn
vanwege de positieve waarde van b2.
Stap 2 Voorspelde waarden uitrekenen.
Dus nu zien we eindelĳk wat de gewogen som van X1 en X2 is. Nog wat moeilĳker gezegd, Ŷi is te
schrĳven als (of is gelĳk aan) de ‘lineaire combinatie’ van X1 en X2. Als je nu per aapje de scores
op X1 en X2 invult, kun je uitrekenen wat zĳn lengte zou moeten zĳn volgens ons nieuwe model.
Deze predicted values vind je in de kolom met Ŷi. Ik laat de berekening één keer zien aan de hand
van aapje nummer negen.
Ŷ9 = 78.44 + 35.05·X91 + 3.72·X92
114</p>
<p>Aapje nummer 9 heeft op X1 een waarde van 2.0 en op X2 een 8, invullen geeft:
Ŷ9 = 78.44 + 35.05·2.0 + 3.72·8 = 178.26
Hĳ zou dus 178.26 cm lang moeten zĳn volgens ons model.
Stap 3 Kwadraten sommen uitreken.
Volgens het regressiemodel moet aapje nummer 9 dus 178.26 cm zĳn. In werkelĳkheid heeft
hĳ een lengte van 180. Het model heeft dit aapje dus nog maar 1.74 cm onderschat. Of anders
gezegd, dit aapje zit dus 1.74 cm boven zĳn voorspelling en deze waarde is dus gelĳk aan zĳn
error of residu:
ei = Yi – Ŷi
e9 = Y9 – Ŷ9
e9 = 180 – 178.26 = 1.74
De residuen vind je in de ener laatste kolom van tabel 6B en zouden natuurlĳk netjes tot nul
moeten optellen (als je heel precies zou zĳn en niet te veel afrond tussendoor). In de laatste
kolom staan de gekwadrateerde residuen, die je nodig hebt om sse te berekenen (door de
gekwadrateerde residuen op te tellen krĳg je de sum of squares due to error).
Om ssm (sum of squares due to model) te berekenen moet je eerst weer weten hoeveel ons model
(M2) de voorspelling heeft veranderd ten opzichte van het nul-model, voor aapje nummer 9:
Ŷi – Ȳ
De systematische verschuiving in voorspelling, invullen voor aapje negen:
Ŷ9 – Ȳ
178.26 – 150 = 28.26
Als deze waarde kwadrateert krĳg de waarde 798.63 (in de kolom waar je onderaan ook ssm
vindt) en de optelling (sommatie) van deze waarden leidt tot ssm.
Ook hier moet weer gelden dat de totale variatie in lengte scores (sst) op te delen is in een
gedeelte verklaard en een gedeelte onverklaard:
SST = SSM + SSE
in ons bĳzondere geval:
SST = 3000 = 2734.40 + 265.60
Stap 4 Bereken de proportie verklaarde variantie, de vaf.
We gaan over tot de berekening van ‘Multiple R2’. We noemen deze R2 ‘Multiple’, omdat we dus
met meerdere predictoren te maken hebben. We kĳken nu naar een multiple samenhang of
correlatie (Multiple R) omdat we kĳken naar het (gezamenlĳke) effect van enerzĳds x1 en x2 op
anderzĳds y. Maar voor de vaf (variance accounted for) geldt nog steeds de zelfde formule:
SSM
R2 = SST</p>
<p>115</p>
<p>hoofdstuk 6 / Meervoudige Lineaire Regressie-Analyse.</p>
<p>Voor ons model is dat dus:
SSM
R2y.x1x2 = SST
Met het subscript voor R^2 geef ik dus aan dat we y proberen te voorspellen op basis van x1 en x2.
R2y.x1x2 =</p>
<p>2734.40
= .91
3000</p>
<p>We kunnen nu zeggen dat ongeveer 91 procent van de totale variatie in lengte-scores, verklaard
kan worden door de (gezamenlĳke) variatie in de predictoren ‘leeftĳd’ en ‘banaan’. Slechts 9
procent blĳft onverklaard.
Stap 5 Het checken van aannames voor het uitvoeren en interpreren van je regressie-analyse.
Voor een multipele regressie-analyse zĳn er natuurlĳk weer een tal van aannames die je officieel
eerst dient te checken, net zoals bĳ enkelvoudige regressie. Zelfs nog meer dan bĳ enkelvoudige
regressie, zoals de afwezigheid van een te hoge correlatie tussen de predictoren. Mocht dit het
geval zĳn dan spreekt men van ‘multicollineariteit’. Maar voor nu, laten we die assumpties even
naast ons liggen en slaan we deze stap even over, dus voorlopig no worries.
Stap 6 Toetsing van het gehele model.
Bĳ een model met meerdere predictoren toets je altĳd het model eerst als geheel. Hierbĳ is de
vraag eigenlĳk of er iets aan de hand is (H1) of helemaal niets (H0). De nul-hypothese stelt dat
van de variatie in Y niets verklaard kan worden door de combinatie van x1 en x2, ook wel een
horizontaal regressie-vlak (voor elke waarden van de predictoren is het gemiddelde op y gelĳk).
In dit geval is de proportie verklaarde variantie dus 0:
H0 : r2y.x1x2 = 0</p>
<p>natuurlĳk gaan de uitspraken over de populatie.</p>
<p>H1 : r2y.x1x2 &gt; 0
De alternatieve hypothese ontkent natuurlĳk de H0 en zegt dat de proportie verklaarde variantie
groter is dan nul (kleiner dan nul kan niet). Om dit stelsel van hypothese te toetsen berekenen
we de bĳbehorende toets-statistiek (en p-waarde), in dit geval een F-waarde. In plaats van een
t-test doen we nu een F-test. Om de F-waarde uit te rekenen kun je dat op de volgende manier
doen (er zĳn heel veel manieren of formules om een F-waarde te bereken, maar ik geef je er dus
slechts één).
F=</p>
<p>R2 dferror
·
1 – R2 dfmodel</p>
<p>Met dfmodel = p, waarbĳ ‘p’ voor het aantal predictoren staat, dus 2 en dferror = n – p – 1 dus 9 – 2 – 1
= 6 en aangezien we R2 al gevonden hadden, kunnen we de boel invullen (ik gebruik nu de onafgeronde waarde voor R2:</p>
<p>Handleiding statistiek I</p>
<p>F=</p>
<p>6
.9115
· = 30.90
1 – .9115 2</p>
<p>We kunnen nu de bĳbehorende p-waarde (overschrĳdingskans of significantie) opzoeken
in de F-tabel. Om dit te doen moet je weer rekening houden met de degrees of freedom
(vrĳheidsgraden). Maar nu hebben we te maken met een koppel van vrĳheidsgraden, namelĳk
voor het model én voor de error. Respectievelĳk dus 2 en 6, we gaan de de p-waarde opzoeken
die hoort bĳ de F-verdeling voor 2 en 6 vrĳheidsgraden, 2 voor het model, en 6 voor de error, ook
wel F(2;6) = 30.90. Normaal rekent het statistiek-programma dat je gebruikt, de p-waarde uit.
116</p>
<p>Kĳk in de F-tabel en zoek eerst het aantal vrĳheidsgraden op voor de ‘teller’ (de numerator), je
gebruikt hier altĳd het aantal vrĳheidsgraden van het model voor (2 bĳ ons). Zoek vervolgens
naar het aantal vrĳheidsgraden op voor de ‘noemer’ (de denominator), hier gebruik je dus
altĳd de vrĳheidsgraden van de error voor (dus 6 bĳ ons). Vergelĳk dan onze F-waarde (30.90)
met de gegeven F-waarden uit de tabel. De F-tabel geeft als hoogste waarde 27.00 met een
bĳbehorende p-waarde (staart oppervlakte) van .001. Onze F-waarde is extremer en heeft dus
een kleiner staartje dan .001 en we kunnen dus concluderen dat:
F(2;6) = 30.90, p &lt; .001
Bĳ toetsing van een model mag je nooit de p-waarde verdubbelen (onze alternatieve hypothese
was immers éénzĳdig, een vaf kan alleen maar groter zĳn dan nul, niet kleiner). En omdat onze
p-waarde veel kleiner is dan a = .05, moeten we de H0 verwerpen en kunnen we concluderen
dat R2 in onze steekproef, significant afweek van nul, en dat in de populatie dat dus ook wel het
geval zal zĳn (r2). Jippie!
Stap 7 Significantie per predictor, toetsing van de slopes.
Nu we weten dat er echt iets aan de hand is (een gedeelte van de variatie in y wordt verklaard),
willen ook weten hoe dat komt. Ligt dit aan de variabele ‘leeftĳd’ of aan de twee predictor
‘banaan’ of aan een combinatie van de twee? Om dit te beoordelen kĳken we naar de
significanties van de twee regressie-gewichten - of mischien iets meer van deze tĳd - naar de
betrouwbaarheidsintervallen. Ik kan dus eigenlĳk gewoon refereren naar het vorige hoofdstuk,
want dat heb ik daar al uitgelegd. Maar ik loop er even snel doorheen.
Om een uitspraak te doen over de significatie per predictor (of hun slope dus significant afwĳkt
van nul en generaliseerbaar is naar de populatie slopes), bereken je eerst de bĳbehorende toetsstatistiek. We toetsen de slopes nog steeds a.d.h.v. de t-verdeling en je gebruikt het aantal
vrĳheidsgraden van de error dferror = n – p – 1. In het algemeen, voor de j-de predictor bereken je
de t-waarde als volgt:
tdf=n–p–1 =
t(6) =</p>
<p>bj
SEbj</p>
<p>voor de variabel leeftĳd wordt dat:</p>
<p>b1
= 35.046 / 7.724 = 6.12
SEb1</p>
<p>en bĳbehorende tweezĳdige p-waarde opzoeken leidt tot:
t(6) = 6.12, p &lt; .001
Dus aannemen dat leeftĳd wel degelĳk een positief effect heeft op lengte. Voor de variabele
‘banaan’ volgen we dezelfde procedure (ik gebruik weer preciezere getalletjes):
t(6) =</p>
<p>b2
= 3.716 / 1.352 = 2.75
SEb2</p>
<p>Voor de predictor ‘banaan’ kunnen we dus ook concluderen dat het effect op lengte significant
is (t(6) = 2.75, .02 &lt; p &lt; .04) en we kunnen dus concluderen dat ‘meer bananen’ ook echt met een
hogere lengte kan worden geassocieerd.</p>
<p>117</p>
<p>hoofdstuk 6 / Meervoudige Lineaire Regressie-Analyse.</p>
<p>Rapportage (bĳvoorbeeld):
Om te onderzoeken of de lengte van een aapje voorspeld of verklaard kan worden op basis van
de leeftĳd en het aantal bananen dat een aapje per dag eet is een multipele regressie-analyse
uitgevoerd. De twee predictoren (‘leeftĳd’ en ‘banaan’) tezamen bleken 91 procent van de totale
variatie in lengte scores te kunnen verklaren. Deze vaf ,was significant (R2 = .91, F(2;6) = 30.90,
p &lt; .001), waardoor we kunnen aannemen dat model generaliseerbaar is naar de populatie
aapjes. Verder hadden beide predictoren een positief effect op de lengte. De slope voor leeftĳd
week significant af van 0 (b1 = 35.05, t(6) = 6.12, p &lt; .001). Op basis van deze uitkomst kunnen we
concluderen dat aapjes die ouder zĳn, ook daadwerkelĳk met een langere lengte geassocieerd
kunnen worden. Ook het effect van de variabele ‘banaan’ was significant (b2 = 3.72, t(6) = 2.75,
.02 &lt; p &lt; .04) Al met al is het dus handig om beide variabelen te gebruiken wanneer men lengtescores wil voorspellen vanwege de significante multiple samenhang.</p>
<p>Handleiding statistiek I</p>
<p>Officieel zĳn er nog veel meer ‘ditjes en datjes’ bĳ het doen van een multipele regressie-analyse,
maar gezien dit een introductie-cursus is, laten we het hierbĳ. De kleinste aap wenst je een heel
fĳn Inzicht!</p>
<p>118</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": [["Handleiding_Statistiek_met_JASP.pdf", "PDF"]],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
