<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, Descriptive Statistics. | Handleiding Statistiek met JASP</title>
  <meta name="description" content="1 Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, Descriptive Statistics. | Handleiding Statistiek met JASP" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, Descriptive Statistics. | Handleiding Statistiek met JASP" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, Descriptive Statistics. | Handleiding Statistiek met JASP" />
  
  
  

<meta name="author" content="Benjamin Telkamp" />


<meta name="date" content="2021-11-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hoofdstuk-0.html"/>
<link rel="next" href="hoofdstuk-2---de-normaalverdeling..html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-0.108.3.2/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-0.108.3.2/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-0.108.3.2/rglClass.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/utils.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/buffer.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/subscenes.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/shaders.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/textures.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/projection.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/mouse.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/init.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/pieces.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/draw.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/controls.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/selection.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/rglTimer.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/pretty.src.js"></script>
<script src="libs/rglwidgetClass-0.108.3.2/axes.src.js"></script>
<script src="libs/CanvasMatrix4-0.108.3.2/CanvasMatrix.src.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
<script data-goatcounter="https://countcamp.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Voorwoord</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html"><i class="fa fa-check"></i>Hoofdstuk 0</a>
<ul>
<li class="chapter" data-level="0.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#handleiding-der-handleidingen-en-het-absoluut-minimale-dat-je-móet-weten."><i class="fa fa-check"></i><b>0.1</b> Handleiding der Handleidingen en het absoluut minimale dat je móet weten.</a>
<ul>
<li class="chapter" data-level="0.1.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#de-essentie-van-waar-we-mee-bezig-zĳn-in-het-leven-én-in-de-wetenschap."><i class="fa fa-check"></i><b>0.1.1</b> De essentie van waar we mee bezig zĳn, in het leven én in de wetenschap.</a></li>
<li class="chapter" data-level="0.1.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#aapjes"><i class="fa fa-check"></i><b>0.1.2</b> Aapjes</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#onderzoek-en-aantal-algemene-definities-voordat-we-aan-de-slag-gaan-met-het-echte-rekenwerk-het-absoluut-minimale-dus."><i class="fa fa-check"></i><b>0.2</b> Onderzoek en aantal algemene definities voordat we aan de slag gaan met het echte rekenwerk, het absoluut minimale dus.</a></li>
<li class="chapter" data-level="0.3" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#rekenen-aan-apen."><i class="fa fa-check"></i><b>0.3</b> Rekenen aan Apen.</a>
<ul>
<li class="chapter" data-level="0.3.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#waarnemingen-samenvatten-aan-de-hand-van-statistieken."><i class="fa fa-check"></i><b>0.3.1</b> Waarnemingen samenvatten aan de hand van statistieken.</a></li>
<li class="chapter" data-level="0.3.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#de-berekening-van-het-gemiddelde-voor-een-variabele."><i class="fa fa-check"></i><b>0.3.2</b> De berekening van het gemiddelde voor een variabele.</a></li>
<li class="chapter" data-level="0.3.3" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#de-berekening-van-de-variantie-en-de-standaardafwijking"><i class="fa fa-check"></i><b>0.3.3</b> De berekening van de Variantie en de Standaardafwijking</a>
<ul>
<li class="chapter" data-level="0.3.3.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#rekenregels-en-volgorde-van-toepassing"><i class="fa fa-check"></i><b>0.3.3.1</b> Rekenregels en volgorde van toepassing</a></li>
</ul></li>
<li class="chapter" data-level="0.3.4" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#minimale-oefening"><i class="fa fa-check"></i><b>0.3.4</b> Minimale Oefening</a></li>
</ul></li>
<li class="chapter" data-level="0.4" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#meetniveaus-van-variabelen"><i class="fa fa-check"></i><b>0.4</b> Meetniveaus van variabelen</a>
<ul>
<li class="chapter" data-level="0.4.1" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#nominaal"><i class="fa fa-check"></i><b>0.4.1</b> Nominaal</a></li>
<li class="chapter" data-level="0.4.2" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#ordinaal"><i class="fa fa-check"></i><b>0.4.2</b> Ordinaal</a></li>
<li class="chapter" data-level="0.4.3" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#interval"><i class="fa fa-check"></i><b>0.4.3</b> Interval</a></li>
<li class="chapter" data-level="0.4.4" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#ratio"><i class="fa fa-check"></i><b>0.4.4</b> Ratio</a></li>
<li class="chapter" data-level="0.4.5" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#absoluut"><i class="fa fa-check"></i><b>0.4.5</b> Absoluut</a></li>
<li class="chapter" data-level="0.4.6" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#het-negeren-van-hogere-meetniveaus."><i class="fa fa-check"></i><b>0.4.6</b> Het negeren van hogere meetniveaus.</a></li>
<li class="chapter" data-level="0.4.7" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#andere-soorten-indelingen-dan-het-meetniveau-voor-soorten-variabelen"><i class="fa fa-check"></i><b>0.4.7</b> Andere soorten indelingen (dan het meetniveau) voor soorten variabelen</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#het-beschrĳven-van-data-aan-de-hand-statistieken-en-parameters"><i class="fa fa-check"></i><b>0.5</b> Het Beschrĳven van Data aan de hand Statistieken en Parameters</a></li>
<li class="chapter" data-level="0.6" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#het-grotere-doel-lekker-significant."><i class="fa fa-check"></i><b>0.6</b> Het Grotere Doel (Lekker Significant).</a></li>
<li class="chapter" data-level="0.7" data-path="hoofdstuk-0.html"><a href="hoofdstuk-0.html#rekenen-met-jasp"><i class="fa fa-check"></i><b>0.7</b> Rekenen met JASP</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><i class="fa fa-check"></i><b>1</b> Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, <em>Descriptive Statistics</em>.</a>
<ul>
<li class="chapter" data-level="1.1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#waar-ligt-de-data"><i class="fa fa-check"></i><b>1.1</b> Waar ligt de Data?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#belgedrag-onder-jongeren-in-nederland"><i class="fa fa-check"></i><b>1.1.1</b> Belgedrag onder Jongeren in Nederland</a></li>
<li class="chapter" data-level="1.1.2" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#opgaven-belgedrag-onder-jongeren-in-nederland-beschrijven"><i class="fa fa-check"></i><b>1.1.2</b> <em>Opgaven</em> Belgedrag onder Jongeren in Nederland: Beschrijven</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#hoe-is-de-data-verdeeld-spreidingsmaten."><i class="fa fa-check"></i><b>1.2</b> Hoe is de data verdeeld? Spreidingsmaten.</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html"><a href="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics..html#opgaven-belgedrag-onder-jongeren-in-nederland-spreidingsmaten"><i class="fa fa-check"></i><b>1.2.1</b> <em>Opgaven</em> Belgedrag onder Jongeren in Nederland: Spreidingsmaten</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html"><i class="fa fa-check"></i><b>2</b> Hoofdstuk 2 - De Normaalverdeling.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#scores-zijn-verdeeld-verschillende-vormen-van-verdelingen."><i class="fa fa-check"></i><b>2.1</b> Scores zijn verdeeld, verschillende vormen van verdelingen.</a></li>
<li class="chapter" data-level="2.2" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#de-normaalverdeling-sommige-scores-volgen-een-normaalverdeling"><i class="fa fa-check"></i><b>2.2</b> De Normaalverdeling, Sommige Scores Volgen een Normaalverdeling</a></li>
<li class="chapter" data-level="2.3" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#opgaven-verdelingen"><i class="fa fa-check"></i><b>2.3</b> <em>Opgaven</em> Verdelingen</a></li>
<li class="chapter" data-level="2.4" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#variabelen-in-de-steekproef-en-parameters-in-de-populatie"><i class="fa fa-check"></i><b>2.4</b> Variabelen in de Steekproef en Parameters in de Populatie</a></li>
<li class="chapter" data-level="2.5" data-path="hoofdstuk-2---de-normaalverdeling..html"><a href="hoofdstuk-2---de-normaalverdeling..html#opgaven-variabelen-en-parameters"><i class="fa fa-check"></i><b>2.5</b> <em>Opgaven</em> Variabelen en Parameters</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><i class="fa fa-check"></i><b>3</b> Hoofdstuk 3 - Samenhang tussen 2 variabelen, correlatie.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#correlatie"><i class="fa fa-check"></i><b>3.1</b> Correlatie</a></li>
<li class="chapter" data-level="3.2" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#verband-in-woorden"><i class="fa fa-check"></i><b>3.2</b> Verband in woorden</a></li>
<li class="chapter" data-level="3.3" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#predictor-criterium-respons"><i class="fa fa-check"></i><b>3.3</b> Predictor, criterium, respons</a></li>
<li class="chapter" data-level="3.4" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#het-verband-grafisch-weergeven."><i class="fa fa-check"></i><b>3.4</b> Het verband grafisch weergeven.</a></li>
<li class="chapter" data-level="3.5" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#covariantie-en-pearson-correlatie"><i class="fa fa-check"></i><b>3.5</b> Covariantie en Pearson Correlatie</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#covariantie-als-ongestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen"><i class="fa fa-check"></i><b>3.5.1</b> Covariantie als ongestandaardiseerde maat voor het verband tussen twee variabelen</a></li>
<li class="chapter" data-level="3.5.2" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#correlatiecoëfficiënt-de-pearson-correlatie-als-gestandaardiseerde-maat-voor-het-verband-tussen-twee-variabelen."><i class="fa fa-check"></i><b>3.5.2</b> Correlatiecoëfficiënt, de Pearson Correlatie als gestandaardiseerde maat voor het verband tussen twee variabelen.</a></li>
<li class="chapter" data-level="3.5.3" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#andere-manieren-om-de-pearson-correlatie-uit-te-rekenen."><i class="fa fa-check"></i><b>3.5.3</b> Andere manieren om de Pearson Correlatie uit te rekenen.</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html"><a href="hoofdstuk-3---samenhang-tussen-2-variabelen-correlatie..html#lekker-belangrijk"><i class="fa fa-check"></i><b>3.6</b> Lekker Belangrijk</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><i class="fa fa-check"></i><b>4</b> Hoofdstuk 4 - Van Steekproef naar Populatie. Generalisatie van Statistieken naar Parameters aan de hand van Betrouwbaarheidsintervallen en Significantie-toetsen.</a>
<ul>
<li class="chapter" data-level="4.1" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#populaties-kun-je-niet-meten-steekproeven-wel."><i class="fa fa-check"></i><b>4.1</b> Populaties kun je niet meten, steekproeven wel.</a></li>
<li class="chapter" data-level="4.2" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#de-steekproevenverdeling."><i class="fa fa-check"></i><b>4.2</b> De steekproe<strong>ven</strong>verdeling.</a></li>
<li class="chapter" data-level="4.3" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#standaard-normaalverdeling-voor-steekproefgemiddelden-overliney."><i class="fa fa-check"></i><b>4.3</b> Standaard Normaalverdeling voor Steekproefgemiddel<strong>den</strong>, <span class="math inline">\(\overline{Y}\)</span>.</a></li>
<li class="chapter" data-level="4.4" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#students-t-verdeling-voor-steekproefgemiddelden-overliney."><i class="fa fa-check"></i><b>4.4</b> <em>Student’s</em> <span class="math inline">\(t\)</span>-verdeling voor Steekproefgemiddel<em>den</em>, <span class="math inline">\(\overline{Y}\)</span>.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#betrouwbaarheidsintervallen-voor-een-populatiegemiddelde."><i class="fa fa-check"></i>Betrouwbaarheidsintervallen voor een populatiegemiddelde.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#toetsing-van-een-idee-aan-de-hand-van-een-stelsel-van-hypotheses."><i class="fa fa-check"></i>Toetsing van een idee aan de hand van een stelsel van Hypotheses.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#tweezijdige-toetsing"><i class="fa fa-check"></i>Tweezijdige Toetsing</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#type-i-en-ii-fouten"><i class="fa fa-check"></i>Type I en II Fouten</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#conclusie-aan-de-hand-van-je-toetsings-resultaat."><i class="fa fa-check"></i>Conclusie aan de hand van je toetsings-resultaat.</a></li>
<li><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#when-p-is-low-h-o-must-go">When <em>p</em> is Low, H-O must Go!</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#eénzijdige-toetsing"><i class="fa fa-check"></i>Eénzijdige Toetsing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#significantietoetsen-en-betrouwbaarheidsintervallen"><i class="fa fa-check"></i><b>4.5</b> Significantietoetsen en Betrouwbaarheidsintervallen</a></li>
<li class="chapter" data-level="4.6" data-path="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html"><a href="hoofdstuk-4---van-steekproef-naar-populatie.-generalisatie-van-statistieken-naar-parameters-aan-de-hand-van-betrouwbaarheidsintervallen-en-significantie-toetsen..html#significantie-toets-voor-verband-de-pearson-correlatie"><i class="fa fa-check"></i><b>4.6</b> Significantie Toets voor Verband, de Pearson Correlatie</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><i class="fa fa-check"></i><b>5</b> Hoofdstuk 5 - Enkelvoudige Lineaire Regressie-Analyse.</a>
<ul>
<li class="chapter" data-level="5.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-voorspelling-van-een-belangrĳke-variabele-op-basis-van-één-andere-toch-óók-wel-een-beetje-belangrĳke-variabele."><i class="fa fa-check"></i><b>5.1</b> De voorspelling van een belangrĳke variabele op basis van één andere (toch óók wel een beetje belangrĳke) variabele.</a></li>
<li class="chapter" data-level="5.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#beter-voorspellen-aan-de-hand-van-een-lineaire-vergelĳking-formule."><i class="fa fa-check"></i><b>5.2</b> Beter Voorspellen aan de Hand van een Lineaire Vergelĳking (Formule).</a></li>
<li class="chapter" data-level="5.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-enkelvoudige-lineaire-regressie-vergelĳking-de-regressie-lĳn"><i class="fa fa-check"></i><b>5.3</b> De Enkelvoudige Lineaire Regressie-vergelĳking, de Regressie-lĳn</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#slope-en-intercept-old-school"><i class="fa fa-check"></i><b>5.3.1</b> Slope en Intercept, Old School</a></li>
<li class="chapter" data-level="5.3.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#slope-en-intercept-for-real"><i class="fa fa-check"></i><b>5.3.2</b> Slope en Intercept, For Real</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#voorspelkracht"><i class="fa fa-check"></i><b>5.4</b> Voorspelkracht</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#het-spel-bij-regressie"><i class="fa fa-check"></i><b>5.4.1</b> Het Spel bij Regressie</a></li>
<li class="chapter" data-level="5.4.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdeling-van-totale-afwijking-in-model-en-error-per-individu"><i class="fa fa-check"></i><b>5.4.2</b> Opdeling van Totale Afwijking in Model en Error per Individu</a></li>
<li class="chapter" data-level="5.4.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdeling-van-totale-variatie-in-model-variatie-en-error-variatie"><i class="fa fa-check"></i><b>5.4.3</b> Opdeling van Totale Variatie in Model Variatie en Error Variatie</a>
<ul>
<li class="chapter" data-level="5.4.3.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#sum-of-squares-voor-total-model-en-error"><i class="fa fa-check"></i><b>5.4.3.1</b> Sum of Squares voor Total, Model en Error</a></li>
</ul></li>
<li class="chapter" data-level="5.4.4" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#grand-final"><i class="fa fa-check"></i><b>5.4.4</b> Grand Final</a>
<ul>
<li class="chapter" data-level="5.4.4.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#standaardafwijking-van-de-error"><i class="fa fa-check"></i><b>5.4.4.1</b> Standaardafwijking van de error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsintervallen-en-significantietoetsen-voor-regressie-parameters."><i class="fa fa-check"></i><b>5.5</b> Betrouwbaarheidsintervallen en Significantietoetsen voor Regressie-Parameters.</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsinterval-bi-voor-de-populatie-slope-beta_1"><i class="fa fa-check"></i><b>5.5.1</b> Betrouwbaarheidsinterval (BI) voor de populatie-slope <span class="math inline">\(\beta_1\)</span></a></li>
<li class="chapter" data-level="5.5.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#significantietoets-voor-de-populatie-slope"><i class="fa fa-check"></i><b>5.5.2</b> Significantietoets voor de Populatie Slope</a>
<ul>
<li class="chapter" data-level="5.5.2.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-t-toets-voor-een-regressieslope"><i class="fa fa-check"></i><b>5.5.2.1</b> De t-toets voor een regressieslope</a></li>
</ul></li>
<li class="chapter" data-level="5.5.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsinterval-en-toetsing-van-het-intercept"><i class="fa fa-check"></i><b>5.5.3</b> Betrouwbaarheidsinterval en Toetsing van het Intercept</a>
<ul>
<li class="chapter" data-level="5.5.3.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#betrouwbaarheidsinterval-voor-het-populatie-intercept-beta_0"><i class="fa fa-check"></i><b>5.5.3.1</b> Betrouwbaarheidsinterval voor het Populatie Intercept (<span class="math inline">\(\beta_0\)</span>)</a></li>
<li class="chapter" data-level="5.5.3.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#significantietoets-voor-het-populatie-intercept-beta_0"><i class="fa fa-check"></i><b>5.5.3.2</b> Significantietoets voor het Populatie Intercept (<span class="math inline">\(\beta_0\)</span>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#toetsing-van-een-model-als-geheel"><i class="fa fa-check"></i><b>5.6</b> Toetsing van een Model als ‘Geheel’</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#toetsing-van-het-regressie_model_-aan-de-hand-de-hand-van-een-anova-tabel"><i class="fa fa-check"></i><b>5.6.1</b> Toetsing van het regressie_model_ aan de hand de hand van een ANOVA tabel</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#de-4-populatie-assumpties-bij-lineaire-enkelvoudige-regressie-analyse."><i class="fa fa-check"></i><b>5.7</b> De 4 Populatie-assumpties bij Lineaire Enkelvoudige Regressie Analyse.</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#onafhankelĳkheid-van-observaties"><i class="fa fa-check"></i><b>5.7.1</b> Onafhankelĳkheid van Observaties</a></li>
<li class="chapter" data-level="5.7.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#lineariteit"><i class="fa fa-check"></i><b>5.7.2</b> Lineariteit</a></li>
<li class="chapter" data-level="5.7.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#homoscedasticiteit"><i class="fa fa-check"></i><b>5.7.3</b> Homoscedasticiteit</a></li>
<li class="chapter" data-level="5.7.4" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#normaal-verdeelde-residuen"><i class="fa fa-check"></i><b>5.7.4</b> Normaal verdeelde residuen</a></li>
<li class="chapter" data-level="5.7.5" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#wrapping-up"><i class="fa fa-check"></i><b>5.7.5</b> Wrapping Up</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#aapjes-en-jasp"><i class="fa fa-check"></i><b>5.8</b> AAPJES en JASP</a></li>
<li class="chapter" data-level="5.9" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#rapporteren-van-je-resultaten"><i class="fa fa-check"></i><b>5.9</b> Rapporteren van je Resultaten</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#inleiding"><i class="fa fa-check"></i>Inleiding</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#methode"><i class="fa fa-check"></i>Methode</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#participanten"><i class="fa fa-check"></i>Participanten</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#meetinstrumenten"><i class="fa fa-check"></i>Meetinstrumenten</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#analyse"><i class="fa fa-check"></i>Analyse</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#resultaten"><i class="fa fa-check"></i>Resultaten</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#jasp-lineaire-enkelvoudige-regressie-analyse-qol"><i class="fa fa-check"></i><b>5.10</b> JASP, Lineaire Enkelvoudige Regressie Analyse, QOL</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#lineaire-regressie-aan-de-hand-van-één-continue-interval-predictor."><i class="fa fa-check"></i><b>5.10.1</b> Lineaire Regressie aan de hand van één continue (interval) predictor.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-1"><i class="fa fa-check"></i>Opdracht 1</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-2"><i class="fa fa-check"></i>Opdracht 2</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-3"><i class="fa fa-check"></i>Opdracht 3</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-4"><i class="fa fa-check"></i>Opdracht 4</a></li>
</ul></li>
<li class="chapter" data-level="5.10.2" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#enkelvoudige-lineaire-regressie-analyse-aan-de-hand-van-nominale-predictoren."><i class="fa fa-check"></i><b>5.10.2</b> Enkelvoudige Lineaire Regressie-Analyse aan de hand van Nominale Predictoren.</a>
<ul>
<li><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-1-independent-samples-t-test-voor-het-vergelijken-van-twee-steekproefgemiddelden.">Opdracht 1, ‘independent samples <span class="math inline">\(t\)</span>-test’ voor het vergelijken van twee steekproefgemiddelden.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-2-enkelvoudige-regressie-analyse-voor-het-vergelijken-van-twee-steekproefgemiddelden-aan-de-hand-van-een-dummy-variabele."><i class="fa fa-check"></i>Opdracht 2, ‘Enkelvoudige Regressie-analyse’ voor het vergelijken van twee steekproefgemiddelden aan de hand van een dummy-variabele.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#enkelvoudige-regressie-analyse-voor-het-vergelijken-van-drie-steekproefgemiddelden-aan-de-hand-van-twee-dummy-variabelen."><i class="fa fa-check"></i>‘Enkelvoudige Regressie-analyse’ voor het vergelijken van drie steekproefgemiddelden aan de hand van twee dummy-variabelen.</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-3-1"><i class="fa fa-check"></i>Opdracht 3</a></li>
</ul></li>
<li class="chapter" data-level="5.10.3" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#eénweg-anova-oneway-anova"><i class="fa fa-check"></i><b>5.10.3</b> Eénweg ANOVA (oneway ANOVA)</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#opdracht-4-oneway-anova"><i class="fa fa-check"></i>Opdracht 4, Oneway ANOVA</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#assumptie-checks-voor-eenweg-anova"><i class="fa fa-check"></i>Assumptie checks voor eenweg ANOVA</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-5---enkelvoudige-lineaire-regressie-analyse..html#oneway-anova-rapporteren"><i class="fa fa-check"></i>Oneway ANOVA Rapporteren</a></li>
</ul></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><i class="fa fa-check"></i><b>6</b> Hoofdstuk 6 - Meervoudige Lineaire Regressie-Analyse.</a>
<ul>
<li class="chapter" data-level="" data-path="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html#correctie-voor-spurieuze-verbanden"><i class="fa fa-check"></i>Correctie voor Spurieuze Verbanden</a></li>
<li class="chapter" data-level="" data-path="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html"><a href="hoofdstuk-6---meervoudige-lineaire-regressie-analyse..html#veranderende-of-omdraaiende-verbanden"><i class="fa fa-check"></i>Veranderende of Omdraaiende verbanden</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="6.1" data-path="appendix.html"><a href="appendix.html#standaard-normaalverdeling-z-tabel"><i class="fa fa-check"></i><b>6.1</b> Standaard Normaalverdeling, <span class="math inline">\(z\)</span>-tabel</a></li>
<li class="chapter" data-level="6.2" data-path="appendix.html"><a href="appendix.html#t-verdeling-t-tabel"><i class="fa fa-check"></i><b>6.2</b> <span class="math inline">\(t\)</span>-verdeling, <span class="math inline">\(t\)</span>-tabel</a></li>
<li class="chapter" data-level="6.3" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel"><i class="fa fa-check"></i><b>6.3</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel-voor-alpha-.05"><i class="fa fa-check"></i><b>6.3.1</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel, voor <span class="math inline">\(\alpha = .05\)</span></a></li>
<li class="chapter" data-level="6.3.2" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel-voor-alpha-.025"><i class="fa fa-check"></i><b>6.3.2</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel, voor <span class="math inline">\(\alpha = .025\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="appendix.html"><a href="appendix.html#f-verdeling-f-tabel-voor-alpha-.01"><i class="fa fa-check"></i><b>6.3.3</b> <span class="math inline">\(F\)</span>-verdeling, <span class="math inline">\(F\)</span>-tabel, voor <span class="math inline">\(\alpha = .01\)</span></a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Handleiding Statistiek met JASP</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hoofdstuk-1---het-beschrĳven-van-data-aan-de-hand-van-statistieken-descriptive-statistics." class="section level1" number="1">
<h1><span class="header-section-number">1</span> Hoofdstuk 1 - Het beschrĳven van data aan de hand van statistieken, <em>Descriptive Statistics</em>.</h1>
<div id="waar-ligt-de-data" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Waar ligt de Data?</h2>
<p>Als wetenschapper moeten we gebeurtenissen om ons heen kunnen beschrĳven. We willen bĳvoorbeeld weten hoe slim (in IQ-punten) of hoe lang (in centimers) de respondenten in een steekproef zĳn. Dit beschrĳven van de verkregen data (de verzameling opgemeten scores van je respondenten of proefpersonen in je steekproef) is eigenlĳk altĳd stap één van de data-analyse in een onderzoek. Om de scores van één van de variabelen in een dataset te kunnen beschrĳven, hebben we twee hoofdvragen nodig.</p>
<p>De eerste vraag gaat over <em>waar</em> de data zich bevindt. Bĳ deze vraag denk je aan een maat die het centrum of een soort midden van alle datapunten (de opgemeten scores van alle individuen) aangeeft. Het gemiddelde (<em>mean</em>), de mediaan (<em>median</em>) of de modus (<em>mode</em>) kunnen hiervoor gebruikt worden. Afhankelĳk van de data, geeft de éne maat een handigere beschrĳving dan de andere, maar alledrie de maten zĳn bedoeld om aan te geven rond welk punt (getal of waarde) de data (alle waarden in je steekproef) zich bevindt. We noemen deze maten ook wel centrummaten en natuurlijk zijn deze drie centrummaten niet de enige.</p>
<p>Voor de tweede vraag willen we weten <em>hoe</em> de data <em>verdeeld</em> is of hoe de datapunten in je steekproef ten opzichte van elkaar verschillen of variëren. Hierbĳ kun je denken aan de vraag in hoeverre de verschillende scores bĳ elkaar of juist verder van elkaar verwĳderd liggen. Dit beantwoordt dus de vraag in hoeverre de scores op elkaar lĳken (homogeen zĳn) of juist verschillen (heterogeen zĳn). Om de mate van verschil aan te geven voor de scores voor een bepaalde variabele, gebruiken we de zogenaamde spreidingsmaten zoals de standaardafwĳking (<em>standarddeviation</em>) en de variantie (<em>variance</em>). Er zĳn uiteraard en wederom meerdere manieren of spreidingsmaten om de boel te beschrijven.</p>
<p>Soms is het goed mis met de data en gedragen de scores zich niet zoals we graag zouden willen zien of handig is voor bepaalde analyses en gebruiken we andere trucjes om toch de data te kunnen beschrĳven. Grafisch, dus in een figuur of grafiekje, wordt snel duidelĳk hoe de data zich gedraagt (waar de verschillende scores zich bevinden) en dus verdeeld is. Ik zou het hier kunnen gaan vertellen, het middel en het doel, maar een van de belangrĳkste lessen geef ik je meteen mee: Eerst doen en dan pas gaan denken! Het lĳkt een beetje op de film ‘Karate Kid’, frustrerend maar waar. De leerling in deze film moet allerlei – in eerste opzicht – niet gerelateerde oefeningen doen. Hĳ wil natuurlĳk gewoon vechten. Uiteraard wordt hĳ dik beloond in één of ander duel waar hem dán pas duidelĳk wordt waarvoor hĳ die zinloze oefeningen eindeloos moest herhalen (muren verven met een bepaalde beweging of zĳn jas tot in de eeuwigheid op – en af – hangen). Dat geldt hier in de statistiek (vechten) ook dus en kunnen we het beste maar gewoon beginnen met de opgaven (verven). Voor het grootste deel behandel ik in de opgaven de te leren stof en formules. Je zult dus wel moeten ‘doen’! Succes.</p>
<div id="belgedrag-onder-jongeren-in-nederland" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Belgedrag onder Jongeren in Nederland</h3>
<p>In een fictief onderzoek werd gekeken naar het belgedrag onder jongeren. In een steekproef (uit de populatie Nederlandse jongeren) van <span class="math inline">\(20\)</span> personen (<span class="math inline">\(n=20\)</span>, de kleine letter <span class="math inline">\(n\)</span> staat in de meeste gevallen voor het aantal mensen of onderzoeksobjecten in een steekproef) werd de respondenten gevraagd hoeveel minuten zij de voorgaande week gebruik hadden gemaakt van hun mobiele telefoon om te bellen (dat kan tegenwoordig nog steeds, ik heb het dus niet over scherm-tijd). In de tabel hieronder de verkregen data. Voorlopig gebruik ik ‘<span class="math inline">\(X_i\)</span>’ ter vervanging van de variabele ‘het aantal belminuten’, zolang ik dus nog in het algemeen spreek over de variabele ‘het aantal belminuten’ en nog niet specifiek weet over welke persoon met welke waarde voor het aantal belminuten, ik het heb. De waarde waar <span class="math inline">\(X_5\)</span> voor staat, is <span class="math inline">\(25\)</span> (belminuten). Of anders gezegd: De score <span class="math inline">\(X\)</span> voor persoon nummer <span class="math inline">\(i=5\)</span> heeft de waarde <span class="math inline">\(25\)</span>. De kleine letter <span class="math inline">\(i\)</span> (het subscript) staat dus voor respondent- of proefpersoonnummer. De <span class="math inline">\(i\)</span>-tjes zijn er eigenlijk slechts ter organisatie en als je dus weet over welke persoon het gaat, gebruik je zijn nummer in plaats van de letter <span class="math inline">\(i\)</span> (vervang je <span class="math inline">\(i\)</span> door zijn nummer).</p>
<table>
<caption>
<span id="tab:belminuten-data">Tabel 1.1: </span>Belminuten Data
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respondentnummer
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Aantal Belminuten
</div>
</th>
</tr>
<tr>
<th style="text-align:center;">
<span class="math inline">\(i\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(X_i\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
13
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
58
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
31
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
39
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
42
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
17
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
35
</td>
</tr>
<tr>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
46
</td>
</tr>
<tr>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
22
</td>
</tr>
<tr>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
26
</td>
</tr>
<tr>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
14
</td>
</tr>
<tr>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
33
</td>
</tr>
<tr>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
21
</td>
</tr>
</tbody>
</table>
<p>Aan de hand van een aantal statistieken en grafieken en dergelijke gaan we de data
beschrijven. Er is dus een verschil tussen een ‘statistiek’ en ‘de data’. De data is de verzameling van de scores (datapunten) in onze steekproef en een statistiek heeft
een overstijgende functie. Een statistiek is een beschrijvend getalletje en zegt dus iets over - of beschrijft - de data (als geheel). Voordat we beginnen is het handig om de data (de verschillende scores) op volgorde (rangorde) te zetten, zodat we bijvoorbeeld makkelijk de mediaan kunnen berekenen. Neem de data over en orden de scores van lage naar hoge waarden. Je kunt de verschillende scores opnieuw nummeren en de oorspronkelijke waarden voor <span class="math inline">\(i\)</span> negeren, zodat nu de persoon met de laagste score, de waarde <span class="math inline">\(i=1\)</span> krijgt en de persoon met de hoogste score krijgt dus <span class="math inline">\(i=20\)</span>. De verschillende waarden voor <span class="math inline">\(i\)</span> representeren dan meteen de verschillende <em>rangnummers</em> en deze geven dus de (ordinale) <em>volgorde</em> van de originele scores aan.</p>
</div>
<div id="opgaven-belgedrag-onder-jongeren-in-nederland-beschrijven" class="section level3" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> <em>Opgaven</em> Belgedrag onder Jongeren in Nederland: Beschrijven</h3>
<div id="Theorie" class="definities">
<p><strong><span style="color: blue;">Mediaan, <em>Median</em></span></strong></p>
<p>De Mediaan is de waarde voor een variabele zodanig dat <span class="math inline">\(50\)</span> procent van alle scores onder die waarde valt en <span class="math inline">\(50\)</span> procent boven die waarde valt. Dus <span class="math inline">\(50\)</span> procent van de respondenten scoren dus lager dan de mediaan en <span class="math inline">\(50\)</span> procent van de respodenten scoren dus hoger dan de mediaan. De mediaan is een centrummaat en vertelt je wat de waarde is van de middelste score is.</p>
</div>
<div id="Opgave1.1" class="opgaven">
<div id="opgave-1" class="section level5 unnumbered">
<h5>Opgave 1</h5>
<ol style="list-style-type: decimal">
<li>Als eerste statistiek bekijken we de mediaan. De mediaan is een centrummaat en hoort dus bij de vraag waar de data zich bevindt en is de <em>waarde</em> (score) voor de variabele (Aantal Belminuten) behorend bij de middelste observatie, persoon of rangnummer als je de data-punten (scores) dus eerst hebt gerangordend. Wélk <em>rangnummer</em> van de scores ‘draagt’ de mediaan?</li>
<li>Welke waarde heeft de mediaan? (er is dus een verschil tussen de vraag ‘Waar (bij welke observatie als ze gerangschikt zijn) ligt de mediaan?’ en ‘Wat is de (waarde van de) mediaan?’)</li>
</ol>
</div>
</div>
<div id="Theorie" class="definities">
<p><strong><span style="color: blue;">Het eerste en derde Kwartiel, <em>first and third Quartile</em> (<span class="math inline">\(Q_1\)</span> en <span class="math inline">\(Q_3\)</span>) </span></strong></p>
<p>Het <em>eerste</em> kwartiel (<span class="math inline">\(Q_1\)</span>) is die score waaronder <span class="math inline">\(25\)</span> procent van de data (observaties) valt (en dus <span class="math inline">\(75\)</span> procent van de scores daarboven). Zo staat het <em>derde</em> kwartiel (<span class="math inline">\(Q_3\)</span>) voor die score waaronder <span class="math inline">\(75\)</span> procent van de data valt (en dus <span class="math inline">\(25\)</span> procent daarboven).</p>
</div>
<div id="Opgave1.1voortzetting" class="opgaven">
<ol start="3" style="list-style-type: decimal">
<li><p>Welke waarden hebben <span class="math inline">\(Q_1\)</span> en <span class="math inline">\(Q_3\)</span>? Welke <span class="math inline">\(X\)</span>-scores vallen in het eerste quartiel?</p></li>
<li><p>Geef de <em>Five-Number Summary</em> (minimum , <span class="math inline">\(Q_1\)</span>) voor de score X.</p></li>
<li><p>Teken een boxplot zonder uitbijters (ofwel de zogenaamde <em>outliers</em> of extreme waarden). Betrek dus alle scores bij de boxplot. De twee staarten, aan de onder en bovenkant van de boxplot lopen dus tot en met het minimum en het maximum van de scores.</p></li>
<li><p>Om wel rekening te houden met eventuele uitbijters (<em>outliers</em>) gaan we nu een <em>modified boxplot</em> fabriceren. Hiervoor moet je eerst de waarde van de IQR weten (<em>interquartile range</em>). Bereken deze waarde <span class="math inline">\(IQR = Q_3 - Q_1\)</span>, dit is dus (grootte van) de afstand (interval) tussen <span class="math inline">\(Q_1\)</span> en <span class="math inline">\(Q_3\)</span>. Een score wordt als uitbijter gezien als deze boven de waarde ‘<span class="math inline">\(Q_3 + 1.5 \cdot IQR\)</span>’ valt en wordt dan slechts als puntje aangegeven (en wordt dus niet in de bovenste staart opgenomen. De bovenkant van de boxplot (staart) eindigt dan bij - of op - de laatste score die nog wel echt mee mag doen en dus nog net op of onder de waarde <span class="math inline">\(Q_3 + 1.5 \cdot IQR\)</span> valt. Voor uitbijters aan de linker - of dus onderkant - van de verdeling doe je hetzelfde, maar kijk je vanaf <span class="math inline">\(Q_1\)</span> en dan wel in de tegengestelde richting als bij de andere staart, dus naar beneden. Dus <span class="math inline">\(Q_1–1.5 \cdot IQR\)</span> is dan de ondergrens van scores die nog mee zouden mogen doen voor de staart aan de onderkant van de boxplot.</p></li>
<li><p>Regelmatig is er sprake van scheefheid van de verdeling van de scores in de data (<em>skewness</em>). Is hier sprake van een verdeling die links of rechtsscheef is? Zou het gemiddelde, <span class="math inline">\(\overline{X}\)</span>, links of rechts van de mediaan liggen? Je hoeft het gemiddelde nog niet uit te rekenen, geef slechts een schatting.</p></li>
</ol>
</div>
<div id="Theorie" class="definities">
<p><strong><span style="color: blue;">De Modus, <em>Mode</em></span></strong></p>
<p>De Modus is die score die het vaakst voorkomt, die dus het meest frequent is, dus die gebeurtenis (score) die in de ‘mode’ is. Soms zijn er meerdere waarden die het meest voorkomen. Ook de modus is een centrummaat, wel een beetje een erg rare, want wat het meest voorkomt hoeft toch niet het centrum te zijn? Bij een centrummaat denk ik aan een plaatsbepaling (zoals van een stad, dan geef je vaak het cetrum van die stad aan op de kaart).</p>
</div>
<div id="Opgave1.1voortzetting2" class="opgaven">
<ol start="8" style="list-style-type: decimal">
<li><p>Wat is hier de waarde van de modus? Welk probleem ontstaat hier? In hoeverre kunnen we hier zeggen dat de modus een goede beschrijver voor (deze) data is?</p></li>
<li><p>Waar zou de mediaan liggen als er een oneven aantal observaties zouden zijn, bijvoorbeeld bij <span class="math inline">\(21\)</span> scores waarbij de waarde van de nieuwe (en hoogste) score <span class="math inline">\(83\)</span> is? Teken ook voor deze <span class="math inline">\(21\)</span> gevens een gewone boxplot en eentje die aangepast is waarin de outliers zichtbaar zijn.</p></li>
</ol>
</div>
<table class="table" style="font-size: 7px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:belminuten-gesorteerd">Tabel 1.2: </span>Belminuten Data, op Volgorde, van Laag naar Hoog
</caption>
<thead>
<tr>
<th style="text-align:center;">
Rangnummer <span class="math inline">\(i\)</span>
</th>
<th style="text-align:center;">
1
</th>
<th style="text-align:center;">
2
</th>
<th style="text-align:center;">
3
</th>
<th style="text-align:center;">
4
</th>
<th style="text-align:center;">
5
</th>
<th style="text-align:center;">
6
</th>
<th style="text-align:center;">
7
</th>
<th style="text-align:center;">
8
</th>
<th style="text-align:center;">
9
</th>
<th style="text-align:center;">
10
</th>
<th style="text-align:center;">
11
</th>
<th style="text-align:center;">
12
</th>
<th style="text-align:center;">
13
</th>
<th style="text-align:center;">
14
</th>
<th style="text-align:center;">
15
</th>
<th style="text-align:center;">
16
</th>
<th style="text-align:center;">
17
</th>
<th style="text-align:center;">
18
</th>
<th style="text-align:center;">
19
</th>
<th style="text-align:center;">
20
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Aantal Belminuten, <span class="math inline">\(X_i\)</span>
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
31
</td>
<td style="text-align:center;">
33
</td>
<td style="text-align:center;">
35
</td>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
42
</td>
<td style="text-align:center;">
46
</td>
<td style="text-align:center;">
58
</td>
</tr>
</tbody>
</table>
<div id="Uitwerking1.1" class="uitwerkingen">
<div id="uitwerking-1" class="section level5 unnumbered">
<h5>Uitwerking 1</h5>
<ol style="list-style-type: decimal">
<li>De mediaan ligt <em>tussen</em> de rangnummers <span class="math inline">\(10\)</span> en <span class="math inline">\(11\)</span>, dus eigenlijk bij rangnummer <span class="math inline">\(10.5\)</span>. In dit geval hebben we maar <span class="math inline">\(20\)</span> observaties, het middelste rangnummer vinden, is dan vrij eenvoudig. Je kunt dus zeggen wanneer er een even aantal observaties is (bij ons <span class="math inline">\(n = 20\)</span>), dat de mediaan altijd de data in twee gelijke stukken hakt (twee stukken van <span class="math inline">\(50\)</span> procent) én de mediaan dus tussen de twee middelste observaties komt te liggen. Wanneer er een oneven aantal observatie zijn wordt de data ook in twee gelijke stukken gehakt, maar ligt de mediaan op de (enige) middelste persoon (of rangnummer). Om het <em>rangnummer</em> van de Mediaan (<span class="math inline">\(R_{Med}\)</span>) te vinden, kun je ook een formule toepassen (en dat doe ik dus ook meteen):</li>
</ol>
<p><span class="math display">\[R_{Med} = \frac{n + 1}{2} =  \frac{20 + 1}{2} = 21/2 = 10.5\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li><p><span class="math inline">\(Med = \frac{22 + 25}{2} = 23.5\)</span> Je neemt hier dus een het gemiddelde van de twee scores die horen bij de twee rangnumers die naast het rangnummer van de mediaan liggen. Soms heb je te maken met veel herhalingen van bepaalde waarden (knopen) rond de mediaan, er zijn verschillende manieren die ook andere waarden als uitkomst voor de mediaan geven, die laat ik hier buiten beschouwing. Het gaat er vooral om dat je snapt dat de mediaan de middelste waarnemingswaarde is en je data dus in twee gelijke stukken hakt qua aantallen observaties!</p></li>
<li><p><span class="math inline">\(Q_1 = 18.5\)</span> deze waarde is eigenlijk niks anders dan de mediaan van de linker helft van je data, dus behorende bij de eerste tot en met de tiende waarneming. <span class="math inline">\(Q_3 = 34\)</span> deze waarde is eigenlijk niks anders dan de mediaan van de rechter helft van je data, dus behorende bij de elfde tot en met de twintigste waarneming. Om te kijken bij welk rangnummer <span class="math inline">\(Q_1\)</span> hoort kun je altijd de volgende formule toepassen (maar bij weinig data kun je dus ook gewoon even met je vingertjes tellen):
<span class="math display">\[R_{Q_{1}} = \frac{n + 1}{4} =  \frac{20 + 1}{4} = 21/4 = 5.25\]</span>
Dus <span class="math inline">\(Q_1\)</span> ligt tussen de vijfde en zesde waarneming we gebruiken dus <span class="math inline">\(X_5\)</span> en <span class="math inline">\(X_6\)</span> en nemen van deze twee waarde het gemiddelde:
<span class="math display">\[Q_1 = \frac{18 + 19}{2} \]</span>
Voor <span class="math inline">\(Q_3\)</span> kunnen we ook eerst bijbehorend rangnummer vinden door een berekening. Je vermenigvuldig <span class="math inline">\(R_{Q_{1}}\)</span> eigenlijk met een factor <span class="math inline">\(3\)</span>:
<span class="math display">\[ R_{Q_{3}} = 3 \cdot R_{Q_{1}} = \frac{3 \cdot (n + 1)}{4} = 15.75\]</span>
Dus om de waarde van <span class="math inline">\(Q_3\)</span> te vinden, neem je het gemiddelde van de scores behorend bij de twee dichtst gegelegen rangnummers, dus van <span class="math inline">\(15\)</span> en <span class="math inline">\(16\)</span>.</p></li>
<li><p>The Five−Number Summary: Minimum <span class="math inline">\(=13\)</span>, <span class="math inline">\(Q_1 = 18.5\)</span>, Mediaan <span class="math inline">\(=23.5\)</span>, <span class="math inline">\(Q_3 = 34\)</span>, Maximum <span class="math inline">\(= 58\)</span>. De scores die in het eerste quartiel liggen zijn: <span class="math inline">\(13\)</span>, <span class="math inline">\(14\)</span>, <span class="math inline">\(17\)</span>, <span class="math inline">\(18\)</span> en nog een keer <span class="math inline">\(18\)</span>.</p></li>
<li><p>De boxplot en bijbehorende waarden zijn dus:</p></li>
</ol>
<div class="figure"><span style="display:block;" id="fig:belminuten-boxplotA"></span>
<img src="main_files/figure-html/belminuten-boxplotA-1.png" alt="Belminutendata: Boxplot zonder outliers" width="672" />
<p class="caption">
Figuur 1.1: Belminutendata: Boxplot zonder outliers
</p>
</div>
<ol start="6" style="list-style-type: decimal">
<li>De berekening van de IQR en de bepaling van de grenswaarde voor de <em>outliers</em> aan de bovenkant van de boxplot:</li>
</ol>
<p><span class="math inline">\(\:\:\:\:\:\:IQR = 34−18,5 = 15.5\)</span></p>
<p><span class="math inline">\(\:\:\:\:\:\:1.5 \cdot IQR = 1.5 \cdot 15.5 = 23.25\)</span></p>
<p><span class="math inline">\(\:\:\:\:\:\:Q_3 + 1.5 \cdot IQR = 34 + 23.25 = 57.25\)</span></p>
<p>De hoogst <em>mogelijke</em> bovengrens van de boxplot, hoger dan deze waarde zou de <em>staart</em> dus nooit kunnen komen, maar de outliers dus wel! En nu de grenswaarde voor de outliers aan de onderkant.</p>
<p><span class="math inline">\(\:\:\:\:\:\:Q_1 - 1.5 \cdot IQR = 18.5 - 23.25 = \text{-} 4.75\)</span></p>
<p>De laagst mogelijke ondergrens van de boxplot, belminuten kunnen niet negatief zijn (toch?), dus <em>no worries</em>. Zie hieronder de uiteindelijke ‘modified boxplot’ en het is deze manier waarop een boxplot standaard (in statistiek programma’s) worden gemaakt:</p>
<div class="figure"><span style="display:block;" id="fig:belminuten-boxplotB"></span>
<img src="main_files/figure-html/belminuten-boxplotB-1.png" alt="Belminutendata: Boxplot met outliers" width="672" />
<p class="caption">
Figuur 1.2: Belminutendata: Boxplot met outliers
</p>
</div>
<ol start="7" style="list-style-type: decimal">
<li><p>Rechtsscheef. Omdat er een aantal scores vrij hoog zijn ten opzichte van de rest of het gros, zal het gemiddelde iets omhoog worden getrokken en dus rechts van (of boven) de mediaan liggen.</p></li>
<li><p><span class="math inline">\(18\)</span>, <span class="math inline">\(50\)</span>, <span class="math inline">\(20\)</span> en <span class="math inline">\(25\)</span> zijn de modussen, want die komen alle drie het meest (<span class="math inline">\(2\)</span> keer) voor. Vreemd, maar dit kan gewoon. Blijkbaar zijn er dus meerdere scores in de mode!</p></li>
<li><p>Als we <span class="math inline">\(21\)</span> observaties hadden geteld, was de mediaan toebedeeld aan rangnummer <span class="math inline">\(11\)</span>, dan zouden er dus tien scores onder en boven die waarde vallen. Stel dat de waarde van die 21ste score bijvoorbeeld <span class="math inline">\(83\)</span> zou zijn, erg hoog dus, dan zou dat niet zoveel uit maken voor de waarde van de mediaan. Die wordt dan de score 25 die hoort bij de elfde persoon (de score van de middelste persoon ingeval van <span class="math inline">\(21\)</span> scores). Je zou kunnen stellen dat door toevoeging van een score de mediaan slechts een half plekje naar rechts schuift (in ons voorbeeld dus van <span class="math inline">\(10.5\)</span> naar rangnummer <span class="math inline">\(11\)</span>) onafhankelijk van de waarde van die toegevoegde score. Omdat de (hoge) waarde van die toegevoegde score dus eigenlijk niet van belang is voor de mediaan, kunnen we ook stellen dat de mediaan robuust is voor (opgewassen tegen) outliers. De mediaan is dus vrij onveranderlijk of stabiel als het gaat om de invloed van outliers in de data op deze statistiek (mediaan). Uitbijters of extreme waarden hebben dus nauwelijks invloed op de waarde van de mediaan.</p></li>
</ol>
<p><span class="math inline">\(\:\:\:\:\:\:Minimum = 13\)</span>.</p>
<p><span class="math inline">\(\:\:\:\:\:\:Q_1= \frac{18 + 19}{2} = 18.5\)</span></p>
<p>Dus eigenlijk de mediaan van de linker helft, deze loopt ook van <span class="math inline">\(1\)</span> t/m <span class="math inline">\(10\)</span> en niet van <span class="math inline">\(1\)</span> t/m <span class="math inline">\(11\)</span>!</p>
<p><span class="math inline">\(\:\:\:\:\:\:Mediaan = 25\)</span></p>
<p>De mediaan is dus de waarde van de elfde observatie en deelt nu de data in twee gelijke stukken.</p>
<p><span class="math inline">\(\:\:\:\:\:\:Q_3 = \frac{35 + 39}{2} = 37\)</span>.</p>
<p><span class="math inline">\(Q_3\)</span> is dus eigenlijk de ‘mediaan’ van de rechterhelft, deze loopt van rangnummer <span class="math inline">\(12\)</span> t/m <span class="math inline">\(21\)</span> en de twee middelste rangnummers daarvan zijn nu <span class="math inline">\(16\)</span> en <span class="math inline">\(17\)</span>!</p>
<p><span class="math inline">\(\:\:\:\:\:\:Maximum = 83\)</span>.</p>
<p><span class="math inline">\(\:\:\:\:\:\:IQR = Q_3−Q_1 = 37−18.5 = 18.5\)</span></p>
<p>De IQR heb je dus weer nodig om een modified boxplot te maken.</p>
<p><span class="math inline">\(\:\:\:\:\:\:1.5·IQR = 1.5·18.5 = 27.25\)</span></p>
<p><span class="math inline">\(\:\:\:\:\:\:Q_3 + 1.5·IQR = 37 + 27.25 = 64.25\)</span></p>
<p>De bovenkant of de rechterstaart van de modified boxplot, loopt dus tot de waarde in de data die nog net onder of even groot is als <span class="math inline">\(64.25\)</span>. De waarde <span class="math inline">\(58\)</span> valt hier nog (net) onder. De ondergrens van deze boxplot is gewoon weer <span class="math inline">\(13\)</span> omdat de uiterste grens weer negatief zal zijn en dus sowieso niet zal voorkomen in de data. Je ziet hieronder dat de score <span class="math inline">\(X=58\)</span> nu we tot de boxplot behoort en dus niet meer als outlier wordt beschaouwd.</p>
<div class="figure"><span style="display:block;" id="fig:belminuten-boxplotC"></span>
<img src="main_files/figure-html/belminuten-boxplotC-1.png" alt="Belminutendata: Boxplot met outliers met nog een extremere score" width="672" />
<p class="caption">
Figuur 1.3: Belminutendata: Boxplot met outliers met nog een extremere score
</p>
</div>
</div>
</div>
<div id="JaspUitwerking1.1" class="jaspuitwerkingen">
<div id="jasp-uitwerking-opgave-1" class="section level5 unnumbered">
<h5>JASP Uitwerking Opgave 1</h5>
<p>Ik heb alvast een databestand aangemaakt, je hoeft dus niet zelf de getalletjes voor de belminuten in te tikken! Zorg eerst dat je het databestand ‘BelminutenData.xlsx’ download van mijn site <a href="http://www.wisi.nl/" class="uri">http://www.wisi.nl/</a> en het opslaat in een handige en herkenbare map. Maak dus vooral een nieuwe map (folder) aan op je bureaublad (desktop) voor je ‘JASP gymnaStiekjes’. ik ga er even van uit dat je ‘JASP gymnaStiekjes’ als naam voor je nieuwe map gebruikt. Databestanden komen in velen soorten en maten, ieder programma, zoals ‘Microsoft Word’ maar dus ook ‘JASP’, ‘R’, ‘EXCEL’ of ‘SPSS’ bijvoorbeeld, gebruiken hun een eigen ‘extensie’ in de bestandsnaam van het (data-) bestand. Zo gebruikt ‘Word’ de extensie ‘.docx’ bij een ‘Word’-bestand en een ‘excel’-bestand gebruikt de extensie ‘.xlsx’ voor het databestand (datafile). Soms laat je computer die extensie <em>niet</em> zien. Super irritant is dat. Ik weet wel dat mensen bang worden van te veel informatie, maar beter begrijp je dit wel, zodat je beter je verschillende soorten bestanden van elkaar kunt onderscheiden. Dus check even of je wel de extensie ziet. Zo niet, google dan even op ‘Show or hide filename extensions on Mac of Windows’ om deze optie te veranderen. Vaak als we data willen delen met elkaar dan doen we dat in een format dat de meeste kunnen openen. Meestal is dat een ‘Excel’ (.xlsx) of een ‘SPSS’ (.sav) databestand, maar kunnen dus ook anderen zijn. Voor nu heb ik een excel bestand aan jullie gegeven. Open het dit bestand met eerst maar even met EXCEL, zodat je de data kunt zien. Met JASP kun je dit bestand niet gewoon zo openen, daarvoor moeten we het bestand eerst op een andere manier opslaan. Probeer het toch maar wel even, zodat je ziet dat het echt niet werkt, dus eerst even fout:</p>
<ul>
<li><p>De <strong>foute manier</strong> om een excel-bestand te openen die dus niet werkt:</p>
<ul>
<li>Open eerst het programma JASP en probeer het bestand ‘BelminutenData.xlsx’ te openen:</li>
<li>Klik linksboven op ‘Open’, dan ‘Computer’, dan ‘Browse’ en vervolgens ‘navigeer’ dan naar je folder ‘JASP gymnaStiekjes’ en klik je, heeel hard (dubbel) op ‘BelminutenData.xlsx’.
<ul>
<li>Er gebeurt niks, maar dat wist je al.</li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave11.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave12.png" width="50%" /></p>
<p>Als je wilt, kun je op de afbeeldingen, groter in aan aparte browser (tabblad) bekijken door met je cursor op de afbeeldingen te gaan staan, dan op de rechter muisknop drukken drukken en ‘open afbeelding in nieuwe tab’ te kiezen!</p>
<ul>
<li><p>De <strong>correcte manier</strong> om een excel bestand toch te kunnen openen. We gaan <em>eerst</em> het excel bestand ‘BelminutenData.xlsx’ in een ander format, met een andere extensie opslaan. JASP kan bijvoorbeeld wel bestanden met de extensie ‘.csv’ openen (Voor nu niet van belang maar ‘csv’ staat voor ‘Comma Seperated Values’, een manier van opslaan waarin alle waarden (datapunten) dus gescheiden worden door komma’s):</p>
<ul>
<li><p>Open het excel bestand ‘BelminutenData.xlsx’, gewoon met het programma EXCEL.</p></li>
<li><p>Sla het bestand opnieuw op maar nu met een andere extensie:</p>
<ul>
<li><p>Klik op het ‘dropdown’ menu onder ‘File’ (‘Archief’) in de menubalk bovenaan en kies ‘Save as’ (‘Opslaan als’). Als het goed is kom je dan meteen in je ‘JASP gymnaStiekjes’ map.</p></li>
<li><p>Je hoeft niet de naam te veranderen, maar dus alleen de extensie, dit doe je door:</p>
<ul>
<li><p>Onderaan, bij ‘File format:’ de optie ‘CSV UTF-8 (Comma delimted) (.csv)’ te kiezen.</p>
<ul>
<li>Druk dan op ‘Save’, Je krijgt nu waarschijnlijk een waarschuwing te zien (mag je best even lezen hoor), maar klik vooral op ‘Yes’.</li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave13.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave14.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave15.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave16.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave17.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave18.png" width="50%" /></p>
<ul>
<li><p>Kijk in je folder of er een bestand bij is gekomen met de naam én juiste extensie ‘BelminutenData.csv’</p></li>
<li><p>Je kan nu wel, met JASP, dit bestand ‘BelminutenData.csv’ openen. Dus nu weer, binnen het programma JASP klikken om het bestandje te openen;</p>
<ul>
<li><p>Klik linksboven op ‘Open’, dan ‘Computer’, dan ‘Browse’ en vervolgens ‘navigeer’ je weer naar je map ‘JASP gymnaStiekjes’ en klik je op de bestandsnaam ‘BelminutenData.csv’.</p>
<ul>
<li><p>Ik hoop nu echt dat het databestand zichtbaar is geworden en dat je het data bestand dus succelvol hebt geïmporteerd, kunnen we eindelijk onze statistiekjes draaien en kijken of alles klopt met onze handmatige berekeningen.</p></li>
<li><p>Je ziet nu 20 rijen (horizontaal) en 2 kolommen (verticaal). Eén rij staat voor (definiëert) één ‘case’ of onderzoeksobject, bij ons dus een persoon of respondent. In de eerste kolom vind je de respondentnummer ‘id’ (‘id’ voor ‘identitificatie van de respondent) en in de tweede kolom staan de observaties (metingen) voor het aantal belminuten (van de afgelopen week). In totaal hebben we dus <span class="math inline">\(40\)</span> (<span class="math inline">\(2\)</span> keer <span class="math inline">\(20\)</span>) datapunten, terwijl de ’eerste twintig’ puur voor de organisatie, van onze ‘tweede twintig’ datapuntjes dient.</p></li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave19.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave110.png" width="50%" /></p>
<ul>
<li><p>De bedoeling van de opgave 1 was om een beschrijving, weergave of samenvatting te geven van ‘waar’ de scores voor de geobserveerde belminuten in de steekproef zich bevinden. Dus waar we, qua positie en qua grootte van verschillen, de verschillende waarden (datapunten) voor ‘belminuten’ op de ‘getallenlijn’ voor belminuten (dus de variabele of dimensie ‘belminuten’) dus kunnen vinden. in Opgave 1 deden we dit aan de hand van de ‘Five-number summary’, zowel <em>nummeriek</em> aan de hand van statistieken als <em>grafisch</em> (plaatje) aan de hand van een ‘boxplot’. Een van de velen manieren om naar de verdeling van je geobserveerde scores te kijken en die dus voor je publiek (lezers) te kunnen samenvatten. Voor de Five-number summary hebben we het minimum, het eerst kwartiel ‘<span class="math inline">\(Q_1\)</span>’, de mediaan, het derde kwartiel ‘<span class="math inline">\(Q_3\)</span>’ en het maximum van voor onze scores nodig. Verschillende programma’s hebben verschillende instellingen voor correcties voor ‘knopen’ in je data. Als je twee of meer dezelfde scores hebt, geven die samen meer gewicht aan die waarde (meer gelijk is anders dan meer ongelijk) en er zijn dus verschillende manieren om daarmee ‘om te gaan’ (er voor te corrigeren). Er zijn ook verschillende correcties om, om te gaan met de ‘achterliggende rangnummers’ van de scores (bij ons heeft de laagste score de waarde <span class="math inline">\(13\)</span> en heeft deze score dus het laagste rangnummer (rangnummer <span class="math inline">\(=1\)</span>). Textboeken (deze ook) geven vaak een ‘simpele’ manier voor de berekening software programma’s doen het bijna altijd anders, dus de antwoorden komen vaak niet precies overeen. Zeker bij grote steekproeven, zullen de verschillende benaderingen niet veel uit maken (stiekem hoop ik dat we zo een andere uitkomst krijgen dan wij handmatig gevonden hebben, kunnen we zien hoeveel onrust dat bij jou en mij veroorzaakt). Laten we maar snel gaan kijken.</p>
<ul>
<li><p>Klik linksboven op het ‘Descriptives’ icoontje en dan kom je meteen in een interactief scherm;</p>
<ul>
<li><p>Links in het scherm kun je variabelen kiezen en opties kiezen en rechts zie je meteen je resultaten veranderen, ‘while you’re on the job’ dus, heel fijn.</p>
<ul>
<li><p>Sleep de variabele ‘belminuten’ naar rechts, in het vakje onder ‘Variables’ (of klik er eenmaal op en druk dan op het pijltje dat naar rechts wijst).</p></li>
<li><p>Vervolgens klik je op de balk ‘Statistics’ voor meer numerieke beschrijvers en vink de (extra) opties aan die wij nog nodig hebben voor de ‘Five-number summary’ (worden immers, er al twee gegeven, het minimum en het maximum);</p>
<ul>
<li><p>Voor het eerste en derde kwartiel vink je ‘Quartiles’ onder het kopje ‘Quantiles’ aan;</p></li>
<li><p>Voor de mediaan, vink je ‘Median’ aan (onder ‘Central Tendency’)</p></li>
<li><p>Als extraatje meteen ook maar de ‘Interkwartiel Range’ (<span class="math inline">\(IQR\)</span>).</p></li>
<li><p>Voor ons figuur, de boxplot, klik je nog op de balk ‘Plots’ vervolgens alleen nog kiezen welk plaatje je wil zien;</p>
<ul>
<li>Kies ‘boxplot’ en geef hem een gezellig kleurtje door ook nog ‘Use color palette’ aan te vinken’</li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave111.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave112.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave113.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave114.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave1141.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave115.png" width="50%" /></p>
<ul>
<li>Hieronder de ‘Descriptive Statistics’ (beetje dubbelop) die we opgevraagd hebben.</li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave116.png" width="40%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>ALs je deze uitkomsten vergelijkt met die handmatige van ons, dan zie je dat het minimum, het maximum en de mediaan hetzelfde zijn, behalve dus het eerste en derde kwartiel, <span class="math inline">\(Q_1\)</span> (‘<span class="math inline">\(25th\)</span> percentile’) en <span class="math inline">\(Q_3\)</span> (‘<span class="math inline">\(75th\)</span> percentile’):</p>
<ul>
<li><p>Handmatig berekening: <span class="math inline">\(Q_1 = 18.5\)</span> en <span class="math inline">\(Q_3 = 34.0\)</span></p></li>
<li><p>JASP berekening: <span class="math inline">\(Q_1 = 18.75\)</span> en <span class="math inline">\(Q_3 = 33.5\)</span></p>
<ul>
<li>De antwoorden zijn dus net even anders, dat betekent dus ook dat de IQR iets verschilt. Boeien, ik hoop dat je het kunt accepteren. De handmatige manier is voor je aller eerste statistiek tentamen (dus check wel de regeltjes bij jouw opleiding), en daarna gebruik je alleen nog maar software applicaties.</li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/image01BoxplotBelminuten.png" width="70%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Hierboven dus de visuele representatie voor onze data in de vorm van een boxplot. Hij zal dus iets verschillen van die van ons. Maar je ziet nog steeds dat de scores rechtsscheef verdeeld zijn en dat er dus een uitbeiter is aan de rechterkant.</p></li>
<li><p>De <em>Five-number summary</em> of een boxplot kun je dus gebruiken als samenvatiing van je data als je te maken hebt met een variabele waarvan je tenminste aanneemt dat deze op interval niveau (of hoger) gemeten is, dus voor echt numerieke variabelen.</p></li>
</ul>
</div>
</div>
<div id="Opgave1.2" class="opgaven">
<div id="opgave-2" class="section level5 unnumbered">
<h5>Opgave 2</h5>
<ol style="list-style-type: decimal">
<li>Een andere manier om grafisch de verdeeldheid van de data te laten zien is een <em>stem-and-leaf plot</em>. De zogenaamde stam met blaadjes met in de stam de tientallen en de blaadjes zijn de waarden of ‘ééntallen’ binnen die tientallen die in de data voorkomen, als een score drie keer voorkomt, krijg je ook drie dezelfde ‘blaadjes’ te zien. Teken een <em>stem-and-leaf plot</em>. Wat kunnen we over de vorm zeggen? Links of rechtsscheef Komt dit overeen met de eerder getekende boxplot?</li>
</ol>
</div>
</div>
<div id="Uitwerking1.2" class="uitwerkingen">
<div id="uitwerking-2" class="section level5 unnumbered">
<h5>Uitwerking 2</h5>
<ol style="list-style-type: decimal">
<li>De verdeling is rechts scheef, als je de stem- and leaf-plot
een kwartslag tegen de klok indraait, zit de staart rechts.</li>
</ol>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##   1 | 347889
##   2 | 0012556
##   3 | 1359
##   4 | 26
##   5 | 8</code></pre>
</div>
</div>
<div id="JaspUitwerking1.2" class="jaspuitwerkingen">
<div id="jasp-uitwerking-opgave-2" class="section level5 unnumbered">
<h5>JASP Uitwerking Opgave 2</h5>
<ul>
<li>Om een stem and leaf plot te maken, klik je weer op Descriptives linksbovenaan in het JASP scherm, verplaats vervolgens de variabele ‘belminuten’ naar de box onder ‘Variables’. Nu de optie ‘Stem and leaf tables’ aanvinken en ‘scale’ laat je gewoon op ‘<span class="math inline">\(1\)</span>’ staan. Voila.</li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave21.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave22.png" width="50%" /></p>
<ul>
<li>De ‘<span class="math inline">\(1\)</span>’ linksven in de stem and leaf plot lees je als een <span class="math inline">\(10\)</span>, de ‘<span class="math inline">\(2\)</span>’ daaronder als een ‘<span class="math inline">\(20\)</span>’. De eerste kolom onder ‘Stem’, lees je dus als tientallen. Rechts van het het eerste verticale streepje (naast ‘<span class="math inline">\(1\)</span>’) zie je een ‘<span class="math inline">\(3\)</span>’ staan, deze lees je als een gewone <span class="math inline">\(3\)</span> (en heeft dus niks met de ‘<span class="math inline">\(4\)</span>’ erachter te maken). Die eerste ‘<span class="math inline">\(1\)</span>’ en die eerste ‘<span class="math inline">\(3\)</span>’ vormen samen het getal ‘<span class="math inline">\(13\)</span>’. Die eerste ‘<span class="math inline">\(1\)</span>’ en die eerste ‘<span class="math inline">\(4\)</span>’ (achter de eerste ‘<span class="math inline">\(3\)</span>’) vormen samen het getal ‘<span class="math inline">\(14\)</span>’. Zo zie je dus bijvoorbeeld dat er tussen de waarde <span class="math inline">\(10\)</span> en <span class="math inline">\(20\)</span>, twee keer het getal <span class="math inline">\(18\)</span> voorkomt, de meeste getallen tussen de <span class="math inline">\(20\)</span> en de <span class="math inline">\(30\)</span> en maar één getal tussen de <span class="math inline">\(50\)</span> en de <span class="math inline">\(60\)</span> (namelijk <span class="math inline">\(58\)</span>). Omdat het merendeel van de getallen tussen de <span class="math inline">\(10\)</span> en de <span class="math inline">\(30\)</span> (links) en de staart dus rechts, kunnen we zeggen dat de scores rechtsscheef verdeeld zijn (uitschieters aan de bovenkant)</li>
</ul>
</div>
</div>
<div id="Opgave1.3" class="opgaven">
<div id="opgave-3" class="section level5 unnumbered">
<h5>Opgave 3</h5>
<ol style="list-style-type: decimal">
<li><p>Bereken het gemiddelde voor de X-scores ( <span class="math inline">\(\overline X\)</span>– of E(<span class="math inline">\(X\)</span>)), ook wel de verwachting (<em>of expected value</em>) voor de variabele <span class="math inline">\(X\)</span>. Zeker bij scores die zich ‘wenselijk’ gedragen (hier kom ik later op terug), is het gemiddelde de meest gebruikte statistiek om het centrum van de data te beschrijven.</p></li>
<li><p>Loop de voorgaande vragen nog een keer door en bekijk de verschillen tussen de mediaan, de modus en het gemiddelde. Hoe hadden de boxplot en de <em>stem-and-leaf plot</em> eruit kunnen (of moeten) zien zodanig dat het gemiddelde, de mediaan en de modus ongeveer gelijk waren geweest?</p></li>
</ol>
</div>
</div>
<div id="Uitwerking1.3" class="uitwerkingen">
<div id="uitwerking-3" class="section level5 unnumbered">
<h5>Uitwerking 3</h5>
<ol style="list-style-type: decimal">
<li><p><span class="math display">\[\overline{X} = \frac{\sum\limits_{i=1}^{i=n}X_i}{n}=\frac{1}{n}\cdot\sum\limits_{i=1}^{i=n}X_i\]</span>
Het sommatieteken <span class="math inline">\(\Sigma\)</span> met <span class="math inline">\(i=1\)</span> eronder en <span class="math inline">\(i=n\)</span> erboven wil zeggen dat je datgeen wat achter het sommatieteken staat, in ons geval dus alleen <span class="math inline">\(X_i\)</span>, eerst voor alle waarden van <span class="math inline">\(i\)</span> (dus <span class="math inline">\(i=1\)</span> t/m <span class="math inline">\(i=n=20\)</span>) moet invullen en vervolgens (daarna dus) bij elkaar moet optellen. Als ik <em>alleen</em> de sommatie voor alle <span class="math inline">\(X\)</span>-waarden zou willen hebben voor <span class="math inline">\(i=1\)</span> t/m <span class="math inline">\(i=20\)</span> krijg je dus het volgende (ik gebruik hier de rangschikte scores, maar dat maakt natuurlijk niet uit voor de optelling):
<span class="math display">\[\sum\limits_{i=1}^{i=20}X_{i}=\left[X_1 + X_2 +X_3 +X_4+X_5+...+ X_{19} +X_{20}\right]\]</span>
<span class="math display">\[\sum\limits_{i=1}^{i=20}X_{i}=\left[13+14+17+18+18+...+46+58\right]=542\]</span>
Om een sommatieteken uit te werken gebruik ik vaak rechte haakjes. Alles links van het eerste is-gelijk-aan-teken noem ik ook vaak wel dat ‘ding’ (sommatie van alle <span class="math inline">\(X_i\)</span> - scores), maar dat ding heeft dus een waarde van 542 (als je hem netjes en dus correct hebt uitgewerkt). Let op: vaak staat er niks onder of boven het sommatieteken, ze bedoelen dan dat je ‘gewoon’ elke waarde moet nemen.
<span class="math display">\[\overline{X}=E\left(X\right)= \frac{\sum\limits_{i=1}^{i=n}X_i}{n}=\frac{\left[13+14+17+18\;+...+\;45+58\right]}{20}=\frac{542}{20}=27.1\]</span>
of dus:
<span class="math display">\[\overline{X}=E\left(X\right)= \frac{1}{n}\cdot\sum\limits_{i=1}^{i=n}X_i=\frac{1}{20}\cdot\left[13+14+17+18\;+...+\; 45+58\right]=\frac{1}{20}\cdot 542=27.1\]</span>
Zeker voor later is het handig als je beseft dat delen door <span class="math inline">\(20\)</span> hetzelfde is als vermenigvuldigen met het omgekeerde van <span class="math inline">\(20\)</span>. Het omgekeerde van een getal is hetzelfde als ’<span class="math inline">\(1\)</span> gedeeld door dat getal, in dit geval dus <span class="math inline">\(\frac{1}{20}\)</span>.</p></li>
<li><p>Het gemiddelde, de mediaan en de modus verschillen van elkaar. Als de boxplot of de stem-and-leaf plot perfect symmetrisch waren geweest, waren het gemiddelde en de mediaan aan elkaar gelijk geweest. De modus is een beetje een apart verhaal, maar ook hier geldt grofweg hetzelfde. Bij symmetrie in je data (en een normaal-verdeling, kom ik later op terug) zou je wel verwachten dat de modus hetzelfde zou moeten zijn als het gemiddelde en de mediaan!</p></li>
</ol>
</div>
</div>
</div>
</div>
<div id="hoe-is-de-data-verdeeld-spreidingsmaten." class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Hoe is de data verdeeld? Spreidingsmaten.</h2>
<p>In paragraaf 1.1 hebben we gekeken naar de vraag ‘Waar ligt de data?’ Nu gaan we kĳken in hoeverre de data verdeeld is. Als je weet waar (het gros van) de data zich bevindt kun je een voorspelling doen voor iemand uit je steekproef – of zelfs buiten je steekproef, bĳvoorbeeld iemand uit de rest van de populatie. De data uit het belgedrag onderzoek heeft als laagste waarde een score van <span class="math inline">\(13\)</span> en als hoogste een score van <span class="math inline">\(58\)</span>. Als je dan toch een voorspelling of gok moet doen voor een willekeurig persoon uit je steekproef, is het wel handig als je in ieder geval een waarde tussen deze twee uiterste doet. Het gemiddelde is vaak de beste gok mogelĳk. Niet iedereen – of vaak zelfs niemand - binnen je steekproef heeft <em>precies</em> dezelfde waarde als het gemiddelde, maar toch is het handig om het gemiddelde als beste gok of voorspelling te gebruiken. Het gemiddelde gebruiken als beste gok, wil dus ook niet zeggen dat je dan altĳd precies goed gokt, maar wel dat je er <em>gemiddeld gezien</em> (als je dus vaker dan 1 keer zou gokken) er het <em>dichtst bĳ zit</em> met je gok. Anders gezegd: als je het gemiddelde gebruikt als beste voorspelling voor een willekeurig persoon uit je steekproef, zal je gemiddelde gokfout het kleinst zĳn. Wanneer de scores van de verschillende proefpersonen in een steekproef dicht bĳ elkaar liggen, dan zal het duidelĳk zĳn dat de gemiddelde gokfout ook kleiner zal zĳn dan als de proefpersonen onderling juist grotere verschillen vertonen op hun scores (verder van elkaar liggen). De gemiddelde gokfout heet ook wel de standaardafwĳking of standaarddeviatie (de officiële naampjes) en is dan ook een heel handige en veel gebruikte <em>spreidingsmaat</em>. Zoals je later niet zal ontgaan: de standaardafwĳking is <em>heilig</em> binnen de statistiek. We gaan verder op de data uit het belgedrag onderzoek. Voor de volgende vragen is het het handigst als je meteen ook JASP (of R) gebruikt om je handmatige (rekenmachine) berekeningen te controleren. Open het bestand ‘belminuten.sav’ met JASP. Hier nog even de data in een tabelletje.</p>
<table>
<caption>
<span id="tab:belminuten-data2">Tabel 1.3: </span>Belminuten Data
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respondentnummer
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Aantal Belminuten
</div>
</th>
</tr>
<tr>
<th style="text-align:center;">
<span class="math inline">\(i\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(X_i\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
13
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
58
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
31
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
39
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
42
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
17
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
35
</td>
</tr>
<tr>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
46
</td>
</tr>
<tr>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
22
</td>
</tr>
<tr>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
26
</td>
</tr>
<tr>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
14
</td>
</tr>
<tr>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
33
</td>
</tr>
<tr>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
21
</td>
</tr>
</tbody>
</table>
<div id="opgaven-belgedrag-onder-jongeren-in-nederland-spreidingsmaten" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> <em>Opgaven</em> Belgedrag onder Jongeren in Nederland: Spreidingsmaten</h3>
<div id="Opgave1.4" class="opgaven">
<div id="opgave-4" class="section level5 unnumbered">
<h5>Opgave 4</h5>
<ol style="list-style-type: decimal">
<li><p>Bereken het gemiddelde voor de X-scores, ook wel de verwachte waarde (of expected value)
voor de variabele X.</p></li>
<li><p>Van waar tot waar bevinden zich de mogelijke scores? Hoe groot of lang is de lengte van het interval waarop de geobserveerde scores zich bevinden? Anders gezegd: hoe groot is de spreidingsbreedte (<em>range</em>) van onze scores?</p></li>
<li><p>Als je het gemiddelde gebruikt als beste gok voor een willekeurige score, wat is dan de kleinste en wat is dan de grootste gokfout (absoluut gezien)? Geef een schatting voor de gemiddelde gokfout. Wat ik onder een gokfout voor een willekeurige persoon in je steekproef versta, is de afstand tussen de geobserveerde score van die persoon tot het gemiddelde. In het geval van belminuten, onze variabele, is het dus het verschil (afstand, afwijking) tussen de score van een persoon en het gemiddelde voor het aantal belminuten (<span class="math inline">\(X_i\)</span>), ook wel zijn individuele afwijking tot het gemiddelde genaamd. Als een persoon rechts (boven) van het gemiddelde zit qua score dan zien wij dit als een positieve afwijking en negatief als hij zich links van het gemiddelde bevindt. In welke volgorde moet je dan telkens de twee waarden van elkaar aftrekken om niet onterecht een positieve (of negatieve) afwijking te vinden?
We gaan over tot de echte berekening van de standaardafwĳking. Handmatig is het een hoop werk. Aangezien we meestal met statistiek programma’s zoals JASP en R werken, hoeven we dit zelf dus eigenlĳk nooit te doen. Waarom gaan we dit dan doen? Omdat het de nodige rekenvaardigheid en inzichten zal verschaffen die we nodig hebben om later verdere stappen te kunnen nemen. De standaardafwĳking is dus de gemiddelde gokfout als je het gemiddelde zou gebruiken als beste gok, of ook wel de gemiddelde afwĳking (van een observatie) naar het gemiddelde (voor alle observaties). Je zou misschien kunnen denken: dan tel je toch gewoon alle individuele afwĳkingen bĳ elkaar op en deel je het totaal door het aantal afwĳkingen? Maar helaas, het idee is wel juist, maar we komen onderweg een aantal problemen tegen waar we een correctie voor zullen moeten maken.</p></li>
</ol>
</div>
</div>
<div id="Uitwerking1.4" class="uitwerkingen">
<div id="uitwerking-4" class="section level5 unnumbered">
<h5>Uitwerking 4</h5>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\overline{X}=27.1\)</span>.</li>
</ol>
<p><span class="math display">\[\overline{X}= \frac{1}{n}\cdot\sum\limits_{i=1}^{i=n}X_i=\frac{1}{20}\cdot\left[13+14+17+18+18+...+45+58\right]=\frac{1}{20}\cdot 542=27.1\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li><p>De geobserveerde scores lopen vanaf <span class="math inline">\(13\)</span> (minimum) tot en met <span class="math inline">\(58\)</span> (maximum). De spreidingsbreedte of <em>range</em> wordt dan: <span class="math inline">\(Max - Min = 58 - 13 = 45\)</span>. Het interval of lijnstukje waarop zich dus de gemeten scores bevinden, is dus <span class="math inline">\(45\)</span> (Belminuten) lang.</p></li>
<li><p>individuelegokfout <span class="math inline">\(= X_i - X\)</span>
kleinstegokfout = <span class="math inline">\(X_{13} - X = 26 - 27.1 = \text{-}1.1\)</span>
grootstegokfout = <span class="math inline">\(X_{20} − X = 58 − 27.1 = 30.1\)</span>
Ik heb hier dus de nummering voor de <span class="math inline">\(i\)</span>-tjes gebruikt van de scores die we al op volgorde
hadden gezet.
De grootte van een gokfout hangt dus niet af van of het negatief of positief is, maar wel van de (absolute) afstand naar <span class="math inline">\(0\)</span>. De kleinste afwijking is dus <span class="math inline">\(\text{-}1.1\)</span> omdat die het dichtst bij <span class="math inline">\(0\)</span> ligt. Voor een voorlopige schatting voor de gemiddelde gokfout (standdaardafwijking) kunnen we het beste ergens tussen (in het midden) deze twee gokfouten in gaan zitten, ongeveer 16 dus. Na berekening zullen we zien of we ongeveer goed zaten.</p></li>
</ol>
</div>
</div>
<div id="Opgave1.5" class="opgaven">
<div id="opgave-5" class="section level5" number="1.2.1.0.1">
<h5><span class="header-section-number">1.2.1.0.1</span> Opgave 5</h5>
<ol style="list-style-type: decimal">
<li><p>Maak een <span class="math inline">\(21\)</span> x <span class="math inline">\(4\)</span> tabel (<span class="math inline">\(21\)</span> rijen en <span class="math inline">\(4\)</span> kolommen). Zet vanaf de tweede rij, in de eerste kolom de nummering <span class="math inline">\(1\)</span> t/m <span class="math inline">\(20\)</span> (de i-tjes) en daarachter in de tweede kolom de bijbehorende X-scores. Op de eerste rij in het eerste vakje zet je een ‘<span class="math inline">\(i\)</span>’ en in het tweede vakje (in de eerste rij nog steeds) zet je ‘<span class="math inline">\(X_i\)</span>’. Bereken nu voor iedere persoon (observatie) in onze steekproef zijn individuele afwijking naar het gemiddelde, dus de gokfout die je zou maken als je voor die persoon het gemiddelde zou nemen voor zijn voorspelling en dan zou berekenen hoeveel hij er dus naast zit. Iedereen die links van het gemiddelde zit, moet uiteindelijk dus ook een negatieve waarde als gokfout krijgen. Zet deze waarde in de derde kolom.</p></li>
<li><p>Eigenlijk stuiten we hier al op het eerste probleem. Als we - volgens het verkeerde idee (de gokfouten optellen en delen door het aantal) - de individuele afwijkingen nu zouden optellen, dus de sommatie ervan zouden nemen, welke waarde krijgen we dan? Om dit probleem te omzeilen kwadrateren we eerst alle gokfouten voordat we ze gaan optellen. Zet de gekwadrateerde gokfouten in de vierde kolom. Komen in deze kolom nog negatieven waarden voor?</p></li>
<li><p>Als je de waarden in de vierde kolom zou optellen, hoe zou je die waarde in woorden kunnen omschrijven? Bereken deze waarde.</p></li>
</ol>
</div>
</div>
<div id="Theorie" class="definities">
<p><strong><span style="color: blue;">Vrijheidsgraden, <em>Degrees of freedom</em></span></strong></p>
<p>Hier stuiten we op het tweede probleem als we het verkeerde idee zouden volgen. Volgens het <em>verkeerde</em> idee zouden we nu de gevonden kwadratensom (de som van alle gekwadrateerde afwĳkingen) moeten delen door het aantal afwĳkingen of observaties, <span class="math inline">\(n\)</span>. We hadden immers <span class="math inline">\(20\)</span> gokfouten berekend en we willen weten wat de grootte is van de gemiddelde gokfout. Maar zĳn er ook daadwerkelĳk <span class="math inline">\(20\)</span> gokfouten bĳ <span class="math inline">\(20\)</span> observaties? Stel je bent bĳ een echtpaar met drie kinderen (drie observaties) thuis en het echtpaar vertelt je dat deze drie kinderen gemiddeld een leeftĳd hebben van 10 jaar, maar ze spelen nu buiten. Wanneer het eerste kind thuis komt, roep jĳ natuurlĳk dat dat kind wel 10 jaar oud zal zĳn, je bent immers een wetenschapper en gaat dus uit van de beste gok! Het blĳkt echter dat het kind 8 jaar is. Voordat het tweede kind binnenkomt roep je natuurlĳk weer dat ook dat kind wel 10 jaar zal zĳn, maar helaas je hebt het alweer mis want het is <span class="math inline">\(9\)</span> jaar oud. Alleen het derde kind moet nog thuis komen, maar welke leeftĳd zou je nu ‘gokken’? Omdat je weet dat er drie kinderen zĳn, kun je nu de leeftĳd van het laatste kind uitrekenen en hoef je dus niet meer te gokken! Samen (dus opgeteld) moeten de kinderen <span class="math inline">\(30\)</span> jaar oud zĳn om een gemiddelde leeftĳd van <span class="math inline">\(10\)</span> te krĳgen. Je kan dus voordat het derde (laatste) kind binnenkomt al zeggen dat het <span class="math inline">\(13\)</span> jaar oud zou <em>moeten</em> zĳn. In dit geval maak je dus eigenlĳk maar twee gokfouten omdat de laatste waarneming ‘vast’ ligt als de voorgaande bekend zĳn. Je mag hier zeggen dat 2 observaties ‘de vrĳheid’ hebben en dat er <span class="math inline">\(1\)</span> observatie dus vast ligt. In een set of verzameling van <span class="math inline">\(20\)</span> observaties hebben <span class="math inline">\(19\)</span> observaties dus de ‘vrĳheid’ en ligt er dus 1 vast (die je dus niet hoeft te gokken, maar gewoon kan berekenen, als je die andere <span class="math inline">\(19\)</span> observaties weet). In het algemeen zeggen we: een set observaties van n groot heeft <span class="math inline">\(n-1\)</span> vrĳheidsgraden of <em>degrees of freedom</em> (df). Wanneer we de standaardafwĳking willen uitrekenen, delen we de kwadratensom door het aantal vrĳheidsgraden en dus niet door het aantal observaties! Dit doen we dus als correctie voor die ene gokfout die we dus eigenlĳk niet maken. Blĳf qua idee wel denken dat we de kwadratensom ‘gewoon’ door het aantal observaties delen (alleen dus gecorrigeerd voor die ene gokfout die we niet maken). Later in de statistiek komen we complexere berekeningen tegen voor het aantal vrĳheidsgraden bĳ een bepaalde probleemstelling of analyse. Ik zal je er nu niet mee lastig vallen.</p>
</div>
<div id="Opgave1.5" class="opgaven">
<ol start="4" style="list-style-type: decimal">
<li><p>Deel de kwadratensom door bijbehorend aantal vrijheidsgraden, df = n - 1 (‘df’ staat voor degrees of freedom). Wat hebben we hier in woorden berekend, wat is hier de officiële benaming voor?</p></li>
<li><p>De variantie en de standaardafwijking zijn verwant aan elkaar. Om van de variantie naar de standaardafwijking te komen, moet je alleen nog de wortel nemen. Als je van de standaardafwijking naar de variantie wil, moet je alleen nog kwadrateren. Bereken de gemiddelde gokfout ofwel de standaardafwijking Sx.</p></li>
<li><p>Hoe groot zou het gemiddelde en de standaardafwijking zijn als iedereen in onze steekproef drie minuten hoger had gescoord?</p></li>
<li><p>Stel dat je het aantal bel_minuten_ wil omzetten naar het aantal bel_seconden_, wat zou dan gebeuren met het gemiddelde, de standaandafwijking en de variantie? Om de originele scores in minuten te veranderen (te transformeren) naar belseconden, zul je dus elke score moeten vermenigvuldigen met een factor <span class="math inline">\(60\)</span> (<span class="math inline">\(1\)</span> minuut is <span class="math inline">\(1 \cdot 60 = 60\)</span> seconden). Dit kun je doen en alles opniew uitrekenen. Gelukkig kan het óók sneller!</p></li>
</ol>
</div>
<div id="Theorie" class="definities">
<p>Je kunt je de standaardafwĳking ook op een andere manier voorstellen. Als je de scores uitzet zoals in figuur 1.3 hieronder, kun je verticale lĳntjes trekken. Elk beginnend van af het gemiddelde (<span class="math inline">\(\overline{X} = 27.1\)</span>, de horizontale stippel lĳn) tot aan de hoogte van een score. De <em>gemiddelde lengte</em> van die blauwe lĳntjes is dan de standaardafwĳking (wel dus gecorrigeerd voor het aantal vrĳheidsgraden).</p>
<div class="figure"><span style="display:block;" id="fig:belminuten-invidueleafw"></span>
<img src="Bronnen/pictures/H1blauwestreepjesBelm.png" alt="Individuele afwijkingen voor de belminuten data; de blauwe streepjes" width="582" />
<p class="caption">
Figuur 1.4: Individuele afwijkingen voor de belminuten data; de blauwe streepjes
</p>
</div>
</div>
<div id="Uitwerking1.5" class="uitwerkingen">
<div id="uitwerking-5" class="section level5 unnumbered">
<h5>Uitwerking 5</h5>
<ol style="list-style-type: decimal">
<li>De tabel ziet er zo uit:</li>
</ol>
</div>
</div>
<table>
<caption>
<span id="tab:berekening-belminuten-afw">Tabel 1.4: </span>Belminuten
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Respondentnummer
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Aantal belminuten
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Indiviuele Afwijking
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Gekwadrateerde Indiviuele Afwijking
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
<span class="math inline">\(i\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(X_i\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(X_i - \overline{X}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\((X_i - \overline{X})^2\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:center;">
-14.1
</td>
<td style="text-align:center;">
198.81
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
14
</td>
<td style="text-align:center;">
-13.1
</td>
<td style="text-align:center;">
171.61
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
17
</td>
<td style="text-align:center;">
-10.1
</td>
<td style="text-align:center;">
102.01
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:center;">
-9.1
</td>
<td style="text-align:center;">
82.81
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:center;">
-9.1
</td>
<td style="text-align:center;">
82.81
</td>
</tr>
<tr>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:center;">
-8.1
</td>
<td style="text-align:center;">
65.61
</td>
</tr>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
20
</td>
<td style="text-align:center;">
-7.1
</td>
<td style="text-align:center;">
50.41
</td>
</tr>
<tr>
<td style="text-align:left;">
8
</td>
<td style="text-align:left;">
20
</td>
<td style="text-align:center;">
-7.1
</td>
<td style="text-align:center;">
50.41
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
21
</td>
<td style="text-align:center;">
-6.1
</td>
<td style="text-align:center;">
37.21
</td>
</tr>
<tr>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:center;">
-5.1
</td>
<td style="text-align:center;">
26.01
</td>
</tr>
<tr>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
25
</td>
<td style="text-align:center;">
-2.1
</td>
<td style="text-align:center;">
4.41
</td>
</tr>
<tr>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
25
</td>
<td style="text-align:center;">
-2.1
</td>
<td style="text-align:center;">
4.41
</td>
</tr>
<tr>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
26
</td>
<td style="text-align:center;">
-1.1
</td>
<td style="text-align:center;">
1.21
</td>
</tr>
<tr>
<td style="text-align:left;">
14
</td>
<td style="text-align:left;">
31
</td>
<td style="text-align:center;">
3.9
</td>
<td style="text-align:center;">
15.21
</td>
</tr>
<tr>
<td style="text-align:left;">
15
</td>
<td style="text-align:left;">
33
</td>
<td style="text-align:center;">
5.9
</td>
<td style="text-align:center;">
34.81
</td>
</tr>
<tr>
<td style="text-align:left;">
16
</td>
<td style="text-align:left;">
35
</td>
<td style="text-align:center;">
7.9
</td>
<td style="text-align:center;">
62.41
</td>
</tr>
<tr>
<td style="text-align:left;">
17
</td>
<td style="text-align:left;">
39
</td>
<td style="text-align:center;">
11.9
</td>
<td style="text-align:center;">
141.61
</td>
</tr>
<tr>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
42
</td>
<td style="text-align:center;">
14.9
</td>
<td style="text-align:center;">
222.01
</td>
</tr>
<tr>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
46
</td>
<td style="text-align:center;">
18.9
</td>
<td style="text-align:center;">
357.21
</td>
</tr>
<tr>
<td style="text-align:left;">
20
</td>
<td style="text-align:left;">
58
</td>
<td style="text-align:center;">
30.9
</td>
<td style="text-align:center;">
954.81
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
<span class="math inline">\(\sum\limits^{i=9}_{i=1}{X_i} = 542\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\sum\limits^{i=9}_{i=1}{(X_i-\overline{X})} = 0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\sum\limits^{i=9}_{i=1}{(X_i-\overline{X})^2} = 2665.8\)</span>
</td>
</tr>
</tbody>
</table>
<div id="Uitwerking1.5vervolg" class="uitwerkingen">
<ol start="2" style="list-style-type: decimal">
<li><p>De optelling van de getalletjes in de derde kolom is <span class="math inline">\(0\)</span>, de afwijkingen heffen elkaar op! Qua berekening ziet de formule en de uitwerking er als volgt uit:
<span class="math display">\[\sum\limits_{i=1}^{i=20}\left(x_i-\overline{x}\right)=\left[\left(13−27.1\right)+\left(14−27.1\right)+......+\left(46−27.1\right)+\left(58−27.1\right)\right]=0\]</span>
<span class="math display">\[\sum\limits_{i=1}^{i=20}\left(x_i-\overline{x}\right)=\left[\left(\text{-}14.1\right)+ \left(\text{-}13.1\right)+......+\left(18.9\right)+\left(30.9\right)\right]=0\]</span>
<span class="math display">\[\sum\limits_{i=1}^{i=20 }\left(x_i-\overline{x}\right)=\left[ \text{-}14.1+ \text{-}13.1 +......+ 18.9+30.9\right]=0\]</span>
Je moet dus voor elke observatie of persoon het gehele stuk achter het sommatieteken invullen en uitrekenen, daarna ga je dus pas optellen (sommeren).</p></li>
<li><p>Uiteraard kun je op verschillende manieren uitleggen waar de optelling van wat er in de vierde kolom berekend is, voor staat. In ieder geval is het qua formule:</p></li>
</ol>
<p><span class="math display">\[\sum\limits_{i=1}^{i=20}\left(x_i-\overline{x}\right)^2\]</span>
Weer zo’n ‘ding’, maar nu al een stuk complexer dan dat we eerder zijn tegen gekomen. Voordat ik tot benoeming van het ding over ga, eerst maar ‘even’ de volledige berekening in stapjes:
<span class="math display">\[\sum\limits_{i=1}^{i=20}\left(x_i-\overline{x}\right)^2 =\left[\left(13-27.1\right)^2+\left(13-27.1\right)^2+...+\left(46-27.1\right)^2+\left(58-27.1\right)^2\right]\]</span>
<span class="math display">\[\sum\limits_{i=1}^{i=20}\left(x_i-\overline{x}\right)^2=\left[\left(\text{-}14.1\right)^2+\left(\text{-}13.1\right)^2+...+\left(18.9\right)^2+\ \left(30.9\right)^2\right]\]</span>
<span class="math display">\[\sum\limits_{i=1}^{i=20}\left(x_i-\overline{X}\right)^2=\left[198.81+171.61+...+357.21+954.81\right] = 2665.8\]</span>
De uitkomst is dus <span class="math inline">\(2665.8\)</span>, nu nog een benaming. Je kunt zeggen dat de optelling van alle gekwadrateerde gokfouten <span class="math inline">\(2665.8\)</span> is. Of iets moeilijker, maar hetzelfde: <span class="math inline">\(2665.8\)</span> is de sommatie van de gekwadrateerde individuele afwijkingen van een observatie naar het gemiddelde voor <span class="math inline">\(i=1\)</span> tot en met <span class="math inline">\(i=20\)</span>. Kortweg noemen we dit een kwadratensom (ten opzichte van het gemiddelde) of ook wel in het engels: the <em>Sum of Squares Total</em> of afgekort ‘SST’.</p>
<ol start="4" style="list-style-type: decimal">
<li>De uitkomst van wat we hier berekenen noemen we de variantie (<em>variance</em>) van de variabele <span class="math inline">\(X\)</span> of ook wel <span class="math inline">\(S_{x}^{2}\)</span>. Maar wat betekent het? Het is de gemiddelde gekwadrateerde afwijking naar het gemiddelde. Of in meer normalere woorden: de gemiddelde gekwadrateerde gokfout.
<span class="math display">\[S_x^2=\ \frac{\sum\limits_{i=1}^{i=n}\left(X_i-\overline{X}\right)^2}{n-1}=\frac{1}{n-1}\cdot \sum\limits_{i=1}^{i=n}\left(X_1-\overline{X}\right)^2\]</span>
Delen door een getal (19 in ons geval) is hetzelfde als vermenigvuldigen met het omgekeerde (<span class="math inline">\(\frac{1}{19}\)</span>).
<span class="math display">\[S^2_x=\frac{2665.8}{20-1}=\frac{2665.8}{19}=\frac{1}{19}\cdot2665.8 = 140.3053\]</span>
Ik heb hier afgerond op vier decimalen. Blijkbaar is de gemiddelde gekwadrateerde gokfout dus (afgerond) gelijk aan <span class="math inline">\(140.3053\)</span>. Dit getal is nog niet handig. Veel handiger en makkelijker te interpreteren is de gewone gemiddelde gokfout en dus niet de gekwadrateerde. Omdat de optelling van de gewone afwijkingen 0 was, hadden we ze eerst gekwadrateerd. Er volgt dus nog 1 stap, we zijn er dus bijna!</li>
</ol>
<p>5.<span class="math display">\[S_x=\sqrt{S_x^2} = \sqrt{140.3053} = 11.845\]</span>
Eindelijk: we kunnen nu dus zeggen dat de mensen in onze steekproef gemiddeld 27.1 minuten bellen (in de afgelopen week welliswaar) en dat de personen in onze steekproef gemiddeld <span class="math inline">\(11.8\)</span> minuten daar vandaan zitten (zowel daaronder als daarboven). We hebben nu dus eindelijk een idee in hoeverre de respondenten in onze steekproef verdeeld zijn op de variabele <span class="math inline">\(X\)</span>, ‘aantal belminuten in de afgelopen week’. De waarde <span class="math inline">\(11.8\)</span> komt redelijk overeen met de eerder geschatte waarde voor de standaardafwijking in opgave 1.4b. Daar had ik ongeveer 16 gezegd. De berekende waarde <span class="math inline">\(11.8\)</span> is kleiner omdat er naar verhouding meer kleine gokfouten zitten dan grote, vandaar de iets kleinere waarde.</p>
<ol start="6" style="list-style-type: decimal">
<li>Het gemiddelde schuift drie punten op naar boven/rechts.
<span class="math display">\[ \overline{X}_{nieuw}= 27.1 + 3 = 30.1\]</span>
Als iedereen qua score hetzelfde verandert, verandert het gemiddelde dus gewoon mee, op dezelfde manier. Voor de standaardafwijking maakt het niks uit, die blijft gelijk. De individuele gokfouten blijven hetzelfde, de gemiddelde gokfout dus ook. Het enige wat verandert is <em>waar</em> iets gebeurt (zich de scores bevinden), maar de onderlinge verschillen tussen de scores veranderen dus niet. Vandaar dat een centrummaat dus wel verandert maar een spreidingsmaat niet.</li>
</ol>
<p>7.Om een oude of originele score te veranderen en dus een nieuwe getransformeerde score te maken:
<span class="math display">\[X_{nieuw} = b \cdot X_{origineel}\]</span>
waarbij ‘<span class="math inline">\(b\)</span>’ voor het getal staat waarmee je moet vermenigvuldigen. In ons geval is de waarde van <span class="math inline">\(b\)</span> dus <span class="math inline">\(60\)</span> omdat we van minuten naar seconden willen gaan.
Om de nieuwe standaardafwijking (<span class="math inline">\(S_{nieuw}\)</span>) voor de nieuwe scores in één keer uit te kunnen rekenen gebuik je de volgende formule:
<span class="math display">\[S_{nieuw} = b \cdot S_{oud}\]</span>
<span class="math display">\[S_{nieuw} = 60 \cdot 11.845 = 710.7\]</span>
De nieuwe standaardafwijking (<span class="math inline">\(S_{x_{nieuw}}\)</span>) heeft dus een waarde van <span class="math inline">\(710.7\)</span>.
En om in een keer te springen van de originele variantie (<span class="math inline">\(S_{oud}^2\)</span>) naar de nieuwe variantie (<span class="math inline">\(S_{x_{nieuw}}^2\)</span>) gebruik je een kwadraatje in je formule (leuk hè?):
<span class="math display">\[S_{nieuw}^2 = b^2 \cdot S_{oud}^2\]</span>
<span class="math display">\[S_{nieuw}^2 = 60^2 \cdot 140.3053 = 3600 \cdot 140.3053 = 505099.1\]</span>
De nieuwe variantie (<span class="math inline">\(S_{x_{nieuw}}^2\)</span>) heeft dus een waarde van <span class="math inline">\(505099.1\)</span>.</p>
</div>
<div id="JaspUitwerking1.4en5" class="jaspuitwerkingen">
<div id="jasp-uitwerking-opgave-4-5-6-en-7" class="section level5 unnumbered">
<h5>JASP Uitwerking Opgave 4, 5, 6 en 7</h5>
<ul>
<li><p>We hadden het gemiddelde voor het aantal belminuten natuurlijk allang opgevraagd, je kreeg het gemiddelde (en de standaardafwijking) gewoon kado bij de eerste opgave a.d.h.v. ‘Descriptives’. Ik maak graag gebruik van deze gelegenheid om wat tussen antwoorden (zoals individuele gekwadrateerde afwijkingen) te checken. Om dit te doen, gaan we wat nieuwe variabelen (kolommen) aanmaken in ons databestand. Dus open weer even, vanuit het programma JASP, het ‘BelminutenData.csv’ databestand en sla het bestand meteen even op ondere een andere naam (zodat we het originele bestand altijd nog hebben):</p>
<ul>
<li>Druk op het icoontje voor het ‘Main Menu’ linksboven en kies ‘Save as’, vervolgens ‘Computer’ en kies dan ‘Browse’ of meteen de folder waar je het bestand wil opslaan.
<ul>
<li>En natuurlijk kies je dan een naam die te herleiden is naar wat je doet: dus bijvoorbeeld “BelminutenDataOpgave4en5.csv”.</li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en501.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en502.png" width="50%" /></p>
<ul>
<li><p>Om de variantie (<span class="math inline">\(S_x^2=140.3053\)</span>) en de standaardafwijking (<span class="math inline">\(S_x=11.845\)</span>) handmatig te berekenen, hebben wij een aantal tussen stappen genomen, die gaan we nu met JASP:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>Voor het gemiddelde moesten we de som van de scores hebben (en dan nog delen door het aantal)</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>Neem voor iedereen de individuele afwijking van het gemiddelde: <span class="math inline">\(X_i - \bar{X}\)</span></li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>voor iedereen de individuele afwijking kwadrateren: <span class="math inline">\((X_i - \bar{X})^2\)</span></li>
</ol></li>
<li><ol start="4" style="list-style-type: decimal">
<li>De som berekenen van alle individuele gekwadrateerde afwijkingen, dus de ‘kwadratensom’: <span class="math inline">\(\sum\limits_{i=1}^{i=n}(X_i - \bar{X})^2\)</span></li>
</ol></li>
<li><ol start="5" style="list-style-type: decimal">
<li>Voor de variantie deel je de kwadratensom door het aantal vrijheidsgraden: <span class="math inline">\(S_x^2=\frac{\sum\limits_{i=1}^{i=n}(X_i - \bar{X})^2}{n-1}\)</span></li>
</ol></li>
<li><ol start="6" style="list-style-type: decimal">
<li>Voor de standaardafwijking neem je nog de wortel van de variantie: <span class="math inline">\(S_x = \sqrt{S_x^2}\)</span></li>
</ol></li>
</ul></li>
</ul>
<!-- hier graag een witregel -->
<!-- hier graag een witregel -->
<ul>
<li><p>Stap <span class="math inline">\(2\)</span> en <span class="math inline">\(3\)</span> kunnen we doen met twee nieuwe variabelen (kolommen met data). Stap <span class="math inline">\(4\)</span> weer aan de hand van ‘Descriptives’. Voor tweede stap heb je dus wel het gemiddelde vast nodig en die is <span class="math inline">\(\bar{X}=27.1\)</span>; Nu kunnen we voor iedereen zijn individuele afwijking laten uitrekenen:</p>
<ul>
<li><p>Druk op het plusje rechtsboven de kolom voor ‘belminuten’ om een nieuwe kolom te maken</p>
<ul>
<li><p>In dit scherm kun je een naam geven aan je nieuwe variabele en kiezen of je deze met een ‘R-code’ wilt aanmaken of met het ‘handje’ (drag and drop gedoe).</p></li>
<li><p>Ik heb de nieuwe variabele de naam ‘ind_afw’ gegeven, je mag ook andere namen verzinnen natuurlijk (mocht je rare leestekens gebruiken, kijk dan wel of JASP het accepteerd, een ‘laag streepje of <em>underscore</em>’ is in ieder geval prima)</p></li>
<li><p>Al is de ‘R-code’ eigenlijk handiger om een nieuwe variabele te brekeken, we doen het nu toch even met het ‘handje’ (net even iets intuïtiever, maar geeft wel minder mogelijkheden). Een indivuele afwijking is ook gewoon een numerieke variabele en we kunnen dus de standaard optie ‘Scale’ (interval meetniveau en hoger) aan laten staan. Kies nu ‘Create Column’,</p>
<ul>
<li><p>Je ziet nu een nieuwe <em>lege</em> kolom, met een raar <span class="math inline">\(F_x\)</span>-tekentje en de variabelenaam ‘ind_afw’ erboven.</p></li>
<li><p>Je ziet ook een raampje waar we (formule voor) de berekening kunnen invoeren. Gaan we doen, <em>drag, drop and type</em>!</p></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en503.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en504.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en507.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en508.png" width="50%" /></p>
<ul>
<li><p>Wij willen het verschil tussen de observatie (<span class="math inline">\(X_i\)</span> of ‘belminuten’) en het gemiddelde. En natuurlijk in de volgorde van “Observed - Expected”, bij ons dus: ‘belminuten’<span class="math inline">\(- 27.1\)</span>. Sleep dus de variabele ‘belminuten’ naar het raampje.</p>
<ul>
<li><p>Vervolgens sleep je het min-teken erbij.</p></li>
<li><p>Dan type je nog, waar die drie puntjes staan, ‘<span class="math inline">\(27.1\)</span>’ en druk dan op ‘Compute column’.</p>
<ul>
<li><p>Nu zie je, als het goed is, een nieuwe kolom naast de variabele ‘belminuten’ met de naam ‘ind_afw’ met links een lineaaltje met een soort ‘<span class="math inline">\(F_x\)</span>’-teken (zodat je straks herkent dat je zelf die kolom/variabele hebt aangemaakt). Druk op het zwarte kruisje (helemaal rechts naast het de ‘i’ voor extra hulp) om het ‘rekenscherm’ af te sluiten, zodat we alleen weer de kolommen zien.</p>
<ul>
<li>Na zo’n berekening, kijk ik altijd even naar mijn data om te checken of het goed is gegaan. Klopt het dat persoon met <span class="math inline">\(id = 1\)</span> een afwijking heeft van <span class="math inline">\(-14.1\)</span>, zoja, dan zal de rest ook wel kloppen denk ik zo.</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en509.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en510.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en511.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en512.png" width="50%" /></p>
<ul>
<li><p>De gekwadrateerde afwijkingen wil ik ook zien,dus we maken weer een nieuwe kolom aan om nieuwe data aan te maken. Dus nog een keer op het zwarte ‘plusje’ drukken voor een nieuwe kolom. Geef eerst weer een nieuwe naam, bijvoorbeeld ‘gekw_ind_afw’. Omdat het weer een <em>scale</em> (interval) variabele is, kun je die voorkeur aan laten staan en we doen de berekening nog een keer met het ‘handje’. Druk dus op ‘Create Column’.</p>
<ul>
<li><p>We willen de gekwadrateerde individuele afwijking per persoon berekenen: <span class="math inline">\((X_i-\bar{X})^2 = \text{ind_afw}^2\)</span>. We hoeven dus alleen nog de kolom ‘ind_afw’ te kwadrateren (elke waarde in die kolom dus, maar dat gaat vanzelf).</p></li>
<li><p>Sleep de variabele ‘ind_afw’ naar het rekenscherm,</p>
<ul>
<li><p>Gebruik het dakje (‘^’) voor ‘tot de macht’;</p>
<ul>
<li>Type dan een ‘<span class="math inline">\(2\)</span>’ om de individuele afwijking (‘ind_afw’) te kwadrateren (tot de macht <span class="math inline">\(2\)</span> te doen). Druk vervolgens op ‘Compute Column’ om de kolom te vullen met nieuwe data.</li>
<li>Controleer voor de eerste persoon of het kwadraat klopt. <span class="math inline">\((-14.1)^2= 198.81\)</span></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en513.png" width="45%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en514.png" width="45%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en515.png" width="45%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en516.png" width="45%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en517.png" width="45%" /></p>
<ul>
<li><p>Okay we hebben nu twee tussenstappen uitgevoerd om tot de variantie en de standaardafwijking te komen. De volgende stap is de ‘kwadratensom’ dus de optelling van alle gekwadrateeerde individuele afwijkingen.</p>
<ul>
<li><span class="math inline">\(\sum\limits_{i=1}^{i=n}(X_i-\bar{X})^2 = \sum\limits_{i=1}^{i=n}\text{ind_afw}^2\)</span></li>
</ul></li>
<li><p>Als je de som (van data-punten) neemt, bereken je een statistiek, dit betekent dus dat we de volgende stap met de ‘Descriptives’ optie kunnen (moeten) doen:</p>
<ul>
<li><p>Druk op ‘Desrcriptives’ en voeg allebei de aangemaakte variabelen toe aan de box onder ‘Variables’ (Ja, ik doe ze even allebei, dus ‘ind_afw’ en ‘gekw_ind_afw’).</p>
<ul>
<li>Om de som op te vragen, klik je op de balk met ‘Statistics’ en vink je de optie ‘Sum’ aan.</li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en518.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en519.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en520.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave4en521.png" width="50%" /></p>
<ul>
<li><p>Wen er maar vast aan, ik had toevallig mijn instellingen op de ‘wetenschapppelijke notatie’ staan: Je ziet dus weer zo’n lekker irritant getal staan bij het gemiddelde voor de individuele afwijkingen;</p>
<ul>
<li><p><span class="math inline">\(-1.421e-15\)</span> uitgeschreven naar de normale notatie betekent dit dus;</p>
<ul>
<li><p><span class="math inline">\(\text{-}1.421e\text{-}15 = \text{-}1.421 \cdot 10^{\text{-}15} -0.000000000000001421\)</span> oftewel een super klein getalletje, net iets onder nul of;</p>
<ul>
<li>Afgerond op twee decimalen dus gewoon <span class="math inline">\(0.00\)</span>. Wat trouwens <em>altijd</em> zo is, of waar is voor het gemiddelde (en ook voor de som) van (alle) individuele afwijkingen van een steekproef! Klopt dus!</li>
</ul></li>
</ul></li>
</ul></li>
<li><p>Ook de som (<em>sum</em>) van de <em>gewadrateerde</em> individuele afwijkingen klopt met onze handmatige berekening:</p>
<ul>
<li><p><span class="math inline">\(\sum\limits_{i=1}^{i=n}(X_i-\bar{X})^2 = \sum\limits_{i=1}^{i=n}\text{ind_afw}^2 = 2665.80\:\:\:\)</span></p>
<ul>
<li><p>Om vervolgens de variantie (<span class="math inline">\(S_x^2\)</span>) voor de variabele ‘belminuten’ te berekenen, deel je de kwadratensom nog door het aantal vrijheidsgraden (<span class="math inline">\(df = n-1\)</span>);</p></li>
<li><p><span class="math inline">\(S_x^2 = \frac{\sum\limits_{i=1}^{i=n}(X_i-\bar{X})^2}{n-1} = \frac{2665.80}{20-1} = 140.3053\)</span></p>
<ul>
<li><p>Voor de standdaarafwijking <span class="math inline">\(S_x\)</span> neem je alleen nog de wortel van de variantie;</p></li>
<li><p><span class="math inline">\(S_x= \sqrt{S_x^2} = \sqrt{140.3053} = 11.845\)</span></p>
<ul>
<li>We kunnen dus zeggen dat de gemiddelde afstand van een observatie naar het gemiddelde (een blauw streepje dus) de waarde <span class="math inline">\(11.845\)</span> is, onze gemiddelde gok-fout als we ‘het spelletje’ zouden spelen.</li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
<li><p>Als laatste (opgave <span class="math inline">\(6\)</span> en <span class="math inline">\(7\)</span>) wil ik nog kijken naar de waarde van de waarde van het gemiddelde, de standaardafwijking en de variantie, als we een andere meeteenheid zouden nemen, in mijn voorbeeld dus de beltijd gemeten in ‘belseconden’ in plaats van ‘belminuten’. Om dit toe doen maken we eerst weer een nieuwe variabele ‘belseconden’ in JASP aan door de originele variabele ‘belminuten’ te vermenigvuldigen met <span class="math inline">\(60\)</span> (voor iedere minuut tel je <span class="math inline">\(60\)</span> seconden, dus bijvoorbeeld <span class="math inline">\(2\)</span> min zou <span class="math inline">\(2 \cdot 60 = 120\)</span> seconden moeten zijn, de vermenigvuldigingsfactor; ‘<span class="math inline">\(b = 60\)</span>’) en daarna vragen we gewoon het gemiddelde, de variantie en de standaardafwijking op voor onze nieuwe variabele ‘belseconden’ met de optie ‘Descriptives’.</p>
<ul>
<li><p>Zorg dat je in het data-scherm zit en druk op het zwarte ‘plusje’ om een nieuwe kolom aan te maken. Geef vervolgens een nieuwe naam aan je variabele, ‘bel_seconden’ bijvoorbeeld. En kies, voor de verandering, de optie ‘R’ (in plaats van het ‘handje’) om de boel te berekenen, vaak makkelijker, maar let wel goed op hoofdletters, kleine letters en leestekens zoals lage streepjes of spaties, maar ook: probeer het gewoon en kijk of het werkt!</p>
<ul>
<li>Type in het scherm je berekening voor de nieuwe variabele ‘bel_seconden’; dus <code>belminuten * 60</code> (het sterretje gebruiken als het vermenigvuldigings- of keerteken) en druk vervolgens op ‘Compute Column’.</li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en701.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en702.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en704.png" width="50%" /></p>
<ul>
<li><p>Nu kunnen we de ‘Descriptives’ opvragen en kijken of onze handmatige berekeningen uit opgave <span class="math inline">\(6\)</span> en <span class="math inline">\(7\)</span> kloppen;</p>
<ul>
<li><p>Druk op ‘Descriptives’ en voeg de variabele ‘bel_seconden’ toe aan de box.</p>
<ul>
<li>Vraag ook de variantie op (de rest heb je nu al) door onder de balk voor ‘Statistics’. En check zelf maar of de uitkomsten kloppen met onze eerder berekeningen.</li>
</ul></li>
</ul></li>
</ul>
<p><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en705.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en706.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en707.png" width="50%" /><img src="Bronnen/JASP%20Pictures/Ch1JASP/opgave6en708.png" width="50%" /></p>
<p>Als je de boel wilt afsluiten en je ook je nieuwe variabelen wil bewaren, kies je via het ‘Main Menu’ de optie ‘Save’ (je had immers al een nieuwe naam gegeven aan je databestand, anders kies je dus ‘Save As’…). Nu kun je JASP afsluiten en je nieuwe databestand blijft dan bewaard.</p>
</div>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hoofdstuk-0.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="hoofdstuk-2---de-normaalverdeling..html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": [["Handleiding_Statistiek_met_JASP.pdf", "PDF"]],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
