<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 9.5 · ANCOVA: een groep én een getal – JASP-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_interactie.html" rel="next">
<link href="../20_blokken/blok_anova.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_dummy_regressie.html">H9 · Groepen zijn ook getallen</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_ancova.html">Oefening 9.5 · ANCOVA: een groep én een getal</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">JASP-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JASP-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in JASP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Vierde beweging · Verschil onthechten</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_dummy_regressie.html">H9 · Groepen zijn ook getallen</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_ancova.html">Oefening 9.5 · ANCOVA: een groep én een getal</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 9.5 · ANCOVA: een groep én een getal</h1>
<p class="subtitle lead">Een covariaat naast een nominale voorspeller · <em>analysis of covariance</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#een-verschil-dat-van-teken-wisselt" id="toc-een-verschil-dat-van-teken-wisselt">Een verschil dat van teken wisselt</a></li>
  <li><a href="#zet-een-getal-naast-een-groep" id="toc-zet-een-getal-naast-een-groep">Zet een getal naast een groep</a></li>
  <li><a href="#waar-die-duizend-gram-gebleven-is" id="toc-waar-die-duizend-gram-gebleven-is">Waar die duizend gram gebleven is</a></li>
  <li><a href="#de-aanname-die-zakte-en-wat-je-dan-doet" id="toc-de-aanname-die-zakte-en-wat-je-dan-doet">De aanname die zakte, en wat je dan doet</a></li>
  <li><a href="#van-soort-naar-sekse-nu-met-een-aanname-die-houdt" id="toc-van-soort-naar-sekse-nu-met-een-aanname-die-houdt">Van soort naar sekse — nu met een aanname die houdt</a></li>
  <li><a href="#de-afsluiter-van-het-hele-hoofdstuk" id="toc-de-afsluiter-van-het-hele-hoofdstuk">De afsluiter van het hele hoofdstuk</a></li>
  <li><a href="#schrijf-het-op-als-een-onderzoeker" id="toc-schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="een-verschil-dat-van-teken-wisselt" class="level2">
<h2 class="anchored" data-anchor-id="een-verschil-dat-van-teken-wisselt">Een verschil dat van teken wisselt</h2>
<p><span class="begrippen">groepsverschil · derde variabele · correctie</span></p>
<p>Je kent deze drie stapeltjes inmiddels goed.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> In deze pinguïns wegen de Chinstraps gemiddeld 32.43 gram méér dan de Adélies — bijna niks — en de Gentoo’s 1375.35 gram méér, ruim een kilo voorsprong. Die verschillen heb je in de vorige oefening getoetst, klaar.</p>
<p>Nu doen we iets kleins. We zetten vinlengte in het model, naast soort. Eén kolom erbij, meer niet — er wordt geen pinguïn opnieuw gewogen. En kijk wat er met precies dezelfde twee getallen gebeurt: de voorsprong van de Gentoo’s zakt van 1375.35 naar 266.81 gram, en de Chinstraps wegen in dit model opeens 206.51 gram mínder dan de Adélies. Van ietsje zwaarder naar duidelijk lichter. Het verschil klapt om van plus naar min, en niemand heeft de data aangeraakt.</p>
<p>Een getal dat van teken wisselt zodra er een tweede kolom mag meekijken — dat wil je verklaard hebben. Wat weet die vin dat de weegschaal alleen niet ziet? Trek even mee.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="zet-een-getal-naast-een-groep" class="level2">
<h2 class="anchored" data-anchor-id="zet-een-getal-naast-een-groep">Zet een getal naast een groep</h2>
<p><span class="begrippen">covariaat · factor · ANCOVA</span></p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open <code>diamantjes.csv</code>. De kolom <code>D</code> ken je uit de dummy-oefening: <strong>1</strong> voor een sterretje, <strong>0</strong> voor een golfje.</li>
<li><strong>Eerst alleen het merk</strong> — verschillen golfje en sterretje in glans? <strong>Regression → Linear Regression</strong>, <code>glans</code> naar <strong>Dependent Variable</strong> en <code>D</code> naar <strong>Covariates</strong>. In <em>Coefficients</em>: <code>D</code> <strong>20.00</strong>, <em>p</em> = .114.</li>
<li><strong>En nu met gladheid ernaast</strong>: sleep ook <code>gladheid</code> naar <strong>Covariates</strong>. Dezelfde rij <code>D</code> zegt nu <strong>14.95</strong>, <em>p</em> = .001.</li>
</ol>
</div>
</div>
<p>Kijk daar even naar, want het gaat de andere kant op dan je misschien verwacht. Op de twaalf steentjes lijken de twee merken twintig punten glans te schelen, maar met zoveel ruis eromheen haalt dat verschil de drempel niet: <em>p</em> = .11. Zet je gladheid ernaast, dan wordt het verschil <strong>kleiner</strong> (14.95) en tegelijk <strong>significant</strong> (<em>p</em> = .001). De <em>R</em>² springt van .231 naar .945.</p>
<p>Dat is geen goochelarij. Gladheid verklaart een enorm deel van de glans-verschillen, en zolang die verschillen als ruis in het model blijven zitten, verdrinkt het merk-effect erin. Reken gladheid weg en de ruis krimpt — waardoor je het merkverschil ineens wél kunt zien.</p>
<p><strong>Nu jij</strong> — bij de pinguïns, waar de covariaat het omgekeerde doet. Bij de steentjes haalde gladheid ruis wég en maakte het merkverschil daarmee <em>zichtbaar</em>. Bij de pinguïns gaat de vinlengte het soortverschil juist grotendeels <em>opeten</em>. Allebei zijn het redenen om een covariaat te gebruiken — de eerste heet ruis wegnemen, de tweede vertekening wegnemen.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · eerst de soort alleen, dan de vin erbij · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · eerst de soort alleen, dan de vin erbij · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Open <code>penguins.csv</code> in JASP (menu linksboven → Open). Voor dit blok houd je de Adélies als vertrekpunt aan, zoals in de dummy-oefening afgesproken — dus bouw je de dummy’s <code>chinstrap</code> en <code>gentoo</code>. Heb je <code>chinstrap</code> nog staan van die oefening, dan hoeft alleen <code>gentoo</code> erbij: een berekende kolom (klik op de <strong><code>+</code></strong> rechts van de laatste kolom, icoon <strong>R</strong>) met</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(soort <span class="sc">==</span> <span class="st">"Gentoo"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Kijk of hij staat waar je denkt: <strong>Frequencies → Contingency Tables</strong>, <code>gentoo</code> in <strong>Rows</strong> en <code>soort</code> in <strong>Columns</strong> — 123 Gentoo’s op 1, alle andere op 0.</p></li>
<li><p><strong>Model 1 — alleen de soort.</strong> Dit is de eenweg-ANOVA uit de vorige oefening, nu als regressie geschreven. <strong>Regression → Linear Regression</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>chinstrap</code> en <code>gentoo</code> naar <strong>Covariates</strong>. In <em>Coefficients</em>: intercept <strong>3700.66</strong>, <code>chinstrap</code> <strong>32.43</strong>, <code>gentoo</code> <strong>1375.35</strong>; in <em>Model Summary</em> drukt JASP <strong>0.670</strong> af.</p></li>
<li><p><strong>Model 2 — de vinlengte erbij.</strong> Sleep ook <code>vinlengte</code> naar <strong>Covariates</strong>. In <em>Coefficients</em> staat nu:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>−4031.48</td>
</tr>
<tr class="even">
<td>vinlengte</td>
<td>40.71</td>
</tr>
<tr class="odd">
<td>chinstrap</td>
<td>−206.51</td>
</tr>
<tr class="even">
<td>gentoo</td>
<td>266.81</td>
</tr>
</tbody>
</table>
<p>En in <em>Model Summary</em>: <strong>0.783</strong>.</p></li>
<li><p>Vraag bij allebei de modellen onder <strong>Statistics</strong> ook <strong>Confidence intervals</strong> op — die heb je verderop in dit blok nodig.</p></li>
</ol>
</div>
</div>
<p>Schrik niet van dat eerste getal, −4031.48: dat is het intercept, en het voorspelt het gewicht van een pinguïn met een vin van nul millimeter. Die bestaat niet, dus het getal betekent niets — precies zoals in oefening 8.1. Laat hem staan en kijk naar de rest.</p>
<p>Zet de twee soort-regels onder elkaar en je ziet waar de prikkel over ging:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>model 1 (alleen soort)</th>
<th>model 2 (vin erbij)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Chinstrap t.o.v. Adélie</td>
<td><strong>+32.43</strong></td>
<td><strong>−206.51</strong></td>
</tr>
<tr class="even">
<td>Gentoo t.o.v. Adélie</td>
<td><strong>+1375.35</strong></td>
<td><strong>+266.81</strong></td>
</tr>
</tbody>
</table>
<p>Dit model — een <strong>nominale voorspeller</strong> (de soort) naast een <strong>getalsmatige</strong> voorspeller (de vinlengte) — heeft een eigen naam: <strong>ANCOVA</strong>, <em>analysis of covariance</em>. De getalsmatige voorspeller die je erbij zet heet de <strong>covariaat</strong>, en de groepsvariabele heet de <strong>factor</strong>.</p>
<p>Laat die naam je niet imponeren. Kijk nog eens naar het kader hierboven: het is gewoon een regressie met twee voorspellers, precies zoals in de vorige oefeningen. Wat er anders is, is niet de som maar de <strong>vraag</strong> — je wilt de groepen vergelijken, en de covariaat zit erin om die vergelijking eerlijker te maken.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="waar-die-duizend-gram-gebleven-is" class="level2">
<h2 class="anchored" data-anchor-id="waar-die-duizend-gram-gebleven-is">Waar die duizend gram gebleven is</h2>
<p><span class="begrippen">gecorrigeerde gemiddelden · vergelijkbaar maken</span></p>
<p>De Gentoo’s verloren ruim duizend gram voorsprong. Waar ging die heen?</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · hoe lang zijn die vinnen eigenlijk?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · hoe lang zijn die vinnen eigenlijk?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives → Descriptive Statistics</strong>, <code>vinlengte</code> bij <strong>Variables</strong> en <code>soort</code> bij <strong>Split</strong>: Adelie <strong>189.95</strong>, Chinstrap <strong>195.82</strong>, Gentoo <strong>217.19</strong>.</p>
</div>
</div>
<p>Daar staat het. De Gentoo’s hebben vinnen van gemiddeld 217 millimeter, tegen 190 bij de Adélies — ruim zevenentwintig millimeter langer. En je weet uit oefening 8.1 wat een millimeter vin waard is: zo’n veertig gram. Een flink deel van “de Gentoo is zwaarder” was dus eigenlijk “de Gentoo heeft langere vinnen”.</p>
<p>Model 2 vraagt daarom iets anders dan model 1. Niet: <em>hoeveel schelen deze soorten in gewicht?</em> Maar: <strong>hoeveel zouden ze schelen als ze allemaal dezelfde vinlengte hadden?</strong> Je maakt de groepen op papier vergelijkbaar op de covariaat, en kijkt wat er van het verschil overblijft.</p>
<p>Dat kun je ook echt uitrekenen. Vraag het model wat het voorspelt voor elke soort bij één en dezelfde vinlengte — bijvoorbeeld de gemiddelde:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de gecorrigeerde gemiddelden">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de gecorrigeerde gemiddelden
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>ANOVA → ANCOVA</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>soort</code> naar <strong>Fixed Factors</strong> en <code>vinlengte</code> naar <strong>Covariates</strong>.</li>
<li>Vouw <strong>Marginal Means</strong> open en sleep <code>soort</code> naar het rechtervak.</li>
</ol>
<p>In de tabel <em>Marginal Means</em>: Adelie <strong>4146.86</strong>, Chinstrap <strong>3940.35</strong>, Gentoo <strong>4413.67</strong> — het model doorgerekend bij de gemiddelde vinlengte, 200.92 mm.</p>
<p>Ter vergelijking de ruwe gemiddelden: <strong>Descriptives → Descriptive Statistics</strong>, <code>gewicht</code> bij <strong>Variables</strong> en <code>soort</code> bij <strong>Split</strong> — 3700.66, 3733.09, 5076.02.</p>
</div>
</div>
<p>Deze heten de <strong>gecorrigeerde gemiddelden</strong> (<em>adjusted means</em>): wat elke soort naar verwachting zou wegen bij een vin van 200.92 millimeter. Ruw liggen ze op 3700, 3733 en 5076 — een kloof van bijna veertienhonderd gram. Gecorrigeerd liggen ze op 4147, 3940 en 4414: nog steeds verschillend, maar veel dichter bij elkaar, en de Chinstrap is nu de <strong>lichtste</strong> in plaats van de middelste.</p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Vragen bij dit model">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Vragen bij dit model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoeveel van het verschil in gewicht verklaart model 1, en hoeveel model 2? <em>(rapporteer beide R²)</em></p>
<p><strong>b)</strong> Toets model 2 als geheel. Schrijf de nulhypothese eerst voluit op. <em>(rapporteer R², F(df<sub>1</sub>, df<sub>2</sub>) en p)</em></p>
<p><strong>c)</strong> Wat voegt de vinlengte toe bovenop de soort? Vink in <strong>Linear Regression</strong> onder <strong>Statistics</strong> het vakje <strong>R² change</strong> aan en zet onder <strong>Model</strong> de dummy’s <code>chinstrap</code> en <code>gentoo</code> in het nulmodel (<strong>Add to null model</strong>); de regel van het tweede model in <em>Model Summary</em> geeft je de <em>F</em> Change. <em>(rapporteer F(df<sub>1</sub>, df<sub>2</sub>), p en ΔR²)</em></p>
<p><strong>d)</strong> En andersom — wat voegt de soort toe bovenop de vinlengte? Ruil om: nu staat alleen <code>vinlengte</code> in het nulmodel. <em>(rapporteer F(df<sub>1</sub>, df<sub>2</sub>), p en ΔR²)</em></p>
<p><strong>e)</strong> Zijn de twee soort-verschillen in model 2 significant? <em>(rapporteer per soort b, SE, t en p)</em></p>
<p><strong>f)</strong> Welke soort is de referentiecategorie, en waaraan zie je dat?</p>
<p><strong>g)</strong> Waarom is de Chinstrap ruw ietsje zwáárder dan de Adélie, maar gecorrigeerd ruim tweehonderd gram lichter? Kijk naar de gemiddelde vinlengtes.</p>
<p><strong>Z)</strong> Mag je dit model eigenlijk wel gebruiken? Een ANCOVA heeft één aanname die de gewone regressie niet heeft: de covariaat moet in élke groep <strong>dezelfde helling</strong> hebben. Toets dat door een model mét interactie ernaast te leggen — in <strong>ANOVA → ANCOVA</strong> voeg je die onder <strong>Model</strong> toe — en kijk ook naar de drie hellingen apart.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Model 1: <em>R</em>² = .670. Model 2: <em>R</em>² = .783.</p>
<p><strong>b)</strong> De nulhypothese: dit model — vinlengte en soort samen — verklaart níéts van de verschillen in gewicht; de <em>R</em>² is in de populatie nul. Uitkomst: <em>R</em>² = .783, <em>F</em>(3, 338) = 405.69, <em>p</em> &lt; .001. De <em>F</em> staat in de <em>ANOVA</em>-tabel onder je <em>Model Summary</em>.</p>
<p><strong>c)</strong> <em>F</em>(1, 338) = 175.69, <em>p</em> &lt; .001, Δ<em>R</em>² = .113. Fors: de vin brengt echt iets nieuws mee.</p>
<p><strong>d)</strong> <em>F</em>(2, 338) = 18.39, <em>p</em> &lt; .001, Δ<em>R</em>² = .024. Twee vrijheidsgraden, want de soort bracht twee dummy’s mee. Ook significant, maar veel kleiner — en dat is het punt van dit blok: het meeste van wat “soortverschil” leek, was vinlengte.</p>
<p>En herken je dit getal? Kijk nog eens naar de <em>ANCOVA</em>-tabel waarmee je de gecorrigeerde gemiddelden opvroeg: daar staat bij <code>soort</code> precies deze <em>F</em>(2, 338) = 18.39, en bij <code>vinlengte</code> de 175.69 van vraag c). Die tabel toetst per voorspeller wat hij toevoegt bovenop de andere — dezelfde som als jouw twee nulmodellen.</p>
<p><strong>e)</strong> Ja, allebei. Chinstrap tegenover Adélie: <em>b</em> = −206.51, <em>SE</em> = 57.73, <em>t</em>(338) = −3.58, <em>p</em> &lt; .001. Gentoo tegenover Adélie: <em>b</em> = 266.81, <em>SE</em> = 95.26, <em>t</em>(338) = 2.80, <em>p</em> = .005.</p>
<p><strong>f)</strong> Adélie. Die komt in geen enkele rij van de tabel voor — jij hebt zelf <code>chinstrap</code> en <code>gentoo</code> gebouwd en de Adélies weggelaten, precies zoals bij de dummy-oefening.</p>
<p><strong>g)</strong> Omdat de Chinstraps langere vinnen hebben dan de Adélies (195.82 tegen 189.95 mm). Ruw compenseert die extra vinlengte hun gewicht net tot iets boven de Adélies. Houd je de vinlengte gelijk, dan valt die compensatie weg, en dan blijkt een Chinstrap bij dezelfde vinlengte gewoon een lichter beest.</p>
<p><strong>Z) Nee — en dat is geen formaliteit.</strong> Draai de toets:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de parallelliteitsaanname">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de parallelliteitsaanname
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>ANOVA → ANCOVA</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>soort</code> naar <strong>Fixed Factors</strong>, <code>vinlengte</code> naar <strong>Covariates</strong> — dezelfde analyse als bij de gecorrigeerde gemiddelden.</li>
<li>Open <strong>Model</strong>, selecteer in de linkerlijst <code>vinlengte</code> én <code>soort</code> tegelijk en voeg de <strong>interactieterm</strong> <code>vinlengte✻soort</code> toe.</li>
<li>Kijk in de <em>ANCOVA</em>-tabel naar die rij: <em>F</em>(2, 336) = 5.53, <em>p</em> = .004.</li>
</ol>
<p>De drie hellingen apart: filter per soort (het <strong>trechtertje</strong> boven de data, bijvoorbeeld <code>soort == "Gentoo"</code>) en draai per soort een <strong>Regression → Linear Regression</strong> van <code>gewicht</code> op <code>vinlengte</code>. Zet het filter daarna weer uit.</p>
<p>Adelie <strong>32.83</strong> | Chinstrap <strong>34.57</strong> | Gentoo <strong>54.62</strong></p>
</div>
</div>
<p><em>F</em>(2, 336) = 5.53, <em>p</em> = .004 — significant, dus de aanname zákt. En je ziet het ook zonder toets: bij de Gentoo’s is elke millimeter vin ruim 54 gram waard, bij de Adélies nog geen 33. Dat is geen klein verschil.</p>
<p>Wat dat betekent lees je in de volgende sectie, want dit is te belangrijk voor een antwoordkader.</p>
</div>
</div>
</div>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="de-aanname-die-zakte-en-wat-je-dan-doet" class="level2">
<h2 class="anchored" data-anchor-id="de-aanname-die-zakte-en-wat-je-dan-doet">De aanname die zakte, en wat je dan doet</h2>
<p><span class="begrippen">parallelliteit · interactie · wat je niet mag beweren</span></p>
<p>Een ANCOVA leunt op iets wat de gewone meervoudige regressie niet nodig heeft. Model 2 geeft <strong>één</strong> helling voor de vinlengte, en gebruikt die voor alle drie de soorten. Dat mag alleen als die ene helling in elke groep ongeveer klopt. Die eis heet de <strong>parallelliteitsaanname</strong> (<em>parallelism</em>, of voluit: <em>homogeneity of regression slopes</em> — je komt allebei de namen tegen).</p>
<p>Waarom hij ertoe doet, is met één beeld te zien. Drie evenwijdige lijnen liggen overal even ver uit elkaar, dus “het verschil tussen de soorten” is één getal, waar je ook kijkt. Lopen de lijnen niet evenwijdig, dan <strong>waaieren</strong> ze — en dan hangt het verschil ervan af bij welke vinlengte je meet. Bij korte vinnen is het verschil anders dan bij lange. Dan bestaat <em>het</em> gecorrigeerde gemiddelde helemaal niet meer.</p>
<p>En dat is precies de situatie hier: 32.83, 34.57 en 54.62. De Gentoo-lijn loopt veel steiler dan de andere twee.</p>
<div class="apa callout callout-style-default callout-note callout-titled" title="De regel, en waar hij vandaan komt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>De regel, en waar hij vandaan komt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Het MVDA-werkboek van Peter de Heus — het oefenboek waarmee tweedejaars psychologie in Leiden multivariate data-analyse leren — is hier kort over (p.&nbsp;78):</p>
<blockquote class="blockquote">
<p><em>“Since there is no reason for social reality to obey the parallelism assumption, in addition to an ordinary ANCOVA, we must also always perform an ANCOVA with the addition of the <code>covariate * treatment</code> interaction. If the F test of this interaction is not significant, you can forget the analysis with interaction and interpret the results with the ordinary ANCOVA model. <strong>If the interaction is significant, however, the variable should not be used as a covariate.</strong>”</em></p>
</blockquote>
<p>En over waaróm (p.&nbsp;77): <em>“Violation of the parallelism assumption is deadly for the validity and interpretability of ANCOVA.”</em> De gecorrigeerde gemiddelden kloppen dan niet meer, en de <em>F</em>-toetsen evenmin.</p>
<p><strong>Dus:</strong> de mooie tabel uit de vorige sectie — 4147, 3940, 4414 — mag je zó niet rapporteren. Je hebt hem berekend, je hebt gezien wat een covariaat dóet, en dat was de les. Maar als resultaat houdt hij geen stand.</p>
</div>
</div>
<p><strong>En dan de vraag die je nu hoort te stellen: wat van mijn eigen antwoorden hierboven is nog geldig?</strong> Eerlijk antwoord: <strong>alles wat uit model 2 komt, valt om.</strong> Dat is niet alleen die tabel — het zijn ook de twee soort-verschillen uit vraag e) (de −206.51 en de 266.81), de <em>F</em>-toets van het hele model uit vraag b), en de modelvergelijkingen uit c) en d). Als de hellingen niet parallel lopen, kloppen de gecorrigeerde gemiddelden niet, en dan kloppen de toetsen die erop rusten net zo min.</p>
<p>Wat wél blijft staan: het model met <strong>alleen de soort</strong> (vraag a, model 1) — dat is de gewone eenweg-ANOVA uit de vorige oefening en die heeft met dit alles niets te maken. En de gemiddelde vinlengtes per soort uit vraag g, want dat zijn gewoon gemiddelden.</p>
<p>Zeg dat verschil één keer hardop, want het is de hele kunst van dit blok: <strong>berekenen mocht, rapporteren mag niet.</strong> Je hebt die getallen nodig gehad om te zíen wat een covariaat doet. Ze in een verslag zetten is iets anders.</p>
<p>Voordat je denkt dat je iets fout hebt gedaan: dat heb je niet. Je hebt de keuring gedraaid en die heeft gewerkt. <strong>Zo hoort het te gaan</strong> — een aanname die nooit zakt, is geen aanname maar een formaliteit.</p>
<p>En je kent dit eigenlijk al.&nbsp;Een covariaat-maal-factor-interactie is exact wat je in de volgende oefening onder een andere naam tegenkomt: een helling die per groep verschilt. Bij een ANCOVA is dat een probleem, want die wíl één helling delen. In de volgende oefening is het juist het onderwerp.</p>
<p>Wat je nu doet, is drie dingen kunnen kiezen — en de eerste is bijna altijd de goede:</p>
<ol type="1">
<li><strong>De covariaat niet gebruiken</strong> en gewoon de eenweg-ANOVA rapporteren. Dat is De Heus’ voorschrift.</li>
<li><strong>De interactie tot onderwerp maken</strong> en per groep een eigen helling rapporteren. Dan doe je geen ANCOVA meer, maar precies wat de volgende oefening doet.</li>
<li><strong>Een andere factor kiezen</strong> waar de aanname wél houdt — en dat gaan we nu doen, want de pinguïns hebben er een.</li>
</ol>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="van-soort-naar-sekse-nu-met-een-aanname-die-houdt" class="level2">
<h2 class="anchored" data-anchor-id="van-soort-naar-sekse-nu-met-een-aanname-die-houdt">Van soort naar sekse — nu met een aanname die houdt</h2>
<p><span class="begrippen">covariaat · gecorrigeerd gemiddelde · parallelliteit</span></p>
<p>In de vorige oefening toetste je het gewichtsverschil tussen de seksen met een eenweg-ANOVA: <em>F</em>(1, 331) = 72.96, <em>p</em> &lt; .001. Mannetjes zijn zwaarder. Maar mannetjes hebben ook langere vinnen — en daarmee is dit precies dezelfde vraag als hierboven, op een factor met twee groepen.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · zet het klaar">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · zet het klaar
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Tel eerst wie er meedoet</strong>, net als in de ANOVA-oefening: <strong>Descriptives → Descriptive Statistics</strong>, <code>sekse</code> bij <strong>Variables</strong>, vink <strong>Frequency tables</strong> aan. Je hoort <strong>Valid</strong> 333 en <strong>Missing</strong> 9 te zien staan — van negen pinguïns is de sekse nooit vastgesteld. Staat er 342 bij <strong>Valid</strong> met <code>NA</code> als derde categorie, zet die twee letters dan onder <strong>Preferences → Data</strong> in de lijst met ontbrekende waarden en draai opnieuw.</p></li>
<li><p>Bouw de dummy <code>man</code>: een berekende kolom (<strong><code>+</code></strong>, icoon <strong>R</strong>) met</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(sekse <span class="sc">==</span> <span class="st">"male"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code></pre></div><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></div>
<p>Kijk het na: vraag ook van <code>man</code> een <strong>Frequency table</strong> — 165 nullen, 168 enen en 9 bij <strong>Missing</strong>. Staan de negen zonder sekse op 0 in plaats van bij <strong>Missing</strong>, dan tellen ze stiekem als vrouwtje mee; regel dan eerst stap 1.</p></li>
<li><p>Model 1: <strong>Regression → Linear Regression</strong>, <code>gewicht</code> naar <strong>Dependent Variable</strong> en <code>man</code> naar <strong>Covariates</strong>. Model 2: sleep ook <code>vinlengte</code> naar <strong>Covariates</strong>. Vraag onder <strong>Statistics</strong> weer de <strong>Confidence intervals</strong> op.</p></li>
</ol>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoeveel gram schelen de seksen ruw? <em>(rapporteer b en R² van model 1)</em></p>
<p><strong>b)</strong> Waarom doen er 333 pinguïns mee en geen 342? Wat betekent dat voor je rapportage?</p>
<p><strong>c)</strong> Toets model 2 als geheel. <em>(rapporteer R², F(df<sub>1</sub>, df<sub>2</sub>) en p)</em></p>
<p><strong>d)</strong> Wat gebeurt er met het sekseverschil zodra de vinlengte erbij komt? <em>(rapporteer b, SE, t, p en het 95%-interval)</em></p>
<p><strong>e)</strong> Reken de gemiddelde vinlengte per sekse uit. Verklaart dat de verandering uit vraag d?</p>
<p><strong>f)</strong> Vraag de twee gecorrigeerde gemiddelden op, net als bij de soort: <strong>ANOVA → ANCOVA</strong> met <code>sekse</code> als <strong>Fixed Factor</strong> en <code>vinlengte</code> als <strong>Covariate</strong>, en <code>sekse</code> bij <strong>Marginal Means</strong>. Bij welke vinlengte rekent JASP ze uit — bij de 200.92 van eerder in dit blok, of bij iets anders? Zet ze daarna naast de ruwe gemiddelden.</p>
<p><strong>g)</strong> Wat voegt de vinlengte toe bovenop de sekse? <em>(rapporteer F(df<sub>1</sub>, df<sub>2</sub>) en p)</em></p>
<p><strong>h)</strong> Vergelijk deze uitkomst met de soort-ANCOVA hierboven. Bij de soort verdween het meeste van het groepsverschil; hier niet. Wat is het verschil?</p>
<p><strong>Z)</strong> Toets de parallelliteitsaanname, net als hierboven. Kijk ook naar de twee hellingen apart. Mag je dit model gebruiken?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <em>b</em> = 683.41 gram (mannetjes zwaarder dan vrouwtjes), <em>R</em>² = .181.</p>
<p><strong>b)</strong> Van negen pinguïns is de sekse niet vastgesteld; die doen in elk model met sekse erin niet mee. In je rapportage noem je die <em>n</em> = 333 dus expliciet, en niet de 342 van het hele bestand. Een steekproefgrootte die stilletjes verandert tussen twee analyses is precies het soort ding waar een lezer over struikelt.</p>
<p><strong>c)</strong> <em>R</em>² = .806, <em>F</em>(2, 330) = 684.80, <em>p</em> &lt; .001.</p>
<p><strong>d)</strong> Het halveert ruimschoots: van 683.41 naar <em>b</em> = 347.85, <em>SE</em> = 40.34, <em>t</em>(330) = 8.62, <em>p</em> &lt; .001, 95% CI [268.49, 427.21]. Nog steeds fors en nog steeds significant — maar de helft van het “sekseverschil” was vinlengte.</p>
<p><strong>e)</strong> Ja. Mannetjes 204.51 mm, vrouwtjes 197.36 mm — ruim zeven millimeter langer. En wat een millimeter waard is, staat gewoon in je eigen model:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de vin-helling van dit model">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de vin-helling van dit model
</div>
</div>
<div class="callout-body-container callout-body">
<p>Kijk in de tabel <em>Coefficients</em> van model 2: in de rij <code>vinlengte</code> staat <strong>46.98</strong>.</p>
</div>
</div>
<p>Ruim zeven millimeter maal bijna 47 gram is ongeveer 336 gram — en dat is vrijwel precies het stuk dat uit het sekseverschil verdween (683.41 − 347.85 = 335.56).</p>
<p><strong>f)</strong> Bij de gemiddelde vinlengte van <strong>200.97</strong> mm: vrouwtjes 4031.57 gram, mannetjes 4379.42 gram. Ruw waren dat 3862.27 en 4545.68.</p>
<p>Geen 200.92 dus. Eerder in dit blok was de gemiddelde vinlengte 200.92, gerekend over alle 342 pinguïns; dit model draait op de 333 met een bekende sekse, en JASP rekent de tabel <em>Marginal Means</em> uit bij het gemiddelde van precies díé 333: 200.97. Die negen weggevallen pinguïns verschuiven het gemiddelde met vijf honderdsten millimeter, en dus je gecorrigeerde gemiddelden met een paar gram. Dat is geen rekenfout — het is dezelfde <em>n</em> = 333 uit vraag b, die nu ook je covariaat raakt. <strong>Een gecorrigeerd gemiddelde hoort gerekend te zijn op precies de gegevens waar het model op draait</strong> — en dat doet het programma hier zelf. De twee schuiven dus naar elkaar toe, maar de volgorde blijft dezelfde — anders dan bij de Chinstrap.</p>
<p><strong>g)</strong> <em>F</em>(1, 330) = 1062.63, <em>p</em> &lt; .001. Enorm, zoals te verwachten: de vinlengte is verreweg de beste voorspeller van het gewicht die deze data heeft.</p>
<p><strong>h)</strong> Bij de soort ging het grootste deel van het groepsverschil naar de covariaat toe, en één verschil klapte zelfs om van teken. Hier blijft ruim de helft staan. Dat komt doordat de seksen véél minder in vinlengte verschillen (7 mm) dan de soorten onderling (27 mm tussen Adélie en Gentoo). Hoe sterker de groepen op de covariaat verschillen, hoe meer er van het groepsverschil verdwijnt zodra je ervoor corrigeert.</p>
<p><strong>Z) Ja, deze keer wél.</strong> De toets:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de parallelliteitsaanname, nog een keer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de parallelliteitsaanname, nog een keer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ANOVA → ANCOVA</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>sekse</code> naar <strong>Fixed Factor</strong>, <code>vinlengte</code> naar <strong>Covariate</strong>. Voeg onder <strong>Model</strong> de interactieterm <code>vinlengte✻sekse</code> toe en lees die rij af: <em>F</em>(1, 329) = 0.01, <em>p</em> = .92.</p>
<p>De twee hellingen apart, met het trechtertje (<code>sekse == "female"</code> en daarna <code>sekse == "male"</code>): <strong>47.15</strong> en <strong>46.86</strong>.</p>
</div>
</div>
<p><em>F</em>(1, 329) = 0.01, <em>p</em> = .92 — bij lange na niet significant. En de twee hellingen zijn 47.15 en 46.86: die schelen nog geen drie tienden van een gram per millimeter. Zó parallel worden ze zelden. Hier mag je de gecorrigeerde gemiddelden dus gewoon rapporteren.</p>
<p>Eén slag om de arm, en die is van De Heus (p.&nbsp;83): een niet-significante interactie <strong>bewijst</strong> de aanname niet. Een toets die niets vindt, kan ook gewoon te weinig power hebben gehad — “niets gevonden” is nooit hetzelfde als “er is niets”. Daarom kijk je er altijd de hellingen zelf bij. Hier zeggen die twee hetzelfde als de toets, en dán ben je zo dicht bij zekerheid als je komt.</p>
</div>
</div>
</div>
<div class="kicker">
<p>eindopdracht</p>
</div>
</section>
<section id="de-afsluiter-van-het-hele-hoofdstuk" class="level2">
<h2 class="anchored" data-anchor-id="de-afsluiter-van-het-hele-hoofdstuk">De afsluiter van het hele hoofdstuk</h2>
<p>Dit hoofdstuk ging over één idee in vijf gedaanten: <strong>een groep is ook een getal.</strong> Je codeerde groepen als dummy’s, toetste twee groepen met een <em>t</em>-toets, gaf dat verschil een maat met Cohens <em>d</em>, toetste drie groepen in één keer met een ANOVA, en zette er zojuist een covariaat naast. Vijf namen, één model.</p>
<p>Nu breng je het samen — en deze keer niet als losse vragen, maar als het stuk dat je in een verslag zou zetten. Twee secties, zoals in een artikel.</p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eindopdracht">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eindopdracht
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>De vraag.</strong> Verschillen de drie pinguïnsoorten in <strong>snaveldiepte</strong>, en blijft dat verschil overeind als je corrigeert voor de vinlengte?</p>
<section id="methode-en-data-analyse" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse">Methode en data-analyse</h3>
<p>Schrijf op wat je gaat doen, vóór je de uitkomsten kent. Deze sectie bevat geen resultaten.</p>
<ul>
<li>Welke variabelen gebruik je, en welke rol heeft elk (afhankelijke, factor, covariaat)? Noem het meetniveau erbij.</li>
<li>Hoeveel pinguïns doen er mee, en vallen er waarnemingen af?</li>
<li>Welke toetsen ga je draaien, in welke volgorde, en waarom die volgorde?</li>
<li><strong>Welke aannames ga je controleren, en hoe?</strong> Noem ze bij naam en zeg per aanname wat je opvraagt. Vergeet de parallelliteit niet — en schrijf ook op wat je gaat doen als hij zakt. Dat besluit neem je nú, niet straks als je de uitkomst ziet.</li>
</ul>
</section>
<section id="resultaten" class="level3">
<h3 class="anchored" data-anchor-id="resultaten">Resultaten</h3>
<p>Draai het, en schrijf het op als een resultatensectie — lopende zinnen, geen lijstje.</p>
<ul>
<li>De eenweg-ANOVA op soort, met effectgrootte.</li>
<li>De uitkomst van je aannamecontroles, inclusief de parallelliteit. Als een aanname zakt, zeg dat en voer uit wat je in je methodesectie beloofde.</li>
<li>Het model dat je uiteindelijk mag interpreteren, met de bijbehorende getallen.</li>
<li>Eén slotalinea in gewone taal: wat betekent dit voor de vraag waarmee je begon?</li>
</ul>
<p><em>Ter controle van je opzet, niet van je uitkomst:</em> de vinlengte en de snaveldiepte hangen negatief samen (<em>r</em> = −.584), dus verwacht hier iets anders dan bij het gewicht. En loop de parallelliteit écht na voordat je gecorrigeerde gemiddelden opschrijft — dit blok liet net zien waarom.</p>
</section>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-het-op-als-een-onderzoeker" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</h2>
<p><span class="begrippen">rapportagezin · gecorrigeerde gemiddelden · aanname vermelden</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bij een ANCOVA komt er één laag bij die je bij de gewone regressie niet had: je <strong>meldt dat je de aanname gecontroleerd hebt</strong>, en met welke uitkomst. Niet in een voetnoot — gewoon in de zin, want een lezer kan je gecorrigeerde gemiddelden anders niet op waarde schatten. Zo voor het sekse-model:</p>
<blockquote class="blockquote">
<p>Om te onderzoeken of het gewichtsverschil tussen mannetjes- en vrouwtjespinguïns standhoudt na correctie voor lichaamsgrootte, voerden we een covariantieanalyse uit met sekse als factor en vinlengte als covariaat (<em>n</em> = 333; van negen pinguïns was de sekse niet vastgesteld). De parallelliteitsaanname werd niet geschonden, <em>F</em>(1, 329) = 0.01, <em>p</em> = .92. Het model als geheel verklaarde het grootste deel van de verschillen in gewicht, <em>R</em>² = .81, <em>F</em>(2, 330) = 684.80, <em>p</em> &lt; .001. Bij gelijke vinlengte wogen mannetjes gemiddeld 347.85 gram meer dan vrouwtjes, <em>b</em> = 347.85, <em>SE</em> = 40.34, <em>t</em>(330) = 8.62, <em>p</em> &lt; .001, 95% CI [268.49, 427.21]. De gecorrigeerde gemiddelden bedroegen 4031.57 gram voor vrouwtjes en 4379.42 gram voor mannetjes, tegen ruwe gemiddelden van 3862.27 en 4545.68 gram.</p>
</blockquote>
<p>Vier dingen om op te letten. <strong>De <em>n</em> staat erbij, mét de reden</strong> dat het er 333 zijn en geen 342 — een steekproef die tussen twee analyses krimpt zonder uitleg is een lezer kwijt. <strong>De aannametoets staat vóór de uitkomsten</strong>, want hij bepaalt of die uitkomsten iets betekenen. <strong>De gecorrigeerde gemiddelden staan náást de ruwe</strong>, zodat je lezer ziet hoevéél de correctie deed. En <strong>“bij gelijke vinlengte”</strong> staat er met zoveel woorden: zonder die woorden leest iemand het getal als het gewone sekseverschil, en dat is het niet.</p>
<p>De typografie is als altijd: symbolen die een waarde dragen cursief — <em>R</em>², <em>F</em>, <em>p</em>, <em>SE</em>, <em>t</em>, <em>n</em> — de gewone woorden rechtop, CI rechtop met een spatie vóór de haak, twee decimalen, en een <em>p</em> onder .001 schrijf je als <em>p</em> &lt; .001 zonder nul voor de punt.</p>
<p><strong>En schrijf een gezakte aanname net zo op.</strong> Voor het soort-model zou de zin beginnen met:</p>
<blockquote class="blockquote">
<p>De parallelliteitsaanname werd geschonden, <em>F</em>(2, 336) = 5.53, <em>p</em> = .004; de vinlengte is daarom niet als covariaat gebruikt en de soortverschillen worden ongecorrigeerd gerapporteerd.</p>
</blockquote>
<p>Dat is geen bekentenis van falen maar gewoon wat er gebeurd is. Wie de gezakte toets weglaat en de gecorrigeerde gemiddelden tóch opschrijft, rapporteert wat goed uitkwam.</p>
</div>
</div>
<div class="boekvorm" data-w="W9">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: een groepsverschil dat verschuift — en soms van teken wisselt — zodra je een getalsmatige medespeler naast de groep zet, plus de aanname die bepaalt of je dat mag.</p>
<p>In het boek: <strong>W9 — Groepen zijn ook getallen</strong></p>
<p><em>Daar is de soort geen etiket maar een kolom getallen zoals elke andere. Zodra dat gelukt is, mag er van alles naast — ook iets wat wél gewoon een getal was.</em></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Palmer Penguins — Gorman, Williams &amp; Fraser (2014), Palmer Station Antarctica LTER; via het R-pakket <code>palmerpenguins</code> (CC0). Alle getallen in dit blok zijn op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_anova.html" class="pagination-link" aria-label="Oefening 9.4 · ANOVA en η²">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 9.4 · ANOVA en η²</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_interactie.html" class="pagination-link" aria-label="Oefening 10.1 · Als de moderator een groep is">
        <span class="nav-page-text">Oefening 10.1 · Als de moderator een groep is</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>