<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 10.1 · Als de moderator een groep is – JASP-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_interactie_continu.html" rel="next">
<link href="../20_blokken/blok_ancova.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">H10 · Verschil in verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">Oefening 10.1 · Als de moderator een groep is</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">JASP-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JASP-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_confounding_partiele_correlatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.2 · Confounding en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · Eenweg ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in JASP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Vierde beweging · Verschil onthechten</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">H10 · Verschil in verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">Oefening 10.1 · Als de moderator een groep is</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 10.1 · Als de moderator een groep is</h1>
<p class="subtitle lead">Interactie met een groep als moderator · <em>categorical moderation</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#eén-getal-dat-uit-twee-getallen-bleek-te-bestaan" id="toc-eén-getal-dat-uit-twee-getallen-bleek-te-bestaan">Eén getal dat uit twee getallen bleek te bestaan</a></li>
  <li><a href="#twee-lijnen-één-groep-tegenover-de-rest" id="toc-twee-lijnen-één-groep-tegenover-de-rest">Twee lijnen: één groep tegenover de rest</a></li>
  <li><a href="#nog-twee-lijnen-maar-dan-parallel-de-sekse" id="toc-nog-twee-lijnen-maar-dan-parallel-de-sekse">Nog twee lijnen, maar dan parallel: de sekse</a></li>
  <li><a href="#drie-lijnen-de-hele-soort-erbij" id="toc-drie-lijnen-de-hele-soort-erbij">Drie lijnen: de hele soort erbij</a></li>
  <li><a href="#zes-hokjes-twee-groeperingen-tegelijk" id="toc-zes-hokjes-twee-groeperingen-tegelijk">Zes hokjes: twee groeperingen tegelijk</a></li>
  <li><a href="#wie-krijgt-het-overlapstuk-type-i-en-type-iii" id="toc-wie-krijgt-het-overlapstuk-type-i-en-type-iii">Wie krijgt het overlapstuk? Type I en type III</a></li>
  <li><a href="#duizend-werelden-waarin-de-soort-niets-modereert" id="toc-duizend-werelden-waarin-de-soort-niets-modereert">Duizend werelden waarin de soort niets modereert</a></li>
  <li><a href="#onder-welke-conditie-doet-iets-ertoe" id="toc-onder-welke-conditie-doet-iets-ertoe">Onder welke conditie doet iets ertoe</a></li>
  <li><a href="#dezelfde-zes-hokjes-een-andere-meetlat" id="toc-dezelfde-zes-hokjes-een-andere-meetlat">Dezelfde zes hokjes, een andere meetlat</a></li>
  <li><a href="#schrijf-het-op-als-een-onderzoeker" id="toc-schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</a></li>
  <li><a href="#tentamenvragen" id="toc-tentamenvragen">Tentamenvragen</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="eén-getal-dat-uit-twee-getallen-bleek-te-bestaan" class="level2">
<h2 class="anchored" data-anchor-id="eén-getal-dat-uit-twee-getallen-bleek-te-bestaan">Eén getal dat uit twee getallen bleek te bestaan</h2>
<p><span class="begrippen">helling per groep</span></p>
<p>Bij de enkelvoudige regressie trok je een lijn door 342 pinguïns en las je er één getal van af: <strong>49.69 gram per millimeter</strong>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Elke millimeter vin erbij, bijna vijftig gram pinguïn erbij. Eén getal, netjes uitgerekend, en er was geen enkele reden om het te wantrouwen.</p>
<p>Splits diezelfde 342 beesten nu eens in tweeën — de Gentoo’s aan de ene kant, de Adélies en Chinstraps aan de andere — en trek de lijn twee keer. In deze steekproef komt er bij de niet-Gentoo’s <strong>29.49</strong> uit, en bij de Gentoo’s <strong>54.62</strong>.</p>
<p>Kijk daar even naar. 49.69 ligt tussen die twee in, en het is geen van beide.</p>
<p>En het is ook niet netjes hun gemiddelde — dat zou te makkelijk zijn. Weeg de twee hellingen naar groepsgrootte (219 niet-Gentoo’s tegen 123 Gentoo’s) en je komt uit op 38.53. Je eerste getal ligt daar ruim elf gram bóven.</p>
<p>Dat komt doordat één lijn door alle pinguïns twee dingen tegelijk moet doen: het verband bínnen elke groep volgen, én de afstand tússen de groepen overbruggen. En die tweede taak duwt hem omhoog, want de Gentoo’s zijn niet alleen zwaarder maar hebben óók langere vinnen. Trek je een lijn door niets anders dan de twee groepsgemiddelden, dan is die zelfs 53.73.</p>
<p>Je eerste getal was dus niet fout gerekend. Het was een <strong>menging</strong> — en niet eens een eerlijke.</p>
<p>En dat roept meteen de vraag op waar deze oefening over gaat. Is die kloof echt, of kan het toeval van 342 beesten hem namaken? En als hij echt is — hoe schrijf je dan een model op dat niet één helling wil, maar twee?</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="twee-lijnen-één-groep-tegenover-de-rest" class="level2">
<h2 class="anchored" data-anchor-id="twee-lijnen-één-groep-tegenover-de-rest">Twee lijnen: één groep tegenover de rest</h2>
<p><span class="begrippen">dummy · interactieterm · simple slope</span></p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Regression → Linear Regression</strong>, <code>glans</code> als <strong>Dependent</strong>.</li>
<li>Zet <code>gladheid</code>, <code>D</code> én <code>DxG</code> in <strong>Covariates</strong> — <code>DxG</code> is het product van de twee, dat staat al klaar als kolom.</li>
<li>In <strong>Coefficients</strong> staat <code>gladheid</code> op 6.136 en <code>DxG</code> op 2.637, met <em>p</em> = 0.054.</li>
</ol>
</div>
</div>
<p><code>D</code> is een kolom met nullen en enen: nul voor golfje, één voor sterretje. Zo’n nul-of-één-kolom heet een <strong>dummy</strong>, en hij is het eenvoudigste soort moderator die er bestaat — twee groepen, meer niet. De interactie gladheid × merk komt uit op <em>b</em> = 2.64 met <em>p</em> = .054: bij het ene merk telt een punt gladheid harder mee voor de glans dan bij het andere. Eén helling is dan niet meer genoeg.</p>
<p><strong>Nu jij</strong> — dezelfde beesten als in oefening 3.2, nieuwe vraag. Is die 49.69 één helling, of zijn het er twee?</p>
<p>De pinguïns hebben geen kant-en-klare dummy in het bestand, dus die maak je zelf: één kolom die zegt of een pinguïn een Gentoo is of niet. En het product er meteen bij, want dat is wat de interactieterm ís: de twee voorspellers met elkaar vermenigvuldigd.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · twee kolommen erbij rekenen · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · twee kolommen erbij rekenen · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Open <code>penguins.csv</code> in JASP (menu linksboven → <strong>Open</strong>).</p></li>
<li><p>Scroll in het databad helemaal naar rechts en klik op de <strong>+</strong> boven de lege kolom. Noem hem <code>gentoo</code> en kies de <strong>R</strong>-knop om een formule te typen:</p>
<pre><code>ifelse(soort == "Gentoo", 1, 0)</code></pre>
<p>Klik <strong>Compute column</strong>. Je hebt nu een kolom met 219 nullen en 123 enen.</p></li>
<li><p>Maak op dezelfde manier nog een kolom, <code>vinXgentoo</code>:</p>
<pre><code>vinlengte * gentoo</code></pre>
<p>Zet beide nieuwe kolommen op <strong>Scale</strong> (het liniaaltje), anders wil JASP ze niet als covariaat aannemen.</p></li>
</ol>
</div>
</div>
<p>Nu het model. De drie kolommen samen — <code>vinlengte</code>, <code>gentoo</code> en hun product — zijn de toestemming: reken het verband tussen vinlengte en gewicht uit, maar laat de Gentoo’s er een eigen helling op na houden.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · trek eraan · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · trek eraan · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Regression → Linear Regression</strong>.</li>
<li><code>gewicht</code> naar <strong>Dependent Variable</strong>.</li>
<li><code>vinlengte</code>, <code>gentoo</code> én <code>vinXgentoo</code> naar <strong>Covariates</strong>.</li>
<li>Vink onder <strong>Statistics</strong> de optie <strong>Estimates</strong> aan als die nog uit staat.</li>
<li>Lees in de tabel <em>Coefficients</em> de drie rijen af.</li>
</ol>
<p>In <strong>Coefficients</strong> staat <code>vinlengte</code> op 29.494 — de helling bij <code>gentoo</code> = 0 —, <code>gentoo</code> op −4841.807 en <code>vinXgentoo</code> op 25.129 met <em>p</em> &lt; .001. In <strong>Model Summary</strong> staat <em>R</em>² = 0.785.</p>
</div>
</div>
<p>Vier getallen, en ze doen alle vier iets anders. Het loont om er even bij stil te staan, want dit is de tabel die je de rest van de oefening blijft lezen:</p>
<ul>
<li><code>vinlengte</code> is de helling <strong>bij <code>gentoo</code> = 0</strong>, dus bij de niet-Gentoo’s: <strong>29.49</strong> gram per millimeter.</li>
<li><code>gentoo</code> is het hoogteverschil bij vinlengte = 0 — een vin van nul millimeter, dus dat getal woont op een adres dat niet bestaat. Laat het staan; in oefening 10.2 gaan we er iets aan doen.</li>
<li><code>vinXgentoo</code> is waar het om gaat: <strong>25.13</strong> gram per millimeter <strong>extra</strong> voor de Gentoo’s. Niet hun helling — het verschil tussen hun helling en die van de rest.</li>
<li>En die <em>p</em> &lt; .001 zegt: zo’n kloof tussen twee hellingen zie je bijna nooit als er in werkelijkheid geen kloof is.</li>
</ul>
<p>De helling van de Gentoo’s zelf staat er dus niet; die tel je op. En dat is de hele truc:</p>
<blockquote class="blockquote">
<p>29.49 + 25.13 = <strong>54.62</strong> gram per millimeter bij de Gentoo’s</p>
</blockquote>
<p>Twee hellingen, allebei uit één tabel: <strong>29.49</strong> en <strong>54.62</strong>. Zulke hellingen binnen één groep heten <em>simple slopes</em>, en je hebt er niets voor nodig behalve optellen. Geloof je het niet, reken ze dan los na — het moet op de komma hetzelfde geven:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · ter controle, de twee lijnen los · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · ter controle, de twee lijnen los · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Klik op het <strong>trechtertje</strong> boven de eerste kolom van het databad.</li>
<li>Typ als filter <code>gentoo == 0</code> en klik <strong>Apply</strong>.</li>
<li>Draai een gewone <strong>Regression → Linear Regression</strong> van <code>gewicht</code> op <code>vinlengte</code>. Je vindt <strong>29.494</strong>.</li>
<li>Zet het filter op <code>gentoo == 1</code> en draai hem opnieuw: <strong>54.623</strong>.</li>
<li>Zet het filter daarna weer uit — anders rekent alles hierna op één soort.</li>
</ol>
</div>
</div>
<p>En daar ligt je 49.69 uit oefening 3.2 uit elkaar. Eén lijn door twee groepen die elk hun eigen lijn hebben, geeft een getal dat bij geen van beide groepen hoort — te steil voor de Adélies en Chinstraps, te flauw voor de Gentoo’s. Het is een gemiddelde waar niemand woont.</p>
<p>Teken het maar, dan zie je het in één keer:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de twee lijnen tekenen · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de twee lijnen tekenen · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ga naar <strong>Regression → Correlation</strong>, zet <code>vinlengte</code> en <code>gewicht</code> in het vak, en vink onder <strong>Plots</strong> de <strong>Scatter plots</strong> aan. Sleep <code>gentoo</code> naar het vakje onder de plot-opties dat om een groeperende variabele vraagt; JASP tekent dan een eigen puntenwolk én een eigen lijn per groep.</p>
<p>Zie je twee lijnen die uit elkaar lopen — dan klopt het. De ene lijn uit oefening 3.2 zou er dwars tussendoor gaan.</p>
</div>
</div>
</section>
<section id="nog-twee-lijnen-maar-dan-parallel-de-sekse" class="level2">
<h2 class="anchored" data-anchor-id="nog-twee-lijnen-maar-dan-parallel-de-sekse">Nog twee lijnen, maar dan parallel: de sekse</h2>
<p><span class="begrippen">niet-significante interactie · hoogte tegenover steilheid</span></p>
<p>Voordat je dit doortrekt naar meer groepen, eerst een tegenvoorbeeld — want anders ga je overal waaiers zien. In <code>penguins.csv</code> staat nóg een kolom met twee groepen: <code>sekse</code>. Mannetjes zijn duidelijk zwaarder dan vrouwtjes; in deze steekproef wegen ze gemiddeld 4545.68 gram tegen 3862.27 — een verschil van 683.41 gram. Dan zal een millimeter vin bij mannetjes ook wel zwaarder tellen?</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · dezelfde zet, andere groep · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · dezelfde zet, andere groep · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>ANOVA → ANCOVA</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>sekse</code> naar <strong>Fixed Factors</strong>, <code>vinlengte</code> naar <strong>Covariates</strong>.</li>
<li>Open <strong>Model</strong>, selecteer <code>vinlengte</code> én <code>sekse</code> samen en voeg de interactieterm <code>vinlengte✻sekse</code> toe.</li>
<li>Kijk in de <em>ANCOVA</em>-tabel naar die rij: <em>F</em> = 0.010, <em>p</em> = 0.920.</li>
</ol>
<p>De negen pinguïns zonder genoteerde sekse vallen er vanzelf uit.</p>
<p>Wil je de twee hellingen los zien: filter op <code>sekse == "female"</code> respectievelijk <code>sekse == "male"</code> en draai per groep een <strong>Linear Regression</strong> van <code>gewicht</code> op <code>vinlengte</code>. Je vindt <strong>47.153</strong> en <strong>46.859</strong>.</p>
</div>
</div>
<p><strong>47.15</strong> tegen <strong>46.86</strong>. Die liggen zo goed als op elkaar, en de interactie is dan ook nergens: <em>p</em> = .92. De mannetjes zijn zwaarder, maar een millimeter vin weegt bij hen niet zwaarder.</p>
<p>Dat is het onderscheid dat de rest van deze oefening draagt. “Mannetjes zijn zwaarder” is een verschil in <strong>hoogte</strong> — twee wolken, de ene boven de andere, met lijnen die keurig parallel lopen. Een interactie is een verschil in <strong>steilheid</strong> — lijnen die uit elkaar waaieren. Twee groepen kunnen ver uit elkaar liggen en tóch precies dezelfde helling hebben, en dan is er geen interactie te bekennen.</p>
</section>
<section id="drie-lijnen-de-hele-soort-erbij" class="level2">
<h2 class="anchored" data-anchor-id="drie-lijnen-de-hele-soort-erbij">Drie lijnen: de hele soort erbij</h2>
<p><span class="begrippen">nominale moderator · modelvergelijking</span></p>
<p>Een dummy kon maar twee groepen aan. Maar <code>soort</code> heeft er drie — Adélie, Chinstrap, Gentoo — en dat verandert meer dan je zou denken.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · drie soorten in één model · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · drie soorten in één model · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>ANOVA → ANCOVA</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>soort</code> naar <strong>Fixed Factors</strong>, <code>vinlengte</code> naar <strong>Covariates</strong>.</li>
<li>Open <strong>Model</strong>. Selecteer in de linkerlijst <code>vinlengte</code> én <code>soort</code> tegelijk en voeg de <strong>interactieterm</strong> <code>vinlengte✻soort</code> toe. Er staan nu drie termen in het model.</li>
<li>Kijk in de uitvoertabel <em>ANCOVA</em> naar de rij <code>vinlengte✻soort</code>: <em>F</em> = 5.532, <em>p</em> = 0.004.</li>
<li>Open <strong>Descriptives Plots</strong>: <code>vinlengte</code> op de horizontale as, <code>soort</code> bij <strong>Separate Lines</strong>. JASP tekent één lijn per soort.</li>
</ol>
</div>
</div>
<p>Merk op wat JASP hier voor je doet — en wat het je daarmee ontneemt. In het R-broertje zie je bij drie soorten <strong>twee</strong> losse interactieregels. De Adélie is daar het ijkpunt — alfabetisch de eerste — en de andere twee soorten worden ertegen afgezet: de Chinstraps lopen 1.74 gram per millimeter steiler dan de Adélies (en dat is niets, <em>p</em> = .82), en de Gentoo’s 21.79 steiler (en dat is wél iets, <em>p</em> = .002). Twee regels die je apart moet lezen en die elk maar de helft van het verhaal vertellen. JASP legt daar meteen één <em>F</em> overheen: <em>F</em>(2, 336) = 5.53, met <strong>twee</strong> vrijheidsgraden, want er kwamen twee regels bij. Dat ene getal is het antwoord op de vraag <em>“verschilt de helling érgens tussen de soorten?”</em> — en dat is precies de vraag waar één coëfficiënt geen antwoord meer op geeft.</p>
<p>En die ene <em>F</em> komt niet uit één tabel maar uit twee modellen: één waarin alle soorten dezelfde helling moeten delen, tegenover één waarin elke soort een eigen helling mag hebben. Zo’n <strong>modelvergelijking</strong> stelt één vraag: past het grote model beter dan het kleine? JASP legt die twee voor je naast elkaar en drukt alleen de uitslag af — vandaar dat de rapportagezin verderop over twee modellen praat terwijl jij er één hebt aangeklikt.</p>
<p>Dezelfde trechter als bij de eenweg ANOVA — daar toetste je eerst met één <em>F</em> of de drie soortgemiddelden überhaupt van elkaar verschilden, en pas daarna welk paar het deed. Eerst overkoepelend of er íéts is, dan pas waar het zit. Hier zit het bij de Gentoo’s.</p>
<p>De drie hellingen los:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de helling per soort · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de helling per soort · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Filter per soort (het <strong>trechtertje</strong> boven de data, bijvoorbeeld <code>soort == "Gentoo"</code>) en draai per soort een <strong>Regression → Linear Regression</strong> van <code>gewicht</code> op <code>vinlengte</code>. Zet het filter daarna weer uit.</p>
<ul>
<li><strong>32.832</strong> gram per millimeter bij de Adélie’s</li>
<li><strong>34.573</strong> bij de Chinstraps</li>
<li><strong>54.623</strong> bij de Gentoo’s</li>
</ul>
</div>
</div>
<p><strong>32.83</strong>, <strong>34.57</strong> en <strong>54.62</strong> gram per millimeter vin. Twee soorten die vrijwel samenvallen, en één die er ver bovenuit steekt. Trek de flauwste van de steilste af — 54.62 − 32.83 — en je krijgt 21.79. Dat is exact de Gentoo-regel van het R-broertje hierboven, en dat is geen toeval: de Adélie is daar het ijkpunt én toevallig ook de flauwste, dus “hoeveel steiler dan de Adélie” en “hoeveel tussen de steilste en de flauwste” zijn hier hetzelfde getal. Onthoud het, want in de volgende trede komt het terug. Merk op dat de Gentoo’s op precies dezelfde 54.62 uitkomen als in de eerste trede — logisch, het is dezelfde groep pinguïns met dezelfde lijn. Wat veranderde is waarmee je ze vergelijkt: eerst met alle andere pinguïns op één hoop, nu met elke soort apart.</p>
</section>
<section id="zes-hokjes-twee-groeperingen-tegelijk" class="level2">
<h2 class="anchored" data-anchor-id="zes-hokjes-twee-groeperingen-tegelijk">Zes hokjes: twee groeperingen tegelijk</h2>
<p><span class="begrippen">tweeweg-ANOVA · celgemiddelde · type III</span></p>
<p>Tot nu toe modereerde een groep het effect van een <em>getal</em> op het gewicht. Maar twee groeperingen kunnen elkaar ook onderling moduleren, en dan blijft er van de lijnen niets over — je houdt hokjes over.</p>
<p>Zet <code>sekse</code> (twee groepen) naast <code>soort</code> (drie groepen) en je krijgt zes hokjes. Dat heet een <strong>tweeweg-ANOVA</strong>, of een factoriële ANOVA; dat is hetzelfde. Twee groeperingen, dus tweeweg — net zoals <a href="../20_blokken/blok_anova.html">Oefening 9.4</a> er één had en eenweg heette. De vraag is dan niet meer hoe steil een lijn loopt, maar of het gemiddelde per hokje zich netjes gedraagt.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · eerst de zes hokjes zelf · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · eerst de zes hokjes zelf · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Zet eerst een filter dat de negen pinguïns zonder sekse weglaat: <code>sekse == "male" | sekse == "female"</code>.</li>
<li><strong>Descriptives</strong>: <code>gewicht</code> bij <strong>Variables</strong>, en zet <code>sekse</code> én <code>soort</code> allebei bij <strong>Split</strong>. Je krijgt het gemiddelde en de <em>n</em> per hokje.</li>
</ol>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Adélie</th>
<th>Chinstrap</th>
<th>Gentoo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>vrouwtje</strong></td>
<td>3368.8 g (<em>n</em> = 73)</td>
<td>3527.2 g (<em>n</em> = 34)</td>
<td>4679.7 g (<em>n</em> = 58)</td>
</tr>
<tr class="even">
<td><strong>mannetje</strong></td>
<td>4043.5 g (<em>n</em> = 73)</td>
<td>3939.0 g (<em>n</em> = 34)</td>
<td>5484.8 g (<em>n</em> = 61)</td>
</tr>
</tbody>
</table>
<p>Lees die tabel eens per kolom. Bij de Adélies zijn de mannetjes 674.7 gram zwaarder dan de vrouwtjes, bij de Chinstraps 411.8, bij de Gentoo’s 805.1. Het sekseverschil is er bij alle drie — maar het is niet overal even groot. Dát is de interactie: het <strong>verschil in verschil</strong>. Niet of sekse uitmaakt, maar of het bij elke soort evenveel uitmaakt.</p>
<p>En let op wat je nog steeds kunt: je kunt dit tekenen. Zes punten, twee lijntjes die elkaar volgen of niet. Dat is wat de hele 10.1 bij elkaar houdt — of de moderator nu twee, drie of zes hokjes maakt, je kunt het plaatje voor je zien.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de tweeweg-ANOVA · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de tweeweg-ANOVA · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>ANOVA → ANOVA</strong> (níét ANCOVA — er is geen covariaat meer, allebei de voorspellers zijn groeperingen).</li>
<li><code>gewicht</code> naar <strong>Dependent Variable</strong>; <code>sekse</code> én <code>soort</code> naar <strong>Fixed Factors</strong>. JASP zet de interactie er zelf al in; kijk het na onder <strong>Model</strong>: daar hoort <code>sekse✻soort</code> te staan, en <strong>Sum of squares</strong> op <strong>Type III</strong>.</li>
<li>Vink onder <strong>Display</strong> <strong>Estimates of effect size</strong> aan, en zet daaronder het vinkje bij <strong>η²</strong>: uit zichzelf zet JASP daar alleen <strong>ω²</strong> aan, een andere maat.</li>
<li>Open <strong>Descriptives Plots</strong>: <code>soort</code> op de horizontale as, <code>sekse</code> bij <strong>Separate Lines</strong> — lijnen boven staafjes, want alleen bij lijnen zie je of ze parallel lopen.</li>
</ol>
<p>In de tabel <strong>ANOVA</strong> staat bij <code>sekse</code> <em>F</em> = 311.838, bij <code>soort</code> 746.924 en bij <code>sekse ✻ soort</code> 8.757, alle drie met <em>p</em> &lt; .001. In de kolom η² staat 0.145, 0.695 en 0.008.</p>
<p>Die η²’s zijn niet helemaal dezelfde als in de rapportage verderop (.14, .66 en .01), en dat ligt niet aan jou. In de rapportage is het stuk van elk effect gedeeld door álle spreiding in gewicht; JASP deelt door de stukken in zijn eigen tabel bij elkaar opgeteld. Zijn de hokjes even groot, dan komt dat op hetzelfde uit. Hier zijn ze dat net niet — 61 Gentoo-mannetjes tegen 58 vrouwtjes — en dan tellen de stukken niet precies op tot het geheel. De rangorde blijft dezelfde: de soort doet veruit het meeste werk.</p>
</div>
</div>
</section>
<section id="wie-krijgt-het-overlapstuk-type-i-en-type-iii" class="level2">
<h2 class="anchored" data-anchor-id="wie-krijgt-het-overlapstuk-type-i-en-type-iii">Wie krijgt het overlapstuk? Type I en type III</h2>
<p><span class="begrippen">kwadratensommen · type III</span></p>
<p>Eén ding verdient uitleg, ook al hoef je er in JASP niets voor te doen — juist daarom.</p>
<p>Teken twee cirkels die elkaar deels overlappen. De ene is alles wat <code>sekse</code> van het gewicht kan verklaren, de andere alles wat <code>soort</code> kan verklaren. In het overlapstuk zit variantie waar ze allebei aanspraak op maken — en iemand moet beslissen wie hem krijgt.</p>
<p><strong>Type I geeft hem aan wie het eerst genoemd wordt.</strong> Zet je sekse vooraan, dan pakt sekse het overlapstuk en houdt soort alleen wat overblijft; zet je soort vooraan, dan is het andersom. De uitkomst hangt dus af van de volgorde.</p>
<p><strong>Type III geeft hem aan niemand.</strong> Elke factor krijgt alleen wat híj als enige kan verklaren. Dat is onafhankelijk van de volgorde, en dat is wat we hier aanhouden — het is ook wat je bij de meeste opleidingen en in de meeste tijdschriften tegenkomt.</p>
<p><strong>JASP zet type III standaard aan</strong>, en je vindt de keuze onder <strong>Model → Sum of squares</strong>. Kijk daar één keer, ook al ga je er niets veranderen — want het is precies zo’n instelling waarvan je moet wéten dat hij bestaat. En achter die keuze zit nog een tweede, die JASP je helemaal uit handen neemt: hoe je groepen in getallen worden omgezet, de <em>codering</em> of het <em>contrasttype</em>. Type III heeft een andere codering nodig dan die R standaard gebruikt. JASP regelt dat zelf; in R moet je het er zelf bij zeggen, en vergeet je dat, dan rekent R gewoon door en geeft andere getallen, zonder een kik.</p>
<p>Kijk maar wat er met de <em>F</em> voor sekse gebeurt onder vier varianten van dezelfde data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>hoe je het uitrekent</th>
<th><em>F</em> voor sekse</th>
<th><em>F</em> voor de interactie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>type I, <code>sekse</code> eerst opgeschreven</td>
<td>406.14</td>
<td>8.76</td>
</tr>
<tr class="even">
<td>type I, <code>soort</code> eerst opgeschreven</td>
<td>387.46</td>
<td>8.76</td>
</tr>
<tr class="odd">
<td>type III (de standaard in JASP)</td>
<td>311.84</td>
<td>8.76</td>
</tr>
<tr class="even">
<td>type III, verkeerd gecodeerd (de val in R)</td>
<td>173.55</td>
<td>8.76</td>
</tr>
</tbody>
</table>
<p>Vier verschillende antwoorden op “heeft sekse effect op gewicht”, en één ervan is minder dan de helft van een andere. Maar kijk naar de rechterkolom: <strong>de interactie is in alle vier precies 8.76.</strong> Dat is geen toeval — de interactie is de term die als laatste komt, wat je ook doet, dus er valt voor hem niets te verdelen.</p>
<p>En vergelijk je je uitkomst ooit met die van een medestudent, kijk dan éérst naar de interactie. Komt die overeen terwijl de hoofdeffecten verschillen, dan heeft niemand zich verrekend — dan heeft een van jullie tweeën een andere kwadratensom gebruikt. Wélke van de twee, zegt die vergelijking je niet; daarvoor moeten jullie allebei opschrijven wat je gedaan hebt. Vandaar dat het in de rapportage hoort.</p>
<p>Wil je het zelf zien: zet onder <strong>Model</strong> de <strong>Sum of squares</strong> eens op <strong>Type I</strong>, draai opnieuw, en kijk wat er met de rijen <code>sekse</code> en <code>soort</code> gebeurt en wat níét met <code>sekse ✻ soort</code>. Zet hem daarna terug op <strong>Type III</strong>.</p>
<div class="kicker">
<p>schud het</p>
</div>
</section>
<section id="duizend-werelden-waarin-de-soort-niets-modereert" class="level2">
<h2 class="anchored" data-anchor-id="duizend-werelden-waarin-de-soort-niets-modereert">Duizend werelden waarin de soort niets modereert</h2>
<p><span class="begrippen">soort-labels husselen · kloof tussen hellingen</span></p>
<p>Terug naar de drie lijnen. Is die kloof tussen 32.83 en 54.62 echt, of kan het toeval hem namaken? Je zou dat willen uitproberen door vals te spelen. Deze keer husselen we de <strong>soort-labels</strong> los van de pinguïns: elke pinguïn houdt z’n eigen vinlengte en gewicht, maar krijgt een willekeurig soort-kaartje opgeplakt. Adélie, Gentoo, Chinstrap — lukraak rondgestrooid.</p>
<p>Dat husselen <strong>koppelt de soort los van het vin-gewicht-verband</strong>. Je haalt met eigen handen weg dat een bepaalde soort bij een bepaalde helling hoort. In zo’n losgekoppelde wereld kán de ene soort geen steilere lijn meer hebben dan de andere — als de hellingen dan tóch verschillen, is dat puur toeval van de verdeling.</p>
<p><strong>En hier moet ik eerlijk zijn: dat schudden is geen knop in JASP.</strong> JASP rekent één keurige uitkomst uit; het door elkaar husselen en duizend keer opnieuw kijken is <em>code</em>-werk. Voor deze interactie is er (nog) geen browser-speeltje — dus voor de schud-ervaring <strong>draai je het R-broertje</strong>, waar het husselen een paar regels code is. Dat is geen gemis van jou of van JASP: het boek doet het bewust zo, de simulatie leeft in de code en in de speeltjes.</p>
<p>Wat je daar ziet: <strong>duizend werelden waarin de soort de vin-gewicht-relatie niet modereert</strong> — want in elke geschudde wereld is de soort losgeknipt van de helling. De kloof tussen de hellingen danst rond een paar gram: soms toevallig wat groter, meestal klein. En dan de echte kloof — <strong>21.79</strong> gram per millimeter tussen de steilste (Gentoo) en de flauwste (Adélie) — valt ver buiten dat hele bergje. In duizend keer schudden haalde <strong>geen enkele</strong> geschudde wereld de echte kloof. De echte pinguïns weten iets wat de geschudde niet weten: bij de Gentoo’s telt een langere vin écht zwaarder mee.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="onder-welke-conditie-doet-iets-ertoe" class="level2">
<h2 class="anchored" data-anchor-id="onder-welke-conditie-doet-iets-ertoe">Onder welke conditie doet iets ertoe</h2>
<p><span class="begrippen">interactie · moderatie · verschil in verschil</span></p>
<p>Wat je hier drie keer zag, heeft één naam: een <strong>interactie</strong>, in de wandelgangen ook <em>moderatie</em>. En de nette formulering is de moeite waard om precies over te nemen, want de slordige versie kost je later punten: <strong>het effect van vinlengte op gewicht verandert in grootte en/of richting met het niveau van de soort.</strong> Niet “vinlengte interacteert met soort” — dat zegt niet wát er met wát gebeurt.</p>
<p>De kortste weg naar waar het echt over gaat, loopt even bij de pinguïns vandaan. Zou wel of geen therapie uitmaken voor het welzijn van mensen? Ja, hè. Maar ga nu eens naar een moeilijk land waar geen eten is, waar mensen verhongeren. Geef sommige van die hongerende mensen therapie en sommige geen therapie — zou dat verschil maken? Nee: als je geen eten hebt, heeft therapie ook geen zin.</p>
<p>Therapie geeft dus soms een verschil in welzijn, maar alleen in bepaalde situaties. Bij een interactie-effect is dát de vraag: wanneer, onder welke conditie, heeft een variabele een effect op de uitkomst?</p>
<p>Dáár gaat het om. Een interactie is geen ingewikkeldere versie van een effect — het is de erkenning dat de vraag <em>“hoeveel effect heeft X op Y?”</em> soms geen antwoord heeft zonder de vervolgvraag <em>“bij wie, en wanneer?”</em> Bij de pinguïns: “hoeveel extra gewicht per millimeter vin?” heeft geen antwoord zonder “bij welke soort?”</p>
<p>En daarom loog die 49.69 uit de prikkel niet, maar antwoordde hij op een vraag die niet goed gesteld was.</p>
<p>Drie dingen om vast te houden, want ze komen alle drie terug.</p>
<p><strong>Eén: hoogte is geen steilheid.</strong> De sekse maakte de pinguïns 683.41 gram zwaarder en veranderde niets aan de helling. Dat is een hoofdeffect, geen interactie. Twee wolken op verschillende hoogte met parallelle lijnen — verschil, maar geen verschil in verschil.</p>
<p><strong>Twee: bij meer dan twee groepen stopt de coëfficiënt met antwoorden.</strong> Twee groepen geven één interactieregel die je gewoon kunt aflezen. Drie groepen geven er twee, en dan heb je een modelvergelijking nodig om te weten of er überhaupt iets is. Dat is geen extra formaliteit; het is dezelfde reden waarom je bij drie gemiddelden een eenweg ANOVA doet en niet drie <em>t</em>-toetsen.</p>
<p><strong>Drie: een hoofdeffect lees je aan de randen af.</strong> Bij de zes hokjes vroeg je niet naar één cel maar naar het gemiddelde van een hele rij of kolom — de <em>marginalen</em>. Doe het even met lengtes: in Nederland zijn de mannen 1.80 en de vrouwen 1.70, in Japan 1.70 en 1.65. Vraag je “er komt een man binnen, hoe lang is die?”, dan gebruik je het marginaal van de mannen — (1.80 + 1.70) / 2 = 1.75 — en bij een vrouw (1.70 + 1.65) / 2 = 1.675. Die twee getallen gaan enkel en alleen over het hoofdeffect van geslacht op lengte, niet over land, en het verschil ertussen is 7.5 centimeter. Zo lees je ook de pinguïn-tabel: de rijen voor sekse, de kolommen voor soort, en de manier waarop de hokjes van hun eigen randen afwijken is de interactie.</p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="dezelfde-zes-hokjes-een-andere-meetlat" class="level2">
<h2 class="anchored" data-anchor-id="dezelfde-zes-hokjes-een-andere-meetlat">Dezelfde zes hokjes, een andere meetlat</h2>
<p><span class="begrippen">tweeweg-ANOVA · type III · parallel</span></p>
<p>Jouw beurt. Je hebt net gezien dat sekse en soort samen iets doen met het <strong>gewicht</strong> van een pinguïn: het sekseverschil is groter bij de Gentoo’s dan bij de Chinstraps. Nu dezelfde twee groeperingen, dezelfde zes hokjes — maar je meet iets anders: de <strong>snavellengte</strong>. De vraag: is het sekseverschil in snavellengte ook niet overal even groot?</p>
<p>Zet eerst klaar, en beantwoord daarna de vragen. De laatste heet met opzet <strong>Z)</strong> en niet l): de aannames staan altijd achteraan, en die vreemde letter zegt <em>“en ook, elke keer, deze”</em>. En onder <em>Tentamenvragen</em>, aan het eind van deze oefening, staan dezelfde onderwerpen nog een keer in de vorm waarin een tentamen ze stelt.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · zet klaar · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · zet klaar · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Laat het filter aan staan dat de negen pinguïns zonder sekse weglaat (<code>sekse == "male" | sekse == "female"</code>).</li>
<li><strong>ANOVA → ANOVA</strong>: <code>snavellengte</code> naar <strong>Dependent Variable</strong>; <code>sekse</code> én <code>soort</code> naar <strong>Fixed Factors</strong>. JASP zet de interactie er zelf al in; kijk het na onder <strong>Model</strong>, daar hoort <code>sekse✻soort</code> te staan.</li>
<li>Vink onder <strong>Display</strong> <strong>Estimates of effect size</strong> aan, en zet daaronder het vinkje bij <strong>η²</strong>: uit zichzelf zet JASP daar alleen <strong>ω²</strong> aan, een andere maat.</li>
</ol>
<p>Over de kwadratensommen hoef je niets te doen: JASP rekent standaard type III, zoals je hierboven zag — je hoeft dat straks alleen in je rapportage te zéggen.</p>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoeveel pinguïns zitten er in de zes hokjes, en hoeveel per hokje? Draai <strong>Descriptives</strong> met <code>snavellengte</code> bij <strong>Variables</strong> en <code>sekse</code> én <code>soort</code> allebei bij <strong>Split</strong>, en lees per hokje de <em>n</em> af. Waarom is het totaal geen 342? (zes getallen, één totaal, en één zin)</p>
<p><strong>b)</strong> Lees in dezelfde Descriptives-uitvoer het gemiddelde per hokje af en zet ze in een tabel van twee rijen bij drie kolommen. (zes getallen)</p>
<p><strong>c)</strong> Trek per soort de vrouwtjes van de mannetjes af. Zijn die drie kloven ongeveer even groot? (drie getallen, en hoeveel de grootste en de kleinste schelen)</p>
<p><strong>d)</strong> Schrijf de nulhypothese voor de <strong>interactie</strong> voluit op, in woorden én in symbolen. (één zin, en die ook in symbolen)</p>
<p><strong>e)</strong> Toets de interactie — de rij <code>sekse ✻ soort</code> in de uitvoertabel. (rapporteer <em>F</em>(<em>df</em><sub>1</sub>, <em>df</em><sub>2</sub>) en <em>p</em>)</p>
<p><strong>f)</strong> Rapporteer nu ook de twee hoofdeffecten. (per hoofdeffect <em>F</em>(<em>df</em><sub>1</sub>, <em>df</em><sub>2</sub>) en <em>p</em>)</p>
<p><strong>g)</strong> Lees de drie effectgroottes af in de η²-kolom die je bij het klaarzetten hebt aangevinkt. Welke van de drie doet het meeste werk? (drie η²’s)</p>
<p><strong>h)</strong> Dit is het moment waarop JASP je stilletjes beschermt: de codering waar het hier om gaat, zet JASP zelf goed — daar is geen knop voor, dus je kunt hier niets stukmaken. In R wél: daar kun je type III verkeerd opzetten door één regel code te vergeten, en dan zakt de <em>F</em> voor sekse van 208.06 naar 66.81, zonder één waarschuwing. De interactie blijft in allebei de gevallen 2.28. Waaróm staat de interactie stil, wat je ook doet? (één zin)</p>
<p><strong>i)</strong> Teken het via <strong>Descriptives Plots</strong>: <code>soort</code> op de horizontale as, <code>sekse</code> bij <strong>Separate Lines</strong>, en leg het naast het eerdere plaatje van het gewicht. (twee plaatjes, en wat je aan de lijnen ziet)</p>
<p><strong>j)</strong> Waarom moet je in je rapportagezin schrijven dát het type III-kwadratensommen zijn? (één zin, met het getal uit h) erin)</p>
<p><strong>k)</strong> Bij het gewicht wás er een interactie, bij de snavellengte niet — op precies dezelfde 333 pinguïns, met precies dezelfde twee groeperingen. Wat zegt dat over waar een interactie in zit?</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Loop de aannames na: is de spreiding in snavellengte ongeveer gelijk over de zes hokjes (de rij <strong>Std. Deviation</strong> in de Descriptives-uitvoer van a)), en telt elke pinguïn maar één keer mee? En dan de vraag die bij dít ontwerp hoort: kijk nog eens naar je zes celaantallen uit a) — wat zou er met de hele type I/type III-kwestie gebeuren als die zes gelijk waren geweest?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Vrouwtjes 73, 34 en 58; mannetjes 73, 34 en 61 — samen <strong>333</strong>. Geen 342, want bij negen pinguïns is de sekse nooit vastgesteld, en het filter laat die hier expliciet weg. Onthoud die zes getallen; bij <strong>Z)</strong> blijken ze ertoe te doen.</p>
<p><strong>b)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Adélie</th>
<th>Chinstrap</th>
<th>Gentoo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>vrouwtje</strong></td>
<td>37.26</td>
<td>46.57</td>
<td>45.56</td>
</tr>
<tr class="even">
<td><strong>mannetje</strong></td>
<td>40.39</td>
<td>51.09</td>
<td>49.47</td>
</tr>
</tbody>
</table>
<p><strong>c)</strong> 3.13, 4.52 en 3.91 mm. Het sekseverschil is er bij alle drie de soorten, en het scheelt tussen de grootste en de kleinste maar <strong>1.39 mm</strong>. Vergelijk dat met het gewicht, waar diezelfde drie kloven 674.7, 411.8 en 805.1 gram waren — daar was de grootste bijna twee keer de kleinste.</p>
<p><strong>d)</strong> De nulhypothese: het sekseverschil in snavellengte is bij alle drie de soorten even groot. In symbolen: <span class="math inline">\(H_0:\ \mu_{\text{man},j} - \mu_{\text{vrouw},j}\)</span> is hetzelfde voor elke <span class="math inline">\(j\)</span>, waarin <span class="math inline">\(j\)</span> een aftelnummer voor de soort is. Je mag het ook schrijven als <em>alle interactietermen in de populatie zijn nul</em>; één van de twee is genoeg.</p>
<p><strong>e)</strong> <em>F</em>(2, 327) = 2.28, <em>p</em> = .103. Niet significant: deze keer lopen de lijnen zo goed als parallel.</p>
<p><strong>f)</strong> Sekse <em>F</em>(1, 327) = 208.06, <em>p</em> &lt; .001. Soort <em>F</em>(2, 327) = 650.21, <em>p</em> &lt; .001. Allebei ruimschoots.</p>
<p><strong>g)</strong> η² = .11 voor sekse, <strong>.70</strong> voor soort en .00 voor de interactie. De soort doet vrijwel al het werk; dat mannetjes langere snavels hebben komt daar als een keurig parallelle laag bovenop.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · wat er in je η²-kolom staat">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · wat er in je η²-kolom staat
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bij jou staat er 0.113, 0.707 en 0.002 — net iets anders dan hierboven. Waarom, lees je in het kader bij de tweeweg-ANOVA.</p>
</div>
</div>
<p><strong>h)</strong> De interactie staat stil omdat hij als laatste komt, wat je ook doet: er valt voor hem niets meer te verdelen — vandaar twee keer 2.28, terwijl de <em>F</em> voor sekse naar minder dan een derde zakt. Precies wat je bij het gewicht in de vier-varianten-tabel zag.</p>
<p><strong>i)</strong> Bij de snavellengte lopen de twee lijnen zo goed als parallel: overal ongeveer vier millimeter tussen de vrouwtjes en de mannetjes. Bij het gewicht liepen ze zichtbaar uiteen — bij de Gentoo’s stond het sekseverschil veel wijder open dan bij de Chinstraps. Hoogte tegenover steilheid, en hier is het alleen hoogte.</p>
<p><strong>j)</strong> Omdat dezelfde data zonder die vermelding niet na te rekenen is: je zag bij h) 208.06 en 66.81 op precies dezelfde 333 pinguïns. Wie niet weet welke van de twee je gebruikte, kan je <em>F</em> niet reproduceren en dus ook niet controleren.</p>
<p><strong>k)</strong> Dat een interactie niet in de twee groeperingen zit maar in <strong>wat je meet</strong>. Sekse en soort zijn in allebei de analyses dezelfde twee kolommen, op dezelfde 333 dieren. Het gewicht van een Gentoo-mannetje loopt anders uit de pas dan zijn snavel. “Sekse en soort interacteren” is dus een onaffe zin — de vraag is altijd: interacteren ze <em>op welke uitkomst?</em></p>
<p><strong>Z)</strong> De spreiding per hokje loopt van 1.56 mm (Chinstrap-mannetjes) tot 3.11 mm (Chinstrap-vrouwtjes) — de grootste is <strong>1.99 keer</strong> de kleinste. Dat is krap onder de twee, dus het mag, maar het is geen ruime marge; bij een grensgeval als <em>p</em> = .103 is dat het vermelden waard. Elke pinguïn is één keer gemeten, dus de waarnemingen zijn onafhankelijk.</p>
<p>En dan de tweede helft van de vraag, want dáár zit de winst. Waren de zes hokjes even groot geweest, dan <strong>had de hele type I/type III-kwestie niet bestaan.</strong> De twee cirkels overlappen alleen doordat de aantallen ongelijk zijn; bij gelijke aantallen valt er niets te verdelen en geven alle varianten hetzelfde getal. Op deze data is dat na te meten: trek 34 dieren uit elk hokje en type I met sekse eerst, type I met soort eerst en type III komen alle drie op dezelfde <em>F</em> uit. Op de échte, scheve verdeling geven ze 219.23, 211.81 en 208.06.</p>
<p>De weg terug, voor als de spreiding wél ver uiteen was gelopen:</p>
<ul>
<li><strong>Blijft staan:</strong> de zes celgemiddelden bij b) en de drie kloven bij c). Dat zijn beschrijvingen van deze 333 dieren.</li>
<li><strong>Doe je over:</strong> alle drie de <em>F</em>’s bij e) en f), en daarmee je conclusie bij k). Die rusten op één gedeelde restspreiding over de zes hokjes, en die is er dan niet.</li>
</ul>
</div>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-het-op-als-een-onderzoeker" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</h2>
<p><span class="begrippen">rapportagezin · F en p · nul-vondst</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een interactie opschrijven klinkt als iets voor de gevorderden, maar het blijft een boodschappenlijstje in zinsvorm: wat vergeleek je, verschilde het, en waar zat het. Twee modelzinnen, één voor elke vorm die je vandaag zag.</p>
<p><strong>Een helling die per groep verschilt:</strong></p>
<blockquote class="blockquote">
<p>Om te onderzoeken of het effect van vinlengte op gewicht afhangt van de soort, vergeleken we bij 342 pinguïns twee modellen: één waarin alle soorten dezelfde helling moesten delen, en één waarin elke soort een eigen helling mocht hebben. De hellingen verschilden significant tussen de soorten, <em>F</em>(2, 336) = 5.53, <em>p</em> = .004: bij de Gentoo’s ging een millimeter extra vin samen met meer extra gewicht (54.62 g/mm) dan bij de Adélies (32.83) en de Chinstraps (34.57). Het effect van vinlengte op gewicht werd dus gemodereerd door de soort.</p>
</blockquote>
<p><strong>Twee groeperingen tegelijk:</strong></p>
<blockquote class="blockquote">
<p>Om te onderzoeken of het effect van sekse op gewicht afhangt van de soort, voerden we bij 333 pinguïns een tweeweg-variantieanalyse uit met sekse en soort als factoren (type III-kwadratensommen). De interactie was significant, <em>F</em>(2, 327) = 8.76, <em>p</em> &lt; .001, η² = .01: het sekseverschil was groter bij de Gentoo’s (805.09 g) dan bij de Chinstraps (411.76 g). Beide hoofdeffecten waren eveneens significant, voor sekse <em>F</em>(1, 327) = 311.84, <em>p</em> &lt; .001, η² = .14, en voor soort <em>F</em>(2, 327) = 746.92, <em>p</em> &lt; .001, η² = .66.</p>
</blockquote>
<p>Kijk wat er cursief staat en wat niet. Alléén de symbolen <em>F</em> en <em>p</em> hellen; η² is een Griekse letter en blijft rechtop, en de gewone woorden en de gewichtsgetallen ook. De statistieken krijgen <strong>twee decimalen</strong>, APA-precies, terwijl de lopende tekst hierboven gerust rondde (“ruim zeshonderd gram”) voor de intuïtie. Een <em>p</em> die kleiner is dan .001 schrijf je niet uit maar als <em>p</em> &lt; .001, en zonder nul ervoor. Alles staat in de verleden tijd, want je vertelt wat er gevónden werd, en beide zinnen staan op eigen benen: wie er één uit dit blok tilt, weet nog steeds wie er gemeten werd, wat er gemeten werd, en waar de interactie zat.</p>
<p>In geen van beide zinnen staat welk programma je gebruikt hebt. Dat is met opzet: een methodezin zegt wát je gedaan hebt, niet welke knop je hebt aangeklikt of welke regel je hebt getypt. Zag jij zelf maar één tabel in plaats van twee modellen? Dan legde je programma die twee voor je naast elkaar, en het getal is hetzelfde. Twee onderzoekers die dezelfde pinguïns dezelfde vraag stellen, hebben niet twee verschillende methoden gebruikt — en precies díé verwarring hoort een methodesectie weg te nemen.</p>
<p>Merk ook op dat de tweede zin zégt dat het type III-kwadratensommen zijn. JASP had dat al aan staan, dus je hoefde er niets voor te doen — maar je moet het wél vermelden. Dat is geen pronken met vaktaal — je zag hierboven dat dezelfde data vier verschillende <em>F</em>-waarden kan opleveren, dus zonder die vermelding kan niemand jouw getal narekenen.</p>
<p>Jouw beurt: schrijf zelf de rapportage-zin voor de taak hierboven — de snavellengte. Die interactie was juist níét significant (<em>F</em>(2, 327) = 2.28, <em>p</em> = .10), en ook een nul-vondst rapporteer je netjes op: dat het sekseverschil in snavellengte bij alle drie de soorten ongeveer even groot was, is een echt resultaat. De modelzinnen hierboven mag je lenen; hardop voorlezen mag ook.</p>
</div>
</div>
<div class="kicker">
<p>tentamen</p>
</div>
</section>
<section id="tentamenvragen" class="level2">
<h2 class="anchored" data-anchor-id="tentamenvragen">Tentamenvragen</h2>
<p><span class="begrippen">interactieterm aflezen · hoogte tegenover steilheid · modelvergelijking · marginalen</span></p>
<p>Deze zes hebben de vorm waarin een tentamen dit onderwerp stelt: vier opties, en precies één is de beste — de andere drie kunnen best waar zijn en toch niet het beste antwoord. Bij vraag 2 reken je; bij de rest kies je.</p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Tentamenvragen">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Tentamenvragen
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>1.</strong> In de regressie van gewicht op <code>vinlengte</code>, <code>gentoo</code> en hun product <code>vinXgentoo</code> staat de regel <code>vinXgentoo</code> op 25.13 gram per millimeter. Wat is dat getal?</p>
<ol type="a">
<li>De helling van gewicht op vinlengte bij de Gentoo’s.</li>
<li>Hoeveel steiler de Gentoo’s lopen dan de andere pinguïns.</li>
<li>Het gewichtsverschil tussen de Gentoo’s en de andere pinguïns.</li>
<li>De helling van gewicht op vinlengte bij de niet-Gentoo’s.</li>
</ol>
<p><strong>2.</strong> In dezelfde tabel staat <code>vinlengte</code> op 29.49 en <code>vinXgentoo</code> op 25.13. Hoe steil loopt de lijn van de Gentoo’s zelf, in gram per millimeter vin?</p>
<ol type="a">
<li>25.13</li>
<li>38.53</li>
<li>49.69</li>
<li>54.62</li>
</ol>
<p><strong>3.</strong> De mannetjes wegen gemiddeld 683.41 gram meer dan de vrouwtjes, en de interactie tussen vinlengte en sekse komt op <em>p</em> = .92. Welke uitspraak is de beste?</p>
<ol type="a">
<li>De sekse verschuift de wolk omhoog en verandert de helling niet.</li>
<li>De sekse doet niets voor het gewicht, want de interactie is niet significant.</li>
<li>Bij de mannetjes heeft vinlengte geen effect op gewicht.</li>
<li>Met een grotere steekproef zou deze interactie wél significant worden.</li>
</ol>
<p><strong>4.</strong> Bij <code>soort</code> — drie groepen — staan er in een coëfficiëntentabel twee interactieregels, zoals je hierboven bij het R-broertje las: Chinstrap +1.74 en Gentoo +21.79 gram per millimeter, met <em>p</em> = .82 en <em>p</em> = .002. Waarom heb je daarnaast nog een modelvergelijking nodig?</p>
<ol type="a">
<li>Omdat de tabel geen regel voor de Adélies heeft, en die soort dus ongetoetst blijft.</li>
<li>Omdat twee losse toetsen op dezelfde data je twee keer de kans op een toevalstreffer geven.</li>
<li>Omdat de vraag of de helling érgens tussen de soorten verschilt nergens in de tabel staat.</li>
<li>Omdat de twee coëfficiënten alleen kloppen zolang je de Adélie als ijkpunt neemt.</li>
</ol>
<p><strong>5.</strong> Je rekent hetzelfde tweeweg-model op vier manieren uit. De <em>F</em> voor sekse komt op 406.14, 387.46, 311.84 en 173.55 — en de <em>F</em> voor de interactie alle vier de keren op 8.76. Waaraan ligt dat?</p>
<ol type="a">
<li>Alleen hoofdeffecten hebben kwadratensommen; een interactie heeft ze niet.</li>
<li>De interactie komt als laatste, dus er valt voor hem niets meer te verdelen.</li>
<li>De interactie is ongevoelig voor het contrasttype, omdat hij geen hoofdeffect is.</li>
<li>De vier manieren verschillen alleen in de volgorde waarin je de factoren opschrijft, en een interactie heeft geen volgorde.</li>
</ol>
<p><strong>6.</strong> Bij het <strong>gewicht</strong> komt de interactie tussen sekse en soort op <em>F</em>(2, 327) = 8.76, <em>p</em> &lt; .001. Bij de <strong>snavellengte</strong>, op precies dezelfde 333 pinguïns en met dezelfde twee groeperingen, op <em>F</em>(2, 327) = 2.28, <em>p</em> = .10. Welke uitspraak is de beste?</p>
<ol type="a">
<li>Sekse en soort interacteren op gewicht en niet op snavellengte: een interactie zit in wát je meet.</li>
<li>De twee analyses spreken elkaar tegen, dus één van de twee is verkeerd uitgerekend.</li>
<li>Sekse en soort interacteren niet echt — de ene toets haalde net de grens en de andere net niet.</li>
<li>Bij de snavellengte zijn 333 pinguïns te weinig om de interactie aan te tonen.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1 b · 2 d · 3 a · 4 c · 5 b · 6 a</strong></p>
<p>Hieronder staat per vraag eerst waaróm het goede antwoord goed is, en daaronder een korte toelichting per foute optie. Heb je er een goed, dan kun je die overslaan.</p>
<p><strong>1. b.</strong> Een interactieterm is een <strong>verschil tussen hellingen</strong>, geen helling. De Gentoo-helling is 54.62 gram per millimeter en staat nergens in de tabel — die tel je zelf op.</p>
<ul>
<li><strong>a</strong> — de meest gemaakte fout: een coëfficiënt lezen als “de waarde voor deze groep” terwijl er “het verschil met de ijkgroep” staat.</li>
<li><strong>c</strong> — het hoogteverschil staat wél in de tabel, op de regel <code>gentoo</code>, als −4841.81 gram bij een vin van nul millimeter. Twee regels, twee soorten verschil.</li>
<li><strong>d</strong> — dat is 29.49 gram per millimeter: de regel erboven.</li>
</ul>
<p><strong>2. d.</strong> 29.49 + 25.13 = <strong>54.62</strong> gram per millimeter.</p>
<ul>
<li><strong>a</strong> — de interactieterm zelf: het verschil, niet de helling.</li>
<li><strong>b</strong> — de twee hellingen naar groepsgrootte gewogen (219 tegen 123); een som die klopt en een andere vraag beantwoordt.</li>
<li><strong>c</strong> — de 49.69 uit de prikkel: één lijn door alle 342 pinguïns, en juist het getal dat bij geen van beide groepen hoort.</li>
</ul>
<p><strong>3. a.</strong> Hoogte is geen steilheid. De twee hellingen liggen 0.29 gram per millimeter uit elkaar, de wolken 683.41 gram.</p>
<ul>
<li><strong>b</strong> — trekt uit een niet-significante <strong>interactie</strong> de conclusie dat er geen <strong>hoofdeffect</strong> is; de mannetjes zijn onbetwist zwaarder.</li>
<li><strong>c</strong> — bij de mannetjes is de helling 46.86 gram per millimeter, bepaald niet nul.</li>
<li><strong>d</strong> — de gedachte die bij elk grensgeval opkomt. Ze gaat alleen op als er in de populatie écht een verschil zit; hier weten we dat niet, en in deze 342 dieren is de waaier 0.29 gram per millimeter. Dat is voor een pinguïn van vier kilo niets. Significant is niet hetzelfde als groot.</li>
</ul>
<p><strong>4. c.</strong> Twee losse regels antwoorden niet op één overkoepelende vraag. Daarom leg je twee modellen naast elkaar: één waarin alle soorten dezelfde helling moeten delen, één waarin elke soort er een eigen mag hebben.</p>
<ul>
<li><strong>a</strong> — de Adélie is juist het ijkpunt waar de andere twee tegen afgezet worden; niet ongetoetst, maar de meetlat.</li>
<li><strong>b</strong> — een echte zorg bij meervoudig toetsen, en niet de reden hier: ook ná corrigeren heb je nog geen getal over de twee regels samen. <a href="../20_blokken/blok_anova.html">Oefening 9.4</a> motiveert de overkoepelende toets net zo: eerst óf er íets is, dan waar.</li>
<li><strong>d</strong> — waar, en geen antwoord: coëfficiënten hangen aan het ijkpunt, en dat is wat een ijkpunt doet.</li>
</ul>
<p><strong>5. b.</strong> De interactie komt altijd als laatste, dus alles wat te verdelen was, is al verdeeld. Dat geldt voor de volgorde waarin je de factoren opschrijft (rij 1 en 2) én voor de codering (rij 3 en 4): een codering verandert waar de nul van een factor ligt, en dus wat een hoofdeffect betekent — maar de interactie is wat er ná beide hoofdeffecten overblijft, en die rest is dezelfde.</p>
<ul>
<li><strong>a</strong> — onwaar: elke term in een ANOVA heeft een kwadratensom, dat is waar de <em>F</em> uit komt.</li>
<li><strong>c</strong> — de goede uitkomst met de verkeerde reden: niet omdát hij een interactie is, maar omdat hij de laatste term is.</li>
<li><strong>d</strong> — klopt voor de bovenste twee rijen van de tabel en niet voor de onderste twee: type III goed en verkeerd gecodeerd geeft 311.84 tegen 173.55 op dezelfde volgorde. Dát is de val die JASP voor je dichtzet.</li>
</ul>
<p><strong>6. a.</strong> Twee keer dezelfde 333 dieren, twee keer dezelfde twee groeperingen, en twee verschillende uitkomsten. Dus zit de interactie niet in sekse en soort maar in <strong>wat je meet</strong> — precies wat vraag k) van <em>Jouw beurt</em> je liet opschrijven.</p>
<ul>
<li><strong>b</strong> — er is geen tegenspraak: het zijn twee verschillende uitkomstmaten, en het gewicht van een Gentoo-mannetje loopt anders uit de pas dan zijn snavel.</li>
<li><strong>c</strong> — <em>p</em> = .10 en <em>p</em> &lt; .001 zijn geen twee grensgevallen. De eerste ligt er ruim naast en de tweede ruim eronder.</li>
<li><strong>d</strong> — dezelfde 333 dieren droegen de interactie op gewicht wél. Aan de omvang kan het dus niet liggen.</li>
</ul>
<p>De getallen in deze zes vragen staan allemaal al eerder op deze bladzij. Eén komt er nieuw bij: de 0.29 bij vraag 3. Dat is 47.15 − 46.86, de twee sekse-hellingen uit <em>Nog twee lijnen, maar dan parallel</em> van elkaar afgetrokken — zo kun je hem narekenen zonder hem te geloven.</p>
</div>
</div>
</div>
<div class="boekvorm" data-w="W10">
<p>◠ <strong>In het boek</strong></p>
<p>Hier: als de moderator een groep is, kun je het tekenen — twee lijnen, drie lijnen, of zes hokjes.</p>
<p>In het boek: <strong>W10 — Verschil in verschil</strong></p>
<p><em>Daar draait het om de lijnen die niet parallel lopen — het moment waarop je merkt dat “het effect” een tweede vraag nodig heeft: bij wie?</em></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Palmer Penguins — Gorman, Williams &amp; Fraser (2014), Palmer Station Antarctica LTER; via het R-pakket <code>palmerpenguins</code> (CC0). Alle getallen in dit blok zijn op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_ancova.html" class="pagination-link" aria-label="Oefening 9.5 · ANCOVA: een groep én een getal">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 9.5 · ANCOVA: een groep én een getal</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_interactie_continu.html" class="pagination-link" aria-label="Oefening 10.2 · Als de moderator een getal is">
        <span class="nav-page-text">Oefening 10.2 · Als de moderator een getal is</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>