<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 3.3 · De residuen bekijken – JASP-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_steekproevenverdeling.html" rel="next">
<link href="../20_blokken/blok_enkelvoudige_regressie.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Tweede beweging · Verschillen koppelen</li><li class="breadcrumb-item"><a href="../20_blokken/blok_correlatie_scatterplot.html">H3 · Het rechthoekje</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_residuen.html">Oefening 3.3 · De residuen bekijken</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">JASP-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JASP-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">H3 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 3.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_confounding_partiele_correlatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.2 · Confounding en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · Eenweg ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in JASP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Tweede beweging · Verschillen koppelen</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Tweede beweging · Verschillen koppelen</li><li class="breadcrumb-item"><a href="../20_blokken/blok_correlatie_scatterplot.html">H3 · Het rechthoekje</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_residuen.html">Oefening 3.3 · De residuen bekijken</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 3.3 · De residuen bekijken</h1>
<p class="subtitle lead">Wat de lijn liet liggen, en waar <em>R</em>² vandaan komt · <em>residuals</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#tweeëntwintig-pinguïns-van-precies-190-millimeter" id="toc-tweeëntwintig-pinguïns-van-precies-190-millimeter">Tweeëntwintig pinguïns van precies 190 millimeter</a></li>
  <li><a href="#reken-de-gokfouten-uit-op-de-twaalf-steentjes" id="toc-reken-de-gokfouten-uit-op-de-twaalf-steentjes">Reken de gokfouten uit op de twaalf steentjes</a></li>
  <li><a href="#het-residu-en-waar-r²-vandaan-komt" id="toc-het-residu-en-waar-r²-vandaan-komt">Het residu, en waar <em>R</em>² vandaan komt</a></li>
  <li><a href="#de-boekhouding-van-de-pinguïnlijn" id="toc-de-boekhouding-van-de-pinguïnlijn">De boekhouding van de pinguïnlijn</a></li>
  <li><a href="#dezelfde-boekhouding-op-2634-vragenlijsten" id="toc-dezelfde-boekhouding-op-2634-vragenlijsten">Dezelfde boekhouding op 2634 vragenlijsten</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/bigfive.csv" download="bigfive.csv">bigfive.csv</a> 2634 ingevulde vragenlijsten · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="tweeëntwintig-pinguïns-van-precies-190-millimeter" class="level2">
<h2 class="anchored" data-anchor-id="tweeëntwintig-pinguïns-van-precies-190-millimeter">Tweeëntwintig pinguïns van precies 190 millimeter</h2>
<p><span class="begrippen">voorspelling · gokfout</span></p>
<p>De pinguïns zijn oude bekenden — in <a href="../20_blokken/blok_enkelvoudige_regressie.html">Oefening 3.2</a> trok je er zelf een lijn door: het gewicht voorspeld uit de vinlengte, bijna vijftig gram pinguïn per millimeter vin, en <em>R</em>² = .76.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Driekwart van alle verschil in gewicht loopt langs de vin mee. Dat is veel, voor levende dieren, en het klinkt alsof de lijn het gewicht daarmee wel zo ongeveer wéét.</p>
<p>En nu iets raars. In het bestand zitten <strong>tweeëntwintig</strong> pinguïns met een vin van precies 190 millimeter. De lijn kent alleen de vinlengte, dus die tweeëntwintig krijgen alle tweeëntwintig dezelfde voorspelling: 3659.4 gram. Wat de weegschaal werkelijk zei, in grammen:</p>
<blockquote class="blockquote">
<p><strong>3050</strong> · 3325 · 3400 · 3450 · 3450 · 3450 · 3575 · 3600 · 3600 · 3650 · 3700 · 3700 · 3725 · 3800 · 3900 · 3900 · 3900 · 3950 · 4250 · 4250 · 4250 · <strong>4600</strong></p>
</blockquote>
<p>Van 3050 tot 4600 — anderhalve kilo verschil, bij één en dezelfde vinlengte. De lijn kan daar niets aan doen: hij weet maar één ding van een pinguïn, en dat ene ding was tweeëntwintig keer gelijk.</p>
<p>En die tweeëntwintig zijn geen rariteit die je toevallig trof. Kies een andere vinlengte en je ziet hetzelfde, alleen met minder dieren tegelijk op een kluitje: overal langs de lijn zit de werkelijkheid erboven en eronder. Dat zet een vraag op scherp die we tot nu toe hebben laten liggen: <strong>hoe ver zit de lijn er per pinguïn naast — en wat kun je met die gokfouten doen?</strong></p>
<p>Trek even mee. De lijn heeft gegokt; wij gaan nakijken.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="reken-de-gokfouten-uit-op-de-twaalf-steentjes" class="level2">
<h2 class="anchored" data-anchor-id="reken-de-gokfouten-uit-op-de-twaalf-steentjes">Reken de gokfouten uit op de twaalf steentjes</h2>
<p><span class="begrippen">residu · voorspelde waarde</span></p>
<p>Zo’n gokfout heb je in het boek al zien staan: <strong>DATA = FIT + RESIDU</strong>. De <em>fit</em> is wat de lijn gokt, het <strong>residu</strong> is wat er overblijft — de gokfout, nu niet meer ten opzichte van het gemiddelde maar ten opzichte van de lijn.</p>
<p>Je komt dat ene ding onder vier namen tegen: <strong>gokfout</strong>, <strong>residu</strong>, <strong>afwijking</strong>, en in Engelse uitvoer en artikelen <em>error</em> (of <em>residual</em>). Het is telkens de afstand tussen wat er echt is en wat de lijn gokte. In dit blok heet hij <em>gokfout</em>; zegt JASP <em>Residual</em> of een plaatje <em>residu</em>, dan is het precies hetzelfde.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Open <code>diamantjes.csv</code> en maak twee kolommen in het <strong>R</strong>-vak (type <strong>Scale</strong>):</p>
<pre><code>gok      -&gt;   fitted(lm(glans ~ karaat))
residu   -&gt;   resid(lm(glans ~ karaat))</code></pre>
<p>In <code>gok</code> staat wat de lijn gokt, in <code>residu</code> wat er overblijft. Afgerond op één decimaal:</p>
<pre><code>gok       30.7   33.9   33.9   40.4   50.0   50.0   53.2   56.4   59.6   59.6   66.1   66.1
residu   -10.7   -3.9   -3.9  -10.4    0.0   20.0   26.8    3.6   10.4   20.4  -36.1  -16.1</code></pre>
<p>Tel <code>residu</code> daarna op: <strong>Descriptives</strong>, <code>residu</code> bij <strong>Variables</strong>, en onder <em>Statistics</em> het vinkje <strong>Sum</strong>.</p>
<p><span class="even-checken">Kijk of die som ook bij jou nul is — op wat rekenstof na. Doet hij dat niet, dan heb je onderweg iets anders in handen gekregen dan de residuen van dit model.</span></p>
</div>
</div>
<p>Dat zijn precies de twee kolommen uit de tabel in het boek: Else valt op nul (de lijn gaat dwars door haar heen), Kees zit er met −36.1 het verst naast. Nieuw is alleen het <strong>plaatje</strong> hieronder — je zet die twee kolommen tegen elkaar in plaats van ze te lezen:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de gokfouten in een plaatje · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de gokfouten in een plaatje · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Draai <strong>Regression → Linear Regression</strong> met <code>glans</code> als <strong>Dependent Variable</strong> en <code>karaat</code> bij <strong>Covariates</strong>, en vink onder <strong>Plots</strong> de optie <strong>Residuals vs. predicted</strong> aan: de gok op de liggende as, de gokfout op de staande, en de nullijn er dwars doorheen.</p>
</div>
</div>
<p>Kijk goed wat dat plaatje doet. De regressielijn is <strong>plat geworden</strong>: alles wat de lijn al wist is eruit gerekend, dus wat overblijft hoort rond de nullijn te zweven. Een residuenplot is een schoongeveegde puntenwolk — je kijkt niet meer naar het verband, je kijkt naar wat het verband liet liggen.</p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eerst de twaalf diamantjes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst de twaalf diamantjes
</div>
</div>
<div class="callout-body-container callout-body">
<p>Twee vragen voor je verder leest.</p>
<p><strong>a)</strong> Vraag de standaardafwijking van de glans op, en die van de residuen. (twee getallen, en één zin over wat het verschil tussen die twee betekent)</p>
<p><strong>b)</strong> Kwadrateer allebei die getallen, tel de twaalf gekwadrateerde afwijkingen van de glans op en doe hetzelfde met de residuen. (In de tabel <strong>ANOVA</strong> van je regressie staan ze allebei.) (twee sommen, en zeg welk deel van de eerste door de tweede wordt opgeslokt)</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> De glans zelf spreidt met <em>SD</em> = 21.74 glanspunten, de residuen met <em>SD</em> = 17.75. Zonder lijn is je beste gok voor elk steentje het gemiddelde, en dan zit je er typisch bijna 22 punten naast; met de lijn nog bijna 18. De lijn scheelt je dus wel iets, maar niet veel — bij deze twaalf steentjes is het karaat lang niet alles.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong> met <code>glans</code> en <code>residu</code>: <em>Std. deviation</em> 21.742 en 17.746.</p>
</div>
</div>
<p><strong>b)</strong> De glans om zijn eigen gemiddelde geeft <strong>5200.0</strong>; de glans om de lijn geeft <strong>3464.3</strong>. Van alle verschil in glans blijft er dus tweederde over nadat de lijn zijn deel heeft gehad — en dat ene derde dat hij wél pakt, is precies de <em>R</em>² = .33 die je in Oefening 3.1 en 3.2 zag.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>In de tabel <strong>ANOVA</strong> staat onder <em>Sum of Squares</em>: <em>Total</em> 5200.000 en <em>Residual</em> 3464.286. De rij ertussen, <em>Regression</em> 1735.714, is het stuk dat de lijn wél pakt.</p>
</div>
</div>
<p>Waaróm dat zo is, staat hieronder.</p>
</div>
</div>
</div>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="het-residu-en-waar-r²-vandaan-komt" class="level2">
<h2 class="anchored" data-anchor-id="het-residu-en-waar-r²-vandaan-komt">Het residu, en waar <em>R</em>² vandaan komt</h2>
<p><span class="begrippen">residu · residuenplot · <em>R</em>²</span></p>
<p>Kijk nog eens naar die som van de residuen. Nul — niet ongeveer, maar op afrondingsgruis na exact. Dat is geen toeval en ook geen compliment aan de lijn: het is de bouw. Zo is de lijn gelegd — voor elke gokfout in de plus staat er evenveel min tegenover, want bleef er iets over, dan kon de hele lijn een stukje opschuiven en was het de best passende lijn niet.</p>
<p>Zoek voor jezelf momentjes om te controleren — het zou nul moeten zijn, klopt dat? Onthoud die nul dus wél als controle-momentje: telt jouw kolom residuen niet op tot nul, dan is er onderweg iets misgegaan.</p>
<p>Maar let op wat het óók betekent. Juist omdát die som altijd nul is — bij een lijn die strak door de wolk loopt én bij een lijn die er van alles naast laat liggen — zegt hij níéts over hoe goed de lijn gokt. Plus en min heffen elkaar toch wel op. Wil je weten hoe goed, dan moet je niet optellen maar kijken: <strong>hoe breed liggen de gokfouten om de nul?</strong></p>
<p>En dat is precies wat je in de residuenplot ziet. De tweeëntwintig waar dit blok mee opende staan er als één kolom in: zelfde gok, tweeëntwintig gokfouten, boven en onder de nul.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · teken de gokfouten en tel de tuin · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · teken de gokfouten en tel de tuin · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Open <code>penguins.csv</code> en draai <strong>Regression → Linear Regression</strong> met <code>gewicht</code> als <strong>Dependent Variable</strong> en <code>vinlengte</code> bij <strong>Covariates</strong>; vink onder <strong>Plots</strong> de <strong>Residuals vs.&nbsp;predicted</strong> aan. Maak daarna dezelfde kolom als bij de steentjes:</p>
<pre><code>residu   -&gt;   resid(lm(gewicht ~ vinlengte))</code></pre>
<p><strong>Descriptives</strong> geeft je de twee getallen die je nodig hebt: <code>gewicht</code> spreidt met <em>Std. deviation</em> 801.955, <code>residu</code> met 393.700. Deel ze op elkaar en kwadrateer, in drie stapjes die je allemaal kunt narekenen:</p>
<pre><code>393.700 / 801.955 = 0.491
0.491 x 0.491     = 0.241
1 - 0.241         = .759</code></pre>
<p>Let op één getal in <strong>Model Summary</strong>: daar staat <em>RMSE</em> 394.278 en niet 393.700. Geen van beide is fout — de <em>RMSE</em> deelt door 340 (342 dieren min de twee getallen die de lijn beschrijven, het intercept en de helling), een standaardafwijking door 341.</p>
</div>
</div>
<p>Zonder lijn was je beste gok voor elk gewicht het gemiddelde — dat spel ken je — en dan was je typische gokfout 801.95 gram, de standaardafwijking van het gewicht. Mét de lijn blijft er 393.70 gram over: de standaardafwijking van de gokfouten. De lijn scheelt je dus 408.25 gram, <strong>ruim de helft</strong> van je gokfout.</p>
<p>En toch zei Oefening 3.2 <em>R</em>² = .76. Driekwart. Wie liegt er — de helft of de driekwart? Geen van beide; ze tellen in een andere maat. Denk aan alle verschil in gewicht als een <strong>tuin vol variatie</strong>. Een verband verklaren is geen lijntje verklaren maar oppervlakte, en oppervlakte gaat in kwadraten — dus kwadrateer de twee gokfouten vóór je ze op elkaar deelt. Dan staat er .76: het verklaarde stuk van de tuin, gedeeld door de hele tuin. In meters langs de rand wint de lijn ruim de helft; in tuinoppervlakte driekwart. Het is dezelfde winst, twee keer opgemeten.</p>
<p>En <em>R</em>² heeft daar niets nieuws voor nodig: alles wat hij weet, zit al in de gokfouten. Doe dezelfde deling op de twaalf steentjes en er komt .33 uit — precies het kwadraat van de <em>r</em> = .58 die je aan het begin van dit hoofdstuk zelf in elkaar zette. Twee routes, één getal: de correlatie kwadrateren, of de gokfouten boekhouden.</p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="de-boekhouding-van-de-pinguïnlijn" class="level2">
<h2 class="anchored" data-anchor-id="de-boekhouding-van-de-pinguïnlijn">De boekhouding van de pinguïnlijn</h2>
<p><span class="begrippen">som van de residuen · residuenplot · <em>R</em>² uit de gokfouten</span></p>
<p>Nu jij, op de lijn uit de prikkel: het gewicht van 342 pinguïns, voorspeld uit hun vinlengte. Je hebt hem in Oefening 3.2 getrokken en gelezen; nu ga je uitrekenen wat hij liet liggen.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · zet klaar · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · zet klaar · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>penguins.csv</code> staat open en de regressie van <code>gewicht</code> op <code>vinlengte</code> draait. Eén kolom komt er nog bij, naast <code>residu</code>:</p>
<pre><code>gok      -&gt;   fitted(lm(gewicht ~ vinlengte))</code></pre>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Beantwoord de vragen op volgorde; ze bouwen op elkaar. De laatste heet met opzet <strong>Z)</strong> en niet k): de wolk-vraag staat altijd achteraan.</p>
<p>Het zijn er elf, en dat is te veel voor één zitting. <strong>Na e) heb je de gokfouten in handen en heb je de prikkel teruggevonden</strong> — een goed moment om te stoppen. Bij f) begint de boekhouding, en dat is het stuk waar <em>R</em>² uit rolt.</p>
<p><strong>a)</strong> Vraag van de eerste zes pinguïns de voorspelling en het residu op (de eerste zes rijen van <code>gok</code> en <code>residu</code>). Tel bij één van de zes de twee op en leg de uitkomst naast zijn echte gewicht. (twee rijtjes van zes, en één som)</p>
<p><strong>b)</strong> Tel alle 342 residuen op. Wat komt eruit, en waarom is dat géén compliment aan de lijn? (één getal, en twee zinnen)</p>
<p><strong>c)</strong> Teken de residuenplot. Wat hoort daar te staan, en wat zie je? (twee zinnen)</p>
<p><strong>d)</strong> Zoek de pinguïn waar de lijn er het verst naast zit, naar boven en naar onder. (twee getallen mét eenheid, en zeg van welke soort ze zijn)</p>
<p><strong>e)</strong> Terug naar de tweeëntwintig uit de prikkel. Vraag de residuen op van de pinguïns met een vin van precies 190 millimeter. (de kleinste en de grootste, en één zin over wat er in de residuenplot boven die ene gok staat)</p>
<p><strong>f)</strong> Nu de boekhouding. Tel de gekwadrateerde afwijkingen van het gewicht om zijn eigen gemiddelde op, en die van de residuen om nul. Tel daarna de gekwadrateerde afstanden van de lijn tot het gemiddelde op (alle drie staan in de tabel <strong>ANOVA</strong>, onder <em>Sum of Squares</em>: bij <em>Total</em>, <em>Residual</em> en <em>Regression</em>). (drie getallen — en tel de laatste twee bij elkaar op)</p>
<p><strong>g)</strong> Reken <em>R</em>² uit die getallen: één min de residu-som gedeeld door de totaal-som. Leg het naast de <em>R</em>² in <strong>Model Summary</strong>. (twee getallen)</p>
<p><strong>h)</strong> Vraag de standaardafwijking van het gewicht op en die van de residuen. Hoeveel procent van je gokfout scheelt de lijn — en waarom is dat een ánder getal dan de <em>R</em>² uit g)? (twee getallen, en twee zinnen)</p>
<p><strong>i)</strong> Kleur de residuenplot per soort en vraag het gemiddelde residu per soort op. Wat zegt dat over de lijn? (drie getallen, en twee zinnen)</p>
<p><strong>j)</strong> Schrijf je bevinding op in één zin. (wat de lijn dekt, en wat hij per pinguïn laat liggen)</p>
<p><strong>Z) Is de wolk recht, en zitten er geen punten tussen die de boel verneuken?</strong> Kijk naar je residuenplot uit c) — ligt er een boog in, of hangt er één dier zo ver weg dat het in zijn eentje aan de lijn trekt? (twee korte uitspraken, en zeg welke van je antwoorden hierboven eraan hangen)</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> De zes voorspellingen zijn 3212.3 · 3460.7 · 3907.9 · 3808.5 · 3659.4 · 3212.3 gram, en de zes residuen 537.7 · 339.3 · −657.9 · −358.5 · −9.4 · 412.7. Tel ze per dier op en je hebt het gewicht terug: de eerste pinguïn weegt 3212.3 + 537.7 = 3750 gram, en dat staat ook in het bestand. <strong>DATA = FIT + RESIDU</strong>, letterlijk.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>Kijk in je gegevens naar de eerste zes rijen van <code>gok</code>, <code>residu</code> en <code>gewicht</code>. Wil je ze als tabel: vink onder <strong>Statistics</strong> bij <em>Residuals</em> de optie <strong>Casewise diagnostics</strong> aan en zet hem op <strong>All</strong>.</p>
</div>
</div>
<p><strong>b)</strong> Nul, op afrondingsgruis na. En dat is geen compliment: het is de manier waarop de lijn gelegd is. Elke gokfout in de plus heeft een gokfout in de min tegenover zich staan, en dat geldt voor élke best passende lijn — ook voor een die er compleet naast zit. Een getal dat altijd hetzelfde is, kan je niets vertellen over hoe goed het gaat.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong> met <code>residu</code>, vinkje <strong>Sum</strong>: er staat nul, op wat rekenstof na.</p>
</div>
</div>
<p><strong>c)</strong> Er hoort een vormeloze wolk te staan rond de nullijn: alles wat de lijn al wist is eruit gerekend, dus wat overblijft mag geen patroon meer dragen. En dat is ook wat je ziet — een band van punten die van links naar rechts ongeveer even breed blijft en nergens duidelijk omhoog of omlaag loopt. Je ziet de verticale strepen wél: pinguïns zijn op hele millimeters opgemeten, dus de gokken vallen op een beperkt aantal plekken.</p>
<p><strong>d)</strong> Naar boven zit de lijn er 1288.69 gram naast (een Adélie, rij 39) en naar onder 1058.80 gram (een Chinstrap, rij 313). Ruim een kilo, allebei — bij dieren die gemiddeld ruim vier kilo wegen.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong> met <code>residu</code> geeft <em>Minimum</em> −1058.797 en <em>Maximum</em> 1288.687. Wie die twee dieren zijn, zoek je met het <strong>Filter</strong>: <code>residu == max(residu)</code> laat één rij over, en daar lees je de soort af. Zet het filter daarna weer uit.</p>
</div>
</div>
<p><strong>e)</strong> Van −609 tot +941 gram. In de residuenplot staat boven die ene gok van 3659.4 dus één verticale streep van tweeëntwintig punten, ruim anderhalve kilo lang. Dat is de prikkel, nu als plaatje: dezelfde voorspelling, tweeëntwintig verschillende gokfouten.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>Zet in het <strong>Filter</strong> <code>vinlengte == 190</code> — er blijven 22 dieren over — en vraag van <code>residu</code> het <em>Minimum</em> en <em>Maximum</em> op: −609.426 en 940.574. Filter daarna weer uit.</p>
</div>
</div>
<p><strong>f)</strong> De totaal-som is <strong>219 307 697</strong>, de residu-som <strong>52 854 796</strong> en de fit-som <strong>166 452 902</strong>. Tel die laatste twee op en je krijgt de eerste terug, tot op de eenheid. Dat is <code>DATA = FIT + RESIDU</code>, maar dan in gekwadrateerde afwijkingen — en dát is de vorm waarin de boekhouding klopt.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>Alle drie staan in de tabel <strong>ANOVA</strong>, onder <em>Sum of Squares</em>: <em>Total</em> 219307697.368, <em>Residual</em> 52854795.628 en <em>Regression</em> 166452901.740. Dat zijn dezelfde drie getallen als hierboven, alleen zonder spaties en met drie decimalen erachter.</p>
</div>
</div>
<p><strong>g)</strong> <strong>.76</strong>, allebei.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>Zelf rekenen: 1 − 52854795.628 / 219307697.368 = .759 — jouw eigen getal, dus zonder de nul ervoor. En in <strong>Model Summary</strong> staat 0.759, want JASP draagt zijn nul wél mee.</p>
</div>
</div>
<p>En dat is de pointe van deze oefening. <em>R</em>² is geen aparte maat die JASP ergens vandaan tovert: het is de tuin die de lijn pakt, gedeeld door de hele tuin. Je hebt hem net zelf uit de gokfouten gerekend.</p>
<p><strong>h)</strong> De standaardafwijking van het gewicht is 801.95 gram, die van de residuen 393.70. De lijn scheelt je dus 408.25 gram, en dat is <strong>51 procent</strong> van je gokfout — ruim de helft, niet driekwart.</p>
<p>Twee zinnen waarom die twee getallen allebei kloppen: de 51 procent telt in grammen, langs de rand van de tuin, en de .76 telt in oppervlakte. Kwadrateren maakt van ruim de helft driekwart — reken maar na, 393.70 gedeeld door 801.95 is .49, en .49 in het kwadraat is .24, en één min .24 is .76.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong> met <code>gewicht</code> en <code>residu</code>: <em>Std. deviation</em> 801.955 en 393.700. (De <em>RMSE</em> van 394.278 in <strong>Model Summary</strong> is een ander getal — zie het kader hierboven bij de tuin.)</p>
</div>
</div>
<p><strong>i)</strong> Adélie <strong>+43.5</strong>, Chinstrap <strong>−215.7</strong>, Gentoo <strong>+65.8</strong> gram.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong>, <code>residu</code> bij <strong>Variables</strong> en <code>soort</code> bij <strong>Split</strong>: 43.539, −215.683 en 65.789 gram. De gekleurde residuenplot maak je onder <strong>Descriptives → Plots → Scatter plots</strong> met <code>gok</code> en <code>residu</code>, en <strong>Color by / group</strong> op <code>soort</code>.</p>
</div>
</div>
<p>Twee zinnen: over alle 342 heen is het gemiddelde residu nul, maar per soort is het dat niet — de lijn zit voor de Chinstraps stelselmatig ruim twee ons te hoog en voor de andere twee een beetje te laag. Dat wil zeggen dat er ook hier nog een derde speler in de wolk zit, precies zoals in Oefening 3.1; alleen is hij deze keer klein genoeg om de lijn niet om te gooien.</p>
<p><strong>j)</strong> Bijvoorbeeld:</p>
<blockquote class="blockquote">
<p>De lijn van gewicht op vinlengte dekte ruim driekwart van de verschillen in gewicht bij 342 pinguïns (<em>R</em>² = .76), maar liet per dier nog altijd bijna vierhonderd gram spreiding om zich heen liggen (<em>SD</em> van de residuen = 393.70).</p>
</blockquote>
<p><strong>Z)</strong> Ja — allebei komen ze goed uit.</p>
<p><em>Er ligt geen boog in.</em> De residuen lopen niet stelselmatig omhoog of omlaag met de voorspelling; sterker nog, de samenhang tussen de gok en de gokfout is exact nul, en dat is geen bevinding maar de bouw — dat is precies wat “de lijn is plat geworden” betekent. Wat je wél kunt nakijken is of er een <em>kromme</em> in zit, en dat doe je door de lijn een knik toe te staan. De <em>R</em>² was .76, op vier decimalen .7590; met de knik erbij wordt het .7753. Ruim anderhalve procent erbij — maar dat is geen bocht, dat is een parameter erbij, en die kan de <em>R</em>² alleen maar omhoog duwen.</p>
<p><em>En geen pinguïn trekt in zijn eentje aan de lijn.</em> De grootste gokfout is 1288.69 gram, en dat is ruim drie keer de standaardafwijking van de residuen — een dier dat opvalt, maar niet een dier dat de lijn kantelt. Laat je hem weg, dan beweegt de helling nauwelijks.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regression → Correlation</strong> met <code>gok</code> en <code>residu</code>: <em>Pearson’s r</em> 0.000 — op machineruis na precies nul.</p>
</div>
</div>
<p>Wat eraan hángt, als het wél mis was gegaan: de hele boekhouding blijft staan — de sommen bij f), de <em>R</em>² bij g), de standaardafwijkingen bij h) en de soortgemiddelden bij i) zijn optellingen op deze 342 dieren, en die kloppen wat er ook krom is. Wat je overdoet is elke zin waarin je de lijn <em>aanbeveelt</em>: bij j) staat dat hij driekwart dekt, en als het verband krom loopt is dat geen leugen maar wel een lijn die je op de verkeerde plek in de steek laat.</p>
</div>
</div>
</div>
<div class="kicker">
<p>eindopdracht</p>
</div>
</section>
<section id="dezelfde-boekhouding-op-2634-vragenlijsten" class="level2">
<h2 class="anchored" data-anchor-id="dezelfde-boekhouding-op-2634-vragenlijsten">Dezelfde boekhouding op 2634 vragenlijsten</h2>
<p><span class="begrippen">schaalscore · <em>R</em>² uit de gokfouten · steekproefzin</span></p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eindopdracht">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eindopdracht
</div>
</div>
<div class="callout-body-container callout-body">
<p>De afsluiter van het hele hoofdstuk, en hij eindigt waar dit boek altijd eindigt: bij mensen.</p>
<p>In <code>bigfive.csv</code> staan <strong>2634 mensen</strong> die vijfentwintig uitspraken over zichzelf beoordeelden op een schaal van 1 tot 6. Je gebruikt er hier tien — vijf over <strong>neuroticisme</strong>, hoe snel je van slag raakt, en vijf over <strong>openheid</strong>, de smaak voor nieuwe dingen. Je hebt ze in Oefening 3.1 en 3.2 al ontmoet; nu doe je er de boekhouding van dit blok op.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · zet de mensen klaar · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · zet de mensen klaar · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Open <code>bigfive.csv</code> en maak drie kolommen in het <strong>R</strong>-vak (type <strong>Scale</strong>):</p>
<pre><code>neuroticisme   -&gt;   rowMeans(data.frame(N1, N2, N3, N4, N5))
openheid       -&gt;   rowMeans(data.frame(O1, O2, O3, O4, O5))
residu_mens    -&gt;   resid(lm(neuroticisme ~ openheid))</code></pre>
<p>Draai daarna <strong>Regression → Linear Regression</strong> met <code>neuroticisme</code> als <strong>Dependent Variable</strong> en <code>openheid</code> bij <strong>Covariates</strong>.</p>
</div>
</div>
<p><strong>a)</strong> Vraag de residuen op en tel ze op. (één getal, en één zin over waarom je dat had kunnen voorspellen)</p>
<p><strong>b)</strong> Vraag de standaardafwijking van het neuroticisme op en die van de residuen. Hoeveel scheelt de lijn je? (twee getallen, en één zin)</p>
<p><strong>c)</strong> Reken <em>R</em>² uit de gokfouten, net als bij de pinguïns. (één getal, en leg het naast de <em>R</em>² in <strong>Model Summary</strong>)</p>
<p><strong>d)</strong> Nu de mensen-versie van de tweeëntwintig pinguïns. Hoeveel mensen scoren precies 4.0 op openheid, welke voorspelling krijgen die allemaal, en hoe ver loopt hun échte neuroticisme uiteen? (drie antwoorden, en één zin)</p>
<p><strong>e)</strong> Schrijf op wat je gevonden hebt, in <strong>twee zinnen</strong> en in deze vaste vorm:</p>
<blockquote class="blockquote">
<p>Binnen deze <em>n</em> mensen geldt: … (<em>R</em>² = …). Of dat ook buiten deze <em>n</em> opgaat, weet je nog niet.</p>
</blockquote>
<p>(vul de <em>n</em>, de bevinding in gewone taal en de <em>R</em>² in — en laat die tweede zin staan zoals hij er staat)</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Nul, op afrondingsgruis na — en dat had je kunnen voorspellen, want dat geldt voor élke best passende lijn, hoe goed of slecht hij ook past. Bij de diamantjes was het zo, bij de pinguïns was het zo, en hier dus ook.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong> met <code>residu_mens</code>, vinkje <strong>Sum</strong>: nul, op wat rekenstof na.</p>
</div>
</div>
<p><strong>b)</strong> Het neuroticisme spreidt met <em>SD</em> = 1.1946 schaalpunten, de residuen met <em>SD</em> = 1.1789. De lijn scheelt je dus 0.0156 schaalpunt op een schaal van 1 tot 6 — oftewel: bijna niets. (Vier decimalen hier met opzet: op twee zie je het verschil niet eens meer.) Wie de openheid van iemand kent, weet daarmee nauwelijks meer over zijn neuroticisme dan wie alleen het gemiddelde kent.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Descriptives</strong>: <em>Std. deviation</em> 1.195 voor <code>neuroticisme</code> en 1.179 voor <code>residu_mens</code>. Wil je de vier decimalen uit de tekst zien — 1.1946 en 1.1789 — zet dan <strong>Preferences → Results → Fix the number of decimals</strong> op 4.</p>
</div>
</div>
<p><strong>c)</strong> <strong>.03</strong>, allebei. Van de hele tuin pakt deze lijn nog geen drie procent.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>1 − 1.1789² / 1.1946² = .026 — jouw eigen getal, zonder de nul ervoor. In <strong>Model Summary</strong> staat 0.026.</p>
</div>
</div>
<p><strong>d)</strong> <strong>470</strong> mensen scoren precies 4.0 op openheid. Die krijgen alle 470 dezelfde voorspelling: <strong>3.21</strong> schaalpunten neuroticisme. En hun échte neuroticisme loopt van <strong>1.0 tot 6.0</strong> — van de laagste score die op deze schaal bestaat tot de hoogste, allemaal binnen die ene gok.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP
</div>
</div>
<div class="callout-body-container callout-body">
<p>Zet in het <strong>Filter</strong> <code>openheid == 4</code>: er blijven 470 rijen over, en dat aantal staat in <strong>Descriptives</strong> bij <em>Valid</em>. Van <code>neuroticisme</code> staat daar <em>Minimum</em> 1.000 en <em>Maximum</em> 6.000. De voorspelling reken je zelf uit met de twee getallen uit <strong>Coefficients</strong>: 1.798 + 0.353 × 4 = 3.210. Filter daarna weer uit.</p>
</div>
</div>
<p>Dat is dezelfde figuur als de tweeëntwintig pinguïns waar dit blok mee opende, maar dan harder: daar liep het echte gewicht over anderhalve kilo uiteen bij één gok, hier loopt het echte neuroticisme over de <strong>hele schaal</strong> uiteen bij één gok. Bij mensen is dat de regel en niet de uitzondering.</p>
<p><strong>e)</strong> Bijvoorbeeld:</p>
<blockquote class="blockquote">
<p>Binnen deze 2634 mensen geldt: wie opener is, scoort gemiddeld iets hoger op neuroticisme, maar openheid en neuroticisme delen nog geen drie procent van hun verschillen (<em>R</em>² = .03). Of dat ook buiten deze 2634 opgaat, weet je nog niet.</p>
</blockquote>
<p>Kijk wat die tweede zin doet. Alles wat je in dit hoofdstuk hebt uitgerekend — de covariantie, de correlatie, de lijn, de residuen, de <em>R</em>² — beschrijft de mensen die je vóór je hebt, en verder niemand. Je hebt geen enkele reden gekregen om aan te nemen dat de volgende 2634 mensen hetzelfde zouden laten zien, en ook geen manier om te zeggen hoe waarschijnlijk dat is.</p>
<p>Dat is precies waar de volgende beweging mee begint.</p>
</div>
</div>
</div>
<div class="boekvorm" data-w="W4">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: de gokfouten zelf uitgerekend, en <em>R</em>² uit de boekhouding in plaats van uit een knop.</p>
<p>In het boek: <strong>W4 — Hangen ze samen?</strong></p>
<p><em>Daar valt DATA = FIT + RESIDU voor het eerst; hier zie je wat er in die derde term zit, en dat het verklaarde deel er gewoon uit te tellen is.</em></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Palmer Penguins — Gorman, Williams &amp; Fraser (2014), Palmer Station Antarctica LTER; via het R-pakket <code>palmerpenguins</code> (CC0). Alle getallen in dit blok zijn op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="pagination-link" aria-label="Oefening 3.2 · Enkelvoudige regressie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 3.2 · Enkelvoudige regressie</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_steekproevenverdeling.html" class="pagination-link" aria-label="Oefening 4.1 · Steekproevenverdeling en standaardfout">
        <span class="nav-page-text">Oefening 4.1 · Steekproevenverdeling en standaardfout</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>