<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 8.2 · Confounding en partiële correlatie – JASP-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_dummy_regressie.html" rel="next">
<link href="../20_blokken/blok_meervoudige_regressie.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">H8 · Meer dan één verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_confounding_partiele_correlatie.html">Oefening 8.2 · Confounding en partiële correlatie</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">JASP-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JASP-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_confounding_partiele_correlatie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 8.2 · Confounding en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in JASP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Vierde beweging · Verschil onthechten</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">H8 · Meer dan één verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_confounding_partiele_correlatie.html">Oefening 8.2 · Confounding en partiële correlatie</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 8.2 · Confounding en partiële correlatie</h1>
<p class="subtitle lead">Overlappende voorspellers, en wat er uniek overblijft · <em>confounding &amp; partial correlation</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#zevenentachtig-gram-en-waar-ze-gebleven-zijn" id="toc-zevenentachtig-gram-en-waar-ze-gebleven-zijn">Zevenentachtig gram, en waar ze gebleven zijn</a></li>
  <li><a href="#reken-de-vin-weg-en-kijk-wat-er-overblijft" id="toc-reken-de-vin-weg-en-kijk-wat-er-overblijft">Reken de vin weg en kijk wat er overblijft</a></li>
  <li><a href="#waarom-de-snavel-instort-hij-zei-niets-eigens" id="toc-waarom-de-snavel-instort-hij-zei-niets-eigens">Waarom de snavel instort: hij zei niets eigens</a></li>
  <li><a href="#twee-maten-die-elkaar-niet-in-de-weg-zitten" id="toc-twee-maten-die-elkaar-niet-in-de-weg-zitten">Twee maten die elkaar niet in de weg zitten</a></li>
  <li><a href="#de-afsluiter-van-het-hele-hoofdstuk" id="toc-de-afsluiter-van-het-hele-hoofdstuk">De afsluiter van het hele hoofdstuk</a></li>
  <li><a href="#schrijf-een-weggerekend-verband-op" id="toc-schrijf-een-weggerekend-verband-op">Schrijf een weggerekend verband op</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="zevenentachtig-gram-en-waar-ze-gebleven-zijn" class="level2">
<h2 class="anchored" data-anchor-id="zevenentachtig-gram-en-waar-ze-gebleven-zijn">Zevenentachtig gram, en waar ze gebleven zijn</h2>
<p><span class="begrippen">confounder · gedeelde variantie · partiële correlatie</span></p>
<p>Er staat nog een rekening open.</p>
<p>In de vorige oefening voorspelde de snavellengte het gewicht van de pinguïns keurig: ruim 87 gram per millimeter, ruim een derde van alle verschil in gewicht verklaard. Toen kwam de vinlengte erbij en bleef er van die 87 gram nog 6.05 over — niet eens van nul te onderscheiden. Je hebt gemeten dát het gebeurde, met drie verschillende meetlatten, en alle drie zeiden hetzelfde.</p>
<p>Maar niemand heeft je verteld wáár die 87 gram naartoe is.</p>
<p>Dat is geen bijvraag. Een helling die instort verdwijnt niet; hij verhuist. En wie dat niet ziet gebeuren, gelooft de eerste de beste regressie die hem uitkomt — want de simpele lijn had een prachtige <em>p</em>, en hij loog. In deze oefening reken je uit waar de 87 gram is gebleven, en je leert het getal kennen dat er een naam aan geeft.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="reken-de-vin-weg-en-kijk-wat-er-overblijft" class="level2">
<h2 class="anchored" data-anchor-id="reken-de-vin-weg-en-kijk-wat-er-overblijft">Reken de vin weg en kijk wat er overblijft</h2>
<p><span class="begrippen">partiële correlatie · residuen · wegrekenen</span></p>
<p>De tabel gaf je een <em>p</em> en een helling. Maar de vraag uit de prikkel was eigenlijk een correlatie-vraag: <em>hoe sterk hangen gewicht en snavel nog samen als de vin er niet tussen zit?</em> Daar bestaat een eigen getal voor, en in JASP is het één sleepbeweging — al loont het de moeite eerst te zien wat die sleep eigenlijk doet.</p>
<p>Het recept is precies wat het woord <em>wegrekenen</em> belooft. Wil je weten wat er van de band tussen gewicht en snavellengte overblijft als de vinlengte er geen rol meer in speelt, dan <strong>haal je uit allebei weg wat de vin erover te zeggen had</strong>, en kijkt of de restjes nog samenhangen. En “wat de vin erover te zeggen had” weghalen — dat zijn residuen, en die ken je uit de oefening over de residuen: wat er van een kolom overblijft nadat een model erdoorheen is getrokken.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de partiële correlatie · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de partiële correlatie · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Ga naar <strong>Regression</strong> en kies <strong>Correlation</strong>.</li>
<li>Sleep <code>gewicht</code> en <code>snavellengte</code> naar het variabelenvak.</li>
<li>Sleep <code>vinlengte</code> naar het vak <strong>Partial out</strong>.</li>
</ol>
<p>De tabel toont nu <em>r</em> = .063. Haal <code>vinlengte</code> weer uit <strong>Partial out</strong> en je ziet wat er zonder wegrekenen staat: <em>r</em> = .595.</p>
</div>
</div>
<p>Van <strong>.595 naar .063</strong>. Dit getal heet de <strong>partiële correlatie</strong> (<em>partial correlation</em>): de samenhang tussen gewicht en snavellengte <em>bij gelijk gehouden vinlengte</em>. Onderzoekers zeggen daar iets deftigs bij — <em>“gecontroleerd voor vinlengte”</em> — maar je weet nu wat er onder dat vak zit: wegrekenen, en kijken wat overblijft.</p>
<p>Dat vak <strong>Partial out</strong> is namelijk geen toverdoos. Wat JASP onder water doet is precies het recept hierboven: uit allebei de kolommen weghalen wat de vin erover te zeggen had — residuen — en kijken of de restjes nog samenhangen. Wil je dat één keer met je eigen handen bouwen, zodat je het voelt in plaats van gelooft: in het <strong>R-broertje</strong> is het drie regels, met gereedschap dat daar al op tafel lag.</p>
<p>Doe het nu andersom, want dat is de andere helft van het antwoord:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · en nu de vin, met de snavel weggerekend · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · en nu de vin, met de snavel weggerekend · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Zet nu <code>gewicht</code> en <code>vinlengte</code> in het variabelenvak, en sleep <code>snavellengte</code> naar <strong>Partial out</strong>: <em>r</em> = .793. Zonder wegrekenen: <em>r</em> = .871.</p>
</div>
</div>
<p>De vin houdt bijna alles over: van .871 naar <strong>.793</strong>. De snavel houdt vrijwel niets over: van .595 naar <strong>.063</strong>. Dáár staat, in twee getallen naast elkaar, wat de tabel je met een <em>p</em> van .244 al probeerde te vertellen.</p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Let op — twee getallen die op elkaar lijken en het niet zijn">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Let op — twee getallen die op elkaar lijken en het niet zijn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Er bestaat een tweede getal met bijna dezelfde naam, en het is een klassieke struikelplek. Naast de <strong>partiële</strong> correlatie is er de <strong>semi-partiële</strong> correlatie (JASP noemt die in zijn tabellen <em>Part</em>). Het verschil zit in hoevéél je wegrekent:</p>
<ul>
<li>bij de <strong>partiële</strong> correlatie haal je de andere voorspeller uit <strong>allebei</strong> de kolommen weg — dat deed het vak <strong>Partial out</strong> hierboven;</li>
<li>bij de <strong>semi-partiële</strong> correlatie haal je hem alleen uit de <strong>voorspeller</strong> weg, en laat je het gewicht heel.</li>
</ul>
<p>Het is dus hetzelfde stukje verklaarde ruimte, afgezet tegen iets anders. Bij de semi-partiële zet je het af tegen <strong>alle</strong> gewichtsverschillen; bij de partiële alleen tegen wat er ná de vin nog te verklaren óverblijft. Zelfde stukje, andere maatstok — en omdat die tweede maatstok kleiner is, is de partiële correlatie altijd de grootste van de twee.</p>
<p>Zet ze allebei in beeld, dan zie je het. Vink in <strong>Regression → Linear Regression</strong> onder <strong>Statistics</strong> het vakje <strong>Part and partial correlations</strong> aan: in <strong>Coefficients</strong> komen er dan twee kolommen bij. Onder <em>Partial</em> staan de .793 en .063 van hierboven; onder <em>Part</em> staat de semi-partiële — <strong>.637</strong> voor de vin, <strong>.031</strong> voor de snavel.</p>
<p>Waarom dit ertoe doet: <strong>de semi-partiële correlatie in het kwadraat is de unieke bijdrage aan <em>R</em>².</strong> Niet de partiële. Reken maar na: .637² = .406, en de <em>R</em>² van het model gaat inderdaad van .354 (snavel alleen) naar .760 als de vin binnenkomt — een sprong van .406. Had je .793 gekwadrateerd, dan was je op .628 uitgekomen, en dat getal staat nergens in de tabellen.</p>
</div>
</div>
<p>Onder elkaar, zodat je ze uit elkaar kunt houden:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">gewone <em>r</em></th>
<th style="text-align: right;">partieel</th>
<th style="text-align: right;">semi-partieel</th>
<th style="text-align: right;">uniek in <em>R</em>²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>vinlengte</td>
<td style="text-align: right;">.871</td>
<td style="text-align: right;">.793</td>
<td style="text-align: right;">.637</td>
<td style="text-align: right;">.406</td>
</tr>
<tr class="even">
<td>snavellengte</td>
<td style="text-align: right;">.595</td>
<td style="text-align: right;">.063</td>
<td style="text-align: right;">.031</td>
<td style="text-align: right;">.001</td>
</tr>
</tbody>
</table>
<p>De onderste rij is het hele verhaal van dit blok in vier getallen: een maat die in zijn eentje een <em>r</em> van .595 haalt, en aan het model één duizendste <em>R</em>² toevoegt.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="waarom-de-snavel-instort-hij-zei-niets-eigens" class="level2">
<h2 class="anchored" data-anchor-id="waarom-de-snavel-instort-hij-zei-niets-eigens">Waarom de snavel instort: hij zei niets eigens</h2>
<p><span class="begrippen">confounder · constant houden · overlap tussen voorspellers</span></p>
<p>De simpele lijn schreef álle 87.42 gram per millimeter toe aan de snavellengte. Maar er speelde iemand mee die niet in het model zat: de <strong>vinlengte</strong>. Pinguïns met een lange snavel hebben meestal ook lange vinnen — de twee maten hangen onderling samen met <em>r</em> = .656. Gooi je ze op één hoop en trek je één lijn op de snavel alleen, dan telt een flink deel van “lange vin weegt meer” mee als “lange snavel weegt meer”. De snavellengte kreeg krediet dat eigenlijk aan de vin toebehoorde.</p>
<p>Reken je de vin mee — houd ’m constant, vergelijk pinguïns <em>met dezelfde vinlengte</em> — dan valt dat geleende stuk weg, en blijft er van de snavel bijna niets over: <strong>6.05</strong>, en niet eens te onderscheiden van nul. Dat is precies wat meervoudige regressie doet. Ze vraagt niet “hangt gewicht samen met snavellengte?”, maar: <em>wat draagt elke voorspeller bij als de andere gelijk blijft?</em> Elke helling in het model is een helling <strong>met de rest vastgehouden</strong>.</p>
<p>De vinlengte was hier een <strong>confounder</strong>: een derde speler die zich vermomde als een stuk van het snavel-effect. Precies wat gladheid deed bij de steentjes, en dezelfde les als de Simpson-paradox die je bij de correlatie-wolk al tegenkwam.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · hoeveel overlappen de twee? · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · hoeveel overlappen de twee? · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regression → Correlation</strong>, met <code>vinlengte</code> en <code>snavellengte</code> in het variabelenvak (en niets in <strong>Partial out</strong>): <em>r</em> = .656.</p>
</div>
</div>
<p><strong>Dat ene getal beslist alles in dit blok.</strong> Twee voorspellers die sterk samenhangen vertellen elkaars verhaal; de zwakste van de twee houdt dan niets eigens over. Hangen ze nauwelijks samen, dan kunnen ze allebei hun eigen bijdrage leveren — en dat ga je zo bij <em>Jouw beurt</em> zelf zien gebeuren.</p>
<p>Speel de film nog één keer af, maar nu zoals je hem zelf gedraaid zou hebben. Je begon met de snavellengte, en die deed het prima: <em>R</em>² = .354, ruim een derde van alle verschil in gewicht verklaard, uit één maat. Toen zag je de vinlengte — en die hangt óók samen met het gewicht, sterker zelfs: in z’n eentje haalt hij <em>R</em>² = .759. Dus bouw je een supermodel, allebei erin, en de verwachting schrijft zichzelf: .354 + .759 = 1.113. Meer dan alles. Meer dan honderd procent van de verschillen in gewicht verklaard — en aan die onmogelijkheid zie je al dat er met dat optellen iets niet klopt, want meer verklaren dan er verschil ís, dat bestaat niet. Goed, denk je, dan geen 1.113. Maar ruim boven de .759 toch zeker wel?</p>
<p>Samen halen ze <em>R</em>² = .760. Eén duizendste boven de vin alleen.</p>
<p>Waar is de rest gebleven? Nergens — hij is nooit weggeweest, hij was alleen dubbel geteld. Je weet inmiddels waarom: de twee voorspellers vertellen voor een flink deel hetzelfde verhaal, <em>r</em> = .656. Een flink deel van wat de snavel over het gewicht wist, wist de vin dus ook al.&nbsp;In de optelsom .354 + .759 telde je dat gedeelde verhaal twee keer mee — één keer via de snavel, één keer via de vin. Het model telt het één keer, want vaker dan één keer valt er niets te verklaren.</p>
<p>En hoe groot dat dubbel getelde stuk is, staat er gewoon: .354 + .759 − .760 = .353. Je kwam .353 te véél uit, en dat is precies het stuk verschil in gewicht dat snavel en vin sámen weten — je kunt het aan geen van beide alleen toeschrijven.</p>
<p>Nu het mooie. Tel eens de andere kant op: niet wat elk alléén kan, maar wat elk uniek toevoegt — de kolom uniek in <em>R</em>² uit de tabel hierboven. Vin .406, snavel .001, samen .407. Ook geen .760: .760 − .407 = .353, dus nu kom je .353 tekort. Hetzelfde getal, en dat moet ook, want het is hetzelfde stuk: in de eerste som telde je het gedeelde stuk twee keer, in de tweede nul keer, en het model telt het precies één keer. Het gedeelde stuk is van allebei, en dus van geen van beide alleen.</p>
<p>De les van deze oefening, in drie regels:</p>
<ul>
<li>De <strong>partiële correlatie</strong> zei waar de 87 gram gebleven is: reken de vinlengte weg en de band tussen gewicht en snavel zakt van .595 naar .063. De snavel had niets eigens; hij leende.</li>
<li>De <strong>confounder</strong> is de naam voor wat er gebeurde: een derde speler die niet in het model zat en zich vermomde als een stuk van het snavel-effect.</li>
<li>De <strong>overlap</strong> zegt hoe groot dat geleende stuk was: <em>r</em> = .656 tussen de twee voorspellers, en .353 van de verklaarde ruimte die van allebei is en dus van geen van beide.</li>
</ul>
<p>Daarmee is de vraag beantwoord waarmee deze oefening opende. En let op wat er niet is gebeurd: er is geen enkel getal veranderd. Dezelfde 342 pinguïns, dezelfde weegschaal, dezelfde snavels. Alleen de vraag werd scherper — niet <em>hangt dit samen?</em> maar <em>hangt dit samen als ik de rest vasthoud?</em> — en het antwoord ging van “ruim 87 gram per millimeter” naar “niets dat ik van nul kan onderscheiden”. Dat is geen trucje van de statistiek. Dat is wat er gebeurt als je een medespeler binnenlaat die er altijd al was.</p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="twee-maten-die-elkaar-niet-in-de-weg-zitten" class="level2">
<h2 class="anchored" data-anchor-id="twee-maten-die-elkaar-niet-in-de-weg-zitten">Twee maten die elkaar niet in de weg zitten</h2>
<p><span class="begrippen">unieke bijdrage · overlap tussen voorspellers · partiële correlatie</span></p>
<p>Hierboven stierf de snavellengte naast de vin. Nu zet je diezelfde snavellengte naast een ándere maat — de <strong>snaveldiepte</strong> (<code>snaveldiepte</code>, in mm) — en dan loopt het heel anders af. Draai eerst de drie modellen, en beantwoord daarna de vragen. De laatste heet weer <strong>Z)</strong>: de aannames staan altijd achteraan.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · de drie modellen · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · de drie modellen · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Draai <strong>Regression → Linear Regression</strong> drie keer, steeds met <code>gewicht</code> als <strong>Dependent Variable</strong>:</p>
<ul>
<li><strong>het lengte-model</strong> — alleen <code>snavellengte</code> in <strong>Covariates</strong>;</li>
<li><strong>het diepte-model</strong> — alleen <code>snaveldiepte</code>;</li>
<li><strong>het model met allebei</strong> — allebei de snavelmaten. Zet voor vraag h de <strong>Model</strong>-blokken in, met <strong>R squared change</strong> aan: <code>snaveldiepte</code> in blok 1, <code>snavellengte</code> erbij in blok 2.</li>
</ul>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoeveel gram per millimeter voorspelt het lengte-model, en hoeveel van het verschil in gewicht verklaart hij? (rapporteer <em>b</em> en <em>R</em>²)</p>
<p><strong>b)</strong> Doe hetzelfde voor het diepte-model. Let op het teken — klopt dat met wat je zou verwachten? (rapporteer <em>b</em> en <em>R</em>²)</p>
<p><strong>c)</strong> Toets nu het model met allebei als geheel. Schrijf de nulhypothese eerst voluit op, in woorden én in symbolen. (rapporteer <em>R</em>², <em>F</em>(<em>df</em><sub>1</sub>, <em>df</em><sub>2</sub>) en <em>p</em>, en de hypothesen in symbolen)</p>
<p><strong>d)</strong> Wat gebeurt er met de helling van de snavellengte als de snaveldiepte ernaast komt te staan — en hoe verhoudt dat zich tot wat er in dit blok met diezelfde snavellengte naast de vinlengte gebeurde?</p>
<p><strong>e)</strong> Blijven ze allebei significant in het model met allebei? (rapporteer per voorspeller <em>b</em>, <em>SE</em>, <em>t</em>, <em>p</em> en het 95%-interval)</p>
<p><strong>f)</strong> Reken de overlap uit: de correlatie tussen <code>snavellengte</code> en <code>snaveldiepte</code>. Vergelijk met de .656 van vin en snavel. Wat voorspelt dat ene getal over de uitkomst van vraag d?</p>
<p><strong>g)</strong> Reken de twee partiële correlaties uit, met het vak <strong>Partial out</strong> uit dit blok. (rapporteer beide)</p>
<p><strong>h)</strong> Hoeveel voegt de <strong>snavellengte</strong> uniek toe aan de <em>R</em>²? Zet <code>snaveldiepte</code> in blok 1 en <code>snavellengte</code> erbij in blok 2, en lees de regel van blok 2. (rapporteer Δ<em>R</em>² en de <em>F</em>-toets) — voor de snaveldiepte krijg je hem kado: Δ<em>R</em>² = .117, <em>F</em>(1, 339) = 74.76.</p>
<p><strong>i)</strong> Tel die twee unieke bijdragen bij elkaar op en vergelijk met de <em>R</em>² van het model met allebei. Ze tellen niet op. Waar is het verschil gebleven?</p>
<p><strong>Z)</strong> Mag je dit model eigenlijk wel gebruiken? Loop de aannames na: kijk naar de residuen (onder <strong>Plots</strong> het spreidingsdiagram <em>Residuals vs.&nbsp;predicted</em> voor gelijke spreiding, en de <em>Q-Q plot standardized residuals</em> voor de verdeling), en of elke pinguïn maar één keer meetelt.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <em>b</em> = 87.42 gram per millimeter, <em>R</em>² = .354.</p>
<p><strong>b)</strong> <em>b</em> = −191.64, <em>R</em>² = .223. Negatief, en dat wringt: over alle pinguïns heen lijkt een <em>diepere</em> snavel bij een <em>lichter</em> beest te horen. Onthoud dat, het komt bij de dummy-oefening en de ANCOVA terug.</p>
<p><strong>c)</strong> De nulhypothese: dit model — snavellengte en snaveldiepte samen — verklaart níéts van de verschillen in gewicht. In symbolen:</p>
<p><span class="math display">\[H_0:\ \beta_1 = \beta_2 = 0 \qquad H_1:\ \text{minstens één } \beta_j \neq 0\]</span></p>
<p>of over de verklaarde variantie: <span class="math inline">\(H_0:\ \rho^2 = 0\)</span> tegen <span class="math inline">\(H_1:\ \rho^2 &gt; 0\)</span> — Grieks (β en ρ²), want het gaat over de populatie en niet over deze 342. Eén van de twee is genoeg.</p>
<p>Uitkomst: <em>R</em>² = .471, <em>F</em>(2, 339) = 150.82, <em>p</em> &lt; .001. Die mag dus de deur uit.</p>
<p><strong>d)</strong> Hij zakt, maar hij stort niet in: van 87.42 naar <strong>75.28</strong>. Vergelijk dat met wat de vin deed — dáár ging dezelfde helling van 87.42 naar 6.05. Naast de vin hield de snavellengte niets over; naast de snaveldiepte houdt hij ruim zesentachtig procent van zijn helling.</p>
<p><strong>e)</strong> Ja, allebei ruimschoots. Snavellengte: <em>b</em> = 75.28, <em>SE</em> = 5.97, <em>t</em>(339) = 12.61, <em>p</em> &lt; .001, 95% CI [63.54, 87.03]. Snaveldiepte: <em>b</em> = −142.72, <em>SE</em> = 16.51, <em>t</em>(339) = −8.65, <em>p</em> &lt; .001, 95% CI [−175.19, −110.25]. Geen van beide intervallen bevat nul.</p>
<p><strong>f)</strong> <em>r</em> = −.235, tegen .656 voor vin en snavel. Dát is het antwoord op vraag d. Twee voorspellers die elkaar nauwelijks overlappen kunnen allebei hun eigen verhaal vertellen; twee die sterk samenhangen vertellen elkaars verhaal, en dan houdt de zwakste niets eigens over.</p>
<p><strong>g)</strong> <em>r</em>(gewicht, snavellengte | snaveldiepte) = <strong>.565</strong> — nauwelijks lager dan de gewone .595. En <em>r</em>(gewicht, snaveldiepte | snavellengte) = <strong>−.425</strong>, tegen een gewone −.472. Vergelijk met de snavel naast de vin: dáár zakte .595 naar .063.</p>
<p><strong>h)</strong> Snavellengte uniek (snaveldiepte in blok 1, snavellengte erbij in blok 2): Δ<em>R</em>² = .248, <em>F</em>(1, 339) = 158.97, <em>p</em> &lt; .001. Snaveldiepte uniek (andersom): Δ<em>R</em>² = .117, <em>F</em>(1, 339) = 74.76, <em>p</em> &lt; .001. Allebei substantieel — en vergelijk dat nog één keer met de .001 van de snavel naast de vin.</p>
<p><strong>i)</strong> .248 + .117 = .365, terwijl <em>R</em>²(het model met allebei) = .471. Er ontbreekt .106. Dat is het <strong>gedeelde</strong> stuk: verschil in gewicht dat de twee samen verklaren, maar dat je aan geen van beide alleen kunt toeschrijven. Precies daarom telt zo’n opsplitsing niet netjes op, en precies daarom is “hoe belangrijk is deze voorspeller?” een lastigere vraag dan hij lijkt.</p>
<p><strong>Z)</strong> Ja, met de gebruikelijke slag om de arm. De residuen liggen in een vrijwel egale band om nul (geen trechter, dus gelijke spreiding is hier geen probleem) en volgen de rechte lijn in de QQ-plot redelijk. Elke pinguïn is één keer gewogen, dus de waarnemingen zijn onafhankelijk. En de twee voorspellers overlappen maar weinig (<em>r</em> = −.235), dus ze zitten elkaar niet in de weg bij het schatten.</p>
</div>
</div>
</div>
<div class="kicker">
<p>eindopdracht</p>
</div>
</section>
<section id="de-afsluiter-van-het-hele-hoofdstuk" class="level2">
<h2 class="anchored" data-anchor-id="de-afsluiter-van-het-hele-hoofdstuk">De afsluiter van het hele hoofdstuk</h2>
<p><span class="begrippen">artikelvorm · methode en resultaten gescheiden · unieke bijdrage</span></p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eindopdracht">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eindopdracht
</div>
</div>
<div class="callout-body-container callout-body">
<p>De afsluiter van het hele hoofdstuk. Je brengt allebei de oefeningen samen — het model draaien en beoordelen uit 8.1, de overlap en het wegrekenen uit 8.2 — en je schrijft het op zoals het in een artikel zou staan.</p>
<p>Deze keer voorspel je niet het gewicht maar de <strong>vinlengte</strong>, uit de twee snavelmaten die je in de taak hierboven al naast elkaar zag staan. Zelfde paar, andere vraag. Zet in JASP de vinlengte als afhankelijke variabele en draai drie modellen: één met alleen de snavellengte, één met alleen de snaveldiepte, en één met allebei.</p>
<p>En let op de vorm: een artikel valt in <strong>twee gelabelde stukken</strong>, en die volgorde is niet dezelfde als de volgorde waarin je het leerde. Toen mocht de aannamecontrole achteraf, want je moest eerst zien wát je nou eigenlijk controleerde. Nu je het opschrijft voor een lezer gaat hij vóórop, want die wil weten of hij je getallen mag geloven vóórdat hij ze leest.</p>
<section id="methode-en-data-analyse" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse">Methode en data-analyse</h3>
<p><strong>a)</strong> Wat onderzoek je, waarop, en met welke analyse? Schrijf het op zonder één uitkomst te noemen. (twee of drie zinnen; wie of wat er gemeten is, hoeveel, en welke analyse)</p>
<p><strong>b)</strong> Hoeveel pinguïns houd je over als je alle drie de maten compleet moet hebben, en hoeveel staan er in het bestand? (twee getallen, en waarom dat er hier toe doet als je straks modellen van elkaar aftrekt)</p>
<p><strong>c)</strong> Loop de aannames na en schrijf ze op als data-analyse-alinea: liggen de residuen symmetrisch, is de spreiding van de residuen ongeveer gelijk over het bereik, telt elke pinguïn maar één keer mee, en zitten de twee voorspellers elkaar in de weg? (vier korte uitspraken, elk met het getal waar je hem op baseert)</p>
</section>
<section id="resultaten" class="level3">
<h3 class="anchored" data-anchor-id="resultaten">Resultaten</h3>
<p><strong>d)</strong> Toets het model als geheel. (rapporteer <em>R</em>², <em>F</em>(<em>df</em><sub>1</sub>, <em>df</em><sub>2</sub>) en <em>p</em>, en zeg wát je verwerpt)</p>
<p><strong>e)</strong> Rapporteer allebei de voorspellers apart. (per voorspeller b, SE, t, p en het 95%-interval)</p>
<p><strong>f)</strong> Hoeveel voegt elk van de twee <strong>uniek</strong> toe? (twee ΔR²’s met hun F-toets)</p>
<p><strong>g)</strong> Tel de twee losse <em>R</em>²’s bij elkaar op en vergelijk met de <em>R</em>² van het volle model. En tel daarna de twee unieke bijdragen op en vergelijk óók. Wat valt je op aan de twee verschillen? (twee sommen en één getal dat je twee keer tegenkomt)</p>
<p><strong>h)</strong> Reken allebei de partiële correlaties uit met het residuen-recept. Vergelijk ze met de gewone correlaties. (vier getallen)</p>
<p><strong>i)</strong> Hier zit een valkuil, en hij is de moeite waard. Kwadrateer de partiële correlatie van de snavellengte en vergelijk met de unieke bijdrage die je bij f) uitrekende. Waarom lopen die twee zo ver uiteen, terwijl ze bij een vluchtige blik hetzelfde lijken te meten? (twee getallen, en twee zinnen)</p>
<p><strong>j)</strong> Schrijf de resultaten-alinea uit, in rapportagevorm, met alle drie de lagen erin. (hele zinnen, verleden tijd, symbolen cursief)</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Je hebt de aannames bij c) al nagelopen — dus nu de vraag die erachteraan hoort: stel dat de spreiding van de residuen duidelijk ongelijk was geweest, welke van je antwoorden hierboven doe je dan over, en welke mogen blijven staan?</p>
</section>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="methode-en-data-analyse-1" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse-1">Methode en data-analyse</h3>
<p><strong>a)</strong> Bijvoorbeeld: <em>“Bij 342 pinguïns van drie soorten onderzochten we of de vinlengte samenhangt met de twee snavelmaten. We voorspelden de vinlengte met een meervoudige regressie uit de snavellengte en de snaveldiepte samen, en bepaalden per voorspeller de unieke bijdrage aan de verklaarde variantie.”</em> Geen enkel getal uit de uitkomsten — dat is de toets waaraan je ziet of de scheiding echt is.</p>
<p><strong>b)</strong> <strong>342</strong> van de <strong>342</strong> rijen in het bestand zijn compleet op alle drie de maten; er valt er geen weg. Dat doet ertoe omdat je bij f) modellen van elkaar aftrekt, en twee modellen die op verschillende pinguïns draaien mag je niet van elkaar aftrekken. Was er wél iets weggevallen, dan had je alle modellen op dezelfde volledige rijen moeten draaien.</p>
<p><strong>c)</strong> De residuen liggen symmetrisch: gemiddelde min mediaan is 0.005 standaardafwijking, dus praktisch nul. De spreiding is over het bereik ongeveer gelijk: bij de laagste helft van de voorspelde waarden is de standaardafwijking van de residuen 8.24 mm, bij de hoogste helft 8.96 mm — een verhouding van 0.92, geen trechter. Elke pinguïn is één keer gemeten, dus de waarnemingen zijn onafhankelijk. En de twee voorspellers overlappen nauwelijks, <em>r</em> = −.235, dus ze zitten elkaar niet in de weg bij het schatten.</p>
</section>
<section id="resultaten-1" class="level3">
<h3 class="anchored" data-anchor-id="resultaten-1">Resultaten</h3>
<p><strong>d)</strong> <em>R</em>² = .63, <em>F</em>(2, 339) = 283.63, <em>p</em> &lt; .001. Wat je verwerpt is de nulhypothese dat dit model — de twee snavelmaten samen — niets van de verschillen in vinlengte verklaart.</p>
<p><strong>e)</strong> Snavellengte: <em>b</em> = 1.42 mm vin per mm snavel, <em>SE</em> = 0.09, <em>t</em>(339) = 16.07, <em>p</em> &lt; .001, 95% CI [1.24, 1.59]. Snaveldiepte: <em>b</em> = −3.24, <em>SE</em> = 0.24, <em>t</em>(339) = −13.31, <em>p</em> &lt; .001, 95% CI [−3.72, −2.76]. Allebei ruimschoots significant, en geen van beide intervallen bevat nul.</p>
<p><strong>f)</strong> Snavellengte uniek: Δ<em>R</em>² = .285, <em>F</em>(1, 339) = 258.33, <em>p</em> &lt; .001. Snaveldiepte uniek: Δ<em>R</em>² = .195, <em>F</em>(1, 339) = 177.05, <em>p</em> &lt; .001. Anders dan bij de snavellengte naast de vinlengte in 8.1 houden ze hier allebei fors iets eigens over.</p>
<p><strong>g)</strong> Naïef opgeteld: .431 + .341 = <strong>.771</strong>, terwijl het volle model op <strong>.626</strong> uitkomt. <em>(Tel je de gedrukte cijfers op, dan krijg je .772. Reken met de onafgeronde waarden — .4306 en .3409 — en het is .771. Dat verschil van één duizendste is afronding en niets anders.)</em> Je telde <strong>.146</strong> te veel. Unieke bijdragen opgeteld: .285 + .195 = <strong>.480</strong>, tegen diezelfde .626. Nu kom je <strong>.146</strong> te kort. Dat is twee keer hetzelfde getal, en dat is geen toeval: het gedeelde stuk wordt in de eerste optelling dubbel geteld en in de tweede helemaal niet.</p>
<p><strong>h)</strong> <em>r</em>(vinlengte, snavellengte) = .656 gewoon, en <strong>.658</strong> partieel. <em>r</em>(vinlengte, snaveldiepte) = −.584 gewoon, en <strong>−.586</strong> partieel. Ze bewegen vrijwel niet.</p>
<p><strong>i)</strong> .658² = <strong>.43</strong>, terwijl de unieke bijdrage bij f) <strong>.285</strong> was. Wie de partiële correlatie kwadrateert, concludeert dus dat de snavellengte niets verloor — terwijl er .146 gedeeld bleek. De oorzaak staat in het kader hierboven, maar nu vergeleken met de <strong>gewone</strong> correlatie in plaats van met elkaar. Ga je van de gewone naar de <strong>partiële</strong>, dan haal je de snaveldiepte uit allebei de kolommen weg: er valt boven én onder de streep iets af, en de verhouding blijft dus vrijwel staan. Ga je van de gewone naar de <strong>semi-partiële</strong>, dan haal je hem alleen uit de voorspeller: er valt alleen bovenaan iets af, en het getal zakt — van .656 naar <strong>.534</strong>. En de sémi-partiële is het die je kwadrateert: .534² = .285, precies de Δ<em>R</em>² uit f).</p>
<p>Die .534 maak je met hetzelfde recept als in het kader, maar dan met het gewicht vervangen door de vinlengte: <code>cor(peng$vinlengte, resid(lm(snavellengte ~ snaveldiepte, data = peng)))</code>. Dit is een mooi geval om te onthouden, want hier lijkt er niets aan de hand en is er tóch bijna een kwart van de verklaarde ruimte gedeeld.</p>
<p><strong>j)</strong> Bijvoorbeeld:</p>
<blockquote class="blockquote">
<p>Het model als geheel verklaarde een groot deel van de verschillen in vinlengte, <em>R</em>² = .63, <em>F</em>(2, 339) = 283.63, <em>p</em> &lt; .001. Bij gelijke snaveldiepte ging elke millimeter langere snavel samen met ruim anderhalve millimeter langere vin, <em>b</em> = 1.42, <em>SE</em> = 0.09, <em>t</em>(339) = 16.07, <em>p</em> &lt; .001, 95% CI [1.24, 1.59]; bij gelijke snavellengte ging elke millimeter diepere snavel samen met ruim drie millimeter kórtere vin, <em>b</em> = −3.24, <em>SE</em> = 0.24, <em>t</em>(339) = −13.31, <em>p</em> &lt; .001, 95% CI [−3.72, −2.76]. Beide voorspellers droegen ook uniek bij: de snavellengte Δ<em>R</em>² = .29, <em>F</em>(1, 339) = 258.33, <em>p</em> &lt; .001, en de snaveldiepte Δ<em>R</em>² = .20, <em>F</em>(1, 339) = 177.05, <em>p</em> &lt; .001.</p>
</blockquote>
<p><strong>Z)</strong> Was de spreiding van de residuen duidelijk ongelijk geweest, dan <strong>blijven staan</strong>: de hellingen bij e) en de Δ<em>R</em>²’s bij f) en g). Dat zijn beschrijvingen van deze 342 pinguïns, en daar verandert geen aanname iets aan. <strong>Doe je over</strong>: alle standaardfouten, en daarmee elke <em>t</em>, elke <em>p</em>, elk interval bij e) en elke <em>F</em> bij d) en f). Die rusten allemaal op één gedeelde restspreiding, en die is er dan niet. De conclusie bij j) gaat dus mee terug — je weet dan nog steeds hoe groot het verband is, maar niet meer hoe zeker.</p>
</section>
</div>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-een-weggerekend-verband-op" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-een-weggerekend-verband-op">Schrijf een weggerekend verband op</h2>
<p><span class="begrippen">partiële correlatie in een zin · gecontroleerd voor · gedeelde variantie</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een partiële correlatie schrijf je op als een gewone correlatie, met één zinsdeel erbij: <strong>wát je hebt vastgehouden</strong>. Dat zinsdeel is niet optioneel. Zonder dat weet je lezer niet welk getal hij voor zich heeft, en de twee kunnen ver uiteen liggen — in dit hoofdstuk .60 tegenover .06.</p>
<blockquote class="blockquote">
<p>De partiële correlatie tussen het gewicht en de snavellengte, gecontroleerd voor de vinlengte, was <em>r</em> = .06, tegen een gewone correlatie van <em>r</em> = .60.</p>
</blockquote>
<p>Drie dingen zitten erin, en alle drie met opzet. Er staat <strong>wat</strong> er gecontroleerd is, niet alleen dát er iets gecontroleerd is. De gewone correlatie staat ernaast, want zonder die vergelijking is .06 alleen maar een klein getal en niet een verhaal over waar .60 gebleven is. En de <em>r</em> leunt schuin terwijl de woorden rechtop staan, zoals bij elk symbool dat zelf een waarde draagt.</p>
<p><strong>Eén ding dat je hier níét moet doen: het gedeelde stuk aan iemand toeschrijven.</strong> Je mag opschrijven dat twee voorspellers samen <em>R</em>² = .471 halen en dat elk er respectievelijk .248 en .117 uniek aan bijdraagt. Je mag er niet bij zeggen dat de overige .106 “van allebei een beetje” is, of hem netjes in tweeën delen. Die .106 is verschil in gewicht dat de twee samen verklaren en dat aan geen van beide alleen toe te schrijven is — dat is geen tekortkoming van je rapportage maar een eigenschap van de data. Schrijf hem dus op als wat hij is: <strong>gedeeld</strong>.</p>
<p>Dat is meteen waarom de vraag <em>“welke van mijn voorspellers is het belangrijkst?”</em> zoveel lastiger is dan hij klinkt. Op de unieke bijdrage kun je ze rangschikken, en dat doen onderzoekers ook — maar wat gedeeld is doet in die rangschikking niet mee, en dat kan een flink stuk zijn.</p>
</div>
</div>
<div class="boekvorm" data-w="W8">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: de derde speler die zich vermomde als een stuk van het snavel-effect, de partiële correlatie die vangt wat er overblijft als je hem wegrekent, en het gedeelde stuk dat van geen van beide voorspellers is.</p>
<p>In het boek: <strong>W8 — Meer dan één verschil</strong></p>
<p><em>Daar draait het niet om méér knoppen, maar om dezelfde vraag als bij die correlatie-wolk: wat blijft er van een verband over als je vasthoudt wie er nog meer meepraat?</em></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_meervoudige_regressie.html" class="pagination-link" aria-label="Oefening 8.1 · Meervoudige regressie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 8.1 · Meervoudige regressie</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_dummy_regressie.html" class="pagination-link" aria-label="Oefening 9.1 · Dummy-codering">
        <span class="nav-page-text">Oefening 9.1 · Dummy-codering</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>