<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 10.2 · Als de moderator een getal is – JASP-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_mediatie.html" rel="next">
<link href="../20_blokken/blok_interactie.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">H10 · Verschil in verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie_continu.html">Oefening 10.2 · Als de moderator een getal is</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">JASP-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JASP-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_confounding_partiele_correlatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.2 · Confounding en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · Eenweg ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in JASP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Vierde beweging · Verschil onthechten</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie.html">H10 · Verschil in verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_interactie_continu.html">Oefening 10.2 · Als de moderator een getal is</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 10.2 · Als de moderator een getal is</h1>
<p class="subtitle lead">Interactie tussen twee continue voorspellers · <em>continuous moderation</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#de-moderator-heeft-geen-hokjes-meer" id="toc-de-moderator-heeft-geen-hokjes-meer">De moderator heeft geen hokjes meer</a></li>
  <li><a href="#waar-de-nul-woont-en-waarom-dat-nu-wél-uitmaakt" id="toc-waar-de-nul-woont-en-waarom-dat-nu-wél-uitmaakt">Waar de nul woont, en waarom dat nu wél uitmaakt</a></li>
  <li><a href="#de-waaier-bij-de-pinguïns" id="toc-de-waaier-bij-de-pinguïns">De waaier bij de pinguïns</a></li>
  <li><a href="#kies-je-eigen-hokjes-de-simple-slopes" id="toc-kies-je-eigen-hokjes-de-simple-slopes">Kies je eigen hokjes: de simple slopes</a></li>
  <li><a href="#waarom-centreren-hier-geen-gemak-meer-is" id="toc-waarom-centreren-hier-geen-gemak-meer-is">Waarom centreren hier geen gemak meer is</a></li>
  <li><a href="#duizend-werelden-waarin-de-snavel-niets-modereert" id="toc-duizend-werelden-waarin-de-snavel-niets-modereert">Duizend werelden waarin de snavel niets modereert</a></li>
  <li><a href="#een-vlak-dat-kantelt" id="toc-een-vlak-dat-kantelt">Een vlak dat kantelt</a></li>
  <li><a href="#een-tweede-moderator-die-de-waaier-de-andere-kant-op-zet" id="toc-een-tweede-moderator-die-de-waaier-de-andere-kant-op-zet">Een tweede moderator, die de waaier de andere kant op zet</a></li>
  <li><a href="#van-getal-naar-groep-en-weer-terug" id="toc-van-getal-naar-groep-en-weer-terug">Van getal naar groep — en weer terug</a></li>
  <li><a href="#schrijf-het-op-als-een-onderzoeker" id="toc-schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="de-moderator-heeft-geen-hokjes-meer" class="level2">
<h2 class="anchored" data-anchor-id="de-moderator-heeft-geen-hokjes-meer">De moderator heeft geen hokjes meer</h2>
<p><span class="begrippen">continue moderator</span></p>
<p>In oefening 10.1 kon je het altijd tekenen. Twee groepen, twee lijnen. Drie soorten, drie lijnen. Sekse naast soort, zes hokjes met een punt in elk hokje. Wat de moderator ook was, je kon hem aanwijzen en de hellingen ervan aflezen.</p>
<p>Probeer dat nu eens met de <strong>snavellengte</strong>.</p>
<p>Dezelfde 342 pinguïns.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Je wilt weten of het effect van vinlengte op gewicht afhangt van hoe lang de snavel is. Redelijke vraag — een pinguïn met een lange snavel is misschien een ander soort dier dan een met een korte, en bij een ander dier telt een millimeter vin misschien anders.</p>
<p>Maar teken het maar eens. Snavellengte heeft geen twee waarden en geen drie; hij loopt van 32.1 tot 59.6 millimeter, en in deze 342 beesten komen er 164 verschillende waarden voor. Eén lijn per snavellengte worden er dan 164. Er is geen hokje om in te gaan staan.</p>
<p>En tóch is er iets. Knip de pinguïns straks maar eens grof in tweeën bij de middelste snavellengte — dat doen we verderop echt — dan ligt de helling van gewicht op vinlengte bij de korte-snavelhelft rond de <strong>37</strong> en bij de lange-snavelhelft rond de <strong>57</strong>. Dus of het verband tussen vinlengte en gewicht meebeweegt met de snavellengte, of het toeval van deze 342 beesten is dat.</p>
<p>Deze oefening gaat over die twee vragen tegelijk: hoe je zoiets tóétst als er geen groepen zijn, en — lastiger — hoe je het <em>opschrijft</em> als er geen groepen zijn om je hellingen aan op te hangen.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="waar-de-nul-woont-en-waarom-dat-nu-wél-uitmaakt" class="level2">
<h2 class="anchored" data-anchor-id="waar-de-nul-woont-en-waarom-dat-nu-wél-uitmaakt">Waar de nul woont, en waarom dat nu wél uitmaakt</h2>
<p><span class="begrippen">centreren · intercept</span></p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Maak eerst een productkolom. Klik in het databad op de <strong>+</strong> rechts van de laatste kolom, noem hem <code>gladXkaraat</code> en typ in de <strong>R</strong>-modus:</p>
<pre><code>gladheid * karaat</code></pre>
<p>Draai dan <strong>Regression → Linear Regression</strong>: <code>glans</code> als <strong>Dependent</strong>, en <code>gladheid</code>, <code>karaat</code> én <code>gladXkaraat</code> als <strong>Covariates</strong>.</p>
<pre><code>gladheid       b = 10.00
karaat         b =  4.70
gladXkaraat    b = -1.21   p = .80</code></pre>
</div>
</div>
<p>En hier moet ik meteen eerlijk zijn: <strong>op twaalf steentjes valt over deze interactie niets te zeggen.</strong> <em>p</em> = .80, en dat blijft zo hoe je ook kijkt. Een interactie tussen twee getallen is de hongerigste term die er in een model kan zitten — hij vraagt om veel meer waarnemingen dan een hoofdeffect, want hij moet een verschil in een verschil zichtbaar maken. Twaalf steentjes zijn genoeg om een lijn te trekken en te krap om een waaier te zien. Dat is geen tegenvaller maar een les die je meeneemt.</p>
<p>Kijk wél naar dat eerste getal, want dáár leren de diamantjes je iets wat de pinguïns straks nodig hebben. <code>gladheid</code> staat op <strong>10.00</strong>. Maar in oefening 10.1 stond de helling van gladheid op 6.14, en in de meervoudige regressie weer op iets anders. Hoe kan dat?</p>
<p>Omdat een coëfficiënt in een model met een interactie altijd de helling is <strong>bij nul van de ander</strong>. Die 10.00 is de helling van glans op gladheid bij een steentje van <strong>nul karaat</strong>. En een steentje van nul karaat bestaat niet — het gemiddelde steentje weegt 1.6 karaat. Je leest dus een helling af op een adres waar niemand woont.</p>
<p>De reparatie is één aftrekking:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · centreren is aftrekken · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · centreren is aftrekken · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Maak drie nieuwe kolommen met <strong>Compute Column</strong>, in de <strong>R</strong>-modus:</p>
<pre><code>glad_c        -&gt;   gladheid - mean(gladheid)     # gemiddelde gladheid = 5.0
kar_c         -&gt;   karaat   - mean(karaat)       # gemiddelde karaat   = 1.6
gladXkar_c    -&gt;   glad_c * kar_c</code></pre>
<p>Let op de derde: het product maak je van de <strong>gecentreerde</strong> kolommen, niet van de ruwe. Draai dan dezelfde <strong>Linear Regression</strong> met <code>glad_c</code>, <code>kar_c</code> en <code>gladXkar_c</code>.</p>
<pre><code>glad_c         b = 8.06    &lt;- helling bij GEMIDDELDE karaat
gladXkar_c     b = -1.21   &lt;- exact hetzelfde als hierboven</code></pre>
</div>
</div>
<p>Twee dingen om vast te houden. <strong>De interactie verandert niet</strong> — hij was −1.21 en hij blijft −1.21. Centreren verschuift alleen waar de nul ligt; het verzet het model niet. <strong>De helling van gladheid verandert wél</strong>, van 10.00 naar 8.06, en dat komt doordat je hem nu op een ander adres afleest: niet bij nul karaat maar bij een gemiddeld steentje.</p>
<p>Ben zegt het in de les zo:</p>
<blockquote class="blockquote">
<p>Nul is hier gemiddeld. Als je naar een moderatieregressie kijkt, dan staat het effect van die X in de coëfficiëntentabel altijd bij een nulwaarde van de moderator. De vraag is dus: wat betekent nul?</p>
</blockquote>
<p>Onthoud die vraag. Vanaf hier is het de vraag die je bij elke tabel stelt.</p>
</section>
<section id="de-waaier-bij-de-pinguïns" class="level2">
<h2 class="anchored" data-anchor-id="de-waaier-bij-de-pinguïns">De waaier bij de pinguïns</h2>
<p><span class="begrippen">gecentreerde voorspellers · interactieterm</span></p>
<p><strong>Nu jij</strong> — dezelfde beesten als in 10.1, en nu twee getallen als voorspellers. Centreer ze allebei voordat je het model draait.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · drie kolommen erbij rekenen · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · drie kolommen erbij rekenen · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Open <code>penguins.csv</code> en maak drie kolommen met <strong>Compute Column</strong> (<strong>R</strong>-modus):</p>
<pre><code>vin_c        -&gt;   vinlengte    - mean(vinlengte)      # gemiddelde: 200.92 mm
snav_c       -&gt;   snavellengte - mean(snavellengte)   # gemiddelde:  43.92 mm
vinXsnav     -&gt;   vin_c * snav_c</code></pre>
<p>Zet ze alle drie op <strong>Scale</strong>. Ter controle: het gemiddelde van <code>vin_c</code> en van <code>snav_c</code> moet nul zijn — kijk het na met <strong>Descriptives</strong>.</p>
</div>
</div>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · trek eraan · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · trek eraan · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regression → Linear Regression</strong>: <code>gewicht</code> als <strong>Dependent</strong>, en <code>vin_c</code>, <code>snav_c</code> én <code>vinXsnav</code> als <strong>Covariates</strong>. Vink onder <strong>Statistics</strong> de optie <strong>Estimates</strong> aan.</p>
<pre><code>(Intercept)   b = 4141.49        &lt;- gewicht van een dóórsnee pinguïn
vin_c         b =   45.39        &lt;- helling bij GEMIDDELDE snavellengte
snav_c        b =   11.82   p = .027
vinXsnav      b =    1.20   p &lt; .001
R²            = 0.769</code></pre>
</div>
</div>
<p>Lees die tabel nu met de vraag van hierboven in je hoofd — <em>wat betekent nul?</em></p>
<ul>
<li>De intercept, <strong>4141.49</strong> gram, is het voorspelde gewicht van een pinguïn met een gemiddelde vin én een gemiddelde snavel. Dat is een pinguïn die kán bestaan. Vergelijk dat met oefening 3.2, waar de intercept op −5780.83 gram stond: een pinguïn met een vin van nul millimeter, die bijna zes kilo negatief weegt. Het adres is nu bewoond.</li>
<li><strong>45.39</strong> is de helling van gewicht op vinlengte bij een pinguïn met een gemiddelde snavel — niet bij álle pinguïns, bij een gemiddelde. En let op: in oefening 3.2 stond hier 49.69. Dat verschil komt niet door het centreren maar doordat de snavellengte nu <strong>in het model zit</strong>: 45.39 is de helling van gewicht op vinlengte bij pinguïns die even lang van snavel zijn. Precies de verschuiving die je in oefening 8.1 bij de meervoudige regressie zag.</li>
<li>En <strong>1.20</strong> is de interactie: per millimeter extra snavellengte komt er 1.20 gram per millimeter bij de helling van de vin bij.</li>
</ul>
<p>Dat laatste getal is klein en je zou eroverheen kunnen lezen. Maar het is een helling van een helling, en dat is een ander soort getal. Reken maar mee.</p>
</section>
<section id="kies-je-eigen-hokjes-de-simple-slopes" class="level2">
<h2 class="anchored" data-anchor-id="kies-je-eigen-hokjes-de-simple-slopes">Kies je eigen hokjes: de simple slopes</h2>
<p><span class="begrippen">simple slopes · min één SD, gemiddelde, plus één SD</span></p>
<p>Er zijn geen groepen, dus de hellingen komen er niet vanzelf uit. Je moet ze <strong>zelf gaan halen</strong> — en dat betekent: je kiest waarden van de moderator waarop je de helling wilt aflezen. De afspraak die je overal tegenkomt is: één standaardafwijking eronder, het gemiddelde, en één standaardafwijking erboven.</p>
<p>De standaardafwijking van de snavellengte is <strong>5.46</strong> millimeter (vraag hem op met <strong>Descriptives</strong>). Dus je leest de helling af bij een snavel van 38.46, van 43.92 en van 49.38 millimeter — kort, gemiddeld, lang.</p>
<p>En dan is het optellen, net als bij de dummy in 10.1:</p>
<blockquote class="blockquote">
<p>45.39 − 1.20 × 5.46 = <strong>38.84</strong> bij een korte snavel 45.39 = <strong>45.39</strong> bij een gemiddelde snavel 45.39 + 1.20 × 5.46 = <strong>51.94</strong> bij een lange snavel</p>
</blockquote>
<p><strong>38.84 · 45.39 · 51.94.</strong> Bij een pinguïn met een korte snavel weegt elke millimeter vin bijna negenendertig gram; bij een lange snavel bijna tweeënvijftig. Dertien gram per millimeter verschil tussen de buitenste twee. Hoe langer de snavel, hoe zwaarder elke millimeter vin telt.</p>
<p>En dat zijn geen echte groepen — er staat nergens een pinguïn met het bordje “lange snavel” om zijn nek. Het zijn drie plekken op een glijdende schaal, door jou gekozen omdat je ergens moest gaan staan. Kies je andere waarden, dan krijg je andere hellingen; het model is hetzelfde gebleven.</p>
<p>Wil je zien dat het niet uit de lucht komt vallen, knip de pinguïns dan even grofweg in tweeën bij de middelste snavellengte en trek twee losse lijnen:</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · ter controle, grof in tweeën geknipt · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · ter controle, grof in tweeën geknipt · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>De mediaan van <code>snavellengte</code> vraag je op met <strong>Descriptives</strong> (vink <strong>Median</strong> aan). Zet dan het <strong>trechtertje</strong> op <code>snavellengte &lt; 44.45</code> en draai een gewone <strong>Linear Regression</strong> van <code>gewicht</code> op <code>vinlengte</code>: <strong>37.17</strong>. Draai het filter om naar <code>snavellengte &gt;= 44.45</code> en je vindt <strong>57.27</strong>. Zet het filter daarna weer uit.</p>
</div>
</div>
<p>37.17 tegen 57.27 — dezelfde richting, en forser, want een mediaan-knip zet de uitersten tegenover elkaar in plaats van één standaardafwijking. Doe dat níét als je het echt gaat rapporteren: je gooit de helft van de informatie weg en je verzint groepen die niet bestaan. Als controle bij het leren is het prima.</p>
</section>
<section id="waarom-centreren-hier-geen-gemak-meer-is" class="level2">
<h2 class="anchored" data-anchor-id="waarom-centreren-hier-geen-gemak-meer-is">Waarom centreren hier geen gemak meer is</h2>
<p><span class="begrippen">intercept · onmogelijke nul</span></p>
<p>In oefening 3.2 was centreren een leuk extraatje. Hier is het dat niet meer, en dat kun je in één run zien. Draai hetzelfde model nog eens, nu met de <strong>ruwe</strong> kolommen: maak <code>vinXsnav_ruw</code> als <code>vinlengte * snavellengte</code>, en zet <code>vinlengte</code>, <code>snavellengte</code> en die nieuwe kolom in de regressie.</p>
<pre><code>vinlengte        b =   -7.31   p = .63
snavellengte     b = -229.24   p &lt; .001
vinXsnav_ruw     b =    1.20   p &lt; .001   &lt;- exact hetzelfde</code></pre>
<p>Kijk naar de eerste regel. De helling van gewicht op vinlengte is nu <strong>−7.31</strong>. Negatief. Alsof een langere vin een pinguïn <em>lichter</em> maakt.</p>
<p>Dat is geen rekenfout en het spreekt oefening 3.2 niet tegen. Het is de helling van gewicht op vinlengte <strong>bij een snavellengte van nul millimeter</strong> — bij een pinguïn zonder snavel. Zo’n dier bestaat niet, de data bevat er geen enkele in de buurt van, en het model verzint daar dus maar wat. Je leest een echt getal af op een onmogelijk adres.</p>
<p>De interactie blijft ondertussen exact 1.20, gecentreerd of niet. Dát is het patroon: <strong>centreren raakt de hoofdeffecten en laat de interactie met rust.</strong> En precies daarom kun je het niet overslaan — het getal dat je wél mag aflezen verandert van betekenis, en niets in de uitvoer waarschuwt je.</p>
<div class="kicker">
<p>schud het</p>
</div>
</section>
<section id="duizend-werelden-waarin-de-snavel-niets-modereert" class="level2">
<h2 class="anchored" data-anchor-id="duizend-werelden-waarin-de-snavel-niets-modereert">Duizend werelden waarin de snavel niets modereert</h2>
<p><span class="begrippen">interactieterm schudden · dansen rond nul</span></p>
<p>Is die 1.20 echt, of kan het toeval hem namaken? Je zou dat willen uitproberen door vals te spelen. Deze keer husselen we de <strong>snavellengtes</strong> los: elke pinguïn houdt z’n eigen vinlengte en z’n eigen gewicht, maar krijgt de snavel van een willekeurige andere pinguïn toebedeeld.</p>
<p>Dat husselen <strong>koppelt de snavellengte los van het vin-gewicht-verband</strong>. Je haalt met eigen handen weg dat een bepaalde snavellengte bij een bepaalde helling hoort. In zo’n losgekoppelde wereld kán de snavellengte niets meer modereren — de ware interactie is er nul. Wat er dan tóch uitkomt, is puur toeval.</p>
<p><strong>En hier moet ik eerlijk zijn: dat schudden is geen knop in JASP.</strong> JASP rekent één keurige uitkomst uit; het door elkaar husselen en duizend keer opnieuw kijken is <em>code</em>-werk. Voor deze interactie is er (nog) geen browser-speeltje — dus voor de schud-ervaring <strong>draai je het R-broertje</strong>, waar het husselen een paar regels code is. Dat is geen gemis van jou of van JASP: het boek doet het bewust zo, de simulatie leeft in de code en in de speeltjes.</p>
<p>Wat je daar ziet: <strong>duizend werelden waarin de snavellengte de vin-gewicht-relatie niet modereert.</strong> Het gemiddelde van die duizend is −0.002 — zo goed als nul, precies zoals het hoort, want in elke geschudde wereld ís de waarheid nul. En tóch landt geen enkele wereld precies op nul: ze dansen eromheen, met een spreiding van 0.27, en de wildste haalde 0.94.</p>
<p>En dan de echte 1.1998, buiten het hele bergje. Geen van de duizend kwam er in de buurt. De echte pinguïns weten iets wat de geschudde niet weten: bij een langere snavel telt een millimeter vin écht zwaarder mee.</p>
<p>Kijk voor de aardigheid ook eens wat er in zo’n geschudde wereld met de drie simple slopes gebeurt. Die komen alle drie rond de 49.6 uit te liggen — de gewone helling van gewicht op vinlengte over alle pinguïns, zonder waaier. Als er niets te moduleren valt, valt de waaier dicht tot één lijn.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="een-vlak-dat-kantelt" class="level2">
<h2 class="anchored" data-anchor-id="een-vlak-dat-kantelt">Een vlak dat kantelt</h2>
<p><span class="begrippen">continue moderatie · symmetrie van de interactie</span></p>
<p>Bij een groep als moderator kon je lijnen tekenen. Hier niet, en het is de moeite waard om te weten wat je dan wél voor je moet zien.</p>
<p>Met één voorspeller heb je een <strong>lijn</strong>. Met twee voorspellers en géén interactie heb je een <strong>vlak</strong> — een schuin dak boven de wolk, dat overal even schuin is. De interactie is wat dat dak laat <strong>kantelen</strong>: aan de kant van de lange snavels loopt het steiler op dan aan de kant van de korte. Geen twee lijnen die uiteenwaaieren, maar één oppervlak dat verdraait.</p>
<p>En daar zit iets in verstopt wat makkelijk te missen is. Een interactie is <strong>symmetrisch</strong>. Wij hebben hem gelezen als <em>“hoe langer de snavel, hoe zwaarder elke millimeter vin telt”</em>, maar je mag hem net zo goed omdraaien: <em>“hoe langer de vin, hoe zwaarder elke millimeter snavel telt”</em>. Het is één getal en het staat op één regel; welke van de twee de moderator heet, is jouw keuze en niet die van het model. Bij een groep als moderator voelde dat vanzelfsprekend — soort modereert vinlengte, niet andersom — maar dat kwam alleen doordat een soort geen helling kán hebben. Tussen twee getallen is die asymmetrie weg.</p>
<p>Kies dus bewust. Wat je de moderator noemt, bepaalt welk verhaal je vertelt, en je moet dat verhaal kunnen verdedigen met iets buiten de statistiek om: theorie, of de volgorde waarin de dingen gebeuren.</p>
<p><strong>Wat dit hoofdstuk bij elkaar houdt.</strong> In 10.1 was de moderator een groep en kon je het tekenen; de hellingen rolden uit de tabel omdat elke groep er een had. Hier is de moderator een getal, is er geen enkele groep om een helling van af te lezen, en moet je zélf de plekken kiezen waarop je kijkt. Dat is de hele stap. Alles eromheen — de interactieterm, het product, de vraag of het verschil in verschil groot genoeg is — is hetzelfde gebleven.</p>
<p>En de vraag eronder ook. Ook hier geldt wat Ben over de therapie zei: het gaat er niet om óf vinlengte effect heeft op gewicht, maar <strong>onder welke conditie</strong>, en hoeveel. Alleen is de conditie nu geen hokje meer maar een schaal waarop je zelf een plek moet aanwijzen.</p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="een-tweede-moderator-die-de-waaier-de-andere-kant-op-zet" class="level2">
<h2 class="anchored" data-anchor-id="een-tweede-moderator-die-de-waaier-de-andere-kant-op-zet">Een tweede moderator, die de waaier de andere kant op zet</h2>
<p><span class="begrippen">continue moderatie · negatieve interactie</span></p>
<p>Jouw beurt. Je hebt gezien dat de snavel<strong>lengte</strong> het effect van vinlengte op gewicht versterkt: hoe langer de snavel, hoe zwaarder elke millimeter vin telt. Er staat nog een kolom in het bestand die je niet gebruikt hebt: de snavel<strong>diepte</strong> — hoe hoog de snavel is, van boven naar onder. Dezelfde vraag, dezelfde uitkomst, dezelfde vin-voorspeller, andere moderator.</p>
<p>Zet eerst klaar, en beantwoord daarna de vragen. De laatste heet met opzet <strong>Z)</strong> en niet l): de aannames staan altijd achteraan, en die vreemde letter zegt <em>“en ook, elke keer, deze”</em>.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · zet klaar · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · zet klaar · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Maak twee kolommen met <strong>Compute Column</strong> (<strong>R</strong>-modus):</p>
<pre><code>dp_c      -&gt;   snaveldiepte - mean(snaveldiepte)   # gemiddelde: 17.15 mm
vinXdp    -&gt;   vin_c * dp_c</code></pre>
<p>Draai dan <strong>Regression → Linear Regression</strong>: <code>gewicht</code> als <strong>Dependent Variable</strong>, en <code>vin_c</code>, <code>dp_c</code> én <code>vinXdp</code> als <strong>Covariates</strong>. Vink onder <strong>Statistics</strong> ook <strong>Confidence intervals</strong> aan — die heb je bij e) nodig.</p>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoe diep is een gemiddelde pinguïnsnavel, en hoeveel spreiding zit daarop? Vraag het op met <strong>Descriptives</strong>. (rapporteer <em>M</em> en <em>SD</em>, in millimeters)</p>
<p><strong>b)</strong> Lees de vier getallen uit de tabel af, en zeg bij elk wát het is — dus niet alleen het getal maar ook op welk adres het gemeten is. (vier <em>b</em>’s, elk met één regel uitleg)</p>
<p><strong>c)</strong> Kijk naar het teken van de interactie en zeg in gewone woorden wat er staat, vóórdat je verder rekent. Hij is negatief — wat betekent dat voor de helling van gewicht op vinlengte bij een diepe snavel?</p>
<p><strong>d)</strong> Schrijf de nulhypothese voor de interactie voluit op, in woorden én in symbolen. (één zin, en die ook in symbolen)</p>
<p><strong>e)</strong> Toets de interactie. (rapporteer <em>b</em>, <em>SE</em>, <em>t</em>, <em>p</em> en het 95%-interval)</p>
<p><strong>f)</strong> Op welke drie waarden van de snaveldiepte ga je de helling aflezen, en waarom juist die drie? (drie getallen in millimeters, en één zin)</p>
<p><strong>g)</strong> Reken de drie simple slopes uit, met de hand: de helling van <code>vin_c</code>, plus de interactie keer −1 <em>SD</em>, 0 en +1 <em>SD</em> van de snaveldiepte. Neem álle decimalen mee die je scherm je geeft. (drie hellingen in gram per millimeter)</p>
<p><strong>h)</strong> Hoeveel keer zwaarder telt een millimeter vin bij een ondiepe snavel dan bij een diepe? (één verhouding)</p>
<p><strong>i)</strong> Leg deze waaier naast die van de snavellengte uit dit blok. Wat is er hetzelfde en wat is er tegengesteld? (twee reeksen van drie, en één zin)</p>
<p><strong>j)</strong> Een interactie is symmetrisch. Schrijf jouw bevinding daarom nog een keer op, maar dan met de vinlengte als moderator. (één zin, en hetzelfde getal)</p>
<p><strong>k)</strong> Draai het model nu nog eens <strong>zonder</strong> te centreren: maak met <strong>Compute Column</strong> de kolom <code>vinXdp_ruw</code> als <code>vinlengte * snaveldiepte</code>, en zet <code>vinlengte</code>, <code>snaveldiepte</code> en die nieuwe kolom in de regressie. Welk getal blijft precies gelijk, en welk getal verandert onherkenbaar? (twee getallen, en waarom dat zo is)</p>
<p><strong>l)</strong> In oefening 10.1 bleek de soort een sterke moderator — en de Gentoo’s hebben nu net een opvallend ondiepe snavel. Zou de snaveldiepte hier zelf de moderator kunnen zijn, of staat hij in voor iets anders? Wat zou je moeten doen om die twee uit elkaar te trekken?</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Bij een continue moderator komt er een aanname bij die je bij een groep niet had: je hebt de hellingen afgelezen op drie waarden die je zélf gekozen hebt. Wonen daar pinguïns? Kijk naar het minimum en het maximum in je <strong>Descriptives</strong>-tabel van a). En loop daarna de gewone drie na: liggen de residuen in een egale band, liggen ze symmetrisch, en telt elke pinguïn maar één keer mee? (één bereik en drie uitspraken, elk met het getal waar je hem op baseert)</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <em>M</em> = 17.15 mm, <em>SD</em> = 1.97 mm.</p>
<p><strong>b)</strong> Vier getallen, vier adressen:</p>
<ul>
<li><strong>Intercept 4062.79</strong> — het voorspelde gewicht van een pinguïn met een gemiddelde vin én een gemiddelde snaveldiepte. Een dier dat kán bestaan, want je hebt allebei gecentreerd.</li>
<li><strong><code>vin_c</code> 48.63</strong> — de helling van gewicht op vinlengte bij een pinguïn met een gemiddeld diepe snavel. Niet bij álle pinguïns; bij een gemiddelde.</li>
<li><strong><code>dp_c</code> 44.64</strong> — de helling van gewicht op snaveldiepte bij een pinguïn met een gemiddelde vin.</li>
<li><strong>Interactie −8.60</strong> — een helling van een helling: per millimeter diepere snavel gaat er 8.60 gram per millimeter <strong>af</strong> van de helling van de vin.</li>
</ul>
<p><strong>c)</strong> Negatief betekent: hoe diéper de snavel, hoe mínder elke millimeter vin meetelt voor het gewicht. Bij de snavellengte was het andersom. De waaier kantelt hier dus de andere kant op.</p>
<p><strong>d)</strong> De nulhypothese: het effect van vinlengte op gewicht hangt niet af van de snaveldiepte. In symbolen: <span class="math inline">\(H_0:\ \beta_3 = 0\)</span> tegen <span class="math inline">\(H_1:\ \beta_3 \neq 0\)</span>, waarin <span class="math inline">\(\beta_3\)</span> het gewicht van de interactieterm in de populatie is. Je mag ook zeggen dat de helling van de vin voor elke snaveldiepte dezelfde is; één van de twee is genoeg. Grieks, want het gaat over de populatie en niet over deze 342.</p>
<p><strong>e)</strong> <em>b</em> = −8.60, <em>SE</em> = 1.34, <em>t</em>(338) = −6.41, <em>p</em> &lt; .001, 95% CI [−11.23, −5.96]. Het interval blijft ruim aan één kant van de nul.</p>
<p><strong>f)</strong> Bij 15.18, 17.15 en 19.13 mm: één standaardafwijking onder het gemiddelde, het gemiddelde zelf, en één erboven. Dat is een afspraak en geen wet — er staat nergens een pinguïn met het bordje “ondiepe snavel” om zijn nek. Je moest ergens gaan staan, en dit is waar iedereen gaat staan.</p>
<p><strong>g)</strong> <strong>65.61 · 48.63 · 31.66</strong> gram per millimeter. Kwam jij op 65.57 en 31.69 uit? Dan heb je met de afgeronde 48.63, 8.60 en 1.97 gerekend — die paar honderdsten zijn het afronden, niet jij. Met één decimaal meer (48.635, −8.596 en 1.975) land je op 65.61 en 31.66.</p>
<p><strong>h)</strong> 65.61 / 31.66 = <strong>2.07</strong> keer. Bij een ondiepe snavel telt een millimeter vin dus ruim tweemaal zo zwaar als bij een diepe.</p>
<p><strong>i)</strong> Hetzelfde: allebei de moderatoren zijn een getal, allebei op precies dezelfde 342 pinguïns, met dezelfde uitkomstmaat en dezelfde voorspeller. Tegengesteld: bij de snavellengte loopt de reeks omhoog (38.84 → 45.39 → 51.94), hier omlaag (65.61 → 48.63 → 31.66). Twee moderatoren die de waaier de tegengestelde kant op kantelen.</p>
<p><strong>j)</strong> <em>“Per millimeter langere vin gaat er 8.60 gram per millimeter af van de helling van de snaveldiepte.”</em> Precies hetzelfde getal, precies dezelfde regel in de tabel — alleen jouw verhaal is omgedraaid. Welke van de twee je de moderator noemt, is jouw keuze en niet die van het model.</p>
<p><strong>k)</strong> <strong>Gelijk blijft de interactie: −8.60</strong>, tot op de decimaal. <strong>Onherkenbaar verandert <code>vinlengte</code>: van 48.63 naar 196.07.</strong> Dat komt doordat je hem nu afleest bij een snaveldiepte van nul millimeter — bij een pinguïn zónder snavel. Zo’n dier bestaat niet, de data bevat er geen enkele in de buurt van, en het model verzint daar maar wat. Dat is het patroon van dit blok: centreren verzet alleen waar de nul ligt, dus het raakt de hoofdeffecten en laat de interactie met rust.</p>
<p><strong>l)</strong> Je weet het op dit punt nog niet, en dat is het eerlijke antwoord. De Gentoo’s hebben gemiddeld een snaveldiepte van 14.98 mm tegen 18.37 bij de rest, dus “ondiepe snavel” en “Gentoo” zijn bijna hetzelfde bericht. Om ze uit elkaar te trekken moet je één van de twee vasthouden: draai de interactie <strong>binnen</strong> één soort, want daar valt aan de soort niets meer te variëren. Dat doe je in de Eindopdracht hieronder, bij k). Dit is de vraag uit oefening 8.2 in een nieuw jasje: een verband dat verdwijnt zodra je een derde variabele in het model zet die met allebei samenhangt.</p>
<p><strong>Z)</strong> Eerst de nieuwe aanname, want die is de belangrijkste. De snaveldiepte loopt in deze data van <strong>13.1 tot 21.5 mm</strong>, en je leest af op 15.18, 17.15 en 19.13 — alle drie ruim binnen dat bereik. Er zitten zelfs 23 pinguïns binnen een kwart millimeter van je onderste afleespunt en 29 binnen een kwart millimeter van je bovenste. Je leest je hellingen dus af op adressen waar écht dieren wonen. Was een van de drie buiten het bereik gevallen, dan had je een helling gerapporteerd voor een pinguïn die niet bestaat — precies de fout die de ongecentreerde 196.07 bij k) maakt.</p>
<p>De gewone drie houden ook stand; de residu-getallen hierna zijn in het R-broertje nagemeten, want jouw scherm zet ze niet zelf op een rij. De residuen liggen in een egale band: bij de lage helft van de voorspelde waarden is hun standaardafwijking 359.85 gram, bij de hoge helft 381.21 — een verhouding van 1.06, geen trechter. Ze liggen bijna symmetrisch (scheefheid 0.37). En elke pinguïn is één keer gewogen, dus de waarnemingen zijn onafhankelijk.</p>
<p>Eén ding om op te merken en niet af te doen als niets: vinlengte en snaveldiepte hangen onderling samen, <em>r</em> = −.58. Dat is genoeg om de standaardfouten wat op te blazen, maar niet genoeg om het model onbruikbaar te maken.</p>
<p>De weg terug, voor als de residuen wél getrechterd hadden:</p>
<ul>
<li><strong>Blijft staan:</strong> de vier <em>b</em>’s bij b) en de drie simple slopes bij g). Dat zijn beschrijvingen van deze 342 pinguïns.</li>
<li><strong>Doe je over:</strong> de <em>SE</em>, de <em>t</em>, de <em>p</em> en het interval bij e). Die rusten alle vier op één gedeelde restspreiding, en die is er dan niet.</li>
</ul>
</div>
</div>
</div>
<div class="kicker">
<p>eindopdracht</p>
</div>
</section>
<section id="van-getal-naar-groep-en-weer-terug" class="level2">
<h2 class="anchored" data-anchor-id="van-getal-naar-groep-en-weer-terug">Van getal naar groep — en weer terug</h2>
<p><span class="begrippen">dummy · simple slopes · modelvergelijking · <em>R</em>²</span></p>
<p>De afsluiter van het hele hoofdstuk. In de vorige oefening was de moderator een groep en rolden de hellingen uit de tabel; in deze oefening was hij een getal en moest je zelf kiezen waar je ging staan. Die twee hebben elkaar nog niet ontmoet. Dat gaan we nu regelen, op dezelfde 342 pinguïns en met dezelfde vraag — hangt het effect van vinlengte op gewicht af van de snavellengte? Want een getal kun je in groepen knippen, en een groep kun je soms als getal meten. Deze oefening zei dat dat eerste zonde is. Dat gaan we niet geloven maar narekenen. En let op de verrassing die eraan zit te komen.</p>
<p>Een moderator met maar twee waarden is de meest simpele situatie, want dan kun je weer in twee groepen denken. Wat altijd fijn is. Gun jezelf dat plezier — en kijk daarna wat het kost.</p>
<p>En let op de vorm: een artikel valt in <strong>twee gelabelde stukken</strong>, en die volgorde is niet dezelfde als de volgorde waarin je het leerde. Toen mocht de aannamecontrole achteraf, want je moest eerst zien wát je nou eigenlijk controleerde. Nu je het opschrijft voor een lezer gaat hij vóórop, want die wil weten of hij je getallen mag geloven vóórdat hij ze leest.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · zet de vier gedaanten klaar · JASP 0.98.1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · zet de vier gedaanten klaar · JASP 0.98.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>De kolommen maak je met <strong>Compute Column</strong> (<strong>R</strong>-modus); de modellen ken je al.</p>
<ol type="1">
<li><p><strong>Het getal</strong> — de regressie uit de romp van dit blok: <code>gewicht</code> als <strong>Dependent Variable</strong>, met <code>vin_c</code>, <code>snav_c</code> én <code>vinXsnav</code> als <strong>Covariates</strong>.</p></li>
<li><p><strong>Geknipt in tweeën</strong>, bij de middelste snavel. Twee kolommen erbij:</p>
<pre><code>lang       -&gt;   as.numeric(snavellengte &gt;= median(snavellengte))
vinXlang   -&gt;   vin_c * lang</code></pre>
<p>Dan dezelfde regressie met <code>vin_c</code>, <code>lang</code> én <code>vinXlang</code>.</p></li>
<li><p><strong>Geknipt in drieën</strong>, in vrijwel even grote klassen. Maak de kolom <code>klasse</code>:</p>
<pre><code>cut(snavellengte, c(-Inf, quantile(snavellengte, c(1/3, 2/3)), Inf),
    labels = c("kort", "midden", "lang"))</code></pre>
<p>Zet hem op <strong>Nominal</strong>. Het model is hier een <strong>ANOVA → ANCOVA</strong>: <code>gewicht</code> naar <strong>Dependent Variable</strong>, <code>klasse</code> naar <strong>Fixed Factors</strong>, <code>vin_c</code> naar <strong>Covariates</strong>, en voeg onder <strong>Model</strong> de interactieterm <code>vin_c✻klasse</code> toe. Wil je straks de drie hellingen los: filter op <code>klasse == "kort"</code> en draai een gewone regressie van <code>gewicht</code> op <code>vin_c</code>, en zo verder — en zet het filter daarna weer uit.</p></li>
<li><p><strong>De echte soort</strong>, uit de vorige oefening: dezelfde ANCOVA, met <code>soort</code> in plaats van <code>klasse</code>.</p></li>
</ol>
<p>De twee regressies zetten <em>R</em>² in <strong>Model Summary</strong>; de ANCOVA geeft hem onder zijn tabel — staat hij er niet, vink dan onder <strong>Options</strong> de optie <strong>η²</strong> aan.</p>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eindopdracht">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eindopdracht
</div>
</div>
<div class="callout-body-container callout-body">
<section id="methode-en-data-analyse" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse">Methode en data-analyse</h3>
<p><strong>a)</strong> Wat onderzoek je, waarop, en in welke vier gedaanten laat je de moderator meedoen? Schrijf het op zonder één uitkomst te noemen. (twee of drie zinnen; wie of wat er gemeten is, hoeveel, en de vier modellen)</p>
<p><strong>b)</strong> Tel per model hoeveel <strong>parameters</strong> het mag invullen — getallen die het model zelf uit de data haalt. Welke twee paren mag je daarna tegen elkaar uitkomen, en welke niet? (vier getallen en twee paren)</p>
<p><strong>c)</strong> Waarom mag je <em>R</em>² niet tussen modellen met ongelijke parameteraantallen vergelijken? Zeg het in gewone woorden. (één zin; zie het als draaiknoppen)</p>
<p><strong>d)</strong> Kijk of elke gedaante genoeg dieren per groep overhoudt: vraag <code>lang</code> en <code>klasse</code> op met <strong>Descriptives</strong> en vink <strong>Frequency tables</strong> aan. En hoeveel pinguïns doen er in alle vier de modellen mee? (twee plus drie groepsaantallen, en één totaal)</p>
</section>
<section id="resultaten" class="level3">
<h3 class="anchored" data-anchor-id="resultaten">Resultaten</h3>
<p><strong>e)</strong> Waar ligt de middelste snavellengte, en wat geeft het dummy-model? De mediaan vraag je op met <strong>Descriptives</strong> (vink <strong>Median</strong> aan); het model is je knip-in-tweeën-regressie. (rapporteer de mediaan, de helling bij de korte helft, de extra helling met <em>p</em>, en <em>R</em>²)</p>
<p><strong>f)</strong> Tel die twee hellingen bij elkaar op. Welke twee getallen uit de romp van deze oefening krijg je terug? (twee getallen)</p>
<p><strong>g)</strong> Nu de eerste aanwijzing. Het getal-model zei dat de helling met <strong>1.20</strong> per millimeter snavel meebeweegt. Hoe ver liggen de twee helften gemiddeld uit elkaar? Vraag het op met <strong>Descriptives</strong>: <code>snavellengte</code> bij <strong>Variables</strong> en <code>lang</code> bij <strong>Split</strong>. Hoeveel kloof vóórspelt het getal-model dus tussen de helften, en hoeveel meet de knip er? (één som en twee getallen)</p>
<p><strong>h)</strong> Knip nu in drieën en toets zoals bij de drie soorten: eerst één toets over allebei de interactieregels samen — dat is de regel <code>vin_c✻klasse</code> in je ANCOVA-tabel — dan de drie hellingen los, met het klasse-filter uit het kader hierboven. De twee grenzen lees je af als het maximum binnen <em>kort</em> en binnen <em>midden</em>: <strong>Descriptives</strong>, <code>snavellengte</code> bij <strong>Variables</strong> en <code>klasse</code> bij <strong>Split</strong>. (rapporteer de twee grenzen, <em>F</em>(<em>df</em><sub>1</sub>, <em>df</em><sub>2</sub>), <em>p</em> en de drie hellingen)</p>
<p><strong>i)</strong> Zet de vier <em>R</em>²’s op een rij, en vergelijk alleen wat je bij b) mocht vergelijken. Waar zit de verrassing? (vier <em>R</em>²’s en één zin)</p>
<p><strong>j)</strong> Die verrassing is niet gratis. Tel na wie er in die groepen zit: <strong>Frequencies → Contingency Tables</strong>, met <code>lang</code> bij <strong>Rows</strong> en <code>soort</code> bij <strong>Columns</strong>, en daarna nog eens met <code>klasse</code>. Wat blijkt de knip eigenlijk te zijn? (twee percentages en één zin)</p>
<p><strong>k)</strong> Draai het nu om en geef de groep een getal. Vergelijk de Gentoo-regressie uit oefening 10.1 — <code>gewicht</code> op <code>vinlengte</code>, <code>gentoo</code> én <code>vinXgentoo</code> — met het diepte-model uit je Jouw beurt, en reken uit wat de gemiddelde snaveldiepte van de Gentoo’s bij een interactie van −8.60 zou voorspellen. Die twee gemiddelden: <strong>Descriptives</strong>, <code>snaveldiepte</code> bij <strong>Variables</strong> en <code>gentoo</code> bij <strong>Split</strong>. (twee <em>R</em>²’s, twee gemiddelde diepten, en één voorspelde helling naast één gemeten)</p>
<p><strong>l)</strong> Houd tot slot één soort tegelijk vast en draai dezelfde interactie binnen elke soort: zet het <strong>Filter</strong> op <code>soort == "Adelie"</code> en draai de regressie met <code>vin_c</code>, <code>dp_c</code> én <code>vinXdp</code>; herhaal voor <code>"Chinstrap"</code> en <code>"Gentoo"</code>, en zet het filter daarna weer uit. Wat blijft er van de snaveldiepte over? (per soort <em>b</em>, <em>SE</em> en <em>p</em>, en daarna twee of drie zinnen met je eerlijke antwoord)</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Je hebt bij b) en c) al gecontroleerd of de vergelijking eerlijk was — dus nu de vraag die erachteraan hoort. Waar kwam die mediaan van 44.45 mm vandaan, en waarom is de <em>R</em>² van .7762 daardoor eerder te mooi dan te lelijk? (één zin over waar het mes vandaan kwam, en in welke richting dat je uitkomst duwt)</p>
</section>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="methode-en-data-analyse-1" class="level3">
<h3 class="anchored" data-anchor-id="methode-en-data-analyse-1">Methode en data-analyse</h3>
<p><strong>a)</strong> Bijvoorbeeld: <em>“Bij 342 pinguïns onderzochten we of het effect van vinlengte op gewicht afhangt van de snavellengte. We lieten die moderator in vier gedaanten meedoen: als continu getal, geknipt bij de mediaan, geknipt in drie even grote klassen, en vervangen door de soort waartoe het dier behoort. Van elk model bepaalden we de verklaarde variantie, en we vergeleken alleen modellen met gelijke aantallen parameters.”</em> Geen enkel getal uit de uitkomsten.</p>
<p><strong>b)</strong> Het getal-model heeft er <strong>vier</strong> (intercept, twee hellingen, één interactie), de knip in tweeën ook <strong>vier</strong>, de knip in drieën <strong>zes</strong>, en het soort-model <strong>zes</strong>. Je mag dus twee paren tegen elkaar uitkomen: het getal tegen de knip in tweeën, en de knip in drieën tegen de soort. De andere combinaties niet.</p>
<p><strong>c)</strong> Een parameter erbij kan <em>R</em>² nooit laten zakken. Zie het als draaiknoppen: een model met zes knoppen kan er altijd twee op nul zetten en ís dan het model met vier knoppen — verliezen kan het niet, hoogstens gelijkspelen. Een model met meer knoppen naast een model met minder leggen is dus doorgestoken kaart.</p>
<p><strong>d)</strong> De knip in tweeën geeft <strong>171 en 171</strong>, de knip in drieën <strong>115, 113 en 114</strong> — allemaal ruim genoeg. En alle <strong>342</strong> pinguïns doen in alle vier de modellen mee; er valt niemand weg, dus de vier <em>R</em>²’s gaan over precies dezelfde dieren. Dat is geen bijzaak: draaiden twee modellen op verschillende pinguïns, dan mag je hun <em>R</em>² sowieso niet naast elkaar leggen.</p>
</section>
<section id="resultaten-1" class="level3">
<h3 class="anchored" data-anchor-id="resultaten-1">Resultaten</h3>
<p><strong>e)</strong> De mediane snavellengte is <strong>44.45 mm</strong>. Bij de korte helft is de helling <em>b</em> = 37.17 g/mm, en de lange helft loopt daar <em>b</em> = 20.10 g/mm bovenop, <em>p</em> &lt; .001. <em>R</em>² = .7762.</p>
<p><strong>f)</strong> 37.17 + 20.10 = <strong>57.27</strong> — precies de twee losse lijnen (37.17 en 57.27) uit de mediaan-knip eerder in deze oefening. Dezelfde twee getallen, nu uit één tabel in plaats van uit twee losse modellen.</p>
<p><strong>g)</strong> De twee helften liggen <strong>9.40 mm</strong> uit elkaar, gemiddeld 39.22 tegen 48.62 mm. Het getal-model voorspelt dus een kloof van 1.20 × 9.40 = <strong>11.28</strong> g/mm. En de knip meet er <strong>20.10</strong>. Bijna het dubbele — onthoud dat, het is de eerste aanwijzing.</p>
<p><strong>h)</strong> De grenzen liggen op <strong>40.80</strong> en <strong>46.73</strong> mm. De toets over de twee interactieregels samen: <em>F</em>(2, 336) = 20.89, <em>p</em> &lt; .001 — dezelfde vrijheidsgraden als bij de soort-vergelijking in de vorige oefening, want ook hier kwamen er twee regels bij. De drie hellingen: <strong>23.02, 42.22 en 60.26</strong> g/mm. De waaier is wéér breder geworden: het getal gaf 38.84 tot 51.94, de knip in tweeën 37.17 tot 57.27, en deze drie klassen lopen van 23.02 tot 60.26.</p>
<div class="jasp callout callout-style-default callout-note callout-titled" title="In JASP · wat je van je scherm afleest">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In JASP · wat je van je scherm afleest
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las jij die twee grenzen af als het maximum binnen <em>kort</em> en binnen <em>midden</em>, dan zag je 40.8 en 46.7, want de kwantielgrens hoeft zelf geen pinguïn te zijn.</p>
</div>
</div>
<p><strong>i)</strong> .7694 voor het getal, .7762 voor twee groepen, .7863 voor drie groepen en .7896 voor de soort. Vergelijk alleen de twee toegestane paren, en daar staat de verrassing in het bovenste: <strong>de knip wint van het getal</strong>, 77.6% tegen 76.9%, met evenveel parameters. Terwijl deze oefening je net op het hart drukte dat knippen informatie weggooit. In het onderste paar wint de soort van de geknipte klassen, 79.0% tegen 78.6% — de vermomming verliest van het origineel.</p>
<p><strong>j)</strong> Van de korte helft is <strong>87%</strong> Adélie (148 van de 171), en omgekeerd zit <strong>98%</strong> van de Adélies (148 van de 151) in de korte helft. De kortste van de drie klassen is zelfs zuiver: 115 Adélies en niemand anders. De knip op snavellengte is dus bijna dezelfde knip als “Adélie of niet”. Hij gooit wel degelijk informatie weg; hij vindt er alleen per ongeluk iets belangrijkers voor terug — <strong>de soort</strong>, de moderator uit de vorige oefening. Dat verklaart je aanwijzing uit g): de waaier kantelt niet glad met de snavellengte mee, hij springt waar de soorten wisselen, en een knip kan zo’n sprong volgen terwijl een rechte kanteling eroverheen middelt.</p>
<p><strong>k)</strong> De interactie met de <strong>groep</strong> komt op 25.13 met <em>p</em> &lt; .001 en <em>R</em>² = .7846; die met het <strong>getal</strong> gaf −8.60 met <em>R</em>² = .7870. De gemiddelde snaveldiepte is 18.37 mm bij de niet-Gentoo’s en 14.98 bij de Gentoo’s, dus 3.39 mm ertussen. Het diepte-model maakt daarvan −8.60 × (14.98 − 18.37) = 29.15 g/mm. Het getal voorspelt dus dat de Gentoo’s ruim 29 g/mm steiler lopen dan de rest, en de dummy meet zelf 25.13 — het getal doet de groep bijna na. (Die 29.15 rekent met afgeronde getallen; met alle decimalen die het model zelf heeft komt er 29.12 uit. Vandaar <em>ruim 29</em> en geen twee decimalen — zoveel precisie draagt deze som niet.) Schrik niet van de mintekens: de interactie van de diepte is negatief én de Gentoo-snavel ligt 3.39 mm ónder die van de rest, en min keer min is plus. De diepte spreekt de dummy niet tegen; hij vertelt bijna hetzelfde verhaal, in spiegelschrift. En de twee <em>R</em>²’s ontlopen elkaar amper, 78.5% tegen 78.7% — allebei vier parameters, dus deze vergelijking mág.</p>
<p><strong>l)</strong> Binnen één soort valt er aan de soort niets meer te variëren, dus wat daar nog modereert kán de soort niet zijn. Adélies: <em>b</em> = −0.65, <em>SE</em> = 4.36, <em>p</em> = .88 — het getal is kleiner dan zijn eigen ruis. Chinstraps: <em>b</em> = 8.09, <em>SE</em> = 4.75, <em>p</em> = .094, ook niets om over naar huis te schrijven. Gentoo’s: <em>b</em> = −12.55, <em>SE</em> = 4.84, <em>p</em> = .011 — daar blijft hij staan, en hij is er zelfs stérker dan over het hele bestand (−8.60).</p>
<p>Het eerlijke antwoord heeft dus twee delen, en dat mag: <strong>bij twee van de drie soorten stond de snaveldiepte inderdaad alleen maar in voor de soort, en bij de Gentoo’s doet hij zelf iets.</strong> Pas op voor de valkuil aan béíde kanten: <em>“de diepte stond alleen maar in voor de soort”</em> verklaart de Gentoo’s niet, en <em>“de diepte is gewoon zelf de moderator”</em> verklaart de Adélies en de Chinstraps niet.</p>
<p><strong>Z)</strong> Die mediaan van 44.45 mm kwam <strong>uit dezelfde 342 pinguïns</strong> waarop je het model daarna hebt beoordeeld. Je hebt het mes dus geslepen op het hout dat je ermee ging zagen, en dat duwt maar één kant op: <strong>de <em>R</em>² van .7762 is eerder te mooi dan te lelijk.</strong> Op een nieuwe groep pinguïns zou de knip het slechter doen dan hier, want de mediaan van díé groep ligt ergens anders.</p>
<p>Dat maakt je conclusie bij i) niet ongeldig — het verschil tussen .7762 en .7694 is echt, en de verklaring bij j) is dat ook: 148 van de 151 Adélies zitten werkelijk in de korte helft, en dat verzin je niet met een mediaan. Maar het maakt de winst kleiner dan hij eruitziet. Hoe je zoiets fatsoenlijk meet — een model beoordelen op dieren die niet meededen aan het bouwen ervan — staat niet in dit oefenboek, en dat zeg je er dan ook eerlijk bij.</p>
<p>En de weg terug, voor de gewone aannames: gingen de residuen trechteren, dan <strong>blijven staan</strong> alle hellingen bij e), g), h) en k), en alle vier de <em>R</em>²’s — dat zijn beschrijvingen van deze 342 dieren. <strong>Doe je over</strong>: de <em>p</em> bij e), de <em>F</em> bij h) en de drie <em>p</em>’s bij l), want die rusten op één gedeelde restspreiding.</p>
</section>
</div>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-het-op-als-een-onderzoeker" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</h2>
<p><span class="begrippen">rapportagezin · simple slopes · b en p</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bij een continue moderator moet je rapportagezin iets extra’s doen wat bij een groep niet nodig was: hij moet <strong>zeggen op welke waarden je de hellingen hebt afgelezen</strong>. Anders kan niemand jouw getallen narekenen — ze hangen immers af van een keuze die jij gemaakt hebt. Zo:</p>
<blockquote class="blockquote">
<p>Om te onderzoeken of het effect van vinlengte op gewicht afhangt van de snavellengte, voerden we bij 342 pinguïns een regressieanalyse uit met beide voorspellers gecentreerd en hun interactieterm in het model. De interactie was significant, <em>b</em> = 1.20, <em>p</em> &lt; .001; het model verklaarde 76.9% van de variantie in gewicht. Bij een gemiddelde snavellengte (43.92 mm) ging een millimeter extra vin samen met 45.39 gram extra gewicht. Simple slopes op één standaardafwijking onder en boven het gemiddelde lieten zien dat dit effect toenam met de snavellengte: 38.84 g/mm bij een korte snavel (38.46 mm) en 51.94 g/mm bij een lange snavel (49.38 mm).</p>
</blockquote>
<p>Kijk wat er cursief staat en wat niet. Alléén de symbolen <em>b</em> en <em>p</em> hellen; de gewone woorden, de millimeters en de grammen staan rechtop. De statistieken krijgen <strong>twee decimalen</strong>, en een <em>p</em> onder de .001 schrijf je als <em>p</em> &lt; .001, zonder nul ervoor. Eén ding wijkt daarvan af, en dat is met opzet: <em>R</em>² staat hier als <strong>percentage met één decimaal</strong> (76.9%) in plaats van als .77. In deze oefening zit het verschil tussen de modellen in de derde decimaal, en op twee decimalen vallen precies de twee samen die je uit elkaar moet kunnen houden — dat zie je in de eindopdracht gebeuren. Alles staat in de verleden tijd. En de zin staat op eigen benen: wie ’m uit dit blok tilt, weet wie er gemeten werd, wat er gemeten werd, dat er gecentreerd is, en op welke drie waarden de hellingen zijn afgelezen.</p>
<p>Dat laatste is de nieuwe eis. Zou je alleen <em>“de simple slopes waren 38.84 en 51.94”</em> opschrijven, dan staat er een getal zonder adres — en dan is het net zo onnavolgbaar als de −7.31 uit het ongecentreerde model.</p>
<p>Jouw beurt: schrijf zelf de rapportage-zin voor je <strong>jouw-beurt-taak</strong> — de snaveldiepte. Let op twee dingen: de interactie is daar negatief, dus de reeks loopt omláág, en de standaardafwijking is een andere (1.97 in plaats van 5.46), dus je leest af op andere waarden. De modelzin hierboven mag je lenen; hardop voorlezen mag ook.</p>
<p>En dan de eindopdracht van het hoofdstuk, want die brengt zijn eigen rapportage-plicht mee. Je hebt daar dezelfde moderator in twee gedaanten gebruikt — als getal en als knip — en allebei leveren ze een nette, eerlijke zin op, met verschillende getallen erin. Je zin moet dus zeggen <strong>in welke gedaante de moderator meedeed</strong>, anders kan niemand zien welke analyse jij gedaan hebt, laat staan hem narekenen. Zo klinkt de knip-versie:</p>
<blockquote class="blockquote">
<p>Om te onderzoeken of het effect van vinlengte op gewicht afhangt van de snavellengte, deelden we een steekproef pinguïns (<em>N</em> = 342) bij de mediane snavellengte (44.45 mm) in een korte en een lange helft (<em>n</em> = 171 per helft) en voerden we een regressieanalyse uit met vinlengte, deze tweedeling en hun interactieterm als voorspellers. De interactie was significant, <em>b</em> = 20.10, <em>SE</em> = 3.95, 95% CI [12.34, 27.86], <em>p</em> &lt; .001; het model verklaarde 77.6% van de variantie in gewicht. Bij de pinguïns met een korte snavel ging een millimeter extra vin samen met 37.17 gram extra gewicht, bij die met een lange snavel met 57.27 gram.</p>
</blockquote>
<p>Leg hem naast de modelzin bovenaan deze rapportage. Die moest zeggen op welke waarden je de hellingen hebt afgelezen; deze moet zeggen waar het mes viel. Twee keer dezelfde plicht — een helling zonder adres is niet na te rekenen — alleen het soort adres verschilt. En ja: eerder in deze oefening stond dat je níét moet knippen als je echt gaat rapporteren. Dat advies staat nog steeds. Maar wie tóch knipt, zegt het er in elk geval bij, want het is een keuze die de getallen verandert — en dat is precies wat je in de eindopdracht zag gebeuren.</p>
<p>Jouw beurt, de laatste van dit hoofdstuk: schrijf de rapportage-zin voor de knip in drieën. Je hebt eraan: de modelvergelijking <em>F</em>(2, 336) = 20.89, <em>p</em> &lt; .001, de drie hellingen (23.02, 42.22 en 60.26 g/mm) en de twee grenzen (40.80 en 46.73 mm). De eerste modelzin uit de rapportage van de vorige oefening — die over de drie soorten — mag je als voorbeeld ernaast leggen, want dit is precies dat model, alleen met geknipte klassen in plaats van echte soorten. En keur je eigen zin daarna op de nieuwe eis: kan een lezer aan jouw woorden zien dát de snavellengte geknipt is, en waar de grenzen lagen?</p>
</div>
</div>
<div class="boekvorm" data-w="W10">
<p>◠ <strong>In het boek</strong></p>
<p>Hier: als de moderator een getal is, kun je hem niet meer tekenen — je moet zelf kiezen waar je gaat staan om de helling af te lezen.</p>
<p>In het boek: <strong>W10 — Verschil in verschil</strong></p>
<p><em>Daar draait het om de lijnen die niet parallel lopen — het moment waarop je merkt dat “het effect” een tweede vraag nodig heeft: bij wie?</em></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Palmer Penguins — Gorman, Williams &amp; Fraser (2014), Palmer Station Antarctica LTER; via het R-pakket <code>palmerpenguins</code> (CC0). Alle getallen in dit blok zijn op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_interactie.html" class="pagination-link" aria-label="Oefening 10.1 · Als de moderator een groep is">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 10.1 · Als de moderator een groep is</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_mediatie.html" class="pagination-link" aria-label="Oefening 11.1 · Mediatie: direct en indirect">
        <span class="nav-page-text">Oefening 11.1 · Mediatie: direct en indirect</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>