<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 8.1 · Meervoudige regressie en partiële correlatie – SPSS-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_dummy_regressie.html" rel="next">
<link href="../20_blokken/blok_cronbach_alpha.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">H8 · Meer dan één verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">Oefening 8.1 · Meervoudige regressie en partiële correlatie</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">SPSS-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SPSS-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in SPSS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Vierde beweging · Verschil onthechten</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">H8 · Meer dan één verschil</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_meervoudige_regressie.html">Oefening 8.1 · Meervoudige regressie en partiële correlatie</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 8.1 · Meervoudige regressie en partiële correlatie</h1>
<p class="subtitle lead">Twee voorspellers naast elkaar · <em>multiple regression</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#zevenentachtig-gram-per-millimeter-snavel" id="toc-zevenentachtig-gram-per-millimeter-snavel">Zevenentachtig gram per millimeter snavel</a></li>
  <li><a href="#trek-de-regressielijn-in-spss-eerst-zonder-dan-met-de-vin" id="toc-trek-de-regressielijn-in-spss-eerst-zonder-dan-met-de-vin">Trek de regressielijn in SPSS — eerst zonder, dan met de vin</a></li>
  <li><a href="#lees-de-tabellen-van-onderen-naar-boven" id="toc-lees-de-tabellen-van-onderen-naar-boven">Lees de tabellen van onderen naar boven</a></li>
  <li><a href="#reken-de-vin-weg-en-kijk-wat-er-overblijft" id="toc-reken-de-vin-weg-en-kijk-wat-er-overblijft">Reken de vin weg en kijk wat er overblijft</a></li>
  <li><a href="#schud-de-vinlengte-los-van-het-gewicht" id="toc-schud-de-vinlengte-los-van-het-gewicht">Schud de vinlengte los van het gewicht</a></li>
  <li><a href="#waarom-de-snavel-instort-hij-zei-niets-eigens" id="toc-waarom-de-snavel-instort-hij-zei-niets-eigens">Waarom de snavel instort: hij zei niets eigens</a></li>
  <li><a href="#twee-maten-die-elkaar-niet-in-de-weg-zitten" id="toc-twee-maten-die-elkaar-niet-in-de-weg-zitten">Twee maten die elkaar niet in de weg zitten</a></li>
  <li><a href="#schrijf-het-op-als-een-onderzoeker" id="toc-schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="zevenentachtig-gram-per-millimeter-snavel" class="level2">
<h2 class="anchored" data-anchor-id="zevenentachtig-gram-per-millimeter-snavel">Zevenentachtig gram per millimeter snavel</h2>
<p><span class="begrippen">regressielijn · helling · <em>R</em>²</span></p>
<p>Op de rots bij Antarctica meet iemand snavels.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Millimeter voor millimeter, pinguïn voor pinguïn, driehonderdtweeënveertig koppen die liever waren gaan vissen.</p>
<p>En dat meten loont, zo lijkt het. In deze pinguïns voorspelt snavellengte het gewicht heel behoorlijk: elke millimeter snavel gaat samen met zo’n 87 gram meer pinguïn (<em>b</em> = 87.42), en die ene maat verklaart ruim een derde van alle verschil in gewicht (<em>R</em>² = .354). Wie de snavel kent, weet al aardig wat de weegschaal gaat zeggen.</p>
<p>Maar er is méér gemeten op die rots — de vin bijvoorbeeld. En dan wordt de vraag ineens scherper. Niet: voorspelt de snavel het gewicht? Dat doet hij, zie de getallen hierboven. Maar: vertelt de snavel ons iets wat we nog niet wisten? Iets van zichzélf? Trek even mee — we zetten de vin ernaast, en dan mag de snavel laten zien wat hij zelf nog te vertellen heeft.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="trek-de-regressielijn-in-spss-eerst-zonder-dan-met-de-vin" class="level2">
<h2 class="anchored" data-anchor-id="trek-de-regressielijn-in-spss-eerst-zonder-dan-met-de-vin">Trek de regressielijn in SPSS — eerst zonder, dan met de vin</h2>
<p><span class="begrippen">tweede voorspeller · zakkende helling · <em>R</em>²</span></p>
<div class="spss callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ol type="1">
<li><strong>Analyze → Regression → Linear</strong>, <code>glans</code> als <strong>Dependent</strong>, <code>karaat</code> als <strong>Independent</strong>. <strong>OK</strong> — noteer <em>b</em> en <em>R</em>².</li>
<li>Zelfde analyse, nu met <code>karaat</code> én <code>gladheid</code> als <strong>Independent(s)</strong>. Of gebruik <strong>Next</strong> om er een tweede blok van te maken.</li>
</ol>
<p>Karaat zakt van 32.14 naar 0.98; <em>R</em>² gaat van .33 naar .82.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<pre><code>REGRESSION
  /STATISTICS COEFF R ANOVA CHANGE
  /DEPENDENT glans
  /METHOD=ENTER karaat
  /METHOD=ENTER gladheid.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Los voorspelt karaat de glans met <em>b</em> = 32.14, maar zet gladheid ernaast en er blijft <em>b</em> = 0.98 van over — terwijl <em>R</em>² van .33 naar .82 springt. Niet het gewicht maakte de steentjes mooi; de slijper deed dat, en karaat liftte mee.</p>
<p><strong>Nu jij</strong> — bij de pinguïns, die je goed kent inmiddels. De snavellengte voorspelt het gewicht keurig — tot je de vinlengte ernaast zet.</p>
<p>Haal de pinguïns binnen en trek eerst die ene simpele lijn: gewicht voorspeld uit snavellengte, meer niet. Kijk dan wat er gebeurt als je de vinlengte erbij zet.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · trek eraan">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · trek eraan
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Open <code>penguins.csv</code> in SPSS: <strong>File → Open → Data</strong>, bestandstype op <strong>CSV</strong>.</li>
<li>Ga naar <strong>Analyze → Regression → Linear</strong>. Zet <code>gewicht</code> in <strong>Dependent</strong> en <code>snavellengte</code> in <strong>Independent(s)</strong>. Draai zo eerst het model met alleen de snavel.</li>
<li>Nu de vin erbij: klik bij <strong>Independent(s)</strong> op <strong>Next</strong> en zet <code>vinlengte</code> in blok 2 — zo houd je de twee modellen naast elkaar. (Allebei in één blok mag ook; dan zie je alleen het tweede model.)</li>
<li>Klik op <strong>Statistics…</strong> en zet aan: <strong>Estimates</strong>, <strong>Model fit</strong>, <strong>R squared change</strong> en <strong>Confidence intervals</strong> op 95%. Dan zet SPSS in <strong>Model Summary</strong> vanzelf <em>R Square Change</em>, <em>F Change</em> en <em>Sig. F Change</em> neer — dat heb je zo nodig.</li>
</ol>
<p>Of, als je liever typt dan klikt:</p>
<pre><code>REGRESSION
  /STATISTICS COEFF R ANOVA CHANGE CI(95)
  /DEPENDENT gewicht
  /METHOD=ENTER snavellengte
  /METHOD=ENTER vinlengte.</code></pre>
</div>
</div>
<p>Kijk naar dat ene getal bij <code>snavellengte</code>. In het eerste model staat er <strong>87.42</strong>: ruim 87 gram per millimeter, en een derde van alle verschil in gewicht verklaard. Zet je de vinlengte ernaast, dan zakt diezelfde helling naar <strong>6.05</strong> — nog geen veertiende van wat hij was. En de <em>R</em>² doet precies het omgekeerde van de helling: die springt van .35 naar .76.</p>
<p>Dat is dezelfde beweging als bij de steentjes, alleen harder. Daar viel karaat van 32.14 naar 0.98 zodra gladheid binnenkwam; hier valt de snavel van 87.42 naar 6.05 zodra de vin binnenkomt. De vraag is dus dezelfde: <em>wat hoorde er nou eigenlijk bij de snavel?</em></p>
</section>
<section id="lees-de-tabellen-van-onderen-naar-boven" class="level2">
<h2 class="anchored" data-anchor-id="lees-de-tabellen-van-onderen-naar-boven">Lees de tabellen van onderen naar boven</h2>
<p><span class="begrippen"><em>F</em>-toets · adjusted <em>R</em>² · standaardfout</span></p>
<p>Die vraag houden we nog even vast, want SPSS heeft zonet meer uitgerekend dan je gelezen hebt. Er staan drie tabellen in je output, en tot nu toe viste je er twee getallen uit: de helling en de <em>R</em>². In diezelfde tabellen staat óók alles wat een artikel over dit model zou rapporteren — je moet alleen weten in welke volgorde je ze leest. En die volgorde is niet van boven naar beneden.</p>
<p>Eigenlijk wil je eerst het model <strong>als geheel</strong> toetsen: is er iets, of is er niets aan de hand? De nulhypothese is hier lekker groots: dit model — snavellengte en vinlengte samen — verklaart níéts van de verschillen in gewicht, de <em>R</em>² is in de populatie nul. De alternatieve zegt: die <em>R</em>² is groter dan nul. En dát toetsen we met de <strong><em>F</em>-toets</strong>: één getal dat afweegt hoeveel verschil in gewicht het model verklaart tegenover hoeveel er als ruis overblijft. Hij staat in de tabel <strong>ANOVA</strong>: <em>F</em>(2, 339) = 536.63, <em>p</em> &lt; .001. (SPSS noemt die <em>p</em> <strong>Sig.</strong> — zelfde getal, andere naam.)</p>
<p>De 2 telt de hellingen in het model — één voor de snavel, één voor de vin — en de 339 is de rest: 342 pinguïns min de drie getallen die het model schat, die twee hellingen plus het intercept. Die <em>p</em> ken je uit de oefening over de <em>p</em>-waarde: in werelden waarin het model werkelijk niets verklaart, maakt toeval zó’n <em>F</em> vrijwel nooit na. De nulhypothese dat dit model niets van de verschillen in gewicht verklaart, mag dus de deur uit. En pas als dát vaststaat, heeft de rest van de tabellen zin — is er niks, dan valt er ook niks te verdelen.</p>
<p>Let op wat die <em>F</em> wél en niet zegt, want dat wordt zo belangrijk. Hij toetst het model <strong>als geheel</strong>. Hij zegt dus: <em>hier zit iets in.</em> Hij zegt niet dat allebei de voorspellers dat iets leveren.</p>
<p>Ga dan naar <strong>Model Summary</strong>, want daar staat een kolom die we nog niet hadden: <em>Adjusted R Square</em>. De gewone <em>R</em>² is uitgerekend op déze 342 pinguïns, en hij vleit zichzelf: elke voorspeller die je toevoegt kan hem alleen maar omhoog duwen, nooit omlaag — ook een kolom met puur toeval erin duwt hem nog een fractie op. De adjusted <em>R</em>² haalt die vleierij eraf: hij generaliseert de <em>R</em>² van jouw steekproef naar andere mogelijke steekproeven — naar de populatie dus. Hier schelen de twee elkaar bijna niets, .760 tegenover .759, en dát is het nieuws: met 342 pinguïns en maar twee hellingen valt er nauwelijks iets af te halen. Lopen die twee ver uiteen, dan heb je te veel voorspellers op te weinig data gezet, en schept je <em>R</em>² vooral op over jouw eigen steekproef.</p>
<p>Pas als het geheel zegt dat er iets is, ga je uitzoeken waar het aan ligt: aan de snavel, aan de vin, of aan allebei. Daarvoor is de tabel <strong>Coefficients</strong> — en je hebt haar kolommen stuk voor stuk al eens ergens gezien:</p>
<ul>
<li><strong>B</strong> (onder <em>Unstandardized Coefficients</em>) — de hellingen zelf. De 48.14 van de vin en de 6.05 van de snavel. (De bovenste regel, <em>(Constant)</em>, is het intercept: het voorspelde gewicht bij een vin én een snavel van nul millimeter — laat die even voor wat hij is; die pinguïn bestaat niet.)</li>
<li><strong>Std. Error</strong> — de <strong>standaardfout</strong> van elke helling: hoe ver zo’n helling van steekproef tot steekproef zou dansen. Dezelfde wiebel die je in de oefening over de steekproevenverdeling voor het gemiddelde uitrekende, nu voor een helling. Voor de vin 2.01, voor de snavel 5.18.</li>
<li><strong>t</strong> — de helling gedeeld door zijn standaardfout: hoeveel standaardfouten ligt hij van nul af? Voor de vin 23.94, voor de snavel 1.17. (Deel je de getoonde 6.05 door de getoonde 5.18, dan krijg je 1.168 — SPSS rekent met álle decimalen, niet met de afrondingen.)</li>
<li><strong>Sig.</strong> — de <em>p</em> die daarbij hoort.</li>
</ul>
<p>Elke regel toetst zo zijn eigen kleine nulhypothese: déze helling is in de populatie nul, met de andere voorspeller vastgehouden. En hier lopen de twee regels ver uiteen. De vin ligt bijna vierentwintig standaardfouten van nul, <em>p</em> &lt; .001: die levert, náást de snavel, een significante unieke bijdrage aan het voorspellen van het gewicht. De snavel ligt er nog geen anderhalve standaardfout vandaan, <em>p</em> = .24. Voor de snavel houd je de nulhypothese dus gewoon overeind: naast de vin is er geen bewijs dat hij nog íéts van zichzelf bijdraagt aan het voorspellen van het gewicht.</p>
<p>Kijk daar even naar, want het is precies wat de prikkel vroeg. Dezelfde kolom die in zijn eentje ruim een derde van het gewichtsverschil verklaarde, haalt naast de vin de drempel niet eens meer.</p>
<p>En dat vinkje <strong>Confidence intervals</strong> geeft het laatste stuk: twee extra kolommen met het 95%-betrouwbaarheidsinterval van elke helling. Voor de vin loopt het van 44.19 tot 52.10. Lees het zoals je élk interval leest: eerst waar het loopt — alle waarden voor de echte helling die nog goed bij deze data passen, van krap 44 tot ruim 52 gram per millimeter — en dan of nul meedoet. Nul valt er ruim buiten.</p>
<p>Voor de snavel loopt het van <strong>−4.14 tot 16.24</strong>, en daar zit nul dus gewoon tússen. Dat is dezelfde uitspraak als die <em>p</em> van .244, in andere kleren: het interval sluit een helling van nul niet uit. Sterker nog, het sluit ook een <em>negatieve</em> helling niet uit. Het interval is het schat-antwoord, de <em>p</em> de toets-bijvraag die er al in zit; het is hetzelfde feit, twee keer bekeken. Valt nul buiten het 95%-interval, dan is de <em>p</em> kleiner dan .05 — en valt nul erbinnen, zoals hier, dan is hij groter.</p>
<p>Dat interval zegt trouwens iets wat de <em>p</em> níét zegt, en het is het waard er even bij stil te staan. <em>p</em> = .24 betekent <strong>niet</strong> “de snavel doet niets”. Het interval laat zien wat er nog past bij deze data: van vier gram eraf tot zestien gram erbij. Wat je hebt vastgesteld is niet dat de bijdrage nul ís, maar dat je hem met 342 pinguïns niet van nul kunt onderscheiden.</p>
<p>Daarmee heb je de tabellen gelezen zoals een onderzoeker ze leest: eerst het geheel, dan pas de delen. Studeer je psychologie, dan loop je deze trap in het tweede jaar gewoon opnieuw, in het MVDA-werkboek van Peter de Heus<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> — alleen in een andere volgorde: daar keur je éérst de residuen en ga je pas daarna het model in, hier kwam het model eerst en deed je die keuring al eerder, in de oefening over de residuen. Geen van beide volgordes is de juiste; je moet ze allebei gedaan hebben voordat je je conclusie opschrijft. Maar twee dingen staan nog open: of je die <em>p</em> van de vin zomaar op zijn woord moet geloven — en hoevéél elk van de twee nou eigenlijk zelf inbrengt. Dat tweede eerst, want daar is een getal voor.</p>
</section>
<section id="reken-de-vin-weg-en-kijk-wat-er-overblijft" class="level2">
<h2 class="anchored" data-anchor-id="reken-de-vin-weg-en-kijk-wat-er-overblijft">Reken de vin weg en kijk wat er overblijft</h2>
<p><span class="begrippen">partiële correlatie · residuen · wegrekenen</span></p>
<p>De tabel gaf je een <em>p</em> en een helling. Maar de vraag uit de prikkel was eigenlijk een correlatie-vraag: <em>hoe sterk hangen gewicht en snavel nog samen als de vin er niet tussen zit?</em> Daar bestaat een eigen getal voor, en je bouwt het in drie stappen zelf — met gereedschap dat je al hebt.</p>
<p>Het recept is precies wat het woord <em>wegrekenen</em> belooft. Wil je weten wat er van de band tussen gewicht en snavellengte overblijft als de vinlengte er geen rol meer in speelt, dan <strong>haal je uit allebei weg wat de vin erover te zeggen had</strong>, en kijkt of de restjes nog samenhangen. En “wat de vin erover te zeggen had” weghalen — dat zijn residuen, en die ken je uit de oefening over de residuen: wat er van een kolom overblijft nadat een model erdoorheen is getrokken.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · de partiële correlatie, met de hand">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · de partiële correlatie, met de hand
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Analyze → Regression → Linear</strong>, met <code>gewicht</code> in <strong>Dependent</strong> en <code>vinlengte</code> in <strong>Independent(s)</strong>. Klik op <strong>Save…</strong> en vink onder <strong>Residuals</strong> het vakje <strong>Unstandardized</strong> aan. In je databestand verschijnt een nieuwe kolom, <code>RES_1</code>: wat er van het gewicht overblijft nadat de vin erover gezegd heeft wat hij te zeggen had.</li>
<li>Nog een keer, nu met <code>snavellengte</code> in <strong>Dependent</strong> en <code>vinlengte</code> in <strong>Independent(s)</strong>, weer met <strong>Save… → Unstandardized</strong>. Dat wordt <code>RES_2</code>: de snavellengte, met de vin eruit.</li>
<li><strong>Analyze → Correlate → Bivariate</strong>, met <code>RES_1</code> en <code>RES_2</code>: <em>r</em> = .063. Draai dezelfde correlatie ook één keer op <code>gewicht</code> en <code>snavellengte</code> zelf — zonder wegrekenen is het <em>r</em> = .595.</li>
</ol>
<p>Of, als je liever typt dan klikt:</p>
<pre><code>REGRESSION
  /DEPENDENT gewicht
  /METHOD=ENTER vinlengte
  /SAVE RESID.
REGRESSION
  /DEPENDENT snavellengte
  /METHOD=ENTER vinlengte
  /SAVE RESID.
CORRELATIONS /VARIABLES=RES_1 RES_2.
CORRELATIONS /VARIABLES=gewicht snavellengte.</code></pre>
</div>
</div>
<p>Van <strong>.595 naar .063</strong>. Dit getal heet de <strong>partiële correlatie</strong> (<em>partial correlation</em>): de samenhang tussen gewicht en snavellengte <em>bij gelijk gehouden vinlengte</em>. Onderzoekers zeggen daar iets deftigs bij — <em>“gecontroleerd voor vinlengte”</em> — maar je hebt nu met je eigen handen gevoeld wat het is: wegrekenen, en kijken wat overblijft.</p>
<p>Er kwam geen speciale knop aan te pas: <code>RES_1</code> en <code>RES_2</code> zijn residuen, en een gewone correlatie deed de rest. <strong>Het bouwsel ís de definitie</strong> — en dat is precies waarom het hier zo staat. SPSS hééft die knop overigens wel: <strong>Analyze → Correlate → Partial</strong>, met <code>gewicht</code> en <code>snavellengte</code> in <strong>Variables</strong> en <code>vinlengte</code> in <strong>Controlling for</strong>, geeft exact dezelfde .063 — maar dan had je niet gevoeld wat er weggerekend werd.</p>
<p>Doe het nu andersom, want dat is de andere helft van het antwoord:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · en nu de vin, met de snavel weggerekend">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · en nu de vin, met de snavel weggerekend
</div>
</div>
<div class="callout-body-container callout-body">
<p>Zelfde recept, andersom: bewaar de residuen van <code>gewicht</code> uit <code>snavellengte</code> en van <code>vinlengte</code> uit <code>snavellengte</code> (SPSS nummert vanzelf door: <code>RES_3</code> en <code>RES_4</code>), en correleer die twee: <em>r</em> = .793. Zonder wegrekenen, <code>gewicht</code> met <code>vinlengte</code>: <em>r</em> = .871.</p>
</div>
</div>
<p>De vin houdt bijna alles over: van .871 naar <strong>.793</strong>. De snavel houdt vrijwel niets over: van .595 naar <strong>.063</strong>. Dáár staat, in twee getallen naast elkaar, wat de tabel je met een <em>p</em> van .244 al probeerde te vertellen.</p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Let op — twee getallen die op elkaar lijken en het niet zijn">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Let op — twee getallen die op elkaar lijken en het niet zijn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Er bestaat een tweede getal met bijna dezelfde naam, en het is een klassieke struikelplek. Naast de <strong>partiële</strong> correlatie is er de <strong>semi-partiële</strong> correlatie (SPSS noemt die in zijn tabellen <em>Part</em>). Het verschil zit in hoevéél je wegrekent:</p>
<ul>
<li>bij de <strong>partiële</strong> correlatie haal je de andere voorspeller uit <strong>allebei</strong> de kolommen weg — dat deed je hierboven;</li>
<li>bij de <strong>semi-partiële</strong> correlatie haal je hem alleen uit de <strong>voorspeller</strong> weg, en laat je het gewicht heel.</li>
</ul>
<p>Het is dus hetzelfde stukje verklaarde ruimte, afgezet tegen iets anders. Bij de semi-partiële zet je het af tegen <strong>alle</strong> gewichtsverschillen; bij de partiële alleen tegen wat er ná de vin nog te verklaren óverblijft. Zelfde stukje, andere maatstok — en omdat die tweede maatstok kleiner is, is de partiële correlatie altijd de grootste van de twee.</p>
<p>Zet ze allebei in beeld, dan zie je het. Klik in <strong>Analyze → Regression → Linear</strong> op <strong>Statistics…</strong> en vink <strong>Part and partial correlations</strong> aan: in <strong>Coefficients</strong> komen er dan drie kolommen bij, onder de kop <em>Correlations</em> — <em>Zero-order</em>, <em>Partial</em> en <em>Part</em>. Onder <em>Partial</em> staan de .793 en .063 van hierboven; onder <em>Part</em> staat de semi-partiële — <strong>.637</strong> voor de vin, <strong>.031</strong> voor de snavel.</p>
<p>Waarom dit ertoe doet: <strong>de semi-partiële correlatie in het kwadraat is de unieke bijdrage aan <em>R</em>².</strong> Niet de partiële. Reken maar na: .637² = .406, en de <em>R</em>² van het model gaat inderdaad van .354 (snavel alleen) naar .760 als de vin binnenkomt — een sprong van .406. Had je .793 gekwadrateerd, dan was je op .628 uitgekomen, en dat getal staat nergens in de tabellen.</p>
</div>
</div>
<p>Onder elkaar, zodat je ze uit elkaar kunt houden:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>gewone <em>r</em></th>
<th>partieel</th>
<th>semi-partieel</th>
<th>uniek in <em>R</em>²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>vinlengte</td>
<td>.871</td>
<td>.793</td>
<td>.637</td>
<td>.406</td>
</tr>
<tr class="even">
<td>snavellengte</td>
<td>.595</td>
<td>.063</td>
<td>.031</td>
<td>.001</td>
</tr>
</tbody>
</table>
<p>De onderste rij is het hele verhaal van dit blok in vier getallen: een maat die in zijn eentje een <em>r</em> van .595 haalt, en aan het model één duizendste <em>R</em>² toevoegt.</p>
</section>
<section id="schud-de-vinlengte-los-van-het-gewicht" class="level2">
<h2 class="anchored" data-anchor-id="schud-de-vinlengte-los-van-het-gewicht">Schud de vinlengte los van het gewicht</h2>
<p><span class="begrippen">schud-toets · husselen · helling uit puur toeval</span></p>
<p>Voordat we dat uitzoeken, eerst de eerlijkheidscheck: is die 48.14 van de vin écht, of kan zo’n helling ook uit het niets ontstaan? Je zou vals willen spelen: de snavellengte netjes op z’n plek houden, maar elke vinlengte losknippen van z’n eigen pinguïn en op een willekeurige andere plakken.</p>
<p>Dat loskoppelen is de hele truc, en het is het waard er even bij stil te staan: door de vinlengtes te husselen <strong>haal je met eigen handen weg dat een bepaalde vin bij een bepaald gewicht hoort</strong>. In zo’n losgekoppelde wereld kán de vin niks meer bijdragen — elk beetje helling dat je er dan nóg in meet, is per definitie puur toeval. Doe het duizend keer en kijk waar de vin-helling belandt.</p>
<p><strong>En hier moet ik eerlijk zijn: dat schudden is geen knop in SPSS.</strong> SPSS rekent één keurige uitkomst uit; het door elkaar husselen en duizend keer opnieuw kijken is <em>code</em>-werk. Dat is geen gemis van jou of van SPSS — het boek doet het bewust zo. Voor deze meervoudige regressie is er geen los schud-speeltje; wil je de duizend werelden echt zien dansen, draai dan het <strong>R-broertje</strong>, waar het drie regels code is.</p>
<p>Wat je in dat R-broertje ziet: <strong>duizend werelden die dansen rond nul</strong> — want in elke geschudde wereld is de band tussen vin en gewicht doorgeknipt, maar toeval laat de helling nooit precies op nul landen. Ze wiebelen allemaal dicht om nul, van zo’n −8 tot +8 gram per millimeter, niet verder. En dan die rode streep op 48.14, mijlenver buiten het hele bergje. In duizend keer schudden haalde <strong>geen enkele</strong> wereld het. Dát is wat “geen toeval” betekent — geen <em>p</em>-waarde die je moet geloven, maar een <strong>afstand die je zíet</strong>. De 48.14 is echt van de vin.</p>
<p>Nog één ding, omdat je de tabellen al gelezen hebt. Het schudden en de <em>p</em> stelden dezelfde vraag — <em>kan toeval dit namaken?</em> — en gaven hetzelfde antwoord: nee. Maar ze meten met een andere lat, en dat zie je meteen: het geschudde bergje in het R-broertje wiebelt 2.52 om nul, terwijl de standaardfout van diezelfde helling 2.01 was — dat is de <em>SE</em> van de vin uit <strong>Coefficients</strong>, een paar secties terug. Dat is geen slordigheid, en het is de moeite waard om te weten waaróm ze verschillen: in een wereld waarin de vin is losgeknipt, is er niemand meer die het gewicht goed voorspelt — alleen de snavel blijft over, en die kan het niet alleen. Er blijft dus veel meer onverklaarde ruis liggen, en in meer ruis wiebelt elke helling breder. Onthoud dus het antwoord van het schudden, en de lat van de tabel.</p>
<p>Dus de vin draagt echt bij, óók naast de snavel. Maar waarom stortte de snavel dan in van 87.42 naar 6.05? Daar zit de les — en die kun je wél gewoon in SPSS nalezen.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="waarom-de-snavel-instort-hij-zei-niets-eigens" class="level2">
<h2 class="anchored" data-anchor-id="waarom-de-snavel-instort-hij-zei-niets-eigens">Waarom de snavel instort: hij zei niets eigens</h2>
<p><span class="begrippen">confounder · constant houden · overlap tussen voorspellers</span></p>
<p>De simpele lijn schreef álle 87.42 gram per millimeter toe aan de snavellengte. Maar er speelde iemand mee die niet in het model zat: de <strong>vinlengte</strong>. Pinguïns met een lange snavel hebben meestal ook lange vinnen — de twee maten hangen onderling samen met <em>r</em> = .656. Gooi je ze op één hoop en trek je één lijn op de snavel alleen, dan telt een flink deel van “lange vin weegt meer” mee als “lange snavel weegt meer”. De snavellengte kreeg krediet dat eigenlijk aan de vin toebehoorde.</p>
<p>Reken je de vin mee — houd ’m constant, vergelijk pinguïns <em>met dezelfde vinlengte</em> — dan valt dat geleende stuk weg, en blijft er van de snavel bijna niets over: <strong>6.05</strong>, en niet eens te onderscheiden van nul. Dat is precies wat meervoudige regressie doet. Ze vraagt niet “hangt gewicht samen met snavellengte?”, maar: <em>wat draagt elke voorspeller bij als de andere gelijk blijft?</em> Elke helling in het model is een helling <strong>met de rest vastgehouden</strong>.</p>
<p>De vinlengte was hier een <strong>confounder</strong>: een derde speler die zich vermomde als een stuk van het snavel-effect. Precies wat gladheid deed bij de steentjes, en dezelfde les als de Simpson-paradox die je bij de correlatie-wolk al tegenkwam.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · hoeveel overlappen de twee?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · hoeveel overlappen de twee?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Analyze → Correlate → Bivariate</strong>, met <code>vinlengte</code> en <code>snavellengte</code>: <em>r</em> = .656. (Of getypt: <code>CORRELATIONS /VARIABLES=vinlengte snavellengte.</code>)</p>
</div>
</div>
<p><strong>Dat ene getal beslist alles in dit blok.</strong> Twee voorspellers die sterk samenhangen vertellen elkaars verhaal; de zwakste van de twee houdt dan niets eigens over. Hangen ze nauwelijks samen, dan kunnen ze allebei hun eigen bijdrage leveren — en dat ga je zo bij <em>Jouw beurt</em> zelf zien gebeuren.</p>
<p>Blijft er één ding jeuken. Als de vin zó dominant is, verklaart de snavel er dan écht niets meer bovenop? Dat kun je scherp krijgen door de twee modellen zélf tegen elkaar te laten toetsen. Zo’n toets heet een <strong>modelvergelijking</strong>, en met de twee blokken van zonet heb je hem al staan.</p>
<p>Wat je hier aan het doen bent, heeft trouwens een eigen naam. Telkens het model een stap groter maken en per stap kijken hoeveel er extra verklaard wordt van de verschillen in gewicht: dat heet een <strong>hiërarchische regressie</strong> (<em>hierarchical regression</em>). Meer is het niet; het woord klinkt zwaarder dan het werk.</p>
<p>En hier kun je hem twee kanten op draaien, want er zijn twee volgordes:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · wie voegt wat toe?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · wie voegt wat toe?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Je hebt hem al: <strong>R squared change</strong> onder <strong>Statistics…</strong> zet in <strong>Model Summary</strong> drie extra kolommen neer — <em>R Square Change</em>, <em>F Change</em> en <em>Sig. F Change</em>. Lees ze op de regel van blok 2, want die vergelijkt blok 2 mét blok 1.</p>
<ul>
<li>Wat voegt de <strong>vin</strong> toe, bovenop de snavel? Blok 1 <code>snavellengte</code>, blok 2 <code>vinlengte</code>: <em>R Square Change</em> .406, <em>F Change</em> 573.09, <em>df1</em> 1, <em>df2</em> 339, en in <em>Sig. F Change</em> een waarde die SPSS afdrukt als <strong>.000</strong>. Let op dat laatste: <strong>.000 is geen <em>p</em>-waarde maar een afronding</strong> — een kans is nooit precies nul. In een zin schrijf je hem als <em>p</em> &lt; .001.</li>
<li>En andersom: wat voegt de <strong>snavel</strong> toe, bovenop de vin? Draai de twee blokken om: <em>R Square Change</em> .001, <em>F Change</em> 1.36, <em>Sig. F Change</em> .244.</li>
</ul>
</div>
</div>
<p>Lees die twee naast elkaar, want dat is het hele blok in vier getallen.</p>
<p>De vin voegt, bovenop de snavel, <em>F</em>(1, 339) = 573.09, <em>p</em> &lt; .001 toe, en tilt de <em>R</em>² met .406 omhoog. De snavel voegt, bovenop de vin, <em>F</em>(1, 339) = 1.36, <em>p</em> = .24 toe: één duizendste <em>R</em>².</p>
<p>En herken die twee getallen — .406 en .001 stonden hierboven al in de tabel bij de partiële correlatie, in de kolom <em>uniek in R²</em>. Dat is geen toeval maar dezelfde som: de unieke bijdrage van een voorspeller aan de <em>R</em>², langs twee wegen uitgerekend. Merk ook op dat die <em>p</em> van .244 exact de <em>p</em> uit de coëfficiëntentabel is. Voor één voorspeller erbij zijn de modelvergelijking en de <em>t</em>-toets van die helling hetzelfde ding.</p>
<p>Nog één kolom uit <strong>Model Summary</strong>, want die is verraderlijker dan hij eruitziet:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · en wat doet de adjusted R²?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · en wat doet de adjusted R²?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Kijk in de tweede opzet (vin in blok 1, snavel erbij in blok 2) naar de kolom <em>Adjusted R Square</em> van beide blokken. Voluit gerekend is dat .75828 tegen .75854; de tabel rondt af, dus op het scherm scheelt het hooguit één laatste decimaal.</p>
</div>
</div>
<p>De gewone <em>R</em>² moest omhoog — die kan niet anders. De adjusted <em>R</em>² hoefde niet mee, en ging tóch een piepklein beetje omhoog: van .75828 naar .75854, twee tienduizendsten. Zet er een kolom pure ruis in plaats van de snavel in, dan zakt hij wél (nagemeten: van .75828 naar .75762). De adjusted <em>R</em>² doet dus zijn werk — maar zijn lat ligt véél lager dan die van de significantie. <strong>Een voorspeller die de adjusted <em>R</em>² niet laat zakken, heeft daarmee nog niets bewezen.</strong> De snavel haalde die lat, en is alsnog niet van nul te onderscheiden.</p>
<p>De les van dit blok, in drie regels:</p>
<ul>
<li>De <strong>schud-toets</strong> en de toetsen in de tabellen zeiden, elk met hun eigen meetlat: die 48.14 is echt, de vin draagt bij aan het gewicht — óók naast de snavel.</li>
<li>Het <strong>tweede model</strong> zei: van de “87 gram per millimeter snavel” bleef, met de vin ernaast, 6.05 over — en dat is niet van nul te onderscheiden.</li>
<li>De <strong>partiële correlatie</strong> zei waaróm: reken de vin weg en de band tussen gewicht en snavel zakt van .595 naar .063. De snavel had niets eigens.</li>
</ul>
<p><em>Echt</em> en <em>hoe groot</em> zijn dus twee verschillende vragen — en er is een derde: <em>van wie is het eigenlijk?</em> Een helling kan kraakhelder niet-toeval zijn en tóch grotendeels geleend, zolang je een medespeler buiten de deur houdt. Daarom vraag je bij elke regressie: wie zit er nog meer in dit verhaal, en wat gebeurt er met mijn getal als ik hem binnenlaat? Zou je het in één eerlijke zin opschrijven, dan niet “elke millimeter snavel is 87 gram”, maar: <em>bij gelijke vinlengte zegt de snavellengte niets meer over het gewicht — de 87 gram was de vin.</em></p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="twee-maten-die-elkaar-niet-in-de-weg-zitten" class="level2">
<h2 class="anchored" data-anchor-id="twee-maten-die-elkaar-niet-in-de-weg-zitten">Twee maten die elkaar niet in de weg zitten</h2>
<p><span class="begrippen">unieke bijdrage · overlap tussen voorspellers · partiële correlatie</span></p>
<p>Hierboven stierf de snavellengte naast de vin. Nu zet je diezelfde snavellengte naast een ándere maat — de <strong>snaveldiepte</strong> (<code>snaveldiepte</code>, in mm) — en dan loopt het heel anders af. Draai eerst de drie modellen, en beantwoord daarna de vragen. De laatste heet weer <strong>Z)</strong>: de aannames staan altijd achteraan.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · de drie modellen">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · de drie modellen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Draai <strong>Analyze → Regression → Linear</strong> drie keer, steeds met <code>gewicht</code> in <strong>Dependent</strong>:</p>
<ul>
<li><strong>model A</strong> — alleen <code>snavellengte</code> in <strong>Independent(s)</strong>;</li>
<li><strong>model B</strong> — alleen <code>snaveldiepte</code>;</li>
<li><strong>model C</strong> — allebei. Zet voor vraag h twee blokken op (<strong>Next</strong>), met <strong>R squared change</strong> aan: <code>snaveldiepte</code> in blok 1, <code>snavellengte</code> erbij in blok 2.</li>
</ul>
<p>Of, als je liever typt dan klikt:</p>
<pre><code>REGRESSION
  /STATISTICS COEFF R ANOVA CHANGE CI(95)
  /DEPENDENT gewicht
  /METHOD=ENTER snaveldiepte
  /METHOD=ENTER snavellengte.</code></pre>
</div>
</div>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoeveel gram per millimeter voorspelt model A, en hoeveel van het verschil in gewicht verklaart hij? <em>(rapporteer b en R²)</em></p>
<p><strong>b)</strong> Doe hetzelfde voor model B. Let op het teken — klopt dat met wat je zou verwachten? <em>(rapporteer b en R²)</em></p>
<p><strong>c)</strong> Toets nu model C als geheel. Schrijf de nulhypothese eerst voluit op. <em>(rapporteer R², F(df<sub>1</sub>, df<sub>2</sub>) en p)</em></p>
<p><strong>d)</strong> Wat gebeurt er met de helling van de snavellengte als de snaveldiepte ernaast komt te staan — en hoe verhoudt dat zich tot wat er in dit blok met diezelfde snavellengte naast de vinlengte gebeurde?</p>
<p><strong>e)</strong> Blijven ze allebei significant in model C? <em>(rapporteer per voorspeller b, SE, t, p en het 95%-interval)</em></p>
<p><strong>f)</strong> Reken de overlap uit: de correlatie tussen <code>snavellengte</code> en <code>snaveldiepte</code>. Vergelijk met de .656 van vin en snavel. Wat voorspelt dat ene getal over de uitkomst van vraag d?</p>
<p><strong>g)</strong> Reken de twee partiële correlaties uit, met het residuen-recept uit dit blok — of sneller: <strong>Analyze → Correlate → Partial</strong>. <em>(rapporteer beide)</em></p>
<p><strong>h)</strong> Hoeveel voegt de <strong>snavellengte</strong> uniek toe aan de <em>R</em>²? Draai de regressie met <code>snaveldiepte</code> in blok 1 en <code>snavellengte</code> in blok 2, en lees <em>F Change</em> op de regel van blok 2. <em>(rapporteer ΔR² en de F-toets)</em> — voor de snaveldiepte krijg je hem kado: Δ<em>R</em>² = .117, <em>F</em>(1, 339) = 74.76.</p>
<p><strong>i)</strong> Tel die twee unieke bijdragen bij elkaar op en vergelijk met de <em>R</em>² van model C. Ze tellen niet op. Waar is het verschil gebleven?</p>
<p><strong>Z)</strong> Mag je dit model eigenlijk wel gebruiken? Loop de aannames na: kijk naar de residuen (klik op <strong>Plots…</strong>, zet <code>*ZRESID</code> tegen <code>*ZPRED</code> uit voor gelijke spreiding en vink <strong>Normal probability plot</strong> aan voor de verdeling), en of elke pinguïn maar één keer meetelt.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <em>b</em> = 87.42 gram per millimeter, <em>R</em>² = .354.</p>
<p><strong>b)</strong> <em>b</em> = −191.64, <em>R</em>² = .223. Negatief, en dat wringt: over alle pinguïns heen lijkt een <em>diepere</em> snavel bij een <em>lichter</em> beest te horen. Onthoud dat, het komt bij de dummy-oefening en de ANCOVA terug.</p>
<p><strong>c)</strong> De nulhypothese: dit model — snavellengte en snaveldiepte samen — verklaart níéts van de verschillen in gewicht; de <em>R</em>² is in de populatie nul. Uitkomst: <em>R</em>² = .471, <em>F</em>(2, 339) = 150.82, <em>p</em> &lt; .001. Die mag dus de deur uit.</p>
<p><strong>d)</strong> Hij zakt, maar hij stort niet in: van 87.42 naar <strong>75.28</strong>. Vergelijk dat met wat de vin deed — dáár ging dezelfde helling van 87.42 naar 6.05. Naast de vin hield de snavellengte niets over; naast de snaveldiepte houdt hij ruim zesentachtig procent van zijn helling.</p>
<p><strong>e)</strong> Ja, allebei ruimschoots. Snavellengte: <em>b</em> = 75.28, <em>SE</em> = 5.97, <em>t</em>(339) = 12.61, <em>p</em> &lt; .001, 95% CI [63.54, 87.03]. Snaveldiepte: <em>b</em> = −142.72, <em>SE</em> = 16.51, <em>t</em>(339) = −8.65, <em>p</em> &lt; .001, 95% CI [−175.19, −110.25]. Geen van beide intervallen bevat nul.</p>
<p><strong>f)</strong> <em>r</em> = −.235, tegen .656 voor vin en snavel. Dát is het antwoord op vraag d. Twee voorspellers die elkaar nauwelijks overlappen kunnen allebei hun eigen verhaal vertellen; twee die sterk samenhangen vertellen elkaars verhaal, en dan houdt de zwakste niets eigens over.</p>
<p><strong>g)</strong> <em>r</em>(gewicht, snavellengte | snaveldiepte) = <strong>.565</strong> — nauwelijks lager dan de gewone .595. En <em>r</em>(gewicht, snaveldiepte | snavellengte) = <strong>−.425</strong>, tegen een gewone −.472. Vergelijk met de snavel naast de vin: dáár zakte .595 naar .063.</p>
<p><strong>h)</strong> Snavellengte uniek (snaveldiepte in blok 1, snavellengte erbij in blok 2): Δ<em>R</em>² = .248, <em>F</em>(1, 339) = 158.97, <em>p</em> &lt; .001. Snaveldiepte uniek (andersom): Δ<em>R</em>² = .117, <em>F</em>(1, 339) = 74.76, <em>p</em> &lt; .001. Allebei substantieel — en vergelijk dat nog één keer met de .001 van de snavel naast de vin.</p>
<p><strong>i)</strong> .248 + .117 = .365, terwijl <em>R</em>²(model C) = .471. Er ontbreekt .106. Dat is het <strong>gedeelde</strong> stuk: verschil in gewicht dat de twee samen verklaren, maar dat je aan geen van beide alleen kunt toeschrijven. Precies daarom telt zo’n opsplitsing niet netjes op, en precies daarom is “hoe belangrijk is deze voorspeller?” een lastigere vraag dan hij lijkt.</p>
<p><strong>Z)</strong> Ja, met de gebruikelijke slag om de arm. De residuen liggen in een vrijwel egale band om nul (geen trechter, dus gelijke spreiding is hier geen probleem) en volgen de rechte lijn in de QQ-plot redelijk. Elke pinguïn is één keer gewogen, dus de waarnemingen zijn onafhankelijk. En de twee voorspellers overlappen maar weinig (<em>r</em> = −.235), dus ze zitten elkaar niet in de weg bij het schatten.</p>
</div>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-het-op-als-een-onderzoeker" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-het-op-als-een-onderzoeker">Schrijf het op als een onderzoeker</h2>
<p><span class="begrippen">rapportagezin · <em>F</em>, <em>b</em> en <em>R</em>² · twee decimalen</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bij een meervoudige regressie is het boodschappenlijstje voor het eerst echt volgroeid: je rapporteert het model als geheel, dan wat de tweede voorspeller toevoegde, en dan de voorspellers apart. De eerste en de derde laag las je in de tabellen; de middelste kwam uit de modelvergelijking. Het klinkt als veel, maar het zijn gewone zinnen die elk één laag dragen. Zo:</p>
<blockquote class="blockquote">
<p>Om te onderzoeken of de snavellengte iets eigens bijdraagt aan het gewicht, voorspelden we bij 342 pinguïns het gewicht uit hun snavellengte en hun vinlengte. Het model als geheel verklaarde het grootste deel van de verschillen in gewicht, <em>R</em>² = .76, <em>F</em>(2, 339) = 536.63, <em>p</em> &lt; .001. Bij gelijke snavellengte ging elke millimeter langere vin samen met ruim achtenveertig gram meer gewicht, <em>b</em> = 48.14, <em>SE</em> = 2.01, <em>t</em>(339) = 23.94, <em>p</em> &lt; .001, 95% CI [44.19, 52.10]. De snavellengte droeg daarnaast niet significant bij aan het voorspellen van het gewicht, <em>b</em> = 6.05, <em>SE</em> = 5.18, <em>t</em>(339) = 1.17, <em>p</em> = .24, 95% CI [−4.14, 16.24]; bovenop de vinlengte voegde zij .001 aan de verklaarde variantie toe, <em>F</em>(1, 339) = 1.36, <em>p</em> = .24. De partiële correlatie tussen gewicht en snavellengte, gecontroleerd voor vinlengte, was <em>r</em> = .06, tegen een gewone correlatie van <em>r</em> = .60.</p>
</blockquote>
<p>Kijk wat er cursief staat en wat niet. De symbolen die zelf een waarde dragen leunen schuin — <em>R</em>², <em>F</em>, <em>p</em>, <em>b</em>, <em>SE</em>, <em>t</em> — en de gewone woorden staan rechtop. De letters CI staan ook rechtop, met een spatie vóór de haak: ze benoemen wat er tussen de haken staat en dragen zelf geen waarde. De getallen staan in de zin zelf op twee decimalen. De <em>p</em> is de uitzondering: die krijgt er drie zolang hij ónder de .10 ligt, en twee zodra hij erboven komt — vandaar <em>p</em> = .24 hierboven. In een uitleg of een antwoord mag een getal best een derde decimaal dragen als het verschil er anders af valt (een Δ<em>R</em>² van .001 bestaat niet op twee decimalen); in de rapportagezin houd je het strak. En een <em>p</em> die onder de .001 duikt schrijf je niet uit: niet <em>p</em> = .0004, maar <em>p</em> &lt; .001, zonder nul voor de punt. Alles staat in de verleden tijd, want je vertelt wat er gevónden werd, en de zinnen staan op eigen benen: wie ze uit dit blok tilt, weet nog steeds wie er gewogen werd, wat er voorspeld werd, en met welke medespeler vastgehouden.</p>
<p><strong>En let op hoe die tweede voorspeller wordt opgeschreven, want daar gaat het vaak mis.</strong> Er staat <em>p</em> = .24 — het getal zelf. Niet “n.s.”, niet “geen effect”, en al helemaal niet weggelaten. Een niet-significante uitkomst is een uitkomst: hij hoort er met zijn eigen getallen bij te staan, mét het interval, zodat je lezer zelf kan zien hoeveel er nog paste. Wie de snavel uit de zin laat omdat hij “niks deed”, vertelt niet wat er gevonden is maar wat er goed uitkwam.</p>
<p>Eén getal uit de tabellen laat je hier bewust thuis: de adjusted <em>R</em>². Niet omdat hij niets waard is — hij liet je net zien hoe laag zijn lat eigenlijk ligt — maar kijken en rapporteren zijn twee verschillende klussen. Het MVDA-werkboek van De Heus geeft een advies dat we overnemen: rapporteer alleen de <em>R</em>², en laat de adjusted weg — behalve wanneer je het model echt als voorspelformule op nieuwe gevallen gaat loslaten (zíjn voorbeeld: een selectieformule voor nieuwe piloten). Zolang jouw model geen volgende lichting pinguïns hoeft te voorspellen, is de adjusted <em>R</em>² een instrument om mee te kíjken, geen getal voor in de zin.</p>
<p>Jouw beurt: schrijf dezelfde lagen op voor het model uit <em>Jouw beurt</em> hierboven — snavellengte en snaveldiepte samen. Het model als geheel (<em>R</em>² = .47, <em>F</em>(2, 339) = 150.82, <em>p</em> &lt; .001) en dan allebei de voorspellers apart (<em>b</em> = 75.28, <em>SE</em> = 5.97, <em>t</em>(339) = 12.61, <em>p</em> &lt; .001, 95% CI [63.54, 87.03]; en <em>b</em> = −142.72, <em>SE</em> = 16.51, <em>t</em>(339) = −8.65, <em>p</em> &lt; .001, 95% CI [−175.19, −110.25]). Durf het minteken erin te zetten en het uit te schrijven: bij gelijke snavellengte hoort een diepere snavel bij een lichter beest. Hardop voorlezen mag.</p>
</div>
</div>
<div class="boekvorm" data-w="W8">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: één helling die instort zodra je een tweede voorspeller binnenlaat, de confounder die daarachter zat, en de partiële correlatie die het in één getal vangt.</p>
<p>In het boek: <strong>W8 — Meer dan één verschil</strong></p>
<p><em>Daar draait het niet om méér knoppen, maar om dezelfde vraag als bij die correlatie-wolk: wat blijft er van een verband over als je vasthoudt wie er nog meer meepraat?</em></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Palmer Penguins — Gorman, Williams &amp; Fraser (2014), Palmer Station Antarctica LTER; via het R-pakket <code>palmerpenguins</code> (CC0). Alle getallen in dit blok zijn op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Peter de Heus, <em>MVDA Exercise book 2025-2026</em>, Universiteit Leiden — het oefenboek waarmee tweedejaars psychologie daar multivariate data-analyse (MVDA) leren. Daar komt ook het rapporteer-advies over de adjusted <em>R</em>² in dit blok vandaan.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_cronbach_alpha.html" class="pagination-link" aria-label="Oefening 7.1 · Betrouwbaarheid en Cronbachs α">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_dummy_regressie.html" class="pagination-link" aria-label="Oefening 9.1 · Dummy-codering">
        <span class="nav-page-text">Oefening 9.1 · Dummy-codering</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>