<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 9.1 · Dummy-codering – SPSS-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_t_toets.html" rel="next">
<link href="../20_blokken/blok_meervoudige_regressie.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_dummy_regressie.html">H9 · Groepen zijn ook getallen</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_dummy_regressie.html">Oefening 9.1 · Dummy-codering</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">SPSS-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SPSS-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">H4 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie en partiële correlatie</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · ANOVA en η²</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.5 · ANCOVA: een groep én een getal</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in SPSS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Vierde beweging · Verschil onthechten</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Vierde beweging · Verschil onthechten</li><li class="breadcrumb-item"><a href="../20_blokken/blok_dummy_regressie.html">H9 · Groepen zijn ook getallen</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_dummy_regressie.html">Oefening 9.1 · Dummy-codering</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 9.1 · Dummy-codering</h1>
<p class="subtitle lead">Een groep als 0 en 1 · <em>dummy coding</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#een-voorspeller-waar-woorden-in-staan" id="toc-een-voorspeller-waar-woorden-in-staan">Een voorspeller waar woorden in staan</a></li>
  <li><a href="#maak-de-dummys-zelf-in-spss-is-dat-geen-omweg-maar-de-weg" id="toc-maak-de-dummys-zelf-in-spss-is-dat-geen-omweg-maar-de-weg">Maak de dummy’s zelf — in SPSS is dat geen omweg maar de weg</a></li>
  <li><a href="#wie-je-weglaat-bepaalt-wat-alle-andere-getallen-betekenen" id="toc-wie-je-weglaat-bepaalt-wat-alle-andere-getallen-betekenen">Wie je weglaat, bepaalt wat alle andere getallen betekenen</a></li>
  <li><a href="#van-gewicht-naar-snaveldiepte" id="toc-van-gewicht-naar-snaveldiepte">Van gewicht naar snaveldiepte</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="een-voorspeller-waar-woorden-in-staan" class="level2">
<h2 class="anchored" data-anchor-id="een-voorspeller-waar-woorden-in-staan">Een voorspeller waar woorden in staan</h2>
<p><span class="begrippen">groepslabel · voorspeller · regressielijn</span></p>
<p>Een regressielijn is een rekensom, en verder niets. Je stopt er een getal in en er komt een getal uit. Bij de twaalf steentjes stopte je karaat erin en kreeg je glans terug, en de helling vertelde wat één karaat erbij waard was in glans.</p>
<p>Kijk nu eens naar de kolom <code>soort</code> in het pinguïn-bestand.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Daar staan geen getallen in. Daar staat <em>Adelie</em>, <em>Chinstrap</em>, <em>Gentoo</em> — drie woorden. Je kunt er niet mee vermenigvuldigen, je kunt er geen helling van maken, en “één soort erbij” betekent niks.</p>
<p>En toch. Stop de soort in een model en er rolt gewoon een tabel met getallen uit. Geen foutmelding, geen gemopper. Er zijn ergens getallen vandaan gekomen die in het bestand niet staan.</p>
<p>Waar komen die vandaan? Trek even mee.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="maak-de-dummys-zelf-in-spss-is-dat-geen-omweg-maar-de-weg" class="level2">
<h2 class="anchored" data-anchor-id="maak-de-dummys-zelf-in-spss-is-dat-geen-omweg-maar-de-weg">Maak de dummy’s zelf — in SPSS is dat geen omweg maar de weg</h2>
<p><span class="begrippen">dummy · <em>k</em> − 1 · lineaire regressie</span></p>
<div class="spss callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ol type="1">
<li>Open <code>diamantjes.csv</code>. De kolom <code>D</code> staat er al: <strong>1</strong> voor een sterretje, <strong>0</strong> voor een golfje.</li>
<li>Kijk eerst of die kolom staat waar je denkt: <strong>Analyze → Descriptive Statistics → Crosstabs</strong>, <code>D</code> bij <strong>Row(s)</strong> en <code>merk</code> bij <strong>Column(s)</strong>. Je hoort de zes golfjes op 0 te zien staan en de zes sterretjes op 1.</li>
<li><strong>Analyze → Regression → Linear</strong>, <code>glans</code> bij <strong>Dependent</strong> en <code>D</code> bij <strong>Independent(s)</strong>. <strong>OK</strong>.</li>
</ol>
<p>In de tabel <em>Coefficients</em>: <strong>(Constant) 40</strong> en <strong>D 20</strong>. Dat eerste getal is het <strong>intercept</strong>; SPSS noemt het de <em>constante</em>.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<pre><code>CROSSTABS /TABLES = D BY merk.

REGRESSION
  /STATISTICS COEFF R ANOVA
  /DEPENDENT glans
  /METHOD = ENTER D.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Twee groepen, één kolom met nullen en enen: dat is een <strong>dummy</strong>. En kijk nu wat de twee getallen zeggen. Het intercept is 40, en dat is precies de gemiddelde glans van de golfjes. De helling is 20, en dat is precies wat er bij de sterretjes bovenop komt: 40 + 20 = 60, hun gemiddelde. Reken het na met <strong>Analyze → Compare Means → Means</strong>, <code>glans</code> bij <strong>Dependent List</strong> en <code>merk</code> bij <strong>Independent List</strong>.</p>
<p>Die kolom <code>D</code> hoef je trouwens niet cadeau te krijgen. <code>COMPUTE D2 = (merk = "sterretje").</code> maakt hem in één regel na — een uitspraak die waar of onwaar is, levert in SPSS een 1 of een 0 op.</p>
<p>Eén ding om nu al te zien, want je komt het in de volgende oefening tegen. Vraag je diezelfde vergelijking als <em>t</em>-toets op — <strong>Analyze → Compare Means → Independent-Samples T Test</strong>, met <code>golfje</code> als eerste groep — dan staat er <em>t</em>(10) = −1.73. Vraag je ’m als dummy-regressie op, dan staat er <em>t</em>(10) = 1.73, zonder min. Zelfde data, zelfde toets, gespiegeld teken. De <em>t</em>-toets rekent hier golfje mín sterretje; de dummy rekent sterretje mín golfje. Welke kant het op gaat hangt af van wie je als vertrekpunt neemt — en dáár gaat deze hele oefening over.</p>
<p>En de vraag die je nu wilt stellen: wélke van de twee schrijf je dan op? Allebei mag, zolang je er maar bij zegt welke kant je op gerekend hebt. Een min-teken zonder die zin erbij is niet fout maar onleesbaar; met die zin erbij is het antwoord af.</p>
<p><strong>Nu jij</strong> — dezelfde pinguïns die je kent, maar met een vraag die je nog niet aan ze gesteld hebt. Bij de steentjes waren er twee groepen en had je aan één dummy genoeg. Bij de pinguïns zijn het er drie.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · bouw twee dummy's voor drie soorten">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · bouw twee dummy’s voor drie soorten
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ol type="1">
<li>Open <code>penguins.csv</code> in SPSS: <strong>File → Open → Data</strong>, bestandstype op <strong>CSV</strong>.</li>
<li><strong>Transform → Compute Variable</strong>. Doelvariabele <code>adelie</code>, uitdrukking <code>soort = "Adelie"</code>. <strong>OK</strong>.</li>
<li>Nog een keer: doelvariabele <code>chinstrap</code>, uitdrukking <code>soort = "Chinstrap"</code>. De Gentoo’s laat je weg — drie soorten, twee dummy’s.</li>
<li>Kijk of ze staan waar je denkt dat ze staan: <strong>Analyze → Descriptive Statistics → Crosstabs</strong>, <code>adelie</code> bij <strong>Row(s)</strong> en <code>soort</code> bij <strong>Column(s)</strong>. Er horen 151 Adelies op 1 te staan en alle andere op 0.</li>
<li><strong>Analyze → Regression → Linear</strong>: <code>gewicht</code> bij <strong>Dependent</strong>, <code>adelie</code> <strong>en</strong> <code>chinstrap</code> bij <strong>Independent(s)</strong>. <strong>OK</strong>.</li>
</ol>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<pre><code>COMPUTE adelie    = (soort = "Adelie").
COMPUTE chinstrap = (soort = "Chinstrap").
EXECUTE.

CROSSTABS /TABLES = adelie BY soort.

REGRESSION
  /STATISTICS COEFF R ANOVA
  /DEPENDENT gewicht
  /METHOD = ENTER adelie chinstrap.</code></pre>
</div>
</div>
</div>
<p>In de tabel <em>Coefficients</em> staat nu:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Constant)</td>
<td>5076.02</td>
</tr>
<tr class="even">
<td>adelie</td>
<td>−1375.35</td>
</tr>
<tr class="odd">
<td>chinstrap</td>
<td>−1342.93</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="naslag">Die kruistabel is geen versiering. Een dummy die per ongeluk overal 0 is geeft geen foutmelding — hij geeft een model dat rustig doorrekent en nergens meer over gaat. Zet er dus altijd de kruistabel naast. En vergeet <code>EXECUTE.</code> niet: <code>COMPUTE</code> doet zonder dat regel niets. Meer daarover bij <a href="../90_basishandelingen.html#hercoderen">nieuwe variabelen maken en hercoderen</a>.</span></p>
<p>Nu de vragen. Ze staan los onder elkaar zodat je ze later kunt terugvinden; probeer ze eerst zelf, en klap daarna het antwoord open. Tussen haakjes staat telkens wat er in een compleet antwoord hoort — dan kun je je eigen antwoord nakijken zonder het onze te openen. De laatste heet met opzet <strong>Z)</strong> en niet l): dat is geen volgende stap maar de vraag die je bij élk model opnieuw stelt, en daarom staat hij achteraan. Z is de laatste letter van het alfabet, dus je ziet in één oogopslag dat er niets meer achter komt — en het blíjft Z, of het rijtje ervoor nu bij d) ophoudt of bij k).</p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Vragen bij model 1 · je eigen dummy's">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Vragen bij model 1 · je eigen dummy’s
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Hoeveel dummy’s heb je nodig voor drie soorten, welke soort heb je weggelaten, en hoe heet die groep? (het aantal, de soort, en de term)</p>
<p><strong>b)</strong> Wat zijn de nulhypothese en de alternatieve hypothese voor het model als geheel — en gaat je uitspraak over deze 342 pinguïns, of over alle pinguïns waar zij een steekproef uit zijn? (twee hele zinnen, met het woord <em>populatie</em> of <em>steekproef</em> erin)</p>
<p><strong>c)</strong> Kan die nulhypothese verworpen worden? (rapporteer <em>F</em>, <em>df</em> en <em>p</em>, en zeg wát je verwerpt)</p>
<p><strong>d)</strong> Hoeveel procent van het verschil in gewicht tussen deze pinguïns verklaart de soort? (rapporteer <em>R</em>², en zeg wat de rest is)</p>
<p><strong>e)</strong> Wat zijn de nulhypothese en de alternatieve hypothese voor de twee losse regressiegewichten — en waarin verschillen die van b)? (twee verschillen)</p>
<p><strong>f)</strong> Zijn de twee regressiegewichten, −1375.35 en −1342.93, significant? (rapporteer per gewicht <em>b</em>, <em>t</em>, <em>df</em> en <em>p</em>)</p>
<p><strong>g)</strong> Schrijf de geschatte regressievergelijking op. (met de namen van je eigen dummy’s erin)</p>
<p><strong>h)</strong> Welk getal in de tabel is het gemiddelde gewicht van de Gentoo’s — en welke schatter gebruik je daarvoor? (het getal, en hoe die schatter heet)</p>
<p><strong>i)</strong> Reken de andere twee groepsgemiddelden uit de vergelijking uit. (rekenmachine erbij, het zijn twee sommen)</p>
<p><strong>j)</strong> Drie soorten zijn drie paren om te vergelijken, maar je model geeft er maar twee. Welk paar mis je, hoe kom je aan dat verschil, en waarom zit er nog geen toets bij? (een getal in grammen, en één zin over die toets)</p>
<p><strong>k)</strong> Geef een inhoudelijke conclusie in niet meer dan vijf zinnen. (over pinguïns, niet over getallen)</p>
<p><strong>Z) Mag je alles hierboven geloven?</strong> Loop de aannames na:</p>
<ul>
<li>hoe ver lopen de spreidingen per soort uiteen?</li>
<li>telt elke pinguïn maar één keer mee?</li>
<li>liggen de residuen ongeveer symmetrisch?</li>
</ul>
<p>En dan de vraag die er altijd achteraan hoort: gaat er iets mis, welke antwoorden hierboven doe je dan over en welke mogen blijven staan?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Twee: altijd eentje minder dan het aantal groepen, <em>k</em> − 1. De Gentoo’s heb je weggelaten, dus Gentoo is de referentiecategorie.</p>
<p><strong>b)</strong> Over de <strong>populatie</strong>, niet over deze 342. Die heb je gewogen; hun gemiddelden kun je gewoon aflezen, dus daar valt niets aan te toetsen.</p>
<p>De nulhypothese: in de populatie pinguïns waar deze 342 een steekproef uit zijn, hangt de soort niet samen met het gewicht — beide regressiegewichten zijn daar nul.</p>
<p>De alternatieve hypothese: minstens één van die twee is niet nul, dus érgens hangt de soort wél met het gewicht samen.</p>
<p><strong>c)</strong> Ja: <em>F</em>(2, 339) = 343.63, <em>p</em> &lt; .001. Je vindt hem in de <em>ANOVA</em>-tabel onder je regressie. Wat je verwerpt is de nulhypothese dat de soort in de populatie niets met het gewicht te maken heeft. Wat je er níét mee weet, is wélke soorten van elkaar verschillen — daarvoor moet je naar de losse gewichten kijken, bij f) en j).</p>
<p><strong>d)</strong> <em>R</em>² = .67, dus 67%. De andere 33% is verschil in gewicht dat de soort níét verklaart; dat zit bínnen de soorten, tussen pinguïns van dezelfde soort. Je leest hem af bij <strong>R Square</strong> in de tabel <em>Model Summary</em>, waar SPSS <strong>.670</strong> afdrukt.</p>
<p><strong>e)</strong> Bij b) ging het over de twee gewichten samen, hier gaat het per gewicht apart. De nulhypothese voor de Adélie-dummy: in de populatie is het verschil in gewicht tussen Adélies en Gentoo’s nul; de alternatieve: dat verschil is niet nul. En hetzelfde nog eens voor de Chinstrap-dummy. Twee verschillen met b) dus: b) toetst ze in één keer en zegt alleen <em>of er ergens</em> iets zit, deze twee toetsen elk één verschil en zeggen ook <em>welk</em>.</p>
<p><strong>f)</strong> Ja, allebei. Adélies tegenover Gentoo’s: <em>b</em> = −1375.35 g, <em>t</em>(339) = −24.50, <em>p</em> &lt; .001. Chinstraps tegenover Gentoo’s: <em>b</em> = −1342.93 g, <em>t</em>(339) = −19.22, <em>p</em> &lt; .001. Ze staan in de tabel <em>Coefficients</em>: de gewichten in de kolom <strong>B</strong>, de rest in <strong>t</strong> en <strong>Sig.</strong></p>
<p><strong>g)</strong> <strong>gewicht = 5076.02 − 1375.35 × adelie − 1342.93 × chinstrap.</strong> De twee minnen zitten in de gewichten zelf, dus je mag ze ook als plus opschrijven met een negatief getal erachter — als de uitkomst maar hetzelfde is.</p>
<p><strong>h)</strong> 5076.02, de rij <strong>(Constant)</strong>, en de schatter die je daarvoor gebruikt is het <strong>intercept</strong>. Vul in de vergelijking bij <code>adelie</code> en <code>chinstrap</code> allebei een 0 in en er blijft niets over dan dat intercept — en een pinguïn die op allebei de dummy’s nul scoort ís een Gentoo.</p>
<p><strong>i)</strong> Adélie = 5076.02 − 1375.35 = 3700.67; Chinstrap = 5076.02 − 1342.93 = 3733.09. Kijk ze na:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · de drie gemiddelden">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · de drie gemiddelden
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Analyze → Compare Means → Means</strong>, <code>gewicht</code> bij <strong>Dependent List</strong> en <code>soort</code> bij <strong>Independent List</strong>: Adelie 3700.66, Chinstrap 3733.09, Gentoo 5076.02.</p>
</div>
</div>
<p>Jouw Adélie-som landt dus één honderdste te hoog. Dat is geen rekenfout van jou: de exacte waarden zijn 5076.016 en 1375.354, en SPSS rekent met álle decimalen door. Rond af aan het eind, nooit onderweg.</p>
<p><strong>j)</strong> Je mist <strong>Chinstrap tegenover Adélie</strong>. Je model meet álles af aan de Gentoo’s, dus die twee komen elkaar nergens tegen.</p>
<p>Het verschil krijg je door de gewichten van elkaar af te trekken: −1342.93 − (−1375.35) = 32.42 gram, de Chinstraps net iets zwaarder.</p>
<p>Maar een verschil is nog geen toets. Daarvoor heb je de standaardfout van dít verschil nodig, en die staat nergens in deze tabel — je krijgt hem pas als je de Adélies tot referentie maakt. Wil je alle drie de paren tegelijk, dan is daar een eigen gereedschap voor: de post-hoc-toets, in de oefening over de eenweg ANOVA.</p>
<p><strong>k)</strong> Bijvoorbeeld: welke soort een pinguïn is, hangt sterk samen met wat hij weegt — de soort verklaart 67% van het verschil in gewicht tussen deze 342 pinguïns, <em>F</em>(2, 339) = 343.63, <em>p</em> &lt; .001. Dat verschil zit vrijwel helemaal in de Gentoo’s: die wegen gemiddeld ruim 1300 gram meer dan de Adélies en ruim 1300 gram meer dan de Chinstraps. Adélies en Chinstraps ontlopen elkaar maar 32 gram. Een pinguïn wegen zegt dus veel over welke soort het is, zolang je alleen de Gentoo van de andere twee hoeft te onderscheiden.</p>
<p><strong>Z)</strong> Ja. Dezelfde <strong>Means</strong>-tabel geeft je onder <strong>Std. Deviation</strong> de spreiding per soort: 458.57, 384.34 en 504.12 gram. Grootste gedeeld door kleinste is 1.31, ruim onder de 2, dus gelijke spreiding is hier geen probleem. Elke pinguïn is één keer gewogen, dus de waarnemingen zijn onafhankelijk, en de residuen zijn vrijwel symmetrisch (scheefheid 0.18; dat begrip kwam langs in de oefening over de mediaan en de scheefheid).</p>
<p>Vuistregel voor die spreidingen: pas als de grootste meer dan twee keer de kleinste is, gaat gelijke spreiding echt knellen.</p>
<p><strong>En als het antwoord nee was geweest?</strong> Dan gaat niet alles hierboven overboord — en dát is waarom deze vraag achteraan mág staan.</p>
<ul>
<li><strong>Blijft staan:</strong> de gewichten bij f), g) en i). Dat zijn gewoon de verschillen tussen de groepsgemiddelden, en daar verandert geen aanname iets aan.</li>
<li><strong>Doe je over:</strong> de toets bij c), de <em>p</em>’s bij f), en je conclusie bij k). Die rusten alle drie op één gedeelde spreiding.</li>
</ul>
<p>Let op dat f) in allebei de rijtjes staat: de <em>b</em> van −1375.35 blijft, de <em>p</em> ernaast niet. Eén geval om het te zien — zouden de Gentoo’s twee keer zo wild spreiden als de Chinstraps, dan is die gedeelde spreiding te groot voor de Chinstraps en te klein voor de Gentoo’s, en staat er bij f) een <em>t</em> die niet klopt, terwijl die 1375.35 gram er nog steeds gewoon staat.</p>
</div>
</div>
</div>
<p>SPSS kan het ook zelf — niet in <strong>Regression</strong>, maar in het algemene lineaire model:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · en nu SPSS zelf">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · en nu SPSS zelf
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p><strong>Analyze → General Linear Model → Univariate</strong>: <code>gewicht</code> bij <strong>Dependent Variable</strong>, <code>soort</code> bij <strong>Fixed Factor(s)</strong>. Klik <strong>Options</strong> en vink <strong>Parameter estimates</strong> aan. <strong>OK</strong>.</p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<pre><code>UNIANOVA gewicht BY soort
  /PRINT = PARAMETER ETASQ.</code></pre>
</div>
</div>
</div>
<p>Kijk goed naar de tabel <em>Parameter Estimates</em>. Er staan drie soorten in, maar bij één ervan staat <strong>B = 0</strong> en verder niets — geen standaardfout, geen <em>t</em>. Dat is geen fout en geen afronding: dat is de referentiecategorie, die SPSS zelf gekozen heeft. Liet hij de Gentoo’s staan op nul, dan zie je je eigen −1375.35 en −1342.93 terug. Zette hij de Adélies op nul, dan staat er <strong>32.43</strong> en <strong>1375.35</strong>.</p>
</div>
</div>
<p>Andere getallen — en niet zomaar andere. Vijf nieuwe vragen, nu op dit model:</p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Vragen bij model 2 · de dummy's van SPSS">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Vragen bij model 2 · de dummy’s van SPSS
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Welke soort is nu de referentiecategorie, en waaraan zie je dat? (twee aanwijzingen)</p>
<p><strong>b)</strong> Bereken de drie gemiddelden opnieuw uit deze vergelijking — kom je op dezelfde drie uit? (rekenmachine erbij, weer twee sommen)</p>
<p><strong>c)</strong> Hoeveel procent van het verschil in gewicht tussen deze pinguïns verklaart de soort nu? (rapporteer <em>R</em>²)</p>
<p><strong>d)</strong> Eén getal staat in allebei de modellen en één is verdwenen — welk getal is dat, en waar is het gebleven?</p>
<p><strong>e)</strong> En het verschil dat je bij j) met de hand uitrekende: staat het hier, en zit er nu wél een toets bij? (rapporteer <em>b</em>, <em>t</em>, <em>df</em> en <em>p</em>)</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Antwoord — open na je eigen poging">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opgelet</span>Antwoord — open na je eigen poging
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Adélie. Het intercept is 3700.66 en dat is precies het Adélie-gemiddelde; bovendien is dat de rij waar <strong>B = 0</strong> staat en verder niets.</p>
<p><strong>b)</strong> Adélie = 3700.66; Chinstrap = 3700.66 + 32.43 = 3733.09; Gentoo = 3700.66 + 1375.35 = 5076.01 — terwijl het echte Gentoo-gemiddelde 5076.02 is. Dezelfde drie gemiddelden als in model 1, dezelfde afrondingskruimel, andere rij.</p>
<p><strong>c)</strong> <em>R</em>² = .67 — precies hetzelfde. En het <strong>partial eta squared</strong> dat de Univariate-tabel bij <code>soort</code> afdrukt is datzelfde getal: <strong>.670</strong>.</p>
<p><strong>d)</strong> De 1375.35 staat in allebei, daar met een min ervoor en hier zonder. De −1342.93 is weg en er staat 32.43 voor in de plaats, want dat verschil wordt nu afgemeten aan de Adélies in plaats van aan de Gentoo’s: 3733.09 − 3700.66 = 32.43.</p>
<p><strong>e)</strong> Ja, en dit is het paar dat model 1 je niet gaf: <em>b</em> = 32.43 g, <em>t</em>(339) = 0.48, <em>p</em> = .63. Niet significant — met deze data kun je Chinstraps en Adélies op gewicht niet uit elkaar houden. Merk op dat jouw aftreksom bij j) op 32.42 uitkwam en hier 32.43 staat: dat is dezelfde afrondingskruimel als bij b), want je trok twee getallen van elkaar af die al afgerond waren.</p>
<p><strong>En Z)?</strong> Die hoeft hier niet. Dit is hetzelfde model als hierboven, alleen vanaf een ander vertrekpunt, dus het draagt precies dezelfde aannames — en die heb je daar al nagelopen.</p>
</div>
</div>
</div>
<p>Twee modellen, dezelfde drie gemiddelden. Het zijn er dus geen twee — het is hetzelfde model, met een ander vertrekpunt.</p>
<p>En dan de derde gedaante. Draai dezelfde vraag als eenweg ANOVA:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · en nog een keer, nu als eenweg ANOVA">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · en nog een keer, nu als eenweg ANOVA
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p><strong>Analyze → Compare Means → One-Way ANOVA</strong>: <code>gewicht</code> bij <strong>Dependent List</strong> en <code>soort</code> bij <strong>Factor</strong>. <strong>OK</strong>.</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<pre><code>ONEWAY gewicht BY soort.</code></pre>
</div>
</div>
</div>
<p>Weer <strong><em>F</em>(2, 339) = 343.626</strong>, en dat is exact dezelfde <em>F</em> als in de <em>ANOVA</em>-tabel onder je regressie van daarnet.</p>
</div>
</div>
<p>Drie keer hetzelfde getal: op het scherm 343.626, en netjes op twee decimalen <em>F</em>(2, 339) = 343.63. Wat die <em>F</em> precies méét, daar gaat de ANOVA-oefening straks over; kijk er nu alleen naar dat je hem drie keer tegenkomt terwijl je drie verschillende dingen leek te doen.</p>
<p>En let op hoe die knop heet: <strong>One-Way ANOVA</strong>, en niet alleen “ANOVA”. SPSS zet het er zelf bij, en Ben doet dat ook:</p>
<blockquote class="blockquote">
<p><em>“Soort op gewicht doe je niet met ANOVA, maar met eenweg ANOVA. Ik zeg altijd: alles is regressie, en alles is ook analysis of variance — we doen niet anders. Dus noem het oneway of two way anova.”</em></p>
</blockquote>
<p>Dat is geen muggenzifterij. Als álles variantieanalyse is, zegt het woord “ANOVA” niets meer over wát je gedaan hebt; het aantal factoren is dan het enige dat je lezer nog iets vertelt. Hier heb je er één — <code>soort</code> — en dus is het een eenweg ANOVA. Bij twee factoren wordt het een tweeweg ANOVA, en dat is een ander gesprek.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="wie-je-weglaat-bepaalt-wat-alle-andere-getallen-betekenen" class="level2">
<h2 class="anchored" data-anchor-id="wie-je-weglaat-bepaalt-wat-alle-andere-getallen-betekenen">Wie je weglaat, bepaalt wat alle andere getallen betekenen</h2>
<p><span class="begrippen">referentiecategorie · <em>k</em> − 1 dummy’s · intercept</span></p>
<p>Eerst het tellen. Hoeveel dummy’s heb je nodig voor een groepsvariabele? <strong>Eentje minder dan het aantal groepen.</strong> Man en vrouw zijn twee groepen en dus één dummy; drie pinguïnsoorten zijn twee dummy’s. Statistici schrijven <em>k</em> − 1, met <em>k</em> voor het aantal groepen.</p>
<p>Waarom niet gewoon drie? Omdat de derde niets nieuws vertelt. Wie op <code>adelie</code> een 0 heeft staan en op <code>chinstrap</code> ook, is een Gentoo — dat weet je al, zonder ernaar te kijken. De weggelaten groep is de <strong>referentiecategorie</strong>, en die herken je hieraan: hij scoort nul op álle dummy’s.</p>
<p>En dan verdient hij dat woord ook echt, want alles wat er in de tabel staat wordt vanaf hem gemeten:</p>
<ul>
<li><strong>Het intercept is het gemiddelde van de referentiegroep.</strong> Vul in de vergelijking voor alle dummy’s een 0 in en er blijft niets over dan <em>b</em><sub>0</sub>.</li>
<li><strong>Elk regressiegewicht is het verschil met de referentiegroep</strong>, in de eenheid van de uitkomst. Hier dus in grammen.</li>
</ul>
<p>Daarmee wordt het verschil tussen je twee tabellen doodgewoon:</p>
<table class="caption-top table">
<caption>Het vetgedrukte getal is telkens het intercept — het gemiddelde van de groep die je wegliet. De rest zijn regressiegewichten, en elk daarvan is een verschil met dat intercept.</caption>
<thead>
<tr class="header">
<th>soort</th>
<th style="text-align: right;">gemiddeld gewicht</th>
<th style="text-align: right;">Gentoo weggelaten</th>
<th style="text-align: right;">Adélie weggelaten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adélie</td>
<td style="text-align: right;">3700.66 g</td>
<td style="text-align: right;">−1375.35</td>
<td style="text-align: right;"><strong>3700.66</strong></td>
</tr>
<tr class="even">
<td>Chinstrap</td>
<td style="text-align: right;">3733.09 g</td>
<td style="text-align: right;">−1342.93</td>
<td style="text-align: right;">32.43</td>
</tr>
<tr class="odd">
<td>Gentoo</td>
<td style="text-align: right;">5076.02 g</td>
<td style="text-align: right;"><strong>5076.02</strong></td>
<td style="text-align: right;">1375.35</td>
</tr>
</tbody>
</table>
<p>Lees de twee rechterkolommen van boven naar beneden. Het intercept verspringt van de onderste rij naar de bovenste, en alle andere getallen kantelen mee. Er is geen enkel feit over pinguïns veranderd; de drie gemiddelden staan er nog gewoon. Wat veranderde is vanaf wélk gemiddelde je de rest afmeet.</p>
<p><strong>Dus kies dat vertrekpunt met opzet, in plaats van het te laten gebeuren.</strong> Laat je het aan <strong>Univariate</strong> over, dan kiest SPSS; jij ziet pas achteraf in de tabel wie er op nul is gezet. Bij de handgemaakte route zeg je het zelf, en dat is meteen de kortste weg:</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · zeg zelf wie de referentie is">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · zeg zelf wie de referentie is
</div>
</div>
<div class="callout-body-container callout-body">
<p>Je zegt het door te kiezen wélke dummy’s je máákt. Wie geen eigen kolom krijgt, is de referentie.</p>
<ul>
<li>Gentoo als vertrekpunt? Maak <code>adelie</code> en <code>chinstrap</code> — dat deed je hierboven.</li>
<li>Adélie als vertrekpunt? Maak <code>chinstrap</code> en <code>gentoo</code>:</li>
</ul>
<pre><code>COMPUTE chinstrap = (soort = "Chinstrap").
COMPUTE gentoo    = (soort = "Gentoo").
EXECUTE.</code></pre>
</div>
</div>
<p>Wat je met de hand doet is dezelfde ingreep als wat <strong>Univariate</strong> achter de schermen doet: iemand moet het vertrekpunt zijn, en nu zeg jij wie.</p>
<p>Dat handwerk is trouwens geen achterhaalde omweg. In SPSS <strong>moet</strong> je de dummy’s zelf bouwen voor je ze in <strong>Regression</strong> kunt stoppen; daar is dit gewoon de weg. In R en JASP hoeft het niet, maar ook daar is het nog steeds de eerlijkste manier om te zien wat er gebeurt. Allebei goed — als je maar weet wie je weggelaten hebt.</p>
<p>Welke groep hoort het te zijn? Drie vuistregels, in die volgorde:</p>
<ul>
<li><strong>Is er een controlegroep, dan is dat ’m.</strong> Bij een controlegroep en twee behandelingen lees je de twee gewichten meteen als “wat de behandeling oplevert ten opzichte van niets doen”.</li>
<li><strong>Anders de grootste groep</strong>, zodat het intercept op de meeste waarnemingen rust.</li>
<li><strong>Nooit de meest bijzondere groep</strong>, want dan meet je alles af aan de uitzondering.</li>
</ul>
<p>Bij deze pinguïns is er geen controlegroep. De Gentoo is de uitschieter en de Adélie de gewone maat, en de Adélies zijn er bovendien de meeste: 151 van de 342. Vandaar dat wij in de rest van dit hoofdstuk de Adélies als referentie aanhouden.</p>
<p>En dan de aansluiting, want daar is dit hoofdstuk om begonnen. Kijk terug naar wat je gedaan hebt: je hebt drie groepen vergeleken, en er is geen nieuwe toets aan te pas gekomen. Je gebruikte de regressie die je al kende, met nullen en enen in plaats van karaat.</p>
<p>Dat is geen handigheidje dat toevallig ook werkt. De lineaire regressie, de eenweg ANOVA en straks de <em>t</em>-toets zijn één model met drie deuren, en twee van je getallen komen zo weer terug:</p>
<ul>
<li><strong>1375.35 gram</strong> tussen Gentoo’s en Adélies — dat is het verschil dat de <em>t</em>-toets in de volgende oefening onderzoekt.</li>
<li><strong><em>F</em>(2, 339) = 343.63</strong> — die kom je in de ANOVA-oefening weer tegen.</li>
</ul>
<p>Dezelfde getallen, andere jas.</p>
<p>De les van dit blok, in drie zinnen:</p>
<ul>
<li><strong>Een groep wordt een getal door hem in nullen en enen te hakken.</strong> Voor <em>k</em> groepen heb je <em>k</em> − 1 dummy’s nodig; de groep die je weglaat is de referentiecategorie.</li>
<li><strong>Het intercept is het gemiddelde van de referentiegroep, elk gewicht is een verschil daarmee.</strong> Ruil je de referentie om, dan kantelen alle getallen mee zonder dat er één feit verandert.</li>
<li><strong>Groepen vergelijken is regressie.</strong> De <em>t</em>-toets en de eenweg ANOVA zijn geen aparte machines; het is dezelfde som, anders opgeschreven.</li>
</ul>
<p>Zou je dit model in één eerlijke zin opschrijven, dan hóórt de referentiecategorie erin — laat je ’m weg, dan weet je lezer niet waar de getallen vandaan geteld zijn. De standaardfouten (<em>SE</em>) staan in de tabel <em>Coefficients</em>, in de kolom <strong>Std. Error</strong>, naast de <em>t</em>’s die je bij vraag f) al opzocht:</p>
<blockquote class="blockquote">
<p>Om te onderzoeken hoe het gewicht van pinguïns samenhangt met hun soort, voorspelden we hun gewicht uit twee dummyvariabelen (<em>N</em> = 342), met de Adélies als referentiecategorie. Samen verklaarden de twee dummy’s 67% van het verschil in gewicht tussen deze pinguïns, <em>R</em>² = .67, <em>F</em>(2, 339) = 343.63, <em>p</em> &lt; .001. Gentoo’s wogen gemiddeld meer dan Adélies (<em>b</em> = 1375.35 g, 95% CI [1264.91, 1485.80], <em>SE</em> = 56.15, <em>t</em>(339) = 24.50, <em>p</em> &lt; .001). Tussen Chinstraps en Adélies vonden we geen aanwijzing voor een verschil (<em>b</em> = 32.43 g, 95% CI [−100.37, 165.22], <em>SE</em> = 67.51, <em>t</em>(339) = 0.48, <em>p</em> = .63).</p>
</blockquote>
<p>Zo streng is de zin met opzet. Alleen de symbolen zijn cursief (<em>N</em>, <em>b</em>, <em>SE</em>, <em>t</em>, <em>p</em>, <em>R</em>², <em>F</em>), de gewone woorden staan rechtop, en de getallen staan op twee decimalen. Alles staat in de verleden tijd, want je vertelt wat je gevónden hebt. En de zin staat op eigen benen: wie hem uit dit blok tilt, weet nog steeds wie er gewogen zijn, hoeveel het er waren, en vanaf wie er geteld is. Elk getal dat een lezer nodig heeft om je na te rekenen, staat erin — dat is de lat.</p>
<p><strong>Waarom er staat wat er staat.</strong> Dit stuk hoort bij de les en niet bij de zin: wie de zin overschrijft, laat dit hier liggen. Maar je moet het één keer gezien hebben, want anders schrijf je die zin over zonder te weten waarom hij zo lang is.</p>
<ul>
<li><strong>De referentiecategorie staat erin</strong> omdat je lezer anders niet weet vanaf waar de 1375.35 geteld is. Met een andere soort als vertrekpunt was precies hetzelfde getal −1375.35 geweest.</li>
<li><strong><em>N</em> = 342 staat erin</strong> omdat <em>p</em> &lt; .001 zonder steekproefgrootte niets zegt over hoeveel bewijs er ligt.</li>
<li><strong>De <em>F</em> staat erin naast de <em>R</em>²</strong> omdat die twee een paar zijn: <em>R</em>² zegt hoevéél de soort verklaart, de <em>F</em> zegt of dat meer is dan toeval zou opleveren. Een percentage zonder toets is een getal zonder maat.</li>
<li><strong><em>R</em>² staat naast de significantie</strong> omdat significant “vrij zeker” betekent, en niet “groot” of “belangrijk”. De <em>p</em> zegt hoe zeker je bent dát de soort met het gewicht samenhangt; <em>R</em>² zegt hoeveel van het verschil in gewicht hij verklaart.</li>
<li><strong>En de Chinstrap blijft erin, juist omdat hij niet significant is.</strong> Laat je hem weg, dan rapporteer je alleen wat goed uitkwam — en ziet je lezer niet dat de soort het gewicht goed voorspelt voor de één en nauwelijks voor de ander.</li>
</ul>
<p>En let op wat er níét staat. Er staat niet dat Chinstraps en Adélies <em>nauwelijks verschillen</em>, want dat weten we niet. Kijk naar het interval: 95% CI [−100.37, 165.22]. Daar past een verschil van 165 gram in, en dat is bijna 4% van wat een pinguïn gemiddeld weegt. Niet-significant betekent hier “we hebben geen verschil kunnen aantonen”, niet “er is er geen”. Dat verschil tussen die twee zinnen is het interval, en daarom staat het erbij.</p>
<div class="kicker">
<p>jouw beurt</p>
</div>
</section>
<section id="van-gewicht-naar-snaveldiepte" class="level2">
<h2 class="anchored" data-anchor-id="van-gewicht-naar-snaveldiepte">Van gewicht naar snaveldiepte</h2>
<p><span class="begrippen">referentiecategorie zelf kiezen · dummy’s met de hand · teken van een gewicht</span></p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Jouw beurt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Jouw beurt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jouw beurt — dezelfde drie soorten, bekende data, een andere maat: <code>snaveldiepte</code>. Die kolom ken je uit de scatterplot-oefening, waar de soort de derde speler achter het min-teken bleek. Nu mag hij zelf de voorspeller zijn.</p>
<ol type="1">
<li><p><strong>Laat de Adélies weg.</strong> In SPSS bouw je de dummy’s zelf, en dus kies je het vertrekpunt zelf — dat is hier eerder winst dan werk. Maak twee nieuwe kolommen met <strong>Transform → Compute Variable</strong>: <code>chinstrap = (soort = "Chinstrap")</code> en <code>gentoo = (soort = "Gentoo")</code>. Ga dan naar <strong>Analyze → Regression → Linear</strong>, met <code>snaveldiepte</code> bij <strong>Dependent</strong> en die twee bij <strong>Independent(s)</strong>. Ter controle: in de kolom <strong>B</strong> staat 18.35 als constante, 0.07 bij <code>chinstrap</code> en <strong>−3.36</strong> bij <code>gentoo</code>, dan zit je goed. In de <strong>Sig.</strong>-kolom ernaast: onder .001 voor de Gentoo, .65 voor de Chinstrap. Kijk het eerst na met <strong>Analyze → Descriptive Statistics → Crosstabs</strong> of je kolommen staan waar je denkt — een dummy die overal 0 is geeft geen foutmelding, alleen een model dat nergens meer over gaat.</p></li>
<li><p><strong>Ruil het vertrekpunt om.</strong> Je kolommen <code>adelie</code> en <code>chinstrap</code> van eerder staan er nog: draai dezelfde regressie met díé twee. Ter controle: constante 14.98, en daarbovenop 3.36 en 3.44. Alle drie de gemiddelden komen weer terug, alleen vanaf een ander vertrekpunt.</p>
<p>Tel de eerste twee op en er staat 14.98 + 3.36 = 18.34, terwijl de Adélies 18.35 wegen. Dat is geen fout van jou: het programma rekent met alle decimalen en rondt pas aan het eind af. Dezelfde honderdste als bij de Adélie-som van vraag i) hierboven, die op 3700.67 landde terwijl het echte gemiddelde 3700.66 is.</p></li>
<li><p><strong>De denk-vraag: is “bijzonder” een eigenschap van de soort?</strong> Twee keer nu was het de Gentoo die eruit sprong — op gewicht 1375 gram bóven de rest, op snaveldiepte 3.36 millimeter eronder. Alleen de kant verschilt. Maar draai het nog één keer met <strong><code>snavellengte</code></strong> als <strong>Dependent</strong>, met <code>chinstrap</code> en <code>gentoo</code> als voorspellers. Ter controle: 10.04 en 8.71 — allebei fors, en dus ligt hier niet de Gentoo apart maar de <strong>Adélie</strong>.</p>
<p>De vuistregel hierboven zegt: nooit de meest bijzondere groep. Wie is dat hier dan? En let op wie wij in dit hoofdstuk als vertrekpunt gekozen hebben.</p></li>
</ol>
</div>
</div>
<div class="boekvorm" data-w="W9">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: een groepslabel dat een getal wordt, zodat de regressie die je al kent er zonder morren mee rekent — en de keuze wie het vertrekpunt is.</p>
<p>In het boek: <strong>W9 — Groepen zijn ook getallen</strong></p>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Voetnoten</h2>

<ol>
<li id="fn1"><p>Palmer Penguins — Gorman, Williams &amp; Fraser (2014), Palmer Station Antarctica LTER; via het R-pakket <code>palmerpenguins</code> (CC0). <code>penguins.csv</code>, 342 pinguïns. Alle getallen op die échte data nagerekend.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_meervoudige_regressie.html" class="pagination-link" aria-label="Oefening 8.1 · Meervoudige regressie en partiële correlatie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 8.1 · Meervoudige regressie en partiële correlatie</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_t_toets.html" class="pagination-link" aria-label="Oefening 9.2 · De t-toets">
        <span class="nav-page-text">Oefening 9.2 · De t-toets</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>