<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Oefening 4.2 · Enkelvoudige regressie – SPSS-oefenboek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../20_blokken/blok_residuen.html" rel="next">
<link href="../20_blokken/blok_correlatie_scatterplot.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48057d16311d9d91ed8b4f19d25c6006.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>


<link rel="stylesheet" href="../werkboek.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Tweede beweging · Verschillen koppelen</li><li class="breadcrumb-item"><a href="../20_blokken/blok_correlatie_scatterplot.html">H4 · Het rechthoekje</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_enkelvoudige_regressie.html">Oefening 4.2 · Enkelvoudige regressie</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">SPSS-oefenboek</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://countcamp.org/manuscript/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Terug naar het boek</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SPSS-oefenboek</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Eerste beweging · Verschil onder de loep</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">H0 · In den beginne</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.0 · Installeren &amp; instellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_voor_je_begint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 0.1 · Kijken naar de data</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">H1 · De gemiddelde slok</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_gemiddelde_spreiding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 1.1 · Het gemiddelde en de standaardafwijking</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">H2 · De vorm van de hoop</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediaan_scheefheid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 2.1 · Mediaan, kwartielen en scheefheid</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">H3 · De grabbelton geschud</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_steekproevenverdeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 3.1 · Steekproevenverdeling en standaardfout</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Tweede beweging · Verschillen koppelen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">H4 · Het rechthoekje</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_correlatie_scatterplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.1 · Correlatie en scatterplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_enkelvoudige_regressie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Oefening 4.2 · Enkelvoudige regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_residuen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 4.3 · De residuen bekijken</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Derde beweging · Verschil op de proef</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">H5 · Bestaat het echt?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_betrouwbaarheidsinterval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 5.1 · Het betrouwbaarheidsinterval</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">H6 · Hoe beslis je?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_p_waarde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.1 · De p-waarde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 6.2 · Power, type I en II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">H7 · Tien keer welnee</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_cronbach_alpha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 7.1 · Betrouwbaarheid en Cronbachs α</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Vierde beweging · Verschil onthechten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">H8 · Meer dan één verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_meervoudige_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 8.1 · Meervoudige regressie en confounding</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">H9 · Groepen zijn ook getallen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_dummy_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.1 · Dummy-codering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_t_toets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.2 · De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_effectgrootte_d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.3 · Effectgrootte: Cohens d</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 9.4 · ANOVA en η²</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">H10 · Verschil in verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.1 · Als de moderator een groep is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_interactie_continu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 10.2 · Als de moderator een getal is</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">H11 · Het doorgegeven verschil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_mediatie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 11.1 · Mediatie: direct en indirect</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Slot · Verschil dat buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">H12 · En hij buigt</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_odds_ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oefening 12.1 · Logistische regressie: odds en odds ratio</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Naast het boek · Schil</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../20_blokken/blok_kruistabel_chikwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schil · Kruistabel en χ²</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Naslag</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../90_basishandelingen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basishandelingen in SPSS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../91_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De datasets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false">
 <span class="menu-text">Schud-speeltjes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/h3_grabbel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De grabbelton (steekproef)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w4_schud_correlatie.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Correlatie schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_schud_verschil.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Het verschil schudden (t)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_p_planten.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De p geteld</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/s2_schud_tabel.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De tabel schudden (χ²)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w12_schud_odds.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">De odds schudden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../speeltjes/w6_trek_interval.html" class="sidebar-item-text sidebar-link" target="_blank">
 <span class="menu-text">Trek opnieuw (interval)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<p class="beweging">Tweede beweging · Verschillen koppelen</p>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Tweede beweging · Verschillen koppelen</li><li class="breadcrumb-item"><a href="../20_blokken/blok_correlatie_scatterplot.html">H4 · Het rechthoekje</a></li><li class="breadcrumb-item"><a href="../20_blokken/blok_enkelvoudige_regressie.html">Oefening 4.2 · Enkelvoudige regressie</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Oefening 4.2 · Enkelvoudige regressie</h1>
<p class="subtitle lead">Wie voorspelt wie, en wat dat kost · <em>simple linear regression</em></p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">In deze oefening</h2>
   
  <ul>
  <li><a href="#vijftig-gram-of-een-honderdste-millimeter" id="toc-vijftig-gram-of-een-honderdste-millimeter">Vijftig gram, of een honderdste millimeter?</a></li>
  <li><a href="#trek-de-lijn-in-spss" id="toc-trek-de-lijn-in-spss">Trek de lijn in SPSS</a></li>
  <li><a href="#is-die-49.69-echt-of-kan-toeval-hem-namaken" id="toc-is-die-49.69-echt-of-kan-toeval-hem-namaken">Is die 49.69 echt, of kan toeval hem namaken?</a></li>
  <li><a href="#wie-voorspelt-wie" id="toc-wie-voorspelt-wie">Wie voorspelt wie</a></li>
  <li><a href="#de-snavels-en-hoeveel-de-keuze-daar-uitmaakt" id="toc-de-snavels-en-hoeveel-de-keuze-daar-uitmaakt">De snavels, en hoeveel de keuze daar uitmaakt</a></li>
  <li><a href="#schrijf-de-lijn-op-als-een-onderzoeker" id="toc-schrijf-de-lijn-op-als-een-onderzoeker">Schrijf de lijn op als een onderzoeker</a></li>
  </ul>
</nav>
<div class="datastrook">
<p><strong>Data bij deze oefening</strong> — <a href="../10_data/penguins.csv" download="penguins.csv">penguins.csv</a> 342 pinguïns · <a href="../10_data/diamantjes.csv" download="diamantjes.csv">diamantjes.csv</a> de twaalf steentjes uit het boek · <a href="../91_datasets.html">wat elke kolom betekent</a></p>
</div>
<div class="kicker">
<p>prikkel</p>
</div>
<section id="vijftig-gram-of-een-honderdste-millimeter" class="level2">
<h2 class="anchored" data-anchor-id="vijftig-gram-of-een-honderdste-millimeter">Vijftig gram, of een honderdste millimeter?</h2>
<p><span class="begrippen">helling · eenheden · richting van de vraag</span></p>
<p>Dezelfde 342 pinguïns als in de vorige oefening, dezelfde twee kolommen: vinlengte in millimeters, gewicht in grammen. En nu twee getallen, allebei netjes uitgerekend, allebei op dezelfde data.</p>
<p>Vraag je hoe het gewicht meeloopt met de vinlengte, dan komt eruit: <strong>49.69 gram per millimeter</strong>. Een pinguïn met een millimeter meer vin weegt bijna vijftig gram meer.</p>
<p>Vraag je het andersom — hoe de vinlengte meeloopt met het gewicht — dan komt eruit: <strong>0.01528 millimeter per gram</strong>.</p>
<p>Twee getallen over hetzelfde stel beesten. En als ze hetzelfde zeiden, dan zou het ene het andere <strong>ondersteboven</strong> moeten zijn. Doe het even met ronde getallen: <em>vijftig gram per millimeter</em> is precies hetzelfde bericht als <em>een vijftigste millimeter per gram</em>, oftewel 0.02. Heen delen door, terug delen door — dezelfde verhouding, andere kant op gelezen.</p>
<p>Reken het dan maar na met de echte getallen: 1 / 0.01528 komt uit op <strong>65.45</strong>.</p>
<p>En 65.45 is niet 49.69. Er zit ruim vijftien gram per millimeter tussen, en dat gat is er niet in geslopen — het staat er omdat er onderweg iets besloten is. Bij de correlatie van de vorige oefening had je dat kunnen omdraaien zonder dat er iets gebeurde: de samenhang tussen snavellengte en snaveldiepte is hetzelfde getal, welke van de twee je ook vooropzet.</p>
<p>Hier niet. Trek even mee: we gaan uitzoeken wát er besloten wordt, wie het besluit neemt, en wat het kost.</p>
<div class="kicker">
<p>speel het</p>
</div>
</section>
<section id="trek-de-lijn-in-spss" class="level2">
<h2 class="anchored" data-anchor-id="trek-de-lijn-in-spss">Trek de lijn in SPSS</h2>
<p><span class="begrippen">regressielijn · intercept · helling · voorspelde waarde</span></p>
<p>Een lijn door een wolk — je hebt hem in de vorige oefening al zien liggen. Nu ga je hem lézen. Ben stelt daarvoor in de les een vraag die het meteen klein maakt: <em>als je aan iemand die het plaatje niet ziet moet vertellen hoe dat lijntje loopt, hoeveel dingen moet je dan zeggen?</em> Twee. Waar hij begint, en hoe schuin hij is. Meer heeft een rechte lijn niet.</p>
<p>Die twee hebben een naam. Het <strong>intercept</strong> (<em>b</em><sub>0</sub>) is waar de lijn de verticale as snijdt. De <strong>helling</strong> (<em>b</em><sub>1</sub>) is hoeveel de uitkomst verandert als de voorspeller één eenheid opschuift. In SPSS staan ze onder elkaar in de tabel <strong>Coefficients</strong>, in de kolom <em>B</em>: eerst de rij <code>(Constant)</code>, dan de rij met de naam van je voorspeller.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="Eerst zoals in het boek — de twaalf diamantjes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eerst zoals in het boek — de twaalf diamantjes
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ol type="1">
<li>Open <code>diamantjes.csv</code>.</li>
<li><strong>Analyze → Regression → Linear</strong>.</li>
<li>Sleep <code>glans</code> naar <strong>Dependent</strong> en <code>karaat</code> naar <strong>Independent(s)</strong>. <strong>OK</strong>.</li>
</ol>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<pre><code>REGRESSION
  /STATISTICS COEFF R ANOVA
  /DEPENDENT glans
  /METHOD=ENTER karaat.</code></pre>
</div>
</div>
</div>
<p>In <strong>Coefficients</strong> lees je in de kolom <em>B</em>: <code>(Constant)</code> −1.43 en <code>karaat</code> 32.14. In <strong>Model Summary</strong> staat <em>R Square</em> = .334 en <em>Std. Error of the Estimate</em> = 18.61.</p>
</div>
</div>
<p>En kijk nu meteen naar wat SPSS je daar liet doen. Je hebt <code>glans</code> in een vak gesleept dat <strong>Dependent</strong> heet, en <code>karaat</code> in een vak dat <strong>Independent</strong> heet. Dat waren twee verschillende vakken, en je moest kiezen. Die keuze is geen opmaak — hij ís waar deze oefening over gaat.</p>
<p>De lijn leest dus: glans = −1.43 + 32.14 × karaat. Een steentje van één karaat zwaarder glanst ruim tweeëndertig punten meer.</p>
<p><strong>Nu jij</strong> — bij de pinguïns, die je uit de vorige oefening al kent. Bekende beesten, nieuwe vraag: als je van een pinguïn alleen de vin kunt meten, wat gok je dan voor zijn gewicht?</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · trek eraan">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · trek eraan
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ol type="1">
<li>Open <code>penguins.csv</code>: <strong>File → Open → Data</strong>, bestandstype op <strong>CSV</strong>.</li>
<li><strong>Analyze → Regression → Linear</strong>.</li>
<li><code>gewicht</code> naar <strong>Dependent</strong>, <code>vinlengte</code> naar <strong>Independent(s)</strong>. <strong>OK</strong>.</li>
<li>Voor de wolk met de lijn erin: <strong>Graphs → Chart Builder → Scatter/Dot → Simple Scatter</strong>, en dubbelklik daarna in de output op het plaatje → <strong>Add Fit Line at Total</strong>.</li>
</ol>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<pre><code>REGRESSION
  /STATISTICS COEFF R ANOVA CI(95)
  /DEPENDENT gewicht
  /METHOD=ENTER vinlengte.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Daar staat hij: <strong>gewicht = −5780.83 + 49.69 × vinlengte</strong>. Elke millimeter vin erbij is bijna vijftig gram erbij, en <em>R</em>² = .76 zegt dat driekwart van het verschil in gewicht langs de vinlengte loopt. Dat is voor levende dieren veel. De <em>Std. Error of the Estimate</em> van 394.28 gram is hoe ver de lijn er gemiddeld naast zit.</p>
<p>En nu kun je iets wat je in de vorige oefening niet kon: <strong>een getal geven aan een pinguïn die je niet gewogen hebt.</strong> Vul een vinlengte in en de lijn spuugt een gewicht uit. Met de hand, want dit is optellen en vermenigvuldigen:</p>
<pre><code>−5780.83 + 49.69 × 200 = 4157.17 gram</code></pre>
<p>Reken je met de onafgeronde getallen die SPSS intern gebruikt, dan komt er 4156.28 uit — 0.89 gram verschil, en dat verschil is het afronden zelf. Onthoud dat, want straks doet afronden iets veel ergers.</p>
<p>Ben noemt dat in de les een <strong>machientje, een fabriek</strong>: er komt iets in, de fabriek vermenigvuldigt het met de helling, telt het intercept erbij op, en spuugt het uit. En let op waar je begint — je begint bij de vinlengte, en het gewicht rolt eruit. Niet andersom.</p>
<section id="doe-het-nu-expres-verkeerd" class="level3">
<h3 class="anchored" data-anchor-id="doe-het-nu-expres-verkeerd">Doe het nu expres verkeerd</h3>
<p>Want dat is de zet van deze oefening. Draai de twee variabelen om — sleep ze letterlijk in elkaars vak — en kijk wat er gebeurt.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · verwissel de twee vakken">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · verwissel de twee vakken
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<ol type="1">
<li>Zelfde analyse, maar nu <code>vinlengte</code> naar <strong>Dependent</strong> en <code>gewicht</code> naar <strong>Independent(s)</strong>.</li>
<li>Lees <strong>Coefficients</strong> opnieuw, en <strong>Model Summary</strong> erbij.</li>
</ol>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<pre><code>REGRESSION
  /STATISTICS COEFF R ANOVA
  /DEPENDENT vinlengte
  /METHOD=ENTER gewicht.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Er staat nu <code>(Constant)</code> 136.73 en <code>gewicht</code> .01528. Reken die helling ondersteboven — 1 / 0.01528 — en je krijgt <strong>65.45</strong>. Niet 49.69.</p>
<p>En let meteen op iets aan dat schermgetal. SPSS drukt de helling af als <code>.01528</code>, zonder nul ervoor. Die nul hoort daar wél te staan: een helling kan voorbij de 1 komen, en dan zegt die nul iets. SPSS laat hem overal weg, ook waar het fout is. Schrijf hem dus zelf terug: <strong>0.01528</strong>. Verderop bij de rapportage staat waarom dat bij <em>R Square</em> niet hoeft en hier wel.</p>
<p>Kijk tegelijk naar <strong>Model Summary</strong>: <em>R Square</em> is nog steeds .759, tot op de laatste decimaal. En vraag je via <strong>Analyze → Correlate → Bivariate</strong> de correlatie op, dan is die beide kanten op <em>r</em> = .87.</p>
<p>Die drie regels spreken elkaar schijnbaar tegen. De correlatie is beide kanten op hetzelfde getal. <em>R Square</em> is beide kanten op hetzelfde getal. En de <strong>lijn</strong> is het niet.</p>
<p>Doe hetzelfde op de diamantjes en het gebeurt weer: met <code>karaat</code> als <em>Dependent</em> komt er een helling van 0.01038 karaat per glanspunt uit — de nul er weer zelf bij — en één gedeeld door dat getal is ruim 96 — terwijl de lijn van glans op karaat 32.14 zei. Geen toeval dus, en geen eigenaardigheid van pinguïns.</p>
<div class="kicker">
<p>schud het</p>
</div>
</section>
</section>
<section id="is-die-49.69-echt-of-kan-toeval-hem-namaken" class="level2">
<h2 class="anchored" data-anchor-id="is-die-49.69-echt-of-kan-toeval-hem-namaken">Is die 49.69 echt, of kan toeval hem namaken?</h2>
<p><span class="begrippen">schudden · loskoppelen · duizend werelden rond nul</span></p>
<p>Voor we uitzoeken wát er besloten is, eerst de vraag die altijd eerst komt: is die helling er wel? Bijna vijftig gram per millimeter <em>klinkt</em> als veel, maar een getal klinkt nergens naar tot je weet hoe groot een gewone wiebel is.</p>
<p>Dus schudden we. Je laat de vinlengtes staan waar ze staan en hutselt de gewichten erlangs — het gewicht van de ene pinguïn verhuist naar de vin van een andere.</p>
<p>Dat husselen is de hele truc, en het loont om er even bij stil te staan: je <strong>koppelt het gewicht los van zijn eigen vin</strong>. Je haalt met eigen handen weg dat een bepaalde vinlengte en een bepaald gewicht bij hetzelfde dier hoorden. In zo’n losgekoppelde wereld kán er geen echte helling meer zijn — en dus is elke helling die je er dan tóch nog in meet, per definitie puur toeval.</p>
<p><strong>En hier moet ik eerlijk zijn: dat husselen is geen knop in SPSS.</strong> SPSS rekent één keurige uitkomst uit; duizend keer opnieuw hutselen en kijken is werk voor code. Maar voor déze zet hoef je nergens heen — het schud-speeltje van de vorige oefening doet precies wat hier nodig is:</p>
<p><a href="../speeltjes/w4_schud_correlatie.html" target="_blank">▶ Zie het dansen: het schud-speeltje</a></p>
<div class="callout callout-style-default callout-note callout-titled" title="Waarom het correlatie-speeltje hier de helling schudt">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Waarom het correlatie-speeltje hier de helling schudt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dat speeltje schudt de <em>correlatie</em>, niet de helling — en dat mag, want onder schudden zijn het hetzelfde. Husselen verandert niets aan de spreiding van de vinlengtes en niets aan die van de gewichten; alleen wie bij wie hoort verandert. Omdat <em>b</em><sub>1</sub> = <em>r</em> · <em>S<sub>y</sub></em>/<em>S<sub>x</sub></em>, en die breuk dus vastligt, is de dans van de helling exact de dans van <em>r</em> — alleen met een andere maatverdeling op de as. Nagerekend over duizend geschudde werelden: het verschil tussen beide is 3 × 10<sup>−14</sup>, oftewel machineruis.</p>
</div>
</div>
<p>Wat je ziet: <strong>duizend werelden die dansen rond nul.</strong> Rond nul, want in elke geschudde wereld is de band tussen vin en gewicht doorgeknipt, en een lijn door een wolk zonder samenhang ligt plat. Toch landt hij nooit precies op nul: negentig procent van de losgekoppelde werelden ligt tussen −5.21 en 4.95 gram per millimeter, en de wildste haalde 10.90. En dan de echte helling van 49.69 — ruim vier keer voorbij de wildste. <strong>Geen enkele</strong> van de duizend kwam in de buurt. Dat is geen <em>p</em>-waarde die je moet geloven, maar een <strong>afstand die je zíet</strong>.</p>
<p>En er is nog een tweede vraag, die je alleen in dit blok kunt stellen: wat doen die <strong>twee lijnen</strong> in een geschudde wereld — komen ze dichter bij elkaar, of gaan ze verder uit elkaar? Wie dat zelf wil narekenen slaat het <strong>R-broertje</strong> open bij deze oefening; daar is het vijf regels code. De uitkomst: bij de echte pinguïns schelen de twee lijnen een factor 1.32, in een geschudde wereld doorgaans <strong>735</strong>. Knip het verband door en de twee lijnen staan bijna haaks op elkaar; laat het verband intact en ze kruipen naar elkaar toe. Hoe verder ze uit elkaar liggen, hoe minder de een over de ander te zeggen heeft — en dat is geen beeldspraak, zoals je zo ziet.</p>
<div class="kicker">
<p>snap het</p>
</div>
</section>
<section id="wie-voorspelt-wie" class="level2">
<h2 class="anchored" data-anchor-id="wie-voorspelt-wie">Wie voorspelt wie</h2>
<p><span class="begrippen">afhankelijke variabele · onafhankelijke variabele · lege adres · centreren</span></p>
<p>Nu de namen, en pas nu — je hebt het verschijnsel al in je handen gehad. Sterker nog: SPSS heeft je de vraag letterlijk gesteld, en jij hebt hem beantwoord met je muis.</p>
<p>De variabele die je invult heet de <strong>onafhankelijke variabele</strong>, ook wel de <strong>voorspeller</strong>; in SPSS is dat het vak <strong>Independent(s)</strong>. De variabele die eruit rolt heet de <strong>afhankelijke variabele</strong>, ook wel de <strong>uitkomst</strong>; dat vak heet in SPSS dan ook gewoon <strong>Dependent</strong>. Ben zegt erbij: <em>x is het begin — zie dat als oorzaak, ook al mag je dat nooit zo noemen — en y is het gevolg.</em> Die twee halve zinnen horen bij elkaar. De pijl zit in je hoofd en in je vraag, niet in de data.</p>
<p>Want dat is wat de omdraai-proef liet zien. De correlatie kon je omdraaien zonder dat er iets veranderde: <em>r</em> = .87 heen, <em>r</em> = .87 terug. Die maat is <strong>symmetrisch</strong> — hij kent geen richting, dus hij dwingt je ook nergens toe. Een regressielijn is dat niet. Door <code>gewicht</code> in het <em>Dependent</em>-vak te slepen heb je gezegd: <em>de vinlengte weet ik, het gewicht wil ik weten.</em> Sleep je ze andersom, dan stel je een andere vraag, en een andere vraag geeft een ander antwoord.</p>
<p>En dan de vraag die vanzelf komt: welke van de twee lijnen is nou de goeie? Geen van beide, en allebei. Wil je het gewicht schatten van een pinguïn waarvan je de vin gemeten hebt, dan is 49.69 de goeie. Wil je de vin schatten van een pinguïn die op de weegschaal staat, dan is 0.01528 de goeie. Er is geen derde lijn die “het echte verband” is en waar deze twee benaderingen van zijn.</p>
<section id="de-twee-hellingen-weten-samen-precies-hoe-goed-de-lijn-is" class="level3">
<h3 class="anchored" data-anchor-id="de-twee-hellingen-weten-samen-precies-hoe-goed-de-lijn-is">De twee hellingen weten samen precies hoe goed de lijn is</h3>
<p>En nu iets wat je zelf kunt doen, met twee getallen die al op deze bladzij staan. Je hebt de helling heen (49.69) en de helling terug (0.01528). Vermenigvuldig ze met elkaar: 49.69 × 0.01528 = <strong>0.759</strong>, oftewel .76.</p>
<p>Dat is <em>R</em>². Niet ongeveer — dat is ’m.</p>
<p>Doe het nog twee keer, op de andere modellen die je nu hebt liggen:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>lijn</th>
<th style="text-align: right;">helling heen</th>
<th style="text-align: right;">helling terug</th>
<th style="text-align: right;">die twee maal elkaar</th>
<th style="text-align: right;"><em>R</em>²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gewicht op vinlengte</td>
<td style="text-align: right;">49.69</td>
<td style="text-align: right;">0.01528</td>
<td style="text-align: right;">.76</td>
<td style="text-align: right;">.76</td>
</tr>
<tr class="even">
<td>glans op karaat</td>
<td style="text-align: right;">32.14</td>
<td style="text-align: right;">0.01038</td>
<td style="text-align: right;">.33</td>
<td style="text-align: right;">.33</td>
</tr>
<tr class="odd">
<td>snaveldiepte op snavellengte</td>
<td style="text-align: right;">−0.0850</td>
<td style="text-align: right;">−0.6498</td>
<td style="text-align: right;">.06</td>
<td style="text-align: right;">.06</td>
</tr>
</tbody>
</table>
<p>Drie keer raak. En het is geen toeval: het volgt uit de brug die het boek in dit hoofdstuk legt. Heen is de helling <em>r</em> · <em>S<sub>y</sub></em>/<em>S<sub>x</sub></em>, terug is <em>r</em> · <em>S<sub>x</sub></em>/<em>S<sub>y</sub></em> — dezelfde <em>r</em>, en de twee spreidingen precies omgekeerd. Vermenigvuldig ze en de spreidingen vallen tegen elkaar weg. Er blijft <em>r</em> × <em>r</em> over, en dat is <em>R</em>².</p>
<p><strong>En daarmee weet je ook waaróm die twee lijnen uit elkaar liggen zoals ze doen.</strong> Deel de omgekeerde helling door de heen-helling — 65.45 gedeeld door 49.69 — en je krijgt 1.32. Bij de diamantjes komt daar 3.00 uit, bij de snavels 18.10. Dat is telkens <strong>één gedeeld door <em>R</em>²</strong>: hoe kleiner het deel dat de lijn dekt, hoe verder de twee richtingen uiteen gaan liggen.</p>
<p>Daar zit de eigenlijke les van dit blok in. <strong>Hoe sterker het verband, hoe minder je keuze uitmaakt.</strong> Bij de pinguïns dekt de lijn driekwart van het verschil, en dan schelen de twee richtingen maar een derde. Bij de snavels dekt hij ruim vijf procent, en dan schelen ze een factor achttien. Zou <em>R</em>² ooit precies 1 zijn, dan vallen de twee lijnen samen en is er niets meer te kiezen — maar dan liggen alle punten ook exact op één lijn en heb je geen statistiek meer nodig. Kiezen moet je juist dáár waar het rommelig is.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Die laatste stap haal je uit de hellingen, niet uit de tabel">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Die laatste stap haal je uit de hellingen, niet uit de tabel
</div>
</div>
<div class="callout-body-container callout-body">
<p>Probeer 1 / <em>R</em>² maar eens met de getallen uit de tabel hierboven, en kijk wat er gebeurt. Neem de snavels: daar staat <em>R</em>² = .06, en één gedeeld door .06 is <strong>16.67</strong> — terwijl er 18.10 hoort te staan. Bijna anderhalf ernaast. Bij de diamantjes gaat hetzelfde mis, kleiner: 1 / .33 is 3.03 en niet 3.00.</p>
<p>Het afgeronde getal is te grof om de déling nog te dragen. Bij de vermenigvuldiging gebeurt dat niet — 32.14 × 0.01038 geeft gewoon .33, en −0.0850 × −0.6498 geeft .06. Vandaar dat dit blok de proef op de vermenigvuldiging legt en niet op de deling: een gelijkheid die alleen overeind blijft bij ongeronde getallen, is er een die je in een oefening niet moet opgeven.</p>
<p>Dat is dezelfde scheefte als die 0.89 gram van daarnet, maar dan een stuk duurder. Wil je 18.10 zelf zien, deel dan de hellingen (1 / −0.6498 gedeeld door −0.0850) en niet de <em>R</em>².</p>
</div>
</div>
</section>
<section id="het-lege-adres" class="level3">
<h3 class="anchored" data-anchor-id="het-lege-adres">Het lege adres</h3>
<p>Kijk nog eens naar de rij <code>(Constant)</code> van de pinguïnlijn: <strong>−5780.83</strong>. Neem dat letterlijk. Een pinguïn met een vin van nul millimeter weegt volgens deze lijn min 5.8 kilo.</p>
<p>Dat is geen rekenfout en geen slechte lijn. Het is een <strong>adres waar niemand woont</strong> — en hier zelfs een adres dat niet kán bestaan. De kortste vin in dit bestand is 172 millimeter, de langste 231. Nul ligt honderdzeventig millimeter buiten alles wat er ooit gemeten is; de lijn is daar netjes doorgetrokken, maar niemand heeft er ooit gekeken.</p>
<p>Ben zegt daarover: <em>het intercept is altijd te interpreteren als de voorspelling voor iemand die nul scoort op de voorspeller. Dat is altijd waar. Alleen de vraag is: wat betekent die nul?</em> Hier betekent nul: een pinguïn zonder vin. Dus is het intercept waar én waardeloos, tegelijk.</p>
<p>Er is één handeling die dat repareert, en meer dan een aftreksom is het niet. <strong>Centreren</strong>: trek van elke vinlengte het gemiddelde af, zodat nul niet meer “geen vin” betekent maar “een gemiddelde vin”.</p>
<div class="spss callout callout-style-default callout-note callout-titled" title="In SPSS · centreer de voorspeller">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>In SPSS · centreer de voorspeller
</div>
</div>
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Via het menu</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Via syntax</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<ol type="1">
<li>Vraag eerst het gemiddelde op: <strong>Analyze → Descriptive Statistics → Descriptives</strong>, <code>vinlengte</code> erin. Er staat <strong>200.92</strong>.</li>
<li><strong>Transform → Compute Variable</strong>. Doelvariabele <code>vin_gecentreerd</code>, uitdrukking <code>vinlengte - 200.92</code>. <strong>OK</strong>.</li>
<li>Draai de regressie opnieuw, met <code>gewicht</code> als <strong>Dependent</strong> en <code>vin_gecentreerd</code> als <strong>Independent</strong>.</li>
</ol>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<pre><code>DESCRIPTIVES VARIABLES=vinlengte
  /STATISTICS=MEAN.

COMPUTE vin_gecentreerd = vinlengte - 200.92.
EXECUTE.

REGRESSION
  /STATISTICS COEFF R ANOVA
  /DEPENDENT gewicht
  /METHOD=ENTER vin_gecentreerd.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Kijk wat daar gebeurt. Het intercept is nu <strong>4201.75</strong>, en dat is tot op de cent het gemiddelde gewicht van alle 342 pinguïns — vraag het maar na met <strong>Descriptives</strong>.</p>
<p>Dat is geen gelukje. Een regressielijn gaat altijd door één vast punt: het kruispunt van de twee gemiddelden — gemiddelde vin, gemiddeld gewicht. Verschuif je de nul naar de gemiddelde vin, dan schuift dat kruispunt precies op de verticale as, en dus lees je daar het gemiddelde gewicht af. Gemiddelde erin, gemiddelde eruit.</p>
<p>Het adres is bewoond geraakt: waar eerst een onmogelijk dier stond, staat nu de doorsnee-pinguïn. De helling is niet bewogen (nog steeds 49.69), <em>R Square</em> is niet bewogen (nog steeds .759), geen enkele voorspelling is bewogen — je hebt alleen de nul verschoven naar een plek waar iemand woont.</p>
<p>Dat is alles wat centreren doet, en in dit boek kom je het nog twee keer tegen: bij de meervoudige regressie als handeling, en bij de interactie als vaste gewoonte. Hier is het genoeg om het één keer te hebben zien gebeuren.</p>
</section>
<section id="eén-woord-en-zo-meteen-twee-betekenissen" class="level3">
<h3 class="anchored" data-anchor-id="eén-woord-en-zo-meteen-twee-betekenissen">Eén woord, en zo meteen twee betekenissen</h3>
<p>Nog even dit, want je loopt er in de volgende oefening tegenaan. Je hebt hier geleerd dat de voorspeller de <strong>onafhankelijke variabele</strong> heet. In de oefening hierna staat dat de residuen <strong>onafhankelijk</strong> moeten zijn — en dat is iets heel anders. Daar gaat het niet over een variabele maar over je <em>rijen</em>: geeft elke regel in je tabel informatie die niet al ergens anders staat, of meet je dezelfde persoon of dezelfde plek twee keer?</p>
<p>Hetzelfde woord, twee betekenissen, twee oefeningen uit elkaar. Zet het hier vast, dan hoef je straks niet te twijfelen.</p>
<p>En dan het stuk dat deze lijn nog schuldig is. Je hebt hem getrokken, gelezen en omgedraaid — maar je hebt nog nergens gekeken hoe ver hij er per pinguïn naast zit, en of hij er overal even ver naast zit. Dat is de volgende oefening.</p>
<div class="kicker">
<p>eindopdracht</p>
</div>
</section>
</section>
<section id="de-snavels-en-hoeveel-de-keuze-daar-uitmaakt" class="level2">
<h2 class="anchored" data-anchor-id="de-snavels-en-hoeveel-de-keuze-daar-uitmaakt">De snavels, en hoeveel de keuze daar uitmaakt</h2>
<p><span class="begrippen">omdraai-proef · uiteenval · eenheden benoemen</span></p>
<div class="opgave callout callout-style-default callout-note callout-titled" title="Eindopdracht">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Eindopdracht
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jouw beurt — terug naar de snavels uit de vorige oefening. Bekende data, nieuwe vraag: daar bekeek je de sámenhang, nu ga je een van de twee voorspellen uit de andere. En je weet al iets wat je scherp houdt: dat min-teken tussen snavellengte en snaveldiepte was een soorteffect. Dat blijft zo; we gebruiken deze twee hier omdat het verband zwák is, en juist bij een zwak verband is te zien wat kiezen kost.</p>
<ol type="1">
<li><p><strong>Trek beide lijnen.</strong> Eerst <code>snaveldiepte</code> als <strong>Dependent</strong> met <code>snavellengte</code> als <strong>Independent</strong>, dan de twee vakken verwisseld. Ter controle: de eerste geeft <strong>20.89 − 0.0850 × snavellengte</strong>, de tweede <strong>55.07 − 0.6498 × snaveldiepte</strong>. Schrijf van allebei de helling op mét zijn eenheid — millimeter diepte per millimeter lengte, en millimeter lengte per millimeter diepte. Zeg hardop wat er staat.</p></li>
<li><p><strong>Doe de proef met de vermenigvuldiging.</strong> Vermenigvuldig de twee hellingen met elkaar: −0.0850 × −0.6498. Ter controle: er komt .06 uit, en dat is de <em>R</em>² van dit model. Reken daarna ook 1 / −0.6498 uit en leg het naast −0.0850 — hoeveel schelen die twee?</p></li>
<li><p><strong>Leg de twee naast elkaar.</strong> Bij vin en gewicht schelen de twee lijnen een factor 1.32, hier 18.10. Formuleer in één zin waarom het bij de snavels zoveel meer uitmaakt welke van de twee je vooropzet — en gebruik het woord <em>R</em>² in die zin.</p></li>
<li><p><strong>Het lege adres.</strong> Het intercept van de eerste lijn is 20.89: een pinguïn met een snavel van nul millimeter lang heeft een snavel van 20.89 millimeter diep. Centreer de snavellengte (het gemiddelde is 43.92) en kijk wat het intercept wordt. Ter controle: 17.15. Vraag daarna het gemiddelde van <code>snaveldiepte</code> op. Herken je wat er gebeurde?</p></li>
<li><p><strong>De denk-vraag.</strong> Stel dat je van een dataset weet dat <em>R</em>² = 1 — alle punten liggen precies op één lijn. Wat gebeurt er dan met de omdraai-proef, en wat zegt dat over wanneer de keuze tussen voorspeller en uitkomst er wél toe doet?</p></li>
</ol>
</div>
</div>
<div class="kicker">
<p>rapportage</p>
</div>
</section>
<section id="schrijf-de-lijn-op-als-een-onderzoeker" class="level2">
<h2 class="anchored" data-anchor-id="schrijf-de-lijn-op-als-een-onderzoeker">Schrijf de lijn op als een onderzoeker</h2>
<p><span class="begrippen">rapportage van een regressie · APA-notatie · betrouwbaarheidsinterval</span></p>
<div class="apa callout callout-style-default callout-note callout-titled" title="Rapportage">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Opmerking</span>Rapportage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bij het gemiddelde was het een boodschappenlijstje van twee getallen; bij de correlatie kwam er één getal bij. Een regressiezin is dezelfde lijst, iets langer: wát je voorspelde, uit wát, bij hoeveel beesten, hoe steil, hoe zeker, en hoeveel het dekt. De standaardfout staat in <strong>Coefficients</strong> onder <em>Std. Error</em>; het interval krijg je met <strong>Statistics → Confidence intervals</strong>, of in syntax met <code>CI(95)</code> achter <code>/STATISTICS</code>.</p>
<blockquote class="blockquote">
<p>We voorspelden het gewicht van de pinguïns uit hun vinlengte (<em>N</em> = 342). Elke millimeter vin ging samen met 49.69 gram meer gewicht, <em>b</em> = 49.69, <em>SE</em> = 1.52, 95% CI [46.70, 52.67]. Het model dekte ruim driekwart van het verschil in gewicht, <em>R</em>² = .76.</p>
</blockquote>
<p>Let op de kleine lettertjes.</p>
<ul>
<li>Cursief gaat wat zélf een waarde draagt: <em>N</em>, <em>b</em>, <em>SE</em>, <em>R</em>². De woorden eromheen staan rechtop — juist zó zie je wat APA schuin zet.</li>
<li><code>95% CI</code> blijft <strong>rechtop</strong>, want die letters benoemen alleen wat er tussen de haken staat; ze dragen zelf geen getal. Er staat een spatie tussen de grenzen, geen koppelteken.</li>
<li><em>R</em>² krijgt <strong>geen nul vóór de punt</strong>: .76, niet 0.76. Die maat kan niet voorbij de 1, dus die nul heeft niets te melden. De helling <em>b</em> = 49.69 kan dat wél, en houdt zijn nul dus gewoon — zie de <em>SE</em> van 0.02 hieronder.</li>
<li><strong>En hier moet je SPSS níét naschrijven.</strong> SPSS laat de nul vóór de punt <em>overal</em> weg: bij <em>R Square</em> (<code>.759</code>), maar net zo goed in de kolom <em>B</em>, waar je <code>.01528</code> ziet staan. Bij <em>R Square</em> valt dat toevallig samen met de APA-regel; bij een helling is het gewoon fout, want die kan wél voorbij de 1. Het programma volgt dus geen regel, het strookt zijn getallen. Zet die nul zelf terug waar hij hoort.</li>
<li>Twee decimalen, overal — ook waar het scherm er meer gaf. SPSS toonde .759; in je zin staat .76.</li>
<li>Verleden tijd: je vertelt wat je gedaan en gevonden hebt.</li>
<li>En hij noemt de steekproef, de uitkomst én de voorspeller, zodat je hem uit deze opdracht kunt tillen en hij nog klopt.</li>
</ul>
<p>Eén ding dat je hier bewust <em>niet</em> schrijft: <strong>“vinlengte voorspelt gewicht”</strong> als kale bewering, alsof de pijl in de pinguïns zit. Hij zit in je vraag. Wat je opschrijft is wat je gedaan hebt.</p>
<p>Jouw beurt: schrijf zo’n zin voor de snavellijn uit de eindopdracht (<em>b</em> = −0.09, <em>SE</em> = 0.02, 95% CI [−0.12, −0.05], <em>R</em>² = .06, <em>N</em> = 342). En zet er de zin bij die je in de vorige oefening leerde schrijven — die over de drie soorten. Zonder die tweede zin staat er iets wat niet waar is.</p>
</div>
</div>
<div class="boekvorm" data-w="W4">
<p>◠ <strong>Zelfde vorm in het boek</strong></p>
<p>Hier: de lijn getrokken en gelezen, en de proef die laat zien dat er een richting gekozen is.</p>
<p>In het boek: <strong>W4 — Hangen ze samen?</strong></p>
<p><em>Daar krijgt de lijn zijn twee getallen en zijn brug naar r; hier merk je wat er gebeurt als je de vraag omdraait — en wat het intercept betekent op een plek waar niemand woont.</em></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../20_blokken/blok_correlatie_scatterplot.html" class="pagination-link" aria-label="Oefening 4.1 · Correlatie en scatterplot">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Oefening 4.1 · Correlatie en scatterplot</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../20_blokken/blok_residuen.html" class="pagination-link" aria-label="Oefening 4.3 · De residuen bekijken">
        <span class="nav-page-text">Oefening 4.3 · De residuen bekijken</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script data-goatcounter="https://countcamp.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<button id="toc-toggle" onclick="document.documentElement.classList.toggle('toc-weg'); this.textContent=document.documentElement.classList.contains('toc-weg')?'☰ inhoud':'⌫ verberg inhoud';">⌫ verberg inhoud</button>




</body></html>